tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java

CLDR-14811 fix LDML2Json for reading bcp47 dtd, add test

---

common/segments/root.xml

using unicodetools/.../Segmente……r.java
CLDR-14984

CLDR-14984 A23.52 Update the segments

---

common/dtd/ldmlSupplemental.dtd

CLDR-14801 v40 BRS §A40: DTD for Unicode 14.0.0

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/UnCodes.txt

CLDR-15003 v40 BRS §A14: UN Codes

---

common/annotations/en.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-14984 BRS A19 Fix emoji tickets, more uniform uppercase

---

common/annotations/de_CH.xml
common/annotations/sr_Latn_BA.xml
common/main/sr_Latn.xml
common/main/yo_BJ.xml

CLDR-14969
Two commits for ease of review. Second commit is a workaround for a tool issue, CLDR-15006

CLDR-14969 v40 BRS§A21 algorithmic locales

---

common/annotations/en.xml

CLDR-14984
Add 'bathroom' and 'toilet' as suggested in review.

CLDR-14984 A19 Emoji tickets P2

---

CONTRIBUTING.md
README.md
readme.html

CLDR-14976
Update the CLDR site links in various top-level CLDR doc files (md and html).
In readme.html, update data and CLDR status.

CLDR-14976 update CLDR site links, readme status & date

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_bcp47.txt

CLDR-14571
Generated directory structure:
```
cldr-bcp47
├── bcp47
│  ├── calendar.json
│  ├── collation.json
│  ├── currency.json
│  ├── measure.json
│  ├── number.json
│  ├── segmentation.json
│  ├── timezone.json
│  ├── transform-destination.json
│  ├── transform-hybrid.json
│  ├── transform-ime.json
│  ├── transform-keyboard.json
│  ├── transform-mt.json
│  ├── transform-private-use.json
│  ├── transform.json
│  └── variant.json
├── bower.json
├── LICENSE
├── package.json
└── README.md
```

CLDR-14571 Add bcp47 RunType to Ldml2JsonConverter

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java

CLDR-14989 Speedup GenerateProductionData

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrItem.java
tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrNode.java
tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt

- example JSON paths
keyword.t.io.handwrit._description
keyword.u.ms.metric._since
CLDR-14571

CLDR-14571 json: improve bcp47

---

tools/scripts/ansible/backup-db-playbook.yml

-Change backup starting time to one hour earlier
CLDR-14931
This ticket will be completed when this PR has been merged and then backup-db-playbook.yml has been run.

CLDR-14931 Change timing of automatic Survey Tool database backups

---

.github/workflows/build-icu.yml

CLDR-14989 GitHub Action to build ICU with CLDR

---

.github/workflows/build-icu.yml
.github/workflows/commit-checker.yml
.github/workflows/maven.yml
.github/workflows/production.yml
CONTRIBUTING.md
README.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35.md
readme.html
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareFilesBetweenReleases2.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateTransformCharts.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
tools/scripts/ansible/cldr-apps-playbook.yml
tools/scripts/ansible/templates/deploy-sh.j2
tools/st-prom-exporter/README.md

CLDR-14547
NOT for v40, this is landing into v41

CLDR-14547 master→main

---

common/properties/segments/GraphemeBreakTest.html
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java

CLDR-14801
Sync with last-minute HTML fixes for Unicode 14.

CLDR-14801 remove lastModified.js, use https

---

docs/ldml/tr35-keyboards.md
keyboards/README.md
keyboards/dtd/ldmlKeyboard.dtd

- Inform people that the Keyboard SC is at work
- Mention CLDR-15034
CLDR-15003

CLDR-15003 Keyboards: Add a note to TR35§7

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java

This just cherry-picks a commit for CLDR 40 from main to maint/maint-40 branch
(cherry picked from commit 56ca5d563cf57990a7598f570cb9be51956cb9de)
CLDR-14877

CLDR-14877 Coverage Progress Bars (#1469)

---

.github/workflows/build-icu.yml

CLDR-14989
cherrypick from #1488 to avoid a split ticket

CLDR-14989 GitHub Action to build ICU with CLDR (#1488)

---

readme.html

CLDR-14976 update readme for beta

---

docs/ldml/tr35.md

CLDR-14628 obsolete references removed

---

tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/package-lock.json

CLDR-14656
Review Note: See draft output at: https://corp.unicode.org/~srloomis/tr35draft/dist/tr35.html

CLDR-14656 WIP tr35

---

docs/ldml/tr35-general.md
docs/ldml/tr35.md

CLDR-14676 Allow formatting currencies as parts of units of measurement

---

docs/ldml/tr35.md

CLDR-13729 document reasons for alphabetical order among variants

---

docs/ldml/tr35-info.md

CLDR-14684 missing DTD line in spec

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java

-New enum VoteLoadingContext instead of boolean resolveMorePaths
-Refactor loadVoteValues per old TODO comments (move readonly check and doStampAndListen code to the callers)
-New subroutine getFullPathWithResolver, to shorten loadVoteValues
-Change some methods/classes from public to private
-Fix some deprecation warnings, use logger
-Remove dead code (aliasOf)
-Comments
CLDR-14945

CLDR-14945 Refactoring and comments

---

docs/ldml/tr35.md

CLDR-14629 fix ordering of locale aliases

---

docs/ldml/tr35-info.md

CLDR-14712 define nan handling

---

tools/cldr-apps/js/src/esm/cldrVote.js

-In cldrVote.wireUpButton listen for change, not click; then only handle if checked has become true
CLDR-15112

CLDR-15112 Clicking the Abstain/Vote button should have no effect if already selected

---

tools/cldr-apps/js/src/views/MainHeader.vue
tools/cldr-apps/js/test/TestCldrErrorSubtypes.js
tools/cldr-apps/js/test/mockup.html
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/webapp/WEB-INF/tmpl/st_footer.jsp
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckQuotes.java

-Change some links from sites.google.com to cldr.unicode.org
-TODO comment where I could not find new page
-Remove defunct bugFeedbackUrl for legacy st_footer.jsp
CLDR-15080

CLDR-15080 Fix broken links for Survey Tool instructions at sites.google.com

---

common/transforms/Ethiopic-Braille-Amharic.xml

CLDR-15102 Restoration of human readable labels

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyBulkClosePosts.java

-Remove conn.commit since getDBConnection became getAConnection in PR 1236
-Fix deprecation warnings for logger
CLDR-15150

CLDR-15150 Fix autocommit error in Bulk Close Posts

---

tools/pom.xml

-Update com.google.guava:guava:jar:30.1-jre to version 31.0.1-jre
-Update com.google.code.gson:gson:jar:2.8.6 to version 2.8.9
CLDR-15155

CLDR-15155 Update to latest version of guava and gson libs (v41)

---

tools/cldr-apps/js/src/esm/cldrStatus.js
tools/cldr-apps/js/test/mockup.html

-On the front end, prohibit # = U+0023 NUMBER SIGN in id
CLDR-15156

CLDR-15156 Avoid getting stuck, Waiting for the SurveyTool to start up

---

README.md
common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
pom.xml
readme.html
tools/cldr-apps/pom.xml
tools/cldr-code/pom.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-15137
SBRS 41: Update versions (in DTDs, pom.xml files, and CLDRFIle GEN_VERSION); update readme; update ICU4J libs to release-70-1 version.

CLDR-15137 SBRS 41: update versions, readme, ICU4J libs

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15141 add rohingya lc

---

tools/cldr-apps/js/src/esm/cldrProgress.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/ProgressMeters.vue

- externalize progress messages
- improve c'tor in the default situation
CLDR-15161
minor…

CLDR-15161 ui improvements to progress ui

---

tools/cldr-apps/js/src/esm/cldrProgress.js

-Change cldrProgress.USE_NEW_PROGRESS_WIDGET from false to true
CLDR-15056

CLDR-15056 Coverage Progress Bars USE_NEW_PROGRESS_WIDGET true

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-15163 Create proposed update for V41 spec

---

.github/workflows/maven.yml

CLDR-15177 v41 BRS move to -z BUILD

---

.github/workflows/maven.yml
common/supplemental/units.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNew.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/SubmissionLocales.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/chart_messages.html
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java

CLDR-15165
Notes:
I'll need to test this on SmokeTest before knowing whether everything works.
1. The changes to units.txt are to make additional measures have the systems = metric. Note that 'metric' is interpreted broadly, as measures that metrric countries use, so it includes measures that not formally metric (eg week). And that US and UK systems also use metric for many measures (eg minutes).
2. This includes changes to enable limited submission: CheckCLDR, SubmissionLocales and TestCheckCLDR
3. ExampleGenerator is enhanced to show examples of both correct and incorrect uses of minimal pairs. TestExampleGenerator and GrammarInfo are updated for that change. 
4. There are minor changes to GenerateAllCharts and ShowLocaleCoverage and chart_messages to make it easier to view some …

CLDR-15165 v41 units

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15180
Update locales.txt with 3 new locales for Google

CLDR-15180 Update locales.txt with new locales

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-Do not try to import old votes in locale und or root
-Encapsulate with new function SurveyAjax.skipLocForImportingVotes
-Also skip loc if getInstance(loc) returns null
CLDR-15178

CLDR-15178 Auto_import internal server error

---

tools/cldr-apps/js/src/esm/cldrProgress.js
tools/cldr-apps/js/src/esm/cldrTable.js

-Skip row if json.canModify is false or statusAction.vote is false
-Comments
CLDR-15056

CLDR-15056 Coverage Progress Bars, bug fix for Section rows

---

common/main/am.xml
common/main/az.xml
common/main/bn.xml
common/main/cs.xml
common/main/da.xml
common/main/fi.xml
common/main/hi.xml
common/main/hy.xml
common/main/mr.xml
common/main/ro.xml
common/main/sl.xml
common/main/uk.xml
common/main/uz.xml
common/supplemental/grammaticalFeatures.xml

CLDR-15165
This is the first set of corrections based on the survey. There are queries out to reviewers for the next set.
The details of dispositions are in column K "Status"

CLDR-15165 refine minimal pairs and grammar 1

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-New BallotBox.VOTE_IS_AUTO_IMPORTED serves as special flag for voteForValue method
CLDR-15192

CLDR-15192 Auto-import votes should not generate automatic forum post entries

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Refactor FileInfo in preparation for extending it to gather voter progress stats
-VettingViewer.FileInfo.getFileInfo was 167 lines and had 8 parameters
-Shorten long methods by creating new subroutines
-Reduce parameters by means of constructor parameters and setter methods
-Change some local variables/parameters to instance variables
-Format VettingViewer.java using Eclipse
CLDR-15056

CLDR-15056 Coverage Progress Bars, refactor VettingViewer.FileInfo

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-15165
Previous PRs added contrasting examples for minimal pairs; this adds them for the units in different case forms.
There is a bit of refactoring also, partly for clarity, partly to be able to have 2 locales among the tests.
Also, some of the 'informational warnings' are now under an environment flag to avoid clutter in the tests.

CLDR-15165 add contrasting case examples for units

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Avoid using an entire FileInfo to combine counters from multiple locales for Priority Items Summary
-New class VettingCounters with only the parts of FileInfo needed for combining counters
CLDR-15056

CLDR-15056 Coverage Progress Bars, refactor VettingViewer again

---

common/main/ne.xml
common/main/sk.xml
common/main/sv.xml
common/supplemental/grammaticalFeatures.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-15165 2nd batch from minimal review

---

common/main/ar.xml
common/main/da.xml
common/main/fr.xml
common/main/he.xml
common/main/kn.xml
common/main/lv.xml
common/main/no.xml
common/main/sk.xml
common/supplemental/grammaticalFeatures.xml

CLDR-15165 3rd batch from minimal review

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Consistently use underscore, not space, for English_Changed in json
-Encapsulate the underscore version as Choice.jsonLabel
CLDR-14852

CLDR-14852 Dashboard English_Changed issue: fix duplicate button bug

---

common/supplemental/grammaticalFeatures.xml

CLDR-15165 disable ml grammar for this cycle

---

tools/cldr-apps/js/src/views/DashboardWidget.vue

-Encapsulate with a new method canBeHidden
CLDR-14007

CLDR-14007 Disallow Dashboard hiding of Error and Missing

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-New order: Error, Missing, Provisional, Disputed, Losing, Warning, English Changed, Changed
-Format more consistently
CLDR-15179

CLDR-15179 Move Missing in Dashboard

---

tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrProgress.js
tools/cldr-apps/js/src/views/DashboardWidget.vue

-Only write Error ... if there was an error in the server response; else just Please ...
-Format js and vue by running sh tools/cldr-apps/js/test/pretty.sh
CLDR-14845

CLDR-14845 Non-understandable error message in Dashboard

---

tools/cldr-apps/src/main/liberty/config/server.xml

set to at least 1.8
CLDR-14926

CLDR-14926 st: update server.xml jdkSourceLevel

---

common/annotations/dsb.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java

CLDR-15196 common order for grammatical features

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java

CLDR-15196 order for grammatical features 2

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Call System.out.println, not System.err.println, unless it is an error
-Make some debugging output conditional on DEBUG or DEBUG_THREADS
-Move an URL to CLDRURLS.PRIORITY_SUMMARY_HELP_URL
-Call ph.shouldHide slightly sooner to avoid wasting time
-Move some code into a new subroutine recordEnglishChanged
-Fix deprecation warning for SurveyLog.logException
-Employ existing method getChoiceSetForOrg instead of duplicating code
-Make private where possible
-Formatting
-Comments
CLDR-14925

CLDR-14925 Preliminary clean-up for snapshot of Priority Items Summary

---

common/supplemental/grammaticalFeatures.xml

-Update grammaticalFeatures.xml to include nn
CLDR-15212

CLDR-15212 Open nn for v41

---

tools/cldr-apps/js/src/esm/cldrAjax.js
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java

-Use HeaderParam(Auth.SESSION_HEADER) instead of ss parameter for api/summary
-Revise cldrAjax.doFetch to set session header even if other headers are already present
-Simplify getVettingViewerOutput, rename it getPriorityItemsSummaryOutput
-Remove dead code, unused parameters
-Make private where possible
-Comments
CLDR-14925

CLDR-14925 Preliminary refactor for snapshot of Priority Items Summary

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java

-Remove more dead code in VettingViewerQueue.java
-Improve description in Summary.java
CLDR-14925

CLDR-14925 Preliminary refactor again for snapshot of Priority Items Summary

---

tools/cldr-apps/js/src/esm/cldrErrorSubtypes.js
tools/cldr-apps/js/src/esm/cldrLocaleMap.js
tools/cldr-apps/js/src/esm/cldrXpathMap.js
tools/cldr-apps/js/test/TestCldrErrorSubtypes.js

these needed to have the prettier run on them.
CLDR-15224

CLDR-15224 re-run prettier

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STUsersChoice.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Move Dashboard-specific code in VettingViewerQueue.java to new Dashboard.java
-Move STUsersChoice into new STUsersChoice.java
-Move getChoiceSetForOrg into VettingViewer.java
CLDR-14925

CLDR-14925 Preliminary organizing for snapshot of Priority Items Summary

---

.github/workflows/exhaustive.yml

CLDR-8865
- This adds a manual button
- … and also runs weekly Tuesday mornings (so that the results will be ready to review Wednesday)

CLDR-8865 run exhaustive weekly, add a button for manual

---

tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/DashboardWidget.vue

-Also fix the fallback: change humanize to this.humanize
CLDR-14047

CLDR-14047 Dashboard add description for Choice.warning

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java

CLDR-15161 LocaleCompletion: (3rd meter) code cleanup

---

tools/cldr-apps/js/src/views/GeneralInfo.vue

- The code referenced had been deleted.
- See CLDR-15254 for further cleanup
CLDR-14703

CLDR-14703 Remove unneeded comment in GeneralInfo.vue

---

common/main/en.xml

CLDR-13271 piso to peso for PHP in en.xml

---

tools/cldr-apps/js/src/esm/cldrProgress.js

CLDR-15270 remove locale message from progress bar text

---

docs/ldml/tr35-general.md

CLDR-15247 Adding invariants to list patterns

---

tools/cldr-apps/js/src/esm/cldrForum.js

-Replace non-existent params.special.showError with inline error message
-Two new subroutines loadBad and loadOk
CLDR-15275

CLDR-15275 ST forum stuck on loading if user lacks permission

---

.github/workflows/maven.yml

CLDR-15291
First step before checking in XML

CLDR-15291 BRSv41§A03: -z FINAL_TESTING

---

common/main/yo.xml

CLDR-15291 BRS v41§A03 fix yo

---

common/main/sat.xml
common/main/sw.xml
common/main/uz.xml
seed/main/nqo.xml

CLDR-15291 BRS v41§A03 fix others

---

common/main/sat.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-15291
Note that the TestUnit items are turned into warnings. Those are deliberate, because those warnings require some research to address. The following ticket is to make the necessary adjustments:
https://unicode-org.atlassian.net/browse/CLDR-15295

CLDR-15291 fix example generator and units

---

common/main/en_MV.xml
common/supplemental/supplementalData.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt

CLDR-15044
Add en_MV (with parent en_001), update lang-pop data for MV Maldives

CLDR-15044 Add locale for en_MV (inherits from en_001), update lang-pop data for MV

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

- Some organizations have vetters assigned but hadn’t updated Locales.txt
- The valid locale assignments have been added
CLDR-15277

CLDR-15277 Update Locales.txt to reflect vetter assignments

---

seed/annotations/hi_Latn.xml
seed/main/hi_Latn.xml

CLDR-15271 hi-Latn values

---

seed/main/co.xml

CLDR-13062
Corsican (co) aux exemplars: change ǔ to û (e.g. for French words in Corsican)

CLDR-13062 co aux exemplars: change ǔ to û

---

common/main/hi.xml
common/main/kok.xml
common/main/mr.xml
common/main/ne.xml

CLDR-11864
For **hi**, **mr**, **ne**, **kok**: Move 0944 from main to aux exemplars.

CLDR-11864 hi,mr,ne,kok: move 0944 from main to aux exemplars

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java

CLDR-15276 update exception for hi_Latn inheritance

---

common/rbnf/it.xml

CLDR-15154
I reviewed that the contribution round-trips with the Number Format Tester. The requested form is a typical inflection pattern for Italian.

CLDR-15154 Italian ordinal rules should support plural rendering

---

common/rbnf/es.xml
common/rbnf/es_419.xml

CLDR-15067 Spanish digit rules for ordinals need the plural forms

---

common/supplemental/supplementalData.xml
seed/main/hi_Latn.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java

CLDR-15276
Update hi_Latn inheritance to en_IN
[ ] This PR completes the ticket.

CLDR-15276 Update hi_Latn inheritance

---

common/supplemental/supplementalData.xml

Changed weekend start and end for AE to reflect the Monday to Friday working week changes.
CLDR-15309

CLDR-15309 AE working week change

---

tools/cldr-code/src/main/java/org/unicode/cldr/draft/FileUtilities.java

CLDR-15323 Fix fileutilities for Windows

---

common/main/uz.xml

CLDR-15291 check in additional fixes

---

common/annotations/hi_Latn.xml
common/annotations/my.xml
common/main/en_ZA.xml
common/main/hi.xml
common/main/hi_Latn.xml
common/main/kea.xml
common/main/kok.xml
common/main/mr.xml
common/main/ne.xml
common/main/root.xml

CLDR-15339 CLDRModify

---

CONTRIBUTING.md
README.md
readme.html
tools/pom.xml
unicode-license.txt

CLDR-15328
Update to current ICU4J libs; update readme to indicate current status; update copyright on top-level docs including licenses.

CLDR-15328 for alpha1: update ICU4J libs, readme, copyright dates

---

common/main/ml.xml
common/main/ur_IN.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java

CLDR-12028 modify tests for compliance and fix data as nec.

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/TablePrinter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java

CLDR-15297 generate coverage charts for v41

---

common/transforms/my-t-my-d0-zawgyi.xml
common/transforms/my-t-my-s0-zawgyi.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java

CLDR-14854 Update CLDR with latest Myanmar converters from github Google Myanmar Tools

---

common/main/sr_Latn.xml

CLDR-15339 v41 BRS generate algorithmic locale(s)

---

tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrProgress.js

-Per TODO, refresh LocaleMeter even if it is already set, once per minute
-Delete dead/legacy code in cldrProgress.js and cldrGui.js
CLDR-15056

CLDR-15056 Coverage Progress Bars, finishing touches

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveySnapshot.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveySnapshotMap.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Minor Java refactoring as suggested/facilitated by IntelliJ
CLDR-14925

CLDR-14925 Priority Items Summary, minor Java refactoring

---

common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlPlatform.dtd

- copyright change only and some formatting
CLDR-15366

CLDR-15366 v41 BRS GenerateDtd

---

.github/workflows/exhaustive.yml

CLDR-8856
Before closing this ticket for v41, add cldr-archive checkout.

CLDR-8865 build(exhaustive): checkout cldr-archive

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/UnCodes.txt

CLDR-15366 BRS v41 update UN codes

---

readme.html
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/pom.xml

CLDR-15328
- [] This PR completes the ticket.
1. Update to latest version of ICU4J libs (which are finally marked version 71)
2. Update readme date and stage
3. Address leftover comment from [PR-1761](https://github.com/unicode-org/cldr/pull/1761)

CLDR-15328 for alpha3: update ICU4J libs, readme, PR-1761 comments

---

common/bcp47/currency.xml
common/main/en.xml
common/supplemental/supplementalData.xml
common/validity/currency.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml

- VED new, but transitional.
https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl_currency_iso_amendment_170.pdf
CLDR-15366

CLDR-15366 BRS v41 currency codes

---

common/annotations/dsb.xml

CLDR-15379
In dsb, add missing tts annotation for doctor (have the keyword annotation).
Filed [CLDR-15388](https://unicode-org.atlassian.net/browse/CLDR-15388) to dd a test that detects this kind of problem.

CLDR-15379 dsb, add missing tts annotation for doctor

---

readme.html
tools/pom.xml

CLDR-15328
Update ICU4J libs in CLDR again, to pick up many ICU BRS updates that came in over the last day. Also updated readme date.

CLDR-15328 for alpha4: update ICU4J libs again, updated readme date

---

tools/cldr-code/src/main/java/org/unicode/cldr/draft/FileUtilities.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java

CLDR-15366
- Still write to Generated for supplementaldata and likely subtags,
but copy into the repository when done.
Related to CLDR-14120

CLDR-15366 make GenerateMaximalLocales write in-place [v41]

---

common/supplemental/likelySubtags.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ConvertLanguageData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java

- add more exceptions to GenerateMaximalLocales to match current likelies
- minor updates to likely subtags
- GenerateMaximalLocales less noisy by default, easier to see issues
- ConvertLanguageData less noisy by default, updates files in-place
(Related to CLDR-14120)
CLDR-15366

CLDR-15366 BRS v41 LikelySubtags and tools

---

.github/workflows/build-icu.yml
.github/workflows/exhaustive.yml
.github/workflows/maven-release.yml
.github/workflows/maven.yml
.github/workflows/production.yml
tools/pom.xml

CLDR-14311
Bump to JDK 11.  To be landed in CLDR v42

CLDR-14311 use JDK11 for build [v42]

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
Note that this would be API internal to CLDR.

CLDR-15404 Person names draft api

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404 Adjust code to use en.xml

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
Note that this simplifies the test code a lot.

CLDR-15404 Add string convenience methods, and validity checks

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Count locales in VettingViewer only, to encapsulate and fix discrepancies with VettingViewerQueue
-New VettingViewer.getLocaleCount, getSortedNames
-Encapsulate with new NEUTRAL_ORG_LEVEL = Level.COMPREHENSIVE
-Move long HELP_MESSAGE out of function
-Comments
CLDR-15369

CLDR-15369 Priority Items Summary, fix locale count

---

docs/ldml/tr35.md

CLDR-15420 document num&alpha3 codes for CLDR region subtags

---

common/annotations/my.xml

See comments in https://github.com/unicode-org/cldr/pull/1775
CLDR-15385

CLDR-15385 one annotation change in my.xml

---

docs/ldml/tr35.md

CLDR-15116 fix dangling reference marks

---

docs/ldml/tr35.md

CLDR-15378 clarify hybrid locales

---

docs/ldml/tr35.md

CLDR-15378
- Minor change in Hinglish example wording
- Delete duplicate sentence
[x] This PR completes the ticket.

CLDR-15378 Minor wording change in Hinglish example

---

docs/ldml/tr35.md

CLDR-15448
Add new "lw" type value "phrase" to LDML section 3.6 Key/Type Definitions table.
[x] This PR completes the ticket.

CLDR-15448 Add new "lw" type value "phrase"

---

docs/ldml/tr35-info.md

CLDR-15378
* The more extensive bits of Basic were merged into Moderate.
* Some information was removed, now points to the "Core Data" Sites page instead. That way we can keep it updated more easily.

CLDR-15378 revise language on coverage in the spec

---

docs/ldml/tr35.md

CLDR-14927 Explain TZDB links and aliases

---

docs/ldml/tr35.md

CLDR-15115 explain inheritance with multiple variants

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15442 Pick pattern that matches input name better

---

docs/ldml/tr35-numbers.md

CLDR-15305
This is intended to match Robin's recommendations in
https://unicode-org.atlassian.net/browse/CLDR-15305?focusedCommentId=164007
https://unicode-org.atlassian.net/browse/CLDR-15305?focusedCommentId=164028
with a few wording differences.
It also includes one clarifying example from the ticket discussion:
* For example, e = 0 and i != 0 and i % 1000000 = 0 and *+v = 0+* or e != 0..5 is parsed as if it were (e = 0 and i != 0 and i % 1000000 = 0 and v = 0) or (e != 0..5)

CLDR-15305 fix discussion of plural rules

---

tools/cldr-apps/js/src/esm/cldrPriorityItems.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyProgressManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveySnapshotDb.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/SummaryResponse.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-New SurveySnapshotDb.java; json.status.userCanCreateSummarySnapshot
-New table SUMMARY_SNAPSHOTS, with LONGBLOB for json data
-Managers can view snapshots; only Admin can create them
-Org-neutral level for each locale per StandardCodes.getLocaleCoverageLevel
-Move help message to front end; fix it for org-neutral levels; remove bogus instructions link
-Move progress bar from back end to front end Vue; json has message and percent instead of ret
-Revise GUI: only show Stop button when there is something to stop
-Change button label from Refresh to Create New Summary, shown when Stop is not shown
-Minor refactoring; move some string literals out of getPriorityItemsSummaryOutput
-Remove unused method openConsoleProgress
CLDR-15369

CLDR-15369 Priority Items Summary, save in db; manager access; org-neutral

---

docs/ldml/tr35.md

CLDR-15398 Fix mistakes

---

readme.html
tools/pom.xml

CLDR-15461
Update ICU4J in ICU to ICU 71rc; update readme date.

CLDR-15461 for beta2: update ICU4J libs to 71rc, update readme date

---

docs/ldml/tr35-dates.md
docs/ldml/tr35.md

CLDR-13185
Fix the spec example for &lt;appendItems&gt; to use correct request attribute values.

CLDR-13185 spec, fix example for <appendItems>

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-14108
Clarify the description of how to match dateTimeItems to skeletons and to adjust patterns accordingly. Also update copyright dates for all parts.

CLDR-14108 clarify dateTimeItem pattern adjustments; update copyrights

---

tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

- Use package anchor-js to add links to h2 and below
CLDR-15205

CLDR-15205 spec: add an anchor (anchor.js)

---

docs/ldml/tr35.md

CLDR-15453 Document v41 changes in the Modification section

---

docs/ldml/tr35-numbers.md

CLDR-14111 First draft of number range formatting spec

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15469 Improve name pattern parser

---

docs/ldml/tr35.md

See #1785
(cherry picked from commit 5aca9fd2974ed7e2fb1496beffb7ae28c8a92ffa)
CLDR-15398
The spec fix for CLDR-15398 in #1785 was unfortunately made on the main branch. This PR cherry-picks it to maint/maint-41/.

CLDR-15398 Fix mistakes (#1785)

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

CLDR-15470
Merge the 16 spec fixes that have been made on the maint/maint/41 branch (so far) to the main branch.
Note that this includes one spec-related fix which is not in the spec itself: Steven's fix for CLDR-15205 to add 'link' icon.
**Note that this requires special merging, do NOT just click the normal Squash & Merge button. This needs a MERGE COMMIT, which requires going into the admin panel on GitHub, enabling merge commits, performing the merge commit, and then disabling merge commits again from the admin panel.**

CLDR-15470 BRS v41 cherry pick spec fixes from maint/maint-41 to main

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

- any "table caption" is moved to h6 (######)
CLDR-14611
Oops, this will cause #1835 to need an update.

CLDR-14611 spec move captions to h6

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
The main part of this PR is to add the Example Generator. However, in doing so I found that the tests were not being run, so I fixed those.
Notes
* There is a to-do to use the sample person names once those are in en.xml.
* Had to change from using _q to using alt. Simplest was to move the ordering rank into the NamePattern.
* Changed the precedence order to match the DTD. usage before style
* Added some checks for bad data
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
* Removed incorrect .java
* Added test for …

CLDR-15404 Add example generation 2

---

tools/cldr-apps/pom.xml

- Update liberty-maven-plugin version in pom.xml from 3.3.3 to 3.5.1
CLDR-15381

CLDR-15381 Update liberty-maven-plugin version in pom.xml

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15384 Add code to elide literal text around empty fields.

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
Wires up the new sample names data

CLDR-15404 add sample names to examples

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35.md

CLDR-14332
Did not add a notice yet, but fixed links

CLDR-14332 update docs to fix links that were to 'latest'

---

docs/ldml/tr35.md

CLDR-15378
Update language names to match values in Survey Tool.
[X] This PR completes the ticket.

CLDR-15378 Update language names

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java

- expensive operation, clones a CLDRFile (hidden master for data)
CLDR-14543

CLDR-14543 reduce calls to CLDRFile.getUnresolved()

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15384 A few small tweaks to my previous PR.

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- Add finer-grained checks for person name patterns
- Ignore paths with /alias in checks and building from CLDRFile
- Add some utilities to make checking/testing easier
- Refactor out fromPathValue(XPathParts parts, String value), since the same functionality is needed in different places
- Tweak to make verbose output more useful, add debugging printout

CLDR-15404 Add surveytool checks

---

common/main/en.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
1. Adds commas where needed for sorting patterns
2. Adds test for commas

CLDR-15404 fix sorting patterns

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md
tools/scripts/tr-archive/archive.js

CLDR-15470 cherry-pick two more spec fixes from maint-41 to main

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-15503 Update TR35 for CLDR 41

---

docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-numbers.md

CLDR-15484 Fix mistakes

---

docs/ldml/tr35-general.md
docs/ldml/tr35-keyboards.md
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/copy-local-assets.sh
tools/scripts/tr-archive/header.html
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package.json

CLDR-15088
- fix mixed content in html header
- move html header to separate html file
- commented the archive.js generator
- made it so it doesn't download css or gif unnecessarily

CLDR-15088 specs: fix mixed content, improve build

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
* adds examples for nameOrderLocales.
* catches exceptions (trying to figure out why there are smoketest problems)
* change to SimpleNameObject for access to test api
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
* add test api
* test that example generate returns non-null in expected cases
* add test of name samples

CLDR-15404 More tests and examples

---

README.md
common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
pom.xml
readme.html
tools/cldr-apps/pom.xml
tools/cldr-code/pom.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-15532
For SBRS v42: In cldr repo update CLDR version, ICU4J libs, readme version/status

CLDR-15532 SBRS v42: Update CLDR version, ICU4J libs, readme version/status

---

.github/dependabot.yml

CLDR-15319
fyi @gnrunge and @markusicu  - since there's a similar issue open for ICU!

CLDR-15319 build: dependabot file

---

.github/dependabot.yml

- followon to #1893
- prefix must be ≤15 chars
CLDR-15319

CLDR-15319 build: dependabot file update

---

.github/dependabot.yml

CLDR-15319 build: dependabot should run monthly

---

tools/cldr-code/src/test/java/org/unicode/cldr/test/TestExampleGenerator.java

CLDR-15538 test for ExampleGenerator

---

tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/MainMenu.vue
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/js/test/Test.html
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-For snapshots, include only locales in SubmissionLocales.CLDR_LOCALES
-Fix snapshot schedule in case server is started between midnight and 1:00 AM
-Remove the word slow from the menu item
-Automatically show the most recent summary snapshot
-Display controls below the summary rather than above it
-Unrelated formatting change for Test.html (forgot to run prettier for favicon PR)
CLDR-15369

CLDR-15369 Priority Items Summary snapshots, improvements

---

.github/workflows/maven.yml

CLDR-15556 v42 consolecheck to BUILD

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java

- indicate which DTD type failed to read
- indicate whether an illegal annotation was on an ELEMENT or an ATTLIST (i.e. @MATCH on an ELEMENT!)
- indicate the name of the element / attribute
CLDR-15558

CLDR-15558 DtdData err msg improvements

---

tools/cldr-apps/src/test/java/org/unicode/cldr/web/api/TestLocaleCompletion.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java

CLDR-15556 v42 SBRS disable limited submission

---

common/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
common/main/root.xml
Change values in root to be 'empty' so that the tests force people to come up with their own
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
Add a new test, and new test failure type
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
Add a new check that will be run in the survey tool
* checks which sample names have to have certain field values
* checks which sample names have to not have certain field values
* checks that if surname2 is present, surname has to be
* checks that all multiword values have to have a space
* 
Add constant ALL for the SampleTypes
Add to interface new public getModifiedFieldToValue(); so we can access …

CLDR-15404 add checks and tests

---

common/main/en.xml

CLDR-15363
Update QAR Currency display name

CLDR-15363 Update QAR Currency display name

---

common/main/hi_Latn.xml

CLDR-15515
Remove underscore Santo_Domingo

CLDR-15515 Remove underscore Santo_Domingo

---

tools/pom.xml

- 05df9b956232994f12e2c105caca5e60ea77d9ee
CLDR-15571
looks like #1933 broke something in zawgyi… investigating, but getting this in to unbreak smoke

CLDR-15571 revert #1933 maven-shade-plugin

---

tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/AboutPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyLog.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/About.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestMisc.java
tools/cldr-code/pom.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Main.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRConfig.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRPaths.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java

-For the About panel, links to commit, compare release, and compare main
-Construct links in js instead of java; configurable in cldrText.js
-Most of the changes are to fix bugs that blocked this minor GUI change
-Do not assume cldr-apps.war has a hash, since liberty:package drops it
-Two hashes: Data and Code, where Code refers to cldr-code.jar
-For cldr-code, use the name Code consistently, not (Java) Tools, UTILITIES, etc.
-Encapsulate string literals with new constants such as CldrUtility.CODE_SLUG
-Remove deprecated and dead code such as getCurrevCldrApps, setCldrAppsHash
-Fix some minor compiler warnings
-Comments
CLDR-13843

CLDR-13843 Change the About panel github links

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15404
Made the changes noted earlier. That exposed one issue that we will need to talk about; left a TODO in the file for it.

CLDR-15404 fix2 for monogram

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java

-Enforce a max duration for auto-snapshot to run: AUTO_SNAP_MAX_DURATION_MINUTES
-Provide constants for time of day including minute: AUTO_SNAP_MINUTE_OF_HOUR
-Set percent to 100 (not 0) when complete successfully
-Refactor with subroutines
-Comments
CLDR-15369

CLDR-15369 Priority Items Summary snapshots, more improvements

---

.github/workflows/codeql-analysis.yml
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveySnapshotDb.java
tools/cldr-code/src/main/java/org/unicode/cldr/draft/CharacterListCompressor.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LanguageInfo.java

CLDR-15319
While doing dependabot, GitHub suggested CodeQL analysis which is in a similar tab. This will report any issues to us.
I updated the suggested action script to use our own maven build.

CLDR-15319 build: CodeQL Analysis

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-For efficiency, skip unused getHidden and voterProgress for single-path dash
-New DashboardArgs.isOnlyForSinglePath
-Minor refactoring of parameters, subroutines, accessor methods
-Fix bug in setUserAndOrganization, parameter names vs field names
CLDR-14906

CLDR-14906 Retain Dashboard hidden status across releases

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-15597 Create Draft TR35

---

common/supplemental/coverageLevels.xml

CLDR-15405
Remove coverage restrictions that limited personName submissions to certain languages.

CLDR-15405 Remove personName coverage restrictions to certain languages

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

Added/Updated to moderate: xh in Google and Cldr items
Added/Updated to modern: hi_Latn in Google and Cldr items
Updated from basic to moderate: pcm in Google and Cldr items
CLDR-15598

CLDR-15598 Update Google coverage in Locales.txt

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

Update locales.txt for Apple for v42 support
- Adding kk, bg, mi ⇒ Modern
- Adding: cv ⇒ basic
- Fix minor formatting issues
CLDR-15598

CLDR-15598 Update locales.txt for Apple v42

---

common/supplemental/supplementalMetadata.xml
seed/main/bho.xml
seed/main/bho_IN

CLDR-15615
Add core date for new locale Bhojpuri (bho)

CLDR-15615 Add new locale Bhojpuri (bho)

---

common/main/en.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15637
Update en.xml personNames/sampleName with matching surname and surname-core.

CLDR-15637 update sampleName surname-core

---

common/supplemental/supplementalMetadata.xml
seed/main/raj.xml
seed/main/raj_IN.xml

CLDR-15617
Add Core data for Rajasthani (raj)

CLDR-15617 Rajasthani (raj) Core Data

---

tools/cldr-apps/js/src/esm/cldrDeferHelp.js
tools/cldr-apps/js/src/esm/cldrInfo.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-apps/src/main/webapp/css/redesign.css

- also add to Row payload
- also add to ("new") Vote API
CLDR-13963
Image example:
(though, we can tweak the style if desired, in this or a future PR)

CLDR-13963 show placeholders in info panel

---

tools/cldr-apps/js/src/esm/cldrDeferHelp.js
tools/cldr-apps/js/src/esm/cldrForum.js
tools/cldr-apps/js/src/esm/cldrInfo.js
tools/cldr-apps/js/src/esm/cldrText.js

-New message added to the Submit form, in cldrForum.js and cldrText.js
-Formatting changes in cldrDeferHelp.js, cldrInfo.js, due to unformatted previous commits in #2012 
CLDR-14922

CLDR-14922 Remind user to vote when posting in forum

---

common/main/mdf.xml
common/main/mdf_RU.xml
common/supplemental/supplementalMetadata.xml

CLDR-10952 add mdf Moksha

---

tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java

- don’t setup the registry when not needed
This is to fix `main` failing to build.
CLDR-14766

CLDR-14766 improve startup of TestUserLevel

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java

CLDR-14766 restructure TestUserLevel for stability
- CLDR-15656 for future fix

CLDR-14766 restructure TestUserLevel to avoid problems

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java

- fix typos
- add comments
- remove dead code
CLDR-15653

CLDR-15653 improve LocaleCompletion

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-This affects snapshots, and summaries by Admin
CLDR-15646

CLDR-15646 Priority Items: fix coverage level if orgIsNeutralForSummary

---

tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/api/TestLocaleCompletion.java

CLDR-15662 re-enable TestLocaleCompletion

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java

CLDR-8666
- API for get/set single report completion

CLDR-8666 Report completion: Add an API

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15665
Add VeC as an organization

CLDR-15665 Add VeC as an organization

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java

CLDR-15002
Fixes the supplemental/coverage_goals.html
- Adds 8 vs 4 votes
- focus on TC orgs
- make spreadsheet-friendly.

CLDR-15002 Fix org chart

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java

-The field named stuff must be public since it is referenced by jsp
CLDR-15676

CLDR-15676 Cannot do a bulk upload with the Survey Tool 42

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java

-Move ten CLDRFile.getName functions and related subroutines/data to bottom of CLDRFile.java in preparation for refactoring as separate class
CLDR-13263

CLDR-13263 Constructed-value-related clean-up of CLDRFile

---

common/main/en.xml
common/main/nl.xml
common/main/nl_BE.xml
common/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java

CLDR-15695 remove unnecessary fields; mark nl person-name fields as draft

---

tools/cldr-apps/js/src/esm/cldrText.js

CLDR-15683
Fix link to page about default content

CLDR-15683 Fix link to page about default content

---

tools/cldr-apps/src/main/webapp/META-INF/microprofile-config.properties

- affects report view and votring
- CLDR-15702 to revisit this workaround
CLDR-8666

CLDR-8666 fix the swagger client: broken in smoke/prod

---

common/collation/fy.xml

CLDR-15542 Western Frisian sort order

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java

CLDR-14789
Cleanup turned out to be needed for CLDR-15689

CLDR-14789 fix API, ui for Vetting Participation

---

common/main/en.xml

CLDR-15714 Change the formal sorting for English to use surname -prefix and -core

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java

- also add last_mod field to the vetting participation payload
CLDR-15689

CLDR-15689 add Download XLS page to vetting participation

---

tools/cldr-apps/js/src/esm/cldrProgress.js

-Prevent front end from making too-frequent requests to refresh locale completion
-Remove some dead code
CLDR-15707

CLDR-15707 Survey Tool hangs with a thousand hung threads

---

common/main/en.xml

CLDR-15318
Add alt value for TR territory name

CLDR-15318 Add alt value for TR territory name

---

common/main/en.xml
common/supplemental/supplementalData.xml

CLDR-15353
Outstanding request: renaming "lah" from "Lahnda" to "Western Punjabi"

CLDR-15353 adjust PK language populations

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15687 clean up locales.txt

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

CLDR-15687
1. Make changes for MS
2. Once integrated with the Apple & Google changes
a. Fix the the test that checks for agreement with CLDR Org
b. Make changes in the CLDR Org (Locales.txt) as necessary
Adds a new 'special' org for handling the high-coverage and generated cases.

CLDR-15687 Fix MS changes

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js

- truncate sheet name to avoid 31 char limit
CLDR-15689

CLDR-15689 Download XLS page to vetting participation fix

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

CLDR-15687 Tweak MS locales and clarify warning

---

common/main/en.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java

CLDR-15722
- Add alt for NZ country name
- Make new item appear as missing in all locales.

CLDR-15722 Add alt for NZ country name

---

common/main/en.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java

CLDR-15706 Add Hinglish variant
- Add Hinglish variant
- Make visible in to all languages

CLDR-15706 Add Hinglish variant

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15598
Remove mt from locales.txt for Google and CLDR

CLDR-15598 Remove mt from locales.txt

---

common/rbnf/ru.xml

CLDR-15612 Some rules in OrdinalRules incorrectly have a spellout-ordinal prefix for Russian

---

common/main/en.xml

CLDR-15722
Reverts unicode-org/cldr#2109

CLDR-15722 Revert change NZ Alt to Aotearoa

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15687
Update locales.txt for more accurate stats in priority items based on targeted coverage level.

CLDR-15687 Update locales.txt

---

common/main/gd.xml

CLDR-15760 Add extra person-name patterns for gd

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleCompletionData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/NotificationCategory.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingParameters.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestVettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java

-Move/rename VettingViewer.DashboardArgs to new VettingParameters.java
-Move/rename VettingViewer.Choice to new NotificationCategory.java
-Keep appendDisplay in VettingViewer, not in NotificationCategory
CLDR-15646

CLDR-15646 Refactoring, move two inner classes to top level

---

common/rbnf/kk.xml

These rules have been tested with the [Number Format Tester](https://st.unicode.org/cldr-apps/numbers.jsp) and vetted with Apple's translators.
CLDR-15766

CLDR-15766 Add RBNF for Kazakh (kk)

---

tools/cldr-apps/js/src/esm/cldrReport.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/views/ReportResponse.vue

CLDR-8666
shows an approval status on each report. (can be disputed, etc.)

CLDR-8666 reports: individual report UI

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

- only during SUBMISSION is bulk upload allowed
- minor cosmetic fixes
- added helpful notes
- fixed userguide url
CLDR-15778

CLDR-15778 disallow bulk upload during VETTING

---

tools/cldr-apps/js/src/esm/cldrReport.js
tools/cldr-apps/js/src/views/ReportResponse.vue
tools/cldr-apps/js/src/views/VettingSummary.vue

- hide report response if not logged in
- summary ui with vetting
CLDR-8666
will add spreadsheet download tomorrow

CLDR-8666 Report improvements

---

tools/cldr-apps/js/src/esm/cldrProgress.js
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Revise percent to 99 as specified in the ticket
-Revise both Priority Items Summary (java) and Locale Completion meter (js)
-This is not a logical long-term solution
CLDR-15785

CLDR-15785 Pin the progress at 99 percent if EMP greater than 0

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAccessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15782
- Made some changes for comments in last PR
- Added warning if initialSequence has any non-blanks.

CLDR-15782 code cleanup and added warnings

---

tools/cldr-apps/js/src/esm/cldrReport.js
tools/cldr-apps/js/src/esm/cldrUserListExport.js
tools/cldr-apps/js/src/esm/cldrXlsx.js
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java

- sticky table header
- include counts for each report type
- includes updated spreadsheet
CLDR-8666

CLDR-8666 Report summary: improve view

---

tools/cldr-apps/js/src/esm/cldrPriorityItems.js
tools/cldr-apps/js/src/views/VettingSummary.vue

-Was missing this. in this.canCreateSnapshots
-Debug logging conditional on SUMMARY_DEBUG
CLDR-15646

CLDR-15646 Priority Items Summary, fix bug in last PR; add debug logging

---

CONTRIBUTING.md
docs/requesting_changes.md

CLDR-15805
* Migrate Change request doc to GitHub from Google Sites
* Update links

CLDR-15805 Migrate Change Requests doc to GitHub

---

docs/requesting_changes.md

CLDR-15805
Add requirement that tickets are in English since there may not be a committee member who speaks the language.

CLDR-15805 Add requirement that tickets are in English

---

tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

CLDR-15625 always allow TC to vote for 4/6

---

docs/ldml/tr35-dates.md

CLDR-15791 Fix mistakes

---

common/main/de_AT.xml

CLDR-15049
Revert to match value in Survey tool made after export.

CLDR-15049 revert to match value in Survey tool

---

.github/workflows/maven.yml

CLDR-15837 v42: move tests to FINAL_TESTING

---

common/main/zh.xml

CLDR-15823 zh: translation of Cal is the same as cal

---

common/main/pa.xml
common/main/ta.xml

CLDR-15547 Add back group separator to pa and ta

---

common/main/qu.xml
seed/main/raj.xml

CLDR-15845
Fix some bogus nameOrderLocales

CLDR-15845 remaining cc errors

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java

-Delete erroneous duplicated thread creation
CLDR-15819

CLDR-15819 Fix Priority Items Summary threads

---

.github/COMMIT_METADATA.md

9e15f63e30cadf57b8eee0f6d6c3398263dfcdac CLDR-15470 v41 cherry pick
but had a bad commit message
CLDR-15865

CLDR-15865 another update to COMMIT_METADATA.md

---

common/supplemental/metaZones.xml

CLDR-15518
Add a short metazone ID for the Yukon metazone (restored to use in CLDR 40)

CLDR-15518 add short metazone ID for Yukon metazone (restored in CLDR 40)

---

.github/COMMIT_METADATA.md

CLDR-15865
"Commits with Jira Issue Not Found" goes to zero entries with this PR.

CLDR-15865 update COMMIT_METADATA.md with v41 BRS tasks

---

common/annotations/sv.xml

CLDR-15870 sv typo in light blue heart

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15857
Simplify the code by replacing ParameterMatcher by FormatParameters.
ROUGH CUT for now.

CLDR-15857 simplify person names code

---

common/supplemental/supplementalData.xml

CLDR-11510 fix first day of week for China

---

common/main/ca.xml

CLDR-15599
Add Catalan minimal pair value for many

CLDR-15599 Add Catalan minimal pair value for many

---

common/main/my.xml

CLDR-15858
Revert main exemplar update in my

CLDR-15858 Revert main exemplar update in my

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

- also deprecate CLOSED, DISPUTED, FINAL_TESTING, and BETA
CLDR-15582

CLDR-15582 document SurveyTool.Phase enums

---

common/main/ks_Deva.xml

CLDR-15874
Revert change to decimal separator in ks_Deva

CLDR-15874 Revert change to decimal separator

---

common/supplemental/attributeValueValidity.xml

CLDR-15549 remove duplicate values for blocking items in attributeValueValidity.xml

---

common/supplemental/attributeValueValidity.xml

CLDR-15550
Sort values and remove duplicates for several items in attributeValueValidity.xml (used for internal testing):
- `<attributeValues dtds='ldml' elements='pattern' attributes='type' type='choice'>`
- `<attributeValues dtds='supplementalData' elements='attributeValues' attributes='attributes' type='choice'>`
- `<attributeValues dtds='supplementalData' elements='attributeValues' attributes='elements' type='choice'>`

CLDR-15550 sort values, remove duplicates for several items in attributeValueValidity.xml

---

common/main/en.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-15877
Add English name for bgc

CLDR-15877 Add English name for bgc

---

readme.html
tools/pom.xml

CLDR-15886 BRS v42: Update readme and ICU4J libs before alpha1

---

common/rbnf/root.xml

CLDR-15863 rename zDefault to zz-default (ruleset names should not have uppercase)

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRFileTransformer.java

CLDR-15006 CLDRFileTransformer: preserve ↑↑↑

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestReportStatus.java

CLDR-15765
fix breakage from #2132

CLDR-15765 update calls to obsolete VoteResolver functions

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java

CLDR-15486
[Best to review with Hide whitespace changes]
1. First transforms

CLDR-15486 fix exhaustive errors; transforms

---

common/main/nl.xml
common/main/tk.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java

CLDR-15486
This will (hopefully) fix the remaining exhaustive test failures. Some of these are workarounds, so I filed a different ticket for taking care of them when we have time (https://unicode-org.atlassian.net/browse/CLDR-15894)

CLDR-15486 fix problems in nl, tk, and the tests.

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java

-Add more debug logging dependent on DEBUG being true
-This logging helps to show that when the Stop button is pressed, myThread.interrupt() does not stop the thread
CLDR-15819

CLDR-15819 Fix Priority Items Summary semaphore

---

common/main/bgc.xml
common/main/bho.xml
common/main/raj.xml

CLDR-15897
bgc,bho,raj: Add std time patterns with h, copied from hi. In the longer run this sort of issue should be handled per [CLDR-15901 ](https://unicode-org.atlassian.net/browse/CLDR-15901)

CLDR-15897 bgc,bho,raj: add std time patterns with h, copied from hi

---

common/annotations/de_CH.xml
common/annotations/ha_NE.xml
common/annotations/sr_Latn.xml
common/annotations/sr_Latn_BA.xml
common/annotations/yo_BJ.xml
common/annotations/yue_Hans.xml
common/main/de_CH.xml
common/main/ha_NE.xml
common/main/sr_Latn.xml
common/main/sr_Latn_BA.xml
common/main/sr_Latn_ME.xml
common/main/sr_Latn_XK.xml
common/main/yo_BJ.xml
common/main/yue_Hans.xml

CLDR-15865 BRS v42: Algorithmic Locales

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/UnCodes.txt

- added a trailing newline in the file also
CLDR-15865
only change is the name change for Turkey

CLDR-15865 BRS v42: update UnCodes.txt

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java

-Return true if stop is true in VettingViewerQueue.Task.CLDRProgressCallback.isStopped
CLDR-15819

CLDR-15819 Fix Priority Items Summary threading

---

common/properties/coverageLevels.txt
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocalesTxtReader.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java

CLDR-15903
1. Check in the coverageLevels.txt (which has computed levels)
2. The coverage charts don’t distinguish between the special ‘high-coverage locales' in the cldr org and the normal ones. Add a flag ("‡") to distinguish them.
3. Improve the SearchCLDR.java code to make debugging easier
4. Fix a problem with the Organization:special. It should not have the special handling to add parent language/script. That caused Hindi (hi) to show up as ‘special’.
5. Set Fulah (ff) to moderate for the Organization:special (it should be lower than ff_Adlam to reflect reality
The effects are seen in:
- [locale_coverage.html](https://unicode-org.github.io/cldr-staging/charts/42/supplemental/locale_coverage.html) (once it refreshes)
- [locale_coverage.tsv](https://github.com/unicode-org/cldr-staging/ …

CLDR-15903 fix charts (and related issues)

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDelta.java

CLDR-15892
1. Call DAIP on old data so the comparison ignores DAIP changes
a. Except for certain data, like collation
2. Do better comparison of UnicodeSets

CLDR-15892 charts handle DAIP

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java

CLDR-15884
Note that reviewing is easier with Hide whitespace differences.

CLDR-15884 fix the private paths in CLDR so 'many' works in 'ca'

---

common/rbnf/bg.xml

CLDR-15887 Bulgarian RBNF update

---

common/annotations/en_001.xml
common/main/en_001.xml
common/main/en_GB.xml
common/main/hi_Latn.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareEn.java

CLDR-15908
Update the generation program. Distributed results to TC.

CLDR-15908 Update en_001 (first step)

---

common/segments/root.xml

CLDR-15767 Treat @ as ALetter in WordBreak

---

common/supplemental/pluralRanges.xml
common/supplemental/plurals.xml

CLDR-14634
Make changes as per ticket, dropping many and adjusting one.

CLDR-14634 Adjust Hebrew plural rules

---

common/supplemental/ordinals.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePluralConfirmation.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePluralRanges.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/PluralRulesFactory.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowPlurals.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/WritePluralRulesSpreadsheets.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCompactNumbers.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
tools/pom.xml

CLDR-15446
Instructions to reproduce:
1. Switch to your working copy of ICU, and then...
2. Checkout the [PR #2007](https://github.com/unicode-org/icu/pull/2007) that does the ICU side of work. You can use the [Github CLI tool](https://cli.github.com/) to do this with the command `gh pr checkout 2007`
3. Build the ICU4J jar that also includes CLDR-specific dependencies: `cd icu4j`;  `ant clean`; `ant -noinput releaseCLDR -f build.xml`
4. Give that new jar file a unique testing-specific version number and register ("install") it to your local file system's Maven cache of artifacts (jar files).  For a version string `71.0.1-SNAPSHOT-icu-pr-2007`, we would install it with the proper Maven groupId, artifactId coordinates as:  `mvn install:install-file -Durl=file:repo -DgroupId=com.ibm.icu …

CLDR-15446 Replace FixedDecimal with DecimalQuantity for plural rule samples

---

common/main/en.xml

- ff: Fula
- sah: Yakut
CLDR-13887

CLDR-13887 en: rename ff, sah

---

common/supplemental/units.xml

CLDR-14857 fix light-year, parsec

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-14421
Adds a parser to verify against old code.

CLDR-14421 More tests for unitIdComponent 2

---

common/main/bgc.xml
common/main/bho.xml
common/main/raj.xml
common/main/ti.xml

CLDR-15918 Add raj, bgc, bho, ti values required for Basic coverage

---

common/supplemental/supplementalData.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt

CLDR-15350
Add language population data
Will cause a rerun of #2265
Also related to: CLDR-15922 BRS v42: Languge Script Metadata (#2263)

CLDR-15350 BRS v42 update language population data

---

common/main/mr.xml
common/supplemental/dayPeriods.xml

CLDR-14879 drop evening2 from mr

---

common/supplemental/pluralRanges.xml
common/supplemental/plurals.xml

CLDR-14634
Neglected to reformat after the change. Cleaner to do it on this ticket.

CLDR-14634 adjust hebrew plural rules (reformatted)

---

common/supplemental/plurals.xml

— doesn't change number of categories
CLDR-13413

CLDR-13413 adjust plural rules for locale is

---

common/main/bn.xml

CLDR-15867 changed translation of MO (Macao SAR China) territory

CLDR-15867 changed translation of MO territory

---

common/main/gd.xml

CLDR-13677 ordinals for locale gd

---

readme.html
tools/pom.xml

CLDR-15936
Update ICU4J libs and readme before CLDR release-42-alpha2

CLDR-15936 BRS v42: Update readme and ICU4J libs before alpha2

---

common/main/gd.xml

CLDR-15760
See ticket; remove surname2 in the alt=1

CLDR-15760 update gd name patterns B

---

common/main/gsw.xml

CLDR-15934
Update value of display name of MVR in gws

CLDR-15934 Update value of MVR in gws

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-15931
- Add additional locales to high-coverage locales list which meet the coverage criteria
- Add new HCLs to the special org
- Remove hi_Latn from the special org and add to Google org list

CLDR-15931 Update HCL list in locales.txt

---

common/main/as.xml
common/main/brx.xml
common/main/doi.xml
common/main/gu.xml
common/main/hi.xml
common/main/hi_Latn.xml
common/main/kn.xml
common/main/kok.xml
common/main/ks.xml
common/main/ks_Deva.xml
common/main/mai.xml
common/main/ml.xml
common/main/mni.xml
common/main/mr.xml
common/main/my.xml
common/main/ne.xml
common/main/or.xml
common/main/pa.xml
common/main/pcm.xml
common/main/sa.xml
common/main/sd.xml
common/main/sd_Deva.xml
common/main/te.xml
common/main/ti.xml
common/main/ur.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt

Except for si and ta, which have already been incorporated in other PR
CLDR-15924

CLDR-15924 red fixes from spreadsheet

---

common/main/si.xml
common/main/ta.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt

CLDR-15924 Fix ta and si person names

---

common/dtd/ldml.dtd
common/dtd/ldmlSupplemental.dtd
common/main/si.xml
common/main/ta.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java

CLDR-15924
Mike, please look these over. I tried to get all the items, except that I wanted to make sure we wanted the prefix on formal, even for non-long items.

CLDR-15924 items not picked up in pr2297

---

common/bcp47/measure.xml
common/main/en.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBCP47.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-15933
No PathHeader or PathDescription changes are necessary. Doc changes to follow later.

CLDR-15933 define extension for temperature

---

common/main/en.xml

-Move kelvin after fahrenhe
CLDR-15049

CLDR-15049 BRS: CLDRModify no args, fix sorting of kelvin in en.xml

---

tools/cldr-apps/js/src/esm/cldrProgress.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/test/TestCldrProgress.js
tools/cldr-apps/js/test/index.js

-Revise percent to zero (not 99) for locale meter if more problems than in baseline
-Rename some variables from votes to done, more accurate for locale meter
-Add explanatory comment in flyover (title)
-New unit test for cldrProgress.js
-Comments
CLDR-15785

CLDR-15785 Pin the progress at 0 percent if worse than baseline

---

common/supplemental/supplementalData.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-15962 Update supplementalData's nameOrder

---

common/properties/coverageLevels.txt

CLDR-15865 BRS coverageLevels.txt

---

common/properties/coverageLevels.txt
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java

CLDR-15903 update charts

---

common/supplemental/likelySubtags.xml

CLDR-15921 BRS v42: regen likely subtags

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config.txt

creates packages cldr-personNames-full and cldr-personNames-modern
CLDR-15414
This is temporary, to unbreak the json build.  Format is not optimal.
```json
{
"main": {
"lt": {
"identity": {
"version": {
"_cldrVersion": "42"
},
"language": "lt"
},
"personNames": {
"givenFirst": "und lt",
"surnameFirst": "ko vi yue zh",
"foreignSpaceReplacement": {
"_value": " ",
"_xml:space": "preserve"
},
"initial": "{0}.",
"initialSequence": "{0} {1}",
"referring-length-long-formality-formal-order-givenFirst": {
"namePattern": "{suffix} {prefix} {given} {given2} {surname} {surname2}"
},
"referring-length-long-formality-informal-order-givenFirst": {
"namePattern": "{given} {given2} {surname} {surname2}"
},
"addressing-length-long-formality-formal-order-givenFirst": {
"namePattern": "{suffix} {prefix} …
```

CLDR-15414 json: temporary personnames patch

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java

- in the cldr-core package
- based on coverageLevels.txt
CLDR-15624
Is this the only code that reads coverageLevels.txt?

CLDR-15624 json: add coverageLevels.json

---

docs/ldml/tr35-keyboards.md

CLDR-15034 fix typo in layerMaps

---

common/main/ms.xml

CLDR-15988 ms: nanometer mistakenly translated

---

common/main/az.xml
common/main/bg.xml
common/main/hy.xml
common/main/ka.xml
common/main/kk.xml
common/main/kok.xml
common/main/mn.xml
common/main/sq.xml
common/main/uk.xml
common/main/uz.xml
common/main/xh.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchCLDR.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt

Also make some changes in the tooling to make it easier to generate a modify_config.txt file.
CLDR-15967

CLDR-15967 Upgrade some provisional items. 

---

common/properties/coverageLevels.txt

CLDR-15865
Trying to keep this up to date and in sync with the charts

CLDR-15865 rebuild of coverageLevels.txt

---

common/supplemental/supplementalData.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt

- vec is official_regional in SI and HR based on official documents from VeC
- official documents are linked in this ticket
CLDR-15943

CLDR-15943 supplemental update for vec

---

tools/cldr-apps/src/main/webapp/css/redesign.css

-Delete style in redesign.css that was .data .statuscol (without comma)
-This should have been deleted when statuscol was moved to surveytool.css
CLDR-13837

CLDR-13837 Survey Tool status icons, fix css error

---

seed/main/en_Shaw_GB.xml

CLDR-16006
CLDRModify passes before beta1, just fixes spacing in seed/main/en_Shaw_GB.xml

CLDR-16006 CLDRModify fixes spacing in seed/main/en_Shaw_GB.xml

---

.github/workflows/gh-pages.yml

CLDR-15464
See for example https://cldr-smoke.unicode.org/spec/maint-42/ldml/tr35.html

CLDR-15464 build: post maint branches and releases to smoketest

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java

-Fall back to use LikelySubtags if there are no target territories
-Fall back to use secondary territories if there are no LikelySubtags
-Comments
CLDR-15963

CLDR-15963 Missing country name should show in Dashboard

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-16026 Add stub LDML section for Person Names, link to it from other sections

---

docs/ldml/tr35.md

CLDR-15876 Update parentLocales guidelines and invariants

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/LogicalGroupChecker.java
tools/cldr-code/src/test/java/org/unicode/cldr/test/TestCheckLogicalGroupings.java

-Instead of removing optional paths, skip them for the first (original) condition
-Take optional paths into account for the second (new) condition
-New subsets: presentPaths, optionalPaths
-New methods: checkMissingRequiredPaths, getMissingRequiredPaths, groupIsIncomplete, etc.
-Rename some methods and fields for clarity
-New unit test: testPresentOptionalPlusMissingRequired
-Comments
CLDR-15973

CLDR-15973 Check present optional path and missing required path in one group

---

docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-15626 Document currencyPattern alts alphaNextToNumber,noCurrency and currencyPatternAppendISO

---

docs/ldml/tr35-keyboards.md

- updated docs with naming changes from #2354
- also improved the transform docs, but more to do there
CLDR-15034

CLDR-15034 kbd: doc naming updates from Sep 12/13, 2022

---

tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java

-Change Stopped message to: Completed successfully
-Change Waiting message to: Waiting in line
-Change wording of summary_coverage_neutral
CLDR-15727

CLDR-15727 Priority Items Summary messages

---

docs/ldml/tr35-info.md
docs/ldml/tr35.md

CLDR-15956 Specify relations between the unit preferences data and the locale identifier

---

docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-15609 add sign for sample value syntax

---

docs/ldml/tr35-general.md

CLDR-14875 document the usage of animate and inanimate with gender

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java

CLDR-15002 Update locale coverage chart for v42

---

docs/ldml/tr35-general.md

CLDR-15614 spec: link to OT feature registry

---

docs/ldml/tr35-dates.md

CLDR-15559 the date format item count= not documented

---

docs/ldml/tr35.md

… fixing the spelling, and adding pointer to Unit Conversion and Unit Preferences.
CLDR-15956

CLDR-15956 Incorporate text from #2365

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

- kept .html when referring to network URLs
- also update my email in a couple of places

CLDR-15655 spec v42: update .html to .md in links

---

docs/ldml/tr35-general.md

CLDR-15522
Note the target link is dead, but will fix that.

CLDR-15522 spec: correct link to ULI

---

docs/ldml/tr35-numbers.md

CLDR-15608 Specify ranges of numbers with qualifiers

---

docs/ldml/tr35-dates.md
docs/ldml/tr35.md

CLDR-15613 More info on matching pattern field lengths to requested skeleton field lengths

---

docs/ldml/tr35.md

CLDR-13370
Fix hybrid locales tags and clarify descriptions.

CLDR-13370 Fix hybrid locales tags

---

docs/ldml/tr35-personNames.md

These came up in review, but we weren't able to make the changes before beta.
CLDR-13722

CLDR-13722 refine person names spec algorithms

---

tools/cldr-apps/js/src/esm/cldrDash.js
tools/cldr-apps/js/src/esm/cldrDeferHelp.js
tools/cldr-apps/js/src/esm/cldrInfo.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/esm/cldrVote.js
tools/cldr-apps/js/src/views/CldrRows.vue
tools/cldr-apps/js/src/views/TestPanel.vue
tools/cldr-apps/js/test/data/dash_data.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSubmissionResultHandler.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DefaultDataSubmissionResultHandler.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/Partition.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/PathHeaderSort.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SummarizingSubmissionResultHandler.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathMatcher.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-apps/src/main/webapp/WEB-INF/jspf/stcontext.jspf
tools/cldr-apps/src/main/webapp/tc-mzfix.jsp
tools/cldr-code/src/main/java/org/unicode/cldr/test/TestCache.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

-Add DefaultValue false for getDashboard parameter of VoteAPI.getRow
-Rename DataSection to DataPage; where appropriate, rename section to page/partition
-Rename some xpath to xpstrid for clarity when it means xpath hex string id
-Remove unused items from json: stro, baseXpath
-Remove dead code, including Partition.Membership
-Fix some compiler warnings, suggestions from IntelliJ
-Comments
CLDR-15368

CLDR-15368 Switch WHAT_GETROW to api, more preliminary clean-up

---

keyboards/3.0/fr-t-k0-azerty.xml
keyboards/dtd/ldmlKeyboard.dtd
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-15034
hit this in #2404  - otherwise more than one `<name>` element is not allowed.

CLDR-15034 kbd: name needs to be ORDERED

---

keyboards/3.0/mt.xml

CLDR-15034
- MSA 100:2002 is available from <https://mccaa.org.mt/Section/Content?contentId=1242>
Some references mentioning this layout:
- <http://web.archive.org/web/20160414071246/https://www.mita.gov.mt/MediaCenter/Images/1_Fonts_Pic1.jpg>
- <https://www.farah.cl/Keyboardery/A-Visual-Comparison-of-Different-National-Layouts/#mt>
ALLOW_MULTI_COMMITS=yes
ALLOW_MANY_COMMITS=yes

CLDR-15034 kbd: add mt

---

.github/workflows/gh-pages.yml
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/copy-local-assets.sh
tools/scripts/tr-archive/header.html
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

CLDR-16029
- Back port of lots of stuff.  Pushes spec v41 to smoketest.
- Literally just a backport, subsetted to only the `.github/workflows/gh-pages.yml` and `tools/script/tr-archive` subdirectories.
- Below looks worse than the actual diffs.
-----
List of back ports:
- CLDR-15088 specs: fix mixed content, improve build (#1881)
> (cherry picked from commit db15bae6b0ba6be54b50072c220e77a2dc14047f)
- CLDR-15539 tr:(deps): Bump jsdom in /tools/scripts/tr-archive (#1906)
> (cherry picked from commit 96383a3ca3603c91990c0474feda9666d80bbf5c)
- CLDR-15539 tr:(deps): Bump highlight.js in /tools/scripts/tr-archive (#1903)
> (cherry picked from commit 5e8707538ea06403d7638127d538c0e8bc8c361b)
- CLDR-15539 tr:(deps): Bump jsdom in /tools/scripts/tr-archive (#2150)
> (cherry picked from commit …

CLDR-16029 v41: backport tr-archive improvements

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java

-Include NNBSP in WHITESPACE_AND_NBSP_TO_NORMALIZE and related patterns
-New unit tests for NNBSP
-Comments
CLDR-14481

CLDR-14481 Coalesce multiple interior spaces

---

common/main/so.xml
common/main/yo.xml
common/main/yo_BJ.xml

CLDR-16065
Per TC discussion:
- for yo[_BJ], remove bad display names for Gulf Time
- for so, fix names as follows (with draft="contributed")
- for CI, make alt version be “Côte d’Ivoire”
- for PS, make short version be “Falastiin”

CLDR-16065 so,yo[_B]: fix or remove bad display names with translation hints

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LogicalGrouping.java

LogicalGrouping.getPaths might be called from different threads created in GenerateProductionData.
Wrapping the existing cache into Multimaps.synchronizedMultimap is not enough as underlying ArrayList is also should be synchronized: it is traversed in new TreeSet<>(cache.get()) and modified in cache.putAll() calls.
CLDR-15913

CLDR-15913 Make LogicalGrouping thread-safe.

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/supplemental.html
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/chart_messages.html

CLDR-14480 Fix old links in charts

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDelta.java

CLDR-14997 Suppress Special in charts

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowPlurals.java

CLDR-14310 fix charts for romance plurals

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/src/esm/cldrVote.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

-Front end: new VOTE_USES_NEW_API = true, getSubmitUrl, and related modernization in cldrVote.js
-Back end: use the same resolved CLDRFile for daip and calculateShowRowAction
-Back end: rename pvi to dataRow
-Back end: if value is empty in api post request, make it null, meaning abstain
-Both front and back end: rename submitResultRaw to submitResult for consistency
-Updated package-lock.json (unrelated to changes for this ticket)
-Comments
CLDR-15368

CLDR-15368 VOTE_USES_NEW_API=true, replaces WHAT_SUBMIT

---

tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt

CLDR-16032 json: update for atTime

---

common/main/hr.xml
common/supplemental/supplementalData.xml

CLDR-16061
note this does NOT have an end date for HRK, i could not find that yet.

CLDR-16061 add EUR to HR from 2023-01-01

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VerifyZones.java

-New method VerifyZones.metazoneIsOutdated
-Skip metazones for which metazoneIsOutdated returns true
-Minor refactoring for clarity
-Comments
-The following metazones are found to be outdated:
-Africa_FarWestern; tzid = Africa/El_Aaiun; range is null
-Aktyubinsk; tzid = Asia/Aqtobe; range.metazone = Kazakhstan_Western
-Alaska_Hawaii; tzid = America/Anchorage; range.metazone = Alaska
-Almaty; tzid = Asia/Almaty; range.metazone = Kazakhstan_Eastern
-Aqtau; tzid = Asia/Aqtau; range.metazone = Kazakhstan_Western
-Aqtobe; tzid = Asia/Aqtobe; range.metazone = Kazakhstan_Western
-Argentina_Western; tzid = America/Argentina/San_Luis; range.metazone = Argentina
-Ashkhabad; tzid = Asia/Ashgabat; range.metazone = Turkmenistan
-Baku; tzid = Asia/Baku; range.metazone = Azerbaijan
-Bering; tzid = …

CLDR-16014 Bad link in Zones report

---

tools/cldr-code/src/main/resources/org/unicode/cldr/tool/bytype-index.css

-Fix in bytype-index.css
CLDR-16086

CLDR-16086 Headers are hidden in new web site color scheme

---

keyboards/3.0/mt.xml
keyboards/import/README.md
keyboards/import/keys-Zyyy-punctuation.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java

CLDR-15034
Example use of the import statement

CLDR-15034 kbd: add an example import

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java

-Do not suppress candidate item matching inherited value from root or code-fallback
-Remove superfluous and erroneous duplicate INHERITANCE_MARKER item for country
-New method DataRow.inheritsFromRootOrFallback
-Comments
CLDR-15054

CLDR-15054 Fix DataPage inherited item from root/fallback

---

docs/ldml/tr35.md

CLDR-16094
- Remove the Proposed Update from part 1 title and in mods section
- Fix mods section bad bullet indenting for Units of Measurement
- Add mods section item about Hinglish

CLDR-16094 spec: removed Proposed Update, fix mods section bullets and add item re Hinglish

---

tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/PermanentVote.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveySnapshotDb.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserSettingsData.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUser.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

-Fix some Java compiler warnings, mostly using IntelliJ-suggested changes
CLDR-15717

CLDR-15717 Default coverage: preliminary clean-up

---

docs/ldml/tr35-keyboards.md
keyboards/3.0/fr-t-k0-azerty.xml
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlKeyboard.xsd
keyboards/dtd/ldmlKeyboardTest.dtd
keyboards/dtd/ldmlKeyboardTest.xsd
tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestMatchValue.java

CLDR-15034
Clarify that the keyboard's version is semver <https://semver.org>
ALLOW_MULTI_COMMITS=yes
ALLOW_MANY_COMMITS=yes

CLDR-15034 kbd: note that version number is semver

---

.github/workflows/gh-pages.yml
.gitignore
docs/.gitignore
docs/_config.yml
docs/index.md
docs/ldml/tr35.md
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/copy-local-assets.sh
tools/scripts/tr-archive/fix-tocs.js
tools/scripts/tr-archive/header.html
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

CLDR-16030
Includes:
-----
CLDR-16028 doc: update Latest Proposed Update link (#2370)
(cherry picked from commit 8d5fcd8a4cdf3abbcf09d82b4b2a7be6a27a69ce)
CLDR-15104 docs: use gh-pages branch and tr-archiver (#1572)
- build into the 'gh-pages' branch instead of using Github Pages default build
- use the tr-archiver for the spec
(cherry picked from commit fa660d9f1585ff21068b4f5de9f07de4c608b943)
CLDR-15205 spec: add an anchor (anchor.js) (#1827)
- Use package anchor-js to add links to h2 and below
(cherry picked from commit 3b5d276db853bb559d1b9f2ff993f11c9c94ac16)
CLDR-15105 spec: update ToC (#1835)
(cherry picked from commit 6c7bdab0dfc9315746d70d5dd673f809da104b07)
CLDR-15206 spec: section numbers outside of anchors, table caption (#1866)
- Update all anchors starting with section …

CLDR-16030 v40: backport proposed latest update and other fixes

---

.github/workflows/gh-pages.yml
.gitignore
docs/.gitignore
docs/_config.yml
docs/index.md
docs/ldml/tr35.md
tools/scripts/tr-archive/.gitignore
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/copy-local-assets.sh
tools/scripts/tr-archive/fix-tocs.js
tools/scripts/tr-archive/header.html
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

CLDR-16031
- don't apply fix-tocs
-----
Includes:
- CLDR-14691 Bump ws from 7.4.4 to 7.4.6 in /tools/scripts/tr-archive (#1285)
(cherry picked from commit f77f55798202fc4b50b67a11e32e23be1cfcbf3f)
- CLDR-14649 doc: update TR archiver (#1455)
(cherry picked from commit 3d8327b2f4b03186e4e4b700f9927d8d668f37bd)
- CLDR-14656 Updates to TR35 HTML output (#1511)
(cherry picked from commit 8acb11262ad89e7c5459341f2a34cdde927ef9ce)
- CLDR-16030 v40: backport proposed latest update and other fixes
(cherry picked from commit dc62029e10a295df04a077540bb1b6f3f2810f57)
- CLDR-16028 doc: update Latest Proposed Update link (#2370)
(cherry picked from commit 8d5fcd8a4cdf3abbcf09d82b4b2a7be6a27a69ce)
- CLDR-15104 docs: use gh-pages branch and tr-archiver (#1572)
(cherry picked from commit …

CLDR-16031 v39 spec: backport proposed update and build process

---

keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlKeyboard.xsd

CLDR-15034
This was actually found during implementation.

CLDR-15034 kbd: displays is a singleton

---

.github/workflows/staging.yml
tools/scripts/ansible/hosts
tools/scripts/ansible/openliberty-playbook.yml
tools/scripts/ansible/requirements.yml
tools/scripts/ansible/templates/deploy-sh.j2
tools/scripts/ansible/vars/main.yml

CLDR-14878 feat(build): add a staging action and server

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

-Remove dead code (WHAT_GETROW, WHAT_SUBMIT, ...)
-Fix some compiler warnings
CLDR-15368

CLDR-15368 After switch to API, remove dead code

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java

- verbose explaination of vote resolution
- ⚠️ refactoring of some critical functions
CLDR-14943

CLDR-14943 cldr-splaining: add VoteResolver function to get a transcript

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java

CLDR-16097 Fix delta dtd charts

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/TranslationHints.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/translation-hints/hints.txt

-Add a header with comments in hints.txt
-Validate hints.txt, comments must start with #; trim first
CLDR-13665

CLDR-13665 Translation hints, follow-up

---

tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/js/src/esm/cldrText.js

-If comparison cell would be empty, show circled i with hover message
CLDR-13640

CLDR-13640 ST confusion about dayPeriods not defined in English

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculatedCoverageLevels.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCalculatedCoverageLevels.java

- backed by CalculatedCoverageLevels
CLDR-16117
Ther's more to do, like to add more tests, a 'test' file, and to refactor the JSON code.
But that can be done after.

CLDR-16117 add StandardCodes.isLocaleAtLeastBasic

---

common/supplemental/supplementalData.xml

- end of HRK has an explicit official date as 2023-01-14
CLDR-16122

CLDR-16122 BRS: update supplemental data for ISO-4217 amd174

---

.github/workflows/maven.yml

revert 4cc91429561cb628a2b69323e9cf39408998c679
CLDR-16122

CLDR-16122 BRS: move tests to -z BUILD

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java

-In api.Auth.login set PREF_COVLEV (p_covlev) to null
-Remove unused SurveyMain.PREF_CODES_PER_PAGE (p_pager)
CLDR-15717

CLDR-15717 Default coverage: reset when log in

---

tools/cldr-apps/js/src/esm/cldrForumFilter.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java

-The thread id passes the filter if it matches the current id
-Comments
CLDR-15816

CLDR-15816 ST: links to specific forum post should open the post

---

tools/scripts/ansible/upgrade-playbook.yml

CLDR-15424 ansible: update upgrade playbook

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java

-TestAttributeValues/TestValid
-TestBasic/TestCoreData
-TestBasic/TestCurrencyFallback
CLDR-6396

CLDR-6396 Seed and common; skip some tests if !isLocaleAtLeastBasic

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocalCurrency.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java

-Fix TestLocalCurrency/TestConsistency
-Fix TestLocale/TestLanguageRegions
-Fix TestPaths/TestPathHeadersAndValues
-Fix TestSupplementalInfo/Test10765
-Fix TestSupplementalInfo/TestDefaultScripts
CLDR-6396

CLDR-6396 Seed and common; fix tests except TestCLDRLocaleCoverage

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java

-Fix some compiler warnings in STFactory.java, including dead code removal
CLDR-16105

CLDR-16105 Inheritance not recognized by PerXPathData, clean-up

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CldrVersion.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java

CLDR-15047
Seems like this should be a SBRS task

CLDR-15047 update ToolConstants for v42

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16085 Updated list of Meta locales

---

tools/scripts/ansible/certbot-playbook.yml
tools/scripts/ansible/upgrade-playbook.yml

-Fix tools/scripts/ansible/certbot-playbook.yml
-Comments in tools/scripts/ansible/upgrade-playbook.yml
CLDR-16127

CLDR-16127 BRS update servers; fix ansible script

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java

-Fix compiler warnings/suggestions
CLDR-11228

CLDR-11228 ST: notify TC of forum responses; preliminary clean-up

---

common/main/rif.xml
common/main/rif_MA.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml

CLDR-14962 add rif Tarifit

---

tools/cldr-apps/js/src/views/DashboardWidget.vue

CLDR-15813 Suppress Abstained for TC+

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java
tools/cldr-apps/src/test/resources/org/unicode/cldr/web/TestUserLevel.csv
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

- also update test cases
- add Level.canDeleteUsers() function
CLDR-8603

CLDR-8603 move “delete user” to super-Admin priv

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-15747
Since I did the sample code, was simple to just make a PR.

CLDR-15747 add method to get alt values (actually, any literal values)

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRTransforms.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16135 Add test for displaying names

---

common/main/root.xml

CLDR-16135
Add the names to root so that they are visible in the ST.

CLDR-16135 Make new sample names visible

---

common/main/ajp.xml
common/main/ajp_JO.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-14884 add ajp South Levantine Arabic

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUser.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/EmailValidator.java

-New class EmailValidator
-Call EmailValidator.passes in MailSender, and also in AddUser which had equivalent code
-Comments
CLDR-13329

CLDR-13329 Avoid SurveyTool sending to bogus email addresses

---

tools/cldr-apps/js/src/views/AddUser.vue

- no longer default to mul
- hide the Add button in some circumstances
CLDR-15680

CLDR-15680 don't allow creating vetters w/o locale

---

tools/cldr-apps/js/src/esm/cldrInfo.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/index.js
tools/cldr-apps/src/main/webapp/surveytool.css
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

- fix wordwrap in explainer
- hide explainer unless you click the circled 'i'
- update VoteResolver annotations to not prematurely declare a winner
- improve comments around annotations
This adds a top level function to cldrBundle due to difficulties in event handlers for the info panel.
CLDR-14943

CLDR-14943 explain UI improvements

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-Return silently from doAutoImportOldWinningVotes if user is null
CLDR-16157

CLDR-16157 Avoid null user causing null pointer exception in auto import

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16136
Found the code that was checking for empty values. Needed to add a method and infrastructure to test a path and an element.
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- Using new code on line 445 to verify that when val is empty we only register a problem when DtdData.getValueConstraint(cp) == DtdData.Element.ValueConstraint.nonempty
- NOTE: I'm unable to compile cldr-apps locally, or even check syntax, so its a bit of guesswork
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- unify the approach for zxx and ❮EMPTY❯
- add some constants at the top
- at 355, add test for either path
- at 506 qualify the replacement for empty.
- at 581 replace the ❮EMPTY❯ in locale lists (but also remove zxx for now) …

CLDR-16136 First cut at enabling ST to have empty values

---

tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/js/src/esm/cldrVote.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java

- had to do some work arounds for abstention as well, also for JSON serialization
CLDR-16172

CLDR-16172 support empty string values in the FE

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java

-Move call to db.getAConnection within try()
CLDR-16179

CLDR-16179 NPE in sending mass mail, MailSender.processOneMail

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestOrganization.java

-Add Organization.meta to the set VoteResolver.TC_ORGS
-Revise unit test
CLDR-16127

CLDR-16127 Add Meta to TC_ORGS

---

tools/pom.xml

CLDR-16181 Updated ICU4J version to 2022-12-02 for Ciudad Juarez

---

common/bcp47/timezone.xml

CLDR-16181 Added 'since' attribute to the new zone Ciudad Juarez

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java

-Get the complete report as a String before making a Response
CLDR-16205

CLDR-16205 Swedish Person Names report; avoid StreamingOutput

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

-Check for VoteStatus.provisionalOrWorse before VoteStatus.disputed
CLDR-16197

CLDR-16197 Count Disputed items correctly

---

common/supplemental/units.xml

CLDR-16201
Add initial unitPreferenceData for rainfall-rate, snowfall-rate. Can refine if we get more input on this.

CLDR-16201 Add initial unitPreferenceData for rainfall-rate, snowfall-rate

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

-Revise the SimpleNameObject constructor not to throw an exception
-Comment out TestInvalidNameObjectThrows for now
CLDR-16205

CLDR-16205 Swedish Person Names report; avoid IllegalArgumentException

---

common/main/brx.xml
common/main/cv.xml
common/main/fi.xml
common/main/fr.xml
common/main/ks_Deva.xml
common/main/mdf.xml
common/main/oc.xml
common/main/sms.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java

-Revert changes in eight xml files in common/main
-Revert changes in DAIP  and unit test
-Comments
CLDR-16210

CLDR-16210 Revert some changes involving NNBS U+202F

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

CLDR-14943
Example (taken from the unit tests):
- Two 4-votes for `a | b | e`, so 8 total
- Two 4-votes for `a | b | c | d`, so 8 total
- One 4-vote for `a | b`, so 4 total
```
Resolving votes:
- Getting all totals by organization:
-- Considering X which has 1 item(s)
--- X vote is for 'a | b | e' with strength 4
-- Considering Y which has 1 item(s)
--- Y vote is for 'a | b | e' with strength 4
-- Considering Z which has 1 item(s)
--- Z vote is for 'a | b | c | d' with strength 4
-- Considering W which has 1 item(s)
--- The W vote is for 'a | b | c | d' with strength 4
-- Considering V which has 1 item(s)
--- V vote is for 'a | b' with strength 4
Vote weights are being adjusted due to annotation keywords.
- First, components are split up and total votes calculated
-- component 'a' has …
```

CLDR-14943 explain votes: annotate geometric means

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java

CLDR-16229 Fix spurious characters

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-New methods VettingViewer.addLocaleStatusColumn, getLocaleStatusColumn
-Minor refactor: new subroutine VettingViewer.makeSummaryHeader
CLDR-15720

CLDR-15720 Add Priority Item Summary column Status AL/TC/HC

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java

-  add space in the VettingParticipation spreadsheet for ProgressVote/ProgressCount
- add back end API for fetching another user's dashboard
- fill in voting meter to spreadsheet
- only vetter and guest users
CLDR-16254

CLDR-16254 add API and spreadsheet space for voting meter

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java

- add org coverage level
- add %
UI:
- disable button while generating
CLDR-16254

CLDR-16254 update voting progress spreadsheet

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

-Process: -fP like -fp but without inheritance replacement
-Inheritance: -fI like -fp but only inheritance replacement
-Un-drop: -fU revert INHERITANCE_MARKER to pre-drop-hard-inheritance values
CLDR-16239

CLDR-16239 Add CLDRModify options related to inheritance

---

tools/cldr-apps/js/src/views/ReportResponse.vue

CLDR-16272
Updated wording screenshot:

CLDR-16272 update report instructions per ticket

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/IsoCurrencyParser.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a3.xml

will do a proper import in CLDR-16317
CLDR-16263

CLDR-16263 update ISO-4217 data since HRK is obsolete

---

common/main/cho.xml
common/main/cho_US.xml
common/supplemental/supplementalMetadata.xml

CLDR-16302
https://unicode-org.atlassian.net/browse/CLDR-16302
@pedberg-icu

CLDR-16302 Adding core data for cho (Choctaw)

---

common/main/aa.xml
common/main/ajp.xml
common/main/bal.xml
common/main/bal_Latn.xml
common/main/cho.xml
common/main/cu.xml
common/main/lmo.xml
common/main/pap.xml
common/main/rif.xml
common/main/ssy.xml

CLDR-16127 BRS, modify -fP -scommon/main

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java

-DROP_HARD_INHERITANCE = true: no change in behavior
-DROP_HARD_INHERITANCE = false: partial reversion to pre-drop-hard-inheritance behavior
-Making it false reduces changes from baseline when generating VXML
CLDR-16239

CLDR-16239 New boolean constant VoteResolver.DROP_HARD_INHERITANCE

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/esm/cldrClient.js
tools/cldr-apps/js/src/esm/cldrSearch.js
tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/js/src/views/MainHeader.vue
tools/cldr-apps/js/src/views/SearchButton.vue
tools/cldr-apps/js/src/views/SearchPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SearchManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyLog.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/SearchAPI.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestSearchManager.java

- plus tests
- search is asynchronous, and based on the CLDRFile API
- Exact matches only, for now
No UI… yet…
CLDR-13803

CLDR-13803 st api: add a search API

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRTransforms.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java

- use transform from CLDR-9007 for Olck
- rename getScriptTransform() to getTestingLatinScriptTransform()
CLDR-16122

CLDR-16122 v43 BRS: update transform for Olck

---

common/main/ks.xml

ks:
- drop an incomplete logical group that was only an inheritance marker anyway
CLDR-16122

CLDR-16122 v43 BRS: fix logical group errs

---

common/main/tt.xml

tt:
- drop all metazones that have only 'generic' time but require standard and daylight
CLDR-16122

CLDR-16122 v43 BRS: fix tt.xml

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16346 fix resolution errors in TestPersonNames

---

.github/workflows/maven.yml
common/main/nl_BE.xml

CLDR-16122
exact redo of #2657  + 1 fix

CLDR-16122 v43 BRS -z… FINAL_TESTING

---

common/main/nl.xml

CLDR-16069
Add ý to Dutch aux exemplars per discussion in JIRA ticket

CLDR-16069 nl, add ý to aux exemplars per ticket

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonName.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16323 Update code to handle patterns without given, fix charts

---

common/main/hi_Latn.xml

- keep draft status but change to triple up arrow
CLDR-16320

CLDR-16320 hi_Latn: drop compact numbers

---

common/supplemental/units.xml

CLDR-15281 Add unit preferences for floor area

---

common/main/fr.xml

CLDR-16222 Fix typo in French locale for currency LAK

---

common/main/ar.xml
common/main/bs.xml
common/main/gl.xml
common/main/gu.xml
common/main/he.xml
common/main/pa.xml
common/main/pl.xml
common/main/sq.xml
common/main/syr.xml
common/main/te.xml
common/main/tr.xml
common/main/zh.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonName.java

CLDR-16346
See ticket for details

CLDR-16346 fix extra dots/spaces in mononyms

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CheckoutArchive.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Option.java

- also update Option to support no-parameter arguments
CLDR-15047
Review note: Draft changes to the docs in <https://sites.google.com/d/1aVpQoyX7npAjbJstg5E17dCLDaHbzNhn/p/1_we1tnCo3hQCx4RbrvGLBzJ3x0C25Z6A/edit?pli=1>

CLDR-15047 add options to CheckoutArchive

---

common/main/root.xml
common/properties/coverageLevels.txt
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-16341
Note: this also includes some fixes for some long-standing issues in Locales.txt 
- English shouldn't have been comprehensive
- Some locales should have been in Org=special

CLDR-16341 locale coverage fixes

---

common/main/no.xml

https://unicode-org.atlassian.net/browse/CLDR-16003
CLDR-16003

CLDR-16003 Norwegian Bokmål - Use full, 4-letter month names

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/supplementalData.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-16185
@Manishearth @yumaoka @FrankYFTang

CLDR-16185 Add era codes to supplementalData

---

.github/COMMIT_METADATA.md

CLDR-16122 v43 BRS update COMMIT_METADATA.md

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/supplementalData.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-16253
This is a proposed design for CLDR-16253. Spec text and ICU changes need to follow.

CLDR-16253 Add component-specific parents to CLDR

---

common/annotations/ha_NE.xml
common/annotations/sr_Latn_BA.xml
common/annotations/yo_BJ.xml
common/main/ha_NE.xml
common/main/sr_Latn.xml
common/main/sr_Latn_BA.xml
common/main/yo_BJ.xml
common/main/yue_Hans.xml
common/subdivisions/ha_NE.xml
common/subdivisions/sr_Latn.xml
common/subdivisions/yo_BJ.xml
common/subdivisions/yue_Hans.xml

CLDR-16377 v43 BRS Algorithmic Locales

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRFileTransformer.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java

- don't write to Generated, but update files - if actual changes
- update TempPrintWriter to support this
CLDR-16377
(supports CLDR-14120 )

CLDR-16377 update CLDRFileTransformer to overwrite in place

---

common/main/da.xml
common/main/pl.xml
common/main/to.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java

CLDR-16323
See ticket for items handled here.

CLDR-16323 Tooling changes for person names

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareResolved.java

CLDR-16239 Basic diff tool for resolved files

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareResolved.java

-Minor revision of CompareResolved from PR #2709
-New -fV is also included per PR #2703
CLDR-16239

CLDR-16239 compare fully resolved values

---

common/dtd/ldml.dtd

CLDR-16122 v43 BRS: GenerateDTD, whitespace only

---

docs/ldml/tr35-keyboards.md

CLDR-15034 kbd: note that key to= is not always required

---

common/testData/personNameTest/cs.txt
common/testData/personNameTest/de.txt
common/testData/personNameTest/fr.txt
common/testData/personNameTest/ja.txt
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePersonNameTestData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/CheckPersonNamesTest.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestIcuPersonNames.java

CLDR-15111
It is just generating one file for now until we nail the format, namely de.txt.
Please look over the test data format to see if it is reasonable. It uses a semicolon delimited format, following what we have done before, but has a bit more structure.
Note: the parameter lines could be compacted for storage and readability, but that would then complicate the parsing, so it probably isn't worth it. But appreciate feedback on that. 
The one thought I had was that if a set of parameter lines is the same across all values of one of the parameters, that that be represented by *. 
Eg, 
```
parameters; givenFirst; long; addressing; formal
parameters; givenFirst; long; addressing; informal
parameters; givenFirst; long; referring; formal
parameters; givenFirst; long; referring; informal …
```

CLDR-15111 Initial version of test data for person names

---

common/supplemental/windowsZones.xml

CLDR-16386 Update windowsZones.xml for 2022g Mexican time zones

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-14587
- updates to LogKnownIssues. See specific commits.

CLDR-14587 v43 BRS: update logKnownIssues

---

common/main/en_001.xml
common/main/en_GB.xml

CLDR-16376 v43 BRS: en_GB to en_001 promotion

---

common/main/be_TARASK.xml
common/main/el_POLYTON.xml
common/main/oc_ES.xml
common/main/pt_AO.xml
common/main/pt_CH.xml
common/main/pt_CV.xml
common/main/pt_GQ.xml
common/main/pt_GW.xml
common/main/pt_LU.xml
common/main/pt_MO.xml
common/main/pt_MZ.xml
common/main/pt_ST.xml
common/main/pt_TL.xml
common/main/ru_BY.xml
common/main/zh_Hant_HK.xml
common/main/zh_Hant_MO.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareResolved.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleIDParser.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java

CLDR-16410
The following has a solution for v43, but we will need follow-on work in v44.
The problem is that resolved(main) != resolved(GenerateProductionData(main))
common/main/be_TARASK.xml ...
- Added a few items that need to be retained in the production data. 
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleIDParser.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java
- Refactored to move getParentChain to a reasonable location, because I needed it at one point but didn't want spaghetti import chains. 
- Turned out to not be necessary, but it is a good refactoring anyway. 
- Ended up using     public static boolean isL1(String localeId) …

CLDR-16410 Fix GenerateProductionData

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CldrVersion.java

CLDR-15047 add a comment referencing CheckoutArchive from CldrVersion

---

docs/ldml/tr35-dates.md

CLDR-16417 Add spec text for era codes

---

docs/ldml/tr35-personNames.md

CLDR-16265 Fix typos in personName documentation

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartLocaleGrowth.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java

CLDR-16346 Followup to PR 2731

---

docs/ldml/tr35-keyboards.md
keyboards/3.0/mt.xml
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlKeyboard.xsd
tools/cldr-code/src/main/java/org/unicode/cldr/tool/KeyboardFlatten.java
tools/cldr-code/src/test/java/org/unicode/cldr/tool/TestKeyboardFlatten.java

- update docs
- update mt.xml
CLDR-15034

CLDR-15034 kbd: change modifiers= to be NMTOKENS, doc

---

.github/dependabot.yml

CLDR-16437
- update dependabot to the new v44 ticket

CLDR-16437 v44 BRS: dependabot bump for v44

---

docs/ldml/tr35-personNames.md

CLDR-16433 Clean up language around spaceReplacement

---

common/dtd/ldml.dtd
docs/ldml/tr35-info.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListCoverageLevels.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/CheckLdmlDtdReferences.java

CLDR-15034
- merge commits from maint/maint-43

CLDR-15034 keyboard: branch maintenance

---

tools/cldr-code/src/main/java/org/unicode/cldr/draft/FileUtilities.java

CLDR-16456. Previously: #1729, broken by #1764.

CLDR-16456 Fix fileutilities for Windows again

---

common/supplemental/supplementalData.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/Iso3166Data.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java

- also fix duplicate data in Iso3166Data
CLDR-16423

CLDR-16423 v43 include CQ as a sibling to GG

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java

- fix for TempPrintWriter
CLDR-16458

CLDR-16458 fix GenerateDtd and other generators on Windows

---

tools/cldr-apps/pom.xml
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestUserRegistry.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestUserSettingsData.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestXPathTable.java
tools/pom.xml

- remove all infrastructure support for Derby
- does not remove Derby workarounds yet
CLDR-14213

CLDR-14213 Drop Derby Support: next phase

---

tools/scripts/ansible/nginx-playbook.yml
tools/scripts/ansible/server-playbook.yml
tools/scripts/ansible/templates/fail2ban-jail.local
tools/scripts/ansible/templates/nginx-stapler.conf

- we can't actually set the ocsp cache due to nginx version, but we can set a resolver
CLDR-16475

CLDR-16475 ansible updates for ocsp

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/supplementalData.xml
docs/ldml/tr35-dates.md
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt

CLDR-16469 Add inheritEras and remove eras with -2/-1

---

common/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateNumberingSystemAliases.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestNumberingSystems.java

- update root.xml
- add a test
- add a generator
- the test tells you to run the generator
CLDR-16480

CLDR-16480 v43 add all missing numsys + test

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-15473
Note: more radical changes to personNames as it is newer, simplified its header structure.

CLDR-15473 drop section numbering

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
tools/scripts/tr-archive/fix-tocs.js

CLDR-16122 (v43 BRS)
- update copyright date at bottom of spec
- update fix-tocs so it automatically bumps copyright CLDR-14239

CLDR-16122 v43 BRS: update © in spec

---

docs/ldml/tr35-personNames.md

CLDR-16433 Apply fixes from the PNF working group

---

common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlPlatform.dtd

CLDR-16511 DTD

---

docs/ldml/tr35-keyboards.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
tools/scripts/tr-archive/fix-tocs.js

CLDR-16122 v43 spec: fix bad link, update wording

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json

CLDR-16437
- also see CLDR-14408 CLDR-14409

CLDR-16437 use mocha-headless-chrome

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STUsersChoice.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteType.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VotelessUsersChoice.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterProgress.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java

-For now, counts for vote types are shown in the last column
-Change API from dashboard/for, to participation/for
-Omit (unused, large) notifications from Vetting Participation json; new ParticipationResults
CLDR-15850

CLDR-15850 Add vote type column to Vetting Participation sheet

---

docs/ldml/tr35.md

CLDR-16418 Add spec text for parent locales by component

---

docs/ldml/tr35-info.md

alternative for processing phone numbers
CLDR-16504

CLDR-16504 add reference to recommended open source

---

docs/ldml/tr35.md

CLDR-16511 flesh out modification section 2

---

docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-16122
spec was updated without rerunning fix-tocs

CLDR-16122 v43 BRS: rerun fix-tocs

---

docs/ldml/tr35.md

CLDR-16511 Refine modification section

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/TablePrinter.java

CLDR-16520
This is done in TablePrinter.java, by breaking before each <td..> and <th...>, and indenting. The <tr...> are also indented, but by a smaller amount. Example:
```
<table>
<tr>
<th class='source' width='1%'>Quantity</th>
<th class='source' width='1%'>Unit</th>
<th class='source' width='1%'>Case</th>
<th class='target'>Pattern for one</th>
<th class='target'>Case MP + pattern with 1.0</th>
<th class='target'>Pattern for other</th>
<th class='target'>Case MP + pattern with 3.0</th></tr>
<tr>
<td class='source' rowSpan='4'>acceleration</td>
<td class='source' rowSpan='2'><a name='meters per second squared' href='#meters per second squared'>meters per second squared</a></td>
<td class='source'>nominative</td>
<td class='target' rowSpan='2'>{0} ሜ/ሰ²</td>
<td class='target'>የዩኬ 1 ሜ/ሰ² …
```

CLDR-16520 break lines between cells for diffability

---

.gitignore
docs/ldml/tr35-info.md
docs/ldml/tr35.md

- remove broken appspot link, link to project
- add gitignore for lychee, a link checker
CLDR-16512

CLDR-16512 v43 BRS spec links phase 1

---

common/properties/coverageLevels.txt
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java

CLDR-16449
And in the coverageLevels.txt file

CLDR-16449 Retain sr_Latn in coverage chart 

---

.github/workflows/gh-pages.yml
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-personNames.md
tools/scripts/tr-archive/extract-link-targets.js

CLDR-16512
- add an internal link checker (part of the extractor)
- run the extractor, but don't fail the build yet. Will revisit in CLDR-16526

CLDR-16512 v43 BRS: fix internal spec links

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js

-To facilitate inserting new rows without adding new bugs, avoid hard-coded column numbers/letters
-New const array: COLUMNS, single data item determines the ordering/labeling of columns
-New const strings: COLUMN_TITLE_ORG, COLUMN_TITLE_LOCALE_NAME, ...
-Reduce function length by using new subroutines: getHeaderRow, getIndexOfColumnsByTitle, getDefaultRow, addColumnComments
-TODO comments for revising the wording of some column comments
CLDR-15850

CLDR-15850 Refactor cldrVettingParticipation.js before further changes

---

common/annotations/lij.xml
common/annotations/root.xml
common/annotationsDerived/root.xml
common/main/ab.xml
common/main/ab_GE.xml
common/main/lij.xml
common/main/lij_IT.xml
common/main/root.xml
exemplars/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

CLDR-14527 Fix broken links to spec

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js

-New const COLUMN_TITLE_VOTES_DIRECT, ...; new const VOTE_TYPES; new method getVoteTypes
-Revise COLUMNS
-Revise the wording of some column comments
-Include column title with comment, for convenience if column is narrower than title
-Warn in console if more than 26 columns A-Z
-Change some console.log to console.warn
CLDR-15850

CLDR-15850 Replace single Vote Type column with five specific columns

---

tools/cldr-apps/js/src/esm/cldrVettingParticipation.js

-Support more than 26 columns using pre-existing library method
CLDR-15850

CLDR-15850 Vetting table xlsx use encode_cell

---

common/annotations/lij.xml
common/annotations/root.xml
common/main/ab.xml
common/main/ab_GE.xml
common/main/lij.xml
common/main/lij_IT.xml
common/main/root.xml
exemplars/main/root.xml

CLDR-16555
Ran CLDRModify one more time before final tag. The first pass produced these changes: Removing a blank link from the headers of a few files, and updating copyright dates in some of those files. The other passes produced no change.

CLDR-16555 BRS 43 pre-final CLDRModify: remove blank header lines, update copyrights

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
keyboards/README.md
keyboards/dtd/ldmlKeyboard.dtd

- drop “draft” and update status
- also fix keyboard links to go to the new subcommittee homepage
CLDR-16122

CLDR-16122 v43 BRS finalize the spec

---

common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
pom.xml
tools/cldr-apps/pom.xml
tools/cldr-code/pom.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CldrVersion.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-16464 v44: bump version numbers to v44

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java

-When needed to meet requirements, change INHERITANCE_MARKER to Bailey or vice-versa
-New method STFactory.DataBackedSource.reviseInheritanceAsNeeded called by setValueFromResolver
-Throw exception from reviseInheritanceAsNeeded if CLDRFile has isResolved false
-Only change STFactory; no changes to CLDRFile
CLDR-16560

CLDR-16560 Requirements for storing inheritance marker

---

docs/ldml/tr35.md

- missed in earlier commit
CLDR-16122

CLDR-16122 v43: remove 'Proposed Update' tr35.md

---

.github/workflows/maven.yml

CLDR-16564 v44 SBRS: update tests to -z BUILD

---

tools/pom.xml

CLDR-16578
Update ICU4J libs in CLDR to ICU 73 final release version (currently the latest tagged ICU version)

CLDR-16578 SBRS v44 update ICU4J libs in CLDR to ICU 73 final release

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/SubmissionLocales.java

CLDR-16564 turn off LIMITED_SUBMISSION for v44

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/esm/cldrInheritance.mjs
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/setupComponents.js
tools/cldr-apps/js/src/views/InfoPanel.vue
tools/cldr-apps/js/src/views/InheritanceExplainer.vue
tools/cldr-apps/js/webpack.config.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Inheritance.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/STError.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAlt.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestXPathTable.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleInheritanceInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java

CLDR-16390
- also refactors some of the component .js code
- also reformats the Info panel a little

CLDR-16390 UI for Inheritance Explainer

---

keyboards/3.0/ja-Latn.xml
keyboards/3.0/pt-BR-k0-abnt2.xml
keyboards/3.0/pt-k0-abnt2.xml
keyboards/import/keys-Zyyy-currency.xml
keyboards/test/ja-Latn-test.xml
keyboards/test/pt-BR-k0-abnt2-test.xml

CLDR-15034 kbd: add iso and abnt2 keyboards

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

- SurveyMain.getSupplementalDataInfo() ended up calling itself again. This was probably introduced in #757 but unmasked by another possible issue in CLDR-15296 #2868
- getting this patch in for now to unbreak
CLDR-16622

CLDR-16622 workaround for deadlock in SurveyTool

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateIndexCharacters.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java

CLDR-4903
The code and tests are now complete. I'd like to merge this before doing the DAIP step.

CLDR-4903 simpler display of exemplar sets

---

common/main/en_ZA.xml

CLDR-16247
Update decimal and grouping separator for en_ZA

CLDR-16247 Update decimal and grouping separator

---

common/annotations/en.xml

CLDR-14050 annotation fix mxclaus

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-16623
Includes both the changes for the PNF spec, and the finalization for 43.1:
- change the version to 43.1 in all files
- change the date to today
- change from proposed draft to final

CLDR-16623 V2 make specified changes to the PNF spec

---

tools/cldr-code/src/main/java/org/unicode/cldr/draft/ExemplarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckExemplars.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CountItems.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowKeyboards.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/ComparatorUtilities.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnicodeSetPrettyPrinter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCollationMapMaker.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java

CLDR-4903 Refactor use of collators in UnicodeSet printing

---

tools/cldr-apps/js/src/esm/cldrForumFilter.mjs

-Change [Open topics] to [Open requests by others] and [Open discussions]
-Revise function passIfNeedingAction and subroutines
-New functions to replace passIfOpen: passIfOpenDiscuss; passIfOpenRequestByOther
-Simplify implementation of passIfOpenRequestYouStarted
-New subroutine hasYourUpToDateResponse
-Remove simplifyCounts, no longer applicable
-Comments
CLDR-14380

CLDR-14380 Needing Action count should exclude if you have responded to a discussion

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16548 create choctaw nation

---

common/transforms/Cyrillic-Latin.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PrettyPath.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/TransliteratorUtilities.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java

CLDR-16643
Most of the work was in fleshing out the test to try to prevent breakage before it hits ICU. Didn't have time to port the ICU tests, so just did a quick test.

CLDR-16643 Fix kh, add more comprehensive tests

---

common/dtd/ldml.dtd
common/main/ja.xml
common/main/root.xml
common/main/yue.xml
common/main/yue_Hans.xml
common/main/zh.xml
common/main/zh_Hant.xml
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16457 nativeSpaceReplacement and so on

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java

CLDR-16570 improve logging, less noisy on jwt login and stale sessions

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/translation-hints/hints.txt

CLDR-16536 drop m hint from narrow duration-minute

---

.github/workflows/gh-pages.yml
.github/workflows/keyboard.yml
docs/charts/keyboard/.gitignore
docs/charts/keyboard/build.mjs
docs/charts/keyboard/package-lock.json
docs/charts/keyboard/package.json
docs/charts/keyboard/static/index.html
docs/charts/keyboard/static/keyboard-chart.css
docs/charts/keyboard/static/keyboard-chart.js
keyboards/import/keys-Latn-implied.xml

CLDR-15034 super basic keyboard charts

---

common/main/blo.xml
common/main/blo_BJ.xml
common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java

CLDR-16592 Add Anii (blo-BJ) locale

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DisplayAndInputProcessorFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java

CLDR-13180 Use locale-sensitive DAIP on display

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/en_001.xml
common/main/en_AE.xml
common/main/en_AU.xml
common/main/en_DK.xml
common/main/en_FI.xml
common/main/en_GB.xml
common/main/en_IN.xml
common/main/en_ZA.xml
common/segments/root.xml
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-16650
**Note: This needs to be merged using a _merge commit_ (must be temporarily enabled in settings), _not_ the normal _squash and merge_.**
Merge the 4 CLDR 43.1 commits on maint/maint-43 branch (so far) back to main.

CLDR-16650 Cherry-pick v43.1 maint/maint43 fixes to main branch, part 1

---

tools/cldr-apps/js/src/esm/cldrInfo.mjs

CLDR-13180 st: use DAIP view in Info panel

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java

CLDR-16630 Change the escape characters for displaying UnicodeSets

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16646
Still need the core data

CLDR-16646 Create organization WSC+I for csw

---

.github/workflows/production.yml

CLDR-16564 
work around production issue

CLDR-16564 workaround prod issue

---

tools/cldr-apps/js/src/esm/cldrAddAlt.mjs
tools/cldr-apps/js/src/esm/cldrAjax.mjs
tools/cldr-apps/js/src/esm/cldrAnnounce.mjs
tools/cldr-apps/js/src/esm/cldrForum.mjs
tools/cldr-apps/js/src/esm/cldrGui.mjs
tools/cldr-apps/js/src/esm/cldrPriorityItems.mjs
tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/js/src/setupComponents.mjs
tools/cldr-apps/js/src/specialToComponentMap.mjs
tools/cldr-apps/js/src/views/AnnounceForm.vue
tools/cldr-apps/js/src/views/AnnouncePanel.vue
tools/cldr-apps/js/src/views/AnnouncePost.vue
tools/cldr-apps/js/src/views/MainMenu.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleSet.java

-New web/api/Announcements.java and web/AnnouncementData.java
-Two new versioned database tables: ANNOUNCE and ANNOUNCE_READ
-New AnnouncePanel.vue, AnnouncePost.vue, AnnounceForm.vue, and cldrAnnounce.mjs
-New Announcements item in MainMenu.vue
-New function cldrAjax.makePostData, used in cldrAnnounce.mjs, also, for encapsulation, by refactoring in cldrAddAlt, cldrGui, cldrPriorityItems
-The change in cldrGui also fixes a compiler warning mentioned in old comment
CLDR-13962

CLDR-13962 Improve communication with vetters (announcements)

---

docs/ldml/tr35.md

CLDR-16629 Account for macroregions in likely subtags

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java

CLDR-16382
common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- Standard stuff when adding new structure:
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
- Standard stuff to test new structure
- load new structure (just to make sure we can; not needed in CLDR …

CLDR-16382 Add default parameters for PNF

---

.github/COMMIT_METADATA.md

Accidentally made the PR under the wrong ticket. It should have been CLDR-16598, not CLDR-14380.
CLDR-16598

CLDR-16598 Update COMMIT_METADATA.md

---

common/main/vmw.xml
common/main/vmw_MZ.xml
common/supplemental/supplementalMetadata.xml

CLDR-16287 core data for Makhuwa (vmw)

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/downgrade.txt

CLDR-16568
Set the votes to 0 in Survey Tool for certain personNames paths, per the [Person name formatter patterns](https://docs.google.com/spreadsheets/d/1Tw1FsgkDSpXJuf-CAFSHMzTuqDI6wC68wqb8B7QhIsQ/edit#gid=0) spreadsheet (with comments in yellow by Peter).

CLDR-16568 Add PNF paths with questionable data to downgrade list

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java

-Synchronize fixes strange errors on start-up if new tables do not exist yet
-Include the message body, poster name, audience/orgs/locales in the email
CLDR-13962

CLDR-13962 Announcements: synchronize makeSureDbSetup; email has body/etc.

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DowngradePaths.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocalePathValueListMatcher.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/downgrade.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathLookup.java

CLDR-16654
Fix the tool to:
- Have the right polarity on the test
- Ignore en and root
- Have a fast path to ignore locales that can't match any line in downgrade.txt

CLDR-16654 Revise the downgrade tool

---

common/main/xnr.xml
common/main/xnr_IN.xml
common/supplemental/supplementalMetadata.xml

CLDR-16667 add xnr

---

common/collation/root.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-apps/js/test/TestCldrErrorSubtypes.mjs

-Also updated one copyright notice to 1991-2023, and changed one http to https
CLDR-15371

CLDR-15371 Fix broken links for Survey Tool instructions

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-Fix filterDowngradePaths to get locale as parameter, not from query
-Fix query, ver not newVer for oldVotesTable
CLDR-16661

CLDR-16661 Downgrade paths when importing votes: bug fixes

---

tools/cldr-apps/js/src/esm/cldrDeferHelp.mjs
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java

-Add CLDRURLS.GRAMMATICAL_INFLECTION for .../unitLength.../gender paths
-Make helpHtml links clickable in Info Panel
-Remove dead code from PathDescription.java
CLDR-13916

CLDR-13916 Update help link for unitLength...gender; make clickable

---

common/main/csw.xml
common/main/csw_CA.xml
common/supplemental/supplementalMetadata.xml

- Chart is Approved by WSC+I WG
CLDR-16646

CLDR-16646 Seed data for csw

---

common/main/en.xml
common/supplemental/units.xml
common/validity/unit.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CheckUnit.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-13932 gasoline gallon equivalent
