unicode-org/cldr

tools/cldr-code/src/main/java/org/unicode/cldr/tool/LikelySubtags.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16136
Found that the logic didn't work for Thai. Changes:
tools/cldr-code/src/main/java/org/unicode/cldr/tool/LikelySubtags.java
- Slight reworking of the code to allow access to methods that directly manipulate a LanguageTagParser, which is more convenient to use for what we want.
- added the formatter language and script, so that "is a foreign language" is not dependent on anything but the likely language and script. This was to take care of an old TODO, where the old code just did a raw comparison, and would miss that en and en-UK are not "foreign languages" for the purpose of picking foreign space replacements.
- added a nativeSpaceReplacement. For the locales  that don't need spaces, this is …
=> CLDR-16136 Tweak FSR conditions

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAccessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/LikelySubtags.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15826
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAccessor.java
- Needed access to the Phase() in the CheckAccessor.
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
- Name Order locales were being changed for exemplars, but those are just ASCII
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
- Dropped the old (ugly) REQUIRED and REQUIRED_EMPTY. The info is improved, and moved to SampleType. So we can just test with sampleType.getOptionality(modifiedField);
- The logic in handleCheck is improved. We are about whether the MISSING values are in the locale either explicitly or by explicit inheritance, but don't show errors if we don't yet have a value added to the locale.
- We emit warnings in BUILD phase (so we can check …
=> CLDR-15826 Fix PersonName Check warnings and errors

tools/cldr-apps/js/src/index.js, tools/cldr-apps/src/main/webapp/surveytool.css, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonName.java, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/reports.css
CLDR-16161
- update ChartPersonName.java to put a <div class="ReportChart"> around
its output
- create a new reports.css file in org.unicode.cldr.tool (so it could be used by the Chart.java tooling)
This is based on the sibling index.css file but has .ReportChart around each declaration.
- include that reports.css file directly into the webpack bundle by updating index.js
Note that .dtf-table and related styles were already in surveytool.css so I moved those
into reports.css
=> CLDR-16161 fix CSS for PersonName (and possibly others)

common/main/km.xml, common/main/lo.xml, common/main/th.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16136
I realized that there is no way for vetters to enter an empty FSR. So we need to handle it like we did zxx for the nameOrderLocales.
That is done here.
=> CLDR-16136 Allow empty FSR

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16136
The example cache needs to have the dependencies updated. In particular:
The namePattern examples depend on:
1. nameSamples
2. initial patterns
3. nameOrderLocales
4. foreignSpaceReplacement
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java
- Update the general Example generators with changes to the above.
- There is also a special cache to keep from recreating the personname samples and formatter, so update that with changes to the above.
- There was also a bug in the examples, where personnames needs to know about the background/forground flags. It has to remove then re-add them in the case …
=> CLDR-16136 The examples are not updating properly.

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
- enqueueing (not sending) mail in CLDR-11228 (#2526) didn't close Connection when done
- this restores the Connection to the try-with-resource block
CLDR-16179
=> CLDR-16179 fix NPE in queueing mail

common/main/en.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16137
The generation field was overlooked in English for foreignFull, which causes vetters to forget it for their languages.
=> CLDR-16137 Add missing generation field for English

tools/pom.xml
CLDR-16189
Update CLDR to use the latest ICU4J which is now marked as version 73.0.1
=> CLDR-16189 SBRS v43: Update ICU4J libs to first version marked 73.0.1

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-In PathHeader.java, only allow Etc/Unknown to give null/001/ZZ
-This would have informed us sooner of needed ICU update for America/Ciudad_Juarez
CLDR-16127
=> CLDR-16127 Throw exception for zone not in ICU

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SpecialLocales.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
-New Type.algorithmic distinct from Type.readonly; method isReadOnly true for both
-Revise unit test TestSpecialLocales
-Comments
CLDR-15720
=> CLDR-15720 First step: SpecialLocales.Type.algorithmic

common/main/ar_BH.xml, common/main/ar_DJ.xml, common/main/ar_EG.xml, common/main/ar_ER.xml, common/main/ar_IL.xml, common/main/ar_IQ.xml, common/main/ar_JO.xml, common/main/ar_KM.xml, common/main/ar_KW.xml, common/main/ar_LB.xml, common/main/ar_MR.xml, common/main/ar_OM.xml, common/main/ar_PS.xml, common/main/ar_QA.xml, common/main/ar_SA.xml, common/main/ar_SD.xml, common/main/ar_SO.xml, common/main/ar_SS.xml, common/main/ar_SY.xml, common/main/ar_TD.xml, common/main/ar_YE.xml
CLDR-16147
Restore explicit defaultNumberingSystem=arab for ar_XX locales that had it as defaultNumberingSystem=↑↑↑; i.e. undo a bit of #2433 which was for CLDR-15054. This PR is a data fix only: I have cloned the CLDR ticket to another ticket to investigate tool enhancements.
=> CLDR-16147 Restore explicit defaultNumberingSystem=arab for ar_XX locales that had it as ↑↑↑

common/supplemental/units.xml
CLDR-16201
Per Mark and Shane comments in #2605, drop the "-rate" from the new unitPreferenceData speed category usage values "rainfall-rate", "snowfall-rate"
=> CLDR-16201 Drop -rate from unitPreferenceData usages rainfall-rate, snowfall-rate

common/main/fr_CA.xml
CLDR-16215
Undo inadvertent change to fr_CA grouping separator from the sequence of PR #2433 followed by #2609.
=> CLDR-16215 Restore fr_CA grouping separator to U+00A0

common/rbnf/ar.xml, common/rbnf/el.xml, common/rbnf/en.xml, common/rbnf/en_IN.xml, common/rbnf/he.xml, common/rbnf/nl.xml, common/rbnf/ru.xml, common/rbnf/uk.xml
=> CLDR-16089 Remove periods from ordinal number formatters in languages that don't have this convention

common/main/ckb_IR.xml
CLDR-16199
Per supplemental data, IR prefers time cycle H.
So ckb_IR needs to provide standard time formats explicitly using H for all calendars inherited from ckb (which defaults to IQ and time cycle h).
=> CLDR-16199 ckb_IR needs H time formats for calendars inherited from ckb

common/main/en_001.xml, common/main/en_GB.xml
-Changes are limited to a few paths with short, duration-hour
-The values are derived by reverting to before drop-hard-inheritance, then running cldrmodify one locale at a time, parent before child
CLDR-16239
=> CLDR-16239 Change some inheritance markers to specific values in en_001.xml and en_GB.xml

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
-New method setWinningValue ensures winningValue never gets bailey
-This makes VoteResolver more consistent
-Fix unit tests that failed to set bailey
CLDR-16239
=> CLDR-16239 Always change bailey to inheritance marker in VoteResolver

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- allow anyone with UserRegistry.userCanModifyUser() (basically manager/tc in your own org, or else admin for everyone) to update user email or user name
- Admin can still change orgs, etc.
This was inadvertently broken in CLDR-8603 (#2527), not realizing that 'userCanDeleteUser' was actually used for whether email and name could be modified.
CLDR-16234
=> CLDR-16234 st: allow manager/tc to update email and name

tools/cldr-apps/js/src/esm/cldrAjax.js, tools/cldr-apps/js/src/esm/cldrLoad.js, tools/cldr-apps/js/src/esm/cldrRetry.js, tools/cldr-apps/js/src/esm/cldrText.js, tools/cldr-apps/js/src/views/WaitingPanel.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/webapp/surveytool.css
- handleDisconnect no longer tries to load the 'loading' page.  That page only should show up if the ST is not up yet.
- on loading rows, process the error code properly and display the error, such as E_BAD_SECTION
- update the errCodeMsg box to have a Reload and a Home button
CLDR-16224
=> CLDR-16224 st: updates to loading and retry

.github/pull_request_template.md
CLDR-16246
Many PRs are landed which fail the 'single commit check'.  It would be better to quell this error so that we can see when there are real errors.
Examples: 
#2616 #2575 #2578 #2562
=> CLDR-16246 update PR template to allow multi commits by default

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-16057
Note that this is for v43, and also it will fail until e5a71a8a2dc008c8d9c731168212f2eca3eed357 (#2375) is cherry picked to main
=> CLDR-16057 test: improve TestCurrency message on ISO 4217

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/SubmissionLocales.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
CLDR-16272
- add a limited set of available reports in SubmissionLocales
- only show available reports in the sidebar
- don't count unavailable reports against completion in Dashboard
- throw 403 Forbidden if user tries to navigate to or vote on un-available reports
=> CLDR-16272 limit some reports during limited submission

common/main/root.xml
CLDR-16199
Remove the 'draft="provisional"' that seems to have been accidentally added to all of the root <namePattern> entries with real data (as opposed to being aliases). This must have been a side effect of resetting the personName data for CLDR 43 Survey Tool submission; but data in root and en should never be provisional. This was causing resource load errors in the ICU4J PersonName code.
=> CLDR-16199 remove draft="provisional" from root <namePattern> entries

.github/workflows/gh-pages.yml
CLDR-13619
See https://github.com/unicode-org/cldr/actions/runs/3954024609/jobs/6770915378 for a successful run
I tried several things and wasn't able to do a local build… but, updating ruby to 2.7 seemed to succeed.
=> CLDR-16319 deps: fix gh-pages breakage w/ ruby 2.7

common/main/en.xml, common/main/nl.xml, common/main/root.xml, common/main/zh.xml, common/validity/unit.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-16200
Initial support for Beaufort scale units (for wind speed). Data for `root` and `en`; provisional data for`zh` and `nl` (the latter formats without a unit symbol, checked that this does not generate errors in CLDR at least).
The conversion to other speed units is non-linear (see the ticket) which is not yet supported, so this  unit is currently marked as non-convertible in tests.
Usage data will be added in the future after we have confirmed localized formats for Beaufort units in the relevant locales.
=> CLDR-16200 initial support for Beaufort units, currently non-convertible

.github/workflows/gh-pages.yml
From CLDR-16319 (#2650)
(cherry picked from commit 0cf65943c0eb8fe7e3e490887bf5afba4240bd25)
CLDR-16330
=> CLDR-16330 v42: deps: fix gh-pages breakage w/ ruby 2.7

common/main/fi.xml, common/main/nl.xml
- fi and nl had `SLE` and `SLL` with identical localizations
- SLL is obsolete and needs  (1964—2022)
CLDR-16122
=> CLDR-16122 v43 BRS: fix fi,nl

common/main/chr.xml, common/main/ps.xml
CLDR-14770
Remove incorrect curly quotes (\u2018, \u2019) that appear to have been intended as the apostrophe (\u0027) used to mark literal text. The apostrophe would not be needed in these cases anyway (since the literal text is non-ASCII), and in the `ps` case the \u2018s were spanning the wrong range anyway (and removing them makes the MMMMW "one" format match the "other" format, as is the case for the yw formats).
=> CLDR-14770 chr,ps: remove incorrect curly quotes intended to mark literals

common/main/bs.xml, common/main/cs.xml, common/main/de.xml, common/main/dsb.xml, common/main/fi.xml, common/main/frr.xml, common/main/gsw.xml, common/main/hr.xml, common/main/hsb.xml, common/main/hu.xml, common/main/is.xml, common/main/ksh.xml, common/main/lb.xml, common/main/lt.xml, common/main/lv.xml, common/main/nds.xml, common/main/prg.xml, common/main/rm.xml, common/main/sk.xml, common/main/smn.xml, common/main/sr_Latn.xml, common/main/uz.xml, common/main/wae.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
CLDR-16308
Adjusted DisplayAndInputProcessor (DAIP) so that the intervalFormat normalizations it performs for Latin-script locales (replacing hyphen or en-dash surrounded by space with en-dash \u2013 surrounded by thin space \u2009) work even if those characters are preceded by literal text such as a period or a quoted literal. It turn out that when DateTimePatternGenerator.FormatParser.getItems returns the tokens for the first part of the intervalFormat pattern, the last token - which ends with the spaces + hyphen/dash - also includes any preceding literal text which came after the last pattern character in the first part.
Then ran the updated DAIP to actually fix the problem intervalFormats. The differences are just changing regular space to thin space around an en-dash, to be …
=> CLDR-16308 DAIP Latin-script intervalFormat adjustments should handle preceding literals

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16323
The previous PR fixed most problems, but one remained.
That code handles the case where the name data is a monogram (no surname) and there's no {given} in the pattern. It does that by using a filtered NameObject that returns the given name instead of the surname. 
1. That mostly works. Where it doesn't is in cases of "Z" in the nativeG column on https://unicode-org.github.io/cldr-staging/charts/43/verify/personNames/en_GB.html, where we would not expect just an initial (if there were a surname, it would be a full name).
2. The problem comes when we have a monogram, and the pattern is {given-initial} {surname} (perhaps with additional items like {title}. We get just "Z" (or "Z." in https://unicode-org.github.io/cldr-staging/charts/43/verify/personNames/en.html).
3. We could of …
=> CLDR-16323 Fix patterns with given-initial

common/annotations/hy.xml, common/annotations/sq.xml, common/main/az.xml, common/main/lv.xml, common/main/mk.xml, common/properties/coverageLevels.txt
(and exposed in charts/43/tsv/locale-missing.tsv) by setting to contributed.
Add generated coverageLevels.txt from charts.
CLDR-16346
=> CLDR-16346 Address provisional items identified in resolution

tools/pom.xml
CLDR-16359
Update ICU4J libs in CLDR to version of 2023-02-02 before starting first integration with CLDR 43 Survey Tool data.
=> CLDR-16359 BRS v43: Update ICU4J libs to 2023-02-02

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowData.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/verify-index.html
CLDR-15995
1. Modifies GenerateSidewaysView and ShowData to avoid generating files too large for github.
2. Modifies ShowLocaleCoverage to clean up the Key, drop the column that showed common vs seed, added links to the tsv files.
3. Fixed a missing index line (that effectively hid all the person name charts.
=> CLDR-15995 fixes to charts

common/dtd/ldml.dtd, common/dtd/ldmlSupplemental.dtd, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
CLDR-15071
I noticed that the tests were not catching a mismatch between the sil1 value in the .xml file and the sil22 value in the dtd. I looked into it, and found some problems in the test, where paths not being tested correctly. Fixed those, and the cases in the DTD that they exposed.
=> CLDR-15071 Fix dtd tests

tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16284
Removing Thai from the list of scripts that don't need spaces in names.
=> CLDR-16284 Remove Thai from no-space name scripts

common/main/ar.xml, common/main/fa.xml, common/main/ps.xml, common/main/ur.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16346
common/main/ar.xml
- retracted the special pattern
- I had to understand what the code was doing, so went ahead and added comments for the future.
- The main change was to coalesceLiterals. It is not just duplicates, but rather anytime we would get a repeat at the end of a combined literal
- Added test cases
=> CLDR-16346 Automatically handle adjacent duplicate literals in person names

common/main/cch.xml, common/main/ken.xml, common/main/nv.xml, common/main/sms.xml, common/main/ssy.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverage.java
CLDR-7674
*.xml files
Added names as per ticket
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- Minor change to set default to basic for the last column
tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
- Significant revamp here. 
- Added 3 items at Basic level (we had moved up from Core). 
- Added static sets for quick access to the CoreItems at each level (and below)
- Added a sublevel, to distinguish the ones that should be present at the start. 
- Moved ordinals to Modern (discussed earlier, since we don't depend on them in CLDR itself)
- Restructured the main function getCoreCoverageInfo
- Now compute result at the end, simplifying the code and making less error-prone
- Better tests of edge cases like ZZ and 001
- Handles the …
=> CLDR-7674 Fix a few locales, adjust charts, test, and utility

common/main/ar.xml, common/main/en.xml, common/main/nl.xml, common/main/yue.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16346
Detect and fix inconsistencies between initial pattern and literals between initial fields. Handles the "J. R.R. Tolkien" case.
From Person Names WG agenda
Overall Recommendations AGREED
1. For en, en_GB: Switch to J.R.R. Tolkien.
a. In en, drop space between initial fields, drop space in initial sequence pattern, 
b. In en_GB, en_001, change to ^^^.
2. For ar, move period to ‘initial’. Was:
a. <initialPattern type="initial">{0}</initialPattern>  R Gillam→R. Gillam
b. <initialPattern type="initialSequence">{0}. {1}.</initialPattern> R. B. Gillam (same)
3. For nl, drop the space in the adjacent fields. 
a. Will look like en, en_GB in (i) above
4. For yue, the sorting forms need spaces, eg
a. <namePattern>{surname-core}{given-initial}{given2-initial}</namePattern>
b. The FSR will …
=> CLDR-16346 Fix initials 2

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareResolved.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java
CLDR-16239
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
- added option to retain unchanged files (this allows simple generation of a complete set) with -R
- for -f, added printing of number of changes to each file.
- changed fixList.add('V', "Fix values that would inherit laterally", which changes the following paths, but *just* those that inherit laterally:
- if we have an L1 locale, change each ↑↑↑ value
- if we don't have an L1 locale
- change each ↑↑↑ value where its parent bailey value is different.
- ALSO change each null value where its parent bailey value is different. (pulled my hair out for this one). This is done in a new handleEnd()
- Also added a new utility to get the parent chain. After the dust settles, this should probably be moved to a central …
=> CLDR-16239 fix main lateral inheritance

docs/ldml/tr35-keyboards.md, docs/ldml/tr35.md, keyboards/dtd/ldmlKeyboard.dtd, keyboards/dtd/ldmlKeyboard.xsd, keyboards/dtd/ldmlKeyboardTest.dtd, keyboards/dtd/ldmlKeyboardTest.xsd, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
_(Note: Keyboard PR- not for v43!)_
CLDR-15034
Add a `` DTD annotation noting where `\u{…}` escaping is allowed on an attribute.
This does not address changes to UnicodeSet escaping, because there are still open issues around UnicodeSets in keyboard
CLDRFile is not affected, and the escaping is optional.
Currently this annotation is only on Keyboard attributes, so escaping is not permitted on any non-keyboard data items
=> CLDR-15034 kbd: add @ALLOWS_UESC DTD annotation

common/supplemental/likelySubtags.xml
CLDR-16402
A few of the new likelySubtags added per [CLDR-15071](https://unicode-org.atlassian.net/browse/CLDR-15071) / [#2619](https://github.com/unicode-org/cldr/pull/2619) produce errors in CLDR-ICU integration, and do appear to have some problems. This integration comments them out; I have filed https://unicode-org.atlassian.net/browse/CLDR-16405 to fix the issues, and it has details on the specific problems.
[CLDR-15071]: https://unicode-org.atlassian.net/browse/CLDR-15071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-16402 exclude some problematic likelySubtags

CONTRIBUTING.md, README.md, docs/README.md, readme.html, tools/pom.xml, unicode-license.txt
CLDR-16411
Update ICU4J libs to 2023-02-21 (after integration of CLDR 43-alpha1).
Update readme; update copyrights in various docs.
=> CLDR-16411 BRS v43: Update ICU4J libs to 2023-02-21, update readme & copyrights

docs/ldml/tr35-keyboards.md
CLDR-15034
Summary:   `<info normalization=…>` already has the possible values `NFC`, `NFD`, and `other`. 
This notes that `NFC` is required for CLDR's repository, and that tooling would validate for `NFC` or `NFD` values.
If `other` is provided (this is like the 'mixed' @miloush  mentioned) then tooling would not be expected to check the output of the keyboard.
=> CLDR-15034 kbd: spec: NFC as  the preferred form

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/dtd/ldmlKeyboard.dtd, keyboards/dtd/ldmlKeyboard.xsd, keyboards/import/keys-Zyyy-punctuation.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
thanks to @mcdurdin suggestion below, this changes the format to the below. Dropping the `hardware=` attribute, and changing the meaning of `form` to be the hardware type or otherwise `touch`
- more than one hardware layout is allowed per file. This is pursuant to the 'single file' goal. Otherwise we will need one `fr.xml` for US and one `fr.xml` for ISO, etc.
- only one `layers` allowed per 'form'.  So, illegal to have two with `form="iso"`.
```xml
<keyboard>
<layers form="touch" />
<layers form="touch" minDeviceWidth="100" /> 
<layers form="iso" /> 
<layers form="us" /> 
</keyboard>
```
-----
<details><summary>previous format:</summary>
Previously, `form=touch` or `form=hardware`, and a separate attribute for `hardware=iso` etc.  Also previously, only one `hardware` layers was allowed. …
=> CLDR-15034 kbd: spec: move hardware type into 'form'

common/transforms/und-Ethi-t-und-latn-m0-aethiopi-geminate.xml, common/transforms/und-Ethi-t-und-latn-m0-alaloc-geminate.xml, common/transforms/und-Ethi-t-und-latn-m0-beta_metsehaf-geminate.xml, common/transforms/und-Ethi-t-und-latn-m0-ies-jes-1964-geminate.xml
CLDR-16408
In the non-BCP-47 aliases for the newly-added Ethiopic Geminate transforms, the fragment -Geminate (or in one case -Geminated) needed to instead use an underscore, since it is part of a complete variant name such as ALALOC_Geminate or  IES_JES_1964_Geminate. Otherwise ICU could not parse the name.
=> CLDR-16408 in Ethiopic transform aliases, -Geminated? → _Geminate

common/main/xh.xml
CLDR-16416
Fix _data_ errors from running tests on production data in cldr-staging. The only such item was removal of bogus `minimalPairs` in `xh`.
=> CLDR-16416 xh, delete bogus minimalPairs

common/properties/coverageLevels.txt, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartLocaleGrowth.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
CLDR-16346
common/properties/coverageLevels.txt
- 3 locales lowered in coverage, while one improved
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartLocaleGrowth.java
- (techdebt) separated out from ShowLocaleCoverage, since the code is entirely orthogonal.
- In so doing, changed many public items to private
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- (techdebt) separated out ChartLocaleGrowth, since the code is entirely orthogonal.
- In so doing, changed many public items to private
- Removed the contents of SUPPRESS_PATHS_AFTER_SUBMISSION. Those were in place for the late-breaking changes in v42.
tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
- Three lines were producing the inverted results from previous changes to …
=> CLDR-16346 fix glitch in coverage charts

common/main/br.xml, common/main/bs.xml, common/main/eu.xml, common/main/he.xml, common/main/id.xml, common/main/is.xml, common/main/ms.xml, common/main/nl.xml, common/main/ro.xml, common/main/sc.xml, common/main/so.xml, common/main/sv.xml, common/main/to.xml, common/main/vi.xml, common/main/yi.xml, common/main/zu.xml
CLDR-16419
CLDRModify passes none, -fQ, -fP before alpha2 integration & tag.
The changes are:
1. Space normalization for recently-added items, mostly or all from https://github.com/unicode-org/cldr/pull/2722 (inheritance hardening)
2. Exemplar reordering in `he`/`yi` due to the recent collation changes for geresh/gershayim etc.
=> CLDR-16419 CLDRModify changes: space fixes for newly added items, exemplar reorder for geresh/ayim

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculatedCoverageLevels.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java, tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCalculatedCoverageLevels.java
- fixes for CoverageLevel reader
- add `und` to coverageLocales.txt for convenience 
- maybe a new command line option ✨ 
CLDR-16425
=> CLDR-16425 v43 BRS: JSON

docs/ldml/tr35.md
CLDR-16428
The old HTML spec had subscripts: https://www.unicode.org/reports/tr35/tr35-61/tr35.html#Likely_Subtags
The subscripts seem to have gotten lost in Markdown. I added them back with HTML.
=> CLDR-16428 spec: Fix formatting of likely subtags algorithm

common/main/ja.xml, common/main/zh_Hant.xml
CLDR-16355
Translation of TRY (Turkish Lira) in Japanese and Traditional Chinese includes the word “new”, likely from it being called “New Turkish Lira” in the past. This PR removes "new" from the translation in both. It also updates zh_Hant translation of TRL to include year interval to avoid name collision.
=> CLDR-16355 ja zh hant remove new from try

tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
-Simply return parameter unchanged for WebContext.decodeFieldString
-Comments
CLDR-16192
=> CLDR-16192 Admin email encoding failure for non-ASCII text

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
-Revise SurveyForum.userCanUsePostType, isPhaseReadonly only matters for non-TC
-Refactor with boolean isTC to avoid calling userIsTC repeatedly
CLDR-11368
=> CLDR-11368 Enable Forum posting by TC even when read-only

tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
- personNames was OK, just needed to fix test exclusion
- also fix a TODO from CLDR-14421 - unitIdComponents.json’s _values is now an array
CLDR-16373
unitIdComponents.json now looks like this:
```json
"prefix": {
"_values": [
"arc",
"british",
"dessert",
"fluid",
"light",
"nautical",
"xxx",
"x",
"curr"
]
}
```
=> CLDR-16373 v43 BRS: json, fix personNames, unitIdComponents

common/dtd/ldml.dtd, docs/ldml/tr35-personNames.md
CLDR-16433
1. Removed prefixed section numbers from anchors (unfortunately, this caused many lines to change)
2. Dropped that this is tech preview
3. Changed prefix and suffix fields to title, generation, and credentials
4. Changed 6.5 to cover 2 topics, and made them 6.5.1 and 6.5.2
5. Described how to coalesce literals (and revamped the rest of the description)
6. Fixed the sample name categories
7.  Deleted some examples in 8.2 that aren't needed or are not explained clearly.
8. Fix the second on locales with scripts that don't need spaces between words.
=> CLDR-16433 Document changes in person names

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListCoverageLevels.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/CheckLdmlDtdReferences.java
=> CLDR-8956 add tool for missing dtd items in spec

common/dtd/ldml.xsd, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/dtd/ldmlKeyboard.dtd, keyboards/dtd/ldmlKeyboard.xsd, keyboards/dtd/ldmlKeyboardTest.dtd, keyboards/dtd/ldmlKeyboardTest.xsd, keyboards/import/keys-Zyyy-currency.xml, keyboards/import/keys-Zyyy-punctuation.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
CLDR-15034
a few fixes:
- …
- 
=> CLDR-15034 kbd: update DTD, import should have distinguishing attrs

docs/ldml/tr35-personNames.md, docs/ldml/tr35.md, tools/scripts/tr-archive/fix-tocs.js
CLDR-16122
- also drop some extra whitespace
- regen ToC using `cd tools/scripts/tr-archive ; npm ci ; npm run fix-tocs`
- fix the generator tool to not add extra junk on top of the tr35 ToC
Note that this tool runs automatically before the HTML is published.
=> CLDR-16122 v43 spec: regenerate ToC

keyboards/3.0/mt-t-k0-47key.xml
CLDR-15034
Missed in recent spec changes… with these, the sample kbds compile except for:
- some `<vkeys>` issues in french
- bksp / enter / extra keys, already on the agenda for discussion
=> CLDR-15034 kbd: fix: fixes noted by keyman

common/bcp47/currency.xml, common/bcp47/segmentation.xml, common/bcp47/timezone.xml, common/bcp47/variant.xml
CLDR-16450
In bcp47 data:
- Add missing since= attribute for tags added since CLDR 21 that did not already have them.
- Update currency descriptions to match currency names in en.xml (but AsCII only, so e.g. change en-dash to hyphen-minus).
=> CLDR-16450 bcp47: Add missing since= attributes, update currency descriptions

readme.html
CLDR-16470
This was supposed to update both the IU4J libs in CLDR to the latest ICU version, and update the readme in CLDR for beta1. Unfortunately it only does the latter; a recent change in ICU4J per https://github.com/unicode-org/icu/pull/2326 eliminates from core the classes UnicodeMap and ElapsedTimer that a lot of CLDR code depends upon, so we cannot use the current ICU4J libs. 
=> CLDR-16470 BRS v43: update readme for beta1

tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteType.java
-New enum VoteType in its own file VoteType.java
-New vote_type column in db table cldr_vote_value_44 (and later)
-New methods for submitting vote with vote type; default to VoteType.DIRECT
-Remove BallotBox.VOTE_IS_AUTO_IMPORTED, use VoteType.AUTO_IMPORT instead
-For VoteType.MANUAL_IMPORT (anonymous) do not trigger automatic forum posts
CLDR-15850
=> CLDR-15850 Collect type of vote: direct, auto/manual import, bulk upload

common/testData/localeIdentifiers/localeCanonicalization.txt, tools/cldr-code/src/main/java/org/unicode/cldr/util/LsrvCanonicalizer.java
=> CLDR-16476 fix problem in locale canonicalization.txt

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/CheckPersonNamesTest.java, tools/pom.xml
CLDR-16477
Update CLDR to ICU4J libs as of 2023-03-15 (not that compatibility issues have been fixed), update CheckPersonNamesTest.java to use latest PersonNameFormatter API in ICU.
=> CLDR-16477 BRS v43: Update ICU4J libs to 2023-03-15, CheckPersonNamesTest to new API

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
CLDR-16468
- add a `-R` option to include the old redundant data (off by default)
- will make JSON much smaller
- cosmetic improvements to the progress bars
- apidoc improvements to CLDRFile
Example of data no longer included: (composite diff)
```diff
-          "apc": "apc",
-          "hi-Latn": "الهندية (اللاتينية)",
-            "lepc": "lepc",
-            "limb": "limb",
-            "mathbold": "mathbold",
-            "mathdbl": "mathdbl",
-            "mathmono": "mathmono",
-            "mathsanb": "mathsanb",
-            "mathsans": "mathsans",
```
```diff
-            "symbol": "ADP"
```
```diff
-          "ABL1943": "ABL1943",
-          "AKUAPEM": "AKUAPEM",
-          "ALALC97": "ALALC97",
-          "ALUKU": "ALUKU",
-          "AO1990": "AO1990",
-          "ARANES": …
```
=> CLDR-16468 v43 JSON drop code_fallback and constructed data

tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/FormattedFileWriter.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateChangeChart.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/analytics.html, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/chart-template.html
CLDR-16389
- we had at least 2 different versions of the tags, consolidated
- dropped standardFooter because the FormattedFileWriter already uses chart-template.html which now includes the footer and analytics (no longer at the foot per guidance)
=> CLDR-16389 v43 update analytics tags

tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCalculatedCoverageLevels.java
CLDR-16122
very very minor. But running tests was complaining because there were two test annotations on this test.
=> CLDR-16122 v43 remove noise from test run

common/validity/subdivision.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateValidityXml.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java
- regen subdivision for CLDR-16397
- was needed due to CLDR-16293 CLDR-10923 - CQ
- also, improve skip of copyright lines
CLDR-16122
=> CLDR-16122 v43 BRS codes

docs/ldml/tr35.md, readme.html, tools/pom.xml
CLDR-16509
UPdate ICU4J libs in CLDR to ICU 73rc. Update dates for readme & spec.
=> CLDR-16509 BRS v43: Update ICU4J libs to 73rc, update readme & spec date

docs/ldml/tr35-info.md, docs/ldml/tr35.md
=> CLDR-15861 Add additional spec text around resource inheritance

docs/ldml/tr35-personNames.md, docs/ldml/tr35.md
=> CLDR-16511 flesh out modification section

tools/cldr-apps/js/package-lock.json, tools/cldr-apps/js/package.json, tools/cldr-apps/js/webpack-test.config.js, tools/cldr-apps/js/webpack.config.js
CLDR-16517
Cherry pick of:
- CLDR-16517 v43 use mocha-headless-chrome (#2811)
cherry pick of CLDR-16437 c5724116bbf6b156d390b8eab127cadeaf6d251e
also see CLDR-14408 CLDR-14409
- CLDR-16517 v43 js:(deps-dev): Bump webpack from 5.24.3 to 5.76.0 in /tools/cldr-apps/js (#2781)
cherry pick from CLDR-16437 b7a9c256916012c040176a05012c3269554c4178
=> CLDR-16517 v43 two cherry-picks to unbreak JS

tools/cldr-apps/js/src/esm/cldrCache.mjs, tools/cldr-apps/js/src/esm/cldrForum.js, tools/cldr-apps/js/src/esm/cldrForumPanel.js, tools/cldr-apps/js/src/esm/cldrInfo.js, tools/cldr-apps/js/src/esm/cldrSideways.js, tools/cldr-apps/js/src/esm/cldrTable.js, tools/cldr-apps/js/src/views/InfoPanel.vue, tools/cldr-apps/js/test/TestCldrCache.mjs, tools/cldr-apps/js/test/index.js, tools/cldr-apps/js/test/pretty.sh
-Use LRU cache in cldrForumPanel.loadInfo and cldrSideways.loadMenu to avoid disappearance/reload
-New cldrCache.mjs for simple front-end LRU cache, with unit test TestCldrCache.mjs
-New Refresh button in Info Panel, clears caches and reloads
-Clear forum cache when user submits a post
-Remove cldrForumPanel.appendForumStuff, merge into loadInfo instead
-Encapsulate FORUM_DIV_CLASS (forumDiv) and SIDEWAYS_AREA_CLASS (sidewaysArea)
-Refactor/modernize some related code; reduce cruft; new subroutines to shorten long methods
-Remove dead code (buttonTitle, theForum, replyStub, postUrl, tr.forumDiv.forumPosts, ...)
-Comments
CLDR-16048
=> CLDR-16048 New forum post window sometimes disappears

common/main/ckb.xml
[CLDR-14276](https://unicode-org.atlassian.net/browse/CLDR-14276)
Related (closed) PR was #823 by @jwtiyar. Note for @jwtiyar: the characters you have mentioned in the #823 only h-doucheshme needed replacing. David's suggestions is the bulk of this PR.
[CLDR-14276]: https://unicode-org.atlassian.net/browse/CLDR-14276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-14276 update ckb single character + add locale tags

common/supplemental/supplementalData.xml
CLDR-16122
- Per https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/news/public-notice-redenomination-leone.pdf
- SLL is legal tender through 2023-12-31
- per Bank of Sierra Leone note 2023-03-10
(See CLDR-15900 for prior amendments)
=> CLDR-16122 v43 BRS: ISO-4217 amd 175, SLL -> 2023-12-31

common/supplemental/supplementalData.xml
- cherrypick from #2825 CLDR-16122
- Per https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/news/public-notice-redenomination-leone.pdf
- SLL is legal tender through 2023-12-31
- per Bank of Sierra Leone note 2023-03-10
See CLDR-15900 for prior amds.
(cherry picked from commit 4222a036ecddccaa864d099558523aafd3a97632)
CLDR-16531
=> CLDR-16531 v44 BRS: ISO-4217 amd 175, SLL -> 2023-12-31 (#2825)

tools/cldr-apps/js/src/esm/cldrInfo.js, tools/cldr-apps/js/src/esm/cldrText.js, tools/cldr-apps/js/test/TestCldrCache.mjs
- Restore front-end distinction between hard/soft inheritance, dropped in pr #2433 
- Fix typo in unrelated recent pr #2821
CLDR-16414
=> CLDR-16414 Revision of inheritance (v44)

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDayPeriods.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DateConstants.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DayPeriodInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
- give 1 year for the ISO 4217 to be still in CLDR if it recently expired
- for example, the notice of extension for SLL only came the day after expiration
- also improve the output to include the actual expiration date
CLDR-16316
-----
example output:
> `Warning: (TestSupplementalInfo.java:1445) WARNING: Codes in ISO 4217 and until-recently legal tender in CLDR. (may need to update https://cldr.unicode.org/development/updating-codes/update-currency-codes ): SLL end=Thu Mar 30 17:00:00 PDT 2023`
Previous error:
> `(TestSupplementalInfo.java:1428)  Error: Codes in ISO 4217 but not current tender in CLDR (may need to update https://cldr.unicode.org/development/updating-codes/update-currency-codes ): [SLL]`
=> CLDR-16316 test: make it a warning if a currency code recently expired

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
-Avoid throwing exception with db before version 42, for testing other features than hidden notifications
-Earlier versions had versioned tables like cldr_dash_hide_41 or cldr_review_hide_38
CLDR-16532
=> CLDR-16532 Ignore missing hidden notifications table if db is too old

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java
CLDR-16131
Change the way that an empty value is represented: have it be the collection of Status=value attributes. That preserves a fallback for strange cases, but also lets an empty value be empty.
=> CLDR-16131 fix glych in empty value

docs/ldml/tr35.md, readme.html, tools/pom.xml
CLDR-16549
Update ICU4J libs to version of maint/maint-73 after merge of collation update for quotes. Update dates for readme, spec.
=> CLDR-16549 BRS v43: Update ICU4J libs to 2023-04-06 with coll fix; update readme & spec dates

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
=> CLDR-16532 Follow-up: define constant FIRST_DB_VERSION for magic number 42

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java
CLDR-16538
Notes for reviewers
- I did a bit of refactoring so that I could do more rapid turnaround. That involved inlining private static StringWriter printLanguageData(...), so that disappeared (lines 104...), plus a flag to exit early.
- The only substantive changes are at line 936 and following. I reordered the columns, reset the sorting priority, and dropped the setSpanRows(false).
- At line 958, I disabled the normal handling of 'und' for the target language, so that it would be in an appropriate place.
- At line 962, I reordered the data in the cells to match the column headers.
I uploaded to the the chart to cldr-staging so that the results can be checked. It should show up soon (check that the date says 2023-04-11) at https://cldr-smoke.unicode.org/staging-dev/charts/43/supplemen …
=> CLDR-16538 B Revise the likely subtags chart

tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
-Revert pending redesign
CLDR-16560
=> CLDR-16560 Requirements for storing inheritance marker, revert last PR

tools/cldr-apps/pom.xml, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/KeepLoggedInManager.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java, tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestKeepLoggedInManager.java, tools/pom.xml
- does not replace or modify the X-SurveyTool-Session
- JWT payload is just the subject with the user's id
- secret key is managed automatically
CLDR-16570
=> CLDR-16570 retire old cookies, use a jwt for keep-logged-in

tools/cldr-code/src/main/java/org/unicode/cldr/tool/Option.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/PathInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/resolver/CldrResolver.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/GlossonymConstructor.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleInheritanceInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/With.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCldrResolver.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java, tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/common/dtd/ldml.dtd, tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/common/main/root.xml
CLDR-16390
- new tool PathInfo
- Option.getHelp() now public and useful
- new class LocaleInheritanceInfo to track inheritance traces
- added documentation to With for using forEach
- updated XMLSource.getPathLocation mechanism to track LocaleInheritanceInfo details
- added code to CLDRFile.getName to track glossonymn construction
=> CLDR-16390 Tooling and functions for Inheritance Explaining

CONTRIBUTING.md, README.md
- per licensing and new CLA
- wording matches Unicode's standard file https://github.com/unicode-org/.github/blob/main/.github/CONTRIBUTING.md
CLDR-16466
fyi @annebright
=> CLDR-16466 updates to CONTRIBUTING.md and README.md

docs/ldml/tr35.md
- leftover merge conflict marker
CLDR-16577
=> CLDR-16577 fix typo in markdown

tools/cldr-apps/js/src/esm/cldrInheritance.mjs, tools/cldr-apps/js/src/views/InheritanceExplainer.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Inheritance.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/PathInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleInheritanceInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
- update the implementations behind getPathsForValue to keep going when a hard value is hit. Won't affect getSourceLocale, etc, return values,
but will populate the tracing list with additional values.
CLDR-16390
-----
Example output:
```
• //ldml/localeDisplayNames/territories/territory[@type="PM"]
• 576f1c82a03a22a8
• Value: Saint-Pierre-et-Miquelon
• Inheritance chain:
• value: en_CA://ldml/localeDisplayNames/territories/territory[@type="PM"]
• value: en://ldml/localeDisplayNames/territories/territory[@type="PM"]
• none: root://ldml/localeDisplayNames/territories/territory[@type="PM"]
• codeFallback: //ldml/localeDisplayNames/territories/territory[@type="PM"]
```
=> CLDR-16390 Bailey explainer

tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXPathParts.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Validity.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParser.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathValue.java
CLDR-16622
Note:
- #2888 fixed the SurveyTool part that exacerbated this
- this implements a minimal SimpleXPathParts class needed for Validity. There may be other clients and improvements.
- There is not a conformance test between XPathParts and SimpleXPathParts.  That should be done before the ticket is closed.
=> CLDR-16622 add SimpleXPathParts and abstract parser, for deadlock

common/dtd/ldml.dtd, common/dtd/ldmlBCP47.dtd, common/dtd/ldmlSupplemental.dtd, keyboards/dtd/ldmlKeyboard.dtd, pom.xml, readme.html, tools/cldr-apps/pom.xml, tools/cldr-code/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-rdf/pom.xml, tools/pom.xml
CLDR-16628
Update maint/maint-43 branch to use version 43.1 (except that spec stays at 43). Update ICU4J libs to latest. Update readme.html date and status.
=> CLDR-16628 BRS 43.1: update CLDR version, ICU4J libs, readme date

common/dtd/ldml.dtd, common/main/en.xml, common/main/en_001.xml, common/main/en_AE.xml, common/main/en_AU.xml, common/main/en_DK.xml, common/main/en_FI.xml, common/main/en_GB.xml, common/main/en_IN.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-16606
Add alt="ascii" versions of standard time formats and availableFormats for en[_*] locales; these have ASCII space instead of NNBSP, and clients can choose to use these instead of the regular time formats if these are experiencing problems with apps that parse time formats in a fragile way and cannot handle NNBSP.
Also:
- Update the LDML dtd accordingly (to allow alt="ascii" as needed).
- Update DAIP so that it normalizes spaces to U+0020 for the alt="ascii" forms (instead of normalizing time format spaces to U+202F for Latn, Greek, Cyrl scripts).
- The alt="ascii" forms are intended to have a relatively short life, and they can be mechanically generated from the non-alt forms. Hence they are not included in modern coverage, and do not appear in Survey Tool. Update tests as …
=> CLDR-16606 add alt="ascii" timeformats with plain space for en*; update dtd, DAIP

tools/cldr-apps/js/src/esm/cldrInfo.js, tools/cldr-apps/js/src/esm/cldrTable.js, tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/PathInfo.java
- add rawEnglish field to DataPage for what was formerly the displayName
- displayName in the voting data is now DAIP processed
- remove DAIP normalization from STFactory, it should be done by callers, and not done on DB values. CLDR-16105
- PathInfo CLI tooling to test DAIP
Still some rough edges:
1. ST doesn't always recognize the display value as the one you were voting for, so vote 'jumps' unnecessarily.
2. raw UnicodeSet in the info panel. 
CLDR-13180
=> CLDR-13180 st: use DAIP for English, Root, Others

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java
-Change VoteResolver.DROP_HARD_INHERITANCE to true
-When needed to meet requirements, change INHERITANCE_MARKER to Bailey or vice-versa
-New method STFactory.PerLocaleData.reviseInheritanceAsNeeded called by setValueFromResolver
-New method VoteResolver.reviseInheritanceAsNeeded called by STFactory.PerLocaleData.reviseInheritanceAsNeeded
-New unit test TestVoteResolver.testReviseInheritance for VoteResolver.reviseInheritanceAsNeeded
-Remove DataPage.DataRow.inheritsFromRootOrFallback, no longer necessary or appropriate
-Make isBaselineValue true for inheritance marker in DataPage.DataRow.addItem when appropriate to display star
-Comments
CLDR-16560
=> CLDR-16560 Requirements for storing inheritance marker

common/segments/root.xml
CLDR-16634
Revert the change which included '@' in ALetter for wordbreak, i.e. revert #2256.
=> CLDR-16634 revert #2256 which included @ in ALetter for wordbreak

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckExemplars.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateIndexCharacters.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/FormatterParser.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnicodeSetPrettyPrinter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
CLDR-4903
This is to handle the 3 changes listed in https://unicode-org.atlassian.net/browse/CLDR-4903?focusedCommentId=169687
Some more notes:
This clearly separates the three different string forms of UnicodeSet
- the plain form coming from calling unicodeSet.toString() or .toPattern(), and produced by new UnicodeSet()
- the prettier form used internally to XML. This is valid UnicodeSet, but is formatted to group the elements differently, eg in sorting order according to the locale. This is handled by UnicodeSetPrettyPrinter, with parse and format methods. (The parse method just calls new UnicodeSet, since the prettier form is still valid UnicodeSet input.)
- a new display form for vetters, that simplifies the syntax to help prevent them from making mistakes, handled by …
=> CLDR-4903 Correct ordering etc

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/js/src/esm/cldrForumFilter.mjs, tools/cldr-apps/js/src/esm/cldrForumType.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs
-New cldrForumType.mjs encapsulates constants DISCUSS, REQUIRE, etc.
-Move prefill messages to cldrText.mjs
-Do not use Info Panel for the brief guidance message, show it inline instead
CLDR-14380
=> CLDR-14380 Follow-up refactoring and no Info Panel for forum help

docs/ldml/tr35-keyboards.md, keyboards/dtd/ldmlKeyboard.dtd, keyboards/dtd/ldmlKeyboard.xsd, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
CLDR-15034
- also, re-add `display id=` to the DTD which was in-spec but missing from DTD
FYI @eggrobin — this makes the spec match the DTD
=> CLDR-15034 kbd: clarify identifier restrictions per DTD

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DowngradePaths.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocalePathValueListMatcher.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/downgrade.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathLookup.java
CLDR-16654
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
- add a new option, -fD for downgrade
tools/cldr-code/src/main/java/org/unicode/cldr/util/DowngradePaths.java
- simple API for calling from CLDRModify, and later while importing votes
tools/cldr-code/src/main/java/org/unicode/cldr/util/LocalePathValueListMatcher.java
- regex matcher for <locale, path, value>
- doesn't need to be highly optimized, because it isn't on critical paths. 
tools/cldr-code/src/main/resources/org/unicode/cldr/util/downgrade.txt
- a data file read by DowngradePaths.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathLookup.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
- adds basic unit tests for LocalePathValueListMatcher and Downgrade …
=> CLDR-16654 Add tool and code for downgrading <locale, path, value> matches

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
CLDR-16322
The idea here is to have the SurveyTool show personName patterns with a  grouping and tagging that matches the personName report. So this puts the patterns into 5 groups, in the following order:
1. Main patterns for order givenFirst
2. Main patterns for order surnameFirst
3. Sorting patterns (order is sorting, usage is referring)
4. Monogram patterns for order givenFirst (usage is monogram)
5. Monogram patterns for order surnameFirst (usage is monogram)
Within the first two sections, individual items are tagged with length-usage-formality[-alt], but ordered by length, formality then usage as in the report.
In the other sections, items are only tagged with length-formality[-alt], since usage is implied by the section (for sorting it is referring, for monogram it is monogram). …
=> CLDR-16322 Make SurveyTool personName pattern ordering as in personName report

common/main/root.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
CLDR-16365
Restore Beaufort to root and undo the test skips added when it was removed from root. This reverts the parts of #2696 related to Beaufort.
=> CLDR-16365 Restore Beaufort to root, remove test skips

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
CLDR-16630
- appends the escapes used in the set, and their short names
tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java
- more cleanup, changed the ordering to group better, enhanced names
- Also changed ZWSP to WNJ, as per other ticket
- cleaned up API a bit, added utilities, changed names (some of this percolates into other files)
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
- enhanced the verbose option to print a table we can use in the Sites documentation
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java
- Added the paths with UnicodeSet values. The examples need flushing when the winning value changes, since they …
=> CLDR-16630 Further cleanup of unicode set escaping

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/views/AnnounceForm.vue, tools/cldr-apps/js/src/views/AnnouncePost.vue, tools/cldr-apps/js/src/views/MainHeader.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleList.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleSet.java
-New pulsating balloon 🎈 emoji link in main header with unread count, if nonzero
-Remove the word Menu adjacent to ☰ icon in main header to make more room
-New cldrAnnounce.getUnreadCount, etc.
-Fix db bugs: no DB_SQL_IDENTITY for ANNOUNCE_READ; skip add/deleteCheckRow when superfluous
-Add primary key for ANNOUNCE_READ on announce_id,user_id
-New api/locales/combine-variants converts fr_CA to fr (etc), and normalizes
-Form for entering locales calls combine-variants automatically
CLDR-13962
=> CLDR-13962 Announcements: show in header if unread; fix db; fix locales

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/downgrade.txt
CLDR-16534
One part of changing the islamic calendar display names to use Hijri: Downgrade the relevant paths.
=> CLDR-16534 Downgrade paths for islamic calendar display names (renaming to use Hijri)

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16384
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- In setCldrFileToCheck, compute the Modifiers that are allowed in this locale (depending on grammar) and cache.
-  checkPersonNamePatterns adds some parameters, and now checks for the allowed Modifiers
- changed \" to «, etc. Makes dealing with test easier.
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
- Added the capability to have personNames as a scope for grammar. Unused right now, but will add in release.
- added constants and utilities to Modifier. For now, just two grammatical categories; may add more later (We need to tell vetters that if they need more than these, they need to …
=> CLDR-16384 add grammatical modifiers

tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/views/InfoPanel.vue, tools/cldr-apps/js/src/views/InheritanceExplainer.vue
-Change [This item is inherited] to [This item is inherited from the ... locale]
-Change [This item is aliased from another location] to either [This item is inherited from another field in this locale] or [This item is inherited from another field in the ... locale]
-Rename with item_description_... instead of pClass_... for clarity
-Change styles of some Info Panel buttons to match other buttons (e.g., Dashboard)
-Make some hover titles more descriptive: Close the Info Panel, Reload the Info Panel, Explain inheritance for this item
-Link the Inheritance Explainer window to its button; add a Close button
CLDR-16339
=> CLDR-16339 Improve inheritance messaging

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
-In DataRow.getVoteVHash inherited value matches inheritance marker and vice-versa
CLDR-16680
=> CLDR-16680 Fix bug preventing voting for aliased values

docs/ldml/tr35.md
(cherry picked from commit 5f36fda0dea159aa5856a7d27d019062693df312)
CLDR-16629
The fix for 43.1 issue [CLDR-16629](https://unicode-org.atlassian.net/browse/CLDR-16629) (Many (almost most) "und_" + 3 digits entry in likelySubtags.xml will produced suprising results.) was committed to main, cherry-pick it to the maint/maint-43 branch
[CLDR-16629]: https://unicode-org.atlassian.net/browse/CLDR-16629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-16629 Account for macroregions in likely subtags (#2913)

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-15622
Add more examples for date-time combining formats. Previously we showed examples of combining a date and a time, each of the length matching the length of the combination format. But that does not illustrate all of the grammatical issues, nor the different between the standard combining formats and the new "atTime" version. So chnage the examples as follows:
- For all types, show
- date (of same length as combo format) with a single full time
- date (of same length as combo format) with a single short time
- For the standard patterns, add
- date (of same length as combo format) with a short time range
- relative date with a short time range
- For the atTime patterns, add
- relative date with a single short time
This gets a little complex because
- We …
=> CLDR-15622 Add more examples for date-time combo formats (std, atTime)

common/main/en.xml, common/main/mic.xml, common/main/mic_CA.xml, common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
CLDR-16482
Add core data for `mic`. Change the English name from Mi'kmaq to Mi'kmaw (note that English uses a straight quote, while `mic` itself uses 02BC for instance in its autonym Lʼnuiʼsuti). Data from Alla Shashkina and Dragan Bešević (with input from Mi'kmaw Kina'matnewey), I just made the CLDR PR.
Also note:
- We already included the display name for `mic` in modern coverage.
- It was also already in attributeValueValidity.xml
- We also already had territoryInfo data for `mic` in Canada.
=> CLDR-16482 Add core data for mic, change English name to Mi'kmaw

tools/cldr-apps/js/src/esm/cldrBulkClosePosts.mjs, tools/cldr-apps/js/src/esm/cldrFlagged.mjs, tools/cldr-apps/js/src/esm/cldrForumParticipation.mjs, tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrListEmails.mjs, tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/esm/cldrVettingParticipation.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Do not use the Info Panel for specials; instead, show guidance inline for Bulk Close Posts, Flagged Items, List Emails, Vetting Participation
-Remove Forum Participation guidance, was useless: This is the Forum Participation page
-Usage of Info Panel for specials needlessly complicated the code; simplification facilitates modernization
-Refactor cldrInfo.mjs slightly to facilitate further changes and modernization
-Rename pucontent to itemInfoElement for clarity
-In cldrLoad, use notification.error instead of cldrInfo.showMessage to report problem loading data
-Fix bug in cldrForumParticipation.mjs discovered while testing: no json in error handler
-Fix bugs in cldrListEmails.mjs discovered while testing: import cldrRetry; no json in error handler
-Remove dead code in cldrVote.mjs …
=> CLDR-7536 Info Panel not for specials; preliminary refactoring

.github/workflows/production.yml
CLDR-16663
Example tag: https://github.com/unicode-org/cldr/releases/tag/production%2F2023-05-27-1924z
Example run: https://github.com/unicode-org/cldr/actions/runs/5100418543
=> CLDR-16663 Fix production tagger

common/dtd/ldmlSupplemental.dtd, common/supplemental/coverageLevels.xml
CLDR-16699
Give unit speed-beaufort modern coverage only for selected regions (where it is known to be used), but make it comprehensive for other regions should they choose to add localized data for it.
To do this I had to re-enable (in the dtd) explicit use of coverage level "comprehensive" in coverageLevels.xml. It already seems to be handled correctly elsewhere (e.g. in tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java).
=> CLDR-16699 add modern coverage for beaufort in selected regions, re-enable use of comprehensive

tools/cldr-apps/src/main/webapp/surveytool.css
-In the Info Panel, wrap links with long URLs to avoid horizontal scrollbar
-Apply the style word-wrap: break-word to a[href] within class sidebyside-narrow
CLDR-15371
=> CLDR-15371 Fix broken links, wrap long URLs

CONTRIBUTING.md
The previous link led to a 404 error.
CLDR-16700 Maven setup link in CONTRIBUTING.md is broken
=> CLDR-16700 Correct link to Maven setup in CONTRIBUTING.md

tools/cldr-apps/js/src/views/AnnouncePost.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java
-Fix message display, no boolean orgsAll, instead Organization(s): Mine/TC/All
-Improve display of Locale(s) line in the email, put All if null/empty; two newlines
CLDR-13962
=> CLDR-13962 Announcements: bug fix, orgs not orgsAll; improve email

tools/cldr-apps/js/src/esm/cldrAddAlt.mjs, tools/cldr-apps/js/src/esm/cldrCoverageReset.mjs, tools/cldr-apps/js/src/esm/cldrDash.mjs, tools/cldr-apps/js/src/esm/cldrForumPanel.mjs, tools/cldr-apps/js/src/esm/cldrGui.mjs, tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrNotify.mjs, tools/cldr-apps/js/src/esm/cldrProgress.mjs, tools/cldr-apps/js/src/esm/cldrReport.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs, tools/cldr-apps/js/src/esm/localesTxtGenerator.mjs, tools/cldr-apps/js/src/views/CldrRows.vue, tools/cldr-apps/js/src/views/DashboardWidget.vue
-Get rid of cldrInfo.showWithRow to simplify cldrInfo and use more modern notifications
-New cldrNotify.mjs with three methods: show, warning, and error
-In JavaScript, always throw new Error instead of throw string so e.message is defined
-Also throw new Error instead of throw Error, for consistency (although they are equivalent)
CLDR-7536
=> CLDR-7536 New cldrNotify to replace showWithRow and encapsulate notification

tools/cldr-apps/js/src/esm/cldrNotify.mjs, tools/cldr-apps/js/src/esm/cldrRetry.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Call new cldrNotify.errorWithCallback, with cldrLoad.reloadV to avoid leaving the submission pop-up visible
-This change only affects the behavior when the back end does not return OK (200)
CLDR-16721
=> CLDR-16721 Show a notification if there is an error for a newly submitted value

tools/cldr-apps/js/src/esm/cldrInheritance.mjs, tools/cldr-apps/js/src/views/InheritanceExplainer.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Inheritance.java
- routine on STFactory to calculate if an xpath is hidden
- also, add generated XPaths to the XPathTable
CLDR-16390
Half (back end) implementation for the issue of the broken jump button.  Adds a `hidden: true/false` property to the API. 
Update:  including Front End  also, see image
for path `/cldr-apps/v#/de/Duration/1aab94512d97c3fd`
=> CLDR-16390 inh explainer: add 'hidden' property

common/collation/root.xml
CLDR-16669
Update the collation root.xml file with the unihan-index.txt contents which has changes for Unicode 15.1 (new radicals).
@markusicu forgot to update this file in PR #3007.
=> CLDR-16669 Update collation root from unihan-index

docs/ldml/tr35.md
(cherry picked from commit 37d524354422f46731db74f3bd6b3f46516c3ced)
CLDR-16756
Cherry-pick from maint/maint-43 to main the fix in #3037 for the spec modifications section
=> CLDR-16756 Pick from maint-43 to main: fix for CLDR-16629 Add to modifications section in #3037

tools/cldr-apps/js/src/esm/cldrDowngradedVotes.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/esm/cldrVueMap.mjs, tools/cldr-apps/js/src/views/DowngradedVotes.vue, tools/cldr-apps/js/src/views/MainMenu.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/DowngradedVotes.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DowngradePaths.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteType.java
-New cldrDowngradedVotes.mjs, DowngradedVotes.vue, DowngradedVotes.java
-New item in main menu for Admin only: Votes for Downgraded Paths
-The new page shows how many votes for downgraded paths, categorized by vote type
-The new page has a button for deleting the imported votes for downgraded paths
-Revise DowngradePaths.java to make data private
-Revise VoteType.java with added method isImported
CLDR-16681
=> CLDR-16681 Enable gettings stats and deleting votes for downgraded paths

tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBoxXMLSource.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/DelegateXMLSource.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/LocaleMaxSizer.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java, tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestMisc.java
CLDR-16763
Initial work:
- use a real cache instead of homegrown
- initialize the non-resolved XMLSource / CLDRFile in the Per-Locale c'tor instead of deferring
I think initializing the resolved XMLSource might be more challenging because it's reentrant, needs to construct other PerLocaleDatas. 
But perhaps, when, say, French or French in Canada is hit, ST should grab a lock  and initialize ALL `fr*` sublocales right there. That way if  say `fr_FR` and `fr_CA` both got hit at the same time, they wouldn't deadlock on adding `fr` . 
=> CLDR-16763 Reduce deadlocks

common/supplemental/attributeValueValidity.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverage.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-16786
Note: this adds the missing languages (such as aa and osa). I left some duplication in the attributeValueValidity file to make review easier (while ensuring that nothing else changes).
=> CLDR-16786 make languages in CLDR locales' ids available

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
- CandidateItem.rawValue (sic!) can contain INHERITANCE_MARKER, thus failing to retrieve a list of voters.
- Probably only affects UI. It was showing the vote result for inheritance but no voters.
- Also note that the vote transcript was still correct in this case.
CLDR-16815
=> CLDR-16815 fix vote-for-inheritance showing up

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-16841
- Adds the example to unit/unitPattern and /displayName
- The related units are fetched from the UnitConverter, and displayed with each separate example.
- The format is like **1 ounce-troy (US/UK) 🟰 ~82.943 fun (JP)**, so it shows whether a unit is in a country-system (UK, US, or JP), and what the equivalent amount would be in a related unit
tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java
- Add a shorter, simpler way to show units. 
- currently if numerator or denominator are < 20, shows as fraction (or just numerator, if denominator is 1)
- Uses 5 significant digits, and adds ~ if the displayed value is approximate.
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java …
=> CLDR-16841 add examples for units

common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
CLDR-16862
Upgrade sw and zh_Hant_HK to 8-vote minimum
It looks like bg and is had already been upgraded in https://github.com/unicode-org/cldr/pull/2098
=> CLDR-16862 Upgrade sw and zh_Hant_HK to 8-vote minimum

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java
- update VoteResolver to add OrganizationToValueAndVote.totalUndisputedVotes which excludes intra-org disputes.
- add a test
CLDR-16863
=> CLDR-16863 no longer treat org-disputes as disputed

docs/ldml/tr35-keyboards.md
CLDR-15034
Somehow I missed this.  I moved the obsolete `<transforms type="final"/>` examples to become post-reorder examples.
=> CLDR-15034 kbd: remove errant reference to final transforms

README.md, common/main/en.xml, readme.html, tools/pom.xml
CLDR-16898
Besides updating the ICU4J libs to the version of July 20 (version updated to 74.0.1) and updating the readmes, this also add missing short units to en.xml (and completes some narrow logical groups).
=> CLDR-16898 Update ICU4J libs; update date/status in readmes; add missing short units to en

docs/ldml/.markdownlint.json
- makes it easier to use markdownlint on the spec
(cherry picked from commit 9cbcd2b94dcdfe80c00732cbbb4a32175c84c360)
CLDR-15034
=> CLDR-15034 add some .markdownlint.json rules

common/annotations/ku.xml, common/annotations/sr.xml, common/annotations/sr_Latn.xml, common/annotations/zu.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAnnotations.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/test/java/org/unicode/cldr/test/TestCheckAnnotations.java
> `❮Error: The annotation must be a translation and not contain the numeric E- code (E13.1–125)❯`
- Example: E13.1-416
- includes test
CLDR-16882
=> CLDR-16882 check: fail on emoji annotations using the root codes

common/transforms/Any-Accents.xml, common/transforms/Cyrillic-Latin.xml
CLDR-16885
Changes `&amp;` to `&` and `&quot;` to `"`. 
=> CLDR-16885 Fix `&amp;` and `&quot;` usage in transforms

common/dtd/ldmlSupplemental.dtd, common/supplemental/units.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-15296
common/dtd/ldmlSupplemental.dtd
There was no `@MATCH` for the description attributes
common/supplemental/units.xml
The report was that the unit was wrong. At first I thought that it was the case. Wrote a test to verify, and rechecked the conversion factor, which was off slightly from EPA definition. Added an explanation why the unit for `gasoline-equivalent` seems so odd. 
description="Constructed so that 1 gallon-gasoline-equivalent = 33.705 kWh as per https://www3.epa.gov/otaq/gvg/learn-more-technology.htm"
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
Added some utilities for testing
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
Write test to verify that gasoline-equivalent has the right value and unit, and adjust the …
=> CLDR-15296 Fix gasoline-equivalent

common/main/km.xml, common/supplemental/coverageLevels.xml
CLDR-5321
- Update latn digit number formatting
- Change khmr digit formatting moderate and modern coverage as appropriate
=> CLDR-5321 Update latn number formatting

tools/cldr-apps/js/test/pretty.sh
- v3.0 is interesting but changes a lot of source lines
- this locks down the Javascript prettier version to 2.8.8
CLDR-16437
=> CLDR-16437 lock prettier to version 2.8.8

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- update ShowLocaleCoverage to use TempPrintWriter, so it doesn't zap the file before completion
- also makes sure it shows if there's a difference at the end.
CLDR-16945
Just a little improvement to ShowLocaleCoverage …
=> CLDR-16945 BRS v44: update ShowLocaleCoverage

docs/ldml/tr35-keyboards.md
- Update to the TR35 part 7 Keyboard spec, to harmonize with PRI 476 (techpreview)
Co-authored-by: Marc Durdin <marc@durdin.net>
(cherry picked from commit f3d2f68b2843a2e1939191a7ecd18ab974374d0a)
CLDR-15034
=> CLDR-15034 kbd: Keyboard 3.0 Spec

docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
This adds the `@ALLOWS_UESC` DTD annotation, used in the proposed Keyboard DTD.
This annotation on an attribute value indicates that an attribute value MAY contain the `\u{0127}` Unicode escaped format in the attribute.  For example,
```xml
<!ATTLIST key to CDATA #IMPLIED >
```
and then:
```xml
<key id="quote" to="\u{22}"/>
```
- Originally #2642 734b93461ff567458d58e0cd1cb9b679d8cbc506
(cherry picked from commit 38d093341c5205a8523aa3882a800a275072a387)
CLDR-15034
=> CLDR-15034 add @ALLOWS_UESC DTD Annotation

tools/cldr-code/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestMatchValue.java, tools/pom.xml
For the Keyboard spec, we needed to match two additional `@MATCH` types to the DTD.
- `@MATCH:semver` matches a semantic version ([semver.org](https://semver.org)) such as `1.0.0` or `1.2.3-BETA`  - this is used for the keyboard version   
- `@MATCH:validity/bcp47` matches any valid bcp47 id, such as `nod-Lana` or `de-CH-t-k0-windows-extended-var` - this is used for the keyboard locale id
- plus tests
(cherry picked from commit 632c286d8abd7c20a082e749cf67c3b0b264816a)
CLDR-15034
=> CLDR-15034 DTD @MATCH: add validity/bcp47 and semver match types

common/dtd/ldml.dtd
CLDR-16894
Expand the set of values (as specified in the dtd) for some element attributes:
- contextTransformUsage type attribute, add more of the values specified in TR35 that seem useful (including some already used in Apple data we hope to add)
- pattern numbers attribute, add more numbering systems used for days (at least in Apple data we hope to add)
- dateFormatItem/intervalFormatItem id attribute, use a regex for valid values to include a larger set. I did this instead of adding a special MatchValue function for dateSkeleton, since that would have just used a regex anyway, and since there are differences in the types of skeletons that are valid for intervalFormatItem vs dateFormatItem.
=> CLDR-16894 Expand values for contextTransformUsage type, pattern numbers, dateFormatItem/intervalFormatItem id

common/supplemental/units.xml
CLDR-16888
For barometric pressure, remove IN from the list of regions that use inch-ofhg so it falls back to the default (for region 001) hectopascal.
=> CLDR-16888 for barometric pressure, remove IN from regions that use inHg to use default hPa

common/bcp47/timezone.xml, common/dtd/ldmlBCP47.dtd, common/dtd/ldmlBCP47.xsd, docs/ldml/tr35.md
=> CLDR-14453 Adding IANA zone.tab mapping in timezone.xml

common/main/mt.xml
- GMT is already the approved abbreviation, added the English
- added intervalFormatFallback
CLDR-16929
=> CLDR-16929 upgrade: mt to basic

common/main/kxv_Deva.xml
CLDR-16973
For locale kxv_Deva: This adds curly braces around the nukta sequence {ड़} (U+0921U+093C) in the main exemplars. It also updates the punctuation exemplars per CLDRModify -fP. It does *not* update the main exemplars per CLDRModify -fP because that still causes a unit test failure, see https://unicode-org.atlassian.net/browse/CLDR-16980
=> CLDR-16973 kxv_Deva exemplars: enclose sequence {ड़}; update punct exemplars (not main) per CLDRModify -fP

common/main/fy.xml, common/main/ie.xml, common/main/lij.xml, common/main/lmo.xml, common/main/nds.xml, common/main/oc.xml, common/main/prg.xml, common/main/syr.xml, common/main/szl.xml, common/main/vmw.xml, common/main/za.xml
- upgrade Basic paths to unconfirmed for the ones which have been checked:
`fy syr lij szl za prg lmo ie vmw oc nds`
- uses tool from #3170 
CLDR-16929
-----
I re-ran the coverage check,  and this PR upgrades these:
- fy
- lij
- lmo
- oc
- syr
- szl
- vmw
- za
Not sure what's happening with these two:
- prg
- ie
Known issue, to solve separately:
- nds
=> CLDR-16929 CLDRModify -fG upgrades

common/main/sah.xml
CLDR-16929
Add 8 missing items for basic coverage to Yakut (`sah`, a language of `RU`) with status draft="contributed"; all are for `<timeZoneNames>`. Seven of these just use ↑↑↑ to fall back to root (as does Russian for 5 of these items, including gmtFormat and gmtZeroFormat which use "GMT{0}" and "GMT" respectively). For  the eighth item timeZoneNames/metazone[@type="GMT"]/long/standard, we just use "GMT" (there is no explicit root value) since that is also what would be used here (and in Russian) for gmtFormat and gmtZeroFormat.
=> CLDR-16929 Add missing basic items for Yakut (sah)

common/annotations/bew.xml, common/annotations/cv.xml, common/annotations/de.xml, common/annotations/et.xml, common/annotations/fil.xml, common/annotations/gu.xml, common/annotations/he.xml, common/annotations/hu.xml, common/annotations/is.xml, common/annotations/kab.xml, common/annotations/kk.xml, common/annotations/mr.xml, common/annotations/pa.xml, common/annotations/pt_PT.xml, common/annotations/ru.xml, common/annotations/sq.xml, common/annotations/sv.xml, common/annotations/sw.xml, common/annotations/ta.xml, common/annotations/th.xml, common/annotations/to.xml, common/annotations/uk.xml
CLDR-16978
Restore emoji keyword annotations (non tts) that were (seemingly improperly) deleted by the CLDRModify -fQ pass (commit [e8697986ac..](https://github.com/unicode-org/cldr/pull/3165/commits/e8697986ac626738ba3eb3d21a70bb57ac14674a)) in PR [#3165](https://github.com/unicode-org/cldr/pull/3165). In most cases this just involved reverting to the version of the file before that commit (nothing had changed these files since). In some cases there was a little hand editing where CLDRModify -fQ had deleted some annotations but added others.
There is a separate ticket [CLDR-16972](https://unicode-org.atlassian.net/browse/CLDR-16972)  to investigate why these deletions are happening, and fix.
[CLDR-16972]: …
=> CLDR-16978 restore annotations that were deleted by CLDRModify -fQ in e8697986ac..

common/main/ie.xml, common/main/ie_EE.xml, common/main/prg.xml, common/main/prg_PL.xml, common/properties/coverageLevels.txt, common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
- default content and likely subtags are now: ie-EE and prg-PL
- promote the EE and PL territory translations respectively
- adds 'ie' and 'prg' at basic
CLDR-16929
supersedes #3178
=> CLDR-16929 ie and prg promotion

common/main/ckb_IR.xml
CLDR-16986
Restore Persian calendar time formats for ckb_IR, since Persian calendar is default for IR, which is 24 hour calendar cycle, unlike IQ which is default region for ckb.
=> CLDR-16986 Restore Persian calendar time formats for ckb_IR

common/testData/units/unitPreferencesTest.txt
CLDR-16888
Regenerate unitPreferencesTest.txt due to the change in unitPreferences for IN (barometric pressure); also takes into account GB pref change for windspeed (in CLDR-16892).
=> CLDR-16888 Regenerate unitPreferencesTest.txt due to IN prefs change

common/transforms/fa-fa_FONIPA.xml
CLDR-16995
In the new fa-fa_FONIPA transform, one usage of the new variable $IPA_CONSONANT was immediately followed by a combining mark U+0651, so that combination was interpreted as a single undefined variable name. Just added a space to separate the U+0651
=> CLDR-16995 Add space between variable $IPA_CONSONANT and combining mark

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareEn.java
en.txt was really a .tsv, so rename it
- also add a @CLDRTool annotation
CLDR-16994
=> CLDR-16994 tool: CompareEn should write a .tsv file

common/main/en.xml
CLDR-17001
Add English name "Makhuwa" for locale `vmw` now that it is at basic and being converted for ICU.
=> CLDR-17001 en, add display name for locale vmw Makhuwa

common/main/oc_ES.xml
CLDR-17000
oc_ES, promote some latn miscPatterns items to contributed so they are picked up for ICU (the corresponding non-latn miscPatterns items are already confirmed)
=> CLDR-17000 oc_ES, promote some latn miscPatterns items to contributed

tools/cldr-code/src/main/java/org/unicode/cldr/tool/KeyboardFlatten.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/KeyboardTool.java, tools/cldr-code/src/test/java/org/unicode/cldr/tool/TestKeyboardFlatten.java, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-missing.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownbase.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownver.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-wrongparent.xml
_Note: Depends on xsd, #3108 so won't build until that is merged._
- KeyboardTool for keyboard utilities (currently only Flatten)
- Flatten tool will resolve `<imports>` per spec into an import-less file
- includes tests
Originally from (#2633)
CLDR-15034
=> CLDR-15034 kbd: Add a KeyboardTool, and KeyboardFlatten utility

common/supplemental/likelySubtags.xml
CLDR-17019
Re-comment-out the mappings for jrb and jrb_Arab_MA, which had previously been commented out per CLDR-16405 but just got re-added in a different place. They conflict with the metadata aliases treating aju as the primary child of jrb.
=> CLDR-17019 re-comment-out the mappings for jrb and jrb_Arab_MA (which got re-added in a different place)

readme.html, tools/pom.xml
CLDR-17030
Update ICU4J libs in CLDR to ICU version of 2023-08-22, after CLDR release-44-alpha0 integration, after integration of Unicode 15.1 to ICU, and after ICU fees for likelySubtags and PersonNameFormatter.
=> CLDR-17030 Update ICU4J libs #3; update date in readme

tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java
- This was an error in #3114 / CLDR-15034
CLDR-17018
-----
Two things:
- Keyboard updates were originally going to land in v42, we obvously missed that.
- cldr-archive is present but not enabled in exhaustive tests, CLDR-16393 should have caught this.
=> CLDR-17018 fix firstVersion for ldmlKeyboard and ldmlKeyboardTest

common/main/eo.xml
CLDR-15878
I corrected numerous wrongly confirmed items, which couldn't be corrected using the Survey Tool.
- word “mondo” minuscule
- names of countries according to the list of [Bertilo](https://bertilow.com/lanlin/index.html) (and [AdE](https://www.akademio-de-esperanto.org/decidoj/landnomoj/listo_de_rekomendataj_landnomoj/))
- names of languages (mostly) according to the list of [Bertilo](https://bertilow.com/lanlin/lingvoj.html)
- [capitalized months](https://bertilow.com/pmeg/gramatiko/propraj_nomoj/majuskloj.html#i-klc) and names of languages according to recommends in [PMEG](https://bertilow.com/pmeg/gramatiko/propraj_nomoj/landoj_popoloj_lingvoj.html#i-bzv)
- nonreligious terms (_de nia erao/antaŭ nia erao_) for eras and religious terms as variants (_post Kristo/antaŭ Kristo_)
- …
=> CLDR-15878 fixes to Esperanto

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
CLDR-16956
- Adds attributes to missing-basic TSV chart
=> CLDR-16956 BRS v44 generate charts 2

tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
-Call getDistinguishingXPath in CLDRModify to avoid getting bogus code-fallback
-Enhance DisplayAndInputProcessor.filterCoveredKeywords so PANDA BEAR matches panda and bear
-Add a unit test TestFilterCoveredKeywords
-TODO comment, still need retroactive fix for japanse poskantoor | Japanse poskantoor
CLDR-16972
=> CLDR-16972 CLDRModify -fQ is messing up some annotations

common/collation/fi.xml
CLDR-16392
Finnish search collation should be based on the Finnish _default_ sort order, not the _traditional_ sort order. See discussion in the ticket.
=> CLDR-16392 fi search collation should be based on fi default sort, not traditional sort

common/main/en_AU.xml, common/main/en_GB.xml, common/main/en_IN.xml
CLDR-16974
- For en_AU, en_GB, en_IN: Remove comma after weekday if weekday is fully spelled out. (Note, many en_IN formats had a comma before year that was used pretty consistently throughout, did not remove that).
- Update standard full formats to match.
- This was done with reference to the fully resolved date formats in en_001 (parent of all of these), that is, the formats in en_001 with missing values there filled in from en. So some additions you see here replace the format that would have been inherited from en_001 (via ↑↑↑, and then possibly pattern expansion for E → EEEE etc.)
- I did not do this in en_001 itself because it has around 90 other descendants and we do not know whether this change is desirable for all of them, or even for a majority of them.
=> CLDR-16974 en_AU/GB/IN: for yMMMEd fmts, add yMMMEEEEd without comma; en_AU/GB no comma in MMMEd fmts

common/main/es_419.xml, common/main/es_BR.xml, common/main/es_BZ.xml, common/main/es_CO.xml, common/main/es_DO.xml, common/main/es_PA.xml, common/main/es_PR.xml, common/main/es_VE.xml, common/supplemental/supplementalData.xml
CLDR-16358
Change default time cycle from h to H for most es_419 child locales (except BR).
1.  In supplemental `<timeData>`:
- Move es_419 child regions that are actually in Latin America and have primary language Spanish from a section like `preferred="H" allowed="H h hB hb"` to the section that would be obtained by moving h to the beginning, e.g. in this case `preferred="h" allowed="h H hB hb"`.
- Did not do this for BR, though we have es_BR under es_419; the primary language for BR is pt, and pt_BR uses a 24-hour cycle. Similarly, did not do this for es_BZ; the primary language for BZ is en, and en_BZ uses a 24-hour cycle.
- Also added 419 as a region to supplemental `<timeData>`
2. Updated `<timeFormats>` in specific locales
- In es_419, changed standard …
=> CLDR-16358 default time cycle H→h for es_419 children in Latin Amer except BR,BZ

common/annotations/ha_NE.xml, common/annotations/sr_Latn.xml, common/annotations/sr_Latn_BA.xml, common/annotations/yo_BJ.xml, common/annotationsDerived/sr_Latn.xml, common/annotationsDerived/sr_Latn_BA.xml, common/annotationsDerived/yo_BJ.xml, common/main/ha_NE.xml, common/main/sr_Latn.xml, common/main/sr_Latn_BA.xml, common/main/yo_BJ.xml
CLDR-17073
This is a replacement for [PR #3248](https://github.com/unicode-org/cldr/pull/3248) since I could not figure out how to undo the CLDRModify -fp (lowercase) in that one. But note: Unlike that one, this one was begun **after** [PR #3259](https://github.com/unicode-org/cldr/pull/3259) was merged (which ran the 3 standard CLDRModify passes), so there are some differences. And the CLDRModify step for this one (using -fP, uppercase P) produced no changes.
For this one:
1. CLDRileTransformer, no arguments, produced commit 1
2. CLDRModify -fP for the files modified in step 1, produced no changes
3. GenerateDerivedAnnotations, no arguments, produced commit 2
=> CLDR-17073 regen algorithmic locales before alpha2

common/main/qu.xml, common/supplemental/supplementalData.xml
CLDR-16358
In the original [PR 3244](https://github.com/unicode-org/cldr/pull/3244) for this I neglected two things:
- When I moved BO, EC, PE from preferred cycle H to h in timeData, I did not see that there were also separate entries for `es_BO`, `es_EC`, and `es_PE`. Those just need to be deleted.
- The `gu` locales (for BO, EC, PE) now need to have explicit 12-hour standard time formats, instead of inheriting the H format from root.
=> CLDR-16358 Fix timeData for es_BO/EC/PE; qu_BO/EC/PE locales should use region pref cycle h

common/supplemental/likelySubtags.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
CLDR-16405
It was hard to know exactly how to fix this issue without knowing the failure in ICU, but I took a shot.
The commented lines were in fact superfluous, and I removed them (or replaced them). For an example of replacement, see from="rom_Cyrl_BG" to="rom_Cyrl_BG".
I also wrote a test to find any other superfluous lines. It exposed those and some others in the sil1 data, plus a few in the non-sil1 data. I manually fixed 3 non-sil1 data cases also, and filed a ticket to fix the others (it takes a bit of thought for each one to see the right approach.)
So hopefully that works.
=> CLDR-16405 Fix odd likelySubtags, and add test

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/test/fr-t-k0-azerty-test.xml, keyboards/test/ja-Latn-test.xml, keyboards/test/pt-t-k0-abnt2-test.xml
- for consistency, only \u{…} format escaping is supported.
CLDR-16825
=> CLDR-16825 kbd: drop \u1234 format escaping

tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
-Do not obtain keyword path by removing type=tts
-Two passes through the CLDRFile: first pass gets keyword paths, second pass revises based on tts path
-In general, the old keyword path derived from tts path by removeAttribute had wrong draft status
-New DisplayAndInputProcessor.filterKeywordsDifferingOnlyInCase, collapses Panda | panda
CLDR-17063
=> CLDR-17063 CLDRModify -fQ keyword draft-status bug fix; also, collapse Panda | panda

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
-Start at 8:00 am PT (America/Los_Angeles); typical duration is eight minutes
-Purpose of the change is for snapshot to be more up to date for morning meeting
CLDR-16965
=> CLDR-16965 Move Automatic Snapshot time later so still finished by 8:30 am

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-New CLDRModify -fZ, Zero lateral, replace INHERITANCE_MARKER with bailey for all lateral inheritance
-For -fZ new boolean CONSTRUCTED_PSEUDO_PATH_NOT_LATERAL in VoteResolver#reviseInheritanceAsNeeded, no change in behavior as it stands
-Revise CLDRModify -fV, values that would inherit laterally, do not crash if parentValue is null
-Comments
CLDR-16372
=> CLDR-16372 Code to replace lateral inheritance markers in trunk

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
- decided to drop this feature from keyboards, for now
CLDR-17093
=> CLDR-17093 kbd: remove vkeys

docs/charts/keyboard/build.mjs, docs/charts/keyboard/static/keyboard-chart.js
The keyboard charts had broken
CLDR-17078
=> CLDR-17078 kbd: fix chart breakage from keyboard to keyboard3

common/segments/en_US_POSIX.xml, common/segments/root.xml
CLDR-17126
Update CLDR segmentation tailorings to reflect word break tailorings updates in ICU 74 (CLDR 44 did not make any tailoring updates that need to be synced to ICU).
=> CLDR-17126 Update CLDR segment tailorings to reflect ICU 74 word break changes

common/main/fr.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/DayPeriodInfo.java
CLDR-17129
Notice this when investigating a problem in production data with `fr_CA` abbreviated day periods longer than wide.
`fr` was inconsistent in naming of day periods. In most cases (including for different widths) is used forms of "matin" (morning) for both morning1 and night1 (as did `fr_CA`); however for format abbreviated it used "nuit" (night) for night1. I first thought the use of "matin" for night1 was an error until I read the Survey Tool forum comments; the vetters for fr (and fr_CA) all agreed that the period 00:00-04:00 (night1 for fr) should be referred to using morning ("matin"), along with the the period 04:00-12:00 (morning1). So the only necessary consistency change was to fix the one place that instead used "nuit" for night1, and change it to "matin".
Also (as a …
=> CLDR-17129 Fix inconsistency in fr dayPeriods for night1; always use [du] matin, not [de la] nuit

common/main/en.xml, common/main/root.xml
CLDR-16543
I didn't move `Kostanay` and `Uzhhorod` to `root`, as these seem to be English names (the strict romanization is different).
=> CLDR-16543 Fix exemplar cities

common/main/fil.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/DayPeriodInfo.java
CLDR-17035
Quick fix for dayPeriods in `fil`. There were a couple of issues:
- Standalone wide just used ↑↑↑; not sure what it was inheriting from. Copied the standalone abbreviated (which are actually wide) to standalone wide to ensure correct values (without ng).
- Vetters wanted to use the same name ([ng] gabi) for both evening1 and night1, but tests were preventing that, leading to strange values (like format abbreviated using "ng gabi" for one and "gabi" for another, when they should both be "ng gabi" for format style(. Fixed the tests to allow the same values for evening1 and night1 if night1 ends at 24:00.
=> CLDR-17035 fil use gabi for eve/night (with ng for format), add standalone wide

docs/ldml/tr35-dates.md, docs/ldml/tr35.md
CLDR-16866
Note: it is slightly different than the ticket algorithm. I realized that the sd can only conflict with the region subtag if there is an explicit region subtag, so reordering the explicit region subtag first makes the exposition a bit simpler.
=> CLDR-16866 Add algorithm for first day of week.

docs/ldml/tr35-personNames.md
CLDR-16403
There is a lot of overlap between this ticket and https://unicode-org.atlassian.net/browse/CLDR-17124. I went ahead and included the extra text for nativeSpaceReplacement (replacing some old text), so I think we can mark https://unicode-org.atlassian.net/browse/CLDR-17124 as a duplicate.
=> CLDR-16403 Add v44 PersonName features

common/collation/sv.xml, docs/ldml/tr35.md
CLDR-16638
However we should consider formally deprecating "reformed" as a collation type, I filed https://unicode-org.atlassian.net/browse/CLDR-17143 for that (and then we can get the Unicode FAQ updated, etc.). With this PR I have removed mention of it in the LDML spec. Note (as Markus pointed out) that clients who explicitly request the now-absent  "reformed" collation type in Swedish will fall back to getting the "standard" behavior, which is the desired result ("standard" has the data that used to be "reformed").
=> CLDR-16638 remove mention of "reformed" in spec

docs/ldml/tr35-personNames.md
CLDR-16403
Update status and links for ICU4J PersonName implementation
=> CLDR-16403 Update status and links for ICU4J PersonName implementation

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
=> CLDR-17137 Add --license-file to Ldml2json for overriding the license included in the binary

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
-The method localeIsSpecial should return false for the default content locale ar_001
CLDR-17128
=> CLDR-17128 GenerateProductionData should not add defaultNumberingSystem items to ar_001

docs/ldml/tr35-dates.md, docs/ldml/tr35.md
CLDR-16848
Note parse issues for week of year (affected by firstDay and minDays).
Also add a Modifications entry for the material added in PR [#3316](https://github.com/unicode-org/cldr/pull/3316)
=> CLDR-16848 Note parse issues for week of year; update mods for Transforms

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/pcm.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
CLDR-17092
Note: depends on #3285 — please review only the last commit until I fix up the order
=> CLDR-17092 kbd: drop settings fallback=omit

docs/ldml/tr35.md
=> CLDR-16249 Describe EBNF syntax more clearly

common/supplemental/attributeValueValidity.xml, docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/ja-Latn.xml, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/3.0/pcm.xml, keyboards/3.0/pt-t-k0-abnt2.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-missing.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownbase.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownver.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-wrongparent.xml
- drop the <names> element
- make <info> required
- add <info name="…"> as a required attribute
- update docs and dtd
CLDR-17091
=> CLDR-17091 kbd: move names into info name="…"

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- rename flick to flickSegment, rename flicks to flick
- move flick to child of new flicks element, not under keys
- update dtd, docs, samples
CLDR-17089
=> CLDR-17089 kbd: avoid mixed children in collection

docs/ldml/tr35-keyboards.md, keyboards/dtd/ldmlKeyboard3.dtd
=> CLDR-17141 kbd: keep transform=no but document it

docs/ldml/tr35-keyboards.md, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/ja-Latn.xml, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/3.0/pcm.xml, keyboards/3.0/pt-t-k0-abnt2.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-missing.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownbase.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownver.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-wrongparent.xml
=> CLDR-17140 kbd: specify modifier matching

docs/ldml/tr35-keyboards.md, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
fyi @jahorton 
- expand documentation about use of markers to inhibit transforms
CLDR-17141
also see #3332  which is a sub-PR of this
=> CLDR-17141 kbd: drop transform=no

docs/ldml/tr35-keyboards.md, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
- expand documentation about use of markers to inhibit transforms
(cherry picked from commit 1a52361654f5d9c58f084d1d919080423862975a) #3330 
CLDR-15034
=> CLDR-15034 cherry-pick CLDR-17141 kbd: drop transform=no

docs/ldml/tr35-keyboards.md
Co-authored-by: Marc Durdin <marc@durdin.net>
(cherry picked from commit 85e182e4dcb63046a026dea09481dc3309eeb7fd in #3335)
CLDR-17141
cherry pick PR #3335 was merged with some additional review comments. This copies them *back* to main.
=> CLDR-17141 kbd: Apply suggestions from code review

common/main/en_GB.xml
CLDR-16727
Removing the GTS value for short variant of Gulf Standard Time for en_GB. This is a quick fix, while the real fix should be disabling this in Survey Tool
=> CLDR-16727 Remove short variant for Gulf Standard Time for en_GB

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Race.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STUsersChoice.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VotelessUsersChoice.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java
-VettingViewer should depend on VoteResolver, not vice-versa
CLDR-16369
=> CLDR-16369 Move VoteStatus enum from VettingViewer to VoteResolver

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-The comment for VoteResolver.VoteStatus.provisionalOrWorse was incorrect
-The comment (see class def for null user) was unhelpful
-The reference to ticket/10973 was obsolete
-Fix a few warnings from IntelliJ
CLDR-16369
=> CLDR-16369 Fix some comments and warnings in VoteResolver

common/main/en.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
CLDR-17195
- also fixes a test case which ought to have failed on this case.  Confirmed that there are no other cases besides these (`blo`,`xnr`, `kxv`)
=> CLDR-17195 v44: update en with locales now at basic

docs/charts/keyboard/static/index.html, docs/charts/keyboard/static/keyboard-chart.js
- charts broke with recent renames (such as to= to output=)
CLDR-17205
Note: against v44 for now.
=> CLDR-17205 kbd: fix charts problem

tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrSideways.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/views/InfoRegionalVariants.vue, tools/cldr-apps/src/main/webapp/surveytool.css
-New component InfoRegionalVariants.vue; related refactoring, modernization
-Fix bug, erase deferred/placeholder help when click Next/Previous
CLDR-17080
=> CLDR-17080 Add Regional Variants label for the Info Panel menu

keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- the `<locale id=…>` attribute was set as `@VALUE` which caused it to be wrongly flagged as a duplicate.
CLDR-17204
=> CLDR-17204 kbd: v44: dtd fix for locales

keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- cherry-pick from maint-44: CLDR-17204 kbd: dtd fix for locales (#3369)
- the `<locale id>` attribute was set as `@VALUE` which caused it to be wrongly flagged as a duplicate.
(cherry picked from commit b07c9d8c52f1b03bffa85a93672b1101dd19c19d)
CLDR-17229 
=> CLDR-17229 keyboard: v45 cherry-pick from maint-44

tools/cldr-apps/js/src/esm/cldrSideways.mjs, tools/cldr-apps/js/src/views/InfoRegionalVariants.vue
-Set SIDEWAYS_DEBUG to false
-Remove the 2-second delay if (and only if) the user has just chosen from the menu
-Shorten excessively long functions by moving nested functions to top level and making more subroutines
-Remove dependency of the Vue component on non-GUi modules cldrLoad, cldrStatus
-Refactor for clarity
-Comments
CLDR-17080
=> CLDR-17080 Regional Variants menu follow-up

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/DefaultDataSubmissionResultHandler.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
-Delete dead code and fix compiler warnings in WebContext.java, SurveyMain.java, and related files
-Remove the Deprecated label for the phase BETA since we still use it
-Delete the other deprecated phases and dependent code
-Add warning comments for methods that appear unused but are still accessed by jsp
-Comments
CLDR-16838
=> CLDR-16838 Login bug; preliminary refactoring, clean-up; phase BETA not deprecated

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
-Undeprecate UserRegistry.internalGetPassword, accessed not only by JSP but also by Auth.java
-Fix some compiler warnings for Auth.java
CLDR-16838
=> CLDR-16838 Fix login bug: removeLoginCookies if query has email and password

tools/cldr-apps/js/src/esm/cldrVote.mjs
-Make cldrVote.CLDR_VOTE_DEBUG true; log times to console
-Refactor to use modern cldrAjax.doFetch instead of legacy cldrAjax.sendXhr
-Reduce very long functions and nested subroutines
-Sanitize error message with new method makeSafe to avoid security warning
-Comments
CLDR-17248
=> CLDR-17248 Measure vote timing; log times to console; refactor to use fetch

tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
-Enable running with nginx on port other than default 80, flexibility for testing on local machine
-No change in behavior if CLDR_REDIRECT_PORT not specified
-Property is retrieved only once, then cached for performance
CLDR-16838
=> CLDR-16838 Follow-up, new optional CLDR_REDIRECT_PORT in cldr.properties

common/main/fr.xml, common/main/hi_Latn.xml, common/main/ku.xml, common/main/pap.xml, common/main/root.xml, common/main/syr.xml, common/main/vi.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
CLDR-17233
Fixed DAIP to coalesce multiple spaces of different types to the strictest type (NNBSP if present, else NBSP if present).
Fixed the specific problem in fr.xml short units that prompted the ticket.
Ran CLDRModify passes to test; this also rearranged some time zone names in root.xml.
This is on the maint/maint-44 branch; will need to be merged into the main branch (possibly along with other CLDR 44.1 fixes) under a separate ticket.
=> CLDR-17233 Have DAIP coalesce multiple spaces to strictest; fix in fr.xml, reorder zones in root

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CheckHtmlFiles.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CldrVersion.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDtd.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateItemCounts.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateReformattedXml.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowStarredCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ElementAttributeInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestComparisonBuilder.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDTDAttributes.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRPaths.java
- UNLESS -DNO_CLDR_ARCHIVE=true is set
CLDR-16393
This will cause tests to FAIL unless:
- cldr-archive is setup OR
- `-DNO_CLDR_ARCHIVE=true` is set.
⚠️ if we merge this, users will start getting failures unless they have an up-to-date `cldr-archive` OR disable the check as described here.
=> CLDR-16393 assume cldr-archive is present for tests

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Initialize surveyNextLocaleStamp to NaN instead of 0, to avoid complication of wrap-around (however rare/unlikely)
-Bug fix: when surveyNextLocaleStamp is NaN, handle any newly received stamp as a change
-Bug fix: when newly received stamp is less than surveyNextLocaleStamp, that is also a change (however rare/unlikely)
-Add DEBUG_SHOWER, DEBUG_LOCALE_STAMP, and DISABLE_ANNOUNCEMENTS for debugging
-Additional debug logging dependent on existing CLDR_LOAD_DEBUG
-Delete obsolete code and comment about dijitInp; we no longer use Dijit/Dojo
-Comments
CLDR-13970
=> CLDR-13970 ST Examples used in patterns; fix front end refresh bug

tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs
-Delete CLDR_TABLE_DEBUG_ZOOM and the block of code that depended on it
-Do not duplicate display of xpath in info panel that depended on CLDR_TABLE_DEBUG
CLDR-17248
=> CLDR-17248 Measure vote timing; remove obsolete debugging code

tools/cldr-apps/README.md
=> CLDR-14316 doc: document SurveyTool setup

docs/ldml/tr35.md
CLDR-17221
Update spec sequence number on main (for v45) to account for 44.1 spec update.
=> CLDR-17221 SBRS v45 Update spec sequence number to account for 44.1 spec update

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- _cldrVersion was, recently, only having the major version (44 not 44.1)
- validate semver of the package version
- print a warning if the 'patch' version  is nonzero (#.#.0)
CLDR-17284
=> CLDR-17284 v44.1 cldr-json: fix version number

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyException.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/STError.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java, tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestSTFactory.dtd, tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestVotePerf.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
- execute a bunch of votes all in a row, which calls  VoteResolverAPI (refactored) from the unit test to vote and to check the voting results.
CLDR-17287
=> CLDR-17287 basic performance test for the back end

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
-Never show flag icon on a Discuss button since it cannot cause a path to be flagged
-If a Request button is disabled, do not show a flag icon on it or an empty space for a flag icon
-When a forum post is made, update the locale stamp so the front end will request an update
-New STFactory.PerLocaleData.nextStamp to enable SurveyForum to update the locale stamp
-Improve performance of STFactory.localeStamps initialization, do not copy Set as Array just to get its size
-Remove unused method STFactory.getLocaleStamp
CLDR-17079
=> CLDR-17079 Flag interface: fix some bugs

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
about 2x improvement, could be improved even more especially when targetting batch (non-interactive) mode
CLDR-7277
=> CLDR-7277 Parallel ConsoleCheck

.github/workflows/gh-pages.yml
- bump to ruby 3.2
CLDR-17290
- also fixes CLDR-17286, a simple typo
=> CLDR-17290 chore(build): fix gh-pages.yml

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AuthSurveyDriver.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
-Simulated users have pseudo email addresses like driver-123@cldr-apps-webdriver.org
-New class AuthSurveyDriver
-In Auth, if login fails, call AuthSurveyDriver to enable creation of account if appropriate
-Only create simulated users if SurveyMain.isUnofficial, never on production server
-Only create simulated users if CLDR_WEBDRIVER_PASSWORD is defined in cldr.properties
CLDR-17248
=> CLDR-17248 Enable creation of ST accounts for webdriver simulated users

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- May roll this into CLDR-7646
- needed to unbreak ST
I'm splitting this out because it fixes a critical issue. CLDR-7646 is the eventual improvement.
CLDR-17289
=> CLDR-17289 fix for VettingViewer

.github/workflows/ansible-lint.yml, tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java, tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestXPathTable.java, tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestSTFactory.java, tools/scripts/ansible/README.md, tools/scripts/ansible/Vagrantfile, tools/scripts/ansible/cldr-apps-playbook.yml, tools/scripts/ansible/roles/openliberty/meta/main.yml, tools/scripts/ansible/roles/openliberty/tasks/main.yml, tools/scripts/ansible/vars/mysql.yml
CLDR-17288
- this is just to get the build going again, CLDR-17279 will be for fixing docs etc.
- had to update the Ubuntu version (which we need in CLDR-16735) because of build issues, but should be forward/backward compatible.
Discussion: https://github.com/orgs/community/discussions/73013
=> CLDR-17288 vagrant/ansible: fix for openliberty / mysql

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/About.java
remove derbyNotSupported(), db_Derby, AND db_Mysql AND getDBKind()
CLDR-17109
=> CLDR-17109 st: Actually remove the rest of Derby

tools/cldr-code/src/main/java/org/unicode/cldr/test/TestCache.java
- fix the TestCacheBundle and TestCacheResult caches to be concurrent safe
- was using concurrent safe maps, but not computing the results safely.
CLDR-7646
=> CLDR-7646 TestCache concurrency issues

tools/cldr-apps/js/src/esm/cldrMonitoring.mjs, tools/cldr-apps/js/src/index.js, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- refactor init stuff from index.js to cldrMonitoring.init()
- rename SurveyTool function to the more generic includeMonitoring()
CLDR-17270
=> CLDR-17270 datadog: refactoring

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
CLDR-17304
- before shipping off to front end, call system logger on any Subtype.internalError messages
- confirmed that they show up in the liberty logfile. so, should be picked up by datadog
=> CLDR-17304 capture internalError check stack traces into the system log

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AuthSurveyDriver.java
-Log whether enabled/disabled and why, and log success/failure for user creation
CLDR-17248
=> CLDR-17248 Add logging for webdriver simulated users

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
the supplemental disk factory should be a singleton. also. use the Suppliers.memoize() idiom in more places.
Because it's a singleton, `getSupplementalDiskFactory()` is now cheap to call.
Note: ✅ Sanity tested locally.
CLDR-17313
=> CLDR-17313 st: only build supplemental factory once

common/main/mus.xml
=> CLDR-17246 Muscogee locale data changes

common/dtd/ldmlSupplemental.dtd, common/supplemental/units.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
=> CLDR-16939 add unit prefixes to data

tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CharUtilities.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXMLSource.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/StringId.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
- Unit test to verify that CLDRFile paths are interned
- interning in XPathTable and StringId
CLDR-17314
=> CLDR-17314 intern across multiple locations

tools/cldr-code/src/main/java/org/unicode/cldr/util/DeferredTranscript.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestDeferredTranscript.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java
- skip String.format when unneeded
- defer all transcript operations until needed
measured as between a 5 and 10x speedup
CLDR-17327
=> CLDR-17327 speedup VoteResolver's transcript

common/dtd/ldmlSupplemental.dtd, common/supplemental/supplementalData.xml, docs/ldml/tr35-numbers.md, docs/ldml/tr35.md, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
CLDR-17282
1. For the `currency` element, add attributes `tz` and `to-tz`. Document these in the spec, along with note that implementations may want to convert the combination of date time and timezone to a UTC timestamp or equivalent for use as runtime data.
* I made these `@VALUE` since they are not distinguishing attributes (but rather annotations for the `to` and `from` attributes); however they are not really like element values either. I also updated PathHeader accordingly.
2. Update the supplemental currency data to use these new attributes for all currency transitions from 2022-01-01 onward. There were only two, for Croatia using tz Europe/Zagreb, and for Sierra Leone, using tz Africa/Freetown. Both of those zones are currently aliases in the backward file, but are still valid in …
=> CLDR-17282 Add currency attributes tz, to-tz and docs; use for currency changes from 2022-01-01

docs/charts/keyboard/.gitignore, docs/charts/keyboard/README.md, docs/charts/keyboard/package-lock.json, docs/charts/keyboard/package.json, docs/charts/keyboard/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateKeyboardCharts.java, tools/pom.xml
- needs a node.js step to build, but can be invoked via maven
CLDR-17216
=> CLDR-17216 generate cldr keyboard charts via maven, copy via GenerateAllCharts

tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleFactory.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
CLDR-17326 
- includes a disabled test - could be run manually.
- Note: I wasn't able to measure a very large improvement, but this code did show up as a hotspot in profiling.
=> CLDR-17326 cache Factory.getSourceDirectoriesForLocale()

docs/ldml/tr35-numbers.md
CLDR-17282
This is a follow-up to PR [#3452](https://github.com/unicode-org/cldr/pull/3452), specifically to [Steven's comment](https://github.com/unicode-org/cldr/pull/3452#pullrequestreview-1827631843) in which he asked whether the timezone IDs should actually be CLDR timezone IDs. The answer is yes, and specifically the CLDR canonical “long” time zone ID, so we now say that.
=> CLDR-17282 Clarify the value for the tz and to-tz attributes

common/bcp47/currency.xml, common/main/en.xml, common/main/es.xml, common/main/fr.xml, common/main/nl.xml, common/main/root.xml, common/supplemental/supplementalData.xml, common/validity/currency.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a3.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-17274
XCG translations for Curaçao and Sint Maarten's new currency
=> CLDR-17274 XCG translations

common/dtd/ldmlSupplemental.dtd, common/supplemental/units.xml, docs/ldml/tr35-info.md, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/test/LogicalGroupChecker.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartUnitConversions.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/UnitValidityCanonicalizer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
CLDR-16329
This is an incomplete first pass at adding conversion support for Beaufort so it can be used in unitPreferences. It compiles and passes tests (but tests have not been updated to test or handle Beaufort). It replaces the first attempt in [#3467 ](https://github.com/unicode-org/cldr/pull/3467) whose approach was deemed wrong.
- Add the `special` attribute for the `convertUnit` element to support the special table-based conversions for Beaufort. When converting from meters/sec to Beaufort, these always map to an integral value that corresponds to a range of speeds that includes the input value. When converting from Beaufort to meters/sec, the Beaufort value is rounded to the nearest integer, then converted to a value in the corresponding range of speeds (generally the value from …
=> CLDR-16329 Add convertUnit special attribute for beaufort; update UnitConverter and some related code

common/main/lv.xml, common/main/mus.xml
CLDR-17356
CLDRModify passes before v45 alpha0 (only -fP = DAIP made any changes):
- Adjust exemplar set spacing for `lv`, `mus`
- Update the glottal stop character used to spell weekdays in `mus` (Creek)
=> CLDR-17356 BRS45 CLDRModify before alpha0: lv/mus exemplar spacing, mus glottal fix char

common/supplemental/supplementalData.xml
CLDR-17357
The first of possibly several alpha0 integration fixes:
- The end date for currency ANG needs to be valid (June 30, not June 31), follow-on for CLDR-17274
=> CLDR-17357 alpha0 integration fix 1: Need valid end dates for currency ANG

tools/cldr-apps/js/webpack.config.js, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
changes us from using `index._GITHASH_.js` applied by cache busting function, to a statically generated webpack file `/cldr-apps/dist/main.71e4a712c8f0e9d8.js` (for example)
- instead, let webpack create a bundle name based on the content's hash, which will truly change when and only when the content changes.
- webpack hook to write the file
- read a manifest.json on the server side to serve that
CLDR-17270
Why?
1. it gets us closer to having a static index.html - webpack can create such files. - CLDR-17353
2. the hash only changes if the contents actually change.  The hash is based on the contents, so it's appropriate to cache them if they don't change
3. it lets the datadog source maps work properly, because we know ahead of time what the filename is going to be.
=> CLDR-17270 st: don't use late cache busting for bundle.js

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DiskDataCache.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- stuff we only want to calculate once, versus what can be expired from the cache.
CLDR-17313
=> CLDR-17313 split out immutable DiskData in STFactory

tools/cldr-code/src/main/java/org/unicode/cldr/test/CoverageLevel2.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCoverageLevel2.java
- use CLDRLocale instead of LanguageTagParser
- about a 3x speedup for construct + 1 lookup
CLDR-17342
=> CLDR-17342 speedup CoverageLevel2 construction

docs/ldml/tr35-keyboards.md, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
=> CLDR-17366 kbd: rename `unicodeSet` to `uset`

tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBoxXMLSource.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/OutputFileManager.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
-Replace makeVettedFile with return make(loc.getBaseName(), false)
-Remove dead code including VoteLoadingContext.VXML_GENERATION, makeVettedSource, makeVettedFile
-Baseline has long been used instead of last-release; obsolete comments indicated VXML required VoteResolver for last-release
-Comments
CLDR-16946
=> CLDR-16946 Fix triple up arrow producing error in VXML

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
CLDR-17345
Fix the earlier test failure in testLanguageTagParserIsValid() the right way, by marking co-reformed as valid (even though it is deprecated), as is done with co-direct. Then remove the logKnownIssue added earlier.
=> CLDR-17345 In testLanguageTagParserIsValid, mark co-reformed as valid (though deprecated)

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
-Revise checkSuboptions to throw IllegalArgumentException for FIX other than Q, P, V
CLDR-17144
=> CLDR-17144 Disable all CLDRModify -f except -fQ/-fP/-fV

common/dtd/ldmlSupplemental.dtd, common/supplemental/supplementalData.xml, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Factory.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleIDParser.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLocaleIDParser.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestSupplementalDataInfo.java
CLDR-17336
This turned out to be a bit more work than anticipated; not that many lines but spread over a few files. I'll mention the highlights below.
common/dtd/ldmlSupplemental.dtd
- modified to allow multiple components (and add plurals & grammaticalFeatures)
- allow nonlikelyScript as a single value for locale=
common/supplemental/supplementalData.xml
- Make the changes in the ticket, to use nonlikelyScript
- Remove the redundancies, add grammaticalFeatures, plurals
docs/ldml/tr35.md
- document the changes, removing the complexities of having the other components overlay the main one.
tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- Tell JSON that the components have multiple elements. (The error message is very helpful, but could use some more guidance in …
=> CLDR-17336 Fix parentLocales

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
- updates LogKnownIssues to CLDR-17320 to catch all other cases
CLDR-17304
This quells the rest of the SEVERE errors and stacktraces as a logKnownIssue.  There was already a logKnownIssue in place, this just expands it to apply to the other callers.
=> CLDR-17304 expand logKnownIssues to quell remaining SEVERE errors

tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
- data from CLDR-16939
CLDR-17367
extract from `cldr-json/cldr-core/supplemental/units.json`: 
```json
{
"supplemental": {
"version": {
"_unicodeVersion": "15.1.0",
"_cldrVersion": "45"
},
"unitPrefixes": {
"atto": {
"_symbol": "a",
"_power10": "-18"
},
"centi": {
"_symbol": "c",
"_power10": "-2"
},
"deci": {
"_symbol": "d",
"_power10": "-1"
},
"deka": {
"_symbol": "da",
"_power10": "1"
},
"exa": {
"_symbol": "E",
"_power10": "18"
},
```
=> CLDR-17367 cldr-json: put unitPrefixes into units.json

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LanguageInfoTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
CLDR-17388
update two logKnownIssues from closed to open tickets.
=> CLDR-17388 v45 update logKnownIssues

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
=> CLDR-16108 cldr-json: mark -modern packages as deprecated

LICENSE, docs/charts/keyboard/package-lock.json, docs/charts/keyboard/package.json, pom.xml, tools/cldr-apps/js/package-lock.json, tools/cldr-apps/js/package.json, tools/cldr-code/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePersonNameTestData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java, tools/pom.xml, tools/scripts/ansible/roles/openliberty/meta/main.yml, tools/scripts/tr-archive/package-lock.json, tools/scripts/tr-archive/package.json, tools/st-prom-exporter/package.json
- does not regenerate dtds or xml - that will be done in future LDMLModify steps.
- the person names generator had copy and pasted static text instead of using the correct generator
- https://github.com/unicode-org/.github/issues/15
CLDR-17110
=> CLDR-17110 update LICENSE SPDX, SPDX in other files

CONTRIBUTING.md
- https://github.com/unicode-org/.github/issues/12
CLDR-17110
=> CLDR-17110 update CONTRIBUTING.md

keyboards/3.0/bn.xml, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/ja-Latn.xml, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/3.0/pcm.xml, keyboards/3.0/pt-t-k0-abnt2.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DoctypeXmlStreamWrapper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLFileReader.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestDoctypeXmlStreamWrapper.java, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-missing.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownbase.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownver.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-wrongparent.xml, tools/pom.xml
- optimized
- assumes current version DTD
- supports spec change in #3495 
CLDR-17371
=> CLDR-17371 stream filter to replace xmlns with DOCTYPE

common/dtd/ldmlSupplemental.dtd, common/supplemental/supplementalData.xml, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
CLDR-17336
As per discussion in infrastructure team, we need a migration path. This adds a new attribute with the rule instead of using the locale attribute, which reverts to only having locales. The locales from last release are restored, for this version.
=> CLDR-17336 fix parent locales for migration

common/properties/coverageLevels.txt, common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestStandardCodes.java
CLDR-17407
Regenerated the coverage and charts while doing this.
common/properties/coverageLevels.txt
- Toki Pona dropped from Basic
common/supplemental/coverageLevels.xml
- modified because the previous method for skipping beaufort was not working
tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
- Made the CODE_FALLBACK not include deprecated timezones (eg Currie). Guts are in SupplementalDataInfo
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- While doing this, added some internal structure to make it easier to get BCP47 data. The old mechanism, searching for pairs is awkward to use.
- Also added a backmapping from the aliases (eg long TZ names) to the subtype (eg the short TZ names)
- goodTimezones takes the available codes, and …
=> CLDR-17407 check for anomalies and fix

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java
=> CLDR-17339 Fix problem in ChartDeltaDtds that was skipping keyboard3

tools/cldr-code/src/main/java/org/unicode/cldr/util/Containment.java, tools/cldr-rdf/src/main/java/org/unicode/cldr/tool/GenerateLanguageContainment.java
Update Containment to not stack overflow when there are containment loops.
Report the loops (sparingly) to console. 
(cherry picked from commit d1ae5db9ea0450412c51a02c6eb867c7c77ee171 #3249) 
CLDR-17418
=> CLDR-17418 GenerateLanguageContainment: avoid loops

docs/ldml/tr35-keyboards.md
- documented 'implementation'
- added a Notation section
- corrections to discussion of repository and file layout
CLDR-17177
=> CLDR-17177 kbd: update per feedback

tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-New subroutines makePathHeader and getVolumePageId
-Change example in Dashboard.java from Volume to Area
-Comments
CLDR-11155
=> CLDR-11155 Separate Volume_Metric and Volume_Other

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-Throw InternalCldrException instead of RuntimeException
-Call getVolumePageId() from fix() instead of from makePathHeader()
CLDR-11155
=> CLDR-11155 Refactoring per comments on the previous commit

docs/charts/keyboard/README.md, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateKeyboardCharts.java
CLDR-17216
- GenerateKeyboardCharts wasn't creating a subdirectory prior to  copying. Fixed
- Corrected readme and added eclipse instructions
=> CLDR-17216 improve docs and tooling for keyboard charts

docs/charts/keyboard/static/keyboard-chart.js, docs/ldml/tr35-keyboards.md, keyboards/3.0/bn.xml, keyboards/3.0/fr-t-k0-azerty.xml, keyboards/3.0/ja-Latn.xml, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/3.0/pcm.xml, keyboards/3.0/pt-t-k0-abnt2.xml, keyboards/README.md, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, keyboards/dtd/ldmlKeyboardTest3.dtd, keyboards/dtd/ldmlKeyboardTest3.xsd, keyboards/import/README.md, keyboards/import/keys-Zyyy-currency.xml, keyboards/import/keys-Zyyy-punctuation.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/KeyboardFlatten.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-missing.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownbase.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-unknownver.xml, tools/cldr-code/src/test/resources/org/unicode/cldr/tool/KeyboardFlatten/broken-import-wrongparent.xml
CLDR-16909
- Move Keyboard out of techpreview
- `techpreview` is no longer an acceptable version number for `conformsTo=..` or for the import path.
- remove some hacks that enabled `techpreview`
- fixup the spec and other docs
**NOTE** As discussed earlier, the keyboard _test_ data (`ldmlKeyboardTest3.dtd`) remains in techpreview. I've added some additional notes to make this clear in the DTD and in the spec.
=> CLDR-16909 kbd: move out of techpreview

docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md
- final spec will be poured in as CLDR-17424
CLDR-17423
=> CLDR-17423 Placeholder for MessageFormat 2.0 spec, part 9

docs/ldml/tr35.md
=> CLDR-17432 Fix markup bug

common/main/en_001.xml, common/main/en_CA.xml
=> CLDR-17322 Fix en_001 & en_CA narrow standalone day periods

tools/cldr-code/src/main/java/org/unicode/cldr/util/ElementAttributeInfo.java
CLDR-17371
Wasn't a test failure, but fixes an otherwise ignored error.
=> CLDR-17371 fix ElementAttributeInfo to use DoctypeXmlStreamWrapper

docs/ldml/tr35-messageFormat.md
=> CLDR-17407 BRS spec fixes

common/main/ks.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
This normalizes YEH WITH TAIL (an incorrect Pashto letter) to KASHMIRI YEH. See L2/23-241.
CLDR-16595
=> CLDR-16595 Add DisplayAndInputProcessor rule for normalizing Kashmiri, normalize Kashmiri

common/main/nl.xml
CLDR-17389 
CLDR 44 introduced the changes in time zone names for Dutch, mainly in America's region. Those changes implemented English time zone name translations, instead of the Dutch ones.
Per the discussion in TC, it is agreed to revert the time zone names back to pre-44 values
=> CLDR-17389 Revert Dutch time zone names

tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverage.java
CLDR-17442
I tracked down the problem, which was that the coverage level rules were being sorted, which reordered the comprehensive beaufort rules **after** modern.
This should never have been the case; the rules are meant to be processed in order.
=> CLDR-17442 Fix coverage to handle beaufort

common/supplemental/supplementalData.xml
CLDR-17435
Add the timezone attributes for the 2024 currency changes in CA and SX. Per https://unicode-org.atlassian.net/browse/CLDR-17282 we decided to add the timezone attributes for all currency changes from 2022-01-01 and later. I should have mentioned that when reviewing https://github.com/unicode-org/cldr/pull/3471 but did not, so we add the attributes with this PR.
=> CLDR-17435 add timezone attributes for the 2024 currency changes in CW,SX

common/testData/units/unitPreferencesTest.txt, common/testData/units/unitsTest.txt, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-17420
This is a followup to PR [#3487](https://github.com/unicode-org/cldr/pull/3487) for CLDR-16329
The main thing I had to do here was fix UnitConverter.parseUnitId() to handle special mappings (which also eliminated 3 TODOs in UnitConverter.java). I also added some beaufort cases to TestUnits.TestSpecialCases() and regenerated the units test data files.
=> CLDR-17420 Fix UnitConverter.parseUnitId for special, add tests & regen unit test files

.github/workflows/keyboard.yml, keyboards/3.0/bn.xml
- move kmc from alpha to beta
- use a later kmc version that support current api (this will change again)
- fix a typo in the sample data
CLDR-17202
=> CLDR-17202 kbd: updates to bengali

tools/cldr-apps/src/main/java/org/json/JSONObject.java
-JSONObject had recursive calls in put double/int/long
-Use Double/Integer/Long.valueOf to call the version of put with Object parameter
CLDR-17399
=> CLDR-17399 Fix infinite loops due to removing boxed primitive constructors

common/testData/units/unitLocalePreferencesTest.txt, common/testData/units/unitPreferencesTest.txt, common/testData/units/unitsTest.txt, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateUnitTestData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitPreferences.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Units.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-15954
The main goal was to add tests of test files, for verification. It grew a bit as I discovered and fixed problems.
common/testData/units/unitLocalePreferencesTest.txt
- new test file to check problems in following the spec with locales
common/testData/units/unitPreferencesTest.txt
common/testData/units/unitsTest.txt
- New SPDX id
- Fixed the pointer to generation program.
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateUnitTestData.java
- addition of 'public void generateUnitLocalePreferences() {' to generate the new test data file
- and some utility methods
- refactoring a bit
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
- keep the current behavior for which units get grammar.
- needed because of a fix in XXX …
=> CLDR-15954 Add test of unit preferences test

tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrMenu.mjs, tools/cldr-apps/js/src/esm/cldrStatus.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
-Include real locale ID as json.loc in server response for page request
-Use optional chaining (?.) operator for special_type which may be undefined for USER
-Do not call dispatchEvent or setRef from setCurrentLocale for locale USER
-New method UserRegistry.substituteUserWildcardLocale replacing inline code in SurveyAjax, now called also by VoteAPIHelper
CLDR-17425
=> CLDR-17425 Fix bugs involving locale USER

docs/ldml/tr35.md
Change to use the suggested text in the ticket (after verifying that the results are identical), with only minor edits.
CLDR-16999
=> CLDR-16999 Change Annex C Preprocessing

docs/ldml/tr35.md
CLDR-16998
Took the suggestion to use monospacing in two of the suggested sections. The https://unicode.org/reports/tr35/#Key_And_Type_Definitions_ was more complicated, and would benefit less so that wasn't done.
=> CLDR-16998 Fix Formatting

common/main/ta.xml
CLDR-17470
This PR reorders the day period in time formats to follow minutes and seconds and before the time zone, as is standard for Tamil, and which is similar to many other locales.
=> CLDR-17470 Fix day period order in Tamil time format patterns

docs/ldml/tr35.md
CLDR-17403
Note that the previous version had "minimize(zh-Hans, favorRegion) ⇒ zh-TW", which clearly needs "Hant" instead of "Hans".
=> CLDR-17403 Fix typo, add examples

docs/ldml/tr35-info.md, docs/ldml/tr35.md
CLDR-15954
Clarify the algorithm for unit preferences to catch edge cases.
1. What to do with unitpreferences if there is no quantity for a unit, or no preferences for a quantity. Emphasizes the use of likelysubtags. It more explicit about edge cases when comparing input values to geq values (negative numbers, infinity, NaN). Provides more of a step-by-step approach to handling the subtags that have an impact (no change in effect, but much clearer). Moves examples to better places.
2. Edge cases (but important ones) for mixed units: handling negatives and rounding. One change is to be less prescriptive about the way that precision is handled, giving us a chance to work that our more in the future (because the current advice really doesn't work well.
=> CLDR-15954 Update spec for unit preferences

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/esm/cldrProgress.mjs, tools/cldr-apps/js/src/esm/cldrSchedule.mjs
-This PR only changes the front end
-New module cldrSchedule with class FetchSchedule used by both cldrAnnounce and cldrProgress
-Old code in cldrProgress mistakenly had && for condition on time since last request/response
-New code in cldrSchedule has || instead of &&
CLDR-16900
=> CLDR-16900 Limit frequency of announce and completion requests

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/esm/cldrSchedule.mjs
-Check whether user is logged in before calling schedule.tooSoon
-When the Announcements page gets opened, fetch immediately, since previous fetch only set unread count
-New method cldrSchedule.reset facilitates immediate re-fetch
-In cldrSchedule.tooSoon return false if this.lastRequestTime is zero (reset or not yet set)
-Comments
CLDR-16900
=> CLDR-16900 Fix bugs in the previous PR

tools/cldr-apps/js/package.json, tools/cldr-apps/js/test/Test.html, tools/cldr-apps/js/test/run.sh
CLDR-17481
- run.sh not needed. Just npm run install build-test and then load Test.html
=> CLDR-17481 re-enable directly loading Test.html

docs/ldml/tr35-keyboards.md
CLDR-17467
- disallow empty matches in transform, such as `<transform from=""/>`
=> CLDR-17467 kbd: disallow empty match

common/supplemental/supplementalData.xml, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLevel.java
- Latest amendment: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl-currency-iso-amendment-176.pdf
- PR #3471 had the dates in 2024
CLDR-17490
=> CLDR-17490 XCG transition is in 2025, not 2024

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/views/AnnouncePanel.vue, tools/cldr-apps/js/test/Test.html, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java
-Refactor (encapsulate) to calculate unread/total counts in only one place; new callbackSetCounts
-On front end, remember the last announcement ID fetched (alreadyGotId)
-On back end, respond with 304 Not Modified if alreadyGotId matches
-Do not report 304 Not Modified response as error; log it to console only if debugging enabled
-New front-end method resetSchedule prevents delay and prevents 304 response
-Format Test.html (not specific to this ticket; unrelated PR left it unformatted)
-Comments
CLDR-16900
=> CLDR-16900 Shorten server response if unchanged; bug fix, refactor

docs/ldml/tr35.md
=> CLDR-17265 Document special script codes

docs/ldml/tr35-dates.md
=> CLDR-17217 Reserve datetime fields for private use

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/test/run.sh, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java
-Standard usage of 304 would involve adding headers and getting cached json from browser; this is more efficient
-Also restore and revise tools/cldr-apps/js/test/run.sh for convenience (CLDR-17481)
CLDR-16900
=> CLDR-16900 Avoid 304 Not Modified; instead use boolean json.unchanged

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
-In testPageSize in TestPathHeader.java, show not only Section but also Page
-Also show log/error thresholds, and use String.format, per suggestions in PR 3519
CLDR-11155
=> CLDR-11155 Pages too big: revise test for large pages

docs/ldml/tr35.md
CLDR-17491
This PR is to update the modifications section of LDML to cover the changes in 45 for the public beta. 
Additional PRs can be added under this ticket after this PR is merged.
=> CLDR-17491 Update LDML Mods section

docs/ldml/tr35-keyboards.md
thanks @miloush for the feedback. Numbers refer to feedback items.
- 1. keyboard3 needed to list forms as children
- 
- 4. locales and locale had the same description.
- 
- 5. DTD order: import, … displays, keys, flicks. not reflected in spec
- 
- 6. clarify gap elements
- 
- 7. spec to follow DTD order of key attributes: @id @flickId @gap @output … @width
- 
- 8. Fixed the example in key/@longPressKeyIds
- 
- 9. flick syntax example should use @flickId instead of @flicks
- 
- 10. The note for flick/@id attribute should be clarified that it's not an XML namespace referred to.
- 
- 11. clarify recursive imports
- 
- 12. import was missing forms as a parent
- 
- 13. fixed import example
- 
- 14. layers/@form should be layers/@formId, occurrences in both @form and @minDeviceWidth …
=> CLDR-17341 v45: kbd spec: editorial improvements

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- add special handling for localeRules
CLDR-17367
=> CLDR-17367 v45 JSON: improve localeRules processing

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
-Divide Volume Other into Volume US and Volume Other
-Divide Other Units into Other Units Metric, Other Units Metric Per, Other Units US and Other Units
-New subroutines getOtherUnitsPageId, isSystemUnit, getShortUnitId
-Fix deprecation warnings: remove getSectionsToPages; fix TestZ and filterCldr
CLDR-17514
=> CLDR-17514 Pages too big (v46): further divisions for Volume, Units

keyboards/3.0/ja-Hira-t-k0-flicks.xml
CLDR-17202
Adds a simple 'flick' type Hiragana keyboard.
=> CLDR-17202 kbd: add a Hiragana Flick keyboard

docs/ldml/tr35-messageFormat.md, tools/scripts/tr-archive/archive.js, tools/scripts/tr-archive/tr35.css
CLDR-17424
- linkify `<dfn>` elements
- fix more internal broken links
- improve style for `[!NOTE]` and `[!IMPORTANT]` (see image)
fyi @aphillips
=> CLDR-17424 MFv2 spec: link fix, style improvement

common/validity/currency.xml
=> CLDR-17490 generate validity for units 2

.github/workflows/gh-pages.yml, CONTRIBUTING.md
CLDR-17434
[Later edit] It seems that separate action will be needed to shorten the lines for the CLA section, as the source for that is elsewhere.
=> CLDR-17434 fix markdown lint warnings

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- add an isEntireLocale status to CheckStatus
- make CheckStatus comparable
- set the isEntireLocale for all possibleErrors and deferred (handleCheck)
- update ConsoleCheckCLDR
CLDR-17560
split from #3644 
=> CLDR-17560 add CheckCLDR.isEntireLocale()

tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXPathParts.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathValue.java
note this is for v46 - see also #3631 
- clarify distinction between XPathParts and SimpleXPathParts
- push XPathParts.size() and other API up to XPathValue.size()
- use SimpleXPathParts instead of XPathParts in SupplementalDataInfo
CLDR-17540
=> CLDR-17540 update SupplementalDataInfo reader to not use reentrant XPathParts

README.md, common/dtd/ldml.dtd, common/dtd/ldml.xsd, common/dtd/ldmlBCP47.dtd, common/dtd/ldmlBCP47.xsd, common/dtd/ldmlSupplemental.dtd, common/dtd/ldmlSupplemental.xsd, docs/charts/keyboard/pom.xml, docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd, pom.xml, tools/cldr-apps/pom.xml, tools/cldr-code/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CldrVersion.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestDoctypeXmlStreamWrapper.java, tools/cldr-rdf/pom.xml, tools/pom.xml
CLDR-17571
- Update README date, version, status
- Update spec version (status was already draft on main branch). Remove trailing spaces from tr35-info.md as was done on maint branch.
- Update cldrVersion in dtd and xsd files.
- Update CLDR version in pom files
- Update GEN_VERSION in CLDRFile
- Update DEV_VERSION in ToolConstants.java, and add entries for CLDR 45 in  CLDR_VERSIONS and in CldrVersion.java.
- This all caused some unit test failures with keyboard files, many of which seem to explicitly reference CLDR 45 for their dtd. Filed https://unicode-org.atlassian.net/browse/CLDR-17574 about this and added test skips referencing that ticket. 
=> CLDR-17571 Update CLDR versions (poms, dtd, spec, CLDRFile, README) & status

common/dtd/ldmlSupplemental.dtd, tools/cldr-code/src/main/java/com/ibm/icu/util/MatchElementAttribute.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
=> CLDR-17561 Utility for visiting DtdData elements

common/main/lld.xml, common/main/lld_IT.xml, common/supplemental/attributeValueValidity.xml, common/supplemental/supplementalData.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-17483
This PR adds lld base locale; ticket asks for additional variants to be added.
=> CLDR-17483 add lld Ladin locale

common/main/lld_ANPEZO.xml, common/main/lld_FASCIA.xml, common/main/lld_FODOM.xml, common/main/lld_GHERD.xml, common/main/lld_VALBADIA.xml, common/validity/variant.xml
CLDR-17483
This PR and the previous PR (#3643) should complete the ticket. The previous PR added lld.xml and lld_IT.xml. This PR adds:
lld_ANPEZO.xml
lld_FASCIA.xml
lld_FODOM.xml
lld_GHERD.xml
lld_VALBADIA.xml
for the anpezo, fascia, fodom, gherd and valbadia variants. Note that the valbadia file has only the identity block, since this variant is used as the default for lld.
=> CLDR-17483 add Ladin (lld) variants

docs/ldml/tr35.md
CLDR-17529
Missed these in the final tag
=> CLDR-17529 v45 spec: add keyboard names for spec attribution

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
CLDR-17346
- fix ConcurrentModificationException in CheckCLDR - the `allFilters` was initialized in an unsafe way.  This has been latent for five monthgs in CLDR-7277
- also fixed another issue in the GitHub err reporting
=> CLDR-17346 ConsoleCheckCLDR fixes

tools/cldr-apps/js/src/esm/cldrErrorSubtypes.mjs, tools/cldr-apps/pom.xml, tools/cldr-apps/src/main/java/org/unicode/cldr/web/ErrorSubtypeClient.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/ErrorSubtypes.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java, tools/cldr-apps/src/test/java/org/unicode/cldr/util/TestCLDRLinks.java
CLDR-16101
- Reads from https://docs.google.com/spreadsheets/d/1n7H_yt2Sxea1_AAp6Ggi5zo1HxtC5-xwieBlyM2kAcs/edit#gid=1962856317 for subtype
- automatically updates a sheet with ALL subtype names
=> CLDR-16101 Change Error Subtype to read from Google Sheets

tools/cldr-apps/js/src/esm/cldrDash.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs, tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/js/test/TestCldrDash.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
-Add checkbox next to each notification category in Dashboard header
-The category is hidden if the checkbox is unchecked
-Error and Missing notifications still cannot be hidden with pre-existing right-side path-specific checkboxes, but they can be hidden categorically using the new checkboxes
-Show each path with notifications only once in Dashboard
-If a path has more than one notification, combine them on one line
-Perform data conversion on the front end; http response still has multiple notifications per path
-Refactor to avoid http code in Vue; call cldrAjax.mjs from cldrDash.mjs not from DashboardWidget.vue
-New classes DashData and DashEntry in cldrDash.mjs
-Use new method dashData.addEntriesFromJson for both whole-page json and single-path json
-Make hover titles clearer for …
=> CLDR-15649 Dashboard using filters

.github/workflows/gh-pages.yml, docs/_config.yml
CLDR-17566
Looking at #3650 I realized that some subdirectories were not getting build properly. This fixes the build to use `github-pages build` instead of raw `jekyll`.  FYI @lianghai
To review, see: (note srl URL)
- https://srl295.github.io/cldr/site/downloads/cldr-45.html
- https://srl295.github.io/cldr/ (LDML spec should be same as usual)
- https://srl295.github.io/cldr/dev/generate-emoji-paths.html
These are broken in current main, for example <https://unicode-org.github.io/cldr/dev/generate-emoji-paths.html> and <https://unicode-org.github.io/cldr/site/downloads/cldr-45.html> are dead links.
=> CLDR-17566 fix to GitHub Pages build

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckWidths.java
CLDR-17532
Reset the CheckWidths for emoji search keywords. This is a large max, to allow the extra values from https://unicode-org.atlassian.net/browse/CLDR-17349 One-off import of additional Emoji keyword data from WhatsApp into CLDR as part of v46 cycle
After CLDR-17349 has been merged we can fine-tune the values.
=> CLDR-17532 update max search keywords

tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/js/test/TestCldrDash.mjs
-Use a timeout so that the visible checkbox updates immediately when clicked
-Format TestCldrDash.mjs, neglected in previous PR for this ticket
CLDR-15649
=> CLDR-15649 Dashboard using filters, fix checkbox performance

common/main/uk.xml
=> CLDR-17486 Revert day-name and day-pattern changes for Ukrainian.

common/main/mhn.xml, common/main/mhn_IT.xml, common/supplemental/attributeValueValidity.xml, common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
=> CLDR-17430 add mhn Mocheno locale

tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartSupplemental.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
(PR depends on #3648 )
- add a nonPathError status to CheckStatus
- make CheckStatus comparable
- set the nonPathError for all possibleErrors and deferred (handleCheck)
- update ConsoleCheckCLDR
- add a new 'supplemental' report that simply lists the overall errors
- update Chart api to take testbundle
CLDR-17560
=> CLDR-17560 UI for entire locale checks

tools/cldr-apps/js/src/esm/cldrErrorSubtypes.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
-New icons in the Comparison (English) column: 💬 followed by question mark or period
-💬? means: This item has forum posts, some of which are open
-💬. means: This item has forum posts, all of which are closed
-New class SurveyForum.PathForumStatus
-New method appendForumStatus in cldrTable.mjs
-Fix a few Java compiler warnings
CLDR-17461
=> CLDR-17461 Improve visibility of forum posts in vetting view

tools/cldr-apps/js/src/esm/cldrErrorSubtypes.mjs, tools/cldr-apps/js/src/views/DashboardWidget.vue
-The spinner replaces the Dashboard rows until Vue updates the DOM to reflect checkbox change
-Format cldrErrorSubtypes.mjs (from another ticket)
CLDR-15649
=> CLDR-15649 Dashboard using filters, show spinner while updating visibility

.github/workflows/maven.yml, common/supplemental/units.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-17459
Added grammar to some units that were skipped earlier.
The breakdown is at https://docs.google.com/spreadsheets/d/1soBtcb3SwNaCMg3maD0vvbWqqimco4ZKpdtSpB7NJ1E/edit#gid=0
Also
- added a comparator for units, to help in examining the result. (And are needed for another ticket.)
- set gasoline-per-mile to not be metric_adjacent
=> CLDR-17459 Add units for grammar

tools/pom.xml
Use a specific SNAPSHOT so that the cldr-utilities refactoring does not break the functionality.
Once the changes land in ICU, we will publish a new version. Then back here I update the package, and go back to using 76.0.1-SNAPSHOT, in one single commit.
CLDR-17492
=> CLDR-17492 Temporarily point to a fixed snapshot

tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
=> CLDR-17459 Fixups for printing list, prefixable

common/dtd/ldmlSupplemental.dtd, common/supplemental/coverageLevels.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-16941
1. Improve coverage for number system symbols and patterns belonging to non-`latn` default, native, and finance numbering systems in all locales. In some cases we select coverage by script instead of or in addition to language, to disambiguate cases where languages are written in multiple scripts.
2. Add a unit test to verify that various number symbols and patterns are at the desired coverage level for each of the two or three number systems (default, native, and possibly finance) specified in a locale, for all locales. This currently takes some time (25 sec on my machine), maybe could be sped up.
3. Whet this does not do is group collections of number symbols or patterns into sets. That would require coverage variables with alternate values for elements in paths, which is …
=> CLDR-16941 Improve coverage for non-latn default/native number symbols/patterns

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
-Add a cache localeForumStatusMap in SurveyForum.java
-New class SurveyForum.LocaleForumStatus
-Get all the status for a locale with a single sql call
-Clear the cache for a locale when a post is added/closed
-Revise icons in the Comparison (English) column: 👁️‍🗨️ and 💬
-👁️‍🗨️ means: This item has one or more forum posts, some of which are open
-💬 means: This item has one or more forum posts, all of which are closed
-Change let to const for two items in cldrSurvey.mjs; remove @property
-Call updateRowEnglishComparisonCell even if isSetup, and always removeAllChildNodes; old optimization assumed the cell contents never changed
CLDR-17461
=> CLDR-17461 Forum posts in vetting view, boost performance, change icons

common/main/pl.xml
CLDR-15696
Revert Polish day units to dzień forms as in CLDR 37 (except the per day forms, which should continue to use dobę*); update the inflections* accordingly. The * information is all from Marek Pepke in the ticket.
=> CLDR-15696 Revert Polish day units (except per) to dzień forms, updating inflections accordingly

common/main/root.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchCLDR.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
CLDR-17544
This removes a value from root that isn't really needed, and fixes the example cited in the ticket.
It also adds an option to SearchCLDR to locate these kinds of issues, but doesn't address them all. 
For that I'll clone the ticket.
=> CLDR-17544 In en, remove yMd in chinese calendar availableFormats

common/supplemental/coverageLevels.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-16941
Follow-on to PR [#3690](https://github.com/unicode-org/cldr/pull/3690) - Further number symbols/formats coverage fixes mostly per TC discussion 2024-05-08 in doc [Non-latn number systems coverage](https://docs.google.com/document/d/1cp01T7wBl-5oAjCNYsrkC8NtAOJQ-sNC9XTKnLOX7eQ/edit#heading=h.ecg8w5wx2swc):
- Base forms for compact currency and compact decimal formats in numbers='latn' should be at moderate, not modern
- Where coverage is at basic/moderate for number symbols/formats with numbers='latn', coverage should be at the same level for non-latn number systems that are the defaultNumberingSystem in a locale. This will make several locales whose basic coverage is near 100% but moderate coverage is low drop out of basic until these items are supplied.
- In the TC meeting we …
=> CLDR-16941 Further number symbols/formats coverage fixes per TC discussion

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckConsistentCasing.java
- use the subtype mappings intead (the 'how to fix' link)
CLDR-16853
=> CLDR-16853 drop some additional raw links in tickets

tools/scripts/ansible/certbot-playbook.yml, tools/scripts/ansible/cldr-apps-playbook.yml, tools/scripts/ansible/nginx-playbook.yml
- http/2
- gzip compression fixes
CLDR-7633
=> CLDR-7633 ansible: move performance improvements into ansible

.github/workflows/keyboard.yml
- fix keyboard charts path in keyboard checker script - see #3691 
- use kmc alpha (18.x) version for v46 for keyboard check
CLDR-17610
=> CLDR-17610 fix keyboard chart path in keyboard action

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/DiskDataCache.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/FixedCandidateProvider.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- restructure DataPage / DiskDataCache to hold the candidate providers
- add a FixedCandidateProvider structure, designed to allow quick additions of future fixed candidates.
CLDR-17106
=> CLDR-17106 add more fixed candidate items

tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
CLDR-17459
This is done by removing them from an exception list.
That is, units are metric or metric_adjacent automatically have additional paths added for grammar support. These were on an exception list that suppressed that. By removing them from that list, they will have grammar paths added in locales that support grammar differences in units.
=> CLDR-17459 Add grammar for point and kilocalorie

common/main/en.xml, common/main/root.xml, common/supplemental/units.xml, common/validity/unit.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-13864
Adds unit `night`, as in "Your hotel reservation is for 3 nights". Because it is metric_adjacent, will get grammar
Adds to the normal places: en.xml, root.xml, units.xml, unit.xml
Because night is not convertible to either seconds or months, it has a new quantity. That is reflected in: units.xml, DtdData.java, UnitConverter.java, TestUnits.java
Also changes checkUnitLocalePreferencesTestIcu to not cause an error in testing the preferences test data file, with a CLDR-17581 LogKnownIssue.
=> CLDR-13864 Add night unit

tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitParser.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-17459
This is putting the groundwork in place for doing CLDR-17298, so ideally we would be able to merge today to allow for that additional PR.
It allow for units that use arbitrary constant integers, instead of limited cases like `100-kilometer`. So units like `items-per-12-cubic-meter` or `portion-per-12` all work.
In so doing, the code was moved from using the Continuations class to the UnitParser. The UnitParser has been around for a little while, with a test to ensure that the same results are obtained as using the older code. It is stricter, though, with more checks to make sure the spec grammar is followed, and drawing its data from units.xml. The changeover required a bit of finessing, because some of the UnitConverter code needs to be called in SupplementalDataInfo, and …
=> CLDR-17459 Prepare for adding units with constants

common/main/en.xml, common/main/root.xml, common/supplemental/units.xml, common/validity/unit.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-15216
To be used as a component of the names "light-second", "light-minute", etc.
See https://en.wikipedia.org/wiki/Light-second. Note that we would only have translators handle 1 item, and give instructions for the format in the context of being followed by duration.
=> CLDR-15216 Add light-speed

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
CLDR-11593
The CLDR ticket was mainly about updating the information for quarters in https://cldr.unicode.org/translation/date-time/date-time-names. But then I noticed that the Survey Tool sidebar link to that page from the date symbols & formats pages (e.g. for Gregorian) was wrong, so this PR fixes that.
=> CLDR-11593 Fix URL that ST date symbols page uses for sidebar info

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculatedCoverageLevels.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCoverageLevel2.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLevel.java
Also misc improvements:
- ToolConstants.previousVersion()
- CalculatedCoverageLevels.forVersion() for loading prior versions
- Level.isAbove()
CLDR-17634
=> CLDR-17634 Verify that all prior-Basic locale names have English and Coverage

common/main/ie.xml
CLDR-16734
In ie, add relative day ±2 (unconfirmed, like al of the relative fields there), obtained from online Interlingue dictionary [The English - Interlingue dictionary | Glosbe](https://glosbe.com/en/ie). This (per Mark) is the easiest way to make these fields appear in Survey Tool for Interlingue.
=> CLDR-16734 ie, add relative day ±2 (unconfirmed)

tools/cldr-code/src/main/java/org/unicode/cldr/test/BuildIcuCompactDecimalFormat.java
CLDR-16279
The Numbers report in Survey Tool (and Charts) is generated by util/VerifyCompactNumbers.java, which calls test/BuildIcuCompactDecimalFormat.java to assemble the formats. BuildIcuCompactDecimalFormat.buildCustomData() was iterating over the paths for compact number formats without paying attention to which ones were alt='alphaNextToNumber' (with spacing) and non-alt (normally without spacing), leading to random use of space in compact currency formats in the report (see the Numbers report for en_CA, for example). This PR fixes BuildIcuCompactDecimalFormat.buildCustomData() to explicitly choose the alt='alphaNextToNumber' format when appropriate (currency symbol has letter on side adjacent to value), and to skip the alt format (and use the standard format) otherwise.
It is …
=> CLDR-16279 fix random spacing in the Numbers report for compact currency

docs/ldml/tr35-general.md
and e-notation. Also do a bit of cleanup: adding links to the important syntax elements and changing the references to prefixes to point to the unitPrefix.
CLDR-17298
=> CLDR-17298 Update syntax to permit constants not followed by a unit

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-17147
In the dateTimePattern examples that were originally added per [CLDR-15622](https://unicode-org.atlassian.net/browse/CLDR-15622), change the examples that combine short date with full time to instead use long time (abbreviated zone) per Mark's review comment on the PR for that original ticket, PR [#2977](https://github.com/unicode-org/cldr/pull/2977)
(The ticket for this current PR is a clone of the original ticket specifically to address this issue)
[CLDR-15622]: https://unicode-org.atlassian.net/browse/CLDR-15622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17147 In dateTimePattern examples with short date, use abbreviated not full zone

common/main/csw.xml, common/main/kxv_Deva.xml, common/main/kxv_Orya.xml, common/main/kxv_Telu.xml, common/main/zh_Hans_MY.xml, common/main/zh_Hant_MY.xml
CLDR-17199
Add missing time formats using h in several new locales so ICU tests pass (locales that inherit from root and do not have time formats will get the root formats with H, which may not match the region time-cycle preference causing an ICU error).
- css (for CA): Use the formats for en_CA but these inherit from en, so use those.
- kxv_Deva, kxv_Orya, kxv_Telu (for IN): Use the formats for kxv (Latn).
- zh_Hans_MY, zh_Hant_MY: Use Chinese-style time formats using (a before h, etc). These are in availableFormats e.g. for zh; but the are used as the standard formats in zh_Hans_SG so just copy from there.
Somewhere we have a CLDR ticket to add a CLDR-side test for this so we fix it before we get to ICU integration.
=> CLDR-17199 Add missing time formats with h for several new locales

tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VerifyCompactNumbers.java
CLDR-15764
Add examples with RTL context (I addition to neutral context) to the date time & numbers reports where relevant. Also fix some other report issues:
- dateTime intervals involving a difference of just minutes had a bad end date.
- dateTime formats combining a relative day and a time should use the "atTime" variant of the combining pattern.
- the numbers reports did not show formats for negative numbers or zero, added those.
=> CLDR-15764 Add examples with RTL context to reports; fix other report issues

tools/cldr-apps/js/src/esm/cldrDash.mjs
- fix parameters to sheet construction
- refactor XLSX sheet and file calculation
- #3640 restructured some of the front-end data
CLDR-17465
=> CLDR-17465 Dashboard: fix xlsx download

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-10772
Add ST examples for month names showing them in appropriate context: format months in a format with day number (currently winning format for skeleton yMMMMd), and stand-alone months in a format without (currently winning format for skeleton yMMMM)
=> CLDR-10772 ST examples for month names, in appropriate format

tools/cldr-apps/js/src/esm/cldrDash.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
- remove duplicate StringId table within XPathTable
- improve error messaging in cldrDash.mjs
CLDR-17465
=> CLDR-17465 Dashboard/XPathTable

common/main/fil.xml, common/main/mai.xml, common/main/mgo.xml, common/main/sa.xml, common/main/so.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java
CLDR-13523
CheckDates had tests that abbreviated date symbols were no longer than wide (error), and that narrow date symbols were no longer than abbreviated (warning). But there was no test for short date symbols (only present in weekday names). Added a test that short days are no longer than abbreviated, and no shorter than narrow (both errors). Checked the with width both with a glyph width estimate (as used for the other tests) and a string length test, since the test was too sensitive otherwise (e.g. it failed on letter case differences).
Ran the test and fixed the resulting new data errors:
- `fil`: replaced current standalone narrow (same as abbreviated) with format short (shorter)
- `mai`: replaced the one provided short value (which was too long) with ↑↑↑ like the other short …
=> CLDR-13523 add test for valid short day length; fix resulting data errs

common/testData/units/unitsTest.txt, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateUnitTestData.java
CLDR-17665
Remove `beaufort` from the NOT_CONVERTABLE list in  GenerateUnitTestData since that is no longer correct, then regenerate the unit test data. This regen left alone (as expected) the `unitsTest.txt` entry for `beaufort` which had been manually added in PR [#3562](https://github.com/unicode-org/cldr/pull/3562). It also added entries for 3 new units:
- night
- portion-per-1e9
- light-speed 
=> CLDR-17665 remove beaufort from GenerateUnitTestData.NOT_CONVERTABLE; 17665

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/translation-hints/hints.txt
CLDR-13224
Remove translation hint for MK (old change, and the English name kinda says it all), and add translation hints for some recently added language codes that are referred to using multiple names in English
=> CLDR-13224 remove translation hint for MK, add hints for some newer languages

common/supplemental/supplementalData.xml
CLDR-11883
Update hour cycles for some en_XX locales (while keeping the basic h vs H matching the region), which may be closer to en_001 than to the preferred hour cycle types for the default language in region XX.  See ticket for more details.
=> CLDR-11883 update hour prefs for some en_XX locales

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
=> CLDR-17669 add Organization.airbnb

tools/cldr-apps/js/package-lock.json, tools/cldr-apps/js/package.json, tools/cldr-apps/js/src/esm/cldrClient.mjs, tools/cldr-apps/js/src/esm/cldrComponents.mjs, tools/cldr-apps/js/src/esm/cldrDash.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/views/CldrError.vue, tools/cldr-apps/js/src/views/GeneralInfo.vue, tools/cldr-apps/js/src/views/OverallErrors.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartSupplemental.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
CLDR-17560
- add new CldrError and OverallErrors components
- add new REST endpoint for whole-locale-errors
- remove Report for supplemental data (whole locale errors) and references thereto
- remove link from info panel to supplemental chart
- add whole-locale widget to General Info
=> CLDR-17560 Overall Errors

tools/cldr-apps/js/src/esm/cldrDash.mjs, tools/cldr-apps/js/src/views/AboutPanel.vue, tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/js/test/TestCldrDash.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
-For now, change only the front end, except for enabling Abstain for TC
-Abstain for TC is hidden (unchecked) by default
-Combine notifications in certain categories so that there is not more than one per page
-For now, apply this to only the Abstained category (not Missing); easy to change which categories are affected
-Add unit test
-Try to fix delayed visibility of checkbox click; alternatives and debugging for catCheckmarkChanged
-Remove delay from a-spin pending solution to delayed visibility of checkbox click
-Add Vue version to the About page; bugs may depend on Vue version
CLDR-17658
=> CLDR-17658 Improve Dashboard performance and UI; work in progress

tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/views/MainMenu.vue
- this is a testing facility.  Smoketest, etc don't acutally send mail, so there is a test facility. But it should not be visible in production.
- rename notifications to 'sumulate email notifications'.
- clean up ui slightly
CLDR-17620
=> CLDR-17620 hide the 'notifications' menu item in production

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRPaths.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ScriptToExemplars.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/locales/scriptToExemplars.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
- change tests to update scriptToExemplars.txt when -DSHOW_EXEMPLARS is set
- update scriptToExemplars.txt with instructions
CLDR-17395
=> CLDR-17395 update scriptToExemplars.txt from tests

.github/workflows/auto-author-assign.yml
- whoever opens the PR, gets assigned to it by default.
- can reassign if needed.
CLDR-17181
Pretty simple, just makes the PR author the assignee.
You can see it running in my fork here https://github.com/srl295/cldr/pull/6
=> CLDR-17181 add auto author assign

common/annotations/en.xml, docs/ldml/tr35-general.md, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CheckEmojiAnnotations.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Emoji.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
CLDR-17582
- This cleans up the English annotations according to the directions given to vetters.
- The multiword search keys are split up.
- Duplicates (or near duplicates), synonyms, and low-value terms are removed.
- or at least reduced, with a focus on items that had a very large number of annotations.
- Reduce the maximum number of search terms on items.
- Other misc. cleanup.
When reviewing, note that breaking up keywords and then alphabetizing means that phrases are distributed. Example:
- cp="😄"
- **old:** awesome | face | grin | grinning face with big eyes | happy | mouth | open | smile | smiling | smiling face with open mouth | teeth | yay
- **new:** awesome | big | eyes | face | grin | grinning | happy | mouth | open | smile | smiling | teeth | yay
We can't expect a …
=> CLDR-17582 Cleanup English annotations

tools/cldr-apps/js/src/esm/cldrAccount.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
CLDR-15744
Verified:
- voting and forum posts, etc, update the 'last seen' date
- login/logout through different methods affect last seen
- make sure the named session gets logged out, even if cookies were different
=> CLDR-15744 make sure settings.user.touch() is called

common/annotations/en.xml
CLDR-17582
A few trailing items, mostly from Fredrik
=> CLDR-17582 Cleanup English annotations #2

tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/index.js, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java, tools/cldr-apps/src/main/webapp/surveytool.css
=> CLDR-17462 update ST status icons for clarity

tools/cldr-apps/js/src/views/GeneralInfo.vue, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckConsistentCasing.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCoverage.java
=> CLDR-17680 fix spurious CheckConsistentCasing and CheckCoverage

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
- in #3743,  ReportId.supplemental was retired, but it occurs in some user rows
- skip over invalid rows
CLDR-17560
=> CLDR-17560 skip invalid report ids

tools/cldr-code/src/main/java/org/unicode/cldr/test/TestCache.java
- the data store on success is synchronized, but not the actual test itself
CLDR-16158
=> CLDR-16158 synchronize CheckCLDR in TestCache

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
- seems to be creating excessive DB connections
CLDR-15744
partial revert of #3761
for CLDR-17693
I'm not sure that is a root cause or not, but stack traces are pointing to user.touch(),
so reverting to at least mitigate issue.
=> CLDR-15744 partial revert of #3764 user.touch()

docs/site/development/new-cldr-developers.md
[CLDR-17566](https://unicode-org.atlassian.net/browse/CLDR-17566)
Part of the [CLDR --> GFM conversion project](https://docs.google.com/document/d/1NoQX0zqSYqU4CUuNijTWKQaphE4SCuHl6Bej2C4mb58/edit)
Converting https://cldr.unicode.org/development/new-cldr-developers
View text diffs [here](https://docs.google.com/document/d/1iefV741HMK19WOQLmR8oYpIfI4BM7zc7MdpED8q9jJw/edit)
[CLDR-17566]: https://unicode-org.atlassian.net/browse/CLDR-17566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17566 Converting new-cldr-developers to markdown

docs/site/downloads/brs-copy-en_gb-to-en_001.md
[CLDR-17566](https://unicode-org.atlassian.net/browse/CLDR-17566)
Part of the [CLDR --> GFM conversion project](https://docs.google.com/document/d/1NoQX0zqSYqU4CUuNijTWKQaphE4SCuHl6Bej2C4mb58/edit)
Converting https://cldr.unicode.org/development/brs-copy-en_gb-to-en_001
View text diffs [here](https://docs.google.com/document/d/11V8rDc2I3ZlKXzR3vbnychNLg8zTlIzXcAFtFsWtrqg/edit?usp=sharing)
[CLDR-17566]: https://unicode-org.atlassian.net/browse/CLDR-17566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17566 Converting brs-copy-en_gb-to-en_001 to markdown

docs/ldml/tr35.md
=> CLDR-17687 Correct the explanation of a canonicalization example

tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleUnicodeSetFormatter.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
CLDR-17703
- Handle nulls in the CodePointEscaper
- Add tests in UnicodeSetPrettyPrinterTest for edge cases.
- Also fix the simple test to add more cases (setting locale, and setting the useRangesAbove.
- Clean up SimpleUnicodeSetFormatter.java as well. 
- There were some test failures that led to cleaning up the handling of the default parameters.
- Renamed some variables/constants for clarity
=> CLDR-17703 Fix NPE in CodePointEscaper

tools/cldr-apps/js/src/esm/cldrDash.mjs
-Replace non-existent cat with comma-concatenated cats
-Example: Missing, Warning, Abstained
CLDR-17689
=> CLDR-17689 Dashboard download has empty Category column

.github/workflows/maven.yml, .github/workflows/production.yml, tools/scripts/ansible/hosts, tools/scripts/ansible/monitoring-playbook.yml, tools/scripts/ansible/requirements.yml, tools/scripts/ansible/templates/bootstrap-properties.j2
CLDR-17699
- we were missing sourcemap uploads for production and for smoketest (though smoketest isn't used with datadog currently)
- add ansible rules to enable datadog
=> CLDR-17699 DataDog in Ansible

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
=> CLDR-17560 skip more cases of ReportId.valueOf("supplemental")

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
CLDR-17590
Update coverage levels for Microsoft
=> CLDR-17590 Update coverage levels for Microsoft

tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateTransformCharts.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
CLDR-17719
I found that the coverage_goals.html chart was omitting Meta. I put in a fix so that it would be driven by the Organization.getTCOrgs().
I also generate a .tsv that reformats the Locales.txt data. The reformatted data sorts TC locales first, then others. It does not overwrite Locales.txt, but rather creates the .tsv with the staging charts.
The format looks like:
```
#Organization	;	Locale	;	Level	;	Locale Name
google	;	*	;	moderate	;	ALL
google	;	af	;	modern	;	Afrikaans
google	;	ak	;	moderate	;	Akan
google	;	am	;	modern	;	Amharic
google	;	ar	;	modern	;	Arabic
google	;	as	;	modern	;	Assamese
google	;	az	;	modern	;	Azeri
google	;	be	;	modern	;	Belarusian
google	;	bg	;	modern	;	Bulgarian
```
=> CLDR-17719 update v46 charts

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-Divide Length into Length_Metric and Length_Other
CLDR-17514
=> CLDR-17514 Pages too big: divide Length into Metric and Other

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckWidths.java
- mention both the warning and maximum values, not just the warning value.
CLDR-17532
=> CLDR-17532 improve CheckWidths message for annotations

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java
- this test is sensitive to the current CLDR locales at modern.
- change the test so that it reports *which* locales are causing the need for chars in the transforms.
CLDR-17726
=> CLDR-17726 make TestTransform.TestLocales less obscure

common/transforms/Ukrainian-Latin-BGN.xml
Fix comments. It is BGN/PCGN 1965 System, not BGN/PCGN 1979.
CLDR-14278
=> CLDR-14278 Update Ukrainian-Latin-BGN.xml

.github/workflows/maven.yml
CLDR-17699
An update to #3797 - I accidentally calculated the hash wrong for DataDog sourcemap uploads for smoketest.  Production and Staging are fine.  This will have no user visible effect, and I've tested it separately.
=> CLDR-17699 DataDog sourcemap fix for upload to smoketest

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-apps/src/test/java/org/unicode/cldr/web/DataDrivenSTTestHandler.java
- adding items was using the overall phase instead of the specific phase
CLDR-16835
=> CLDR-16835 fix phase check for adding items

tools/cldr-apps/js/src/esm/cldrVote.mjs
- whole-locale warnings/errs should not affect the kind (color) of a candidate item.
CLDR-17560
1. go to the 'csw' locale, such as <https://cldr-smoke.unicode.org/cldr-apps/v#/csw/Graphics/>
2. you should NOT  see every locale with a yellowish-tint background.
**Wrong:**
**Correct:**
=> CLDR-17560 don't show whole-locale warnings on row

common/supplemental/plurals.xml
- same as 'ak' etc, one = 0/1, other = *
CLDR-17667
=> CLDR-17667 csw plurals

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java, tools/cldr-code/src/main/java/com/ibm/icu/dev/util/ElapsedTimer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/TimeDiff.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
CLDR-17758
- as an Unaffiliated TC, TC can request a Priority Items Summary that includes ONLY non-TC locales.
- also split out Time Calc to improve the remaining time calculation for priority items
Re-do of #3133 
=> CLDR-17758 DDL: expand VettingViewerSummary for unaffiliated TC to all non-TC locales

.gitignore, common/testData/localeIdentifiers/localeCanonicalization.txt, common/testData/localeIdentifiers/localeDisplayName.txt, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLocaleIDTestData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
=> CLDR-17644 Add additional test data for locale display name algorithm

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
Accidentally introduced in 7d65bacef008d7f000fec331629faf7704669db5 #3182
CLDR-17758
=> CLDR-17758 remove dead code from VettingViewer.java

tools/cldr-apps/js/src/esm/cldrInfo.mjs
-Call updateCurrentId and setLastShown directly from listen if Info Panel is hidden
-This is a work-around; the selection should be independent of Info Panel and cldrInfo as stated in new comment
-Remove unused export for openPanel, called only locally
CLDR-17759
=> CLDR-17759 Clicking cell should select even if Info Panel is hidden

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-Divide Fields (in section DateTime) into Fields and Relative
CLDR-17514
=> CLDR-17514 Pages too big: divide Fields

tools/cldr-apps/js/src/esm/cldrReport.mjs, tools/cldr-apps/js/src/views/ReportResponse.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
Back end side:
- Change CheckCLDR.Phase.getShowRowAction() to allow pathValueInfo and pathHeader to be optional (null)
- add convenience functions on StatusAction
- Report API returns 403 forbidden if NOT in phase where voting is allowed.
CLDR-17776
=> CLDR-17776 disallow reports if vetting closed

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckChildren.java
- if a child's value is null, skip that child. It's clearly not overridden.
CLDR-17781
- in this case, yo_BJ (which is algorithmic anyway) did not have a value at `//ldml/dates/timeZoneNames/metazone[@type="Kazakhstan"]/long/standard`
- I don't think there's a need to skip algorithmic or other special locales here, it would be a minor speed optimization that wouldn't affect many cases.
=> CLDR-17781 CheckChildren should skip null values

tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- remove UI front end check for login to dashboard
- use UserRegistry.NO_USER (-1) as a userid, and organization unaffiliated, for such a guest dashboard.
- suppress the Abstain category, since the user can't vote anyway. (Losing is also going to be empty, so it will never show.)
CLDR-16799
=> CLDR-16799 allow not-logged-in to see dashboard

docs/ldml/tr35-dates.md, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DayPeriodInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
CLDR-16933
- Test adjustments needed to resolve an error in Ukrainian and perhaps also needed for other locales, per discussion in ticket:
- Let midnight match a non-fixed period that starts at, ends at, or contains midnight (both 00:00 and 24:00)
- Let noon match a non-fixed period that starts at, ends at, or contains noon (or just before noon);
- Add unit tests for this and for some other dayPeriodRuleSet name allowances we are already making.
- Add a spec note about formatting noon and midnight; these may not need an explicit numeric time, unless the same name is used for other dayPeriods. 
=> CLDR-16933 Allow names for noon, midnight to match adjacent non-fixed dayPeriods; add tests & spec note

tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Move cldrInfo.listen and related code to cldrTable.listen since its effects are not limited to the Info Panel
-This PR is intended not to change behavior, strictly as refactoring in preparation for further changes
-Comments
CLDR-17759
=> CLDR-17759 Move non-Info-Panel code from cldrInfo to cldrTable

tools/cldr-apps/js/src/esm/cldrDom.mjs, tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Previously the cell did not get highlighted unless the Info Panel was open
-New function setDivClassSelected calls setLastShown to add thick border after vote
-Refactor: new function setDivClassSelected combines updateCurrentId and setLastShown
-Refactor: move setDivClass from cldrVote to cldrTable
-Refactor: move parentOfType from cldrTable to cldrDom
-Comments
CLDR-17759
=> CLDR-17759 Highlight cell when vote for a candidate item

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-17756
Add a test for which paths don't have examples. 
Some paths don't have any obvious examples, because their values are not patterns, nor are components of patterns.
So there is a mechanism to exclude those paths.
The test currently succeeds, because all of the failures are now logKnownIssues, with a brief comment for what to do, and a list of the starred paths that need to be handled. The process will be to successively add examples for paths in ExampleGenerator, until the LogKnownIssues can be removed.
There were two tickets that I used for the logKnownIssues; the next step would be to file additional tickets, probably grouping related items so there aren't too many additional tickets.
Run TestForMissing -allKnownIssues to see the full listing, currently:
```
CLDR-15078 …
```
=> CLDR-17756 first cut at test for missing examples

tools/scripts/web/conversion_scripts/README.md, tools/scripts/web/conversion_scripts/cleanup.py, tools/scripts/web/conversion_scripts/pullFromCLDR.py
CLDR-17566
Scripts for partial automation of the conversion process for pages from the Google Sites into markdown.
See readme for more information.
=> CLDR-17566 conversion process scripts

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDisplayCollisions.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
CLDR-17792
Currently Survey Tools is reporting a display collision for \u200B (ZWSP) used as currency symbol for PTE in pt_PT, even though this is the value that has been there for several releases, and is the correct value to use since for this particular currency in pt_PT the symbol is actually in the decimal separator element; see https://st.unicode.org/cldr-apps/v#/pt_PT/C_SEEurope/7f78787c0e4c5be3 (best to view this with coverage set to Comprehensive to see the associated fields).
The error does not appear in offline unit tests or Console Check, so the fix here is somewhat speculative:
- Update SimpleXMLSource.NON_ALPHANUM so \u200B does not get stripped when comparing values across paths
- Update CheckDisplayCollisions to specifically allow a collision for  \u200B as a currency …
=> CLDR-17792 Don't strip ZWSP for value compare, allow currency symbol collision for it

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- The -M (Modern) option now defaults to false, but the user can set it to true
- also, fix a bug where the modern tier was emitted to PACKAGES.md and the cldr-packages.json file even if -M was false.
CLDR-16465
=> CLDR-16465 json: drop the -modern tier (by default)

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- drop //ldml/identity/version entirely (was producing _cldrVersion in every file)
- also, annotate the code working around CLDR-17790 as a TODO
- As a reminder, this will greatly reduce the diffs every time json is updated.
CLDR-17402
Example output with this change:
```diff
--- a/cldr-json/cldr-units-modern/main/zh/measurementSystemNames.json
+++ b/cldr-json/cldr-units-modern/main/zh/measurementSystemNames.json
@@ -2,9 +2,6 @@
"main": {
"zh": {
"identity": {
-        "version": {
-          "_cldrVersion": "46"
-        },
"language": "zh"
},
"localeDisplayNames": {
```
=> CLDR-17402 json: drop _cldrVersion path

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowCalendarGroups.java
CLDR-8823
Here is the current data generated. Shane was also interested in having something like this metadata for calendars in cldr, to help distinguish features of the calendars and set some constraints on behavior. To be discussed is what that would look like in XML.
Note that the days/month suppress the case where the month only has the max value. The columns **max days/year** and **max months/year** are computable from the corresponding detail columns. The data is generated by the code, which cycles over 1000 years just to catch edge cases. (If there are any other edge cases for calendars we should add them).
Calendars | max days/year | max months/year | max days/month | days/year | months/year | days/month
-- | -- | -- | -- | -- | -- | --
islamic islamic-civil islamic-rgsa …
=> CLDR-8823 Tool for grouping calendars by behavior

.github/workflows/gh-pages.yml, docs/site/development/development-process/design-proposals/xmb.md
- on PRs, we should build the gh-pages action to make sure there aren't syntax errs.
- Also, fix some syntax errs inadvertently brought in in #3855 
- deep details: <https://talk.jekyllrb.com/t/code-block-is-improperly-handled-and-generates-liquid-syntax-error/7599/2>
CLDR-17566
=> CLDR-17566 pre-test github pages before merge to main, also fix some items

tools/cldr-apps/js/src/esm/cldrInfo.mjs
-New boolean panelWanted records user preference
-New boolean parameter for closePanel distinguishes manually clicking close box from automatically closing when switching to special view where panel does not belong
-Revise panelShouldBeShown to check panelWanted and getCurrentSpecial
CLDR-16844
=> CLDR-16844 Remember whether the user wants the Info Panel

tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/views/InfoPanel.vue
-Add the boolean parameter for both callers
-Log error to console if parameter is undefined
CLDR-16844
=> CLDR-16844 Fix bug in last PR: require parameter for cldrInfo.closePanel

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAliases.java
CLDR-17812
Since the data in ak was fleshed out, it no longer illustrates an inheritance that was being tested in TestAliases/testCountBase. However `wo` Wolof is now a good example for that.
merge into [#3880](https://github.com/unicode-org/cldr/pull/3880)
=> CLDR-17812 v46 vxml: update locale for TestAliases/testCountBase

.github/workflows/production.yml, .github/workflows/staging.yml
- use the GITHUB_OUTPUT file instead of set-output in production
- drop an unneeded set-output in staging
CLDR-17184
We'll need to do a push to production to really test this.
=> CLDR-17184 fix some warnings in staging and prod actions

common/main/de.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
CLDR-17812
merge into [#3880](https://github.com/unicode-org/cldr/pull/3880)
`de` added unit data for speed-light-speed in which the "one" case has no placeholder; per discussion that reflects a misunderstanding of how this data is intended to be used, so add a placeholder so tests pass (the data will be deleted soon anyway). Also fix the wording of an error message in TestCheckCLDR/TestPlaceholders.
=> CLDR-17812 v46 vxml: Add {0} for de speed-light-speed one, fix error wording in TestCheckCLDR/TestPlaceholders

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-17812
merge into [#3880](https://github.com/unicode-org/cldr/pull/3880)
Updated the `hi` test in TestExampleGenerator/TestUnicodeSetExamples to match the `hi`i exemplar set change in [#3883](https://github.com/unicode-org/cldr/pull/3883)
=> CLDR-17812 v46 vxml: Update TestExampleGenerator/TestUnicodeSetExamples to match hi change in #3883

common/main/bew.xml, common/main/ha_NE.xml, common/main/tig.xml
=> CLDR-17812 v46 vxml fixes for ddls

tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchCLDR.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowInconsistentAvailable.java
CLDR-17544
In order to investigate the issue, I had to write a tool for investigating the issue. I foresee extracting some of the code into a test  or cldrCheck at some point.
=> CLDR-17544 Add tool for assessing issue

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestPathHeader.java
- update PathHeader with a %G, a list of calendars which use the Gregorian month names.
CLDR-8823
Includes a test. The test catches some issues.
=> CLDR-8823 Don't use Jan, Feb, for non-gregorian calendar systems

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowInconsistentAvailable.java
CLDR-17544
- Added a listing of the order of elements by calendar, and by field.
- Added check on interval formats as well. (Exposed problem in interval data, [CLDR-17827](https://unicode-org.atlassian.net/browse/CLDR-17827)
- Also some cleanup, including adding options.
I had hoped to find that eras were consistently ordered (first or last), but that fails with interval patterns.
Results are in https://docs.google.com/spreadsheets/d/1SuCwDlhRE0MgTF-pqAc3qjapKRcNkp_bs5OxoiBxZrQ/edit?gid=1650978285#gid=1650978285
[CLDR-17827]: https://unicode-org.atlassian.net/browse/CLDR-17827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17544 Enable testing order

tools/cldr-apps/js/src/esm/cldrDashContext.mjs, tools/cldr-apps/js/src/esm/cldrDashData.mjs, tools/cldr-apps/js/src/esm/cldrEvent.mjs, tools/cldr-apps/js/src/esm/cldrGui.mjs, tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrProgress.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/js/src/views/GeneralInfo.vue, tools/cldr-apps/js/src/views/OverallErrors.vue, tools/cldr-apps/js/test/TestCldrDashData.mjs, tools/cldr-apps/js/test/index.js
-New module cldrDashContext.mjs, mostly code moved from cldrGui.mjs
-Encapsulate some constant strings such as OPEN_DASH_BUTTON_CLASS
-Rename cldrDash.mjs to cldrDashData.mjs for clarity
-Rename TestCldrDash.mjs to TestCldrDashData.mjs
-Remove unused parameter tr from cldrTable.getSingleRowUrl
-Remove some debugging console.log calls from DashboardWidget.vue
-Comments
CLDR-16844
=> CLDR-16844 Preliminary refactoring for Dashboard

common/bcp47/timezone.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
CLDR-17111
This PR revises changes from #3736 (cc @yumaoka) to align CLDR's aliases for recently deprecated zones to match IANA's Link=>Zone mappings in the following recent commits:
https://github.com/eggert/tz/commit/782d082623aaa130178d944bdbfbb563d2e1adfa
https://github.com/eggert/tz/commit/a0b09c0230089252acf2eb0f1ba922e99f7f4a03
It also fixes tests broken by these deprecations.
=> CLDR-17111 Deprecate old style zone IDs (e.g. EST5EDT, EET)

common/main/an.xml, common/main/rif.xml, common/main/si.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java
CLDR-17827
Added a check that intervalFormats do not cause problems in DateIntervalInfo.genPatternInfo(), except that there is an ICU bug in DateIntervalInfo.genPatternInfo with intervals in which the repeated field uses two different forms, like LLL - MMM, so skip the test for such patterns (which occur in `fa`); filed [ICU-22835](https://unicode-org.atlassian.net/browse/ICU-22835) about the bug.
Fixed bad intervalFormats in `an`, `rif`,`si`.
[ICU-22835]: https://unicode-org.atlassian.net/browse/ICU-22835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17827 check that intervalFormats pass DateIntervalInfo.genPatternInfo; fix an,rif,si

common/dtd/ldml.dtd, common/main/en_ZA.xml
New PR, replacing https://github.com/unicode-org/cldr/pull/3908
----
[CLDR-17675](https://unicode-org.atlassian.net/browse/CLDR-17675)
Revert the decimal/grouping change, but add alts to allow implementations to choose between official and us variant.
From the discussion in the Design meeting, we agreed on 2 variants, plus the default, as the normal pattern. That allows implementations to pick among the two choices by name — without having to know which was the default — or pick the default. People are also in favor of using semantic alt names, rather than just 'variant'.
Still draft because I want to pass this by the TC; there were a couple of things I wanted to get feedback on.
I think the decision was to go with the official syntax (12,34) for the default, but wanted feedback.
For the …
=> CLDR-17675 Revert change in en_ZA

tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
=> CLDR-17847 Fix NPE in CodePointEscaper

common/main/brx.xml, common/main/cy.xml, common/main/hi_Latn.xml, common/main/hy.xml, common/main/km.xml, common/main/kn.xml, common/main/kok.xml, common/main/om.xml, common/main/pa.xml, common/main/sw.xml, common/main/ta.xml, common/main/ti.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchCLDR.java
Drawing on similarity with closely related patterns. Only modifying ↑↑↑ values. 
Note: There are lots of inconsistencies in formatting and ordering, so I limited the changes to what appears to be clear-cut cases. I think the best we can do is add warnings in an upcoming submission cycle, so I'll clone a ticket for that.
Small changes in search tooling.
CLDR-17544
=> CLDR-17544 Fix just the modern paths for gregorian calendar

common/dtd/ldml.dtd, common/main/en_ZA.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowInconsistentAvailable.java
CLDR-17544
Adjust tool to suppress Mn Ms differences, if those are the only differences (affects basically Slavics)
=> CLDR-17544 Adjust tool to suppress Mn Ms differences

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/src/main/webapp/surveytool.css
-Move flagging instructions lower, immedately before Request button
-Move that code from cldrInfo to cldrForum
-Revising wording of instructions for clarity and consistency
-Remove unhelpful message, Losing items may be flagged...
-Revise flagging Request button css so flag icon is visible even when not hovering, and changes color when hovering, for emphasis
-Add hover text for the Stop icon in the Others column, same text as shown with Stop icon in the Info Panel
-New reminder in dialog for entering flagging Request post: ...MUST provide justification...
-Disallow making a flagging Request post with unchanged pre-fill contente
-Remove dead code from css
CLDR-17516
=> CLDR-17516 Revise flag interface

common/main/ak.xml
CLDR-17852
As requested in CLDR TC meeting 2024-07-31, this PR changes epsilon and open-o characters to match main exemplar. Specifically:
- epsilon U+0511 (Cyrillic range) changed to U+025B
- open-o U+037B (Greek range) changed to U+0254
Additionally some accented vowels (which occur in the existing data) are added to the auxiliary exemplar.
=> CLDR-17852 fix characters in ak.xml

tools/cldr-code/src/main/java/org/unicode/cldr/util/BidiUtils.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java
CLDR-17844
Modify the date report to help figure out what is happening with the date formats, and present the user with more and clearer information.
- Added BidiUtils with utilities for display of examples/reports
- Small changes to CodePointEscaper, plus support for printing a table of escape IDs in a report.
- DateTypeFormats
- General cleanup
- Add a paragraph of text underneath **Patterns** to explain the format. Clarify that this is for the default number system, and explain more about the format
- In an RTL language there may be two examples, the top one is the dir=<locale-direction>, and second is dir=auto with a distinct background. This allows vetters to see the contrast, and correct if important.
- Add a line showing the escaped text
- Add a warning when the reordering causes …
=> CLDR-17844 Modify the date report

common/dtd/ldml.dtd, common/main/en.xml
This starts the ball rolling in adding recognition for the name Mvskoke -- an endonym for Muscogee. Initially we just want to add it as a variant. In the future we may want to swap the official & variant options if the Mvskoke/Muscogee linguistic authority prefers it.
[CLDR-17761](https://unicode-org.atlassian.net/browse/CLDR-17761)
[CLDR-17761]: https://unicode-org.atlassian.net/browse/CLDR-17761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17761 Update en.xml -- add variant Mvskoke to Muscogee (mus)

tools/cldr-apps/js/src/esm/cldrForum.mjs
-New class PostInfo
-Delete dead code
CLDR-17799
=> CLDR-17799 Forum preliminary refactoring, class PostInfo

common/main/uz_Cyrl.xml, common/properties/coverageLevels.txt
This adds values for the symbols and number formats for `numberSystem="arab"` -- copying over the values from `numberSystem="arabext"`. The problem was that arab was added as a number system for uz.xml (== uz_Latn.xml) so uz_Cyrl.xml needed declarations.
Ran `java -jar tools/cldr-code/target/cldr-code.jar ShowLocaleCoverage` to regenerate coverage level text.
CLDR-17843
=> CLDR-17843 Restore uz_Cyrl to basic coverage by fixing numerals

common/main/he.xml
CLDR-17839
Update he narrow units to inherit from short
=> CLDR-17839 Fix units in he

common/main/ug.xml, common/properties/coverageLevels.txt
Arabic and Arabic Extended are missing number formats -- just inherit. Same for symbols. Separately the exemplar characters need to be updated too.
https://unicode-org.atlassian.net/browse/CLDR-17843
CLDR-17843 
=> CLDR-17843 Update ug.xml Add missing values to keep basic coverage.

common/main/gaa.xml
CLDR-17859
Locale data is only converted for ICU if it has draft status of at least contributed, so the `gaa` timeFormats with 'h' were not being picked up and in ICU the `gaa` locale was inheriting timeFormats from root using H. This caused an error in an ICU test that the timeFormats hour cycle matches the region preference. So we promote the `gaa` timeFormats to contributed.
=> CLDR-17859 gaa timeFormats unconfirmed->contributed to pass ICU tests

common/main/he.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt
CLDR-17839
Working off of https://docs.google.com/spreadsheets/d/1dRVt9xb4Ffsf86DrxbPIaj26qVz0GB7DL7yyE9N5pfI/edit?gid=2136703940#gid=2136703940 , which has units that contained {, but didn’t start with {0}. 
In particular:
- fixed patterns have {0} uniformly at the start, if it wasn't already. 
- there were 2 exceptions, with a medial {0} that I left alone. 
- fixed a few places where the unit started or ended with a neutral (by protecting with LRM or LRM)
- fixed some others that had excess LRM/RLM
- the remaining LRMs — for clarity in review — are all in xml format (&#x200e;), which will be converted back to the regular character during cldr modify passes.
- fixed places where apostrophe was used instead of  ‎׳‎ U+05F3 HEBREW PUNCTUATION GERESH
For the future, I think we should provide …
=> CLDR-17839 Further fixes for Hebrew units

common/main/scn.xml, common/supplemental/pluralRanges.xml, common/supplemental/plurals.xml
CLDR-17673
Command to regenerate pluralRanges.xml: `java -jar tools/cldr-code/target/cldr-code.jar GeneratePluralRanges`
=> CLDR-17673 update plural forms for Sicilian (scn)

common/main/blo.xml, common/main/es_GT.xml, common/main/si.xml, common/main/vec.xml
CLDR-17865
Fixed most of the cases mentioned in [CLDR-17865](https://unicode-org.atlassian.net/browse/CLDR-17865) where there are inconsistencies among the currencyFormats/unitPattern items for different plural cases in a locale. Note that the pattern in root for `other` and the patterns in English for `other` and `one` are all "{0} {1}" which produces results like "1 Euro" and "3 Euros". Many of the discrepancies in the ticket were for cases that had "{0} {1}" for the non-`other` cases but "{1} {0}" for the `other` case. The TC discussion was to prefer the `other` case pattern which would produce results whose English equivalent would be something like "Euros 3" (vs "1 Euro" which might be the desired result for `one` in some locales). I checked the Survey Tool votes and discussion (no …
=> CLDR-17865 Fix some bad currencyFormats/unitPattern items

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckExemplars.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
- update CheckExemplars parseLenient to error instead of crash on null
- update CheckPlaceHolders to skip aliases instead of crashing
- remove the logknownissue which was to suppress the crash stack traces
CLDR-17320
=> CLDR-17320 check fixes to avoid stack traces

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
CLDR-16180
Adds Romanian to list of languages in United Kingdom. See discussion in CLDR ticket listed above.
Note: No action is being taken for other language population figures.
=> CLDR-16180 Add Romanian to UK in country_language_population.tsv

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
CLDR-17877
Two rows in country_language_population.tsv had misaligned columns. This pull request adjusts the tabs in those rows to realign the column information.
=> CLDR-17877 repair country_language_population.tsv columns

common/annotations/en_001.xml, common/main/en_001.xml
- skipping dateformats for now but will improve the chart
CLDR-17867
=> CLDR-17867 BRS: en_001 updates per spreadheet

common/main/mn_Mong_MN.xml
- it's draft, incorrectly duplicates decimal, and is not a complete logical group.
CLDR-16413
=> CLDR-16413 for now, drop the mn_Mong_MN grouping separator

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
=> CLDR-17856 nan and hak in Taiwan

common/bcp47/currency.xml, common/main/en.xml, common/supplemental/supplementalData.xml, common/validity/currency.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/LogicalGroupChecker.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/IsoCurrencyParser.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLevel.java
- update ZWG per ISO amendment
- retain USD as valid due to feedback and articles
- update English
CLDR-17751
=> CLDR-17751 add ZWG, drop ZWL

common/supplemental/supplementalData.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelySubtags.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/LSRSource.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/LangTagsData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LanguageTagCanonicalizer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleScriptInfo.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
CLDR-17535
The goal is to integrate the SIL data reading into the tool for generating likely subtags. I'm creating a new tool because it needs some major cleanup in order for it to work.
common/supplemental/supplementalData.xml
- fixed a few values for the predominant script
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelySubtags.java
- completely new tool for generating the likely subtag data. It takes code from GenerateMaximalSubtags and breaks it apart into separate files, and cleans up a lot of cruft.
- It now takes regular console options, and the options provide a lot of control over seeing what is happening at each point in the process.
- It incorporates code to directly add the SIL data, after filtering out any data that would be redundant. It does a much better …
=> CLDR-17535 Update LikelySubtags tool

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-10347 Show one example for each day period. Currently suppresses examples for the day period "midnight" (due to [ICU-12278](https://unicode-org.atlassian.net/browse/ICU-12278), lack of controlled use of midnight), but handles remaining day periods and adds relevant samples.
| Locale           | Before | After |
| -------------- | -------------- |  -------------- |
| he       | <img width="530" alt="Screenshot 2024-08-09 at 1 04 25 PM" src="https://github.com/user-attachments/assets/ac42f89f-30c6-46d4-91b8-5d9322c40725"> <img width="530" alt="Screenshot 2024-08-09 at 1 04 46 PM" src="https://github.com/user-attachments/assets/a789db9d-5f08-4265-816b-d2f9436b4b81">| <img width="535" alt="Screenshot 2024-08-09 at 1 05 36 PM" src="https://github.com/user-attachments/assets/11e983d6-296e-4 …
=> CLDR-10347 show one example for each day period, excluding midnight

README.md
- update to wording
https://github.com/unicode-org/.github/issues/17
CLDR-17898
=> CLDR-17898 Update README.md

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/views/AnnounceForm.vue, tools/cldr-apps/js/src/views/AnnouncePost.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java
(Note: waiting for #3795 )
CLDR-16835
- Announcement UI to announce to Non-TC locales, and/or Non-TC orgs 
Supports CLDR-16614
=> CLDR-16835 DDL announcement

common/segments/root.xml
CLDR-17830
Nothing special, just regenerating the rules from unicodetools to match the soon-to-be-released Unicode.
=> CLDR-17830 Regenerate segmentation data

tools/cldr-apps/js/src/esm/cldrTable.mjs
-Move the LR marker div below the i-star icon, simply by moving the call to checkLRmarker a few lines lower
-Also remove a comment in the same file about appendExample which is no longer true, and remove the export for appendExample which is no longer needed
CLDR-17572
=> CLDR-17572 Move LR marker div below star

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/js/src/esm/cldrForumPanel.mjs, tools/cldr-apps/js/src/esm/cldrInfo.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/views/ForumButton.vue, tools/cldr-apps/js/src/views/ForumForm.vue
-New ForumButton.vue, ForumForm.vue; revise cldrForum.mjs; related refactoring
CLDR-17799
=> CLDR-17799 Use Vue components for forum form and buttons

common/supplemental/metaZones.xml, common/supplemental/windowsZones.xml
=> CLDR-17901 Remove deprecated zone IDs from metaZones/windowsZones.

common/supplemental/supplementalData.xml
CLDR-15697
Update AE first day of the week to mon
=> CLDR-15697 Update AE first day of the week to mon

common/supplemental/languageInfo.xml
=> CLDR-17382 languagematch Ukrainian should not fall back to Russian

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs, tools/cldr-apps/js/src/esm/cldrGenerateVxml.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/esm/cldrVueMap.mjs, tools/cldr-apps/js/src/views/GenerateVxml.vue, tools/cldr-apps/js/src/views/MainMenu.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/OutputFileManager.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VxmlGenerator.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VxmlQueue.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/GenerateVxml.java
-Front end: new GenerateVxml.vue, cldrGenerateVxml.mjs
-Back end: new GenerateVxml.java, VxmlQueue.java, VxmlGenerator.java
-Run the task in its own thread, with multiple http requests fetching status until done
-Partly imitate implementation of Priority Items Summary: GenerateVxml.java corresponds to Summary.java; VxmlGenerator.java corresponds to VettingViewer.java; VxmlQueue.java corresponds to VettingViewerQueue.java
-Revise OutputFileManager.java as needed and also to fix some (not all) compiler warnings
-Disable Announce requests while VXML generation is in progress (only on front end; only affects the browser of the Admin user, not other users if running on remote server)
-Fix bug in XPathTable.loadXPaths, DB connection without commit, change getDBConnection to getAConnection for …
=> CLDR-14913 Add Download XML button to Survey Tool

docs/site/downloads/cldr-46.md
Small updates from TC meeting.
CLDR-17830
=> CLDR-17830 BRS Alpha release page 2

docs/site/_layouts/page.html, docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js
CLDR-17803
- improve look of top nav. 
- don't list a page twice in subpages
- show entire breadcrumb
- looking at comments from https://github.com/unicode-org/cldr/pull/4020
=> CLDR-17803 site: improve top nav

docs/site/assets/js/cldrsite.js
only show subpages of an index page, not siblings.
CLDR-17803
=> CLDR-17803 site: hide sibling pages

docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js
CLDR-17803
'popup' menu of subpages
@macchiati with position:absolute the menu was harder to access (it would disappear when trying to move over to it
=> CLDR-17803 site: popup menu for subpages

docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js
=> CLDR-17803 site: improved popup

tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestUserRegistry.java, tools/cldr-apps/src/test/resources/org/unicode/cldr/web/data/TestSTFactory.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestHelper.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVoteResolver.java
-Avoid confusion with util.TestUtilities
CLDR-15029
=> CLDR-15029 Rename unittest.TestUtilities to unittest.TestHelper

docs/site/.gitignore, docs/site/_layouts/page.html, docs/site/assets/js/build.mjs, docs/site/package-lock.json, docs/site/package.json, docs/site/robots.txt
CLDR-17935
- add sitemap.xml for crawlers
This is unrelated to site organization or navigation. It's so that the crawlers can index the site properly.
=> CLDR-17935 site: add crawler sitemap

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
-Remove code that creates unused db table sf_loc2forum
-Revise the implementation of localeToForum by calling getLanguage instead of toULocale().getLanguage
CLDR-17071
=> CLDR-17071 Do not create unused db table sf_loc2forum; improve localeToForum

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
[output.txt](https://github.com/user-attachments/files/16352544/output.txt)
before:
after:
CLDR-15698
- [CLDR-15698 ] This PR completes the ticket.
=> CLDR-15698 Time examples < 10 and > 12

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-17949
ICU is returning random zones that don't resolve… work around it so CLDR can merge PRs…
=> CLDR-17949 hotfix for random ICU timezone breakage

docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js
- add a popup site map
CLDR-17934
=> CLDR-17934 user-visible sitemap

docs/ldml/tr35-info.md
=> CLDR-17893 Clarify rg validation for unit preferences

docs/site/assets/css/page.css, docs/site/assets/js/build.mjs
CLDR-17947
- css: pin image width to 100% of the parent (the page), and also pin height to 90% of the viewable area.
also:
- fix builder for windows pathnames
- before: https://cldr.unicode.org/index/language-support-levels
- after: https://b1085791.cldr.pages.dev/index/language-support-levels
=> CLDR-17947 site: pin image width, win fix

common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelySubtags.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
If we re-run ConvertLanguageData on unrelated data, it will update the order and values of some other data -- this fixes inconsistencies with the XML outputs to match expectations. The biggest change was updating values in `language_script.tsv` to demote script variations to secondary when they really are not expected. Furthermore I added explicit annotations to `country_language_population.tsv` when the writing system for a country was a variant.
CLDR-17897
Scripts ran
=> CLDR-17897 Make ConvertLanguageData Consistent

docs/site/assets/css/page.css
merge conflict broke css for img
compare the images https://cldr.unicode.org/index/keyboard-workgroup to https://c6075b6b.cldr.pages.dev/index/keyboard-workgroup
CLDR-17947
=> CLDR-17947 site: css: fix breakage

docs/ldml/tr35-dates.md
=> CLDR-17842 Add semantic skeleton spec text

docs/ldml/tr35.md
CLDR-17770
Clarify what the alias element path value is relative to (the path to the parent of the alias element, not the path of the alias element itself).
=> CLDR-17770 Clarify what the alias element path value is relative to

docs/ldml/tr35-general.md
This is a fix for the problem noted in https://unicode-org.atlassian.net/browse/CLDR-17298?focusedCommentId=177586
CLDR-17298
=> CLDR-17298 Fix problem with unit exponents

docs/site/downloads/cldr-46.md
CLDR-17830
First cut for spec beta
=> CLDR-17830 Update release page

tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config.txt
- The iso8601 calendar type was added in CLDR-17892
- Add this calendar type under the `cldr-dates-full` package
- TODO: in CLDR-17984 add a test to catch new calendars
CLDR-17918
(Note: the package mentioned above is where gregorian and generic are already kept.)
=> CLDR-17918 json: put 8601 calendar under dates

docs/site/_redirects
CLDR-17977
> It appears that [https://cldr.unicode.org/index/cldr-spec/unicode-transliteration-guidelines](https://cldr.unicode.org/index/cldr-spec/unicode-transliteration-guidelines#h.wh84w0csexl6) is another link that used to work but doesn’t any more.
- https://6a4424c6.cldr.pages.dev/index/cldr-spec/unicode-transliteration-guidelines#h.wh84w0csexl6
- 
=> CLDR-17977 Update _redirects

common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
See https://unicode-org.atlassian.net/browse/CLDR-11567 and https://translatorswithoutborders.org/language-data-for-el-salvador
Re-generated the xml with `mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags`
CLDR-11567
=> CLDR-11567 Add population counts for El Salvadoran Languages

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-5854
| Locale               | Before               | After |
| -------------- | -------------- |  -------------- |
| cy |  <img width="335" alt="Screenshot 2024-08-27 at 4 33 56 PM" src="https://github.com/user-attachments/assets/bf40d024-ed64-4d57-9ca9-faf79074f50f"> |  <img width="511" alt="Screenshot 2024-08-27 at 4 34 32 PM" src="https://github.com/user-attachments/assets/005e21de-8a2e-4b65-be77-2167e5aa973a"> |
| cy |  <img width="409" alt="Screenshot 2024-08-27 at 4 35 20 PM" src="https://github.com/user-attachments/assets/6c2fd76e-52c8-496b-9a86-15a68a7f9d04"> | <img width="917" alt="Screenshot 2024-08-27 at 4 50 53 PM" src="https://github.com/user-attachments/assets/25d57321-8073-4301-944b-68d86837c138"> |
| cy | <img width="770" alt="Screenshot 2024-08-27 at 4 36 47 PM" …
=> CLDR-5854 Add-examples-for-relative-dates-and-times

docs/site/.gitignore, docs/site/_layouts/sitemap.html, docs/site/assets/css/page.css, docs/site/assets/css/reports-v2.css, docs/site/assets/js/build.mjs, docs/site/assets/js/cldrsite.js, docs/site/sitemap.md, docs/site/sitemap.tsv
CLDR-18001
lot of copy and paste here, to cleanup (modularize) in the future.
- `sitemap.md` is empty but could have instructions or notes which appear above the sitemap. 
- go to the cloudflare site linked below
- notice that the sitemap is a separate page, accessible by header and as a normal subpage of index
=> CLDR-18001 site: move sitemap to separate page

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
CLDR-16720
- no leading or trailing spaces on json transform .txt files
=> CLDR-16720 json: trim output files for transforms (v46)

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
=> CLDR-11018 currency decimal place isn't accurate in the examples

docs/site/downloads/cldr-46.md
CLDR-16062
Update migration notes for 46 about collation removal with link to ticket and updated version number
=> CLDR-16062 Update migration notes about collation removal

tools/cldr-apps/js/src/esm/cldrGenerateVxml.mjs, tools/cldr-apps/js/src/views/GenerateVxml.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/OutputFileManager.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VxmlGenerator.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/VxmlQueue.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/GenerateVxml.java
-Request every 5 seconds instead of 10 seconds for better feedback
-Change button from Stop to Cancel, less ambiguous
-Change status label from READY to SUCCEEDED, less ambiguous
-Show the full path of the generated directory, along with a button for copying it to the clipboard
-Do not create a long HTML string on the back end combining various types of information; instead, store individual data items in the http response, enabling the front end to determine their presentation
-Do not show the entire list of locales generated; instead, show the number of locales generated so far as numerator and the total number of locales to be generated as denominator, along with the most recent locale generated
-Bug fix: enable repeated runs with new method QueueEntry.reset
-Rename …
=> CLDR-17953 Improve UI and implementation for VXML generation

docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js
CLDR-18001
- adds Contents section to sidebar, with auto-link headers.  For now, it just has a flat list of headings and doesn't try to sort out the nesting.
- Fix an issue with the "subpage" arrow so it doesn't collide.
=> CLDR-18001 site: add Contents to sidebar, fix arrow

docs/site/assets/css/page.css, docs/site/assets/js/cldrsite.js, docs/site/cldr-tc.md, docs/site/development/development-process.md, docs/site/development/development-process/design-proposals/bcp-47-changes-draft.md, docs/site/development/development-process/design-proposals/chinese-and-other-calendar-support-intercalary-months-year-cycles.md, docs/site/development/development-process/design-proposals/delimiter-quotation-mark-proposal.md, docs/site/development/development-process/design-proposals/json-packaging-approved-by-the-cldr-tc-on-2015-03-25.md, docs/site/development/updating-codes/un-literacy.md, docs/site/translation/displaynames/countryregion-territory-names.md, docs/site/translation/displaynames/locale-option-names-key.md
CLDR-18001
- suppress link to title in ToC, hide ToC if empty
- suppress title h1 entirely, add centered title
- shift ToC over to the left one
- check links in ToC on index and subpages
- check the /development page as an example of a page that will not have a 'Content' sidebar in this change
=> CLDR-18001 site: fix link in ToC to entire page, fix some titles

docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35.md
CLDR-18022
- Fixed links as per ticket, except for message-format.md (will be done separately)
- Also added some missing links to the EBNF for units.
=> CLDR-18022 fix spec links

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestURLs.java
CLDR-18032
Separated off part of a ticket that needed to go to main instead of maint-46.
While this needs further refinement, I'd like to get the basic version into main.
=> CLDR-18032 Tooling for bad urls

docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md
CLDR-18028
Includes
- Updates to the terms of use and status for each section.
- Deletion of some outdated notes in summaries (eg, "some links may lead to in-development ...")
- In tr35.md, also:
- reworded the explanation of the relationship between _Unicode BCP 47 locale identifier_ and_BCP 47 language tag_, also adding 2 links for more information
- fixed typos
This does **not** do the final adjustments before release:
- changing `|Version|46 (draft)      |` to `|Version|46 |`
- Hiding `_This is a draft document…` and unhiding `_This document has been…`
- Fixing the TOC
=> CLDR-18028 Fix final items in spec before release

.github/workflows/keyboard.yml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
- also fix compiler version to pickup latest stable
CLDR-17948
=> CLDR-17948 v46 dtd: conformsTo needs to include current CLDR version

docs/site/downloads/cldr-46.md, docs/site/downloads/cldr-47.md, docs/site/index.md, docs/site/sitemap.tsv
CLDR-18057
- For CLDR 46 release note:
- Remove beta status note at the top
- Change spec links using smoketest to use final posted spec
- Add CLDR 47 stub release note
- On homepage, replace announcements of CLDR 46 alpha/beta with announcement of final
=> CLDR-18057 BRS 46 Download page remove beta, fix spec links; announcement; stub 47 page

docs/site/downloads/cldr-46.md
=> CLDR-18058 Release page nits

common/main/ht.xml, common/main/ht_HT.xml, common/supplemental/attributeValueValidity.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java
This adds core data for Haitian Creole so that in Fall 2024 / v47 we can fill out the information for this locale.
CLDR-17587
=> CLDR-17587 Add Haitian Creole

docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md
CLDR-18062
Update spec version. The status (draft, proposed update) was mostly already correct on the main branch, except that "Tech Preview" needed to be removed from the Keyboards part as was done on the maint/maint-46 branch as part of PR [#4150](https://github.com/unicode-org/cldr/pull/4150) (but we do not want the rest of that PR's changes in main)
=> CLDR-18062 Update spec version, and status where necessary

common/main/en.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java, tools/cldr-code/src/test/java/org/unicode/cldr/test/TestEnInheritance.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
-New TestEnInheritance.java checks modern coverage inherited values in en that are marked with up arrows or are null
-Make TestPaths.extraPathAllowsNullValue public and static for use by TestEnInheritance
-New CLDRModify option -fE corrects problems that would fail TestEnInheritance
-Revise common/main/en.xml per running CLDRModify -fE
CLDR-17088
=> CLDR-17088 Flesh out en.xml

common/transforms/de-ASCII.xml
CLDR-18042
Latin-ASCII actually exists.
=> CLDR-18042 Replace `Any-ASCII` reference by `Latin-ASCII`

docs/site/development/development-process/design-proposals/european-ordering-rules-issues.md, docs/site/index/cldr-spec/transliteration-guidelines.md
- tables were broken in the transliteration guidelines
- broken (escaped) NCRs
- http to https
CLDR-18065
compare to broken tables on https://cldr.unicode.org/index/cldr-spec/transliteration-guidelines
=> CLDR-18065 site: typo fixes

common/properties/scriptMetadata.txt, common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelySubtags.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Script_Metadata.csv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
CLDR-11570
Ancient Greek is only written in Greek alphabet rather than Linear B or Cypriot Syllabary -- so this change corrects that. In fact, Linear B was never used for Ancient Greek -- rather it was used by its predecessor Mycenaean Greek (ancient greek to the ancient greeks). The Cypriot Syllabary was used primarily for a different language, Eteocypriot -- its not related to Greek or Indo-European. There is some Ancient Greek text (particularly the Arcadocypriot dialect) in the Cypriot Syllabary, and it's even present in the [Idalion Tablet](https://en.wikipedia.org/wiki/Idalion_Tablet) and the [Idalion bilingual](https://en.wikipedia.org/wiki/Idalion_bilingual) but its pretty rare.
Unfortunately I cannot list "Cypriot Syllabary" as secondary without it bumping out the Greek Alphabet …
=> CLDR-11570 Update Ancient Greek writing systems

docs/site/downloads/cldr-45.md, docs/site/downloads/previous-releases.md, docs/site/index/charts.md, docs/site/index/cldr-spec/coverage-levels.md, docs/site/index/cldr-spec/transliteration-guidelines.md, docs/site/index/json-format-data.md, docs/site/index/language-support-levels.md, docs/site/index/locale-coverage.md, docs/site/index/requesting-additionsupdates-to-cldr-languagepopulation-data.md, docs/site/index/survey-tool.md, docs/site/index/survey-tool/survey-tool-accounts.md, docs/site/translation/getting-started/plurals.md
-Fix numerous links in the Sites tab of the sheet linked to the ticket
CLDR-18072
=> CLDR-18072 Clean up links in CLDR site

docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35.md
CLDR-15948
docs/ldml/tr35-general.md
- Added a clearer anchor (the old anchor remains valid)
- Having the unit_identifier ABNF in a table is too painful to edit so I converted to markdown.
- The constraints were turned into either well-formedness constraints or validity constraints.
- The substantive change was to add the following to the definition of `base_component`
- [ vc:  Must be an attribute value of the `source` in: \<convertUnit source='…' …\> or the `type` in \<unitAlias type="…" replacement="…" …\> ]
- Fixed typos from ticket
docs/ldml/tr35-info.md
- moved "The determination of preferred units..." up a section, and fleshed it out to provide a full explanation (with sources) for unit identifiers and unit usage identifiers of their well-formedness and validity.
docs/ldml/tr35.md …
=> CLDR-15948 Clean up well-formedness and/or validity constraints

common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
Kawi, also known as Old Javanese, is undergoing a bit of a revival. It has been written in Javanese, Balinese, and the original Kawi writing system. In modern usage the revival seems to favor the Balinese script. This was recommended by the Jira Ticket [CLDR-17160](https://unicode-org.atlassian.net/browse/CLDR-17160) and will match SIL langtags entry.
```
{
"full": "kaw-Bali-MY",
"iana": [ "Kawi" ],
"iso639_3": "kaw",
"name": "Kawi",
"region": "MY",
"regionname": "Malaysia",
"script": "Bali",
"sldr": false,
"tag": "kaw",
"tags": [ "kaw-Bali", "kaw-MY" ],
"windows": "kaw-Bali"
},
```
CLDR-17160
[CLDR-17160]: https://unicode-org.atlassian.net/browse/CLDR-17160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17160 Update Kawi default Script

common/supplemental/supplementalData.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
There's a community of Mexicans that speak Venetian - but it is definitely not an offical language for the country, region, or city. This updates the data to remove this error.
CLDR-18092
=> CLDR-18092 Clarify Venetian language in Mexico

common/main/yue_Hant_MO.xml, common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, common/testData/localeIdentifiers/likelySubtags.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
This updates the Macau population language data with up-to-date census information.
CLDR-10478
In order to build the auto-generated files, use ` mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags`
=> CLDR-10478 Add latest data from Macau census

docs/ldml/tr35.md
CLDR-15948
We need better well-formedness clauses for identifiers, for references. This doesn't make material changes, since (with some work) someone can derived that the various identifiers have those restrictions. Also added links to some of the EBNF for locale ids, for reference, and reversed the aliasing for keyword, key, type to be the more understandable (and parallel to -t-) terms.
Removed the quotes around the identifiers in the large table, since that was confusing to readers, replacing with `code` style.
=> CLDR-15948 Add additional well-formedness clauses

docs/site/sitemap.tsv
CLDR-18017
Update site map to re-order the releases/downloads page and requesting changes page higher in the nav bar on the CLDR home page
=> CLDR-18017 Update site map ordering

docs/site/index/cldr-spec/picking-the-right-language-code.md
-Go directly to search in ethnologue.com, bypassing google.com
CLDR-18024
=> CLDR-18024 Clean up one link in picking-the-right-language-code.md

common/testData/messageFormat/README.md, common/testData/messageFormat/schemas/v0/tests.schema.json, common/testData/messageFormat/tests/bidi.json, common/testData/messageFormat/tests/fallback.json, common/testData/messageFormat/tests/functions/currency.json, common/testData/messageFormat/tests/functions/date.json, common/testData/messageFormat/tests/functions/datetime.json, common/testData/messageFormat/tests/functions/integer.json, common/testData/messageFormat/tests/functions/math.json, common/testData/messageFormat/tests/functions/number.json, common/testData/messageFormat/tests/functions/string.json, common/testData/messageFormat/tests/functions/time.json, common/testData/messageFormat/tests/syntax.json, common/testData/messageFormat/tests/u-options.json
Update the MessageFormat test data to reflect the latest state of tests in the MessageFormat WG repo. Currently, MFWG is finalizing the spec for 2.0 that it will submit soon to CLDR-TC for review, on the way to a special CLDR 46.1 point release planned for including the MF 2.0 spec at an off-cycle time point.
cc @catamorphism @mradbourne
CLDR-18122
=> CLDR-18122 Update MessageFormat test data

common/testData/localeIdentifiers/localeCanonicalization.txt
Since invalid locales were corrected in https://github.com/unicode-org/cldr/pull/4215 there are a few canonical mappings that were updated. This PR re-runs the generative scripts to fix the output file localeCanonicalization.txt . See the changes to the supplementalData from that PR that caused these macrolanguage changes: https://github.com/unicode-org/cldr/pull/4215/files#diff-0c0a1db9759811ee6479820227a65f23782f468967e94c162bd45d95aecd470a
Scripts ran:
```
mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateTestData
```
CLDR-18129
=> CLDR-18129 Rebuild localeCanonicalization.txt

tools/scripts/tr-archive/tr35.css
CLDR-18050
* Before
- <https://www.unicode.org/reports/tr35/dev/tr35-dates.html#Semantic_Time_Field_Sets>
* After
=> CLDR-18050 spec: use small caps for h5

docs/ldml/tr35-general.md
CLDR-18150
This is to fix a regression introduced by [CLDR-15948: Clarify the well-formedness and validity of certain Unicode CLDR identifiers for MF2](https://unicode-org.atlassian.net/browse/CLDR-15948).
=> CLDR-18150 Fix private-use units to avoid validity constraints

common/supplemental/supplementalData.xml, docs/site/development/updating-codes/update-language-script-info/language-script-description.md, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ConvertLanguageData.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestInheritance.java
This change adds "primary" scripts to many languages in language_script.tsv.
This won't change likely subtags, rather this just future-proofs our data by recognizing a singular primary script, avoiding issues where ambiguities served customers the wrong script.
I also added scripts for languages in country_language_population.tsv that were missing.
CLDR-18108
There are many more tasks, especially more complicated ones, in the parent ticket https://unicode-org.atlassian.net/browse/CLDR-18102
=> CLDR-18108 Give all languages a primary script: trivial cases

common/main/yue_Hans.xml
CLDR-18136
A typo originating in #4217 that I found after testing CLDR 46.1 BETA1 in ICU4X.
=> CLDR-18136 Fix datetimeSkeleton typo in yue

tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ConvertLanguageData.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CountItems.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ExtractMessages.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/FindPreferredHours.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateEnums.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateStatistics.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GetLanguageData.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/Misc.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LanguageTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLsrvCanonicalizer.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
-Switch almost all calls to use integer instead of string
-TODO comments for 3 exceptions where getting integer is challenging
-Fix off-by-one bug in CLDRFile.typeNameToCode
-New unit test for CLDRFile.typeNameToCode
-Move some calls to nameGetter() out of loops, re-use
CLDR-15830
=> CLDR-15830 Use getNameFromTypenumCode instead of getNameFromTypestrCode

common/main/yue_Hans.xml, docs/site/downloads/cldr-46.md
CLDR-18096
This PR cherry-picks to the maint/maint-46 branch all of the 46.1 changes on the main branch from those in PR [#4238](https://github.com/unicode-org/cldr/pull/4238) through commit https://github.com/unicode-org/cldr/commit/9263526c915789a4debe438b42e0644e1eef0f95 on Friday afternoon Dec 13. Those commits on main that are cherry-picked with this PR are:
| Commit | Commit merged | Ticket | Description |
| ------ | ------------- | ------ | ----------- |
| 899a7ade4889f41a22331e9c41bbc839f66dea61 | 2024-12-11 13:03 | CLDR-18170 | BRS v46.1 first pass at release note update.<br>With this we also pick up other release note updates, see note below|
| 57e30cab4bf32babde2b7a857048dc889b49f2a9 | 2024-12-12 08:56 | CLDR-18136 | Fix datetimeSkeleton typo in yue |
Note: With the release …
=> CLDR-18096 BRS 46.1 cherry-pick 46.1 changes from main to maint/maint-46, part 3

tools/cldr-code/src/main/java/org/unicode/cldr/util/NameType.java
=> CLDR-15830 Add explanatory comments in NameType.java

CONTRIBUTING.md, LICENSE, README.md, common/testData/_readme.txt, common/testData/personNameTest/_header.txt, docs/README.md, docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md, readme.html, tools/cldr-code/src/main/resources/org/unicode/cldr/package.html, tools/pom.xml
CLDR-18207
- Restore `docs/ldml/tr35-messageFormat.md` to have version 47
- Update `tools/pom.xml` to use ICU 77.0.1
- Update spec & readme dates
- Update at least some copyright dates for 2025:
- `README.md`, `CONTRIBUTING.md`, `LICENSE`, `readme.html`, `docs/README.md`
- Spec copyright. **The range was 2024-2024 so updated the end year to 2025, but shouldn't the start year be earlier?**
- Misc files: `common/testData/_readme.txt`, `common/testData/personNameTest/_header.txt`, `tools/cldr-code/src/main/resources/org/unicode/cldr/package.html`
- There is probably a standard header file that provides copyright and other info for java files, xml files, etc. but I did not find or update that (perhaps there is a BRS task to run a tool that updates these, did not run that).
- There are …
=> CLDR-18207 SBRS 47 Update misc additional versions and dates

.github/workflows/keyboard.yml, docs/ldml/tr35-keyboards.md, keyboards/abnf/transform-from-required.abnf, keyboards/abnf/transform-to-required.abnf, tools/scripts/keyboard-abnf-tests/check-keyboard-abnf.sh, tools/scripts/keyboard-abnf-tests/transform-from-required.d/from-match.fail.txt, tools/scripts/keyboard-abnf-tests/transform-from-required.d/from-match.pass.txt, tools/scripts/keyboard-abnf-tests/transform-to-required.d/to-replacement.fail.txt, tools/scripts/keyboard-abnf-tests/transform-to-required.d/to-replacement.pass.txt
=> CLDR-16836 kbd: add EBNF to spec for transforms

tools/cldr-apps/src/test/resources/org/unicode/cldr/web/data/TestSTFactory.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrXmlWriter.java
-Writing a CLDRFile to XML failed for extra paths such as this metazone path as shown by the new test in TestSTFactory.xml
-Using cldrFile.fullIterable.forEach instead of xmlSource.forEach in CldrXmlWriter fixes the bug
CLDR-17014
=> CLDR-17014 Illustrate/fix extra-path bug

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_subdivisions.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
=> CLDR-11874 Add conversion of subdivisions to json

tools/cldr-apps/js/src/esm/cldrDashData.mjs, tools/cldr-apps/js/src/esm/cldrText.mjs, tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/NotificationCategory.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
CLDR-18220
- Adds a new notification category 'other'. It's not included in the default choice sets.
- The query param includeOther=true adds this category.
- UI in the dashboard makes the Other category look like similar categories, except that
internally it reloads with the query param set/unset. (This reduces load in the normal case.)
The benefit here is especially in being able to download a spreadsheet of all values in a coverage
level.
[Dash_csw_default(2).xlsx](https://github.com/user-attachments/files/18414370/Dash_csw_default.2.xlsx)
=> CLDR-18220 Dashboard Other category for all other paths

tools/cldr-apps/js/src/views/DashboardWidget.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
CLDR-18220
address comments in #4273 
- Adds a new notification category 'other'. It's not included in the default choice sets.
- The query param includeOther=true adds this category.
- UI in the dashboard makes the Other category look like similar categories, except that
internally it reloads with the query param set/unset. (This reduces load in the normal case.)
The benefit here is especially in being able to download a spreadsheet of all values in a coverage
level.
=> CLDR-18220 Improve Dashboard Other category for all other paths

common/main/en.xml, common/main/root.xml
CLDR-18075
Also CLDR-18076, CLDR-18077, CLDR-18078. 
* Add a short name for territory `CC`, so that `Cocos (Keeling) Islands Time` (location format) becomes `Cocos Islands Time`, matching the non-location format
* Add a short name for territory `PN`, so that `Pitcairn Islands Time` (location format) becomes `Pitcairn Time`, matching the non-location format
* Add exemplar cities for some locations, so that the location format matches the non-location format
* `Pacific/Easter`, so that `Easter Time` -> `Easter Island Time` (`en.xml`)
* `Pacific/Wake`, so that `Wake Time` -> `Wake Island Time` (`en.xml`)
* `America/Noronha`, so that `Noronha Time` -> `Fernando de Noronha Time` (`root.xml`)
* Change some non-location names that use cities when the location names use regions, as they are the …
=> CLDR-18075 timezone names

docs/site/index/process.md
CLDR-18227
Add definitions for Tech Preview and Final Candidate as part of the Spec changes section of the CLDR Process page
=> CLDR-18227 Add definitions for Tech Preview and Final Candidate

common/main/syr.xml
CLDR-17760
In `syr`, delete the obsolete `<decimalFormats>` and ` <currencyFormats>` elements that do **_not_** have a `numberSystem` attribute at all (these probably date from when the `syr` data was first added in xml to the seed directory years ago). These do not show up in Survey Tool and (I think) are ignored by ICU code. The current version of these elements does have a `numberSystem` attribute, and `syr` does also have `<decimalFormats>` and ` <currencyFormats>` elements (and also `<percentFormats>`) **_with_** `numberSystem="latn"`; these are the ones that appear in Survey Tool and get used by the code.
=> CLDR-17760 syr, delete obsolete decimalFormats/currencyFormats without numberSystem

docs/site/index/survey-tool/survey-tool-accounts.md
-It was unclear where [you must list all of the locale(s) that you would like to provide data for, using the locale codes on...] should point; picking-the-right-language-code was the best I could find
CLDR-16530
=> CLDR-16530 Fix links in survey-tool-accounts.md

common/testData/localeIdentifiers/localeDisplayName.txt, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
-Use the extra-paths mechanism instead of code-fallback; new ExtraPaths.java
-For each type (language/script), create the set of extra paths only once
-Change es-419 to es (419) in localeDisplayName.txt so TestLocaleDisplay passes
-Revise testExtraPaths, testGetPaths, so they pass
-Comments
CLDR-17014
=> CLDR-17014 No code fallbacks for language/script paths

common/main/en_ES.xml, common/main/en_FR.xml, common/main/en_IT.xml, common/main/en_NO.xml, common/main/en_PL.xml, common/main/en_RO.xml, common/main/en_SK.xml, common/supplemental/supplementalData.xml
CLDR-18099
Adds the following European English locales inheriting from en_150
- en_ES
- en_FR
- en_IT
- en_NO
- en_PL
- en_RO
- en_SK
=> CLDR-18099 Add European English locales with data

common/main/en_CZ.xml, common/main/en_FR.xml, common/main/en_HU.xml, common/main/en_PT.xml, common/supplemental/supplementalData.xml
CLDR-18099
- en_CZ
- en_HU
- en_PT
and update en_FR for consistency with the approach for other en_150 child locales.
=> CLDR-18099 Add a few more European Englishes

common/main/dv.xml, common/main/gez.xml, common/main/sa.xml, common/main/tt.xml
CLDR-17760
Per discussion in ticket: For dv, gez, sa, tt (the remaining locales for which this is an issue): If there is a number format element without numberSystem and there is a corresponding element with numberSystem='latn', just delete the one without; otherwise add numberSystem='latn' to the one without.
This does not address root or additional tests, which will be under separate tickets to be filed.
=> CLDR-17760 4 locales, delete obsolete decimal/currencyFormats without numberSystem or add it

common/main/en.xml, common/main/en_AU.xml
CLDR-16821
This adds exemplar cities for some islands, and aligns the `en` metazone names with the correct names from `en-AU`.
=> CLDR-16821 Fix Australian time zone names

common/testData/transforms/chr-fonipa-t-chr.txt, common/transforms/chr-chr_FONIPA.xml
CLDR-18226
`ə̃ {ə̃}+ → ə̃;` is an invalid rule, `{` and `}` denote context, and the `+` quantifier cannot follow a context. The intention here was probably to group the decomposed character, but quantifiers apply back to the last space anyway.
=> CLDR-18226 Fix chr-chr_FONIPA transform rule

docs/ldml/tr35-dates.md
=> CLDR-18074 Add specific-non-location -> specific location fallback

common/main/en.xml, common/main/root.xml
CLDR-18255
Replaces PR [#4309](https://github.com/unicode-org/cldr/pull/4309). CLDRModify passes no-options and -fP (DAIP) before v47 alpha0. The only change was that the no-options pass reordered several timezone entries in root and en.
=> CLDR-18255 BRS v47a0 CLDRModify no options: reorder some timezone entries in root,en

docs/site/downloads/cldr-47.md
CLDR-17760
Add migration note (per ticket comment) about v48 deprecation of number symbols and format elements without numberSystem, and removal of these from root.
=> CLDR-17760 Add note about v48 deprecation of number symbols and format elements without numberSystem

common/main/as.xml, docs/ldml/tr35-numbers.md, docs/ldml/tr35.md
CLDR-17760
In addition to number format elements without a numberSystem attribute (PRs [#4292](https://github.com/unicode-org/cldr/pull/4292), [#4306](https://github.com/unicode-org/cldr/pull/4306)), we also need to clean up number symbols without a numberSystem attribute. And we need to update the spec for both so the examples do include a numberSystem attribute, and mention the such elements without a numberSystem attribute should not be used and will be deprecated.
=> CLDR-17760 Also fix number symbols without numberSystem; update spec accordingly

docs/site/development/updating-codes/update-currency-codes.md, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a3.xml
- update URLs
- drop wget instructions, just adds noise
- updated currency codes - no change other than ZWL now in historic.
CLDR-18265
=> CLDR-18265 BRS update currency codes

common/main/en_GS.xml
CLDR-18268
Add HH timeFormat to en_GS
=> CLDR-18268 Add HH timeFormat to en_GS

common/properties/coverageLevels.txt, common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLevel.java
These values were added to CLDR in between submission cycles and it would be unfair to drop locale coverage if the languages did not support them. I'm not happy with the styling of all of my code here -- I'm happy to respond to suggestions.
Thereby, we're temporarily overriding their coverage as "comprehensive". All other coverage level changes are for other reasons ~~(and Haitian Creole has a separate ticket to fix it)~~. You can see changes to charts in this PR https://github.com/unicode-org/cldr-staging/pull/168 Some changes to charts are from other PRs, but the ones keeping coverage level at a good level are there.
While I was here I also had put in the fix for the ticket on Haitian Creole (https://unicode-org.atlassian.net/browse/CLDR-18105) -- because tests are failing since it …
=> CLDR-18258 Exclude new values from coverage

docs/site/development/cldr-big-red-switch/brs-log-known-issues.md, docs/site/development/development-process.md, docs/site/sitemap.tsv
CLDR-18267
see #4322 for the current known issues PR
=> CLDR-18267 site: document how to handle known issues

tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateKaraList.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/NameType.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
-Remove getNameName, getNameTypeName, String[][] NameTable, INDEX_LANGUAGE, ..., nameTableIndex, fromNameTableIndex
-Associate the enum values with the corresponding path fragments by means of constructors
-Move FIX_KEY_NAME, fixKeyName from CLDRFile to NameType
-New method NameType.toCodeType converts NameType to CodeType and obviates conversion to/from String as intermediate step
-Comments
CLDR-15830
=> CLDR-15830 Refactor/simplify NameType

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
CLDR-18267
Three tickets were already closed but needed the logKnownIssues adjusted:
- CLDR-15663 to CLDR-17857
- CLDR-17756 to CLDR-17945
- CLDR-17544 to CLDR-17849
=> CLDR-18267 BRS v47: update logKnownIssues

tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java
-ConcurrentModificationException was thrown when ExtraPaths.getInstance called computeIfAbsent during cldr-generate-json.sh
-Unable to repro the exception before making this change; anyway, this should prevent it
CLDR-17014
=> CLDR-17014 Make ExtraPaths.getInstance synchronized

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java
=> CLDR-17014 Use singleton to avoid synchronized in ExtraPaths

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java
-This is only refactoring
CLDR-17014
=> CLDR-17014 Move more extra-path code from CLDRFile to ExtraPaths

docs/site/downloads/cldr-47.md
=> CLDR-18271 Update release page cldr-47.md

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-In resolveVotes, do not return INHERITANCE_MARKER if baileyValue is null
-Do not misinterpret the boolean baileySet as implying baileyValue is not null
-Always call getBaileyValue instead of reading baileyValue directly, to enforce the requirement that setBaileyValue must be called before getBaileyValue
-Make VoteResolver.getBaileyValue private; it was not called by other classes
-Comments; clarify that baileySet may be true even if baileyValue is false; it only indicates that setBaileyValue was called
CLDR-18240
=> CLDR-18240 Check for null baileyValue in VoteResolver

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
-Use ExtraPaths instead of XMLSource.ResolvingSource.constructedItems
-Paths constructed in this way no longer have fallback values
-Delete getPathsAllowingDuplicates and related code, now unused
CLDR-17014
=> CLDR-17014 Handle TERRITORY paths like LANGUAGE and SCRIPT

tools/cldr-apps/js/src/esm/cldrGenerateVxml.mjs, tools/cldr-apps/js/src/views/GenerateVxml.vue, tools/cldr-apps/js/src/views/MainMenu.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/AnnouncementData.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/GenerateVxml.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAlt.java, tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-Previously only Admin could use the Generate VXML option in the ☰ menu
-New Java function canGenerateVxml, new http response item userCanGenerateVxml to encapsulate this rule on the back end
-Rename Java function isTC to isTCOrStronger, for clarity, likewise for isVetter, etc.
-Remove some superfluous conditions like userIsAdmin in (userIsAdmin || userIsTCOrStronger)
-Do not exhaustively rename ...OrStronger; in particular front end and http response json still have userIsTC, etc.; renaming for front end and json will require caution and is beyond scope of this PR
-Refactor a few lines of js for consistency and to ensure boolean: Boolean(perm?.userIsLocked) instead of (perm && perm.userIsLocked)
-Comments
CLDR-17953
=> CLDR-17953 Enable TC to generate VXML

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- add _type:zone to all actual zones in the tree
- refactor: add a new hook function postprocessAfterAdd() to add this kind of fixup
CLDR-17176
Example run:
<details>
<summary>Example generation of fi/timeZoneNames.json</summary>
```json
{
"main": {
"fi": {
"identity": {
"language": "fi"
},
"dates": {
"timeZoneNames": {
"hourFormat": "+H.mm;-H.mm",
"gmtFormat": "UTC{0}",
"gmtZeroFormat": "UTC",
"regionFormat": "aikavyöhyke: {0}",
"regionFormat-type-daylight": "{0} (kesäaika)",
"regionFormat-type-standard": "{0} (normaaliaika)",
"fallbackFormat": "{1} ({0})",
"zone": {
"Pacific": {
"Honolulu": {
"_type": "zone",
"exemplarCity": "Honolulu"
},
"Easter": {
"_type": "zone",
"exemplarCity": "Pääsiäissaari"
},
"Fiji": {
"_type": "zone",
"exemplarCity": "Fidži"
},
"Truk": …
```
=> CLDR-17176 json: add _type to zone types

docs/site/downloads/cldr-47.md
=> CLDR-18271 More v47 release page work

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBCP47.java
CLDR-16022
Add a test that detects any new aliases for BCP47 keys, or for BCP47 types other than tz types (for tz types the alias contains the tzdata name so any new zones will require an alias); these should not be added. This test depends on having the cldr-archive available (since it compares BCP47 aliases in the current version to those in the previous version), and is skipped if the flag is set indicating that the archive is not available.
This also adds the unit test TestBCP47 to TestAll(); there are probably more unit tests that should be added to TestAll(), filed [CLDR-18301](https://unicode-org.atlassian.net/browse/CLDR-18301) about that.
[CLDR-18301]: https://unicode-org.atlassian.net/browse/CLDR-18301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> CLDR-16022 Add test to detect new aliases for BCP47 keys or non-tz values

docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, tools/scripts/tr-archive/fix-tocs.js, tools/scripts/tr-archive/package-lock.json, tools/scripts/tr-archive/package.json
- corrected indents, where there were multiple top level # - indented everything in by one
- ~corrected heading names with period in them which resulted in broken links~
- ~removed "Message Format 2.0" as redundant in two headings~
- ~demoted `.abnf` to a subheading~
- correct links to /spec/ into internal links
- also ran fix-tocs on tr35-info.md
(Review note: please review ignoring whitespace changes.)
CLDR-18295
=> CLDR-18295 spec: fixes to MFv2 46.1 spec 

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- subdivisions should be tiered for consistency (and if we subset it someday)
- transforms is NOT tiered
- calculate tier from output directory, where possible
- also cleanup PACKAGES.md
CLDR-18277
=> CLDR-18277 json: update PACKAGES.md

common/main/br.xml, common/main/bs.xml, common/main/eu.xml, common/main/gaa.xml, common/main/ha.xml, common/main/so.xml, common/main/sv.xml, common/main/yo.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
-Remove some paths with INHERITANCE_MARKER in XML for eight locales
-Restore code-fallback in XMLSource.java, maybe temporarily, for some paths
-Code comments reference this ticket for follow up in v48
CLDR-18294
=> CLDR-18294 Avoid null Bailey values for paths with INHERITANCE_MARKER

common/main/bew.xml, common/main/en_AU.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
-Combine the test with TestCheckCLDR to avoid another cycle through factory.getAvailable
-New method checkNullWithInheritanceMark
-Skip and log known issue for paths not in LANGUAGE/SCRIPT/TERRITORY/VARIANT
CLDR-18294
=> CLDR-18294 Add unit test for inheriting null, and fix two items in xml

LICENSE, README.md, docs/ldml/tr35.md
CLDR-18308
- Per recent discussion in ICU, LICENSE copyright end year should be 2025 after all. Reverts one of the changes in PR #4289
- Also update README status & date, and update spec date to date of last change.
=> CLDR-18308 Restore LICENSE copyright to 2025, update README/spec date/status

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBCP47.java
CLDR-9774
Start using the test to check for missing or extra English display names for relevant BCP47 keys and types. Most of this was already in unittest/TestBCP47.java, but the tests there were not being run until I added them to TestAll() in PR [#4358](https://github.com/unicode-org/cldr/pull/4358). Then for this PR I just had to switch to using normal error logging, and add some test skips (one marked with a logKnownIssue).
Tested this by temporarily adding some new entries in common/bcp47 files without translations in English and verifying that the test caught them.
=> CLDR-9774 Enable test for missing/extra English names for BCP47 keys/types

common/main/da.xml
=> CLDR-17925 da, update to use “ Hg

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
=> CLDR-18294 Fix known issue to reference future ticket

common/main/ku_SY.xml
(Intended for v48. Only to be merged after v47 is stable and cut from main)
Kurdish, specifically Northern Kurdish, is also spoken by many people in Syria. This adds a Syrian variant. Yes, it also uses the Latin orthography (the default for ku).
CLDR-18239
=> CLDR-18239 Add Kurdish variant

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
- add a known issue on CLDR-17790
- //ldml/identity resolves (inherits) when it shouldn't, per spec
- skip //ldml/identity paths that are inherited (!isHere())
CLDR-18312
FYI @btangmu I don't change CLDRFile here but relevant to inheritance stuff
=> CLDR-18312 json- workaround CLDRFile identity bug

common/supplemental/supplementalData.xml, docs/ldml/tr35-numbers.md, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-15693
Note that per TR35 [Supplemental Currency Data](https://www.unicode.org/reports/tr35/tr35-numbers.html#Supplemental_Currency_Data), "The [xml file] *ordering* of the elements in the [currency] list tells us which was the primary currency during any period in time."
- Update TR35 to note that currency elements with tender="false" should be last in list for currencyData/region (they are never primary at any point in time).
- Order SupplementalDataInfo.CurrencyDataInfo first by isLegalTender, then by _newest_ date range first (not _older_ date range). Note that while this ordering is closer to the file ordering, it will not be identical (since we need to sort these in a unique way), so SupplementalDataInfo has never preserved info about the primary currency during any time period …
=> CLDR-15693 Improve CurrencyDateInfo ordering, add test for XML file ordering, fix data

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
-Private boolean CLDRFile.DEFAULT_ITERATION_INCLUDES_EXTRAS determines whether to skip extras; either way they skip paths with null values
-Rename old iterator iteratorWithoutExtras
-Iterable and iterator are distinct, as in iterableWithoutExtras versus iteratorWithoutExtras
-Call iteratorWithoutExtras/iterableWithoutExtras directly where tests would otherwise fail with DEFAULT_ITERATION_INCLUDES_EXTRAS true
CLDR-18217
=> CLDR-18217 Add CLDRFile Iterable interface option to include extra paths by default

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckNumbers.java
CLDR-13310
- Add TestCheckNumbers to TestAll(); TestCheckNumbers was originally added in PR #490 for [CLDR-11045](https://unicode-org.atlassian.net/browse/CLDR-11045) "Add no-placeholder compact data back to CLDR"
- In TestCheckNumbers, add a test that `ar` and its children (except the default content locale) have explicit defaultNumberingSystem entries, since for the time being we are still supporting the possibility of having `ar` support either `latn` or `arab` as default (clients can choose)
[CLDR-11045]: https://unicode-org.atlassian.net/browse/CLDR-11045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-13310 test that ar and children have explicit defaultNumberingSystem entry

common/main/pms.xml, common/main/pms_IT.xml, common/supplemental/attributeValueValidity.xml, common/supplemental/supplementalData.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
CLDR-18193
Putting this up to merge into main -- but won't actually merge until the v47 cutoff, targetting v48. There are a lot of data updates on the main branch not in the v48 branch that I'd like to keep.
=> CLDR-18193 add Piemontese

docs/ldml/tr35-dates.md, docs/ldml/tr35.md
CLDR-18256
As discussed in the CLDR Design WG.
The spec I ended up implementing here is almost the same as proposed in [the doc](https://docs.google.com/document/d/1SkxoitlCFiQ_KGW3dmRk7lbumGd_N1rfYJLMlkiXvh4/edit?tab=t.0), but I touched up some other things while I was in here.
=> CLDR-18256 Add TimePrecision option to semantic skeletons

docs/ldml/tr35-keyboards.md, keyboards/abnf/transform-from-required.abnf
- Single escaped points in a range such as `<transform from="[\u{127}]"/>` were not supported, but they are present in the spec.
- For example, `[a-z]` or `[a-\u{127}]` or `[\u{61}-z]` are all supported, just not `[\u{61}]` (and by extension, `[a-z\u{127}]` is not supported by the current BNF).
- this PR fixes the EBNF / ABNF to allow a single escaped codepoint to be a member of the character classes.  
CLDR-18319
=> CLDR-18319 kbd: bnf: update bnf for transform ranges

docs/site/downloads/cldr-47.md
- formatting fixes
- known issues
- json
- keyboard
CLDR-18326
=> CLDR-18326 BRS v47: updates to 47 download page

tools/scripts/tr-archive/archive.js, tools/scripts/tr-archive/assets/css/tr35.css, tools/scripts/tr-archive/assets/js/tr35search.js, tools/scripts/tr-archive/header.html, tools/scripts/tr-archive/make-tr-archive.sh
- reorganize css / js files in case we have more later
- make html more readable
- add a search box that goes to a google search
CLDR-18115
By design, the search box is NOT present unless the spec is on a unicode.org site.
So, it can be reviewed [here](https://www.unicode.org/~srloomis/tr35-test/tr35.html) :
=> CLDR-18115 popup box for spec search

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAnnotations.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
CLDR-15388
Add a consoleCheck test (so vetters will see it) in CheckAnnotations that:
- Annotation entries do not have empty values (`<annotation cp=".."></annotation>` or `<annotation cp=".."/>`).
- If there is a keyword entry for a given emoji/symbol, there should also be a tts (name) entry.
This found many missing tts errors, about which I have filed [CLDR-18329](https://unicode-org.atlassian.net/browse/CLDR-18329). In the meantime, I added a skip for these known error cases so that CI tests will pass (I did not use logKnownIssue, as far as I know we cannot do that in consoleCheck tests, not sure what would happen in Survey Tool)
[CLDR-18329]: https://unicode-org.atlassian.net/browse/CLDR-18329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> CLDR-15388 check annotations for empty values or keyword entry without name (tts) entry

docs/ldml/tr35-messageFormat.md
CLDR-18323
This PR contains the pourover of MessageFormat 2.0 for the LDML47 release. Note that there are a few pending changes. This is for consideration by CLDR-TC.
=> CLDR-18323 v47: Pourover of MessageFormat 2.0

docs/ldml/tr35-keyboards.md, keyboards/3.0/mt-t-k0-47key.xml, keyboards/3.0/mt.xml, keyboards/dtd/ldmlKeyboard3.dtd, keyboards/dtd/ldmlKeyboard3.xsd
- and example files
CLDR-17971
=> CLDR-17971 kbd: (dtd/spec) add <info attribution=…> attribute

tools/cldr-apps/js/src/esm/cldrInfo.mjs
-For constructed value, message should be noFollowAlias = This item is constructed from other values
-The wrong message was item_description_alias_same_locale = This item is inherited from another field in this locale
-In cldrInfo.mjs, addSelectedItem calls getItemDescription and getLinkUrlAndText
-In getItemDescription, if no inheritance path, show the message for constructed value
-In getLinkUrlAndText, if no inheritance path, there is no link URL, AND no link text; link text is ignored if there is no link URL
CLDR-11950
=> CLDR-11950 Fix Info Panel wrong-message bug in front end

common/supplemental/dayPeriods.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
One small change from the ticket to minimize changes: keeping the boundary between evening and night at 9:00pm
CLDR-17484
=> CLDR-17484 Update dayPeriods.xml

docs/ldml/tr35-general.md
CLDR-18176
Adds a restriction, because there cannot be a normalized form that fits in 8 characters.
`[ wfc: The string length of the unit constant must be less than 9 characters. ]`
=> CLDR-18176 Changes in unit constants

tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_subdivisions.txt
- the configuration wasn't updated after an internal path change, so the files were in the wrong place
CLDR-11874
=> CLDR-11874 json: output subdivisions to the correct spot

tools/cldr-code/pom.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CopyLicense.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/LICENSE, tools/cldr-code/src/test/java/org/unicode/cldr/tool/TestCopyLicense.java
- copy LICENSE file into a secondary spot
- new tool CopyLicense that performs the copy (should it be needed) so that this can be tied into automation
- test to assert the files are the same
This is to work around the bug https://github.com/eclipse-m2e/m2e-core/issues/1912
CLDR-18205
Note: I'm inclined to not bother cloning the ticket… if some year we find out it's fixed we can back out the change. The eclipse bug  <https://github.com/eclipse-m2e/m2e-core/issues/1912> is already linked in the code and the commit.
=> CLDR-18205 workaround eclipse issue

docs/ldml/tr35-messageFormat.md, docs/ldml/tr35.md, docs/site/downloads/cldr-47.md
CLDR-18340
Adds changes in v47 for MessageFormat to the spec and to the downloads page. Other changes in this PR appear to have come from syncing my fork to main?
=> CLDR-18340 MessageFormat v47 change list

common/supplemental/supplementalData.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ConvertLanguageData.java
ConvertLanguageData rebuilds part of the supplementalData.xml. Since the new <scriptData /> is in the middle of 2 generated sections we need to re-write the generator so it does not accidentally drop it when running the script. Long term this is only more reason to break up the supplementalData.xml - but let's plan that out first.
Can be landed in v48 or v47, no changes will affect ICU.
Code to run generator:
```
mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData
```
CLDR-18349
=> CLDR-18349 Keep scriptData when generating ConvertLanguageData

tools/cldr-apps/js/src/esm/cldrForum.mjs
-Define constant SPECIAL_FORUM instead of repeating string literal forum
-Call setCurrentSpecial(SPECIAL_FORUM) before calling replaceHash
CLDR-17694
=> CLDR-17694 Fix error when trying to navigate back from forum

docs/ldml/tr35-messageFormat.md, tools/scripts/tr-archive/archive.js, tools/scripts/tr-archive/package-lock.json, tools/scripts/tr-archive/package.json
- AnchorJS and GFM have different ideas about the fragment id
- find and detect those, and set for example `<h2 id="foobar">foo.bar</h2>` only where it would make a difference (to minimize impact)
this is a workaround for https://github.com/bryanbraun/anchorjs/issues/197
Also:
- Don't anchorify H1 (#) which is just the top anchor
- fix link target in tr35-messageFormat.md which would now be incorrect.
CLDR-18295
FYI @aphillips 
=> CLDR-18295 spec: fix anchors

docs/ldml/tr35.md
CLDR-16524
I don't think this line needs a version number, the user can click on Modifications and see the entire history (starting with changes since the prev version).
Also, the current version is still in the "this version" URL if needed.
=> CLDR-16524 spec v47: change the Revision line to just link to Modifications

.github/dependabot.yml, .github/workflows/update-jira.yml, tools/scripts/jira-updater/update-jira.mjs
- avoid fork perms issue by running once merged (such as to main)
- update dependabot
CLDR-15400
=> CLDR-15400 workflow: jira-updater for forks

README.md, docs/charts/keyboards/pom.xml, docs/ldml/tr35-collation.md, docs/ldml/tr35-dates.md, docs/ldml/tr35-general.md, docs/ldml/tr35-info.md, docs/ldml/tr35-keyboards.md, docs/ldml/tr35-messageFormat.md, docs/ldml/tr35-numbers.md, docs/ldml/tr35-personNames.md, docs/ldml/tr35.md, pom.xml, tools/cldr-apps/pom.xml, tools/cldr-code/pom.xml, tools/cldr-rdf/pom.xml, tools/pom.xml
CLDR-18395
- Update date and status in README.md
- Remove "-SNAPSHOT" from CLDR versions in pom.xml.
- Update spec from draft to final, update date in tr35.md
Similar to what was done for v46 in PRs [#4144](https://github.com/unicode-org/cldr/pull/4144) and [#4150](https://github.com/unicode-org/cldr/pull/4150)
=> CLDR-18395 BRSv47: final updates: README date/status, remove pom -SNAPSHOT, spec date/status

docs/ldml/tr35.md
CLDR-18401
Among other things, the previous PR for this ticket - [#4481](https://github.com/unicode-org/cldr/pull/4481) - deleted most of the body of the Modifications section of tr35, consisting of entries relevant for CLDR 46.1 and 47. However, it did not delete the TOC entries for those items in the body of the Modification section; this PR completes the job by deleting the corresponding TOC entries.
=> CLDR-18401 SBRSv48: Delete spec TOC entries for Modifications section

.github/workflows/gh-pages.yml, .github/workflows/site.yml
- if you open a site PR from a fork for the site, give a warning instead of failing.
- if you merge to a branch that can't deploy to gh-pages, skip deploy instead of fail
CLDR-18351
=> CLDR-18351 fail better: for site and spec deploy

docs/site/index/downloads.md
=> CLDR-18400 Make downloads table easier to edit

docs/site/downloads/cldr-46.md, docs/site/downloads/cldr-47.md, docs/site/index/downloads.md
=> CLDR-18415 Add as time formatting known issue and clean up links

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartUnitConversions.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/FormattedFileWriter.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateKeyboardCharts.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculateLocaleCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java
(cherry picked from commit 2ef784e3a4168bc2a43cd1b5b9839b6636f5899c)
CLDR-18396
Merge remaining relevant fixes from maint/maint-47 back to main; just one more:
- 2ef784e3a4168bc2a43cd1b5b9839b6636f5899c, CLDR-18406 v47 Chart Improvements (#4487), Steven R. Loomis, Wed Mar 12 09:51:30 2025 -0500
**_Note: This should be merged with "Rebase and merge" (temporarily enable in Settings if necessary), not "Squash and merge"_**
=> CLDR-18396 SBRS48 merge relevant maint-47 fixes to main, part2

common/supplemental/likelySubtags.xml, common/supplemental/supplementalData.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv
The Classical Chinese [lzh] language is the standardized form of Chinese that arose around the start of the Common Era (potentially as early as 5th Century BCE). It is marked as ending in common usage by the May Fourth Movement in 1919 -- it was replaced with vernacular Chinese [zh & it's constituents].
The majority of its duration coincides with Traditional Han writing [Hant]. While many writings were in the earlier scripts, the vast majority of corpora are in Traditional script.  The printed form in which "Traditional Han writing [Hant]" now most often occurs arose in the Song dynasty starting in the 10th century CE.
The ending of common usage of Classical Chinese was 37 years before the advent of Simplified Chinese (1956). Since, for historic languages, we match their writing system to …
=> CLDR-16715 Match Classical Chinese with Traditional Han writing

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
-Add iso8601 to the %N list in PathHeader.txt
CLDR-18443
=> CLDR-18443 ISO 8601 paths not showing in Survey Tool

common/dtd/ldmlSupplemental.dtd, common/supplemental/attributeValueValidity.xml, common/supplemental/supplementalData.xml, docs/site/downloads/cldr-48.md, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ConvertLanguageData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
supplementalData.xml lists the top territories for languages under the `<languageData>` area -- however it's not clear and it's best for people to consume the data from `<territoryInfo>` directly.
This quickly removes the territory information -- but there is additional cleanup to do. I just wanted to get this simple change out there to see how many breaks.
CLDR-5708
Scripts ran
```
mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateTestData
```
=> CLDR-5708 Remove misleading territories attribute from supplementalData

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
-In Ldml2JsonConverter call iteratorWithoutExtras instead of the default iterator
-In ShowData (for GenerateAllCharts) call iterableWithoutExtras instead of the default iterable
CLDR-18325
=> CLDR-18325 Make CLDRFile.DEFAULT_ITERATION_INCLUDES_EXTRAS true

common/main/en.xml, common/main/root.xml
=> CLDR-18249 Add missing exemplar cities

common/dtd/ldml.dtd, common/main/en.xml, common/main/root.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/RegexLookup.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Placeholders.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
CLDR-17570
Add new structure for rationals; put them with the rest of the number formats (decimal, scientific, etc.).
This involved various other changes:
- root and en and dtd
- Placeholder additions
- DAIP additions
- ExampleGenerator additions
- Note that often new structure needs Checks, but this uses DAIP for two cases that would otherwise be errors.
=> CLDR-17570 Rational formatting

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- these were causing odd compilation errors on one environment
CLDR-17686
=> CLDR-17686 change enum.valueOf to enum.forString in a couple of places

tools/cldr-apps/pom.xml
- ref  2cbc7bcbb3db092b5b93d458444fc9ab7742d0a5 (#4506)
- seems org.json was already present
CLDR-18356
Well, I guess I added org.json to maven a long time ago- just didn't delete the source from the tree.
=> CLDR-18356 deps: remove duplicate org.json

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/SearchAPI.java
- the search API was behind a check for a valid logged in user. this is probably not necessary.
- remove the check for now.
Note. this doesn't make any improvements, just unbreaks the search panel.
Another note: a _session_ is still required.  So you can't just hit a certain URL and cause a search to happen, it has to be a browser user (or someone sophisticated enough to use the REST API)
CLDR-18423
=> CLDR-18423 st: search box shouldn't fail if not logged in

tools/cldr-code/src/main/java/org/unicode/cldr/tool/Main.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRConfig.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
- .. if the current dir seems to be a CLDR dir
- we already do this for the .jar, but do this everywhere (such as from mvn:exec)
CLDR-18402
=> CLDR-18402 CLDRConfig to always set CLDR_DIR=. with a warning

common/main/en.xml, common/main/root.xml, common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNumbers.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/fixedcandidates/DefaultFixedCandidates.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
=> CLDR-17570 Exclude rational formats from some checks

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
-New enum CandidateStatus, replace String pClass on back end
-Rename getPClass to getCandidateStatus
-Still named pClass in the http response json and the front end
-Remove function getInheritedLocale, which was only called privately and had only one calling function
-Comments; removed some comments on the back end that assumed too much about the front end and might no longer be accurate
CLDR-18376
=> CLDR-18376 Inheritance data: preliminary refactoring on server side

bin/.gitignore, common/main/en.xml, common/main/root.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-17570
Fixed a warning on \u200b. But then noticed that some other things needed fixing.
- Need to use WJ (2060) instead, to avoid linebreaks within 3½.
- Needed to _not_ warn on either WJ or ZWSP.
=> CLDR-17570 Fix a warning on rationals

common/main/en.xml, common/main/kek.xml, common/main/kek_GT.xml, common/supplemental/attributeValueValidity.xml, common/supplemental/supplementalMetadata.xml, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
Adds a new locale, per CLDR-18381
There are some outstanding questions on orthography.
Also I'll update language's population in a separate diff updating the data from the full Guatemalan census: https://github.com/unicode-org/cldr/pull/4474
CLDR-18381
=> CLDR-18381 Add kek_GT locale

common/dtd/ldml.dtd, common/main/en.xml, common/main/hi.xml, common/main/or.xml, common/main/root.xml, common/main/ta.xml, common/supplemental/coverageLevels.xml, docs/ldml/tr35-dates.md, docs/ldml/tr35.md, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDateTimeTestData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/prettyPath.txt, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverage.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-18350
Add a new type 'relative' for the dateTimeFormat format for combining dates and times (in addition to the existing types `standard` and `atTime`). If this exists, it is used for combining a relative date with a single time; if absent, we fall back to the `standard` format for this combination. (We do this instead of falling back to the `atTime` format in order to produce behavior that is better for locales that do not get much attention; it does mean that vetters for locales that do get attention may need to copy any existing atTime pattern to the relative pattern if they want to preserve current behavior for relative date + single time, and this info will be added to the vetter guidelines).
- add the new type in ldml.dtd.
- add `dateTimeFormat type="relative"` entries in …
=> CLDR-18350 Add dateTimeFormat type=relative, update spec, coverage, ExampleGenerator, tests

common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCoverageLevel2.java
CLDR-17857
- add `bal` to modern
- update test which had missed bal before
- also, test that all Basic lang's scripts are in modern
- add CLDRLocale.toMaximal
- add check for variants - with a known issue CLDR-18480
=> CLDR-17857 coverage for scripts, update 'bal' coverage

common/main/en.xml, common/main/kek.xml, common/main/lzz.xml, common/main/pms.xml, common/main/root.xml
CLDR-18485
CLDRModify passes:
- no options
- `root`, `en`: reorder entries for rationalFormats, new units
- `lzz`: fix indentation
- open -fP:
- `root`, `en`, `kek``, `lzz``, `pms`: fix spacing and ordering within exemplar sets. In `root` this also adds U+2011 no-break hyphen to the `numbers` exemplar set.
=> CLDR-18485 BRS48 CLDRModify passes before m1 integration

tools/cldr-apps/js/src/esm/cldrAddAlt.mjs, tools/cldr-apps/js/src/esm/cldrAddValue.mjs, tools/cldr-apps/js/src/esm/cldrComponents.mjs, tools/cldr-apps/js/src/esm/cldrEvent.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrVue.mjs, tools/cldr-apps/js/src/views/AddValue.vue, tools/cldr-apps/js/test/TestCldrSurvey.mjs, tools/cldr-apps/src/main/webapp/surveytool.css
- rename cldrAddAlt.addButton and cldrAddValue.addButton to reduce my own confusion
- export cldrSurvey.locInfo
- import <a-config-provider> from ant
- add a <AddValue dir="rtl"/> prop to AddValue to support passing through the directionality
- update AddValue to use the configProvider to set directionality
- fix a typo in TestCldrSurvey
- update cldrVue.mount to pass through extra props to mounted components
- also fix RTL on examples
CLDR-18475
Fixed input page:
Fixed example page:
=> CLDR-18475 st: fix RTL input in input box and examples

common/properties/coverageLevels.txt, common/supplemental/coverageLevels.xml
Updated the coverage levels for items that were previously added to basic, causing coverage levels to significantly drop. GMT Unknown Format is now moderate (causing most locales to be moderate, not modern), and the ISO 8601 formats that used to be basic are now comprehensive. There may be other ISO 8601 coverages to alter as well.
```
mvn package -DskipTests=true && java -jar tools/cldr-code/target/cldr-code.jar GenerateAllCharts
```
CLDR-18473
=> CLDR-18473 Change coverage levels for some date/time formats

common/bcp47/timezone.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBCP47.java
CLDR-16439
PR [#4535](https://github.com/unicode-org/cldr/pull/4535) added the secondary zone alias South_Pole for McMurdo, but did not remove it from its previous entry for Auckland. That caused a serious problem in the timezoneTypes array generated for ICU which tries to map legacy zone IDs to modern one; it was trying to map South_Pole to 2 different IDs, so the resource could not be read and all mapping of BCP47 keys and types was broken. So this PR removes the old alias. I will also file a ticket for a unit test to check this sort of thing.
=> CLDR-16439 zone alias South_Pole was moved to McMurdo, so remove it from Auckland

common/supplemental/coverageLevels.xml
-Remove the line for ...Gulf...short/standard from coverageLevels.xml
-Do not remove the similar line for ...Gulf...long/standard
-This may affect all locales associated with territory AE, such as ar and en, since ar_AE and en_AE exist
CLDR-11763
=> CLDR-11763 Do not require Gulf time short/standard at moderate coverage

common/supplemental/supplementalMetadata.xml, common/testData/localeIdentifiers/localeCanonicalization.txt, common/validity/language.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
The Mandingo `man` macrolanguage has 7 members. Right now, in languageAlias, we show 2 default members that represent the whole of Mandingo. In reality, there should be only 1 default for each macrolanguage, so this updates the values to just 1.
Eastern Maninkakan `emk` has ~3.5million speakers but Mandinka `mnk` only has 1 million, so Eastern Maninkakan takes precedence.
CLDR-18437
=> CLDR-18437 Remove duplicate language alias

common/supplemental/likelySubtags.xml, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelySubtags.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Iso639Data.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
I noticed there are language families in the likely subtags data when we import data from Script-Metadata and SIL. It's caused because of script imports -- which we like but in this case the families are too general. The 2 items removed are for the families `pra` Prakrit and `zhx` Chinese -- they are written in a lot of scripts and a lot of regions. It's not well-defined to say which script or region is the likely one, so I am removing the language families from the generated file.
SIL inherited this error from CLDR and is passing it back to CLDR, so this also helps prevent that erroneous feedback loop.
Note that I did this in 2 commits. The first commit deletes dead code and fixes the spelling of Hierarchy, it also updates a language name that wasn't previously updated by running the …
=> CLDR-18233 Remove language families from likely subtags

common/main/en.xml, common/main/root.xml, common/supplemental/supplementalData.xml
CLDR-18464
CC @roozbehp @pedberg-icu @AEApple
=> CLDR-18464 Add a Before Hijrah era to the Islamic calendars

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java
-Add to existing checks in CheckDates
-New methods checkTimeFormatMatchesRegion, getRegionHourFormat
-Failure causes warning, not error
CLDR-18375
=> CLDR-18375 Check time format matches region

docs/site/development/updating-codes/update-currency-codes.md, tools/cldr-code/src/main/java/org/unicode/cldr/util/DateConstants.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/IsoCurrencyParser.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a3.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-18492
- update ISO 4217
- improve site (slightly)
- fix currency test so that recently-withdrawn currencies process OK.  This makes CLDR-17397 not be an issue. ISO moves currencies directly to historical even if they are still tender.
=> CLDR-18492 BRS: update currency

tools/cldr-apps/js/src/views/MainHeader.vue
CLDR-18500
The coverage menu wasn't obscured, it was purposely hidden. Show it even if the CLA isn't signed.
=> CLDR-18500 still show the coverage menu even if the CLA isn't signed.

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
CLDR-18464
Addition of the new islamic era caused an IndexOutOfBoundsException in ExampleGenerator.handleEras, since it uses a hard-coded map to a list of sample dates for each era and it did not have an entry for the new islamic era. Fixed by adding the entry.
=> CLDR-18464 Fix IndexOutOfBoundsException in ExampleGenerator.handleEras

common/main/blo.xml, common/main/bqi.xml, common/main/bua.xml, common/main/bua_RU.xml, common/main/ku_Arab.xml, common/main/sgs.xml
CLDR-18548
I decided to go ahead and do the CLDRModify passes since they cleaned up some recent DDL locale updates:
- the no-options pass fixed formatting (spaces->tabs, comments) for `bqi bua_RU bua ku_Arab`
- the -fP pass reordered/reformatted exemplar sets for `blo bqi bua sgs`
=> CLDR-18548 BRS 48 CLDRModify passes 2025-04-23

tools/cldr-code/src/main/java/org/unicode/cldr/icu/LDMLConstants.java, tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalCalendarData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestSupplementalDataInfo.java
- minimal, modern parser
- minimal test case
- update example generator
CLDR-17851 
- Fixes original root cause of #4629 
=> CLDR-17851 SupplementalCalendarData parser, update ExampleGenerator

common/supplemental/coverageLevels.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/Joiners.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Splitters.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-18574
This narrows the coverage of iso8601 to only date patterns. For available and interval formats, that is tested by making sure that the `id` value matches a regular expression that contains 2 "date" pattern characters. That uses the line:
```
<coverageVariable key="%iso8601IDs" value='([^\\x{22}]*(Gy|y[MQw]|M[EdW]|Ed)[^\\x{22}]*)'/>
```
The regex has the optional non " characters before and after, and sees if there are certain pairs, like Gy or Md. That is, it excludes singleton date characters like value='d', because ordering does not matter for them.
Adds a test, and a couple of GP utility classes.
=> CLDR-18574 Fix coverage for iso8601

tools/cldr-apps/js/src/esm/cldrEscaper.mjs, tools/cldr-apps/js/src/esm/cldrEscaperLoader.mjs, tools/cldr-apps/js/src/esm/cldrGui.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/test/nonbrowser/test-cldrEscaper.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/CharInfo.java, tools/cldr-apps/src/main/webapp/css/redesign.css, tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCodePointEscaper.java
- move <> into CSS before/after for visible-mark
- rewire startup sequence a little- could pre-load some things in parallel
- new mechanism cldrEscaper
CLDR-16765
For now, only _named_ invisibles (except SPACE U+0020!) are shown. But this mechanism could show all invisibles, substituting U+ numbers or something.
=> CLDR-16765 Show un printables

docs/site/translation.md
CLDR-18574
There is a related PR for the code change: https://github.com/unicode-org/cldr/pull/4670
Main change is for ISO 8601 (Fixing the name, clarifying the instructions)
There are a few other fixes
- Drop a ticket number
- Broke apart the paragraph starting "However, in some languages the use of a relative date..."
- Added to "Exemplar cities added or changed in English." the following:
- This was typically to move towards the official spelling in the country in question, such as retaining accents. You should check these, but don't hesitate to retain the older version([star]) if it is a different script or more customary in your language. For example, English still uses "Mexico City" instead of "Ciudad de México".
- Fixed the 2nd instance of `alphaNextToNumber`: it should have been …
=> CLDR-18574 Hub update for ISO8601

tools/cldr-apps/js/src/esm/cldrEscaper.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/CharInfo.java
- use new 'use right regex' function #4673
- remove a debug printout
- pass inherited text through the escaper, as well as translated
CLDR-16765
depends on #4673
=> CLDR-16765 use-right-regex in front end

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
CLDR-18574
There is a related PR for the Info Hub change: https://github.com/unicode-org/cldr/pull/4672
Shouldn't say "8601" or "ISO"
=> CLDR-18574 Fix name YMD calendar section name

common/main/en.xml, common/main/root.xml
CLDR-18603
Add `GyM`, `GyMEd` availableFormats for gregorian, generic, and some other calendars to `root`, `en` (there are already intervalFormats for these), based on the existing availableFormats in the same calendars for `GyMd`, `yM`, and `yMEd`. As far as I can tell these new availableFormats will already be included in appropriate coverage levels.
Leaving the ticket open in case we find other such omissions to add.
=> CLDR-18603 Add GyM, GyMEd availableFormats to root, en

tools/cldr-apps/js/src/esm/cldrDashData.mjs
Not sure where this regressed, but this fixes three issues:
1. XLSX download file name was always for example Dash_es_default.xlsx (default instead of es.moderate)
2. XLSX tab name was also es.default instead of es.moderate, ex
3. URL broken internally, https://st.unicode.org/cldr-apps/v#/undefined/T_NAmerica/77b7368701e0333e instead of /es/…  (undefined instead of locale)
CLDR-18475
this was under CLDR-18475 because I originally thought it was a JSON issue, but it's not.
=> CLDR-18475 dashboard fix: file/tab names were wrong

common/supplemental/supplementalData.xml
=> CLDR-11375 Fix Meiji start date

common/main/en_EE.xml, common/main/en_GE.xml, common/main/en_LT.xml, common/main/en_UA.xml, common/supplemental/supplementalData.xml
CLDR-18572
- Add en_EE, en_GE and en_UA
- Remove unnecessary time formats from en_LT and en_LT
=> CLDR-18572 Add en_EE, en_GE and en_UA

tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculatedCoverageLevels.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
- error if an English translation is missing for a locale which has reached basic in the previous released version
CLDR-17857
Note: no items are failing now, but I was able to get a simulated failure by locally modifying v47 data:
```
TestMissingInfoForLanguage {
Error: (LikelySubtagsTest.java:362) Missing English translation for: suz which was at basic in 47.0.0.0
} (0.236s) FAILED (1 failure(s))
```
=> CLDR-17857 automatically check English against last release version

tools/cldr-apps/js/src/esm/cldrEscaper.mjs, tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/test/nonbrowser/test-cldrEscaper.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java, tools/cldr-apps/src/main/webapp/css/redesign.css, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
1. escape multiple chars, not just first
2. move prefix/suffix out of CSS and into plain text
3. don't escape items on the FE that DAIP already escaped on the BE
CLDR-16765
showing selected as plain text
I'm a little surprised that we didn't have double escaping before for Arabic exemplars. In any event, this is suppressed now - however, I actually think the new escaping display is superior to the server-generated HTML.  Ideally we should have a _widget_ for working with exemplars on the server side. Anyway.
=> CLDR-16765 unescape improvements

common/main/en.xml, common/main/root.xml
CLDR-18538
In root/en, change H  patterns without m[s] to add literal 'h' for disambiguation (affects availableFormats for H, and intervalFormats for H and Hv). No _**new**_ items, just changed ones.
This does not complete the ticket because there will be another PR to add a check that produces a warning or error for such standalone H patterns that do not have some form of disambiguation, but that can be pre-vet.
=> CLDR-18538 root,en: change H patterns without m[s] to add literal 'h'

common/main/en.xml, common/main/root.xml, common/supplemental/coverageLevels.xml
CLDR-18539
- Add availableFormats for hv,Hv where we have intervalFormats for those skeletons in the same calendar (formats can come from the intervalFormat)
- Add availableFormats for
- EBh where we have an availableFormat for EBhm in the same calendar
- Eh where we have an availableFormat for Ehm in the same calendar
- EH where we have an availableFormat for EHm in the same calendar
- The formats can come from the corresponding existing format, just dropping the ":mm", except that...
- When adding formats for H without m (or s) as for the skeletons Hv and EH, suffix the "HH" in the pattern with literal 'h' for disambiguation as was done for my earlier PR today for already-existing formats, PR [#4708](https://github.com/unicode-org/cldr/pull/4708) for …
=> CLDR-18539 root,en: Add availFmts Hv,hv to match intervalFmts; add availFmts EBh,Eh,EH to match ones with m

docs/site/index/survey-tool/admin.md, docs/site/sitemap.tsv, tools/cldr-apps/src/main/java/org/unicode/cldr/web/ClaSignature.java, tools/cldr-apps/src/main/resources/org/unicode/cldr/web/sql/cldr-org-cla-update.sql
CLDR-18536
- also adds a `survey-tool/admin.md` page
- `ADD_CLA_ORGS` can be used to add a new CLA Org without a code change.
=> CLDR-18536 Stored Procedure for CLA Org update

docs/ldml/tr35-collation.md
CLDR-18283
This file is like running blankweights.sed over FractionalUCA.txt.
FractionalUCA.txt contains all of the data for building the CLDR root collation data. Diffing it across Unicode versions is nearly unusable, because inserting any character into the sort order changes the primary weights of every following character. And the fractional byte sequence weights are subject to manual and automatic tweaks in their computation.
Therefore, for many years I have used the [blankweights.sed script](https://github.com/unicode-org/cldr/blob/main/tools/scripts/uca/blankweights.sed) to generate a modified file with “blanked weights” that preserves the sort order and the number of non-zero weights. I find diffing this file across versions valuable. See the [UCA tools …
=> CLDR-18283 add Unicode 16 FractionalUCA_blanked.txt

docs/site/translation.md, docs/site/translation/displaynames/locale-option-names-key.md, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathDescriptions.md
CLDR-16665
This is adding information about the different locale key-type values, to help people translate them. 
This draws upon the data in https://github.com/unicode-org/cldr/tree/main/common/bcp47, mostly the descriptions. After viewing in context, I think we need to make various clarifications and fixes (like not starting the description with "CSS lev 3 ..."). 
I'd like to do those in a later PR, however.
=> CLDR-16665 Add documentation of 'core' type values

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/AnnotationUtil.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestAnnotationUtil.java
- also, fix an issue where the PathDescription markdown ran into the emoji sample image
- add U+xxxx hex escape as title on the emoji image
- refactor and test AnnotationUtil
CLDR-18664
=> CLDR-18664 ui: fix emoji 404

common/main/ar.xml
-Remove the short standard metazone value GST from ar.xml
CLDR-11763
=> CLDR-11763 Remove value GST from ar.xml

.github/workflows/site.yml, docs/site/index.md
- also, update about page to link to CLDR-JSON
CLDR-18512
=> CLDR-18512 site: fix site deploy

common/supplemental/dayPeriods.xml
[CLDR-17626](https://unicode-org.atlassian.net/browse/CLDR-17626)
[CLDR-17626]: https://unicode-org.atlassian.net/browse/CLDR-17626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-17626 Fix day periods for Sicilian (scn), and provide initial data.

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFileOverride.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
-Do not throw exception from XMLSourceMapOverride if locale is en = COMPARISON_LOCALE
-Enlarge testLightSpeed to include locale am (Amharic) and path that threw the exception
-Make delegate and overrides final per compiler suggestion
CLDR-18647
=> CLDR-18647 IllegalArgumentException in ExampleGenerator

.github/workflows/maven.yml, tools/cldr-apps-webdriver/src/test/java/org/unicode/cldr/surveydriver/SurveyDriverDashboard.java, tools/cldr-apps-webdriver/surveydriver-docker.properties, tools/cldr-apps/js/src/esm/cldrGui.mjs, tools/cldr-apps/js/src/esm/cldrLocales.mjs, tools/cldr-apps/js/src/esm/cldrMenu.mjs, tools/cldr-apps/js/src/esm/cldrStatus.mjs
CLDR-18573
- revert d078d935845292bb8df57d41116f24e5ecdd984f and #4742
- untangle loading sequence for locales, menus. improve robustness for starting
- also relates to CLDR-14409 and to the workaroudn for CLDR-18613 - increase webdriver timeout, and add a refresh  to work around CLDR-18613 to enable webdriver test to continue.  
- remove workaround retry from workflow
=> CLDR-18573 locmap-load-fix

common/annotations/ja.xml, common/annotations/mn.xml, common/annotations/yue.xml, common/annotations/yue_Hans.xml, common/annotations/zh_Hant_HK.xml, common/annotationsDerived/zh_Hant_HK.xml, tools/cldr-apps/.settings/org.eclipse.wst.common.component, tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
CLDR-18692
- Broadened the number of look-alikes for | in annotations.
- Added test
- Ran over current annotations (to fix blue star)
Characters are now: https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%EF%B8%B3%EF%B8%B1%E0%A5%A4%7C%EF%BD%9C%E2%8E%B8%E2%8E%B9%E2%8F%90%EF%BF%A8%E2%9D%98%5D
=> CLDR-18692 Fix DAIP annotation delimiters

tools/cldr-code/src/main/java/org/unicode/cldr/util/CodeFallback.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExtraPaths.java
-Fix ExtraPaths.addLocaleDependent; pluralCounts was always empty for addCurrencies
CLDR-18588
=> CLDR-18588 New currencies ZWG and XCG missing forms for translation

tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-18712
Visible on staging,  https://cldr-staging.unicode.org/cldr-apps/v#/de/OtherUnitsMetric/4cb2101b01962374
Katal is one of the new units. So appears to be working correctly.
=> CLDR-18712 Don't include grammar for new units

tools/cldr-apps/js/src/esm/cldrMenu.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
-Repurpose the boolean parameter of getMenusAjaxUrl and SurveyAjax.WHAT_GET_MENUS to indicate whether to fetch canmodify (it is never used for fetching locmap anymore)
-Define a constant SurveyAjax.WHAT_LOCALE_MAP for consistency with other values for what
-Spelling: modifiable
-Comments
CLDR-18727
=> CLDR-18727 Fix fetching set of user-modifiable locales

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ICUServiceBuilder.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PluralSamples.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-18750
The compact number examples were wrong and confusion. In particular the value "0" is special, and means "revert to non-compact form", but people were seeing items like "2" for a range from 1000 to 9999.
=> CLDR-18750 Fix compact examples

common/main/ie.xml, common/supplemental/ordinals.xml, common/supplemental/plurals.xml
Interlingue does not have plural rules set up -- this change update them to the recommendation in the ticket CLDR-16762
CLDR-16762
=> CLDR-16762 Add plural rules for Interlingue

common/testData/datetime/datetime.json, tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java
This PR fixes an issue that is occurring in datetime test data generation, in which `alt="ascii"` alternate data is being picked up, even though no extra configuration was set to request it. So this is undesirable yet happening by default in some cases.
[CLDR-18370](https://unicode-org.atlassian.net/browse/CLDR-18370)
[CLDR-18370]: https://unicode-org.atlassian.net/browse/CLDR-18370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLDR-18370 Prevent alt=ascii values from being exported for datetime test data

tools/cldr-apps/js/src/esm/cldrLoad.mjs, tools/cldr-apps/js/src/esm/cldrNotify.mjs
- make loadAllRows async
- check the fetch result in loadAllRows - throw exception if fetch is failing rather than trying to decode JSON
- show a popup on loadAllRows failure to suggest reload
- add an exception parameter to cldrNotify.openWithHtml
CLDR-17354
=> CLDR-17354 offer to reload instead of failing with obscure message when navigating

tools/cldr-apps/js/src/esm/cldrForum.mjs, tools/cldr-apps/js/src/esm/cldrForumPanel.mjs, tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
-Require same permission for what=WHAT_FORUM_COUNT as for WHAT_FORUM_FETCH (formerly WHAT_FORUM_COUNT required no permission)
-On front end, for Info Panel, determine permission to post from the response to what=WHAT_FORUM_COUNT
-Note: the inconsistency became evident when CLDR_PHASE was changed from VETTING to VETTING_CLOSED
CLDR-18805
=> CLDR-18805 Make Info Panel forum permissions same as in Forum page

tools/cldr-apps/js/src/esm/cldrGui.mjs, tools/cldr-apps/js/src/esm/cldrSurvey.mjs
-New cldrSurvey.fetchInitialStatus, similar to updateStatus but async
-Await completion of cldrSurvey.fetchInitialStatus in cldrGui.initialSetup
CLDR-18790
=> CLDR-18790 Fetch initial ST status before other tasks

common/supplemental/plurals.xml, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-17707
The previous PR on this ticket added plural rules for Chuvash "cv" after identifying the need for "zero", "one", "other", but in the interests of quickly enabling the extra categories, "cv" was added to the existing "ksh" entry. This PR removes "cv" from the "ksh" entry and makes a separate "cv" entry.
=> CLDR-17707 adjust "cv" plural rule

tools/cldr-apps/js/src/esm/cldrLoad.mjs
-New function cldrLoad.linkToLocaleOnly for hash not including any page or row identifier
-Comments, including caution for the original error-prone cldrLoad.linkToLocale which is still used for everything but the left sidebar
CLDR-18796
=> CLDR-18796 Fix bogus left sidebar locale links

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/chart_messages.html
CLDR-18722
This PR makes many updates to the language-territory charts. The biggest is to add the official status column, but while I was here I made a number of formatting improvements that should improve the view of the tables. See these screenshots and descriptions of changes or the PR on cldr-staging https://github.com/unicode-org/cldr-staging/pull/191 :
|Page|Changes|Before|After|
|--|--|--|--|
|[Territory Language Information](https://www.unicode.org/cldr/charts/48/supplemental/territory_language_information.html)|Clarified descriptions, adding some links. Added reporting bug link, TSV link & official status context. Removed references to GDP and likely subtags (the old info was just wrong)|<img width="1007" alt="Screenshot 2025-07-09 at 12 52 17" …
=> CLDR-18772 Add Official Status Column to language-territory charts

tools/cldr-apps/js/src/esm/cldrVettingParticipation.mjs, tools/cldr-apps/js/src/views/VettingParticipation.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-New columns EMP and MP for Errors, Missing, and Provisional counts, based on organization-specific coverage level for locale
-Add tooltip descriptions (comments) for table column headers, matching those in spreadsheet
-Revise column headers: change Targ. Cover. to Coverage, change Vetter# to User#
-Make table header sticky so it remains visible when scroll down to see lowest rows
-On the back end, revise ReviewOutput and ParticipationResults to include errors/missing/provisional counts from LocaleCompletionData; the data was already computed but not included in the http response
-Revise LocaleCompletion Java comment and API description to clarify what was already true, that LocaleCompletion API uses the target coverage level, which is not specific to any organization (and therefore is …
=> CLDR-18610 VettingParticipation add EMP and MP; revise UI

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VotingParticipation.java
-Combine two appendInterestLocales methods into one
-Remove redundant comparison with UserRegistry.GUEST; only locked users have higher userLevel than GUEST; numerical comparison of userLevel is hard to understand, should be encapsulated, but is redundant here anyway
CLDR-18798
=> CLDR-18798 Vetters with bad locale codes: preliminary refactoring

tools/pom.xml
CLDR-18839
Until ICU gets to rc, reference a specific ICU4J dated asset within the version number (78.0.1-SNAPSHOT). Prevents ICU4J changes from breaking CLDR; this way a PR can check the changes.
=> CLDR-18839 Reference specific dated asset for ICU4J (until it is rc)

tools/scripts/llm/verify_cldr_ticket.py
**Description**
This script, `verify_cldr_ticket.py`, streamlines the process of gathering and formalizing acceptance criteria for CLDR JIRA tickets by combining JIRA’s API, HTML parsing, and a lightweight LLM. It begins by loading your JIRA credentials from a local `.env` file and fetching the ticket’s rendered description (falling back to JIRA’s Document Format if necessary). It then scans that text for an existing “Acceptance Criteria” section and, if none is found, invokes a pretrained text-to-text model to draft exactly five concise, one-sentence bullet points. By automating both extraction and generation of criteria, the tool ensures consistent, review-ready definitions of “done” across tickets while keeping sensitive tokens out of source code.
**Ticket**
CLDR-18745 …
=> CLDR-18745 Create verify_cldr_ticket.py

tools/scripts/llm/display_name_criteria_validator.py
CLDR-18745
Validates CLDR unit display names by ensuring all lengths (long, short, narrow) exist; all plural categories are covered with correct {0} placeholders; and optionally scores each pattern’s quality via an LLM.
=> CLDR-18745 Create display_name_criteria_validator.py

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateEnglishChanged.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowStarredCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathStarrer.java
-New getWithPattern gets default starred path, then replaces STAR_PATTERN with given pattern
-Use getWithPattern in GenerateEnglishChanged and ShowStarredCoverage
-Assume STAR_PATTERN would never occur (literally, not as regex) in an unstarred path
-Make STAR_PATTERN private for encapsulation, leaving open options for refactoring
-Fix compiler warnings in GenerateEnglishChanged, mostly automatic refactoring
-Comments
CLDR-18697
=> CLDR-18697 New PathStarrer.getWithPattern; make STAR_PATTERN private

common/rbnf/ro.xml
CLDR-18846
The exemplar data in common/main/ro.xml seems fine. U+0219 and U+021A (the preferred forms) appear in the main exemplar and U+015F and U+0163 appear in the auxiliary exemplar.
The ten changes in common/rbnf/ro.xml are all changing U+015F to U+0219.
=> CLDR-18846 update Romanian data

tools/scripts/llm/llm_cldr_validator.py
CLDR-18754
This Python script is a utility for comparing the output of Large Language Models (LLMs) with the ground truth data found in the Unicode CLDR.
It operates by taking a natural language prompt about unit preferences (e.g., "What is the road speed unit in the UK?"), querying a supported LLM like GPT or Gemini for a structured JSON answer, and then comparing that output against the official ground truth data from a local copy of the Unicode CLDR `unitPreferenceData.json` file.
The final output is a detailed comparison report that highlights matches and mismatches, making it an effective utility for testing an LLM's data conformance and knowledge precision.
=> CLDR-18745 llm_cldr_validator.py

common/supplemental/supplementalData.xml, common/validity/currency.xml, docs/site/development/updating-codes/update-currency-codes.md, tools/cldr-code/src/main/java/org/unicode/cldr/tool/CountItems.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/IsoCurrencyParser.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/dl_iso_table_a1.xml
CLDR-18492
- update latest data from SIX
- amendments include 179 (XAD) and 178 (CUC)
- fixed a problem with CountItems tool where it would silently succeed if a -Dmethod was not chosen
=> CLDR-18492 BRS currency update

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDelta.java, tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowStarredCoverage.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdPathIterator.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathStarrer.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/RegexLookup.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAlt.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathStarrer.java
-Change all pathStarrer.set to PathStarrer.get or PathStarrer.getWithPattern
-New constants PathStarrer.PERCENT_A_PATTERN and PathStarrer.SIMPLE_STAR_PATTERN
-Move other code (not general-purpose) from PathStarrer to private methods in RegexLookup and TestAlt
-New private RegexLookup.StarPatternMap.starPatternTransform corresponds to old PathStarrer.setOld and PathStarrer.transform2
-New private TestAlt.starSkippingAlt corresponds to old PathStarrer.setSkippingAttributes
-Revise TestPathStarrer to test PathStarrer.getWithPattern instead of PathStarrer.set; enable TestPathStarrer.testParallel
CLDR-18697
=> CLDR-18697 Remove all PathStarrer methods except get and getWithPattern

common/supplemental/coverageLevels.xml
The Regex to verify Hindi is translated is written incorrectly. It should be `hi(_Latn)?` so it means "hi or hi_Latn" but its written `hi(_Latn)` which will only match hi_Latn.
It's an easy fix and afaik no locales dropped in coverage -- but now new locales will see the gap in the survey tool. Many generated files change because there is a new value found now @ moderate.
CLDR-18831
=> CLDR-18831 Fix hi/Hindi locale display name coverage

common/testData/datetime/README.md, common/testData/datetime/datetime.json, tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDateTimeTestData.java
According to discussion in today's CLDR design meeting, which clarifies ambiguities around "standard time" vs. "at time" for the "glue pattern" style of formatting when a datetime object contains both a date and a time, the default value should be "at time" in our case.
More specifically, "at time" should be considered the default for formatting a single datetime at a time, and "standard time" should be used in contexts in which multiple datetimes are formatted. In the context of how our test data cases are created, "at time" for a single datetime is appropriate description of this context, so that should be the default.
This change removes explicit references to `atTime` values in the test cases because that will be redundant. We are thus testing that implementations not only are capable …
=> CLDR-18370 Make atTime default for DateTimeFormatType per UTS 35 clarification

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java
CLDR-18850
- move one issues to logKnownIssues
add logknownissue for Gujr transform to CLDR-18852 for U+0AF0
the workaround was in https://github.com/unicode-org/cldr/pull/4889 but was subsumed under #4888
=> CLDR-18850 v48 BRS vxml: logknownissue for unit tests

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
TestSupplementalInfo had incorrect logKnownIssues use
- gave a false negative, made it seem as if the test was passing
- test was ignoring the return value of logKnownIssue
CLDR-18490
=> CLDR-18490 v48 LogKnownIssues (August 2025 edition)

common/supplemental/metaZones.xml
CLDR-18788
The transitions I added in https://github.com/unicode-org/cldr/pull/4833 were not quite correct, some of them didn't align exactly with the time changes. 
I discovered this during ICU4X integration, which validates the alignments.
Also, the transition for `America/Coyhaique` added in #4593 was wrong.
=> CLDR-18788 Fix metazone times

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
-Restore three methods and three constants, only for backward compatibility
-Based on inspection only, these appear to be the only getName codes and methods currently needed by unicodetools, but testing may prove that more are needed
CLDR-18591
=> CLDR-18591 Restore CLDRFile API for unicodetools

tools/scripts/llm/JIRA_classify_ticket_with_rules.py
CLDR-18745
`feat: Implement advanced rule-based classifier engine`
This pull request significantly enhances the `jira_classifier.py` script by replacing the static, hardcoded JSON example with a dynamic, advanced rule-based classification engine. The script now fully processes the fetched Jira ticket data in real-time and generates a unique, intelligent classification for each ticket, making it a complete, self-contained tool.
This update introduces a new function, `classify_ticket_with_rules_advanced`, which serves as the core classification engine. It leverages several advanced techniques:
* **Regular Expressions (Regex)**: The `re` library is now used for sophisticated pattern matching. This allows the script to reliably detect and extract specific information, such as duplicate ticket …
=> CLDR-18745 JIRA_classify_ticket_with_rules.py

common/main/en_IN.xml
CLDR-18876
Fix long compact decimal format in en_IN based on CLDR-13759. Used inheritance instead of T for values below a lakh since  CLDR-17232, and it should have enough space if thousand is what's used in en.
We should investigate why this wasn't raised as an issue when the vetters reviewed the numbers report.
=> CLDR-18876 Fix long compact decimal format in en_IN

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LanguageTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestScriptMetadata.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java, tools/pom.xml
CLDR-18898
Update CLDR to use the latest published version of ICU4J (from 2025-08-14, but latest change was Mon Aug 11), which includes the Unicode 17 updates from Markus of 2025-08-08 including removing Chisoi script. Remove some logKnownIssue test skips related to Chisoi script.
=> CLDR-18898 Use latest (Aug 14) version of ICU4J, remove some logKnownIssue skips

tools/cldr-apps/src/test/java/org/unicode/cldr/util/TestCLDRLinks.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathDescriptionHints.md, tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathDescriptions.md, tools/cldr-code/src/test/java/org/unicode/cldr/util/TestPathDescription.java
-Move http links to bottom of PathDescriptions.md (references)
-Add unit test to check that http links only occur at the bottom (references, that is, lines starting with left bracket)
-Apply the same tests to PathDescriptionHints.md as to PathDescriptions.md
-Make .md filenames public, for messages, since some tests now apply to both PathDescriptionHints.md and PathDescriptions.md
-Two small simplifications for lambdas in TestPathDescription.java, per IntelliJ compiler warnings/autocorrections
CLDR-16755
=> CLDR-16755 Error fixing/testing for links in PathDescriptions

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java
CLDR-18891
Allows this to run where it failed before.
```shell
$ mvn --file=tools/pom.xml -pl cldr-code test  '-Dorg.unicode.cldr.unittest.testArgs=-e10 -n -filter:TestLocales' -Dtest=org.unicode.cldr.unittest.TestShim
```
=> CLDR-18891 update TestTransforms tests to run register() first

common/main/scn.xml
CLDR-18923
Replaced double single straight quotes with a right single curly quote to avoid issue.
Note: Also updated forms for consistency assuming the form is written `l'uri` for all at time formats based on scn phonology.
=> CLDR-18923 Replace straight single quote with right single curly quote

common/transforms/Gujarati-Latin.xml, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRTransforms.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/ExemplarUtilities.java, tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestTransforms.java
- remove log known issue
- rename ExemplarUtilities.getScript() to getLikelyScript() (and use it)
- clarify the transliterator used
And the actual fix:
- add U+0AF0 to the filter at the top of the Gujarati-Latin transform.
CLDR-18852
=> CLDR-18852 Gujr transform

common/annotations/ccp.xml, common/annotations/kab.xml
-Remove the line with 🥪 from annotations/ccp.xml
-Remove the lines with ⚙|🀄|🌤|🎀|💊|💲|🖲|🚀 from annotations/kab.xml
-Note: 🍐, etc., were already removed from annotations/sat.xml in PR 4888
CLDR-18882
=> CLDR-18882 Missing name (tts) annotations

tools/cldr-apps/js/src/esm/cldrGenerateVxml.mjs, tools/cldr-apps/js/src/views/GenerateVxml.vue, tools/cldr-apps/src/main/java/org/unicode/cldr/web/OutputFileManager.java, tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/GenerateVxml.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/Zipper.java
-Button causes creation of a zip file with the same parent as the vxml directory, and downloads it
-New utility Zipper.java uses ZipOutputStream, etc.
CLDR-18837
=> CLDR-18837 Button to download generated VXML in a zip

common/main/fr.xml, common/main/fr_CA.xml
CLDR-18569
Also removes irrelevant short names from `fr.xml`.
=> CLDR-18569 Add missing fr-CA short timezone names

common/main/de_CH.xml, common/main/lmo.xml, common/main/tn.xml, common/main/wal.xml
CLDR-13542
When I looked into this, I found that it was DAIP that was automatically changing the grouping separator. So aside from CH, the other cases (DDL locales) were probably originally entered as straight apostrophes.
In addition, somehow the following removed the grouping separator from de_CH, so this restores it (with the straight/ASCII) version.
- [v48 BRS generate algorithmic](https://github.com/unicode-org/cldr/pull/4961)
- https://github.com/unicode-org/cldr/commit/7fa7166e5fddf418739f35c06ee41eb16aeab5dd#diff-77acfe3eceed0aced87a3ee1334bb6499a63279f711f8733362d1e602b71d138L4932 
=> CLDR-13542 Fix remaining apostrophe groupings

docs/ldml/tr35-keyboards.md, docs/ldml/tr35-modifications.md
- strike a sentence under display about keys with no output
- add a sentence under layer about hardware layouts used as touch
per Kbd-WG
CLDR-18838
=> CLDR-18838 spec: keyboards: update display and layer description

tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrItem.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
CLDR-18956
For now, this just skips the rbnfRules element and uses the old deprecated content.
=> CLDR-18956 json: rbnf: for now just skip the 'new' format content

docs/site/development/maven.md
CLDR-18993
Updates the instructions for Maven setup when running tools locally. 
These instructions are used by people working on Unicode Tools, too. We need more details to help people who get confused by Github's new rules & configuration settings around all this (ex: related PR in Unicode Tools: https://github.com/unicode-org/unicodetools/pull/1208).
=> CLDR-18993 Update doc for Maven setup

docs/site/downloads/cldr-48.md, tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrItem.java, tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- add _rbnfRulesFile key under each rule with the name of the text file to load with the rules.
CLDR-18956
output is planned to appear in the forthcoming 48.0.0-ALPHA3 cldr-json release. You can see the new format at:
- https://github.com/unicode-org/cldr-json/tree/v48/cldr-json/cldr-rbnf/rbnf
=> CLDR-18956 cldr-json: RBNF new format

docs/site/development/updating-codes/updating-language-groups.md, tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DiffLanguageGroups.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java, tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java, tools/cldr-rdf/src/main/java/org/unicode/cldr/tool/GenerateLanguageContainment.java
CLDR-18996
This is just fixes to the tool - data change will be a separate PR.
- fix a less-than-helpful message on the `DtdData.DtdComparator` to tell what was being compared
- convert over the markdown page for GenerateLanguageContainment
- use `TempPrintWriter` (including an additional signature thereto) to prevent writing broken files
- document `TempPrintWriter.dontReplaceFile()`
- fix in `CLDRFile`: includes a fix for CLDR-18997 "CLDRFile shouldn't add extra paths to non-ldml DTDs (such as supplemental)"
=> CLDR-18996 fix GenerateLanguageContainment

tools/pom.xml
CLDR-19009
Improve the instructions for picking up updated ICU4J libraries in CLDR, and follow them to update CLDR to the latest ICU4J.
=> CLDR-19009 Use latest (Sep 23) version of ICU4J, improve instructions for updating ICU

docs/ldml/tr35-info.md
CLDR-14305
Note: while fixing a typo, I noticed that one of the possible implementation options below it was out of date (we'd concluded that using a percentage precision would be too big a hurdle. So I reworked it slightly to bring it up to date (it is not normative, just an example).
=> CLDR-14305 Small cleanup for total order in unit normalization

tools/cldr-apps/js/src/esm/cldrTable.mjs, tools/cldr-apps/js/src/esm/cldrVote.mjs
-Eliminate element tr.myProposal, which was displayed temporarily as though it were one of the candidate items received from the server, but had problems such as not being selectable, and staying visible indefinitely but disappearing on refresh; instead, if the vote/submission was rejected, show whatever needs to be shown using the notification interface
-Fix a problem where two notifications were displayed, one on top of the other, if a Vetter voted for an already-winning item with errors (submitted previously by TC); combine into a single notification
-Display the value as part of the notification
-Minor refactoring; remove some dead code
-Comments
CLDR-16819
=> CLDR-16819 Improve front-end handling of submissions with errors

docs/ldml/tr35-numbers.md
Most of CLDR-18914 was done by previous commits to CLDR-18758. This covers the few remaining items (some old `e` usages).
CLDR-18758
=> CLDR-18758 Fix dangling e operands

docs/ldml/tr35.md
=> CLDR-18366 Fix inconsistent nonterminal references

common/main/es_CO.xml, common/main/vmw.xml
CLDR-11536
- Remove attempted quoting of literal text in intervalFormatFallback (literal text in that pattern should not be quoted; but in the cases here the attempt to quote was also using curly quotes)
=> CLDR-11536 Fixed literal quoting in intervalFormatFallback, clarified quoting requirement in spec
