tools/cldr-code/src/main/java/org/unicode/cldr/tool/CopyNewEmoji.java

CLDR-16605 quick tool to copy missing emoji

---

tools/cldr-apps/js/src/esm/cldrForumFilter.mjs

-One new function passIfOpenWithoutResponse
CLDR-14380

CLDR-14380 Additional forum filter: Open topics without responses

---

common/main/en.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java

CLDR-16503
This doesn't correct all issues, but fixes an issue important for Shakedown

CLDR-16503 Fix problems in units for English

---

tools/cldr-apps/js/src/esm/cldrInfo.mjs
tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/src/main/webapp/css/redesign.css

-Position the button in the same place as the transcript, below the vote div
-Use the same button to reveal and hide (toggle)
-Move the code to a new subroutine makeVoteExplainerDiv
-Make the feedback link clickable
CLDR-16600

CLDR-16600 Improve UI for Explain Vote Counts

---

common/dtd/ldml.dtd
common/main/en.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/common/dtd/ldml.dtd

CLDR-16146
Note: tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/common/dtd/ldml.dtd didn't need to be changed, but it doesn't hurt (and I don't want to do another round).

CLDR-16146 Add variants for BIOT

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16684 Add organization for Mi'kmaw

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/UnicodeSetPrettyPrinter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java

CLDR-16687 Protect the format operation

---

common/main/en.xml
common/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java

CLDR-16163 New SI prefixes

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16705 add Anii Research Group org

---

tools/cldr-apps/js/src/esm/cldrAddAlt.mjs
tools/cldr-apps/js/src/esm/cldrCoverageReset.mjs
tools/cldr-apps/js/src/esm/cldrForum.mjs
tools/cldr-apps/js/src/esm/cldrForumPanel.mjs
tools/cldr-apps/js/src/esm/cldrGui.mjs
tools/cldr-apps/js/src/esm/cldrInfo.mjs
tools/cldr-apps/js/src/esm/cldrLoad.mjs
tools/cldr-apps/js/src/esm/cldrNotify.mjs
tools/cldr-apps/js/src/esm/cldrProgress.mjs
tools/cldr-apps/js/src/esm/cldrVote.mjs

-New method cldrNotify.exception for caught exceptions
-Make duration automatic: no time-out for errors/exceptions, 8 seconds for show/warning
-Minor refactoring and comments
CLDR-7536

CLDR-7536 Revise cldrNotify

---

docs/ldml/tr35.md

CLDR-16629
This fixes a problem that Frank found in the previous PR

CLDR-16629 fix the spec text

---

tools/cldr-apps/js/src/views/InfoPanel.vue

so it points down ↓ as requested in CLDR-16339
CLDR-16390

CLDR-16390 swap info panel inheritance explainer button

---

docs/ldml/tr35.md

* CLDR-16629 fix the spec text as per Frank's comments, updated the date
(cherry picked from commit 3d3f11f72dafaa35af7f00bcd38842f9a84cd709)
CLDR-16737
(This is just the cherry-pick from maint-43 to main)

CLDR-16737 from maint-43 to main: Fix for CLDR-16629 fix the spec text in #3030

---

README.md
readme.html

CLDR-16738
Just update readmes for v43.1 final. Also ran CLDRModify passes but they produced no changes.

CLDR-16738 Update readmes for 43.1 final. Ran CLDRModify passes, no change

---

tools/cldr-apps/js/src/esm/cldrAddAlt.mjs
tools/cldr-apps/js/src/esm/cldrComponents.mjs
tools/cldr-apps/js/src/esm/cldrGenericVue.mjs
tools/cldr-apps/js/src/esm/cldrGui.mjs
tools/cldr-apps/js/src/esm/cldrInfo.mjs
tools/cldr-apps/js/src/esm/cldrLoad.mjs
tools/cldr-apps/js/src/esm/cldrNotify.mjs
tools/cldr-apps/js/src/esm/cldrProgress.mjs
tools/cldr-apps/js/src/esm/cldrReport.mjs
tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/js/src/esm/cldrVue.mjs
tools/cldr-apps/js/src/esm/cldrVueMap.mjs
tools/cldr-apps/js/src/index.js
tools/cldr-apps/js/src/runGui.mjs
tools/cldr-apps/js/src/views/InfoSelectedItem.vue

-Improve formatting of currently selected item per ticket description
-New InfoSelectedItem.vue with improved formatting and explanatory tooltip
-Show a border when hovering to indicate which parts the explanatory tooltip refers to
-Rename cldrVueRouter.mjs to cldrVue.mjs with added methods for attaching Vue components to the DOM
-Simplify the function returned by cldrInfo.showItemInfoFn to be a one-liner for new theRow.selectedItem
-Clarify notify.exception to start with: Internal error
-Remove runGui.mjs, instead call cldrGui.run directly from index.js
-Remove unnecessary references to cldrBundle except in comments and for toggleTranscript
-Fix ticket-number typo in TODO comment related to toggleTranscript in index.js
-Move all .mjs files to the esm folder that were not there already; …

CLDR-7536 Improve Info Panel layout with Vue; related refactoring

---

docs/ldml/tr35.md

CLDR-16629 add to modifications

---

common/main/bew.xml
common/main/bew_ID.xml
common/supplemental/supplementalMetadata.xml

CLDR-16757 Core data for bew

---

tools/cldr-apps/js/src/esm/cldrDash.mjs
tools/cldr-apps/js/test/TestCldrDash.mjs
tools/cldr-apps/js/test/data/dash_data.mjs
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

-Take into account that the back end may return multiple rows even when only one row was requested
-Include the requested xpath string ID in the response to avoid confusion
-Increase error checking on the front end to facilitate future debugging; more try/catch and notifications
-Comments; TODO comment for returning only the requested row
CLDR-16766

CLDR-16766 Voting for inheritance, error message, Dashboard disappears

---

tools/cldr-apps/js/src/esm/cldrOldVotes.mjs
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

CLDR-16758 fix 'import old votes'

---

common/main/skr.xml
common/main/skr_PK.xml
common/supplemental/supplementalMetadata.xml

CLDR-16545 add skr Saraiki

---

common/main/tyv.xml
common/main/tyv_RU.xml
common/supplemental/supplementalMetadata.xml

CLDR-10985 add Tuvan tyv

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/RegexLookup.java

CLDR-16787 exclude typographicNames from same-as-code check

---

common/main/ko_CN.xml

CLDR-16792 Add Korean (China) locale

---

common/main/za.xml
common/main/za_CN.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalMetadata.xml

CLDR-16795 Add Zhuang (za) locale

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestReportStatus.java

- update some VoteAPIs as well to be reusable
CLDR-16313

CLDR-16313 update Report API to include vote results

---

tools/cldr-apps/js/src/esm/cldrComponents.mjs
tools/cldr-apps/js/src/esm/cldrUsers.mjs
tools/cldr-apps/js/src/views/CldrOrgAndUser.vue
tools/cldr-apps/js/src/views/CldrUser.vue
tools/cldr-apps/js/src/views/ReportResponse.vue
tools/cldr-apps/js/src/views/VoteInfo.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/UserAPI.java

- Vue component for VoteInfo
- Vue component for User (backed by REST api)
- REST api for user info
CLDR-16313

CLDR-16313 UI for Report Acceptability Votes

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16816 Apple should cover modern for mi

---

common/supplemental/ordinals.xml
common/supplemental/plurals.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java

CLDR-16791 Add Anii plurals

---

common/supplemental/dayPeriods.xml

CLDR-16790 Anii day periods

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java

- need to include both triple up arrow (soft) AND explicit (hard) votes
CLDR-16815
URLS for testing:
with this PR, these should both show users under the info panel voting for all values
https://cldr-smoke.unicode.org/cldr-apps/v#/mt//6e373b70f56b2bde (now broken!)
https://cldr-smoke.unicode.org/cldr-apps/v#/tk//e8ba06720b375aa (now fixed!)

CLDR-16815 fix vote-for-inheritance showing up again

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

- revert VoteEntry to just have userid
CLDR-16815

CLDR-16815 fix voter info

---

tools/cldr-apps/js/src/esm/cldrDash.mjs
tools/cldr-apps/js/src/esm/cldrNotify.mjs
tools/cldr-apps/js/src/esm/cldrXpathMap.mjs
tools/cldr-apps/js/src/views/DashboardWidget.vue

- also, update cldrXpathMap to support promises
- update cldrNotify to support raw string errors
CLDR-15807

CLDR-15807 dashboard download button

---

tools/cldr-apps/js/src/esm/cldrCoverage.mjs
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculateLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java

- include button to download .XLSX
CLDR-16807

CLDR-16807 report on up to date locale status

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json
tools/cldr-apps/js/src/esm/cldrBulkConverter.mjs
tools/cldr-apps/js/src/esm/cldrComponents.mjs
tools/cldr-apps/js/src/esm/cldrStatus.mjs
tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/js/src/esm/cldrVueMap.mjs
tools/cldr-apps/js/src/views/MainMenu.vue
tools/cldr-apps/js/src/views/UploadPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/webapp/check.jsp
tools/cldr-apps/src/main/webapp/upload.jsp
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleFactory.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCldrFactory.java

- move bulk upload jsp link into a new 'upload' panel
- add a converter from spreadsheet (xlsx/csv/etc)  (the Dashboard Download) to bulk-upload XML
- CLDRFile: add a 'leniency' option, disable validation for XML upload (it gets triple checked anyway)
CLDR-16846
FYI, draft

CLDR-16846 xlsx to xml converter for bulk upload

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-16645 Add zh_Hant_HK

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json

- load SheetJS from CDN
- would prefer not to do this, there's no reason it's not on npm
- background and discussion at CLDR-16725
CLDR-16437

CLDR-16437 SheetJS/XLSX from 0.18.5 to 0.20.0

---

tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java

- tweak UI for omitted English
CLDR-16683

CLDR-16683 if English is a sideways inherit, omit it rom ST

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java

CLDR-16846 allow bulk upload by TC unless readonly

---

tools/cldr-apps/js/src/views/WaitingPanel.vue

- don't redirect to the homepage, losing your place, on startup
- improve the 'startup' sequence a bit
CLDR-16887

CLDR-16887 st ui: redirect back to where you were

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/RegexFileParser.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestPathDescription.java

- broken in CLDR-16704
CLDR-16886

CLDR-16886 add test for PathDescription

---

common/main/ko_CN.xml

CLDR-16903 Add Gregorian time formats for ko_CN. Copied from zh

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

CLDR-16925 dashboard: provisional before losing

---

common/transforms/Hiragana-Katakana.xml

CLDR-16826 Fix multiline UnicodeSets in Hiragana-Katakana transform

---

.github/workflows/maven.yml

CLDR-16945 v44 BRS: -z FINAL_TESTING

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRTransforms.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java

CLDR-16945 BRS v44: fix unit tests

---

common/main/aa.xml
common/main/mt.xml

CLDR-16945 BRS v44: a couple of data fixes

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/units.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/nistAcceptedUnits.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/ExternalUnitConversionData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/GenerateNewUnits.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/NistUnits.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-16851
common/dtd/ldmlSupplemental.dtd
- Added the new systems (si_acceptable, metric_adjacent, astronomical, person_age, prefixable), and reordered
common/supplemental/units.xml
- Added the systems as appropriate. There is a worksheet in https://docs.google.com/spreadsheets/d/1V2uSCqvAKdPFgrfw9ahgEYX5V5_pcFgUwI6kGaAR8vk/edit#gid=909900283 with changes that were refined over the course of doing the ticket. 
- Column M was used to eliminate some si measures from being prefixable.
- There was a fix to the conversion factor for steradian
tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
- Change the logic to intersect with the si & metric (and variants)
tools/cldr-code/src/main/java/org/unicode/cldr/util/Rational.java
- Added utility for approximatelyEqual …

CLDR-16851 more unit systems

---

common/annotations/ps.xml
common/annotations/yo.xml
common/main/ar.xml
common/main/km.xml
common/main/mi.xml
common/main/ps.xml
common/main/yo.xml

- skipped: aa, mt (would reintroduce errs)
CLDR-16945

CLDR-16945 BRS v44: re-import of data from ST

---

common/annotations/ku.xml
common/annotations/zu.xml

- re-apply fixes from CLDR-16882
- does NOT fix all errs in ku
CLDR-16945

CLDR-16945 BRS v44: annotation error fix  ku, zu

---

common/main/nn.xml

- see also CLDR-16907
CLDR-16945

CLDR-16945 BRS v44: SLE/SLL  fix  nn

---

common/annotations/mai.xml
common/main/ks.xml
common/main/ks_Deva.xml
common/main/mi.xml
common/main/pcm.xml
common/main/raj.xml
common/main/to.xml
common/main/uz_Cyrl.xml
common/main/wo.xml
common/main/xnr.xml
common/main/za.xml

Most of the deleted items seem to be due to the CLDR-16946 bug
CLDR-16945

CLDR-16945 BRS v44: additional fixes

---

common/annotations/rhg.xml
common/main/rhg.xml

CLDR-16945
If it looks ok, go ahead and merge

CLDR-16945 fix rhg

---

common/annotations/cv.xml
common/annotations/ha.xml
common/annotations/kab.xml
common/annotations/ku.xml
common/main/be_TARASK.xml
common/main/bew.xml
common/main/en_Shaw.xml
common/main/ia.xml
common/main/kab.xml
common/main/ku.xml
common/main/ps.xml

CLDR-16945
I think this is the rest of the errors

CLDR-16945 fix ku and others

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

(cherry picked from commit 727ca04c350f2cf3569c98483a433c476d1ae3fc)
CLDR-16945
Note: #3151  but based on main.

CLDR-16945 Fix systems issue that caused check failures

---

common/main/bs.xml

(cherry picked from commit 727ca04c350f2cf3569c98483a433c476d1ae3fc)
originally part of #3151 
CLDR-16945

CLDR-16945 v44 brs: Fix for bs (Bosnian)

---

.github/workflows/maven.yml

CLDR-15836
Note that this is parallelizing the GitHub actions, not parallizing within console check.
*Bottom Line:* looks like this runs in ~19m instead of ~32m+ total. So about 13m shorter.

CLDR-15836 build: run check and build (tests) in parallel

---

LICENSE
README.md

CLDR-14239 update to v3 license

---

readme.html
tools/pom.xml

CLDR-16968
Update to latest ICU4J libs; update readme date & status

CLDR-16968 Update ICU4J libs #2; update date/status in readme

---

common/supplemental/units.xml

CLDR-16892
For windpeed, add GB to regions that use mile-per-hour

CLDR-16892 for windpeed, add GB to regions that use mile-per-hour

---

common/main/lb.xml

CLDR-16929 supply missing Basic items

---

common/main/ug.xml

CLDR-16929 add missing Basic value

---

common/main/nqo.xml

CLDR-16929 supply missing Basic values

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java

- -fG
- fixed purpose, upgrades Basic paths to unconfirmed
- ignores truly missing paths
Usage: CLDRModify cldr-modify -fG -mvmw
CLDR-16929

CLDR-16929 CLDRModify: add upgrade tool

---

common/main/nds.xml
common/properties/coverageLevels.txt

- extrapolate dateFormatItems hms -> hmsv and Hms -> Hmsv
- regenerate coverageLevels.txt
CLDR-16929
N.B.. these two missing items were noted correctly in the dashboard.

CLDR-16929 nds promotion

---

common/main/nn.xml

Test failure in #3088
CLDR-16857

CLDR-16857 fix for SLE

---

CONTRIBUTING.md
README.md

- to bring in line with updated requirements
- https://github.com/unicode-org/.github/issues/6
CLDR-14239

CLDR-14239 README.md and CONTRIBUTING.md updates

---

.github/workflows/gh-pages.yml
docs/charts/keyboard/.gitignore
docs/charts/keyboard/build.mjs
docs/charts/keyboard/index.html
docs/charts/keyboard/package-lock.json
docs/charts/keyboard/package.json
docs/charts/keyboard/static/index.html
docs/charts/keyboard/static/keyboard-chart.css
docs/charts/keyboard/static/keyboard-chart.js

- tooling to create Keyboard Charts
- also, add tr35 as an artifact in the gh-pages run
(cherry picked from commit 901c9b7bca48b6c0c048aba1b9ae8d1e322ef31f)
CLDR-16655

CLDR-16655 kbd: Keyboard 3.0 Charts

---

common/dtd/ldml.xsd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlBCP47.xsd
common/dtd/ldmlSupplemental.xsd
keyboards/dtd/ldmlKeyboard.xsd
keyboards/dtd/ldmlKeyboardTest.xsd
tools/cldr-code/src/main/java/org/unicode/cldr/util/DTD2XSD.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LDMLUtilities.java

CLDR-16994 BRS: Run GenerateDtd

---

common/annotations/en.xml
common/annotations/en_001.xml
common/main/en_001.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java

CLDR-16994 BRS: en_001 promotion

---

common/annotations/de_CH.xml
common/annotations/ha_NE.xml
common/annotations/sr_Latn.xml
common/annotations/sr_Latn_BA.xml
common/annotations/yo_BJ.xml
common/annotations/yue_Hans.xml
common/main/de_CH.xml
common/main/ha_NE.xml
common/main/sr_Latn.xml
common/main/sr_Latn_BA.xml
common/main/sr_Latn_ME.xml
common/main/sr_Latn_XK.xml
common/main/yo_BJ.xml
common/main/yue_Hans.xml

CLDR-16994 BRS: Algorithmic Locales

---

docs/ldml/tr35-keyboards.md

- address @mcdurdin feedback from PR #3111
- note: CLDR-16825 proposes removing \u1234 format.
CLDR-15034

CLDR-15034 spec: Address Keyboard feedback

---

common/properties/coverageLevels.txt

CLDR-16956 Updating the charts refreshed the coverage levels.

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowKeyboards.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/keyboards-index.html

- ShowKeyboards is out of date
- Also see CLDR-16655
CLDR-17018

CLDR-17018 revamp ShowKeyboards to just point to the landing page

---

common/main/eo.xml
common/properties/coverageLevels.txt

- run the promotion tool
- hand-add triple up arrow paths that weren't present before
CLDR-15878
followon to #3157 
fyi @verdulo

CLDR-15878 ddl: promote esperanto to basic

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java

-If the special paths are not present, add them
-New set toRetainSpecial; unlike toRetain, add if not already present even if CONSTRAINED_RESTORATION
-New code/data encapsulates which locales/paths are special
-Unrelated refactoring: use LocaleNames.ROOT instead of hard-coded root
-Unrelated refactoring: remove unused directoryName
CLDR-16208

CLDR-16208 Fix inheritance for default number systems in Arabic locales

---

common/main/en.xml
common/main/en_AU.xml
common/main/en_CA.xml
common/main/en_GB.xml
common/main/en_IN.xml
common/main/hi_Latn.xml
common/supplemental/units.xml
common/testData/units/unitsTest.txt
common/validity/unit.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-17037 Change name of gasoline-equivalent

---

docs/ldml/tr35-info.md

CLDR-16981 update the spec for -ms-

---

docs/ldml/tr35-keyboards.md
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlKeyboard.xsd
keyboards/import/scanCodes-implied.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-16604
Draft of scancode layout format

CLDR-16604 kbd: scancodeLayouts.xml

---

common/main/am.xml
common/main/as.xml
common/main/bas.xml
common/main/be.xml
common/main/be_TARASK.xml
common/main/bez.xml
common/main/blo.xml

- some mis
- my early fixes had just renames instead of copies.
CLDR-16857

CLDR-16857 SLE/SLL:  fixes to [ab]*

---

common/properties/coverageLevels.txt
common/testData/localeIdentifiers/likelySubtags.txt
docs/dev/GenerateTestData.md
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePersonNameTestData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateTestData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateUnitTestData.java

CLDR-17048
Also include new coverage file (generated by the chart build)

CLDR-17048 Rebuild testData

---

common/segments/root.xml

CLDR-17048
Tool is run from Unicodetools. 

CLDR-17048 Run Segmenter.java for new Unicode versions

---

README.md
readme.html

- merge anything pertinent into README.md
- make readme.html a stub
- update status badges
CLDR-13046

CLDR-13046 move readme.html to markdown README.md

---

common/supplemental/supplementalData.xml

CLDR-17057
Set CUC as invalid after 2021-01-01. 
@markusicu Thanks for the research on this!

CLDR-17057 Set CUC as invalid after 2021-01-01

---

common/main/fr.xml
common/testData/personNameTest/fr.txt
common/testData/personNameTest/fr_CA.txt

CLDR-17049 fix retain in fr PNF initials

---

common/supplemental/units.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-17077 Fix some unit systems

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java

-New methods doubleCheckSpecialPaths, doubleCheckLocale check the destination folder contents
-Throw an exception in the case of failure
-New methods directoryIsSpecial, localeIsSpecial preserve encapsulation of number systems, Arabic
-New method getLocaleIdFromFileName encapsulates getting locale ID from xml file name
-Comments
CLDR-16208

CLDR-16208 Default number systems in Arabic locales, double-check after generation

---

docs/ldml/tr35-keyboards.md
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlKeyboard.xsd
keyboards/dtd/ldmlKeyboardTest.dtd
keyboards/dtd/ldmlKeyboardTest.xsd

CLDR-16633 kbd: use NMTOKEN for ids

---

docs/ldml/tr35-keyboards.md

CLDR-15034
This is https://github.com/unicode-org/cldr/pull/3279 based on main. Editorial changes to the keyboard LDML.

CLDR-16918 Keyboard LDML editorial

---

keyboards/import/scanCodes-implied.xml

CLDR-16604
found in review of https://github.com/keymanapp/keyman/pull/9615

CLDR-16604 kbd:  jis scancodes incorrect

---

README.md
tools/cldr-apps/pom.xml
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/perf/PerfTest.java
tools/cldr-code/pom.xml
tools/cldr-code/src/main/java/org/unicode/cldr/icu/FixEras.java
tools/cldr-code/src/main/java/org/unicode/cldr/icu/RBNFWriter.java
tools/cldr-code/src/main/java/org/unicode/cldr/posix/GenerateCharmap.java
tools/cldr-code/src/main/java/org/unicode/cldr/posix/GeneratePOSIX.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/KeyboardTool.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Misc.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ModifyCase.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowData.java
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-17097
Update to new ICU4J libs. These have been newly re-organized for maven, required some changes to the artifact that we use, as well as to the paths for some imports. Also update README date & status.

CLDR-17097 Update ICU4J libs #4, new ICU4J mavenization; update README date & status

---

docs/ldml/tr35-general.md

CLDR-16711
Note: am not changing the Modifications section yet, since that can cause merge issues.

CLDR-16711 Uniqueness of units

---

docs/ldml/tr35-keyboards.md

CLDR-16918
Contains multiple items responding to @macchiati feedback in the above ticket.
Review note: can be reviewed commit-by-commit.
***NOTE*** Key modifiers will be covered in a separate ticket.

CLDR-16918 kbd: respond to macchiati feedback

---

docs/ldml/tr35-general.md

CLDR-17123 Document additional characterLabelPatterns

---

docs/ldml/tr35-general.md
docs/ldml/tr35-info.md

CLDR-17072 Document new unit systems

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java

CLDR-16662 json: Don't over-escape values

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

-CLDRModify.CLDRFilter.replace requires fullpath, otherwise draft-status is lost
CLDR-17063

CLDR-17063 CLDRModify -fQ keyword draft-status bug fix, use fullpath

---

docs/ldml/tr35.md

CLDR-17148
Flesh out the spec mods section; update spec date, Just a first pass at the mods, I am sure we will have more updates there.

CLDR-17148 Update spec date and mods section

---

docs/ldml/tr35-general.md

CLDR-16775 Fixes to transform spec

---

docs/ldml/tr35.md

CLDR-16937
Not in modifications section. Adding to https://unicode-org.atlassian.net/browse/CLDR-17152 instead to avoid rebasing issues.

CLDR-16937 Minor clarification for dx

---

docs/ldml/tr35-general.md

CLDR-16038 fix spec constraints using unit id component

---

docs/ldml/tr35.md

CLDR-17145 BRS/kbd: update Modifications section about the keyboard spec

---

.github/COMMIT_METADATA.md

- 2eef76b58182ee16e12897df33094eafd18a1833 should be CLDR-16883
CLDR-16883

CLDR-16883 v44: fix commit metadata

---

common/subdivisions/ha.xml

CLDR-16531
I ran the tool.  This was the only change among gbsct,gbnir,gbeng,gbwls which i thought were the only ones we were maintaining. So I didn't check in all of the changes.

CLDR-16531 v44 BRS: update subdivision codes

---

.github/COMMIT_METADATA.md

CLDR-17112 v44 BRS: commit metadata fix

---

common/main/da.xml

CLDR-17130 da missing unit for singular

---

docs/ldml/tr35.md

Updates to modification section reflecting:
- CLDR-16937
- CLDR-16038
- CLDR-16249
- CLDR-16251
CLDR-17152

CLDR-17152 v44 BRS: update modification section

---

docs/ldml/tr35-general.md

CLDR-16617
A remaining item that was missed.

CLDR-16617 Additional tweak to transforms spec

---

common/main/en_CA.xml

CLDR-16727
- [ x] This PR completes the ticket.
Removing the strange N/A value for short variant of Gulf Standard Time for en_CA

CLDR-16727 Remove short variant for Gulf Standard Time for en_CA

---

.github/COMMIT_METADATA.md

CLDR-17178 v45 brs: fix misticketted

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartLocaleGrowth.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareEmoji.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java

CLDR-17153
There is a file that I mistakenly included. It is, however, a useful tool for comparing emoji so I'd keep it.

CLDR-17153 Investigate discrepancy between growth and coverage charts

---

.github/dependabot.yml

CLDR-17168 v45 BRS: dependencies metadata

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java

- code reading LICENSE file was inadvertently using an obsolete filename
fyi @Manishearth 
CLDR-17137

CLDR-17137 v44: json: fix LICENSE file

---

README.md
docs/ldml/tr35.md

CLDR-17185
Just updated the dates for the README.md and spec. Checked to see whether the spec mods needed any updates for the recent specs changes, but they already seemed to be covered by the existing mods section.
(I want to do this for beta3 integration, but it is also sort of a test PR to make sure I can do CLDR work on my newly set up personal system)

CLDR-17185 Just update dates for readme and spec

---

docs/ldml/tr35-keyboards.md
docs/ldml/tr35.md

- clarify that keyboard is a technical preview
- fix typo in modification section
CLDR-15034

CLDR-15034 v44: spec: kbd: update to modification section and status

---

README.md
pom.xml
tools/cldr-apps/pom.xml
tools/cldr-code/pom.xml
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-17200
Remove -SNAPSHOT from CLDR version in pom.xml files, update README status and date

CLDR-17200 Remove -SNAPSHOT in version, update README status

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

- tr35 revsion 70
- Note, v43.1 had the wrong revision numbers, filed CLDR-17198
CLDR-17145

CLDR-17145 v44: specs to final

---

keyboards/3.0/pt-t-k0-abnt2.xml

CLDR-15034 kbd v44 fix typo in sample data file

---

.github/workflows/maven.yml

CLDR-17228 v45 SBRS: -z BUILD

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java

- update DEV_VERSION=45
- GenerateAllCharts should CREATE the new directory in cldr-staging.
CLDR-17228

CLDR-17228 v45 SBRS: fix DEV_VERSION, mkdir in charts

---

common/main/fr.xml
common/main/hi_Latn.xml
common/main/ku.xml
common/main/pap.xml
common/main/root.xml
common/main/syr.xml
common/main/vi.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java

CLDR-17220
Following on to the previous merge of maint-44 fixes back to main in PR #3373, this merges one additional maint-44 branch fix in #3394; everything else maint-44 has already been merged to main (or done first in main), or is not relevant to main (specific to the maint-44 branch such as final versioning).
**We want to merge this with a Rebase and merge (not a squash and merge) **

CLDR-17220 SBRS v45 merge one more maint/maint-44 fix back to main

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/ICUServiceBuilder.java

-Making ISB_CAN_CLEAR_CACHE true fixes the last known bug for this ticket
-This PR may finish the ticket, depending on whether the performance cost is acceptable
-Fix some compiler warnings (make some items final, remove some commented-out code, ...)
-Comments: updated comment about seed/main, and deleted commented-out code referencing CLDRFile
CLDR-13970

CLDR-13970 ST Examples used in patterns; make ISB_CAN_CLEAR_CACHE true

---

docs/ldml/tr35.md

CLDR-17194 Further clarifications of dx

---

CONTRIBUTING.md
LICENSE
README.md
common/dtd/ldml.dtd
common/dtd/ldml.xsd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlBCP47.xsd
common/dtd/ldmlSupplemental.dtd
common/dtd/ldmlSupplemental.xsd
common/testData/personNameTest/_header.txt
common/testData/personNameTest/_readme.txt
docs/README.md
docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
keyboards/dtd/ldmlKeyboard3.dtd
keyboards/dtd/ldmlKeyboard3.xsd
keyboards/dtd/ldmlKeyboardTest3.dtd
keyboards/dtd/ldmlKeyboardTest3.xsd
readme.html
tools/cldr-apps/README.md

CLDR-17300
Update copyright year in readmes, licenses, spec, dtds, etc.
Hopefully this catches everything, but hopefully we will also soon have a test to catch any other place that needs updating.

CLDR-17300 SBRS 45: Update copyright year in readmes, licenses, spec, dtds, etc.

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

- don't use user settings for voting/getrow queries
- on voting, reuse the test bundle instead of recreating it
CLDR-17249

CLDR-17249 be perf

---

.github/workflows/staging.yml
tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json
tools/cldr-apps/js/src/esm/cldrNotify.mjs
tools/cldr-apps/js/src/index.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/scripts/ansible/monitoring-playbook.yml
tools/scripts/ansible/requirements.yml
tools/scripts/ansible/templates/56-surveytool.j2
tools/scripts/ansible/templates/deploy-sh.j2
tools/scripts/ansible/templates/server-env.j2

CLDR-17270
- add datadog integration
- incidentally fix CLDR-14843 (though not deployed)

CLDR-17270 datadog integration

---

common/main/en.xml

CLDR-16379 change language name Achinese to Acehnese

---

common/main/en_IN.xml

CLDR-17232
Update 'T' to 'K' for thousand in compact decimal formatting for  en_IN

CLDR-17232 Update 'T' to 'K' for thousand in en_IN

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/TestCache.java

- was initializing the cache incorrectly
CLDR-7646 

CLDR-7646 fix for TestCache issue

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java

- add a logKnownIssue on CLDR-17320
- add a return to CheckCLDR.setLoggerLevel() so we can do save/restore level
CLDR-17304

CLDR-17304 quell some test errs

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java

CLDR-17321
This PR just adds the ticket number to the TODO

CLDR-17321 Annotations for allowing empty PCDATA

---

tools/cldr-apps/src/main/webapp/surveytool.css

CLDR-16595 Use Noto Nastaliq Urdu in surveytool for Kashmiri and Urdu

---

README.md
tools/pom.xml

CLDR-17335
Update ICU4J in CLDR to 75.0.1-SNAPSHOT, update README date.

CLDR-17335 Update ICU4J in CLDR to 75.0.1-SNAPSHOT

---

common/main/fr.xml

CLDR-17277 fr update language name ao

---

common/collation/lv.xml

Use the collation rules described in the LVS 24:1993 standard.
CLDR-11982

CLDR-11982 lv collation

---

.github/workflows/maven.yml

CLDR-17228 v45 revert to -z FINAL_TESTING for non-survey

---

tools/pom.xml

-Add toggleOffOn in pom.xml
-Now we can add spotless:off and spotless:on comments when/where convenient
CLDR-17344

CLDR-17344 Enable spotless:off/on

---

common/rbnf/id.xml

CLDR-17350 Fix Indonesian RBNF rules

---

common/dtd/ldml.xsd
common/dtd/ldmlBCP47.xsd
common/dtd/ldmlSupplemental.dtd
common/dtd/ldmlSupplemental.xsd
keyboards/dtd/ldmlKeyboard3.xsd
tools/cldr-code/src/main/java/org/unicode/cldr/util/DTD2XSD.java

- also fix Unicode encoding bug in DTD2XSD  (oops!)
CLDR-17401

CLDR-17401 v45 BRS: update DTDs

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

-Check givenOptions.value != null
CLDR-17144

CLDR-17144 Fix CLDRModify -f NPE

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Emoji.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java

-New Travel_Places2 (Travel & Places 2) starting with subgroup transport-ground
-New Objects2 starting with subgroup money
-New EmojiSymbols, Punctuation, MathSymbols, OtherSymbols, replacing Symbols2
-New methods PathHeader.createNonEmojiMap, PathHeader.getCharacterPageId
-New unit test TestAnnotations.testSymbols
-Fix some compiler warnings including dead code
-Comments, including TODO for Volume/Volume2
CLDR-11155

CLDR-11155 Pages too big; move some paths to new Pages

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java

- see also CLDR-17402
CLDR-17285
adds these to package.json:
```json
"cldrVersion": "45",
"unicodeVersion": "15.1.0"
```

CLDR-17285 json: add cldrVersion and unicodeVersion to package.json

---

docs/ldml/tr35-keyboards.md

CLDR-17177
- this PR is just for the modifiers section
- attempted to avoid overlap with #3495 as well

CLDR-17177 kbd: layers / modifiers update

---

README.md

CLDR-17401 v45 BRS: update v45 as preliminary

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/UnCodes.tsv

CLDR-17416 v45 BRS: Un Codes

---

common/annotations/de_CH.xml
common/annotations/ha_NE.xml
common/annotations/sr_Latn.xml
common/annotations/sr_Latn_BA.xml
common/annotations/yo_BJ.xml
common/annotations/yue_Hans.xml
common/main/de_CH.xml
common/main/ha_NE.xml
common/main/sr_Latn.xml
common/main/sr_Latn_BA.xml
common/main/sr_Latn_ME.xml
common/main/sr_Latn_XK.xml
common/main/yo_BJ.xml
common/main/yue_Hans.xml
common/rbnf/de_CH.xml
common/rbnf/sr_Latn.xml
common/rbnf/yue_Hans.xml
common/subdivisions/de_CH.xml
common/subdivisions/ha_NE.xml
common/subdivisions/sr_Latn.xml
common/subdivisions/yo_BJ.xml
common/subdivisions/yue_Hans.xml

CLDR-17417
I normally run CLDRModify `-fp` but that is disabled per #3502 - anything else to do here?

CLDR-17417 v45 BRS: algorithmic locales

---

README.md

CLDR-16235 Sync README with https://cldr.unicode.org/index

---

common/main/uk.xml

Changing EEEE to cccc.
CLDR-17394

CLDR-17394 uk accusative case of weekdays

---

docs/ldml/tr35-messageFormat.md

CLDR-17407 Update tr35-messageFormat.md

---

docs/ldml/tr35.md

CLDR-17432 fix modifications section, date

---

common/main/ku.xml

CLDR-17024 Deleted conflicting short time zone names in Kurdish.

---

common/testData/localeIdentifiers/likelySubtags.txt
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateLikelyTestData.java

CLDR-17150
We need to check earlier that CLDR has data.

CLDR-17150 fix likely subtag test

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java

-New testPageSize in TestPathHeader.java
CLDR-11155

CLDR-11155 Pages too big: add test for large pages

---

common/main/en_CA.xml

CLDR-17372
Fix narrow USD format in en_CA

CLDR-17372 Fix narrow USD format in en_CA

---

common/main/hi_Latn.xml

CLDR-17450 
hi-Latn change India to Bharat
-  [x] This PR completes the ticket.

CLDR-17450 hi-Latn change India to Bharat

---

.github/COMMIT_METADATA.md

CLDR-17178 BRS fixes to COMMIT_METADATA.md

---

common/dtd/ldml.xsd
common/dtd/ldmlBCP47.xsd
common/dtd/ldmlSupplemental.xsd

CLDR-17401
Review note: Hide whitespace please.

CLDR-17401 BRS v45: GenerateDtd update

---

docs/ldml/tr35-personNames.md

CLDR-16713 Remove old text about draft ICU api

---

docs/ldml/tr35.md

CLDR-17251 Fixes to likely subtags spec

---

tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestUserRegistry.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestSTFactory.java

CLDR-17493 fix cldr-apps tests to skip if no database

---

docs/ldml/tr35-info.md
docs/ldml/tr35.md

- CLDR-17401 BRS: update spec ToC
CLDR-17401

CLDR-17401 v45 BRS: update spec ToC

---

.github/workflows/maven-release.yml

- cache .git and checkout cldr-archive when tagging for maven
CLDR-16393

CLDR-16393 unbreak maven tag

---

README.md
docs/ldml/tr35.md

CLDR-17500
Just update README date & status for public beta; also fix spec date to today, not tomorrow

CLDR-17500 Update README date & status, fix spec date

---

common/main/zh_Hans_MY.xml
common/main/zh_Hant_MY.xml

We didn't end up getting other commits in besides the zh_Hans_MY one. So this is ready to merge.

CLDR-17006 v46: DDL data branch

---

tools/pom.xml

CLDR-17512
- [ x] This PR completes the ticket.
Update ICU4J in CLDR to 75.1-SNAPSHOT

CLDR-17512 Update ICU4J version to 75.1-SNAPSHOT

---

tools/cldr-apps/js/src/esm/cldrAnnounce.mjs
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Announcements.java

-Distinguish between -1 for no response yet, and 0 for no announcements yet
-Include the most recent ID in the response even if that particular announcement is filtered out, so that the client will not keep getting redundant filtered data when there are no new announcements
CLDR-17515

CLDR-17515 Improve the announcements protocol

---

.github/dependabot.yml

CLDR-17492 deps: update dependabot settings for v46

---

docs/ldml/tr35.md
tools/scripts/tr-archive/fix-tocs.js

- fix to support CRLF on windows
- rerun tool and pickup an incorrect link in tr35.md (.html should be .md)
CLDR-17416

CLDR-17416 v45 docs: fix ToCs

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java

Co-authored-by: David Beaumont <david.beaumont+github@gmail.com>
CLDR-17504

CLDR-17504 fix recursive update in XPathParts

---

common/testData/personNameTest/_header.txt

CLDR-16938
Note: fixes the comment at the top also (used to say 'unit conversions')

CLDR-16938 Restore _header.txt file

---

README.md
docs/charts/keyboard/pom.xml
docs/ldml/tr35.md
pom.xml
tools/cldr-apps/pom.xml
tools/cldr-code/pom.xml
tools/cldr-rdf/pom.xml
tools/pom.xml

CLDR-17541
Update README status & date for final.
Update spec date.
Update CLDR poms for final to use version 45.0 without -SNAPSHOT, and also update to use ICU4J vision 75 without -SNAPSHOT. (Oddly the top-level pom was still using version 44)

CLDR-17541 Update README status/data & spec date, update CLDR poms for final

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-messageFormat.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-17529 v45 BRS - spec to final

---

docs/ldml/tr35-personNames.md

- part 8 was missed
CLDR-17529

CLDR-17529 v45 spec to final - part 8

---

tools/cldr-apps/src/main/java/org/json/JSONArray.java

- fix an infinite recursion
- unbreak 'recent items'
CLDR-17548

CLDR-17548 deprecated re-box primitives in deprecated use of org.json in deprecated SurveyAjax

---

tools/pom.xml

CLDR-17595
Update ICU4J libs for CLDR to 76.0.1-SNAPSHOT

CLDR-17595 Update ICU4J libs for CLDR to 76.0.1-SNAPSHOT

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckWidths.java

CLDR-17532
(also temporary, should lower to 25-30 once the data is added)

CLDR-17532 Increase max to 45

---

common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-17590
Update Locales.txt for v46 submission

CLDR-17590 Update Locales.txt for v46

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDisplayCollisions.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java

CLDR-16853 remove raw URLs from checks, handle via subtype map

---

common/main/en.xml
common/supplemental/coverageLevels.xml
common/supplemental/metaZones.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/XPathToMenu.java

CLDR-17368 Added metazone 'Kazakhstan' (short: 'kaza')

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-17590
Add te to locales.txt for Meta

CLDR-17590 Add te to locales.txt for Meta

---

common/main/kok_Deva.xml
common/main/kok_Deva_IN.xml
common/main/kok_Latn.xml
common/main/kok_Latn_IN.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv

CLDR-17122 add kok-Latn

---

common/supplemental/metaZones.xml

https://unicode-org.atlassian.net/browse/CLDR-17601
CLDR-17601 align metazone from/to dates with IANA data.

CLDR-17601 Fix Asia/Kuala_Lumpur metazone start/end boundaries.

---

tools/cldr-apps/js/src/esm/cldrTable.mjs

-Add margins and orange/green padding around 👁️‍🗨️/💬 icons, to make them easier to notice and distinguish
CLDR-17461

CLDR-17461 Forum posts in vetting view, change icon style

---

common/main/en.xml

CLDR-13864 Fix per night, long form

---

common/supplemental/metaZones.xml

Cherry-pick to maint-45.
CLDR-17601 align metazone from/to dates with IANA data.

CLDR-17601 v45 Fix Asia/Kuala_Lumpur metazone start/end boundaries

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-13935
Add Survey Tool examples for minimumGroupingDigits (Examples showing numbers with 3, 4, and 5 integer digits using the specified minimumDigits value)

CLDR-13935 Add ST examples for minimumGroupingDigits

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-Always filter by validPaths to fix NullPointerException that was caused by obsolete/invalid paths
-Filter votes sooner to avoid repeatedly looping through votes that should be filtered
-For consistency and efficiency, move filtering code from viewOldVotes and submitOldVotes to filterPathsForManualImport, which in turn is called by getOldVotesRows, called by both viewOldVotes and submitOldVotes
-The method filterPathsForManualImport is based on old filterDowngradePaths
-In the import db table, use the value processed by current DAIP, not the old DAIP when the vote was made (although neither is guaranteed to produce the correct results in general using SQL only; this way enables further filtering with importTableContains)
-Filter out votes that match the current winning value after …

CLDR-17652 Import Old Votes NullPointerException and other bugs

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

- sort list
- add es_AR
CLDR-17669

CLDR-17669 update Locales.txt for Airbnb

---

tools/cldr-apps/js/src/esm/cldrDash.mjs

CLDR-17658 Fix recently introduced bug, this is undefined

---

common/supplemental/ordinals.xml
common/supplemental/plurals.xml

CLDR-17622 Ladin (lld) plural rules

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckWidths.java

CLDR-17532 Reset keyword limit to 20

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-17590
Lower ti to moderate coverage for better progress tracking

CLDR-17590 Lower ti to moderate coverage

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-17590
Remove cv from locales.txt

CLDR-17590 Remove cv from locales.txt

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java

- no restrictions on user privileges or phase
CLDR-16799

CLDR-16799 st: Dashboard remains open

---

tools/cldr-apps/src/main/webapp/css/redesign.css

-Make the existing style lrmarker-container more distinctive per ticket description
CLDR-17572

CLDR-17572 Clarify in ST when text is commentary instead of content

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

CLDR-17377 disable CLDRModify -fV

---

common/main/ii.xml

CLDR-17812
#3856 is work in progress on the numbering system.

CLDR-17812 ii: drop yiii numbering system

---

common/testData/localeIdentifiers/localeDisplayName.txt

- Tool: GenerateLocaleIDTestData
CLDR-17182
Merge into #3880

CLDR-17812 v46 vxml: update testdata to match vetter input

---

common/testData/personNameTest/af.txt
common/testData/personNameTest/ak.txt
common/testData/personNameTest/am.txt
common/testData/personNameTest/bal_Latn.txt
common/testData/personNameTest/ga.txt
common/testData/personNameTest/gd.txt
common/testData/personNameTest/ig.txt
common/testData/personNameTest/kn.txt
common/testData/personNameTest/pcm.txt
common/testData/personNameTest/so.txt
common/testData/personNameTest/ti.txt
common/testData/personNameTest/yo.txt

CLDR-17812
merge into #3880 
Regenerate personName test data, fixes many unit test errors with imported VXML

CLDR-17812 v46 vxml: Regenerate personName test data

---

common/annotations/ff.xml

common/annotations/ff.xml is "empty" of values, but it is needed for the hierarchy.
CLDR-17812
- merge into #3880 

CLDR-17812 v46 vxml: annotations: ff: reinstate empty file

---

docs/site/development/development-process/design-proposals/units-pixels-ems-display-resolution.md
docs/site/translation/getting-started.md
docs/site/translation/getting-started/vetting-view.md
docs/site/translation/miscellaneous-displaying-lists.md
docs/site/translation/translation-guide-general.md
tools/scripts/web/docker/Dockerfile
tools/scripts/web/docker/README.md
tools/scripts/web/docker/docker-compose.yml

CLDR-17803
- fix some yaml errs in the frontmatter
- add a Docker build for local testing (with docs)

CLDR-17803 site: fix frontmatter errs, add docker build

---

common/main/blo.xml

CLDR-17812 blo: drop incomplete groups

---

common/main/yo_BJ.xml

- regenerate transformed locale yo_BJ
CLDR-17182

CLDR-17812 yo_BJ: regen from yo

---

.github/workflows/maven.yml

CLDR-17812 move to -z FINAL_TESTING

---

common/main/pap.xml

CLDR-17812 pap: drop two incomplete groups

---

docs/dev/generate-emoji-paths.md

update some of the language of instructions
CLDR-17582

CLDR-17582 Update generate-emoji-paths.md

---

common/supplemental/supplementalData.xml

CLDR-11008 Change default calendar for SA to gregorian

CLDR-11008 Update SA default calendar

---

common/main/fi.xml

CLDR-17833 updating Finnish abbreviated months

---

common/properties/coverageLevels.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

CLDR-17830 Update coverageLevels.txt

---

common/main/zh.xml

CLDR-17767 Update IDR translation in zh

CLDR-17767 Update IDR translation in zh

---

common/supplemental/ordinals.xml
common/supplemental/pluralRanges.xml
common/supplemental/plurals.xml

CLDR-17610 v46 BRS: rerun GeneratePluralRanges/GeneratedPluralSamples

---

tools/cldr-apps/js/src/esm/cldrForum.mjs

-Change postType to pi.postType in openPostOrReply
CLDR-17799

CLDR-17799 Forum, fix bug in last PR

---

common/supplemental/units.xml

CLDR-17860 Update wind speed to m/s in JP

CLDR-17860 Update wind speed to m/s in JP

---

common/main/yue_Hant_CN.xml
common/supplemental/supplementalData.xml

CLDR-17871
- Create stub locale for yue_Hant_CN.xml
- Update population data

CLDR-17871 Create yue_Hant_CN stub locale

---

common/supplemental/languageInfo.xml

CLDR-17627 Make Sicilian scn fallback to Italian it

---

common/supplemental/units.xml

CLDR-17875
Update default wind speed for DK and CN while we research common usage in the remaining regions.

CLDR-17875 Update default wind speed for DK and CN

---

common/annotations/en_001.xml

CLDR-17882 rewindershins -> rewind

---

docs/ldml/tr35-collation.md
docs/site/downloads/cldr-46.md

CLDR-17226 document collation changes in CLDR 46

---

.github/workflows/site.yml

- only update PR if there's a PR - correct an error on merge to main previously.
CLDR-17803

CLDR-17803 docs/site: fix merge to main

---

common/testData/localeIdentifiers/localeDisplayName.txt
common/testData/units/unitPreferencesTest.txt

CLDR-17830 BRS GenerateTestData.java

---

docs/site/downloads/cldr-46.md

CLDR-17830 BRS Release page fixes

---

docs/site/_layouts/page.html
docs/site/assets/js/cldrsite.js

- add anchor.js (same as used w/ spec)
- load from CDN
CLDR-17933

CLDR-17933 site: auto linkify headings

---

docs/site/404.html

CLDR-17934 site: add a 404 page

---

docs/site/assets/css/page.css

CLDR-17947 site: css: update sizes of h1, h2, h3, h4, h5, h6

---

docs/ldml/tr35.md

CLDR-17951 Update tr35.md, hoist Unicode BCP 47 Locale Identifier.

---

docs/ldml/tr35.md

CLDR-15611 Update tr35.md for special script codes

---

docs/ldml/tr35.md

CLDR-17235 Organize conformance references

---

docs/site/downloads/cldr-46.md

CLDR-17982
Fix links on 46 release page

CLDR-17982 Fix links on 46 release page

---

docs/requesting_changes.md

CLDR-17982
Add back page as redirect for anyone who had the original page linked.

CLDR-17982 Add permanent redirect from original location

---

docs/ldml/tr35.md

CLDR-17830
This retrofits the spec changes from the release page back into the spec modifications section, organizing by topic.

CLDR-17830 Update modifications section

---

docs/site/_config.yml
docs/site/_redirects

CLDR-17977
Try for example: 
- https://73c8d91b.cldr.pages.dev/index/downloads/cldr-45
- https://73c8d91b.cldr.pages.dev/index/downloads/cldr-42
- https://73c8d91b.cldr.pages.dev/index/downloads/cldr-999 (404 still works)

CLDR-17977 site: add _redirects file for downloads

---

docs/site/downloads/cldr-46.md

CLDR-17830
- Added bulleted item about important spec changes
- Abbreviated the spec section, and pointed to the Modifications section for more details (That mods section is better organized.)
- Added text from Addison summarizing the MF2.0 most important changes
- Dropped 17505 from Known Issues
- Added interns
Let me know if anything else needs changing.

CLDR-17830 Release page fixes

---

docs/site/index.md

CLDR-17982 Add 46 beta news item

CLDR-17982 Add 46 beta news item

---

docs/site/downloads/cldr-46.md

CLDR-17982
Update link to latest JSON data for beta

CLDR-17982 Update link to latest JSON data

---

docs/site/_redirects

CLDR-17977
- try:
- https://913cd2be.cldr.pages.dev/index/downloads/latest
- https://913cd2be.cldr.pages.dev/index/downloads/dev
- https://913cd2be.cldr.pages.dev/downloads/latest
- https://913cd2be.cldr.pages.dev/downloads/dev
Note:
- we'll need to update these as needed of course

CLDR-17977 site: Update _redirects for latest/dev

---

tools/pom.xml

CLDR-17988
Update ICU4J libs for CLDR to 76.1-SNAPSHOT

CLDR-17988 Update ICU4J libs to 76.1-SNAPSHOT

---

docs/site/downloads/cldr-46.md

Add a list of changed files, and additional intern name.
CLDR-17830

CLDR-17830 Update release page

---

.github/dependabot.yml

CLDR-17993
this BRS activity is needed right after a branch. Please review.

CLDR-17993 deps: update workflow for v47 deps (BRS)

---

docs/ldml/tr35-keyboards.md

CLDR-17807 minor edits

---

docs/ldml/tr35-numbers.md

CLDR-18008
Alternative B. Compare to Alternative A: #4111

CLDR-18008 Specify that currency digits might NOT be derived from ISO 4217

---

docs/site/_layouts/page.html
docs/site/assets/css/page.css
docs/site/assets/js/cldrsite.js

- and, prepare for including ToC from pages
CLDR-18001
- pick the latest preview link ✨ from below
- see the root page - note the sidebar
- does not include page table of contents quite yet- soon.
(note: UI update)

CLDR-18001 site: move subpages to sidebar

---

docs/ldml/tr35-keyboards.md
keyboards/3.0/bn.xml
keyboards/3.0/fr.xml
keyboards/3.0/ja-Hira-t-k0-flicks.xml
keyboards/3.0/ja-Latn.xml
keyboards/3.0/mt-t-k0-47key.xml
keyboards/3.0/mt.xml
keyboards/3.0/pcm.xml
keyboards/3.0/pt-t-k0-abnt2.xml

- document conformsTo in further detail
- comment the test data to explain why conformsTo isn't the latest release
CLDR-17948

CLDR-17948 v46 keyboard spec: update conformsTo docs

---

docs/site/assets/css/page.css
docs/site/assets/js/cldrsite.js

CLDR-18001
- move arrow into `&nbsp;»` and off right edge
- indent ToC entries according to their level
observe moved arrow and indents

CLDR-18001 site: improve subpage and ToC 

---

docs/site/cldr-tc.md
docs/site/ddl.md
docs/site/development.md
docs/site/development/getting-started.md
docs/site/development/tests-and-tools.md
docs/site/development/updating.md
docs/site/general-information.md
docs/site/index/keyboard-workgroup.md
docs/site/translation/characters.md
docs/site/translation/core-data.md
docs/site/translation/date-time.md
docs/site/translation/displaynames.md
docs/site/translation/language-specific.md
docs/site/translation/miscellaneous.md

With the new nav bar, some pages need corrections
CLDR-17995

CLDR-17995 Fix pages after new nav bar

---

docs/ldml/tr35-info.md

CLDR-17893
Fix for Frank's comment in https://unicode-org.atlassian.net/browse/CLDR-17893?focusedCommentId=177844

CLDR-17893 Fix rg validation example

---

docs/site/_layouts/page.html
docs/site/_layouts/sitemap.html
docs/site/assets/css/page.css
docs/site/assets/js/cldrsite.js

- drop Site Map from header
- drop "temporary navigation" notice
CLDR-18006
- check the main and site map pages' top nav bar
- still doesn't line up 100%

CLDR-18006 site: updates to top bar

---

docs/site/index.md
docs/site/translation.md
docs/site/translation/getting-started.md
docs/site/translation/getting-started/guide.md

-Fix some broken links (like Updates), some found manually, others found using lychee
-Made all links (except images) relative to docs/site
-Do not say Survey tool is currently open for submission
-Concerning some emoji news, change These will be released... to These were released...
-Make the text "and many others, including:" part of the following list item, to avoid irregular formatting
-Uniformly call the Info Panel the Info Panel rather than the Information Panel, Info Pane, etc.
-Change http: to https:
-Remove News item dated 2022-11-28
CLDR-8038

CLDR-8038 Revise index.md, translation.md, getting-started.md, guide.md

---

tools/cldr-apps/js/src/esm/cldrVote.mjs
tools/cldr-apps/js/src/views/NotificationPopup.vue

CLDR-16750 TODO comments for remaining tech-debt

---

docs/site/index/cldr-spec/collation-guidelines.md
docs/site/index/cldr-spec/plural-rules.md
docs/site/index/draft-schedule.md
docs/site/index/locale-coverage.md
docs/site/index/process.md
docs/site/translation/date-time/date-time-names.md

-Even with these changes, some of these files still have some broken links per lychee
CLDR-8038

CLDR-8038 Fix links in several files in docs/site

---

docs/ldml/tr35-keyboards.md

CLDR-18027 enter changes from CLDR-17807

---

docs/site/_layouts/page.html
docs/site/_layouts/sitemap.html

CLDR-15821 site: add Analytics to site

---

.github/workflows/commit-checker.yml

CLDR-18026 Update commit-checker.yml

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-17964 add Stanford SILICON

---

docs/site/index/keyboard-workgroup.md

- update links to keyboard spec and current status
CLDR-18023
- Preview the site under https://2f163433.cldr.pages.dev/index/keyboard-workgroup or later

CLDR-18023 site: Update keyboard-workgroup.md

---

tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/gtag.html

CLDR-18031
Cherry-pick of CLDR-15821 v47 add Analytics to spec (#4138)
(cherry picked from commit a220913d5477ddd9a55fb2e00753ecdc710af651)

CLDR-18031 v46: add analytics to spec

---

docs/ldml/tr35-general.md

CLDR-18031 v46 spec: replace broken link on rae.es with internet archive

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-general.md

- part of running the ToC updater
- the ToCs were all fine, but it did catch these two issues.
CLDR-18031 

CLDR-18031 v46 BRS: fix spec ToC / endings

---

docs/site/404.html

CLDR-15821
the 404 page didn't have analytics on it

CLDR-15821 site: add analytics to 404 page

---

docs/site/_redirects

- this is a common link in the spec
CLDR-17999
- <https://3163ebbf.cldr.pages.dev/index/bug-reports> redirects to the Requesting Changes page

CLDR-17999 site: /index/bug-reports renamed

---

docs/site/index/cldr-spec/cldr-json-bindings.md
docs/site/sitemap.tsv

- from https://sites.google.com/unicode.org/cldr/index/cldr-spec/cldr-json-bindings
CLDR-18007
https://94c88b1d.cldr.pages.dev/index/cldr-spec/cldr-json-bindings
For now just transfers over this page as an archive

CLDR-18007 site: transfer over the cldr json bindings doc

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-messageFormat.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md

CLDR-18047
Update spec to final. Remove the "Tech Preview" from title of the keyboards part.

CLDR-18047 Update spec to final

---

docs/site/downloads/cldr-46.md

CLDR-18014
- check https://4ebd3622.cldr.pages.dev/downloads/cldr-46

CLDR-18014 v46 link-check fixes to download page

---

docs/site/development/cldr-big-red-switch/generating-charts.md

CLDR-18014 site: update generating-charts

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java

CLDR-18041 json: include _variant field in metadata

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java

- move ConsoleCheckCLDR to CLDRLocale and off LocaleIDParser
- fixes a concurrency issue, cleans up other code
CLDR-18053

CLDR-18053 fix ConsoleCheckCLDR threading issue

---

docs/site/_redirects

CLDR-18059
BRS 46 Update site redirects for latest, dev

CLDR-18059 BRS 46 Update site redirects for latest, dev

---

common/main/cop.xml
common/main/cop_EG.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv

CLDR-17987
This temporarily uses the Latin numbering system until we have values for Coptic numbers.

CLDR-17987 Create coptic locale

---

docs/site/index/acknowledgments.md

CLDR-18018
- the first commit is moving the list to a Markdown list
- the second commit has the v46 updates
https://0e15a924.cldr.pages.dev/index/acknowledgments

CLDR-18018 v46: update Acknowledgements

---

docs/site/downloads/cldr-46.md

CLDR-18014
- Clarify kok locale macrolanguage change
- Other minor edits

CLDR-18014 Clarify kok locale macrolanguage change

---

docs/site/downloads/cldr-46.md

CLDR-18014
Add two known issues to the release page

CLDR-18014 Update known issues

---

common/main/en.xml

CLDR-18073 Fix Samoan metazones

---

common/main/yue_Hant_CN.xml

CLDR-17979
Add std time formats for yue_Hant_CN from H-cycle availableFormats in yue_Hant

CLDR-17979 Add std time formats for yue_Hant_CN from H-cycle availableFormats in yue_Hant

---

docs/ldml/tr35-general.md

CLDR-15948
Fix wording as noted in https://github.com/unicode-org/cldr/pull/4179#pullrequestreview-2437621281

CLDR-15948 Fix wording in tr35-general.md

---

tools/cldr-code/src/main/java/org/unicode/cldr/draft/Misc.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ExtractMessages.java

-Remove TODO comment in Misc.java, add comment explaining why no freeze
-Use ROOT_COLLATOR in CLDRModify.java
-Use ROOT_SECONDARY in ExtractMessages.java
CLDR-7428

CLDR-7428 Freeze collators; finishing touches

---

docs/site/requesting_changes.md

CLDR-18065
Make link to project in Jira clickable

CLDR-18065 Make link clickable

---

common/main/hi.xml

CLDR-11562
Update spelling of October both wide and abbreviated

CLDR-11562 Update spelling of October

---

common/main/ja.xml
common/main/ko.xml
common/main/yue.xml
common/main/yue_Hans.xml
common/main/zh.xml
common/main/zh_Hant.xml

CLDR-18136
I made a basic test for this in ICU4X and used it to identify what to fix in the first pass. https://github.com/unicode-org/icu4x/pull/5826

CLDR-18136 Fix ja, ko, zh, yue datetimeSkeleton

---

.github/workflows/js.yml

see CLDR-17780 for longer term fixes
CLDR-18174

CLDR-18174 workaround jstest sandbox

---

docs/ldml/tr35-messageFormat.md

CLDR-18149 v46.1: Pourover of MessageFormat 2.0 Final Candidate

---

docs/ldml/tr35-messageFormat.md
docs/ldml/tr35.md

CLDR-18096
This PR cherry-picks to the maint/maint-46 branch all of the 46.1 changes on the main branch from those in PR [#4232](https://github.com/unicode-org/cldr/pull/4232) through commit https://github.com/unicode-org/cldr/commit/fffac7bc3fd6573e6c874a699af7f9dd6c5c619d on Monday afternoon Dec 9. Those commits on main that are cherry-picked with this PR are:
| Commit | Commit merged | Ticket | Description |
| ------ | ------------- | ------ | ----------- |
| fffac7bc3fd6573e6c874a699af7f9dd6c5c619d | 2024-12-09 14:24 | CLDR-18149 | Update message format spec and test data for 46.1 |
**Note: This should be merged with "Rebase and merge" (temporarily enable in Settings), not the usual "Squash and merge"**

CLDR-18096 BRS 46.1 cherry-pick 46.1 changes from main to maint/maint-46, part 2

---

docs/site/downloads/cldr-46.md

CLDR-18170
This takes the body text from closed PR https://github.com/unicode-org/cldr/pull/4236, but fixes the heading line.

CLDR-18170 BRS v46.1 first pass at release note update

---

.github/workflows/gh-pages.yml

- … implies upload-artifact@v4
CLDR-18179

CLDR-18179 deps: upload-pages-artifact@v3

---

docs/site/cldr-tc/infrastructure-wg.md

Update CLDR Infra group name to CLDR Ops.
CLDR-18210

CLDR-18210 Update CLDR Infra group name

---

.github/workflows/gh-pages.yml

- also update perms
CLDR-18179
Followon from #3670 

CLDR-18179 deps: deploy-pages@v4

---

common/supplemental/languageInfo.xml

CLDR-18198
Update language matching for Afrikaans to English

CLDR-18198 update language matching for Afrikaans 

---

docs/site/downloads/cldr-46.md

CLDR-18170 Update cldr-46.md

---

docs/site/downloads/cldr-46.md

And a few other minor changes in the 46.1 section
CLDR-18170

CLDR-18170 Provide more detailed MF2 changes

---

common/main/hi.xml

CLDR-17809
hi/indian, fix obvious missing y in GyM/M intervalFormat

CLDR-17809 hi/indian, fix missing y in GyM/M intervalFormat

---

CONTRIBUTING.md
LICENSE
common/testData/_readme.txt
common/testData/personNameTest/_header.txt
docs/README.md
docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-messageFormat.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35-personNames.md
docs/ldml/tr35.md
readme.html
tools/cldr-code/src/main/resources/org/unicode/cldr/package.html

CLDR-18231
Fix copyright issues per [CLDR Copyright updates](https://docs.google.com/document/d/1LUAxtI2gEJBYXDf6U3ifyiJMepKuPoA922cBDnrTaLI/edit?tab=t.0#heading=h.ijwarrckvj1t). Some of these were introduced in PR [#4266](https://github.com/unicode-org/cldr/pull/4266) and reverted here, others are older.

CLDR-18231 SBRS 47 Copyright fixes: revert some PR 4266 changes, fix older issues

---

docs/ldml/tr35-dates.md

CLDR-18237 Don't produce "Unknown City Time"

---

common/transforms/byn-Ethi-t-byn-latn-m0-xaleget.xml

CLDR-18226
Back references don't work in reverse.

CLDR-18226 Fix byn-Ethi-t-byn-latn-m0-xaleget transform

---

docs/site/cldr-tc/person-name-wg.md

CLDR-18072 Clean up links in CLDR site; fix person-name-wg.md

---

tools/scripts/ansible/templates/deploy-sh.j2

CLDR-17749
I hot patched this onto smoketest.
Example run: https://github.com/unicode-org/cldr/actions/runs/12914345143/job/36020019892

CLDR-17749 git gc after deploy

---

common/main/de_CH.xml
common/main/yo_BJ.xml
common/subdivisions/ha_NE.xml
common/subdivisions/sr_Latn.xml
common/subdivisions/yo_BJ.xml
common/subdivisions/yue_Hans.xml

CLDR-18265 BRS: regen algorithmics

---

common/supplemental/supplementalData.xml

CLDR-18268
Add timeData for GS in supplementalData

CLDR-18268 Add timeData for GS

---

docs/site/ddl.md

CLDR-18244
Update references to DDL WG

CLDR-18244 Update references to DDL WG

---

docs/site/index/process.md

CLDR-18227
Add definition for stable for consistency with other stages

CLDR-18227 Add definition for stable

---

docs/site/downloads/cldr-47.md

CLDR-18271
Flesh out release notes on collation, RBNF (some), segments, transforms

CLDR-18271 Flesh out release notes on collation, RBNF (some), segments, transforms

---

docs/site/development/cldr-big-red-switch/brs-post-items.md
docs/site/development/cldr-big-red-switch/cldrmodify-passes.md
docs/site/development/cldr-big-red-switch/cldrmodify-using-config-file.md

CLDR-18282
To see the files, navigate to https://XXXX.cldr.pages.dev/development/cldr-big-red-switch, and click on one of the following:
* CLDRModify Passes
* CLDRModify using Config file
* CLDR BRS Post Items

CLDR-18282 Document the CLDRModify passes for BRS

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateTestData.java

CLDR-18128
This PR includes the DateTime test data generation class in `GenerateTestdata.java`, which is the high level runner class that runs all other test data generation tools/classes. This class is invoked as a part of the BRS tasks for a CLDR release.

CLDR-18128 Include DateTime in the test data gen runner used for BRS

---

docs/site/downloads/cldr-47.md

CLDR-18271
- Removed the MF section (that was under Data when it should have been under Spec), and added a reference to that in the Spec section.
- Fixed Fredrik's items
- Bolded all TBDs.

CLDR-18271 Cleanup release note for alpha

---

docs/site/index.md

CLDR-18271
Update news for 47 alpha and remove old news items

CLDR-18271 Update news for 47 alpha

---

.github/workflows/gh-pages.yml
docs/ldml/tr35-messageFormat.md
docs/ldml/tr35.md
tools/scripts/tr-archive/fix-tocs.js
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

(cherry picked from commit c01b350fa06db64bf9ffbfc9512f5daa5c9ae3f7 #4353)
CLDR-18295
- There's also a minor fix to tr35.md that came in with the updated tooling.
- Also needed to cherry-pick #4267 because of action permissions
fyi @aphillips

CLDR-18295 v46 cherry-pick: spec: fixes to MFv2 46.1 spec  (#4353)

---

docs/ldml/tr35-dates.md
docs/ldml/tr35.md
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

- also update ToC reference back to not-dalia repo since https://github.com/not-dalia/gfm-toc/pull/5 was merged
CLDR-18295

CLDR-18295 spec: re-run ToC gen

---

docs/ldml/tr35-keyboards.md
keyboards/dtd/ldmlKeyboard3.dtd
keyboards/dtd/ldmlKeyboard3.xsd

CLDR-18324
- attribute is the same as other parts of CLDR
- this will be used in the CLDR repository proposal
- draft is only on the whole layout- this is similar to transforms, etc.

CLDR-18324 kbd: add <keyboard3 draft=> status to DTD/spec

---

docs/ldml/tr35-messageFormat.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

- Enables a spec to use MessageFormat's linkification
Specs need to include an element with the id 'linkify' to activate
CLDR-18295

CLDR-18295 Add linkify to archive.js

---

docs/site/index/process.md

CLDR-18227 Fix typo

---

docs/ldml/tr35-messageFormat.md

CLDR-18323 
v47 Final pourover including all edits

CLDR-18323 messageformat v47 final pour

---

docs/ldml/tr35.md

CLDR-18054 spec: Document Triple uparrow

---

README.md
docs/ldml/tr35.md
tools/pom.xml

CLDR-18343
- Update tools/pom.xml to latest ICU version
- Update dates in spec and README (also status in the latter)

CLDR-18343 BRS v47 update ICU version, update dates in readme/spec

---

common/dtd/ldmlSupplemental.dtd
common/dtd/ldmlSupplemental.xsd

CLDR-18347 GenerateDTD

---

docs/ldml/tr35.md

CLDR-18340 Add missing items to Modifications

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java

-Nearly all changes recommended/assisted by IntelliJ, including removal of dead code
CLDR-18279

CLDR-18279 Preliminary refactoring of CheckDates.java

---

docs/ldml/tr35.md

CLDR-18340
The way that the 46.1 changes were captured was confusing, so adopted Addison's format of using separate #### sections per topic.

CLDR-18340 Cleanup 46.1 changes in modifications

---

docs/ldml/tr35.md

ToC update for #4414
CLDR-18340

CLDR-18340 spec: ToC for modifications section

---

docs/site/downloads/cldr-47.md
docs/site/index.md

CLDR-18271
Update 47 release notes with latest beta tags

CLDR-18271 Update release notes for 47 beta

---

docs/site/downloads/cldr-47.md

CLDR-18271
Made various updates, including more information about MF2 and expanding the warnings about 48

CLDR-18271 Clean up release note

---

docs/site/downloads/cldr-47.md

CLDR-18271 release note 47 changes

---

.github/dependabot.yml

- add a couple of the keyboard tools explicitly.
CLDR-18356

CLDR-18356 deps v48: update dependabot for v48

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CodeFallback.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java

-New file CodeFallback.java, only public method is CodeFallback.getConstructedItems
-Refactor to remove dead code, fix compiler warnings, assisted by IntelliJ
CLDR-5973

CLDR-5973 Move some code from XMLSource to new class CodeFallback

---

docs/ldml/tr35.md

Fix typos reported in CLDR-17837 and CLDR-17672
CLDR-17837

CLDR-17837 Fix typos

---

.github/COMMIT_METADATA.md

CLDR-13589 v47 fix COMMIT_METADATA

---

.github/dependabot.yml

- other package.json projects were not properly included
CLDR-18356

CLDR-18356 deps v48: revise dependabot to add missing projects

---

docs/site/assets/css/page.css

CLDR-18355 site: css: add margin to sidebar to prevent collisions

---

common/main/en.xml

CLDR-11231 change tkl Tokelauan

---

common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml

I was running generating files and I noticed there were a few places to auto-update Tokelauan. I made this quick PR to do this so it doesn't happen in unrelated PRs.
```
mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags
```
CLDR-11231

CLDR-11231 Update Tokelauan language name in generated files

---

docs/ldml/tr35.md

CLDR-18368 Update links to maint-41 in LDML spec (tr35.md) to maint-47

---

common/main/bew.xml
common/main/en_AU.xml
common/main/eu.xml
common/main/ha_NE.xml
common/main/syr.xml
common/main/tg.xml
common/main/to.xml
common/main/vi.xml
common/main/yo_BJ.xml
common/main/yue_Hans.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java

-New CLDRModify option -fm to remove such values
-Update XML files per modify -fm
-Revise/simplify test checkNullWithInheritanceMark, no more logKnownIssue
CLDR-18309

CLDR-18309 Remove inheritance marker if inherited value is missing

---

.github/workflows/update-jira.yml
tools/scripts/jira-updater/.gitignore
tools/scripts/jira-updater/README.md
tools/scripts/jira-updater/package-lock.json
tools/scripts/jira-updater/package.json
tools/scripts/jira-updater/update-jira.mjs

- add a new workflow and tooling in tools/scripts/jira-updater which will update jira on merge
- document
CLDR-15400
see the linked ticket.

CLDR-15400 workflow: update jira on merge

---

tools/scripts/jira-updater/update-jira.mjs

- per review in #4459 , delete commented-out code for unused emoji
- add a TODO about forks instead of failing the build
CLDR-15400

CLDR-15400 Update update-jira.mjs

---

docs/site/development/cldr-big-red-switch.md

CLDR-18363
- Update links on BRS info page
- Remove obsolete information

CLDR-18363 Update links on BRS info page

---

docs/site/downloads/cldr-47.md

CLDR-18360 More advance warnings

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18389 Update Locales.txt for Airbnb

---

docs/site/downloads/cldr-47.md

- updates to json, keyboard, and supplemental
CLDR-18360

CLDR-18360 v47 download page updates

---

docs/ldml/tr35-dates.md
docs/ldml/tr35.md

CLDR-17497 v47 spec: fix broken links

---

docs/site/development/cldr-big-red-switch.md

CLDR-18391
Add initial batch of filters for easy access with descriptions of their intended use

CLDR-18391 Add initial batch of filters for easy access

---

docs/site/downloads/cldr-48.md
docs/site/sitemap.tsv

CLDR-18392
Create stub release notes page for CLDR 48

CLDR-18392 Create CLDR 48 release notes stub

---

.github/COMMIT_METADATA.md
docs/ldml/tr35-dates.md
docs/ldml/tr35.md
docs/site/downloads/cldr-47.md
tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/README-CHARTS.md

CLDR-18396
Merge relevant fixes from maint/maint-47 back to main; in order:
- a543ab90e69ea0b84a382f36b93c9d1ab6dd9cff, CLDR-17837 Fix typos (#4434), Annemarie Apple, Sat Mar 1 19:16:44 2025 -0800
- 6655d245fead9697e2a49550489977af51e68370, CLDR-13589 v47 fix COMMIT_METADATA (#4444), Steven R. Loomis, Tue Mar 4 11:31:04 2025 -0800
- 50f3b23c4dd1fcb6b49e27f497157863902ded6b, CLDR-18368 Update links to maint-41 in LDML spec (tr35.md) to maint-47 (#4448), Tom Bishop, Tue Mar 4 20:29:02 2025 -0500
- c450f017a9f71a140000ef9bd2eb01dd6be3ab9b, CLDR-10397 Fix languageInfo.xml conversion to json (#4216), Arjan Mels, Wed Mar 5 17:45:01 2025 +0100
- ee1217b4c4a88eef33eae54ff62f795cc8fabb7a, CLDR-16565 v47 BRS: add LICENSE and README.md to charts (#4446), Steven R. Loomis, Wed Mar 5 12:06:05 2025 …

CLDR-18396 SBRS48 merge relevant maint/maint-47 fixes to main

---

.github/dependabot.yml
.github/workflows/update-jira.yml
tools/scripts/jira-updater/.gitignore
tools/scripts/jira-updater/README.md
tools/scripts/jira-updater/package-lock.json
tools/scripts/jira-updater/package.json
tools/scripts/jira-updater/update-jira.mjs

CLDR-18398
backport of CLDR-15400

CLDR-18398 v47: backport jira updater

---

docs/ldml/tr35.md

CLDR-16527 v47: fix broken links in modification section

---

docs/ldml/tr35.md

CLDR-18340 Update mods for 46.1 items

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartUnitConversions.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/FormattedFileWriter.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateKeyboardCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CalculateLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/TempPrintWriter.java

- reinstate (!) calendar preference column in territory info
- don't rewrite include-*.html if they haven't changed
- add a noDiff() option to TempPrintWriter that doesn't show full diffs
- show progress info on GenerateAllCharts
CLDR-18406

CLDR-18406 v47 Chart Improvements

---

.github/workflows/site.yml

- site deploy inadvertently was turned off for push in #4489 
CLDR-18351

CLDR-18351 fix site deploy

---

common/main/en_GB.xml
common/main/root.xml

CLDR-18249 Add diacritics to root exemplar cities

---

common/main/en.xml
common/main/en_001.xml
common/main/en_IN.xml
common/main/root.xml

CLDR-18249 Align Kazakh and Mongolian exemplar city names

---

docs/site/index/survey-tool.md
docs/site/translation.md

CLDR-18360
Update SurveyTool page

CLDR-18360 Update SurveyTool page

---

common/supplemental/supplementalData.xml

CLDR-13688 Correct the first day of week for Iceland from Monday to Sunday

---

common/main/as.xml

CLDR-18415
Revert problematic day period changes until we can research and update the day periods in Assamese. There are most likely more than two.
Incomplete change was made in SurveyTool and imported to vXML in [#3880](https://github.com/unicode-org/cldr/pull/3880/files#diff-1c3cf350695bf6fe089e2ccb08ff03a2718210024d6929e3a4ad78cb14bb5c21L1429)

CLDR-18415 Revert problematic day period changes

---

common/main/en.xml
common/main/xh.xml
docs/ldml/tr35-dates.md

CLDR-18262 Unknown City -> Unknown Location

---

docs/site/assets/css/page.css
docs/site/assets/js/cldrsite.js

- for now, just vectors to google search
CLDR-18154

CLDR-18154 site: add search panel

---

docs/site/development/cldr-big-red-switch.md

CLDR-18391
Add filters on downloads page which need to be updated every release.

CLDR-18391 Add downloads page filters

---

common/main/fi.xml

CLDR-18367
Revert wide formatted Sunday to sunnuntaina

CLDR-18367 Revert wide formatted Sunday

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckExemplars.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-18394
Add structure for person name validation exemplars, plus two other auxiliary sets. 
Includes an refinement of debug printout for units — while unrelated, I'd rather just leave it in because it doesn't affect test status.

CLDR-18394 Person name validiation data

---

tools/cldr-apps/js/src/index.js
tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/QuickCheck.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/TestMetadata.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/TestMisc.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CountItems.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/DiffWithParent.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Misc.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/PivotData.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/VettingAdder.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestBasic.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java

-Use the simple pattern, for (String path : cldrFile), instead of ... Iterator<String> it = cldrFile.iterator(); it.hasNext() ... String path = it.next()
-Changes to CLDRFile.java recommended and assisted by IntelliJ
CLDR-18325

CLDR-18325 Follow-up refactoring of CLDRFile, iteration

---

common/main/en.xml
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/FlexibleDateFromCLDR.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDateOrder.java

CLDR-17942 ISO8601: Fix coverage also

---

tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestMiscWeb.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestShimWeb.java
tools/cldr-code/src/main/java/org/unicode/cldr/draft/RegexRuleTransform.java
tools/cldr-code/src/main/java/org/unicode/cldr/draft/TransformTest.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/TestTransformsICU.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CheckAnnotationSpaceCount.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateISO639Data.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/MiscTools.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestMetadataEquals.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestVettingViewerCategories.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFileMore.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestPathHeaderGregorian.java

-Rename 11 classes as proposed in the ticket
CLDR-17959

CLDR-17959 Rename classes whose names collide

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java

CLDR-17942 fix the test for wrong order

---

docs/site/assets/css/page.css
docs/site/assets/js/cldrsite.js

CLDR-18154
- attempts to search in current page and page titles
- still goes through to Google search if desired
https://github.com/user-attachments/assets/9bc1f93b-4146-4bb4-ab9b-c4a16bcb2341

CLDR-18154 site: attempt to search in current page and page titles

---

common/bcp47/timezone.xml

CLDR-16439 Alias South_Pole to McMurdo

---

common/bcp47/timezone.xml
common/dtd/ldmlBCP47.dtd
docs/ldml/tr35-dates.md
docs/ldml/tr35.md

CLDR-18261 add timezone regions

---

.github/workflows/maven.yml

- lfs is having issues
- skip it for the cldr-archive checkout
CLDR-18467

CLDR-18467 workaround lfs issue by skipping lfs

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAnnotations.java

CLDR-18329
For the known cases (in 8 locales) for which there is a keyword annotation without a tts annotation, re-enable the check failure so vetters will see the error in Survey Tool. (Wondering whether this will also cause a failure in CI tests). Later on during data resolution, if we still have such cases, we will remove the unpaired keyword annotation.

CLDR-18329 For the known cases in which there is keyword entry without tts, re-enable the check failure

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java

-New list FORBIDDEN_VALUES, currently only contains n/a
-New list FORBIDDEN_VALUE_MESSAGE
-New method checkForbiddenValues
-New CheckCLDR.CheckStatus.Subtype.forbiddenValue
CLDR-17179

CLDR-17179 Flag n/a as forbidden value in CheckForExemplars

---

docs/site/development/cldr-big-red-switch.md

CLDR-18391
These are the remaining filters that were in the BRS sheet.

CLDR-18391 Add remaining filters from BRS sheet

---

docs/site/translation.md
docs/site/translation/date-time/date-time-patterns.md

CLDR-18350
This is the vetter instructions site update for the new "relative" date-time combining pattern, corresponding to the structure/data/code updates in PR [#4563](https://github.com/unicode-org/cldr/pull/4563).

CLDR-18350 Add InfoHub instructions for new "relative" variant of the date-time combining pattern

---

tools/cldr-apps/js/src/esm/cldrSurvey.mjs
tools/cldr-apps/js/test/TestCldrSurvey.mjs
tools/cldr-apps/js/test/index.js

CLDR-18475 st: fe tests for cldrSurvey.setLang

---

docs/site/translation.md

CLDR-18463
Clean out 46 notes and update known issues. Then we can add in updates from here.

CLDR-18463 Clean out 46 notes and update known issues

---

tools/cldr-apps/js/src/views/SearchPanel.vue

- even if search results are in a parent locale, don't send the user to a different locale
- we may want to revisit this later.
CLDR-18423

CLDR-18423 search: don't jump locales

---

docs/site/development/cldr-big-red-switch/brs-log-known-issues.md

CLDR-18490 site: minor updates to known issue docs

---

docs/site/translation.md

CLDR-18463
This is just a first pass at updating the top-level InfoHub page for things that vetters need to pay attention to in CLDR 48. It is not complete; , there may be items here that really belong in the subpages (with a link from the top-level page). Unfortunately this week I have no more time to work on this, so I hope others can take over and flesh this out as necessary and make any other updates and corrections (so unless there are serious problems maybe we can just merge this and then someone else can make a new PR for further updates).

CLDR-18463 Update InfoHub for CLDR 48, part 1

---

common/main/bqi.xml
common/main/bqi_IR.xml
common/main/en.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalMetadata.xml

CLDR-18190 Add Bakhtiari

---

.github/workflows/maven.yml

- also put this into a variable, make it a little easier to flip flop
CLDR-18491

CLDR-18491 BRS v48: move to -z BUILD

---

docs/site/translation/number-currency-formats/number-and-currency-patterns.md

CLDR-17570 Update number-and-currency-patterns.md

---

docs/site/translation/displaynames/locale-option-names-key.md

CLDR-16665 Info Hub update for core names

---

docs/site/translation.md

Took a pass through the info hub (rainy day here).
CLDR-18463

CLDR-18463 Update translation.md

---

docs/site/translation.md

CLDR-18463 Add known issue and comment out iso calendar

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/util/JsonUtil.java

- add a toString() serializer
CLDR-18475

CLDR-18475 correct CLDRLocale serialization

---

docs/site/translation.md
docs/site/translation/units/unit-names-and-patterns.md

CLDR-18463
This is actually a rather minor update, I t turns out that most of what I had planned to add had already been added by Mark. I did fix one broken link in the top page and add a brief new section on Concentrations in the unit-names-and-patterns.md page.

CLDR-18463 Update InfoHub: fix link, add Concentrations section

---

common/supplemental/supplementalData.xml

The English name is provided now, so the Q'eqchi' name needs to be updated in auto-generated files.
```
mvn package -DskipTests=true &&  java -jar tools/cldr-code/target/cldr-code.jar ConvertLanguageData &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateLikelySubtags &&  java -jar tools/cldr-code/target/cldr-code.jar GenerateTestData
```
CLDR-18381

CLDR-18381 Update Q'eqchi' name in auto-generated file

---

common/collation/blo.xml

CLDR-16783 add Anii (blo) collation

---

tools/cldr-code/src/test/java/org/unicode/cldr/test/TestEn001Time.java

CLDR-14996 Test for forbidden time formats in en_001

---

tools/cldr-apps/js/src/views/MainHeader.vue

CLDR-18500 add "click here" to CLA notice

---

docs/site/translation.md

CLDR-18463
Update Info Hub based on TC discussion on 23 April. Still pending new language names at basic.

CLDR-18463 Update Info Hub based on TC discussion

---

docs/site/translation.md

CLDR-18463
Update Info Hub for language names and exemplar cities

CLDR-18463 Add exemplar city and language name information

---

docs/site/index.md
docs/site/translation.md

CLDR-18463
Announce start of submission

CLDR-18463 Announce start of submission

---

docs/site/index/survey-tool/cldr-organization.md

CLDR-18410 Create cldr-organization.md

---

common/main/en_LT.xml
common/main/en_LV.xml
common/supplemental/supplementalData.xml

CLDR-18572 Add more European Englishes

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18579 Kazakh
CLDR-18581 Chuvash
CLDR-18582 Mayan
This will be a world of merge conflicts if I do these as separate PRs.

CLDR-18579 org: add Kazakh (CLDR-18579), Chuvash (CLDR-18581), Mayan (CLDR-18582) orgs

---

docs/site/translation.md
docs/site/translation/date-time/date-time-patterns.md

CLDR-18604 site: move Year First (ISO-8601) into subpage

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Joiners.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Splitters.java
tools/cldr-code/src/test/java/org/unicode/cldr/tool/ListProblemDates.java

CLDR-18600
See ticket for more info.

CLDR-18600 Add tool for investigating date-time patterns

---

common/main/en_001.xml

CLDR-18253 Add japanese calendar formats in en_001

---

docs/site/translation.md

CLDR-18616 Clarify the hidden characters

---

docs/site/translation.md

Because browsers match it to the text "new" (which occurs many times on this page!)
CLDR-18616

CLDR-18616 Add to the NEW emoji

---

docs/site/index/cldr-spec/coverage-levels.md

CLDR-14673
- In addition, four other missing links were addressed.

CLDR-14673 updating links

---

common/main/en.xml
docs/site/translation.md
docs/site/translation/core-data/exemplars.md
tools/cldr-code/src/main/java/org/unicode/cldr/util/CodePointEscaper.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/UnicodeSetPrettyPrinterTest.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCodePointEscaper.java

Can be fleshed out later
CLDR-18616

CLDR-18616 Add info on inputing special characters

---

common/main/en.xml

CLDR-18470 fix naming case for PINYIN & WADEGILE variants

---

.github/workflows/site.yml
docs/site/development/development-process/design-proposals.md
docs/site/downloads/cldr-44.md

CLDR-18512 site: use branch and alias url in deploy

---

common/main/mww.xml
common/main/mww_Hmnp.xml
common/main/mww_Hmnp_US.xml
common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population.tsv
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script.tsv

CLDR-15856 add mww Hmong Daw locale

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

- anonymous users don't need a special CLA
- add some logging
CLDR-18605

CLDR-18605 fix for importOldVotes

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java

CLDR-18649 same-as-code is a warning if it matches lowercase English

---

common/annotations/en.xml
common/annotations/root.xml
common/main/en.xml
common/main/en_GE.xml
common/main/en_JP.xml
common/main/pi.xml
common/main/pi_Latn.xml
common/main/pi_Latn_GB.xml
common/main/suz.xml
common/main/suz_Deva.xml
common/main/suz_Deva_NP.xml
common/main/suz_Sunu.xml
common/main/suz_Sunu_NP.xml

CLDR-18656
CLDRModify passes 2025-05-16 after some recent data and locale additions:
- no-modify pass:
- 10 files: fix initial spacing, add newlines as necessary, fix headers as necessary
- annotations/root,en: reorder annotation entries, fix headers
- -fP pass (DAIP etc.)
- pi,suz: reorder/reformat exemplar sets
- en_JP: fix some intervalFormat spaces
**To merge use Rebase and merge**

CLDR-18656 BRS 48 CLDRModify passes 2025-05-16

---

common/supplemental/coverageLevels.xml

CLDR-17391 no localized name for cq

---

docs/site/translation.md

CLDR-18616
Update Info Hub following May 17 push to production
- Add info about new items
- Update known issues

CLDR-18616 Update Info Hub following May 17 push to production

---

tools/cldr-apps/README.md
tools/cldr-apps/docker-compose.yml

- explain how to vnc into the webdriver container
- explain how to run the client (BE) tests
CLDR-14409
with this change you only need maven and docker and a browser, and you can view the UI tests

CLDR-14409 fe test: update docs, add novnc

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java

-Check for null in handleEllipsis
CLDR-18646

CLDR-18646 NullPointerException in ExampleGenerator

---

tools/cldr-apps/js/src/esm/cldrConstants.mjs
tools/cldr-apps/js/src/esm/cldrGui.mjs
tools/cldr-apps/src/main/webapp/css/redesign.css

CLDR-18653 ui: add copyright/tou at bottom

---

tools/cldr-apps/src/test/resources/org/unicode/cldr/web/data/TestSTFactory.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18655
Enable people at Meta to contribute to other locales provisionally at Moderate Level

CLDR-18655 Enable people at Meta to contribute to other locales provisionally at Moderate Level

---

tools/cldr-apps/js/src/views/AutoImport.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java

CLDR-18670 ui: show progress on auto import

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDates.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDateOrder.java

CLDR-18574
The error messages should be much clearer now. It is easiest to review by looking at the test cases in tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDateOrder.java
I left a comment showing the structure.

CLDR-18574 Make error messages clearer for YMD

---

.github/workflows/site.yml

CLDR-18512 site: fix site deploy…again

---

tools/cldr-apps/README.md
tools/scripts/ansible/README.md

CLDR-14409 docs: update to fe build docs

---

common/main/en_CA.xml

CLDR-18678
Remove unnecessary alt-variant

CLDR-18678 Remove unnecessary alt-variant

---

docs/site/translation.md

CLDR-18616 update info hub with more time zone information

---

common/main/en.xml

CLDR-18680 Update Kyrgyz Som

---

common/README.md
common/annotations/README.md
docs/README.md
tools/README.md
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java

-New common/README.md and common/annotations/README.md
-Revise tools/README.md and docs/README.md (only the copyright year for the latter)
-Allow README.md files in TestForStrayFiles
CLDR-15989

CLDR-15989 Add README.md files to the cldr repo

---

tools/cldr-apps/js/src/esm/cldrLocales.mjs

CLDR-18573 Fix notification for unrecognized locale ID

---

common/supplemental/dayPeriods.xml

CLDR-17710
- Add day periods for kok and kok_Latn
- Merge languages with same day periods for readability since the comments don't get updated from the ST.
- Fix error due to the partial addition of the scn day periods in CLDR-17626

CLDR-17710 Add kok and kok_Latn day periods

---

common/main/ko.xml

CLDR-18560 Add short KR name

---

tools/cldr-apps/src/main/webapp/DataExport.jsp

CLDR-18607 Fix DataExport.jsp with renamed method UserRegistry.userIsVetterOrStronger

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SearchManager.java
tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestSearchManager.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestAnnotationUtil.java

- add a new search type looking for cp= (tts)
- fix unit test factory issue
CLDR-18691

CLDR-18691 Search for annotations

---

tools/cldr-apps/js/src/esm/cldrEvent.mjs

- was testing for truthiness of a selector result, need to check length
CLDR-18637

CLDR-18637 st: don't show 'undefined' for rows without examples

---

common/supplemental/attributeValueValidity.xml

CLDR-18627 Add nan so it shows up in comprehensive

---

common/supplemental/plurals.xml

CLDR-18641
- Add one form for kok and kok_Latn for Survey Tool will need to fix rules after push to production

CLDR-18641 Add plural rules for kok and kok_Latn

---

docs/site/translation.md

CLDR-18616 Update info hub with latest known issues

---

docs/site/development/cldr-big-red-switch.md

Add fix in SurveyTool filter to the BRS page
CLDR-18391

CLDR-18391 Add fix in SurveyTool filter

---

docs/site/translation.md

CLDR-18616 Update known issues for 05 June 2025 push to production

---

tools/cldr-apps/js/src/esm/cldrInfo.mjs

-Temporary change to address performance issues, if CLDR_LOCALE_CACHE_MAX increase turns out to be problematic or insufficient
CLDR-18721

CLDR-18721 Disable Regional Variants (sideways) menu

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

CLDR-18683 Remove inclusion of non-existent manage.jsp

---

tools/cldr-apps/js/src/esm/cldrInfo.mjs
tools/cldr-apps/js/src/esm/cldrText.mjs
tools/cldr-apps/js/test/TestCldrText.mjs

-If vr.requiredVotes is 50 or higher, show new message
-Link to https://cldr.unicode.org/translation/getting-started/guide#changing-protected-items
CLDR-18744

CLDR-18744 Revise flagged item message in Survey Tool

---

common/supplemental/ordinals.xml

CLDR-18641 Add kok and kok_Latn ordinals

---

docs/site/requesting_changes.md

Update page to let people know that Components are now mandatory in Jira when filing a new issue
CLDR-18706

CLDR-18706 update component info

---

tools/cldr-apps/js/src/views/MainHeader.vue

CLDR-18223 ui: update heading

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18743 Add Sitelen Pona Organization

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18645 Add Cihan University organization

---

common/supplemental/supplementalData.xml

CLDR-18348 Fix era starts

---

tools/cldr-apps/js/src/esm/cldrInfo.mjs
tools/cldr-apps/js/src/esm/cldrTable.mjs
tools/cldr-apps/js/src/views/MainHeader.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/BallotBox.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

-New cldrInfo.voteCountTypeCell adds hover text to vote count
-Minor refactoring/cleanup/modernization on front end
-Enhance server methods for getting vote overrides to get vote type and date (new class VoteDetails)
-Fix PerUserData setting of VoteType.UNKNOWN per compiler warning
-Fix unrelated warning for explainPhase in MainHeader.vue
-Comments
CLDR-18761

CLDR-18761 Indicate in the Info Panel whether a vote was imported

---

common/main/cv.xml
common/supplemental/ordinals.xml
common/supplemental/plurals.xml

CLDR-17707 plural rules for Chuvash "cv"

---

tools/scripts/llm/README.md

The llm folder contains the CLDR LLM Validator. The README.md document outlines the project’s goals and scope.
CLDR-18745

CLDR-18745 Create LLM folder and Add README for CLDR LLM Validator project

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ClaSignature.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-18774 Add ST organization for Motorola

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/ClaSignature.java

- as MasterWord (corp CLA)
CLDR-18536

CLDR-18536 add mayan_lpp to CLA orgs

---

common/main/mg.xml

CLDR-18175 update mg exemplars

---

common/supplemental/metaZones.xml

CLDR-18787 Add Northern Cyprus to Eastern European Time

---

common/supplemental/metaZones.xml

CLDR-18788 Fix Russian metazones

---

tools/cldr-apps/js/src/views/UploadPanel.vue

- tsv and csv have encoding issues sometimes
CLDR-18711

CLDR-18711 only support .xls/.xlsx for import

---

.github/workflows/maven.yml

CLDR-18850 v48 BRS: FINAL_TESTING

---

common/properties/coverageLevels.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

Now that all of the v48 submissions are in XML, we can see the changes to coverage levels.
CLDR-18430

CLDR-18430 Update coverageLevels post v48 submissions

---

common/main/en_CA.xml

CLDR-18789 Remove en-CA short time zone names

---

tools/scripts/llm/README_llm_cldr_validator.md

CLDR-18745
This is the README file for llm_cldr_validator.py

CLDR-18745 README_llm_cldr_validator.md

---

docs/site/development/updating-codes/update-plurals.md
docs/site/sitemap.tsv

CLDR-18861 Migrate Adding/Fixing Plural and Ordinals page 

---

common/main/th.xml

CLDR-18862 Update th abbreviated days format to match common usage

CLDR-18862 Update th abbreviated days format to match common usage

---

.github/workflows/maven.yml

CLDR-18860 no failure on web driver tests

---

tools/cldr-code/src/main/java/org/unicode/cldr/icu/dev/test/TestFmwk.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-18490
There's one remaining KI that points to CLDR-18462 but I've left that note as review feedback there.

CLDR-18490 v48 final round of known issue updates  for Aug 2025

---

common/supplemental/metaZones.xml

CLDR-18788 Fix more metazone transitions

---

common/main/zh_Hans_MY.xml

CLDR-17183
Change value to confirmed based on evidence in CLDR-17183

CLDR-17183 Confirm MYR value in zh_Hans_MY

---

docs/site/development/generate-algorithmic-locales.md
docs/site/sitemap.tsv

CLDR-18242
Migrate generate-algorithmic-locales.md

CLDR-18242 Migrate generate-algorithmic-locales.md

---

common/main/ja.xml

CLDR-18530
- Change アメリカ to 米国
- Update Mountain time by changing 山地 to 山岳
This is being updated in XML since the vetters were not able to submit new values at the time this was discussed in the Survey Tool

CLDR-18530 Improve Japanese US metazone names

---

docs/site/downloads/cldr-47.md

CLDR-18367
Update CLDR 47 known issues to include revert of long formatted Sunday in Finnish.

CLDR-18367 Update CLDR 47 known issues

---

common/main/xnr.xml

CLDR-18124 Spurious-tag-in-exemplar

---

tools/scripts/llm/ticket_valdator/cldr_ticket_reader.py

CLDR-18745
`feat: comprehensive ticket reader with Phase 1 analysis`
This pull request introduces a new command-line tool, `cldr_ticket_reader.py`, which serves as the primary information gathering and initial analysis tool for Phase 1 of the ticket validation project.
This script connects to the Jira API, extracts a comprehensive set of details from a specified ticket, runs a preliminary rule-based classification, and formats all the information into a single, human-readable report printed to the console.
* **Comprehensive Data Extraction**: The script fetches more than just the title and description. It now collects:
* Priority
* Reporter
* Components
* Labels
* **Connected Work Items** (e.g., "relates to," "blocks," etc.)
* **Phase 1 Classification Engine**: A new function, …

CLDR-18745 cldr_ticket_reader.py

---

tools/scripts/llm/ticket_valdator/cldr_dynamic_prompter.py

CLDR-18745
Introduce a **prompt generator** that prints a concise, LLM-ready prompt for any CLDR JIRA ticket. It calls `get_ticket_details_string` directly (no subprocess) and prints exactly one prompt to stdout.
* `cldr_dynamic_prompter.py` — CLI tool that:
* Imports and uses `get_ticket_details_string` directly.
* Prints a single prompt (Title/Description included once).
* Default **Triage** prompt aligned with Phase-1 criteria (spam / out-of-scope / role routing / stretch validation / Survey Tool “Fix”).
* Optional flags:
* `--category` to force category (Data Accuracy / Documentation Issue / Software Bug / Feature Request).
* `--auto-category` (optional OpenAI key) to pick a category automatically.
* Light topic detection (e.g., Date/Time Patterns, ICU/Integration, Units) to make …

CLDR-18745 cldr_dynamic_prompter.py

---

.github/workflows/maven-release.yml

CLDR-18907 Enable manual trigger on CI workflow for cldr-code snapshots

---

tools/scripts/llm/ticket_valdator/README.md

CLDR-18745 README.md

---

docs/ldml/tr35-modifications.md

CLDR-18857 Add specific location format removal to modifications

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java

CLDR-18144 handle language:menu attribute in JSON

---

common/main/csw.xml

CLDR-18915 Remove alt="ascii" in csw locale data

---

docs/site/index/process.md

Added CLDR process changes to limit impact on ICU
CLDR-18273

CLDR-18273 Added CLDR process for spec changes to limit impact on ICU

---

tools/cldr-apps/js/src/esm/cldrFlagged.mjs
tools/cldr-apps/js/src/esm/cldrVueMap.mjs
tools/cldr-apps/js/src/views/FlaggedItems.vue

-Revise the table layout and content as proposed in the ticket
-Enable downloading as xlsx instead of csv
-Modernize with new FlaggedItems.vue; extensively revise cldrFlagged.mjs
-Fix formatting of VettingParticipation.vue (minor, should have been done in a previous commit for a different ticket)
CLDR-18808

CLDR-18808 Revise Flagged Items

---

common/main/es.xml
common/testData/personNameTest/es.txt
common/testData/personNameTest/km.txt

The alt and plain forms should differ by {surname2}, as pointed out in the ticket. (It doesn't matter which, so just following the medium choice). Look at the ticket for details.
CLDR-17443

CLDR-17443 Fix person-name problem in Spanish

---

keyboards/README.md
tools/scripts/README.md
tools/scripts/llm/README.md

-New tools/scripts/README.md and keyboards/README.md
CLDR-15989

CLDR-15989 Add two more readme files to the cldr repo

---

common/dtd/ldmlSupplemental.dtd
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java

CLDR-18921 Fix attribute order, add test

---

common/annotations/en_001.xml
common/main/en_001.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt

CLDR-18920 Update modify_config.txt for en_001

---

common/main/en_001.xml

Revert one change to the interval formats in en_001 see #5013
CLDR-18920

CLDR-18920 Revert one change to en_001

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

CLDR-18952
Small improvements to the tool to avoid misunderstandings

CLDR-18952 Improve CLDRModify for modify_config 2

---

common/segments/root.xml

CLDR-18917 Unicode 17.0 segmentation rules

---

common/main/sv.xml

CLDR-18924 Update Hawaii_Aleutian in sv

---

docs/site/cldr-tc/conformance_wg.md
docs/site/sitemap.tsv

CLDR-18992 Add info about Conformance Testing WG to site

---

common/annotations/en_001.xml
common/annotations/shn.xml
common/main/de.xml
common/main/scn.xml
common/main/shn.xml

-Changes to 3 files in common/main: de.xml, scn.xml, shn.xml
-Changes to 2 files in common/annotations: en_001.xml, shn.xml
CLDR-18435

CLDR-18435 CLDRModify -fP common/main and common/annotations

---

common/testData/datetime/datetime.json
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDateTimeTestData.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java

CLDR-18370 Use onlyAvailableFormats patterns for skeletons in datetime test data

---

docs/site/downloads/cldr-48.md

CLDR-18940 Further updates to release page

---

docs/site/index.md

CLDR-18940 Alpha news item

---

docs/site/downloads/cldr-48.md

CLDR-18940 Fix typo and punctuation

---

common/main/fr.xml
common/main/sc.xml

CLDR-18369 Remove "incarnation" translations of Amete eras

---

common/main/brx.xml

CLDR-17808 Fix typo in Md interval format in brx

---

common/main/ko.xml

CLDR-10653 Update AU timezone names to be more concise in ko

---

docs/site/downloads/cldr-48.md

CLDR-18392
Add warning about upcoming H24 deprecation in CLDR-18303.

CLDR-18392 Add warning about upcoming H24 deprecation

---

docs/ldml/tr35-general.md

CLDR-18364 Fix unit spec issues

---

docs/ldml/tr35-modifications.md

CLDR-18938 Add message format to spec modifications

---

common/main/en_JP.xml
common/main/gl.xml

CLDR-18901 Fix ConsoleCheck comprehensive errors

---

common/bcp47/calendar.xml
docs/ldml/tr35-dates.md
docs/ldml/tr35.md
docs/site/downloads/cldr-48.md
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java

CLDR-19031, a sub-item of CLDR-18894

CLDR-19031 Add c12, c24 to hour cycle identifier list

---

docs/ldml/tr35-general.md
docs/ldml/tr35-modifications.md
docs/ldml/tr35-numbers.md
docs/site/downloads/cldr-48.md

CLDR-19021 Misc items missing from spec

---

docs/ldml/tr35-modifications.md

CLDR-19021 Spec Modifications page

---

common/transforms/Hebrew-Latin.xml

CLDR-19033 Update to modern link for ICU userguide

---

docs/site/index/downloads.md

CLDR-18405 fix links on downloads page

---

docs/site/downloads/cldr-48.md

CLDR-18940 Update release page

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java

CLDR-19026 ConsoleCheck default to -c comprehensive

---

docs/site/downloads/cldr-48.md
docs/site/index.md

CLDR-18940 Update to release-48-beta2 tags and news item

---

.github/workflows/maven.yml
docs/ldml/tr35-modifications.md
tools/scripts/tr-archive/check-mod-section.sh

CLDR-18209
In the summary area, you will see these:
- Run: https://github.com/unicode-org/cldr/actions/runs/18251384566
Note copy button!
- Run: https://github.com/unicode-org/cldr/actions/runs/18251524590
- Run: https://github.com/unicode-org/cldr/actions/runs/18251557231
Note that it's OK for a change (such as this present PR) to _only_ change the modification section.

CLDR-18209 spec: require modifications section to be updated
