common/supplemental/supplementalMetadata.xml
seed/casing/mus.xml
seed/main/mus.xml
seed/main/mus_US.xml
tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java

[CLDR-11424]
[CLDR-11424]: https://unicode-org.atlassian.net/browse/CLDR-11424

CLDR-11424 Seed data for Muscogee

---

.travis.yml

[CLDR-12038] (I suppose)
- add .travis.yml for automatic building
[CLDR-12038]: https://unicode-org.atlassian.net/browse/CLDR-12038

CLDR-12038 add .travis.yml

---

tools/java/org/unicode/cldr/util/VoteResolver.java

-Use baseline, then inheritance, then alpha
-[CLDR-11385]
[CLDR-11385]: https://unicode-org.atlassian.net/browse/CLDR-11385

CLDR-11385 VoteResolver tie-breaking

---

.gitignore

[CLDR-12038]
Oops. Forgot to migrate this over.
[CLDR-12038]: https://unicode-org.atlassian.net/browse/CLDR-12038

CLDR-12038 add .gitignore from svn

---

common/dtd/ldml.dtd
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java

Add compound unit for foot-pound, etc.

CLDR-11910 add compound unit

---

tools/java/org/unicode/cldr/util/data/Locales.txt

Cleaning up the Microsoft locales list

CLDR-10399 update Microsoft locale list per v36 plan

---

README.md
tools/cldr-unittest/build.xml

[CLDR-13051]
SBRS task S16 change build.xml to -z build + add README.md
[CLDR-13051]: https://unicode-org.atlassian.net/browse/CLDR-13051

CLDR-13051 SBRS build.xml and add README.md

---

seed/main/ff_Adlm.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
tools/java/build.xml
tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java

[CLDR-11533]
- add Myanmar tools to the build path (build failure)
- Update DisplayAndInputProcessor to correct Nyondal
- Update ff_Adlm.xml
[CLDR-11533]: https://unicode-org.atlassian.net/browse/CLDR-11533

CLDR-11533 Update for ADLaM Nyondal U+1E94B

---

specs/ldml/tr35-collation.html
specs/ldml/tr35-dates.html
specs/ldml/tr35-general.html
specs/ldml/tr35-info.html
specs/ldml/tr35-keyboards.html
specs/ldml/tr35-numbers.html
specs/ldml/tr35.html

[CLDR-13054]
Boilerplate for the 7 files of TR35, CLDR version 36 proposed update.
[CLDR-13054]: https://unicode-org.atlassian.net/browse/CLDR-13054

CLDR-13054 TR35 v36 update

---

tools/java/org/unicode/cldr/test/CheckCLDR.java

[CLDR-13064]
CheckCLDR.LIMITED_SUBMISSION should be false for v36 per email from Mark.
[CLDR-13064]: https://unicode-org.atlassian.net/browse/CLDR-13064

CLDR-13064 make CheckCLDR.LIMITED_SUBMISSION false

---

tools/java/org/unicode/cldr/util/Organization.java

Mostly formatting. Minor change to add names to Bangladesh & SIL

CLDR-13061 Add orgs, cleanup enum

---

common/annotations/en.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

Added names as per ESC recommendations. Note that some additional wordsmithing was done, typically to reduce the number of keywords.

CLDR-13067 Fix emoji names/keywords

---

tools/cldr-apps/WebContent/js/survey.js

-Call showInPop from refreshRow2 for immediate refresh
[CLDR-11307]
[CLDR-11307]: https://unicode-org.atlassian.net/browse/CLDR-11307

CLDR-11307 SurveyTool Information panel refresh

---

tools/cldr-apps/WebContent/WEB-INF/tmpl/r_compact.jsp
tools/cldr-apps/WebContent/WEB-INF/tmpl/r_datetime.jsp
tools/cldr-apps/WebContent/WEB-INF/tmpl/r_vetting.jsp
tools/cldr-apps/WebContent/WEB-INF/tmpl/r_zones.jsp
tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/org/unicode/cldr/web/VettingViewerQueue.java

-Remove dead code; clean up; comments

CLDR-13091 Import winning votes use trunk not last-release for winning

---

tools/java/org/unicode/cldr/tool/SearchCLDR.java

CLDR-13091 Identify fields changed between 35.0 and trunk

---

common/supplemental/supplementalMetadata.xml
seed/casing/szl.xml
seed/main/szl.xml
seed/main/szl_PL.xml

[CLDR-13111] 
New locale request for Silesian
[CLDR-13111]: https://unicode-org.atlassian.net/browse/CLDR-13111

CLDR-13111 Seed data for Silesian

---

tools/java/org/unicode/cldr/util/data/Locales.txt

CLDR-13121 Update Google locales

---

tools/java/org/unicode/cldr/util/VettingViewer.java

CLDR-13091 identify changed fields

---

common/annotations/en.xml

CLDR-13112 for U+1F92F add annotation "mind blown"

---

tools/java/org/unicode/cldr/util/LDMLUtilities.java

CLDR-13126 Fixing the build by fixing the return value

---

common/supplemental/supplementalData.xml

CLDR-13050 UG weekend starts (and ends) on Sunday

---

tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java

CLDR-13124 avoid replacing xmlsource in makeVettedSource

---

tools/cldr-apps/docs/stops.html
tools/cldr-apps/docs/stops.txt
tools/cldr-apps/readme.txt
tools/cldr-apps/src/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/org/unicode/cldr/web/DisputePageManager.java
tools/cldr-apps/src/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java

-Use org-specific email return address like cldr-tc-reply-xyz@unicode.org
-Delete references to obsolete CLDR_FROM; delete some dead code
-Require typing the word confirm (LIST_MAILUSER_CONFIRM_CODE) not surveytool@unicode.org
-Make some strings private (LIST_ACTION_SETLEVEL, ..., LIST_MAILUSER_CONFIRM)
-Fix some warnings (unused badCount, static prepareStatementWithArgs)
-Comments

CLDR-10340 Survey Tool email

---

common/supplemental/likelySubtags.xml
common/supplemental/ordinals.xml
common/supplemental/pluralRanges.xml
common/supplemental/plurals.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
seed/casing/an.xml
seed/main/an.xml
seed/main/an_ES.xml
tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt

[CLDR-10963] 
[CLDR-10963]: https://unicode-org.atlassian.net/browse/CLDR-10963

CLDR-10963 Seed data for Aragonese (an)

---

common/supplemental/plurals.xml
common/supplemental/supplementalMetadata.xml
seed/main/su.xml
seed/main/su_Latn.xml
seed/main/su_Latn_ID.xml

CLDR-13108 Add Sundanese data as unconfirmed

---

tools/cldr-apps/WebContent/WEB-INF/tmpl/ajax_status.jsp

- [CLDR-13154]
[CLDR-13154]: https://unicode-org.atlassian.net/browse/CLDR-13154

CLDR-13154 fix feed.png address

---

tools/cldr-apps/src/org/unicode/cldr/web/CookieSession.java

- [CLDR-13140] 
- follow on to [CLDR-5507] in f5262780b999a48220e96639bcee6a0e1ec3a47a !
fyi @hagbard 
[CLDR-13140]: https://unicode-org.atlassian.net/browse/CLDR-13140
[CLDR-5507]: https://unicode-org.atlassian.net/browse/CLDR-5507

CLDR-13140 javax.xml.bind.DatatypeConverter -> java.util.Base64

---

.travis.yml

[CLDR-13183]
[CLDR-13183]: https://unicode-org.atlassian.net/browse/CLDR-13183

CLDR-13183 add ant to fix travis

---

common/main/tk.xml

CLDR-11338 Turkmen Adding in currency narrow symbol an abbreviation

---

tools/java/org/unicode/cldr/util/DtdData.java

[CLDR-13230]
[CLDR-13230]: https://unicode-org.atlassian.net/browse/CLDR-13230

CLDR-13230 Change DtdData to not require the static CLDR_DIR property

---

tools/java/build.xml

[CLDR-13228]: https://unicode-org.atlassian.net/browse/CLDR-13228

CLDR-13228 include new API in cldr.jar

---

tools/java/org/unicode/cldr/test/CheckNew.java
tools/java/org/unicode/cldr/tool/ChartDelta.java
tools/java/org/unicode/cldr/tool/ToolConstants.java
tools/java/org/unicode/cldr/util/FileReaders.java
tools/java/org/unicode/cldr/util/RegexFileParser.java
tools/java/org/unicode/cldr/util/RegexLookup.java
tools/java/org/unicode/cldr/util/With.java

CLDR-13177 fix chart tool

---

common/annotations/en.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-13067 refix emoji fixes

---

tools/cldr-apps/src/org/unicode/cldr/web/XPathTable.java

-Do not create unique_xpath index

CLDR-11823 Fix SQL warnings for Survey Tool database

---

tools/java/org/unicode/cldr/api/CldrDataType.java

Remove unused code discovered after running coverage analysis. Just some legacy stuff hanging around before I understood DTD stuff properly.

CLDR-11049 remove unused code

---

seed/main/osa.xml

- [ x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13190
- [ x ] Updated PR title and link in previous line to include Issue number
See the Jira ticket for the expected data per Craig.

CLDR-13190 Osage Examplar changes per Craig's revisions

---

common/main/bs_Cyrl.xml
common/main/de_CH.xml
common/main/hu.xml
common/main/ia.xml
common/main/ig.xml
common/main/ku.xml
common/main/sw_KE.xml
seed/main/myv.xml
seed/main/osa.xml
seed/main/szl.xml

[CLDR-13243]
Fix various data errors as part of BRS process.  Per committee decision, Interlingua data was reverted to previous release.

CLDR-13243 Fix various data errors

---

common/main/en.xml

- [ x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13193
- [ x ] Updated PR title and link in previous line to include Issue number
Changing the English name Creek per Craig's research. See Jira ticket.

CLDR-13193 Changing the English name Creek

---

tools/cldr-unittest/build.xml

[CLDR-13243]
BRS Task A03: Switch to -z FINAL_TESTING

CLDR-13243 BRS Task A03: Switch to -z FINAL_TESTING

---

.travis.yml

[CLDR-13250]
- add cldr-apps to travis build
[CLDR-13250]: https://unicode-org.atlassian.net/browse/CLDR-13250

CLDR-13250 build cldr-apps in travis

---

common/annotations/hu.xml
common/annotations/sw_KE.xml

- [ x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13242
- [ x ] Updated PR title and link in previous line to include Issue number

CLDR-13242 Emoji collision fix for Hungarian and Swahili_KE

---

tools/java/org/unicode/cldr/tool/ListRedundantUnicodeSets.java

The original was committed here, so continued because the ticket isn't accepted yet (and this is just a tool).

CLDR-13235 This fixes a tool used in assessing exemplars.

---

common/main/hu.xml

CLDR-13256 hu, change minimumGroupingDigits from 4 to 1

---

common/supplemental/windowsZones.xml

CLDR-13029 Update windowsZones.xml to 2019b level

---

tools/java/org/unicode/cldr/tool/GenerateProductionData.java

Note: the tool skips 3 paths; that needs investigation to find out what the right fix is (I'm guessing we need a data fix).
ha Bad bailey value: ↑↑↑, path: //ldml/dates/timeZoneNames/metazone[@type="Mauritius"]/long/generic
yo Bad bailey value: ↑↑↑, path: //ldml/dates/timeZoneNames/metazone[@type="China"]/long/standard
yo Bad bailey value: ↑↑↑, path: //ldml/dates/timeZoneNames/metazone[@type="China"]/long/daylight

CLDR-13240 B restore all logical groups

---

common/main/qu.xml

CLDR-13225 Quechua data issue

---

common/main/ha.xml
common/main/yo.xml
tools/java/org/unicode/cldr/tool/GenerateProductionData.java
tools/java/org/unicode/cldr/util/CLDRFile.java

CLDR-13240 Create tool to generate production files

---

tools/java/org/unicode/cldr/tool/GenerateProductionData.java

Update tool to fix uparrows, and only do sideways inheritance if a switch is set.

CLDR-13240 Update tool to fix arrows, control sideways inheritance

---

common/main/ja.xml
common/main/ps.xml
common/main/sv.xml

Updated the ja and ps to just have standard time. I think that will pass the tests, but we'll see.

CLDR-13259 bogus empty sets

---

tools/java/org/unicode/cldr/tool/GenerateProductionData.java

CLDR-13240 add option to allow/disallow minimizing against root & code-fallback

---

seed/main/cic.xml

- [ x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13191
- [X ] Updated PR title and link in previous line to include Issue number
The data is provided by Craig in the Jira ticket

CLDR-13191 Chickasaw examplar changes 

---

common/subdivisions/be.xml
common/subdivisions/ca.xml
common/subdivisions/ceb.xml
common/subdivisions/es.xml
common/subdivisions/eu.xml
common/subdivisions/fr.xml
common/subdivisions/gl.xml
common/subdivisions/hr.xml
common/subdivisions/id.xml
common/subdivisions/vi.xml

1 commit based of #93
From filed issue: https://unicode-org.atlassian.net/browse/CLDR-13186

CLDR-13186 Subdivisions SE, consistency correction

---

tools/java/org/unicode/cldr/tool/CLDRModify.java

Withdraw the now-dangerous CLDRModify passes.
(Left them as comments for now, but we could remove completely. Let me know what you think.)

CLDR-13240 remove invalid CLDRModify passes

---

ICU-LICENSE
readme.html

CLDR-13243 BRS 36: update readme and licenses

---

common/main/ceb.xml

CLDR-13261 fix autonym for ceb

---

common/supplemental/metaZones.xml

CLDR-13281 Metazone mapping update for tz 2019c

---

tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/java/org/unicode/cldr/tool/CLDRModify.java

CLDR-13235 BRS cldrmodify fixes

---

common/supplemental/likelySubtags.xml
common/supplemental/supplementalMetadata.xml
tools/java/org/unicode/cldr/tool/GenerateMaximalLocales.java

[CLDR-13243]
Run update likely subtags and default content per BRS A18.

CLDR-13243 BRS Task A18 - likelySubtags and default content

---

tools/java/org/unicode/cldr/tool/CompareFilesBetweenReleases2.java
tools/java/org/unicode/cldr/util/LanguageTagParser.java

Couldn't straighten out the other pull request, so redoing.

CLDR-13235 only tool for file compare 

---

specs/ldml/tr35-general.html
specs/ldml/tr35.html

CLDR-11952 Document changes in the Emoji derived name algorithm

---

specs/ldml/tr35.html

CLDR-13269 Typo in UTS#35 P1 S5.6

---

specs/ldml/tr35-general.html

CLDR-13301 update UTS35 with narrow forms

---

specs/ldml/tr35.html

LDML spec misc updates:
- Update date
- Flesh out Modifications section for some material recently updated

CLDR-13243 BRS 36: LDNL spec, Update date, flesh out Modifications

---

readme.html

Update readme to final and to xhtml 4.0, add note with info on svn>git transition, ↑↑↑ and GenerateProductionData, and cldr-staging repo.

CLDR-13243 BRS 36: Update readme to final

---

README.md

[CLDR-13243]
Final update to README.md for release 36.

CLDR-13243 Update README with current release/publish date

---

tools/java/org/unicode/cldr/json/CldrItem.java
tools/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/java/org/unicode/cldr/json/LdmlConvertRules.java

[CLDR-13351]
Updates to JSON utilities necessary in order to build CLDR 36 JSON data.
[CLDR-13351]: https://unicode-org.atlassian.net/browse/CLDR-13351

CLDR-13351 Update JSON utilities for changes in CLDR 36

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAlt.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocale.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/XMLSource.java
tools/java/org/unicode/cldr/util/XPathParts.java

First cut. Not necessary for v36, so only merge once done.

CLDR-8462 add alt inheritance

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/java/org/unicode/cldr/util/ICUServiceBuilder.java

-Clone cached objects before returning them from ICUServiceBuilder
-Call freeze when create UnicodeSet objects beforeCurrencyMatch, etc.
-Add new cache for getRuleBasedCollator
-Add unit test TestExampleGenerator.TestExampleGeneratorConsistency
-Revise TestUnits and TestCompoundUnit to match actual output 1 not 1.00, etc.

CLDR-13375 getExampleHtml should return same output for same inputs

---

readme.html

CLDR-13415 SBRS 37: update readme.html

---

tools/java/libs/icu4j-src.jar
tools/java/libs/icu4j-version.txt
tools/java/libs/icu4j.jar
tools/java/libs/utilities-src.jar
tools/java/libs/utilities.jar

[CLDR-13415]
Update ICU4J
[CLDR-13415]: https://unicode-org.atlassian.net/browse/CLDR-13415

CLDR-13415 SBRS Task S5 Update ICU4J jars to latest

---

common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
tools/build.xml
tools/java/org/unicode/cldr/util/CLDRFile.java

[CLDR-13415]
SBRS
[CLDR-13415]: https://unicode-org.atlassian.net/browse/CLDR-13415

CLDR-13415 SBRS Task S9 - Update DTD and CLDRFile to version 37

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/java/org/unicode/cldr/icu/ldml2icu_locale.txt
tools/java/org/unicode/cldr/test/CheckUnits.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/data/PathDescription.txt
tools/java/org/unicode/cldr/util/data/PathHeader.txt
tools/java/org/unicode/cldr/util/data/Placeholders.txt

CLDR-13058 New compound unit patterns

---

common/annotations/en.xml
common/annotations/root.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAnnotations.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/java/org/unicode/cldr/util/Emoji.java

CLDR-13038 Symbols as new data in CLDR

---

tools/java/org/unicode/cldr/test/CheckDates.java
tools/java/org/unicode/cldr/test/CheckNumbers.java
tools/java/org/unicode/cldr/util/LogicalGrouping.java
tools/java/org/unicode/cldr/util/PatternPlaceholders.java

CLDR-13434 Fix some of the exceptions in Check*

---

common/main/en.xml
common/main/root.xml

CLDR-13058 fix names for square, cubic

---

common/supplemental/coverageLevels.xml
tools/java/org/unicode/cldr/util/XMLSource.java

CLDR-13363 add fa_AF for translation

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/SubmissionLocales.java
tools/java/org/unicode/cldr/util/data/Locales.txt

CLDR-13398 handle new locales and limited submission

---

tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java

CLDR-13057 tweek tests so unit prefixes case sensitive

---

tools/cldr-apps/WebContent/surveyTool/nls/stui.js
tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
tools/java/org/unicode/cldr/test/CheckCLDR.java

-For annotation paths, add an item for root value
-Disallow voting for such items
-Message: The item is a root annotation code

CLDR-11157 show emoji code identifiers

---

common/annotations/en.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

- [ x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-13409
- [ x ] Updated PR title and link in previous line to include Issue number

CLDR-13409 changing "probing" to "white"

---

common/supplemental/metaZones.xml

Corrections for next 3 zones:
- America/Argentina/San_Luis
- Asia/Aqtobe
- Asia/Choibalsan

CLDR-11076 Misc. metazone mapping corrections

---

tools/java/org/unicode/cldr/util/ICUServiceBuilder.java

CLDR-11496 Proper hashCode impl in ICUServiceBuilder

---

common/annotations/en.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-13038 Tweak emoji-test.txt

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java

CLDR-13460 fix prefix collisions

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java

CLDR-13460 fix collations

---

tools/java/org/unicode/cldr/util/VettingViewer.java

-Use getMissingStatus, not oldValue==null, since oldValue is now baseline, not last-release
-This should fix missing Missing (missingCoverage)
-Does not yet fix New (changedOldValue) or English Changed (englishChanged) which may really need last-release value
-Comments

CLDR-13457 Dashboard does not show all Error/Missing/New… values

---

tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java

CLDR-13468 Revert "fix deadlock between STFactory and PerLocaleData"

---

common/annotations/en.xml

CLDR-13360 Fix infinity sign

---

common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalMetadata.xml
seed/main/mai.xml
seed/main/mai_IN.xml

CLDR-13466 Add Maithili to seed

---

tools/java/org/unicode/cldr/util/data/PathDescription.txt

-Edit more URLs to match current existing pages, now all tested

CLDR-13452 Fix broken links in PathDescription.txt

---

tools/java/org/unicode/cldr/util/XMLSource.java

[CLDR-13475]
[CLDR-13475]: https://unicode-org.atlassian.net/browse/CLDR-13475

CLDR-13475 Remove MK variant from fallback codes

---

common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
seed/main/cad.xml
seed/main/cad_US.xml
tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt

Also updated likelySubtags, territoryInfo, defaultContent.

CLDR-13474 Add new seed locale "cad" Caddo

---

tools/java/org/unicode/cldr/util/data/Locales.txt

CLDR-13466 add Maithili to Locales.txt

---

tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java

-Change "Date(last_mod)" to "last_mod" in the "group by" parts of two queries

CLDR-13470 Fix MySQLSyntaxErrorException for WHAT_STATS_BYDAY

---

tools/cldr-apps/WebContent/js/review.js

-Show message in Dashboard, There are no items to review ...
-Also show message in Dashboard, This is a Limited-Submission release ...

CLDR-13478 Dashboard is loading zero items

---

common/main/en.xml
common/main/root.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAll.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/Units.java

CLDR-13479 fix examples for units, add tests

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/grammaticalFeatures.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

This incorporates the material in https://github.com/unicode-org/cldr/pull/206, and makes some adjustments to fix the tests.

CLDR-13253 fix test issues in grammatical features

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/java/org/unicode/cldr/icu/ldml2icu_locale.txt
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/Units.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-13486 Add counts to square and cubic

---

tools/java/org/unicode/cldr/test/CheckForCopy.java

CLDR-13499 disable check for now.

---

tools/java/org/unicode/cldr/test/CheckForCopy.java

CLDR-13499 reenable check (revert 288)

---

tools/java/org/unicode/cldr/test/SubmissionLocales.java

CLDR-4082 allow related characters to be changed

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/java/org/unicode/cldr/test/SubmissionLocales.java

CLDR-4082 fix special paths and tests for limited submission

---

common/supplemental/languageInfo.xml

https://unicode-org.atlassian.net/browse/CLDR-13526

CLDR-13526 languageMatch fallbacks for group script codes

---

common/main/en.xml

CLDR-13557 en, for CV add alt=variant form "Cabo Verde"

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/units.xml
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-13488 add unit conversions

---

tools/cldr-apps/WebContent/js/review.js
tools/cldr-apps/WebContent/js/survey.js

-Move Show-posts button handler into new function updateInfoPanelForumPosts
-Also call updateInfoPanelForumPosts from submitPost
-Check the json refers to the same path as the tr
-Rename two variables to avoid confusion
-Rename to firstPostHolder a variable forumDiv that was not the element with class forumDiv
-Rename to forumDivClone a variable forumDiv that is a clone of tr.forumDiv
-Comments

CLDR-13547 Update browser when a Forum post is added

---

common/supplemental/units.xml
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/UnitConverter.java

Also 
* removed superfluous factor='1', 
* changed test file to use normalized form.
* fixed 3 conversion factors

CLDR-13488 add instrumentation for spec examples, clean up code

---

common/supplemental/units.xml
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/UnitConverter.java

Based on feedback, used a simpler form of PI, getting just enough precision (using continued fractions) to be a bit better than a double value.

CLDR-13488 Make PI simpler

---

tools/java/org/unicode/cldr/util/Organization.java
tools/java/org/unicode/cldr/util/data/Locales.txt

[CLDR-13439]
[CLDR-13439]: https://unicode-org.atlassian.net/browse/CLDR-13439

CLDR-13439 Add Il-Kunsill Nazzjonali tal-Ilsien Malti

---

tools/cldr-apps/WebContent/WEB-INF/tmpl/manage.jsp
tools/cldr-apps/WebContent/js/CldrSurveyVettingLoader.js
tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
tools/cldr-apps/WebContent/js/redesign.js
tools/cldr-apps/WebContent/js/review.js
tools/cldr-apps/WebContent/js/survey.js
tools/cldr-apps/WebContent/xpath-linkify/cldr-xpath-linkify.js

-Reformat and tidy up JavaScript files
-Normalize formatting partly by hand and partly using website beautifier.io
-Wrap some long lines
-Remove unused functions setManageContent, initFeedBack, toggleHeader, showHeader, hideHeader, showReviewMenu, generateHTMLPost
-Replace all dojo.byId with document.getElementById to help encapsulate and modernize dojo
-Bug fix: declare variable k in updateRowOthersCell for use strict
-Remove commented-out code
-Remove antiquated @method comments
-Comments, conform more with javadoc, indicate callers to facilitate future encapsulation

CLDR-11312 Valid HTML

---

seed/main/sa.xml

Files separate issue to add a test for this sort of thing: https://unicode-org.atlassian.net/browse/CLDR-13590

CLDR-13491 sa, add some missing main exemplars present in index exemplars

---

ICU-LICENSE
README.md
readme.html
unicode-license.txt

CLDR-13591 BRS37 Update license copyright dates & readme

---

ICU-LICENSE
README.md
readme.html
unicode-license.txt

In maint/maint-36 branch (for v36.1), update copyright & readme dates.

CLDR-13431 BRS36.1 Update license & readme copyright dates, readme date

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/supplementalData.xml
common/supplemental/units.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/UnitPreferenceSource.txt
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/UnitPreferences.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

Draft proposed usage documentation at https://docs.google.com/document/d/1NbXHVfitfbm0m2c3zftvCYAdLkurwIC5u1W5HHwWYt8/edit?ts=5e47c910#heading=h.jtv8czb49qu2
Note that the unitPreferences are moved into the units.xml file so that the unit conversion and preference is in one place.

CLDR-13489 Enhance the unit preferences

---

common/main/ga.xml
common/main/kkj.xml
common/main/ml.xml
common/main/nb.xml
common/main/or.xml
common/main/pl.xml
common/main/su.xml
common/main/tg.xml
common/main/uk.xml
common/main/ur.xml
common/main/vai_Latn.xml
seed/main/cad.xml
seed/main/gn.xml
tools/cldr-unittest/build.xml

[CLDR-13596]
Switch over to -z FINAL_TESTING for data checks
[CLDR-13596]: https://unicode-org.atlassian.net/browse/CLDR-13596

CLDR-13596 BRS Task A03 - Change to -z FINAL_TESTING

---

common/annotations/en_001.xml

CLDR-13587 push items up from en-GB to en-001

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/units.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/UnitPreferenceSource.txt
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/UnitPreferences.java

Made changed : to -and- to resolve issue in spec working doc (see Open Issues there).
Will use foot-and-inch in place of either foot:inch or foot+inch

CLDR-13488 Make final changes in data, to change colon to AND

---

common/supplemental/units.xml
common/testData/units/unitPreferencesTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/UnitPreferences.java

CLDR-13620 Fix bug in unit preferences data; add test data file

---

common/bcp47/number.xml
common/dtd/ldml.dtd
common/dtd/ldmlSupplemental.dtd
common/main/en.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAttributeValues.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/java/org/unicode/cldr/util/DtdData.java

Made some fixes to the test and DTDs so that the test passes, then turned the warning into an error. Also updated documentation for how to handle failures, and made the test point to that documentation.
See http://cldr.unicode.org/development/testattributevalues
Note that I found and fixed a bug when doing this: "segment" was not a valid bcp47 "nu" value.

CLDR-13049 Fix TestAttributeValues plus data to make it pass.

---

common/supplemental/units.xml
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java

CLDR-13620 Add ofhg and remap millimeter-of-mercury, inch-hg

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/units.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
tools/java/org/unicode/cldr/util/DtdData.java

CLDR-13620 Add draft="contributed" to unitPreferenceData.

---

common/dtd/ldmlSupplemental.dtd
common/validity/unit.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/MatchValue.java

CLDR-13049 Clean up tests to verify that new units are ok.

---

common/validity/currency.xml
common/validity/subdivision.xml
tools/java/org/unicode/cldr/tool/GenerateDayPeriods.java
tools/java/org/unicode/cldr/tool/GenerateValidityXml.java
tools/java/org/unicode/cldr/tool/ToolConstants.java
tools/java/org/unicode/cldr/util/CLDRPaths.java
tools/java/org/unicode/cldr/util/DtdType.java

Includes tool changes to make the file changes in-place, and use the DtdType.xxx.header appropriately.

CLDR-13587 Fix the validity files as per BRS A18.5. 

---

tools/cldr-apps/WebContent/surveyTool/nls/stui.js

-Change string voteInfo_baseline_desc in stui.js

CLDR-13053 Change the tooltip text for Baseline star

---

common/supplemental/units.xml
common/testData/units/unitPreferencesTest.txt
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/ExternalUnitConversionData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/NistUnits.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/data/external/nistBaseUnits.txt
tools/java/org/unicode/cldr/util/data/external/nistConversions.txt
tools/java/org/unicode/cldr/util/data/external/nistDerivedUnits.txt

Adding tests against NIST data

CLDR-13641 fix bugs and test based on external data

---

tools/java/org/unicode/cldr/tool/Chart.java
tools/java/org/unicode/cldr/tool/ChartSubdivisions.java
tools/java/org/unicode/cldr/tool/ChartUnitConversions.java
tools/java/org/unicode/cldr/tool/ChartUnitPreferences.java
tools/java/org/unicode/cldr/tool/GeneratePluralRanges.java
tools/java/org/unicode/cldr/util/DtdType.java

CLDR-13587 Update charts further

---

tools/java/org/unicode/cldr/tool/Chart.java
tools/java/org/unicode/cldr/tool/ChartCollation.java
tools/java/org/unicode/cldr/tool/ChartDelta.java
tools/java/org/unicode/cldr/tool/ChartDtdDelta.java
tools/java/org/unicode/cldr/tool/CompareHanTransliterators.java
tools/java/org/unicode/cldr/tool/FindAttributeValueDifferences.java
tools/java/org/unicode/cldr/tool/GetChanges.java
tools/java/org/unicode/cldr/tool/ShowData.java
tools/java/org/unicode/cldr/tool/ShowLanguages.java
tools/java/org/unicode/cldr/tool/ToolConstants.java
tools/java/org/unicode/cldr/util/CLDRPaths.java
tools/java/org/unicode/cldr/util/VettingViewer.java

CLDR-13587 update chart generation for old versions

---

common/supplemental/languageInfo.xml

https://unicode-org.atlassian.net/browse/CLDR-13650

CLDR-13650 languageMatch Estonian no fallback

---

common/supplemental/units.xml

- Update Swedish road preferences.
- Add "inch" preferences for CA/GB/IN/US person-height below 3 ft.

CLDR-13649 Fix two unit preferences bugs.

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/Rational.java
tools/java/org/unicode/cldr/util/UnitConverter.java

CLDR-13649 Add geq and systems check

---

tools/java/org/unicode/cldr/util/CLDRLocale.java

-Make stringToLoc a ConcurrentHashMap
-Call computeIfAbsent in getInstance, without synchronized
-Remove ulocToLoc
-Simplify getInstance(ULocale u) to call getInstance(u.getBaseName())

CLDR-13334 Improve CLDRLocale performance with computeIfAbsent

---

common/supplemental/units.xml

CLDR-13629 Remove non-simple unit from convertUnit

---

docs/ldml/tr35-collation.html
docs/ldml/tr35-dates.html
docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-keyboards.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

CLDR-13658 brs spec tasks for mark

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/tool/ChartUnitConversions.java
tools/java/org/unicode/cldr/util/Rational.java

Updates the charts to use repeating fractions, which are easier to read than rationals. This is part of the units update but separated here for clarity

CLDR-13657 chart units update

---

docs/ldml/tr35.html

CLDR-13268 Unicode Set issues

---

tools/java/org/unicode/cldr/util/CLDRLocale.java

-Do not get parent CLDRLocale in constructor
-Use lazy initialization for parent, thread-safe double-check, volatile field
-Move code from init into constructor
-Fix compiler warnings for unused parameters
-Remove unused code
-Remove TODO Auto-generated method stub comments
-Comments

CLDR-13661 Do not call computeIfAbsent recursively for CLDRLocale

---

docs/ldml/tr35-general.html
docs/ldml/tr35.html

CLDR-13658 ListPatterns and Modifications cleanup

---

tools/java/org/unicode/cldr/tool/ChartDelta.java
tools/java/org/unicode/cldr/tool/FormattedFileWriter.java
tools/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/java/org/unicode/cldr/tool/ToolConstants.java

CLDR-13657 Fix growth chart

---

tools/java/org/unicode/cldr/tool/ShowLanguages.java
tools/java/org/unicode/cldr/util/data/chart_messages.html

CLDR-11071 Missing explanation of variables in language plural rules

---

tools/java/org/unicode/cldr/tool/ShowData.java

CLDR-13380 Use better anchor in summary chart

---

tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java

-In openQueryByLocaleRW, include locale in SELECT list as well as in WHERE
-In loadVoteValues, adjust numbering for 4 = locale
-Comments

CLDR-13670 NotUpdatable in loadVoteValues

---

tools/SurveyConsole/WebContent/index.html
tools/java/org/unicode/cldr/tool/bytype-index.html
tools/java/org/unicode/cldr/tool/chart-template.html
tools/java/org/unicode/cldr/tool/keyboards-index.html
tools/java/org/unicode/cldr/tool/main-index.html
tools/java/org/unicode/cldr/tool/supplemental.html
tools/java/org/unicode/cldr/tool/verify-index.html
tools/java/org/unicode/cldr/util/data/chart_messages.html
tools/java/org/unicode/cldr/util/data/st_sysmsg.html
tools/java/org/unicode/cldr/util/data/test_help_messages.html

CLDR-13342 Fix chart generation to use https

---

tools/cldr-apps/WebContent/js/CldrStForumFilter.js
tools/cldr-apps/WebContent/js/special/forum.js
tools/cldr-apps/WebContent/js/survey.js
tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java

-Add a filter menu to the forum window
-New file CldrStForumFilter.js with public functions: createMenu, getFilteredThreadIds
-Avoid repeatedly moving DOM elements as was formerly done with insertBefore
-Remove unused code
-Comments

CLDR-13610 Survey Tool Forum Filter

---

common/supplemental/languageInfo.xml

CLDR-13679 for no→nn mapping, remove oneway attibute

---

common/testData/_readme.txt
common/testData/localeIdentifiers/_readme.txt
common/testData/localeIdentifiers/localeDisplayName.txt
common/testData/segmentation/graphemeCluster/_readme.txt
common/testData/units/_readme.txt
common/testData/units/unitPreferencesTest.txt
common/testData/units/unitsTest.txt
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/CldrUtility.java

CLDR-13712 Fix problem in unit preferences test file

---

docs/ldml/tr35-collation.html
docs/ldml/tr35-dates.html
docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-keyboards.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

- Remove Proposed Update, change status to reviewed & approved for publication.
- Remove yellow (class="changed" attributes and any associated spans/divs), remove text marked class="removed"
- Update copyright date
Notes:
- I kept the new relative links for reports.css and logo60s2.gif; will this work for publication?
- There is still one outstanding issue marked with a review note in the Keyboards section: Bad links for Windows keyboard sources. Marking as incomplete until this is addressed, but the rest can be reviewed.

CLDR-13591 Finalize spec for release (remove yellow etc)

---

common/dtd/ldml.dtd
common/dtd/ldmlSupplemental.dtd
common/main/de.xml
common/supplemental/coverageLevels.xml
common/supplemental/grammaticalFeatures.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestSupplementalInfo.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java
tools/java/org/unicode/cldr/test/CheckUnits.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/CldrUtility.java
tools/java/org/unicode/cldr/util/DtdData.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/LogicalGrouping.java
tools/java/org/unicode/cldr/util/StandardCodes.java
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/TimezoneFormatter.java
tools/java/org/unicode/cldr/util/XPathParts.java
tools/java/org/unicode/cldr/util/data/PathDescription.txt
tools/java/org/unicode/cldr/util/data/PathHeader.txt
tools/java/org/unicode/cldr/util/data/Placeholders.txt

CLDR-13756 Add inflection for units

---

common/main/en.xml
common/main/root.xml
common/supplemental/units.xml
common/validity/unit.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java
tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/DtdData.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/Units.java
tools/java/org/unicode/cldr/util/XPathParts.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-13728 Add new units

---

docs/ldml/tr35-collation.html
docs/ldml/tr35-dates.html
docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-keyboards.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

CLDR-13782 Create proposed update TR35 for CLDR 38, revision 60

---

common/annotations/en.xml
common/annotations/root.xml
common/main/root.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/java/org/unicode/cldr/util/Emoji.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

First part of the ticket, add just the label patterns

CLDR-13705 Add character label patterns

---

common/dtd/ldml.dtd
common/supplemental/coverageLevels.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/java/org/unicode/cldr/util/DtdData.java
tools/java/org/unicode/cldr/util/DtdPathIterator.java
tools/java/org/unicode/cldr/util/MatchValue.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-13756 Fix PathHeaders, coverage; extend tests

---

tools/cldr-apps/WebContent/js/review.js

-Fix function name in Dashboard, getForumSummaryHtml not getForumSummaryText

CLDR-13695 Define stages of a forum thread

---

common/main/pl.xml
common/main/ru.xml

CLDR-13756 fix Russian/Polish other should have been many

---

seed/main/en_ZZ.xml
tools/java/org/unicode/cldr/util/XMLSource.java

CLDR-13463 show "ckb" alt=menu/variant forms in ST, provide translation hints

---

common/main/fr.xml
common/main/it.xml
common/main/so.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAll.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckNumbers.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckNumbers.java

CLDR-11045 add back forms and enhance tests

---

tools/java/org/unicode/cldr/util/VettingViewer.java

CLDR-13833 fix miscounts of provisional

---

tools/cldr-unittest/build.xml

CLDR-13849 cldr-unittest/build.xml use -z build not -z final_testing

---

common/main/en.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckUnits.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/LocaleStringProvider.java
tools/java/org/unicode/cldr/util/PathHeader.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/UnitPathType.java

CLDR-13654 units: add consistency examples and checks, and ability to generate compound names to that end.

---

tools/cldr-apps/WebContent/js/CldrStForum.js
tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java

-My changed vote after my Agree post causes Decline auto-post
-My changed vote after my Request post causes Close auto-post
-Auto-post only to open topics
-Comments

CLDR-13831 Auto-post for change of vote

---

tools/cldr-apps/WebContent/numbers.jsp
tools/java/org/unicode/cldr/tool/ChartAnnotations.java
tools/java/org/unicode/cldr/tool/ShowLanguages.java
tools/java/org/unicode/cldr/util/CLDRURLS.java
tools/java/org/unicode/cldr/util/VerifyCompactNumbers.java
tools/java/org/unicode/cldr/util/data/chart_messages.html
tools/java/org/unicode/cldr/util/data/st_sysmsg.html

-Link to http://cldr.unicode.org/index/bug-reports#TOC-Filing-a-Ticket, no parameters

CLDR-13839 Fix Filing-a-Ticket links

---

common/dtd/ldml.dtd
common/main/en.xml
common/main/root.xml

CLDR-13848 add binary SI prefixes

---

tools/java/org/unicode/cldr/tool/ChartDtdDelta.java
tools/java/org/unicode/cldr/tool/ToolConstants.java
tools/java/org/unicode/cldr/util/CLDRPaths.java

and small fix for DtdDelta chart (show ordered elements)

CLDR-11459 fix charts, starting with setting the version and cldr-staging directory, 

---

docs/ldml/tr35.html

Add consideration of scriptAlias to the Locale canonicalization process

CLDR-13760 Canonicalize locale id with scriptAlias

---

README.md

CLDR-13591 Update latest release on README.md

---

common/annotations/en.xml

CLDR-13693 Fix emoji annotation

---

tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js

-Do appendChild(theTable) before, not after, insertRowsIntoTbody, to ensure document.getElementById finds row id

CLDR-13885 Vote counts cumulate when switch coverage

---

common/annotations/en.xml

CLDR-13876 adding names in missing keywords

---

tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java

-Disable forum auto-posting to test; new ENABLE_AUTO_POSTING = false

CLDR-13906 Survey tool response is slow

---

tools/cldr-apps/WebContent/WEB-INF/lib/license-mysql-connector-java-8.0.20.txt
tools/cldr-apps/WebContent/WEB-INF/lib/mysql-connector-java-8.0.20.jar

CLDR-13913 Add mysql connector (and license) to the ST war.

---

tools/cldr-apps/WebContent/js/survey.js

CLDR-9422
~- interim change~
it's a good change now.

CLDR-9422 bring back admin tabs

---

tools/java/org/unicode/cldr/test/CheckForCopy.java

-Return Failure.ok if value is null

CLDR-13904 Fix NullPointerException in sameAsCodeOrEnglish

---

common/supplemental/supplementalMetadata.xml

CLDR-13809 add sgn-* to languageAlias

---

common/main/en.xml

CLDR-13848 fix spelling error in yobi

---

tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java

Note: compare ignoring whitespace, since the Eclipse reformatting fixed spacing.

CLDR-13933 Minor changes to make it easier to get exemplars

---

tools/java/org/unicode/cldr/util/XPathParts.java

- Old cloneAsThawed is an expensive operation as it copies everything over to a mutable structure. New cloneAsThawed makes shallow copy of elements if XPathParts is frozen, and makes an element mutable unless it is necessary.
- Collections.unmodifiableList/unmodifiableMap move to ImmutableList/ImmutableMap

CLDR-13857 shallow copy in cloneAsThawed if instance is frozen

---

tools/java/org/unicode/cldr/test/CheckUnits.java

CLDR-13900 Mistakenly caused the unit tests to be skipped for the current phase

---

common/annotations/en.xml
common/annotations/root.xml
common/supplemental/coverageLevels.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAnnotations.java
tools/java/org/unicode/cldr/util/Emoji.java
tools/java/org/unicode/cldr/util/With.java

CLDR-13882 38 extended symbols are not available

---

common/main/en.xml

CLDR-13941 fix space before dot in long form

---

tools/java/org/unicode/cldr/util/CLDRConfig.java

Optimize CLDRConfig.getCldrBaseDirectory()

CLDR-13857 use singleton to get CLDR directory

---

common/main/de.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckForExemplars.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/PatternPlaceholders.java
tools/java/org/unicode/cldr/util/data/Placeholders.txt

CLDR-13947 Revamp checking for placeholders, add tests

---

common/main/en.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckLogicalGroupings.java
tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/LogicalGrouping.java
tools/java/org/unicode/cldr/util/PathHeader.java

CLDR-13947 investigate checking consistency

---

common/annotations/en.xml
common/annotations/en_AU.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-13966 Change pistol to water pistol; and for AU, gun to water gun

---

tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
tools/cldr-apps/js-unittest/Test.html
tools/cldr-apps/js-unittest/TestCldrStChecksum.js

-New cldrChecksum to see whether row data has changed; skip DOM update if unchanged
-New unit tests for cldrChecksum
-Remove unused valueToItem
-Comments

CLDR-13969 Make ST faster by avoiding needless DOM manipulation

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/java/org/unicode/cldr/test/CheckCLDR.java
tools/java/org/unicode/cldr/test/CheckForExemplars.java
tools/java/org/unicode/cldr/util/data/PathDescription.txt
tools/java/org/unicode/cldr/util/data/Placeholders.txt

CLDR-13979 Fix pointers to infohub

---

tools/java/org/unicode/cldr/util/VettingViewer.java

-Change to http://cldr.unicode.org/translation/getting-started/vetting-view#TOC-Priority-Items

CLDR-13974 Broken link to instructions in Priority Items Summary

---

tools/cldr-apps/WebContent/WEB-INF/tmpl/ajax_status.jsp
tools/cldr-apps/WebContent/js/CldrStCsvFromTable.js
tools/cldr-apps/WebContent/js/CldrSurveyVettingLoader.js
tools/cldr-apps/js-unittest/Test.html
tools/cldr-apps/js-unittest/TestCldrStCsvFromTable.js
tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyForumParticipation.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/org/unicode/cldr/web/UserRegistry.java
tools/java/org/unicode/cldr/util/VettingViewer.java

-New command in gear menu: Forum Participation
-New permission: userCanMonitorForum
-New http request: survey?do=monitorForum
-New file SurveyForumParticipation.java
-New front-end utility CldrStCsvFromTable.js
-Unit tests
-Delete dead code
-Comments

CLDR-13616 Monitor Forum Participation

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java

CLDR-14031 Allow pixel and dot units to collide

---

tools/java/org/unicode/cldr/tool/ChartDelta.java

-Add boolean DO_CHURN to ChartDelta; if true do Churn instead of Delta
-Catch NullPointerException thrown by DtdData.isMetadata
-For now, use a simple list of high-level paths rather than a RegexLookup
-Comments

CLDR-13306 Generate disruptive data churn report

---

tools/cldr-apps/WebContent/js/survey.js

CLDR-9422
- updates to admin panel.
- keeping this as draft if more changes come in.

CLDR-9422 update admin panel to Jira format

---

.github/workflows/ansible-lint.yml
tools/scripts/ansible/.gitignore
tools/scripts/ansible/README.md
tools/scripts/ansible/Vagrantfile
tools/scripts/ansible/ansible.cfg
tools/scripts/ansible/hosts
tools/scripts/ansible/requirements.yml
tools/scripts/ansible/roles.yml
tools/scripts/ansible/setup-playbook.yml
tools/scripts/ansible/templates/cldr-properties.j2
tools/scripts/ansible/templates/context.j2
tools/scripts/ansible/templates/users.j2
tools/scripts/ansible/test-local-vars/local.yml
tools/scripts/ansible/upgrade-playbook.yml
tools/scripts/ansible/vars/main.yml

CLDR-13771
- For now, this targets cldr-ref which is a test machine.
- add a lint step

CLDR-13771 Ansible playbook and docs for setup of Survey Tool.

---

tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestMisc.java

CLDR-13153 fix test parameters
Saw this while testing CLDR-11131

CLDR-13153 fix order of arguments for assertNotNull

---

common/annotations/af.xml
common/annotations/bn.xml
common/annotations/et.xml
common/annotations/eu.xml
common/annotations/hi.xml
common/annotations/ig.xml
common/annotations/ka.xml
common/annotations/kok.xml
common/annotations/ne.xml
common/annotations/ps.xml
common/annotations/pt.xml
common/annotations/root.xml
common/annotations/sd.xml
common/annotations/sl.xml
common/annotations/so.xml
common/annotations/tk.xml
common/annotations/uk.xml
common/annotations/zu.xml
common/dtd/ldml.dtd
common/main/ar_LY.xml
common/main/de.xml
common/main/fil.xml
common/main/fy.xml
common/main/ig.xml
common/main/vi.xml
seed/main/an.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAnnotations.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocalCurrency.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/Annotations.java

CLDR-14060 fix errors from xml

---

tools/cldr-apps/src/org/unicode/cldr/web/OutputFileManager.java

-Skip non-xml files like .DS_Store
-Do not generate en.xml or root.xml
-Log when finished

CLDR-14061 Generate VXML for version 38

---

common/annotations/en_001.xml
common/main/en_001.xml

CLDR-14071 BRS A05.7 fix en 001

---

tools/java/org/unicode/cldr/util/CLDRFile.java
tools/java/org/unicode/cldr/util/SimpleFactory.java
tools/java/org/unicode/cldr/util/XMLNormalizingLoader.java
tools/java/org/unicode/cldr/util/XMLSource.java

- Add a normalized XMLSource cache
- Add a new CLDRFile constructor

CLDR-13857 Add normalized XMLSource cache

---

common/annotations/br.xml
common/annotations/en.xml
common/annotations/qu.xml
common/main/ce.xml
common/main/gd.xml
common/main/ia.xml
common/main/kab.xml
common/main/kea.xml
common/main/pl.xml
common/main/ru.xml
common/main/ti.xml
seed/main/co.xml
seed/main/nqo.xml
seed/main/oc.xml
tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-14060 D fix last errors

---

tools/cldr-unittest/build.xml

CLDR-14059 cldr-unittest/build.xml -z final_testing instead of -z build

---

common/supplemental/supplementalData.xml

This should cause the likely subtags to be correctly generated in a later phase

CLDR-13396 change the usage information for zh in MY

---

common/main/en.xml

CLDR-13720 shorten narrow display names for digital units

---

common/main/hi.xml
common/main/ia.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/tool/ChartDelta.java
tools/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
tools/java/org/unicode/cldr/tool/GenerateSidewaysView.java
tools/java/org/unicode/cldr/tool/SearchCLDR.java
tools/java/org/unicode/cldr/tool/SearchXml.java
tools/java/org/unicode/cldr/tool/ShowLanguages.java
tools/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-14066 update charts

---

common/main/es.xml

CLDR-14082 USD symbool rollback to US$

---

common/main/en_001.xml

CLDR-13847 Adding the . to St for consistency across all English

---

common/annotations/my.xml

-With arg -fp, only my.xml has differences

CLDR-14093 BRS Task A05.5 : CLDRModify pass 3 common/annotations

---

common/collation/br.xml

https://unicode-org.atlassian.net/browse/CLDR-13822

CLDR-13822 Add collation for breton language

---

common/annotations/en.xml

CLDR-13790 Fix high five, and also 13807 and 13863

---

common/main/de.xml
common/main/es.xml
common/main/es_419.xml
common/main/it.xml
common/main/pl.xml
common/main/ru.xml
tools/java/org/unicode/cldr/tool/ChartGrammaticalForms.java

CLDR-13947 fix problems in case

---

common/supplemental/supplementalData.xml

CLDR-13638 fix MM measurement system

---

common/main/yo.xml

CLDR-13622 fix yoruba exemplars

---

README.md

CLDR-13948 Update build status badges in README.md

---

common/supplemental/attributeValueValidity.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
seed/main/kgp.xml
seed/main/kgp_BR.xml
tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt

CLDR-13901 Add Kaingang locale to CLDR

---

tools/java/org/unicode/cldr/util/data/external/UnCodes.txt

CLDR-14116
Update UN Codes for 38 BRS A14

CLDR-14116 38 BRS A14 update UN Codes

---

common/supplemental/units.xml

Add unit preference category `length`, usage `focal-length`

CLDR-13862 Add length preference for usage focal-length

---

readme.html

Updated CLDR readme for v38 alpha.
The license files all seem up to date and do not need updating.

CLDR-14128 update readme for CLDR v38 alpha

---

.github/workflows/ansible-lint.yml
CONTRIBUTING.md

CLDR-13382
Update to #657 with some more comments from @macchiati 
- add a 'lint' step for markdown (informative only, doesn't stop the build, yet)

CLDR-13382 CONTRIBUTING.md: mdlint, review comments

---

common/main/ha.xml
tools/java/org/unicode/cldr/tool/WritePluralRulesSpreadsheets.java

CLDR-14134
- fix Hausa (ha.xml) : add 'ranaku {0}' for plural-other.

CLDR-14134 plural update, also throw a better NPE

---

common/main/fr.xml
common/supplemental/plurals.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestSupplementalInfo.java
tools/java/org/unicode/cldr/util/LogicalGrouping.java

CLDR-12010 add plural operand.

---

common/supplemental/supplementalMetadata.xml
seed/main/la.xml
seed/main/la_VA.xml

CLDR-10102
Classical Roman numbers could only go as far as a million. Here we have had to use Neo-Latin term for billion. Minuta and secunda are Neo-Latin, too. Classical Latin could not measure more precisely than in hours. There is also no word for quarter in the sense used here, so we have used a neologism.

CLDR-10102 Seed latin

---

common/annotations/ha.xml
common/annotations/ig.xml
common/annotations/kl.xml
common/annotations/lb.xml
common/annotations/mi.xml
common/annotations/mt.xml
common/annotations/pa_Arab.xml
common/annotations/rw.xml
common/annotations/tg.xml
common/annotations/ug.xml
common/annotations/wo.xml
common/annotations/xh.xml
common/annotations/yo.xml
seed/annotations/nso.xml
seed/annotations/quc.xml
seed/annotations/tn.xml

CLDR-14055 Add annotations for new locales

---

.github/workflows/production.yml
tools/scripts/ansible/hosts
tools/scripts/ansible/setup-playbook.yml

CLDR-13948
Looks like it works. The scripting could be a little simpler, but the basic deploy to production seems to be functional.
You can compare this to #601 it is very similar code, but with the hostname variables being different.
(It's too similar, and should be refactored, but I'd like to make sure it's working first.)

CLDR-13948 manual push to production

---

common/supplemental/attributeValueValidity.xml
common/supplemental/dayPeriods.xml
common/supplemental/genderList.xml
common/supplemental/grammaticalFeatures.xml
common/supplemental/ordinals.xml
common/supplemental/pluralRanges.xml
common/supplemental/plurals.xml
common/supplemental/supplementalMetadata.xml
seed/casing/lij.xml
seed/collation/lij.xml
seed/main/lij.xml
seed/main/lij_IT.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

- Ran tests as decribed in <http://cldr.unicode.org/development/running-tests>:
- `ant datacheck` passes.
- `ant unittestExhaustive` has no new failures compared to base revision. Detailed results [here](https://gist.github.com/jeanm/1853e8beff6a6646f55eb239fb34b689).

CLDR-13576 Add Ligurian core data

---

common/supplemental/supplementalMetadata.xml

CLDR-14154 fix double variant issue in aliases

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/UnitPathType.java
tools/java/org/unicode/cldr/util/Validity.java

CLDR-14167 Update subdivisions code

---

.github/workflows/ant.yml
tools/cldr-apps/WebContent/cldr-setup.jsp
tools/cldr-apps/WebContent/js/cldr-setup.js
tools/cldr-apps/build.xml
tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-apps/src/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/test-setup.sql

CLDR-8383 
- allow web tests to take a JDBC URL, org.unicode.cldr.unittest.web.jdbcurl
- start mysql in github actions, set it up before test run

CLDR-8383 CI against mysql, disrecommend derby

---

common/main/eu.xml
common/main/gl.xml
common/main/hr.xml

Fix some of the compact format problems. Will clone ticket for further checks in v39

CLDR-14132 fix gl compact forms (plus eu, hr)

---

tools/pom.xml

CLDR-11585
Fixes: https://github.com/unicode-org/cldr/pull/714
Fixes: https://github.com/unicode-org/cldr/pull/713

CLDR-11585 bump dependency versions

---

tools/java/org/unicode/cldr/util/VettingViewer.java

CLDR-8654
- use a ForkJoinPool to parallelize the VV generation
- write to separate Appendable buffers and then join them all at once
- add CLDRConfig.get(String, int default) for fetching numeric config parameters
- DefaultErrorStatus errorStatus was moved into getFileInfo() as it did not
have any long running state, and produced concurrency issues.
parameters:
CLDR_VETTINGVIEWER_CHUNKSIZE=1
- number of locales each thread should process before getting
more work
CLDR_VETTINGVIEWER_PARALLEL=0
- number of threads (0 means 'one per CPU')

CLDR-8654 parallelize VettingViewer - 25-50% speed improvement

---

tools/java/org/unicode/cldr/util/MapComparator.java
tools/java/org/unicode/cldr/util/VettingViewer.java
tools/java/org/unicode/cldr/util/VoteResolver.java

CLDR-8753
Did not measure this, but should cut down on Collator creation in a couple of hot spots.

CLDR-8753 reduce duplicate Collation construction

---

tools/cldr-apps/WebContent/js/special/statistics.js

CLDR-14184
- turn x axis label to reduce crowding
- improve spacing along y axis
- improve wording in legend
update to #719

CLDR-14184 further updates to statistics page

---

docs/ldml/tr35-info.html
docs/ldml/tr35.html

CLDR-14194 define the skeleton in unitPreferences more precisely

---

docs/ldml/tr35.html

CLDR-14016 Revise localeId canonicalization specification

---

docs/ldml/tr35.html

CLDR-13897 EDITORIAL: remove extra "the"

---

.github/workflows/ansible-lint.yml
.github/workflows/maven.yml
.github/workflows/mvn-settings.xml

the maven build is timing out sometimes… let's see if caching will help.

CLDR-11585 cache maven dependencies

---

common/properties/external_data_versions.tsv

CLDR-14162 add first version of file

---

tools/scripts/ansible/README.md
tools/scripts/ansible/Vagrantfile
tools/scripts/ansible/templates/deploy-sh.j2

CLDR-13771
- port forward nginx so we are testing the right server
- document using the same deployment method used in production

CLDR-13771 update README and Vagrantfile

---

tools/java/org/unicode/cldr/util/Organization.java
tools/java/org/unicode/cldr/util/data/Locales.txt

CLDR-13517
add org 'Rodakych' for `pcm`

CLDR-13517 add Organization for Rodakych, LLC (Nigerian Pidgin)

---

tools/scripts/ansible/templates/index.html

-Same for other ST servers like cldr-smoke, using relative url

CLDR-13776 Forward st.unicode.org to st.unicode.org/cldr-apps/v

---

tools/cldr-apps/js-unittest/Test.html

-Change WebContent/js to src/main/webapp/js

CLDR-14211 Fix paths in tools/cldr-apps/js-unittest/Test.html after Maven changes

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/grammaticalFeatures.xml
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDtdData.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/util/GrammarDerivation.java
tools/java/org/unicode/cldr/util/GrammarInfo.java
tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/java/org/unicode/cldr/util/UnitConverter.java
tools/java/org/unicode/cldr/util/data/PathHeader.txt

CLDR-13920 add structure for deriving grammar

---

tools/scripts/ansible/backup-db-playbook.yml
tools/scripts/ansible/hosts
tools/scripts/ansible/redact-db-playbook.yml
tools/scripts/ansible/templates/cldrbackup/fetch_db_sh.j2
tools/scripts/ansible/templates/cldrbackup/redact-db.sql
tools/scripts/ansible/templates/cldrbackup/redact_db_sh.j2

-New redact-db-playbook.yml to set up and perform redaction
-New redact-db.sql, fetch_db_sh.j2 and redact_db_sh.j2

CLDR-14216 Automate ST db redaction for cldr-smoke

---

common/properties/readme.md
common/properties/scriptMetadata.txt
common/properties/segments/readme.txt

Adding copyright to readme's. Also added a readme where necessary.

CLDR-13706 add copyright

---

.github/workflows/ant.yml
tools/scripts/ansible/hosts
tools/st-prom-exporter/README.md

CLDR-13771
- st2 ➡️  st
- cldr-smoke2 ➡️  cldr-smoke

CLDR-13771 update scripts for azure migration

---

.github/workflows/ansible-lint.yml
.github/workflows/commit-checker.yml
tools/scripts/ansible/README.md
tools/scripts/ansible/ccc-playbook.yml
tools/scripts/ansible/hosts
tools/scripts/ansible/redact-db-playbook.yml
tools/scripts/ansible/setup-playbook.yml

CLDR-14205 
- new ansible playbook for commit checker setup
- update ansible-lint task to run all playbooks
- update ansible-lint to lint yaml also
- new workflow commit-checker (manually run)

CLDR-14205 Manual trigger for commit checker

---

docs/ldml/tr35-collation.html
docs/ldml/tr35-dates.html
docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-keyboards.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

Also fixed an unrelated validation err

CLDR-13659 update URLs, mainly switching from http to https

---

docs/ldml/tr35-general.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

CLDR-14194 Add spec for units structure

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAnnotations.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestInheritance.java
tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
tools/java/org/unicode/cldr/tool/PluralMinimalPairs.java
tools/java/org/unicode/cldr/util/CLDRConfig.java
tools/java/org/unicode/cldr/util/CLDRPaths.java
tools/java/org/unicode/cldr/util/SimpleFactory.java

CLDR-13300 fix tests for cldr-staging

---

docs/ldml/tr35-general.html

CLDR-14194 describe compound unit localization

---

docs/ldml/tr35.html

CLDR-14030 fix LDML typo

---

tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleDependencies.java
tools/java/org/unicode/cldr/test/ExampleGenerator.java
tools/java/org/unicode/cldr/util/DayPeriodInfo.java
tools/java/org/unicode/cldr/util/PluralSamples.java

-Check values to avoid throwing uncaught exceptions
-Remove some dead code
-Some changes are due to Eclipse auto-modernizing Java

CLDR-13830 Fix ExampleGenerator exceptions detected by TestExampleDependencies

---

common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt

Update the underlying txt file and rerun the generation programs for likelySubtags and supplementalData. The process is fragile so filed https://unicode-org.atlassian.net/browse/CLDR-14231 for a longer-term fix.

CLDR-13396 Redo the fix for MY & zh, but permanently

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/webapp/DataExport.jsp
tools/cldr-apps/src/main/webapp/js/special/flagged.js
tools/cldr-apps/src/main/webapp/js/survey.js
tools/cldr-apps/src/main/webapp/surveyTool/nls/stui.js

CLDR-13982
- TC only (because it includes emails)
-----
** demo **
- in right panel:
- contents:
```csv
LOCALE,LAST_MOD,ID,ORG,EMAIL,XPATH
jv,2019-01-18 06:21:41,1930,Wikimedia,redacted@example.com,"//ldml/characters/exemplarCharacters[@type=""index""]"
so,2019-01-15 04:12:42,2043,Google,redacted@example.com,"//ldml/characters/exemplarCharacters[@type=""index""]"
```

CLDR-13982 button to download flagged items to CSV

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CalendarSortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/CodeSortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/InterestSort.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MetazoneSortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/NameSort.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/PathHeaderSort.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/java/org/unicode/cldr/test/CheckAttributeValues.java
tools/java/org/unicode/cldr/util/CLDRConfig.java
tools/java/org/unicode/cldr/util/PatternPlaceholders.java
tools/java/org/unicode/cldr/util/SpecialLocales.java
tools/java/org/unicode/cldr/util/StandardCodes.java

CLDR-14180
Multiple classes, notably:
- DBUtils: need special handling for test instances

CLDR-14180 Bill Pugh singletons

---

tools/java/org/unicode/cldr/tool/VerifyConverterResults.java

CLDR-14202 B Simple tool for checking conversions

---

tools/java/org/unicode/cldr/tool/ShowLocaleCoverage.java

CLDR-14066 C Fix coverage charts for ICU

---

docs/ldml/tr35-general.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

Misc spec fixes from review of https://unicode-org.atlassian.net/browse/CLDR-14194: TOC entry update, fix some links and anchors, fix some change spans.

CLDR-14128 spec misc fixes: TOC, links, change spans

---

tools/scripts/ansible/server-playbook.yml

-Set su directive to avoid error, parent directory has insecure permissions
-Also remove copytruncate, and superfluous attributes for create

CLDR-14220 Azure migration: fix log rotation again

---

common/properties/external_data_versions.tsv

CLDR-14162 Updated tzdata date in external data versions file.

---

tools/java/org/unicode/cldr/json/CldrItem.java
tools/java/org/unicode/cldr/json/JSON_config.txt
tools/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/java/org/unicode/cldr/json/LdmlConvertRules.java

CLDR-14175
- also correct missing additional data items
fyi @eemeli  @zbraniecki

CLDR-14175 JSON: threaded conversion, improve coverage

---

tools/cldr-apps/.classpath

CLDR-12002
Fix for eclipse from: move sandbox from und to mul (#757)
- remove stray .classpath

CLDR-12002 fixup tools/cldr-apps/.classpath

---

docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

CLDR-14128 Fix links

---

tools/java/org/unicode/cldr/json/JSON_config_annotations.txt
tools/java/org/unicode/cldr/json/JSON_config_annotationsDerived.txt
tools/java/org/unicode/cldr/json/Ldml2JsonConverter.java
tools/java/org/unicode/cldr/json/LdmlConvertRules.java
tools/java/org/unicode/cldr/util/FileProcessor.java

CLDR-11050
- new packages cldr-annotations-full and cldr-annotations-derived-full
example:
```json
"😀": {
"default": [
"jidħaq ħafna",
"wiċċ",
"wiċċ jidħak ħafna"
],
"tts": [
"wiċċ jidħak ħafna"
]
},
```

CLDR-11050 json: add annotations

---

docs/ldml/tr35-collation.html
docs/ldml/tr35-dates.html
docs/ldml/tr35-general.html
docs/ldml/tr35-info.html
docs/ldml/tr35-keyboards.html
docs/ldml/tr35-numbers.html
docs/ldml/tr35.html

CLDR-14259 Final TR35 for CLDR 38, revision 61

---

tools/cldr-apps/js-unittest/Test.html
tools/cldr-apps/js-unittest/TestCldrStBulkClosePosts.js
tools/cldr-apps/js-unittest/data/bulk_close_posts_json.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyBulkClosePosts.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/main/webapp/js/CldrStBulkClosePosts.js
tools/cldr-apps/src/main/webapp/js/CldrSurveyVettingLoader.js
tools/cldr-apps/src/main/webapp/js/special/bulk_close_posts.js
tools/cldr-apps/src/main/webapp/surveyTool/nls/stui.js
tools/java/org/unicode/cldr/util/XMLSource.java

-New Bulk Close Posts command in gear menu, for Admin only
-New SurveyBulkClosePosts.java
-New CldrStBulkClosePosts.js, special/bulk_close_posts.js
-Move equalsOrInheritsCurrentValue to XMLSource.java
-New method SurveyForum.closeThreads, use also for PostType.CLOSE
-New TestCldrStBulkClosePosts.js, bulk_close_posts_json.js

CLDR-14122 Bulk close some open forum posts

---

tools/java/org/unicode/cldr/tool/ChartDelta.java

-Implement support for more paths, including some in supplementalData
-Catch disruptive-whitespace-only changes, even for paths not explicitly high-level
-New class SuspiciousChange
-Clean-up, comments

CLDR-14098 Generate disruptive data churn report (part3)

---

tools/cldr-apps/src/main/webapp/js/CldrSurveyVettingLoader.js

-Declare msg outside if statement
-Some whitespace changes made by editor

CLDR-14275 Exception while loading: possibleProblems - msg is not defined

---

tools/scripts/ansible/redact-db-playbook.yml
tools/scripts/ansible/server-playbook.yml
tools/scripts/ansible/templates/cldr-properties.j2
tools/scripts/ansible/templates/deploy-sh.j2
tools/scripts/ansible/vars/main.yml

-Encapsulate tomcat vs tomcat8 vs tomcat9, etc.

CLDR-13139 Upgrade Tomcat, preliminary refactoring

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java

- drop the CLDR_SMTP parameter, vector to existing Java params
To enable mail:
- CLDR_SENDMAIL=true
- mail.host (set to your host, or leave blank for 'pretend' mode)
- set CLDR_SMTP_USER / CLDR_SMTP_PASSWORD for authentication
- All other parameters are documented at:
<https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html>
also fixes CLDR-13156

CLDR-8534 support authenticated mail

---

tools/scripts/ansible/cldr-apps-playbook.yml
tools/scripts/ansible/mysql-playbook.yml
tools/scripts/ansible/nginx-playbook.yml
tools/scripts/ansible/server-playbook.yml
tools/scripts/ansible/setup-playbook.yml
tools/scripts/ansible/tomcat-playbook.yml

-Move parts of server-playbook to new playbooks for mysql, nginx, tomcat, cldr-apps

CLDR-13139 Upgrade Tomcat, more preliminary refactoring

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/webapp/WEB-INF/tmpl/ajax_status.jsp
tools/cldr-apps/src/main/webapp/js/CldrSurveyVettingLoader.js
tools/cldr-apps/src/main/webapp/js/special/vetting_participation.js
tools/cldr-apps/src/main/webapp/surveyTool/nls/stui.js
tools/cldr-apps/src/main/webapp/surveytool.css
tools/cldr-apps/src/main/webapp/v.jsp
tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java

CLDR-14268
- major rewrite of 'vetting participation' to a speedy query + new UI (non JSP)
- also fix Utilka CLDR-6320
- also cleanup a leaking Statement from UserRegistry

CLDR-14268 improve vetting participation page

---

.github/workflows/maven.yml
.github/workflows/production.yml

CLDR-14212
- somehow secrets were dropped on an early line
- this may have only worked due to caching before
@pedberg-icu this is what was blocking #848

CLDR-14212 Actions: fix maven workflow

---

tools/pom.xml

CLDR-14297 update ICU4J libs version in tools/pom.xml

---

tools/cldr-apps/pom.xml
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForumParticipation.java
tools/cldr-apps/src/main/resources/org/unicode/cldr/web/sql/cldr-forum-participation.sql
tools/cldr-apps/src/main/webapp/js/CldrStForumParticipation.js
tools/cldr-apps/src/main/webapp/surveyTool/nls/stui.js
tools/pom.xml

CLDR-14308
- over 200x speedup. 3.5 mins to <2s
- improved accuracy, out-of-version posts were miscounted
- added mechanism for loading raw .sql files (such as stored procedures) to avoid messy escaping in Java

CLDR-14308 speedup forum participation

---

common/supplemental/grammaticalFeatures.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java

CLDR-14284 
- also removed a comment on a previously-duplicate grammaticalFeatures element
that was fixed with CLDR-13730

CLDR-14284 TestAttributeValues check for duplicates in space-separated attributes

---

tools/cldr-apps/.settings/org.eclipse.core.resources.prefs
tools/cldr-apps/.settings/org.eclipse.wst.common.component
tools/cldr-rdf/.settings/org.eclipse.core.resources.prefs
tools/cldr-rdf/.settings/org.eclipse.jdt.core.prefs

CLDR-8802
- forgot to checkin the .settings from cldr-rdf
- update another file that changed
go ahead and merge if you want

CLDR-8802 checkin some junk files

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java

-New method TestUtilities.TestMissingStatus
-Delete some dead code
-Comments

CLDR-11771 Add unit test for VettingViewer.getMissingStatus

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRPaths.java

-Clean up formatting of SurveyMain.Phase
-Delete some dead code
-Change some items from public to private
-Comments

CLDR-14057 Preliminary clean-up related to CLDR_PHASE=FINAL_TESTING

---

tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/AbstractCache.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/MapAll.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/QueryClient.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/ScriptMapper.java
tools/cldr-rdf/src/test/java/org/unicode/cldr/rdf/TestMapAll.java

- documented the process here: http://cldr.unicode.org/development/updating-abstracts

CLDR-8802 add test for RDF, and add Scripts support

---

tools/scripts/ansible/templates/context.j2

-In context.xml, add CookieProcessor sameSiteCookies=strict

CLDR-13818 Fix Survey Tool sameSite attribute

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java

-Skip ROOT_ID for CLDRFile.LANGUAGE_NAME in the loop that iterates over sc.getSurveyToolDisplayCodes
-Remove dead code, revise outdated comments

CLDR-13498 Language name Root should not be open for data contribution

---

README.md
common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
readme.html
tools/build.xml
tools/java/org/unicode/cldr/util/CLDRFile.java

Update CLDR version to 38.1 on maint/maint-38-1 branch: readmes, dtds, tools

CLDR-14354 BRS v38.1, update version in readmes, dtds, tools

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/Main.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java

CLDR-13987 more cleanup in Main.java

CLDR-13987 more cleanup in Main.java

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java

-Reuse the already open Connection instead of creating a separate one in XPathTable.setupDB
-Clean up dead code
-Comments

CLDR-14351 XPathTable SQLException: Table definition has changed

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-14314 add Sardware as org for sc.

---

tools/cldr-apps/src/main/webapp/js/CldrDojoTable.js
tools/cldr-apps/src/main/webapp/js/new/cldrTable.js

in support of CLDR-13956,
fix input box for translations to set the correct language
set for both dojo and non-dojo

CLDR-13956 fix input box for translations to set the correct language

---

common/rbnf/ne.xml

CLDR-14177 RBNF for Nepali

---

tools/cldr-apps/js-unittest/Test.html
tools/cldr-apps/js-unittest/TestCldrErrorSubtypes.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/ErrorSubtypes.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/webapp/js/new/cldrErrorSubtypes.js
tools/cldr-apps/src/main/webapp/js/new/cldrGear.js
tools/cldr-apps/src/main/webapp/js/new/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/new/cldrText.js
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java

-Add new WHAT_ERROR_SUBTYPES in SurveyAjax.java
-Replace tc-all-errors.jsp back end with new ErrorSubtypes.java
-Replace tc-all-errors.jsp front end with new cldrErrorSubtypes.js
-Add new unit test TestCldrErrorSubtypes.js
-Fix minor bug in CLDRURLS.toHTML: do not add spaces to URL

CLDR-14396 Modernize Error Subtypes in gear menu

---

tools/cldr-apps/src/main/webapp/css/redesign.css
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/CurrencyMapper.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/MapAll.java

CLDR-8802
- also switch off DEBUG on some of the mappers
note that the xpath binding is only on the currency **name**, perhaps we should use a prefix model so that other items (symbol, count-one, count-many, etc) are also handled.

CLDR-8802 add Currency abstracts

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/BNF.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Pick.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VariableReplacer.java

There are various small changes (at this point) needed to fix the charts. The BNF-related changes are in anticipation. There are a few updates in syntax to old code.

CLDR-14360 chart fixes

---

ICU-LICENSE
README.md
common/dtd/ldml.dtd
common/dtd/ldmlBCP47.dtd
common/dtd/ldmlSupplemental.dtd
keyboards/dtd/ldmlKeyboard.dtd
readme.html
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
unicode-license.txt

SBRS 39:
- Update CLDR version in dtds, CLDRFile
- Update copyright dates in various docs
- Update readme for CLDR 39 development

CLDR-14297 SBRS 39, update readme, CLDR versions, copyrights

---

common/annotations/en.xml

CLDR-13889 correcting then to than

---

common/supplemental/units.xml

CLDR-14379 Remove incorrect baseUnit for torque

---

common/rbnf/fi.xml

CLDR-13146 Add plural Finnish RBNF variants

---

seed/rbnf/vec.xml

CLDR-10920 RBNF for Venetian

---

common/annotations/en.xml

CLDR-14343 remove "accordian" from emoji keyword

---

common/main/zh.xml
common/main/zh_Hant.xml

Update Indochina timezone name in zh & zh_Hant.

CLDR-11744 Change Indochina timezone name in zh

---

common/main/root.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java

CLDR-11645 A Add aliases for identical units

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java

-This bug has been there a while; only occurs during startup

CLDR-14251 Delete excess } in dojo SurveyTool.serveWaitingPage

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/STError.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAPI.java
tools/cldr-apps/src/main/webapp/browse.jsp

- see CLDR-14388
- clean up API definitions
- introduce STError API object

CLDR-14399 change browse.jsp to use API (CLDR-14388)

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/units.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

Note: this is informative information and shouldn't have an effect on ICU.

CLDR-14140 Distinguish metric from non-metric

---

common/supplemental/units.xml

CLDR-14097 Added values to handle road preferences better

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-14232 add deprecated units to the DtdData comparator

---

tools/scripts/ansible/nginx-playbook.yml

- remove unneeded transform from nginx (openapi is not the surveytool)
CLDR-14399
this was the only nit I found so far…

CLDR-14399 minor nginx cleanup

---

common/testData/units/unitPreferencesTest.txt
common/testData/units/unitsTest.txt

CLDR-14232 regenerate unit test data

---

common/main/ar.xml

On lines 10738-10745 and 10756-10763, I updated to the non-localized versions of GB and MB

CLDR-10831 Updated MB GB to non-localized ar

---

common/main/yo.xml

On line 77, removed the second set of parentheses as this is repetitive

CLDR-14280 moved repetitive content in () yo

---

common/main/en.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRUtils.java

commits in the same PR
ALLOW_MANY_COMMITS

CLDR-13890 world

---

common/dtd/ldmlSupplemental.dtd
common/supplemental/grammaticalFeatures.xml
docs/ldml/tr35-general.html

- [*] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-14419
- [*] Updated PR title and link in previous line to include Issue number

CLDR-14419 Add grammatical features for Hungarian, with new cases and their documentation

---

common/annotations/en.xml

CLDR-14342 lower casing lion for Emoji Sea lion

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-14338 migrate LDML spec to markdown

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AboutST.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/ErrorSubtypes.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/RecentActivity.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyBulkClosePosts.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyException.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForumParticipation.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java

CLDR-14399 move SurveyAjax.JSONWriter to SurveyJSONWrapper

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AbstractCacheManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/webapp/js/new/cldrAccount.js
tools/cldr-apps/src/main/webapp/js/new/cldrAdmin.js
tools/cldr-apps/src/main/webapp/js/new/cldrAjax.js
tools/cldr-apps/src/main/webapp/js/new/cldrGear.js
tools/cldr-apps/src/main/webapp/js/new/cldrListUsers.js
tools/cldr-apps/src/main/webapp/js/new/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/new/cldrRecentActivity.js
tools/cldr-apps/src/main/webapp/js/new/cldrSurvey.js
tools/cldr-apps/src/main/webapp/js/new/cldrText.js
tools/cldr-apps/src/main/webapp/js/special/users.js

-Add new UserList.java for back end
-Add new cldrListUsers.js and cldrAccount.js (cf. CLDR-14383) for front end
-Comments

CLDR-14386 Modernize List Users in gear menu

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java

-Change remaining SurveyAjax.JSONWriter to SurveyJSONWrapper
-Change some org.json.JSONWriter to simply JSONWriter

CLDR-14386 Modernize List Users; fix JSONWriter conflict between PR 1000 and 1002

---

common/supplemental/grammaticalFeatures.xml

CLDR-14419 Add grammatical features for Lithuanian and Latvian

---

.github/workflows/ansible-lint.yml

CLDR-14483 Fix ansible lint
picks up a fix for https://github.com/ansible/ansible-lint-action/issues/45

CLDR-14483 Fix ansible lint

---

common/annotations/en.xml

-Changed ordering of annotations in en.xml

CLDR-14491 BRS Task A05.5 : CLDRModify pass 2 -fQ common/annotations

---

common/main/nn.xml

-Changed ordering of exemplarCharacters in nn.xml

CLDR-14491 BRS Task A05.5 : CLDRModify pass 3 -fp common/main

---

common/annotations/gd.xml
common/annotations/my.xml
common/annotations/uk.xml

-Changed U+00B5 MICRO SIGN to U+03BC GREEK SMALL LETTER MU
-Changes involving U+103C MYANMAR CONSONANT SIGN MEDIAL RA

CLDR-14491 BRS Task A05.5 : CLDRModify pass 3 -fp common/annotations

---

seed/main/hi_Latn.xml
seed/main/sc.xml
seed/main/trw.xml

-Changed U+00B5 MICRO SIGN to U+03BC GREEK SMALL LETTER MU

CLDR-14491 BRS Task A05.5 : CLDRModify pass 3 -fp seed/main

---

common/supplemental/windowsZones.xml

This PR reverts three of the mapping changes incorrectly made in #842 ([CLDR-14301](https://unicode-org.atlassian.net/browse/CLDR-14301))

CLDR-14435 Fix mappings for BC cities without DST

---

tools/cldr-apps/src/main/webapp/js/new/cldrAdmin.js

-Call cldrAccount.createUser not (non-existent) cldrAdmin.createUser

CLDR-14251 Modernize: fix small bug in cldrAdmin.js

---

common/transforms/Latin-ASCII.xml

Update Latin-ASCII with 
- 🄐 - 🄩
- more fractions
- 🄁 - 🄊
- ¡, ¿ [per specific request in ticket]
- some arrows

CLDR-13883 update Latin-ASCII with ¡¿, more arrows & fractions, (A-Z), 0-9,

---

common/supplemental/coverageLevels.xml

Modern coverage should include all narrow units

CLDR-11310 modern coverage should include all narrow units

---

common/supplemental/likelySubtags.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LanguageTest.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java

CLDR-14523 fix BRS problems

---

common/annotations/de_CH.xml
common/annotations/sr_Latn.xml
common/annotations/yo_BJ.xml
common/main/ha_NE.xml
common/main/sr_Latn.xml
common/main/yo_BJ.xml

CLDR-14513 algorithmic locales BRS

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/webapp/js/new/cldrGui.js

-Enable running ESM versions of cldr*.js directly in browser
-This depends on first running convertToModule.mjs
-To test, change SurveyTool.USE_ESM to true
-Move onclick from html to js (more needed)

CLDR-14401 Modernize by using ESM (js modules)

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRFileTransformer.java

CLDR-14530 CLDRFileTransformer should call DisplayAndInputProcessor

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js
tools/cldr-apps/src/main/webapp/js/esm/cldrAdmin.js
tools/cldr-apps/src/main/webapp/js/esm/cldrCreateLogin.js

-Fix bug in cldrCreateLogin.js and AdminPanel.java: userlevel menu both number and string
-SurveyMain use UserRegistry.LOCKED instead of hard-coded 999
-Fix bug in cldrAccount: class not id for listMultipleUsers, since two buttons
-Fix bug in cldrAccount: loadHandler check for json.err
-Fix bugs in cldrAccount: allow for undefined json.userPerms and shownUsers
-Fix bug in cldrAdmin: postpone getElementById for admin_u
-Shorten long functions by adding subroutines
-Comments; clean-up

CLDR-14383 Modernize My Account; Admin CreateAndLogin

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-14415 Draft TR35 files for version 39, revision 62

---

common/main/eu.xml
common/main/fr.xml
common/main/ro.xml

CLDR-14533 compoundUnitPattern fixes for French, etc.

---

common/annotations/my.xml
common/annotations/sr_Latn.xml
common/annotations/yo_BJ.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java

-Normalized 3 files
-Deleted dead code from CLDRModify.java

CLDR-14491 BRS§A24.4 rerun CLDRModify: pass 2 -fQ common/annotations

---

common/main/nn.xml

CLDR-14491 BRS§A24.4 rerun CLDRModify: pass 3 -fp common/main

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLanguages.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/EnumComparator.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/main-index.html

Some fixes for the grammar charts also.

CLDR-14468 BRS Regenerate charts

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js

-Hide Download CSV link for My Account (isJustMe), show only for List Users as originally
-Fix Download CSV link for List Users

CLDR-14383 Modernize My Account; download csv

---

common/supplemental/units.xml

CLDR-14515 mixed metric units

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java
tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js
tools/cldr-apps/src/main/webapp/js/esm/cldrForumParticipation.js
tools/cldr-apps/src/main/webapp/js/esm/cldrGear.js
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrVettingParticipation.js

-New cldrVettingParticipation.js
-Copy and adapt old code from js/special/vetting_participation.js
-Revise cldrVettingParticipation.js so it works
-SurveyVettingParticipation.java delete dead code, make some items final/private, reformat
-Add cache-busting extension for bundle and css in SurveyTool.java
-Fix bug when user id is present in votes table, absent from users table; related debugging
-Fix locale und bug in SurveyAjax.listLocalesForImportOldVotes
-Enable some html in cldrAccount.js to pass xml unit test
-Comments

CLDR-14540 Modernize Vetting Participation

---

tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/SummaryRequest.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/SummaryResponse.java

First cut, just get it up and running.

CLDR-14538 Modernize VV

---

common/main/hi.xml

- [x ] Issue filed: https://unicode-org.atlassian.net/browse/CLDR-12003
- [x ] Updated PR title and link in previous line to include Issue number

CLDR-12003 updating translation

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LoginRequest.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LoginResponse.java
tools/cldr-apps/src/main/webapp/admin-usersWithOldVotes.jsp
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java

CLDR-14395
- API for login/logout/info

CLDR-14395 API for Auth endpoints

---

tools/pom.xml

CLDR-14580 BRS task A26.65 update guava

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/index.js
tools/cldr-apps/js/src/views/CldrValue.vue
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js

- added new custom component <cldr-value/> for CLDR value
- some UI cleanup in the Dashboard

CLDR-14389 fix RTL display (modernize Dashboard)

---

seed/casing/oc.xml

Just to have the proper casing for Occitan

CLDR-14561 Casing for Occitan

---

docs/_config.yml

CLDR-14565 add GA for CLDR docs

CLDR-14565 add GA for CLDR docs

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/index.js
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrMenu.js
tools/cldr-apps/src/main/webapp/js/esm/cldrStatus.js

minor improvements from review:
- use chevron instead of +/-
- counts need to be total counts, not header counts
- also handles covlev changes (see below)

CLDR-14389 Dashboard fixes:

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/src/main/webapp/js/esm/cldrAjax.js
tools/cldr-apps/src/main/webapp/js/esm/cldrForumPanel.js
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrRecentActivity.js
tools/cldr-apps/src/main/webapp/js/esm/cldrReportDates.js
tools/cldr-apps/src/main/webapp/js/esm/cldrReportNumbers.js
tools/cldr-apps/src/main/webapp/js/esm/cldrReportZones.js
tools/cldr-apps/src/main/webapp/js/esm/cldrSurvey.js
tools/cldr-apps/src/main/webapp/js/esm/cldrXpathMap.js

-Remove functions clearXhr, queueCount and queueXhr
-Change all queueXhr calls to sendXhr
-Remove calls to clearXhr and queueCount
-Formatting changes by npx prettier
-Comments

CLDR-14590 Modernize Ajax by removing queue

---

tools/cldr-apps/js-unittest/pretty.sh
tools/cldr-apps/js/src/views/AboutPanel.vue
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/js/src/views/LookUp.vue
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/js/src/views/WaitingPanel.vue

-Revise pretty.sh to run npx prettier on all .vue files
-Resulting formatting changes

CLDR-14590 Formatting

---

tools/cldr-apps/js/src/views/LookUp.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Whatis.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/WhatisResponse.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathRequest.java

-Add Whatis.java and WhatisResponse.java, not done yet
-Revise LookUp.vue, not done yet
-Add an example path param for XPathRequest

CLDR-14557 Modernize look up code or xpath (browse); what-is

---

tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js

CLDR-14554 Modernize My Account; prevent user changing own level

---

tools/cldr-apps/js/src/views/DashboardPanel.vue

- scrolling isnt perfect, but approximates

CLDR-14389 make ToC in Dashboard clickable

---

tools/cldr-apps/js/src/views/AboutPanel.vue
tools/cldr-apps/js/src/views/WaitingPanel.vue

- linkify URLs
- link git hashes
minor improvement to waitingpanel
This will close out CLDR-14652

CLDR-14562 Fix About panel

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyFlaggedItems.java
tools/cldr-apps/src/main/webapp/DataExport.jsp
tools/cldr-apps/src/main/webapp/js/esm/cldrFlagged.js
tools/cldr-apps/src/main/webapp/js/esm/cldrGear.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrTable.js
tools/cldr-apps/src/main/webapp/tc-flagged.jsp

-New SurveyFlaggedItems.java, imitating SurveyForumParticipation.java
-New cldrFlagged.js, based on special/flagged.js, modules/usermap.js, and cldrForumParticipation.js
-Remove tc-flagged.jsp; remove part of DataExport.jsp

CLDR-14387 Modernize Flagged Items in gear menu

---

tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/js/src/views/TestPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/InterestSort.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyException.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/About.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/InterestLocales.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/STError.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteRequest.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Whatis.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAPI.java
tools/cldr-apps/src/main/webapp/cldr-setup.jsp
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrText.js

CLDR-14389
@yumaoka if you have any API comments…
Voting and Getrow API

CLDR-14389 Add Voting/GetRow API, test panel

---

docs/ldml/tr35.md

CLDR-14319 remove duplicate example

---

docs/ldml/tr35.md

CLDR-14312 handle canonicalization of subdivision aliases

---

docs/ldml/tr35-general.md

@targets, @locales, and @scope

CLDR-14272 document grammatical attributes

---

docs/ldml/tr35-info.md

Added a general description of @description on units, and unitConstant@description, unitQuantity@description, convertUnit@description, plus some additional values for convertUnit@systems. Did not add grammaticalCase values, since those were added in a previous PR.

CLDR-14579 document changes in DTDs

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/views/AboutPanel.vue
tools/cldr-apps/js/src/views/CldrRow.vue
tools/cldr-apps/js/src/views/CldrRows.vue
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/js/src/views/TestPanel.vue
tools/cldr-apps/js/src/views/UnknownPanel.vue
tools/cldr-apps/js/src/views/VettingSummary.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
tools/cldr-apps/src/main/webapp/js/esm/cldrTable.js

CLDR-14389 Dashboard/Voting UI updates
- move cldrOpts / specialPage out of props,
now available as $cldrOpts / $specialPage to any component.
- make ST resilient in case cldrBundle build goes awry
- first step at a test panel for rows, special 'test_panel'
pre-work for Vetting update, and some other improvements.

CLDR-14389 Dashboard/Voting UI updates

---

docs/ldml/tr35-info.md

Fix the wording for a couple of steps in Unit_Identifier_Normalization

CLDR-14410 Fix wording in Unit_Identifier_Normalization

---

docs/ldml/tr35.md

CLDR-14329 Clearly disallow duplicate variants

---

docs/ldml/tr35-general.md

CLDR-14253 various unit spec improvements

---

docs/ldml/tr35-numbers.md

CLDR-14448 UTS 35 Numbers spec cleanups

---

tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/AboutPanel.vue
tools/cldr-apps/js/src/views/AddUser.vue
tools/cldr-apps/js/src/views/WaitingPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserSettingsData.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUser.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUserRequest.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/OrgList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/UserLevels.java
tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js
tools/cldr-apps/src/main/webapp/js/esm/cldrAjax.js
tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrText.js
tools/cldr-apps/src/main/webapp/surveytool.css
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestUserRegistry.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java

-New AddUser.vue
-New AddUser.java, AddUserRequest.java, OrgList.java, and UserLevels.java
-New TestUserRegistry.TestOrgList; fix Organization.fromString for Pakistan, Utilika
-Fix Vue a-spin warning, type check failed for prop delay: change delay to :delay (but not in CldrRows.vue)
-Fix some warnings for deprecation, etc.
-Remove some USE_DOJO-dependent code
-Comments, clean-up

CLDR-14433 Modernize Add User

---

tools/cldr-apps/js/src/views/CldrRow.vue
tools/cldr-apps/js/src/views/CldrRows.vue
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/js/src/views/TestPanel.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java

CLDR-14389
- updates to experimental test panel
minor updates to Dashboard per review comments:
- status column
- english changed callout
(still need fixed column widths)

CLDR-14389 updates to Dashboard

---

docs/ldml/tr35-general.md
docs/ldml/tr35.md

Clarify Locale Display Name Algorithm per the proposal in the JIRA ticket

CLDR-14490 Refine Locale Display Name Algorithm to handle names for aliased subtags

---

docs/ldml/tr35.md

CLDR-14244 document @alt inheritance

---

docs/ldml/tr35-general.md
docs/ldml/tr35.md

Add section on using delimiter data for linebreak tailoring.

CLDR-14221 Add section on using delimiter data for linebreak tailoring

---

docs/ldml/tr35-general.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

Add notes on considerations for territory and currency display names

CLDR-14209 Add notes on considerations for territory and currency display names

---

docs/ldml/tr35.md

CLDR-14619 LDML BRS

---

docs/ldml/tr35-keyboards.md
keyboards/dtd/ldmlKeyboard.dtd
keyboards/dtd/ldmlPlatform.dtd

CLDR-14518 align keyboard spec and DTD

---

docs/ldml/tr35-keyboards.md

CLDR-13236 fix keyboard <reordering> example

---

tools/cldr-apps/js/src/views/CldrRow.vue
tools/cldr-apps/js/src/views/CldrRows.vue
tools/cldr-apps/js/src/views/DashboardPanel.vue

CLDR-14389
- update dashboard to have a fixed table layout
Sample here:

CLDR-14389 dashboard: basic fixed-table layout

---

docs/ldml/tr35-keyboards.md
keyboards/dtd/ldmlKeyboard.dtd

CLDR-14519 keyboard info element

---

tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/AddUser.vue
tools/cldr-apps/js/src/views/AutoImport.vue
tools/cldr-apps/src/main/webapp/js/esm/cldrEvent.js
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrMenu.js
tools/cldr-apps/src/main/webapp/js/esm/cldrStatus.js
tools/cldr-apps/src/main/webapp/js/esm/cldrText.js

-New AutoImport.vue for new special #auto_import
-Replace cldrLoad.dialogIsOpen with cldrStatus.get/setAutoImportBusy

CLDR-14541 Modernize Auto Import

---

docs/ldml/tr35.md

CLDR-14619 updates to modifications section

---

docs/ldml/tr35-general.md

These are based on https://github.com/unicode-org/cldr/pull/1142

CLDR-14253 Spec improvements: compound unit pattern algorithms

---

tools/cldr-apps/src/main/webapp/js/esm/cldrCreateLogin.js

-Fix bug: change err to json.err

CLDR-14627 Modernize Create-and-Login

---

tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/GearMenu.vue
tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
tools/cldr-apps/src/main/webapp/js/esm/cldrMail.js
tools/cldr-apps/src/main/webapp/js/esm/cldrText.js

-New GearMenu.vue and new special #gear, not attached to navbar yet
-Fix bug in cldrMail.js: myLoad should be cldrLoad.myLoad

CLDR-14615 Modernize by fixing UI glitches

---

common/main/en.xml
common/main/en_GB.xml
common/supplemental/languageInfo.xml
common/supplemental/likelySubtags.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRFileTransformer.java
tools/cldr-code/src/main/resources/org/unicode/cldr/draft/keyboard/windows/windows-locales.csv
tools/cldr-code/src/test/resources/org/unicode/cldr/unittest/data/xmb/en.xml

CLDR-14589 change maori spelling

---

CONTRIBUTING.md
README.md
readme.html

Update readme.html for final, other misc date updates

CLDR-14461 BRS 39, update readme for final, other misc date updates

---

docs/ldml/tr35.md

CLDR-14619 fix html typos

---

docs/ldml/tr35-numbers.md

CLDR-14448 Change editor of tr35-numbers to sffc

---

tools/cldr-apps/js-unittest/TestCldrAccount.js
tools/cldr-apps/js-unittest/TestCldrAdmin.js
tools/cldr-apps/js-unittest/TestCldrBulkClosePosts.js
tools/cldr-apps/js-unittest/TestCldrChecksum.js
tools/cldr-apps/js-unittest/TestCldrCreateLogin.js
tools/cldr-apps/js-unittest/TestCldrCsvFromTable.js
tools/cldr-apps/js-unittest/TestCldrErrorSubtypes.js
tools/cldr-apps/js-unittest/TestCldrForum.js
tools/cldr-apps/js-unittest/TestCldrForumFilter.js
tools/cldr-apps/js-unittest/TestCldrForumParticipation.js
tools/cldr-apps/js-unittest/TestCldrGui.js
tools/cldr-apps/js-unittest/TestCldrListUsers.js
tools/cldr-apps/js-unittest/TestCldrStatus.js
tools/cldr-apps/js-unittest/TestCldrText.js

CLDR-14630 Fix js unit tests: preliminary, fix paths to esm

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/esm/cldrGenericVue.js
tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrStatus.js
tools/cldr-apps/js/src/getCldrOpts.js
tools/cldr-apps/js/src/index.js
tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/js/src/views/MainHeader.vue

CLDR-14395
- add cldrStatus.on for custom event notification
- refactor app creation

CLDR-14395 move login/out button to component

---

tools/cldr-apps/js/src/esm/cldrDom.js
tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrInfo.js
tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java

-Move some Info Panel functions from cldrTable to cldrInfo
-Move appendIcon to cldrDom; called from both cldrTable and cldrInfo
-Update imports and exports as needed
-Fix recently introduced bug in cldrGui: total not const

CLDR-14615 Modernize: move Info Panel code to cldrInfo.js

---

tools/cldr-apps/js/src/esm/cldrCreateLogin.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

CLDR-14395
- Can still login as Admin, or by adding vap= password
- related to CLDR-14433

CLDR-14395 restore testpw to createAndLogin

---

tools/cldr-apps/js/src/esm/cldrAccount.js
tools/cldr-apps/js/src/esm/cldrAjax.js
tools/cldr-apps/js/src/esm/cldrMenu.js
tools/cldr-apps/js/src/esm/cldrOldVotes.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java

-Importing now works again as before; still slow, no progress bar
-Also misc. corrections, clean-up, comments

CLDR-14564 Modernize Import Old Votes in the gear menu

---

tools/cldr-apps/src/main/liberty/config/server.xml

CLDR-13818
- earlier PR #867 fixed this for Tomcat, this is the OpenLiberty version

CLDR-13818 set SameSite=Strict for Cookies

---

tools/cldr-apps/js/test/index.js

-Revise import of TestCldrTest to avoid warning

CLDR-14630 Fix js unit tests

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

This replaces [PR-1187](https://github.com/unicode-org/cldr/pull/1187) which made the same changes but was based on and targeted the wrong branch. This one is based on and targets the maint/maint-39 branch.

CLDR-14416 fix headers, dates, and status blurb for revision 63, cldr v39

---

tools/scripts/tr-archive/.gitignore
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

- see tools/scripts/tr-archive/README.md for instructions

CLDR-14649 archiver for tr35 .md files

---

tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java

- make the logout button a button
- don't leave the SPA when clicking logout
- update WebContext to clear cookies properly

CLDR-14395 login/out button

---

tools/cldr-apps/js/src/views/DashboardPanel.vue

CLDR-14389 set a target= on the dashboard links
@btangmu please drive this one if needed otherwise *close*

CLDR-14389 set a target= on the dashboard links

---

tools/cldr-apps/js/src/esm/cldrEvent.js
tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/views/DashboardPanel.vue
tools/cldr-apps/js/src/views/DashboardWidget.vue
tools/cldr-apps/js/src/views/MainHeader.vue
tools/cldr-apps/js/test/mockup.html
tools/cldr-apps/src/main/webapp/css/redesign.css
tools/cldr-apps/src/main/webapp/surveytool.css

-Partially implemented; new DashboardWidget.vue
-Boolean useWidgetForDashboard in cldrEvent can be false for fullscreen Dashboard
-Many css changes

CLDR-14647 Restore Fix, voting, Info Panel for Modern Dashboard

---

tools/cldr-apps/js/src/esm/cldrCoverage.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrMenu.js
tools/cldr-apps/js/src/esm/cldrSurvey.js
tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/js/src/views/DashboardWidget.vue
tools/cldr-apps/js/src/views/MainHeader.vue

-New cldrCoverage.js with code moved from cldrSurvey.js
-New subroutine getMenusAjaxUrl in cldrMenus.js
-Comments

CLDR-14668 Fix Coverage bugs in modern front end; preliminary refactoring

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

- restructure MailSender code, cleanup, delete dead code
- rollback() if no mail action. Otherwise resources are left to be cleaned up
- turn off DEBUG mode in DBUtils

CLDR-14555 fix SQL warnings

---

tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java

CLDR-14640 cldr-json: don't create empty output dirs

CLDR-14640 cldr-json: don't create empty output dirs

---

tools/cldr-apps/js/src/esm/cldrDash.js
tools/cldr-apps/js/src/views/DashboardWidget.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-Implement checkboxes for hiding items
-Checked items are NOT yet saved/restored from preferences in db
-Move close box to left side of header, away from checkbox
-Fix some bugs in the updating mechanism
-Refactoring and comments

CLDR-14647 Modern Dashboard Widget: hiding; updating

---

tools/cldr-apps/js/src/esm/cldrDash.js
tools/cldr-apps/js/src/views/DashboardWidget.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-Connect checkboxes for hiding items with preferences in back end database
-Restore json.hidden in Dashboard response
-Change the table to store hex xpath id string instead of decimal xpath id integer
-Change the table name from cldr_review_hide_40 to cldr_dash_hide_40
-Comments

CLDR-14647 Modern Dashboard: hiding with preferences

---

.github/pull_request_template.md

CLDR-14662 add a checkbox to the PR template

---

tools/cldr-apps/js/src/views/MainHeader.vue
tools/cldr-apps/js/src/views/MainMenu.vue

-Include triple slash following special names in links
CLDR-14689

CLDR-14689 Fix browser navigation (back button)

---

tools/cldr-apps/js/src/esm/cldrCoverage.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/views/DashboardWidget.vue
tools/cldr-apps/js/src/views/MainHeader.vue

- improve Dashboard widget loading message
- add cldrLoad.getLocaleName() convenience function
- fix a loading issue in cldrLoad
- remove dead code in cldrCoverage
- update cldrCoverage().effectiveName() to take a locale ID
CLDR-14662

CLDR-14662 Coverage Fixes

---

CONTRIBUTING.md
README.md
common/main/fr.xml
common/main/hi.xml
common/supplemental/plurals.xml
common/supplemental/windowsZones.xml
docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md
readme.html
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRUtils.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
tools/pom.xml
tools/scripts/tr-archive/.gitignore
tools/scripts/tr-archive/README.md
tools/scripts/tr-archive/archive.js
tools/scripts/tr-archive/make-tr-archive.sh
tools/scripts/tr-archive/package-lock.json
tools/scripts/tr-archive/package.json

CLDR-14696
This merges the current CLDR maint/maint-39 branch into master, using the "Hard Way" procedure at
http://site.icu-project.org/repository/gitdev#TOC-Merging-from-Maint-to-Main-BRS-Task-
// Allow commits with mixed issue tags
// Allow multiple commits in the same PR

CLDR-14696 Merge branch 'maint/maint-39' into master (via branch on fork)

---

tools/cldr-apps/js/src/esm/cldrDash.js
tools/cldr-apps/js/src/views/DashboardWidget.vue

CLDR-14647 Modern Dashboard: highlight last-clicked row

---

tools/cldr-apps/js/src/views/DashboardWidget.vue

CLDR-14647 Modern Dashboard: fix fetch error handling

---

common/supplemental/windowsZones.xml

CLDR-14653 Add windows zone mapping for South Sudan (Juba)

---

tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

- fix typo in cldrGui
- we want to hide getInterestLocales() from JSON,
as CLDRLocales aren't serializable (they are recursive)
CLDR-14395

CLDR-14395 step to improve login issue

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java

CLDR-14395 add a session cookie

---

tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LoginResponse.java

CLDR-14395 login flow fixes
- remove s= from vurl() and from cldrGui
- fix login button
broke when 'user' was no longer in the LoginResponse
- Add a TODO to LoginResponse to handle this

CLDR-14395 more login flow fixes

---

tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRCacheDir.java
tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AbstractCacheManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/PermanentVote.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyLog.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyProgressManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyThreadManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
tools/cldr-apps/src/main/liberty/config/server.xml
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/AbstractCache.java

CLDR-14675
- use java.util.logging where possible
- deprecate many SurveyLog functions
- add in commented out code for adding webContext extensions to logging
- bump default logging settings to 10*50MB = 500MB of logs (up from 60MB total)

CLDR-14675 improve logging

---

tools/cldr-apps/js/src/esm/cldrStatus.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

-Remove dead code from UserRegistry.java
-Fix the comment for phase in cldrStatus.js
CLDR-13543

CLDR-13543 Vetting mode permissions: remove dead code; comment

---

tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LoginResponse.java

- re-add 'user' to LoginResponse, as just a boolean
- remove  dead code in LoginButton.vue
CLDR-14395

CLDR-14395 login update per PR

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java

CLDR-14555
No, want to update logging still

CLDR-14555 fix db open in forum

---

common/main/en.xml
common/main/root.xml
common/validity/unit.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-14504 Add kWh-per-100km

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java

CLDR-14555 addXpaths needs to not use autocommit conn

CLDR-14555 addXpaths needs to not use autocommit conn

---

.github/workflows/maven.yml
.github/workflows/production.yml
tools/scripts/ansible/README.md
tools/scripts/ansible/nginx-playbook.yml

- remove comments about tomcat from readme and comments
- update production.yml to match maven.yml for tomcat deploy
CLDR-14747

CLDR-14747 Update push to production

---

tools/cldr-apps/README.md
tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRCacheDir.java
tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AbstractCacheManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/CookieSession.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/PermanentVote.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SortMode.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyLog.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyProgressManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyThreadManager.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
tools/cldr-apps/src/main/liberty/config/server.xml
tools/cldr-apps/src/main/webapp/WEB-INF/tmpl/st_footer.jsp
tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAll.java
tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/AbstractCache.java

- add a mechanism for controlling log levels.
This is in incubation, and will be expanded on in CLDR-8581
- improve (denoise) logging in MailSender and others
- add some interim logging docs
CLDR-14675

CLDR-14675 ST: improve logging

---

tools/cldr-apps/README.md
tools/cldr-apps/src/main/java/org/unicode/cldr/web/AdminPanel.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

- avoid hang for some codepaths
- add docs for testing with mailhog
- fix bug in Create&Login where emails had spaces
- change C&L names to Greenlandic
CLDR-14555

CLDR-14555 Rewrite MailSender

---

.github/workflows/maven.yml

CLDR-14755 bump memory for consolecheck

---

tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LogicalGrouping.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

CLDR-14755 enable locales for grammar collection

CLDR-14755 enable locales for grammar collection

---

docs/ldml/tr35-collation.md
docs/ldml/tr35-dates.md
docs/ldml/tr35-general.md
docs/ldml/tr35-info.md
docs/ldml/tr35-keyboards.md
docs/ldml/tr35-numbers.md
docs/ldml/tr35.md

CLDR-14756 Draft TR35 files for version 40, revision 64

---

common/supplemental/languageGroup.xml
common/supplemental/ordinals.xml
common/supplemental/plurals.xml
common/supplemental/supplementalMetadata.xml
seed/casing/tpi.xml
seed/main/tpi.xml
seed/main/tpi_PG.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-14610
- [ X ] This PR completes the ticket.

CLDR-14610 add Tok Pisin (tpi) to seed

---

docs/ldml/tr35-keyboards.md

CLDR-14584 keyboard elements structure

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrTable.js
tools/cldr-apps/js/src/esm/cldrXpathUtils.js
tools/cldr-apps/js/test/nonbrowser/test-cldrXpathUtils.js
tools/cldr-apps/js/test/pretty.sh

CLDR-14762 update cldrTable for grammatical units
- some XPaths were missed from this function when added
to CLDRFile extra paths

CLDR-14762 update cldrTable for grammatical units

---

common/supplemental/coverageLevels.xml
common/supplemental/grammaticalFeatures.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/LogicalGrouping.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-14772
This is the first fix, for shakedown. There will be additional PRs to generalize the check for superfluous plural values.

CLDR-14772 suppress French many

---

tools/cldr-apps/js/src/esm/cldrForum.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java

-Implement the rule on both front and back ends
-Fix deprecation warnings for SurveyLog.logException
-Comments
CLDR-14290

CLDR-14290 ST forum change: Only TC members can initiate a Discuss

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/LocaleNormalizer.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

-Refactoring preliminary to implementation of warning for locales not covered by org
-Move a lot of code from UserRegistry to LocaleNormalizer for encapsulation
-Fix deprecation and other warnings
-Comments
CLDR-14597

CLDR-14597 Restrict organizations to specified locales; refactoring

---

tools/cldr-apps/js/src/esm/cldrAccount.js

-Fix the UploadXML link in List Users
-Still not modernized, but works as non-SPA with .jsp
-Also hide some List Users menu items from users that lack permissions
CLDR-14385

CLDR-14385 XML Upload in gear menu

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/esm/cldrAccount.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/TransferVotes.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

- manager+ only
- reinstate an old feature
CLDR-14787
demo movie [here 🎦 ](https://drive.google.com/file/d/1PA_sdC7upQx9SbpTLakkSK73D73rrmJr/view?usp=sharing)

CLDR-14787 add a Transfer Votes option to user list

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java

CLDR-14797
See the discussion in the ticket.

CLDR-14797 Make most aliased items show as Missing in ST

---

tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrRetry.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/src/main/webapp/surveytool.css

CLDR-14718
Improve err message when navigating to an xpath that is not visible. (the old message did not mention the actual XPath in question, and removed it from the URL)

CLDR-14718 improve message when clicking a hidden xpath

---

keyboards/windows/sat-t-k0-windows.xml

CLDR-14586 sat-Olck-t-k0 minimal tag

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/ValuePathStatus.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/paths/missingOk.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java

The previous PR made a fix, but it didn't show up in the Survey Tool; it needed to be at a lower level (Tom was right!)
NOTE: I filed a ticket for some cleanup in the vetting viewer: https://unicode-org.atlassian.net/browse/CLDR-14806
CLDR-14797

CLDR-14797 push the change to a lower level

---

tools/cldr-apps/js/src/esm/cldrAccount.js
tools/cldr-apps/js/src/esm/cldrDrag.js
tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/views/DashboardWidget.vue

-New file cldrDrag.js with new function cldrDrag.enable
-Fix bug in cldrAccount.getTransferLink, use the optional chaining operator (?.)
-Fix formatting of cldrLoad.js (in an earlier commit it was unformatted)
-Comment on warning for await in cldrGui.ensureSession
CLDR-14735

CLDR-14735 Dashboard dragging

---

tools/cldr-apps/js/src/esm/cldrAdmin.js
tools/cldr-apps/js/src/esm/cldrLoad.js
tools/cldr-apps/js/src/esm/cldrStatus.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/esm/localesTxtGenerator.mjs
tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/js/src/views/VettingParticipation2.vue
tools/cldr-apps/js/test/pretty.sh
tools/cldr-apps/js/util/locale-coverage-to-localestxt.mjs
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VotingParticipation.java

CLDR-14804 add an API for calculating a historic vetting report

---

common/annotations/en.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/emoji/emoji-test.txt

CLDR-14767
Incorporates the latest changes in the emoji names (the changes to reduce the number of keywords have already been made).

CLDR-14767 Final touches on emoji

---

tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestSTFactory.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

- remove * from all but active TCs
- remove lines that were unused
- ADD lines for locales that had votes and/or vetters
CLDR-14804
Data was generated using #1293

CLDR-14804 update Locales.txt based on research

---

tools/cldr-apps/js/src/cldrVueRouter.js
tools/cldr-apps/js/src/esm/cldrGenericVue.js

CLDR-14790 improve error handling for vue problems

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java

CLDR-14814 fix email footer

---

tools/cldr-apps/js/src/esm/cldrAccount.js
tools/cldr-apps/js/src/esm/localesTxtGenerator.mjs
tools/cldr-apps/js/src/esm/setUtils.mjs
tools/cldr-apps/js/src/views/TransferVotes.vue
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VotingParticipation.java

- also fix a typo and access for CLDR-14804
CLDR-14787

CLDR-14787 UI polish on transfer votes

---

tools/cldr-apps/js/src/esm/cldrRecentActivity.js
tools/cldr-apps/js/src/esm/localesTxtGenerator.mjs
tools/cldr-apps/js/src/esm/setUtils.mjs
tools/cldr-apps/js/src/views/TransferVotes.vue

-Display only the id number, not the name, unless it is the current user
-Comment
-Formatting for unrelated unformatted .mjs and .vue files
CLDR-14817

CLDR-14817 Recent Activity displays wrong user name

---

tools/cldr-apps/pom.xml
tools/cldr-apps/src/cldr-root/index.html
tools/cldr-apps/src/main/liberty/config/server.xml
tools/cldr-apps/src/main/webapp/index.jsp

- CLDR-14398 make /cldr-apps just redirect to /cldr-apps/v
- for the server root ( / in development ) add a redirection page as well
CLDR-14562

CLDR-14562 update index.jsp, add top level root page

---

common/supplemental/grammaticalFeatures.xml

CLDR-14498
This is further progress on reducing the number of grammatical forms we need. There will probably need to be one more PR. However, this takes the number of missing forms substantially in some locales so is worth integrating earlier.

CLDR-14498 Semi-final pass based on survey results.

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java

-After copying votes from user A to user B, enable repeat of auto-import for B
-New clear action for SurveyAjax.alreadyAutoImportedVotes
CLDR-14821

CLDR-14821 ST: need to trigger previous vetter vote copy

---

tools/cldr-apps/js/src/esm/cldrLoad.js

CLDR-14790
handle case "iv" in the ticket.
Test with a URL such as http://cldr-smoke.unicode.org/cldr-apps/v#SOMETHING_NON_EXISTENT

CLDR-14790 handle missing 'special' pages

---

tools/cldr-apps/js/src/esm/cldrLoad.js

CLDR-14790
sorry, #1312 had a change to the click logic that didn't work every time. Fixed.

CLDR-14790 fix return-to-surveytool button in err popup

---

common/main/root.xml
common/supplemental/likelySubtags.xml
common/supplemental/plurals.xml
common/supplemental/supplementalData.xml
common/supplemental/supplementalMetadata.xml
seed/main/hnj.xml
seed/main/hnj_Hmnp.xml
seed/main/hnj_Hmnp_US.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java

Green Hmong in Nyiakeng Puachue Hmong script
also fix for Hmnp numbers
CLDR-13513

CLDR-13513 seed data for hnj-Hmnp

---

tools/cldr-apps/js/src/views/LoginButton.vue
tools/cldr-apps/src/main/webapp/login.jsp

- fix button class
- make login.jsp redirect
CLDR-14395

CLDR-14395 last login review comments

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java

- fix casing of some orgs
- (re-)add * to SIL, wikimedia
- fix corrupted chars in comments
- re-instate obvious participation locales
- add '*' to Apple, IBM, Microsoft, Google
CLDR-14804

CLDR-14804 update Locales.txt per discussion

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java

-If VoteResolver says it is not missing, it is not missing
-Enable VettingViewer to get VoteResolver with new VettingViewerQueue.STUsersChoice.getVoteResolver
CLDR-14827

CLDR-14827 CLDR survey tool dashboard showing incorrect number of issues

---

common/bcp47/number.xml
common/dtd/ldmlSupplemental.dtd
common/main/en.xml
common/main/fr.xml
common/supplemental/coverageLevels.xml
common/supplemental/numberingSystems.xml
tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java

CLDR-14801 Unicode 14 new numbering system: sc=Tnsa has decimal digits

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java

also, improve debugging
CLDR-14850
This is on a branch as  e547a7fb5e9 e518310dab81c1268762f18540f7c to be pushed to production as a hotfix.

CLDR-14850 speed up mail by reusing connection

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

- Added bal, bal_Latn, tpi (at basic level)
- Changed kk to kkj
- Put list in alphabetical order
CLDR-14847

CLDR-14847 update locales for SIL

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java

-Fix the link, and move the url and message into variables to facilitate future updates
CLDR-14856

CLDR-14856 Info Panel: Link for exemplar characters

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java

CLDR-14866
There was some special-case code for computing some pl and ru grammar lines, but it appears to be flaky, so I removed it.
I can't test it locally, so will have to commit to smoketest before verification.

CLDR-14866 Fix Polish missing lines

---

docs/ldml/tr35-keyboards.md

CLDR-14716 keyboard editorial

---

tools/cldr-apps/src/main/webapp/lock.jsp

-Restore lock.jsp for compatibility with Unsubscribe links in old emails
-New version of lock.jsp is only text with link to ST for logging in
CLDR-14384

CLDR-14384 Modernize Lock My Account: support old email link

---

common/main/be_tarask.xml

CLDR-14826
I think the file included in this PR will complete the ticket. Please correct me if I'm wrong!

CLDR-14826 add Belarusian classical locale

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

CLDR-13513 add an organization. Org name was confirmed in email.

CLDR-13513 add org nyiakeng_puachue_hmong

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java

-Fix UserRegistry.updateIntLocs
CLDR-14597

CLDR-14597 Prevent duplicates in cldr_interest table

---

common/main/en.xml
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java

Also wrote a test, which exposed other similar cases where the display name didn't match the plural, so fixed those too.
CLDR-14870

CLDR-14870 fix items

---

common/supplemental/grammaticalFeatures.xml

CLDR-14889 expand grammatical features for certain languages

---

tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt

- add ff_Adlm to the Adlam org
- work around CLDR-14597 behavior where the script is required to be specified
CLDR-14804

CLDR-14804 update Adlam to add ff_Adlm

---

tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java

- get rid of the last of the HttpSession code which was
missed before
- fix the "login failed" message to just be "login failed"
Will bring back password reset in CLDR-7405
- add fine logging to SurveyMain and WebContext
CLDR-14819

CLDR-14819 fixes for login process

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckLogicalGroupings.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java
tools/cldr-code/src/test/java/org/unicode/cldr/test/TestCheckLogicalGroupings.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java

- also add utility on CLDRFile.DraftStatus for going to/from xpath form
- add Level.getAltName()
CLDR-14907
updated message:

CLDR-14907 CheckLogicalGroupings: treat approved/contributed as equiv

---

common/annotations/en.xml

CLDR-14896
Removed bear and added face and marsupial

CLDR-14896 fixed keywords for koala emoji

---

keyboards/und/kgp-t-k0-android-600dpi.xml
keyboards/und/kgp-t-k0-android-768dpi.xml
keyboards/und/kgp-t-k0-android.xml
keyboards/und/kgp-t-k0-chromeos.xml
keyboards/und/kgp-t-k0-osx-extended.xml
keyboards/und/kgp-t-k0-osx.xml
keyboards/und/kgp-t-k0-windows.xml
keyboards/und/yrl-BR-t-k0-chromeos.xml
keyboards/und/yrl-BR-t-k0-osx-extended.xml
keyboards/und/yrl-BR-t-k0-osx.xml
keyboards/und/yrl-BR-t-k0-windows.xml
keyboards/und/yrl-t-k0-android-600dpi.xml
keyboards/und/yrl-t-k0-android-768dpi.xml
keyboards/und/yrl-t-k0-android.xml
keyboards/und/yrl-t-k0-chromeos.xml
keyboards/und/yrl-t-k0-osx-extended.xml
keyboards/und/yrl-t-k0-osx.xml
keyboards/und/yrl-t-k0-windows.xml

CLDR-14573 Add keyboard data of Kaingang and Nheengatu locales
- Kaingang (kgp) keyboards
- Nheengatu (yrl) keyboards

CLDR-14573 Add keyboard data of Kaingang and Nheengatu locales

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-14919 fix use of winning value for example

---

common/annotations/en.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/emoji/emoji-test.txt

Rename "knocked out face" to "face with crossed-out eyes"
CLDR-14803

CLDR-14803 Rename "knocked out face" to "face with crossed-out eyes"

---

common/rbnf/su.xml

CLDR-14917
I verified that the rules work in [Number Format Tester](https://st.unicode.org/cldr-apps/numbers.jsp)

CLDR-14917 Non-ascending order of RBNF rules in "su" depends on undefined ICU behavior

---

common/annotations/en.xml
tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/emoji/emoji-test.txt

Rename 🤗 from "hugging Face" to "smiling face with open hands" and update keyword annotations.
CLDR-14900

CLDR-14900 Rename "Hugging Face"

---

tools/st-prom-exporter/README.md

- documentation for the systemd, prom scrape, and prom alert rules
- also document planned obsolescence
CLDR-14768

CLDR-14768 Document how to install and use the prom exporter

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java

- clear some values that weren't being cleared between reuse
CLDR-14935

CLDR-14935 VoteResolver.clear() fix

---

.github/workflows/maven.yml
tools/cldr-code/src/main/java/com/ibm/icu/dev/test/TestFmwk.java

CLDR-14748 Use GitHub Action Commands to improve test output clarity

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java

-Bug fix: do not call method grammarInfo.get when grammarInfo is null
-Call getLocaleID once instead of three times
-Skip setting local variables gCase and unitCaseInfo when unused, when value is null
-Remove dead code (unitGenders, unitId, width)
-Comments
CLDR-14933

CLDR-14933 Fix ExampleGenerator.handleFormatUnit null pointer exception

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java

CLDR-14941
Allow script Toto to have translated name "Toto" (i.e. add to exceptions list for same-as-code error).

CLDR-14941 Allow script Toto to have translated name "Toto"

---

tools/cldr-apps/js/package-lock.json
tools/cldr-apps/js/package.json
tools/cldr-apps/js/src/esm/cldrRecentActivity.js
tools/cldr-apps/js/src/esm/cldrUserListExport.js

CLDR-14802 add a user Recent Changes .xlsx

---

tools/scripts/ansible/README.md
tools/scripts/ansible/backup-db-playbook.yml
tools/scripts/ansible/test-local-vars/local.yml

-Comments in scripts and README.md
-Update oldversion, newversion, and add certbot settings in local.yml
CLDR-14931

CLDR-14931 Update ansible documentation and scripts

---

common/main/kab.xml

CLDR-14952 console check fixes in kab

---

tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-14755 Clean up some test errors

---

common/main/hi.xml

CLDR-14755 Clean up Hindi errors

---

seed/main/tpi.xml

CLDR-14966
Remove incomplete information in tpi.xml
(only part of CLDR-14966 ticket)

CLDR-14966 cleanup tpi errors

---

common/main/be_tarask.xml
common/main/ff_Adlm.xml

CLDR-14952 fix be_tarask / ff_Adlm errs

---

.github/workflows/maven.yml

CLDR-14952 switch console check to FINAL_TESTING

---

common/main/rw.xml

CLDR-14809 rw: Fix May to Gicurasi

---

tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestSTFactory.xml

CLDR-14966
@macchiati will file a follow up for stable data in the web tests

CLDR-14966 disable some web app tests temporarily

---

common/main/id.xml

- different translation for Islamic calendar
CLDR-14043

CLDR-14043 id: update Sunday

---

tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitPathType.java

-Fix UnitPathType.getPathType to recognize durationUnit.../durationUnitPattern
CLDR-14967

CLDR-14967 Raise error for missing formatting pattern characters

---

.github/workflows/maven.yml
tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java

CLDR-14748
When in a GitHub build, annotate consolecheck output so that it shows errors prominently. c.f. #1378

CLDR-14748 GitHub annotation for ConsoleCheck

---

common/main/kab.xml
common/main/sat.xml
common/main/sd_Deva.xml

See #1422 for the test fix
CLDR-14967

CLDR-14967 Fixes to formatting pattern characters

---

tools/cldr-apps/js/src/esm/cldrRetry.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/specialToComponentMap.js
tools/cldr-apps/pom.xml
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java

- a new special retry_inplace
- For 'normal' disconnect, show the retry message "inplace" without redirecting
- Pick up where you left off when reconnecting to the server!
CLDR-14790

CLDR-14790 No more reconnect loop, stay where you were

---

tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListGrammarData.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java

CLDR-14755
tools/cldr-code/src/main/java/org/unicode/cldr/test/BestMinimalPairSamples.java
Augmented to add stats for use in listing.
tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
The style setting for charts had a syntax error.
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
Enhanced the charts
0. Show the chart if there are genders, even if there are no cases
1. Added a table of minimal pairs
2. Added a gender sample using the minimal pair
3. Now generates a tsv file
4. Include units with grammar, even if they aren't in the minimal set.
5. A few other tweaks
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListGrammarData.java
Add more data for comparison

CLDR-14755 grammar listing fixes

---

common/collation/ku.xml

CLDR-9748 Updating Kurdish collation per Wikimedia Foundation request

---

common/main/kgp.xml
common/main/kgp_BR.xml
common/main/yrl.xml
common/main/yrl_BR.xml
common/main/yrl_CO.xml
common/main/yrl_VE.xml

Part of CLDR-14980
CLDR-14573
#1349 just barely missed #1438 so this catches the last two locales

CLDR-14573 CLDRModify no-arg for kgp/yrl

---

common/main/be_TARASK.xml
common/main/bo.xml
common/main/en_ZA.xml
common/main/kea.xml
common/main/ku.xml
common/main/my.xml
exemplars/main/kk_Arab.xml
seed/main/ab.xml
seed/main/bal.xml
seed/main/bal_Latn.xml
seed/main/hnj.xml
seed/main/rhg.xml
seed/main/tpi.xml
seed/main/trw.xml

CLDR-14980
ALLOW_MULTI_COMMITS=yes
ALLOW_MANY_COMMITS=yes
ALLOW_MUCHO_COMMITS=yes

CLDR-14980 CLDRModify -fp

---

common/supplemental/supplementalData.xml

CLDR-14795 Australia - First day of week is officially Monday

---

common/main/bn.xml
common/main/fi.xml
common/main/gu.xml
common/main/hi.xml
common/main/hy.xml
common/main/kn.xml
common/main/lt.xml
common/main/lv.xml
common/main/ml.xml
common/main/mr.xml
common/main/nn.xml
common/main/no.xml
common/main/pa.xml
common/main/ro.xml
common/main/ru.xml
common/main/si.xml
common/main/sl.xml
common/main/sr.xml
common/main/sr_Latn.xml
common/main/te.xml
common/main/ur.xml
common/supplemental/grammaticalFeatures.xml
tools/cldr-code/src/main/java/org/unicode/cldr/tool/CompareLocales.java
tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt

CLDR-14986
Includes
1. deletion of day-duration data from most locales. The vast majority of this across all locales was bogus.
2. fixing minimal pair data in a few cases
3. removing suspect case data from certain locales. (In those locales, the vast majority of the data was ↑↑↑)
4. making spot fixes to Hindi based on Karan's feedback (and verified by Google vetter)
5. adding corrected case data to Romanian and Serbian
6. narrowing the grammarFeatures.xml data to the units in evidence
7. modifying the CompareLocales tool to aid in comparison

CLDR-14986 Deal with lack of case data for certain locales

---

tools/cldr-apps/js/src/esm/cldrGui.js
tools/cldr-apps/js/src/esm/cldrText.js
tools/cldr-apps/js/src/esm/cldrVote.js
tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VotingCompletion.java
tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java

-New api/VotingCompletion.java, works with openapi/ui, not yet with ST front end
-Revise DataSection and VettingViewer to be more consistent with each other
-Skip paths for which PathHeader returns null
-Refactor PathHeader and related code for encapsulation and consistency
-In some places assume both HIDE and DEPRECATED paths should be hidden
-In getShowRowAction and getAcceptNewItemAction, change ph.status to ph
-Rename cleanPath/pretty to ph for consistency
-Front-end changes in this commit are only refactoring/comments
-Remove superfluous parameter what from cldrVote.handleWiredClick
-Remove unused parameter box from cldrVote.wireUpButton
-Reduce warnings for deprecated/unused/dead
-Change public to private where possible
-Remove dead/commented-out code
-Comments, including TODO …

CLDR-14877 Coverage Progress Bars

---

common/dtd/ldmlSupplemental.dtd
tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDtd.java

- minor whitespace change
- added annotation to the tool (and doc page at http://cldr.unicode.org/tools/generate-dtd )
CLDR-14998

CLDR-14998 BRS v40 §A07.9 GenerateDtd
