- common/supplemental/coverageLevels.xml
am, ga, ka, kk, ky upgrading to 8 votes per TC agreement
> CLDR-12032 add additional 8 vote locales

- tools/cldr-unittest/build.xml
Fixes [CLDR-13042]
[CLDR-13042]: https://unicode-org.atlassian.net/browse/CLDR-13042
> CLDR-13042 Remove unnecessary libs directives from cldr-unittest build

- common/main/ga_GB.xml
[CLDR-11912] 
Adds UK Irish locale, for Irish spoken in Northern Ireland.
[CLDR-11912]: https://unicode-org.atlassian.net/browse/CLDR-11912
> CLDR-11912 Add ga_GB locale

- common/main/rm.xml
- tools/java/org/unicode/cldr/test/CheckDates.java
This is for [CLDR-11598](https://unicode-org.atlassian.net/browse/CLDR-11598) Change Romansh month names
The main idea was to add prepositions to the Romansh (rm) format wide names, and update date formats to match (use MMMM if d is present, LLLL otherwise). However, I also noticed that there were some inconsistencies, and tried to fix them.
- The standard formats used numeric form for medium style, so I made the availableFormats and intervalFormats consistent in using numeric style with MMM and alphabetic styles with MMMM.
- There were inconsistencies in date order (yMd vs dMy) and numeric style (e.g dd.MM vs dd-MM)
To resolve these, I looked at the Romansh portion of the website for Lia Rumantscha, the Romansh language & culture association, to see the formats used there. I saw examples …
> CLDR-11598 rm, add preposition to format months, update date formats for consistency

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
- tools/java/org/unicode/cldr/util/data/PathHeader.txt
CLDR-11454 There was a spurious test on the possible duration values that forced decade into Other Units.
> CLDR-11454 b put decade in right header (not other units)

- .travis.yml
- obviated by b566f5d18f16105b7307b5ebb769c4b95fef513a / #18
- change `;` to `&&` so Travis jobs fail when the build fails
> CLDR-13042 Remove unnecessary mkdir from cldr-unittest build

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
- tools/java/org/unicode/cldr/util/Emoji.java
- tools/java/org/unicode/cldr/util/PathHeader.java
- tools/java/org/unicode/cldr/util/data/PathHeader.txt
The ordering still wasn't right. The root problem is that the collation sequence isn't updated until later in the Unicode process, once we have beta of Unicode.
So reworked the ordering in the Survey Tool (via PathHeader) to follow the emoji-test.txt file, instead of using an alphabetic sort for the Code values.
> CLDR-13040 Fix-the-ordering-to-match-emoji-test

- .github/pull_request_template.md
[CLDR-13056]
This change adds a GitHub Pull-Request template for CLDR, similar to the one used by ICU.
[CLDR-13056]: https://unicode-org.atlassian.net/browse/CLDR-13056
> CLDR-13056 Add a GitHub pull-request template for CLDR.

- common/supplemental/supplementalData.xml
- tools/java/org/unicode/cldr/tool/GenerateMaximalLocales.java
- tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt
- tools/java/org/unicode/cldr/util/data/external/alternate_country_names.txt
- tools/java/org/unicode/cldr/util/data/external/factbook_literacy.txt
- tools/java/org/unicode/cldr/util/data/language_script_raw.txt
[CLDR-13065]
The tools were also barfing on the Eswatini vs. Swaziland change, so I changed factbook literacy file ( which will likely never change ) to Eswatini.
[CLDR-13065]: https://unicode-org.atlassian.net/browse/CLDR-13065
> CLDR-13065 Country/lang/pop additions for Chickasaw

- tools/cldr-apps/WebContent/admin-OutputAllFiles.jsp
- tools/cldr-apps/src/org/unicode/cldr/web/OutputFileManager.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/CLDRPaths.java
[CLDR-12016]
-Change jsp notation to java, move java code from jsp to new OutputFileManager.outputAllFiles
-New OutputFileManager.outputAndVerifyAllFiles
-New function verifyAllFiles and its subroutines
-Make isCacheableKind private
-Remove unused getTryCommitWhyNot
-New function removeEmptyFiles; turn off SKIP_FILE_IF_SKIP_ALL_PATHS
-New createNewManualVetdataDir makes folder like vetdata-2019-05-28T12-34-56-789Z
-Copy ldml.dtd where needed
-Enable both "update" and "new folder" in outputAndVerifyAllFiles
-Encapsulate dir names in new DirNames class
-New parameters for output/separate/remove/verify
-Allow parent in common and child in seed, not vice-versa
-New function otherParentExists
-Allow present in vxml but not in baseline, not vice-versa
-Delete dead code; clean-up, comments …
> CLDR-12016 Verify consistency when generating vxml

- tools/cldr-apps/WebContent/js/CldrSurveyVettingLoader.js
- tools/cldr-apps/WebContent/js/review.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
-Do not replace newer data from one-row request with older data from all-row request
-Do not defer all-row update until after one-row update
-Avoid making all-row request if isInputBusy
-Order SurveyAjax parameters more consistently, start with what=...
-Comments
[CLDR-11685]
[CLDR-11685]: https://unicode-org.atlassian.net/browse/CLDR-11685
> CLDR-11685 ST performance, fix delayed display of submitted values

- tools/cldr-apps/WebContent/about.jsp
- tools/cldr-apps/WebContent/index.jsp
- tools/cldr-apps/WebContent/surveytool.css
- tools/cldr-apps/WebContent/v.jsp
- tools/cldr-apps/build.xml
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestMisc.java
- tools/cldr-apps/src/org/unicode/cldr/util/CLDRConfigImpl.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyLog.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
- tools/java/build.xml
- tools/java/org/unicode/cldr/util/CLDRURLS.java
[CLDR-13047] 
- update cldr.jar and cldr-apps.war builds to include git hash in the jar manifest
- update SurveyMain functions and CLDRConfigImpl to handle the possibly 3 different hashes:
1. cldr.jar (CLDR_TOOLS_HASH)
2. cldr-apps.war (CLDR_APPS_HASH)
3. the actual CLDR data (CLDR_DIR_HASH)
- code in CLDRURLS to generate github URLs for the above
- update the UI to show the version number on the loading page, and under the
gear menu (for SmokeTest).
- Update the 'about.jsp' page to show the three version numbers above
[CLDR-13047]: https://unicode-org.atlassian.net/browse/CLDR-13047
> CLDR-13047 add git hash to manifest, show in SurveyTool

- tools/cldr-apps/WebContent/AdminAjax.jsp
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/src/org/unicode/cldr/web/CookieSession.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/org/unicode/cldr/web/WebContext.java
-Booleans KICK_IF_ABSENT = false; KICK_IF_INACTIVE = true
-Change hard-coded timeouts to Params-based timeouts
-Rename variables and functions for clarity, include secs or millis
-Make data private, use accessor functions
-Merge CLDR_USER_INACTIVITY/CLDR_GUEST_INACTIVITY with CLDR_USER_TIMEOUT/CLDR_GUEST_TIMEOUT
-Double timeouts if not tooManyUsers/tooManyGuests
-No special timeout for TC
-Make CookieSession.Params private
-Remove dead code; clean up; comments
> CLDR-11799 Extend ST timeout

- tools/java/org/unicode/cldr/util/DtdData.java
This should be one of only a small number of changes to existing code required to support the new CLDR data API.
I'm not necessarily seeking a merge at this stage, but just putting the expected changes out for discussion. The prototype API and some unit tests will be added separately (or if people want I can combine into a single pull request).
It turned out to be effectively impossible to simply isolate existing methods and classes to move/expose for a public API, and what I've ended up doing is create a very minimal new API in a new package (but using lots of the existing CLDR classes behind the scenes). This means that there won't be much changing with existing code, which is nice because it removes any risk of breaking things while the new API and ICU tools are being converted to the …
> CLDR-13090 Added a helper function to obtain Attribute instances efficiently.

- tools/java/org/unicode/cldr/util/CLDRLocale.java
[CLDR-13132]
- CLDRLocale.getInstance() needs to be synchronized
-  At runtime, CLDRLocale is a singleton, but needs to be
thread safe at construction
[CLDR-13132]: https://unicode-org.atlassian.net/browse/CLDR-13132
[CLDR-13132]: https://unicode-org.atlassian.net/browse/CLDR-13132
> CLDR-13132 synchronize CLDRLocale.getInstance

- tools/cldr-apps/src/org/unicode/cldr/web/VettingViewerQueue.java
> CLDR-13124 Dashboard Missing, add debugging timestamp to reviewInfo json

- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
-Avoid == due to multiple CLDRLocale objects with name root
-Note: this might not be needed if and when [CLDR-13132] is fixed
[CLDR-13132]: https://unicode-org.atlassian.net/browse/CLDR-13132
> CLDR-13134 Fix wrong background color for values inherited from root

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCLDRUtils.java
- tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/java/org/unicode/cldr/tool/ShowLanguages.java
- tools/java/org/unicode/cldr/util/CLDRLocale.java
- tools/java/org/unicode/cldr/util/Factory.java
- tools/java/org/unicode/cldr/util/LocaleIDParser.java
-LocaleIDParser.getParent return root, not empty string, for _VETTING
-LocaleIDParser.getParent remove SUPPLEMENTAL_NAME test
-LocaleIDParser.getParent call SupplementalDataInfo only if needed
-Prevent creation of multiple instances of root locale
-Improve and extend TestCLDRLocaleEquivalence, assertSame not assertEqual
-Normalize strings equivalent to root before checking stringToLoc
-New function rootMatches encapsulates string equivalence to root
-New constant ROOT_NAME = root
-Make getSiblings and getVendorStatus more bomb-proof in case getParent returns null
-Use !equals instead of != to test string inequality in makeWithFallback
-LocaleIDParser.setVariants guard against null parentID
-Comments, clean-up
> CLDR-13133 fix CLDRLocale.getInstance

- tools/java/org/unicode/cldr/util/DtdData.java
This is needed for the new API work since ordered elements need slightly different treatment in the code.
> CLDR-13090 Adding a trivial utility method to return whether a path element is ordered.

- tools/java/org/unicode/cldr/icu/BreakIteratorMapper.java
- tools/java/org/unicode/cldr/icu/CollationMapper.java
- tools/java/org/unicode/cldr/icu/LDMLComparator.java
- tools/java/org/unicode/cldr/icu/LocaleMapper.java
- tools/java/org/unicode/cldr/icu/MapperUtils.java
- tools/java/org/unicode/cldr/icu/RbnfMapper.java
- tools/java/org/unicode/cldr/util/LDMLUtilities.java
[CLDR-12038]
- <version> is useless and should be deprecated (separate ticket)
- $Revision:$ keyword behavior under svn was not what we 'enjoyed' before '06
- remove extremely obsolete code for reading CVS metadata directly
- use CLDRFile.GEN_VERSION for ldml2icu version production
[CLDR-12038]: https://unicode-org.atlassian.net/browse/CLDR-12038
[CLDR-12038]: https://unicode-org.atlassian.net/browse/CLDR-12038
> CLDR-12038 ignore <version> element for ICU or comparator

- common/transforms/Hiragana-Katakana.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestTransforms.java
Leave \u309B, \u309C  unaffected by transform.
Add final NFC.
Add unit test.
> CLDR-13127 Hira-Kata fixes for U+309B/309C and final NFC; add test

- common/main/en.xml
- seed/main/en_ZZ.xml
Added English name for Zawgyi, and translation hint. Should show up in Survey Tool with Comprehensive coverage in Locale Display Names > Scripts, subsection "Other".
> CLDR-13088 Add English name for Qaag=Zawgyi, and translation hint

- tools/cldr-unittest/src/org/unicode/cldr/api/AllTests.java
- tools/cldr-unittest/src/org/unicode/cldr/api/CldrFileDataSourceTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/CldrPathTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/CldrValueTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/PrefixVisitorTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/XmlDataSourceTest.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAll.java
- tools/java/org/unicode/cldr/api/AbstractDataSource.java
- tools/java/org/unicode/cldr/api/AttributeKey.java
- tools/java/org/unicode/cldr/api/CldrData.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/CldrDataType.java
- tools/java/org/unicode/cldr/api/CldrDraftStatus.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
- tools/java/org/unicode/cldr/api/CldrPath.java
- tools/java/org/unicode/cldr/api/CldrPaths.java
- tools/java/org/unicode/cldr/api/CldrValue.java
- tools/java/org/unicode/cldr/api/InMemoryData.java
- tools/java/org/unicode/cldr/api/PrefixVisitorHost.java
- tools/java/org/unicode/cldr/api/XmlDataSource.java
Note that this CL includes basic tests, but coverage for these will be improved later (with the aim of getting close to 100% coverage, including error handling and exceptions). The new code soon to be in the ICU project will also have a suite of end-to-end tests in the actual ICU data conversion logic.
> CLDR-11049 First version of the new lightweight data access API for ICU data conversion.

- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/surveyTool/nls/stui.js
- [CLDR-13151]
Do not show 'Jump to Original' if it would be a useless link.
Compare to current behavior: https://st.unicode.org/cldr-apps/v#/yo/Languages_E_J/7bbb0dfa5b2ebec9
[CLDR-13151]: https://unicode-org.atlassian.net/browse/CLDR-13151
> CLDR-13151 show alternate message for constructed values

- common/annotations/en.xml
- tools/java/org/unicode/cldr/util/data/emoji/emoji-test.txt
For transgender flag emoji sequence, update English tts name and keywords per ESC.
Also needed to update the local copy of emoji-test.txt so tests pass.
> CLDR-13160 update en tts name and keywords for transgender flag

- tools/cldr-apps/WebContent/submit.jsp
- tools/cldr-apps/WebContent/surveyTool/nls/stui.js
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/java/org/unicode/cldr/test/CheckCLDR.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
-New StatusAction.FORBID_NULL and message: The item has no value.
-New function DataRow.wouldInheritNull
-Delete unused StatusAction values FORBID_COVERAGE, FORBID_NEEDS_TICKET, ...
-Do not send cPhase, phStatus, or covLev to client since client does not use them
-Delete some dead code
-Comments
> CLDR-13172 Disallow voting to inherit No Value

- tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java
[CLDR-13178] Allow display collision between short/duration-century and second
[CLDR-13178]: https://unicode-org.atlassian.net/browse/CLDR-13178
> CLDR-13178 Allow additional display collision

- common/supplemental/supplementalData.xml
> CLDR-11893 Change first day of week from Sunday to Monday for Argentina

- tools/java/org/unicode/cldr/api/AbstractDataSource.java
- tools/java/org/unicode/cldr/api/AttributeKey.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/CldrDataType.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
- tools/java/org/unicode/cldr/api/CldrPath.java
- tools/java/org/unicode/cldr/api/CldrPaths.java
- tools/java/org/unicode/cldr/api/LocaleIds.java
- tools/java/org/unicode/cldr/api/XmlDataSource.java
A handful of bug fixes:
* not walking subdirs for XML files
* improve local-equality checking in paths (it was inefficient)
* have only one bit of logic to check if a path should be emitted rather than 3!
* add alias as a "leaf" element so it doesn't skip all those paths (oops)
> CLDR-11049 Fixes and improvements for the CLDR API classes.

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
-Use day instead of DAYOFMONTH(last_mod) in GROUP BY clause
> CLDR-10255 Votes by day in statistics page gives an SQL Exception

- tools/java/build.xml
This improves on the previous fix to add the new API classes into the CLDR jar, and also introduces a smaller "cldr-api.jar" for use in the ICU project.
The previous fix wasn't complete because it relied on the API classes being vicariously compiled by Ant, rather than compiling them explicitly. This PR adds a new target for compiling the "api" package and another target for making the trimmed down jar. It also notes that, right now, there are circular dependencies in the existing targets (Ant is not very good at enforcing anything regarding which sources are compiled by which targets, so it's easy to end up in a mess like this).
> CLDR-11049 Fixing build file for API jar.

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLdml2ICU.java
- tools/java/org/unicode/cldr/util/CldrUtility.java
This moves a static utility method to the only place it's actually used, and removes one of the relatively small numbers of dependencies from "org.unicode.cldr.util" to "org.unicode.cldr.unittest".
Ideally "util" wouldn't depend on packages like "unittest" or "tool", but right now it does. Removing these will help reduce the size (and complexity) of the new API jar used by the CLDR project.
> CLDR-11049 Breaking an unnecessary inter-package dependency for API jar.

- tools/java/org/unicode/cldr/api/AbstractDataSource.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
- tools/java/org/unicode/cldr/api/CldrValue.java
- tools/java/org/unicode/cldr/api/XmlDataSource.java
The hopefully last tweak to the API classes for now, which adds a check and fixes some documentation regarding the handling of inheritance markers. Also added a better error message for when the entity resolution isn't supported (an issue for Googlers due to the default JDK setup).
> CLDR-11049 Improvements to the API for handling (and documenting) inheritance markers.

- tools/cldr-unittest/build.xml
- tools/cldr-unittest/src/org/unicode/cldr/api/XmlDataSourceTest.java
- tools/java/build.xml
Additionally fixed the tests to honour Ant's idea of the current working directory during testing.
This reliance on the test environment is nasty, but I added an explicit directory setting in the build file to deal with it. The ../../ back-path in the tests is for getting up from the base test directory into the main release root, which has the "real" DTDs in (the "test" DTDs are not complete and don't work for me and weren't obviously upgradeable to the latest ones).
> CLDR-11049 Fix Ant build files (main and test) to build and run everything.

- seed/main/osa.xml
[CLDR-13190] Removing a-z from auxiliary examplars, since having them there breaks the build.
[CLDR-13190]: https://unicode-org.atlassian.net/browse/CLDR-13190
> CLDR-13190 Remove latin a-z from aux examplars, fix build break.

- tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
-Enhance unit test to check extra path null value
-New TestPathHeadersAndValues combines old TestGetFullPath and TestPathHeaders, for speed
-Check extra paths as well as regular paths
-Allow null value for exceptional extra paths, both unit test and client
-Exceptional extra paths are like timeZoneNames/(meta)zone or dayPeriods/dayPeriodContext
-Use getCLDRFile instead of getCldrFactory().make, for speed
-Rename checkPaths to checkPrettyPaths
-Comments
> CLDR-11238 INHERITANCE_MARKER without inheritedValue

- common/supplemental/plurals.xml
[CLDR-13227]
Also removed ji, which is an illegal code for yi (Yiddish), which has rules elsewhere.
[CLDR-13227]: https://unicode-org.atlassian.net/browse/CLDR-13227
> CLDR-13227 fix bh in plural rules

- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
Since the CLDR API is very stable now, I feel happy in opening up the data supplier for subclassing.
It was only ever done like this to keep control while it was in flux. Now I'm convinced it's fit for purpose there's no reason to keep it locked down so much (and this lets me make a fake version for testing).
Please merge once you're happy (this blocks a PR on the ICU side).
> CLDR-11049 Allow subclassing of CldrDataSupplier for easier testing.

- common/supplemental/likelySubtags.xml
https://unicode-org.atlassian.net/browse/CLDR-13071 is about adding an entry for "ars" n likelySubtags. However, although it already has 2 earlier pull requests (#39, #136), neither of them actually added the "ars" entry in likelySubtags. The latter PR does add it in the country_language_population_raw.txt so when likelySubtags is regenerated, "ars" should get added. However, I need "ars" in likelySubtags now for the CLDR-ICU integration, not having it is blocking me. So this PR just finally adds "'ars" to likelySubtags.
> CLDR-13071 really add ars to likeySubtags

- common/main/ar.xml
- common/main/de.xml
36 BRS work: Per discussion in CLDR TC 2019-09-04, revert the following:
- de CompactDecimals, revert formats for 1000,10000,100000 to use just 0, not formats with Tsd. (we seem to do this every release)
- ar latn numbers decimal separator, change from \u066B back to ASCII period (more common with Latin digits)
> CLDR-13243 revert de CompactDecimals, ar@numbers=latn decimalSep

- tools/java/org/unicode/cldr/api/CldrData.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
Minor change primarily to remove the "seed" directory from the data supplier.
This is not currently needed for ICU data generation and will be trivial to support as a option once a proper use case exists.
Also includes a few additional comment improvements.
> CLDR-11049 Minor change primarily to remove the "seed" directory from the data supplier.

- tools/cldr-unittest/src/org/unicode/cldr/api/XmlDataSourceTest.java
This should fix the bug whereby the multiple XML test data fake files are read in an undefined order (currently reversed on Windows).
LinkedListMultimap has well determined iteration order for keys, ArrayListMultimap has undefined key order.
> CLDR-13262 Fix non-determined order of map keys

- tools/cldr-unittest/.classpath
- tools/java/.classpath
[CLDR-13243]
Fix Eclipse classpaths to include failureaccess.jar ( introduced by Guava update to 28.1 ) so that things run properly in Eclipse.
> CLDR-13243 Add failureaccess.jar in Eclipse .classpath files

- common/main/en_001.xml
This reverts some of the en_001 changes from https://github.com/unicode-org/cldr/pull/161. First, note that PR-161 did not change en_GB at all, it just copied some items from en_GB to en_001. So reverting en_001 changes will not affect en_GB, it will only affect other child locales of en_001.
The en_001 reversions here are:
- standard time formats: Delete standard time formats with H copied from en_GB to keep inheriting standard time formats with h from en. Otherwise many child locales of en_001 suddenly change default time cycle.
-  availableFormats, intervalFormats: For some cases of formats that were already in en_001 but replaced by formats from en_GB, restore the formats that were in en_001 to preserve (for other en_001 child locales) use of commas after weekdays, and more compact …
> CLDR-13243 BRS 36: revert some of the en_001 changes from PR-161

- tools/java/org/unicode/cldr/api/AbstractDataSource.java
- tools/java/org/unicode/cldr/api/CldrData.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
- tools/java/org/unicode/cldr/api/CldrPath.java
- tools/java/org/unicode/cldr/api/CldrValue.java
Primarily adding a new method in CldrValue to support "rewriting" CLDR paths in order to allow for "alternate values" in the ICU transformations (e.g. using short versions of various translations).
Also:
* Moved an abstract base method into the CldrData interface itself (makes implementing alternate data instances easier). This is also needed for the alt value stuff.
* Fixed a null pointer bug in the "get()" method of CldrFileDataSource. Seems important.
* Caught a weird lingering case where imports were not properly sorted (optional).
* Trivial removal of unnecessary ';' which was causing a needless lint warning in IntelliJ.
> CLDR-11049 tweaks and fixes plus new API method

- tools/java/org/unicode/cldr/api/AbstractDataSource.java
- tools/java/org/unicode/cldr/api/AttributeKey.java
- tools/java/org/unicode/cldr/api/CldrDataType.java
- tools/java/org/unicode/cldr/api/CldrDraftStatus.java
- tools/java/org/unicode/cldr/api/CldrFileDataSource.java
- tools/java/org/unicode/cldr/api/CldrPaths.java
- tools/java/org/unicode/cldr/api/InMemoryData.java
- tools/java/org/unicode/cldr/api/PrefixVisitorHost.java
- tools/java/org/unicode/cldr/api/XmlDataSource.java
100% automatic resorting and tidying of imports. For some reason some of these files did not have their imports sorted.
> CLDR-11049 Resorting imports.

- tools/java/org/unicode/cldr/api/AttributeKey.java
- tools/java/org/unicode/cldr/api/CldrDataType.java
- tools/java/org/unicode/cldr/api/CldrPath.java
- tools/java/org/unicode/cldr/api/CldrPaths.java
- tools/java/org/unicode/cldr/api/CldrValue.java
- tools/java/org/unicode/cldr/api/LocaleIds.java
- tools/java/org/unicode/cldr/api/XmlDataSource.java
Removed some "weak" TODOs from code to leave only actionable/interesting ones (TODOs which would be hit as part of a natural refactoring are "weak" even if they are actionable).
Also actually did one of the TODOs to strengthen the checking for sort indices.
A couple of small IDE warnings fixed on the way.
> CLDR-11049 Tidy todos

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestTransforms.java
This is for the CLDR 36 BRS task to update the KnownIssues in the CLDR unit tests. All of the CLDR bugs referenced by logKnowIssue statements are still open; the one ICU issue referenced by a logKnownIssue [https://unicode-org.atlassian.net/browse/ICU-11094) is supposedly fixed in the version of ICU4J currently in CLDR, but removing the logKnownIssue to execute the test results in test failures. So I created a new CLDR ticket to investigate the test failure and just changed the logKnownIssue to reference that instead.
> CLDR-13243 BRS 36: Update unittest logKnownIssues

- tools/java/org/unicode/cldr/tool/GenerateProductionData.java
- tools/java/org/unicode/cldr/util/CLDRPaths.java
As the main/ files are processed, we record their subdivisions (and remove them).
As the subdivisions/ files are processed, we add in the corresponding path/value pairs we recorded from main/
There is a warning message if there are subdivisions in main/ that aren't captured in a subdivisions/. NOTE: we don't typically have sublocales in subdivisions/, so messages about those can be ignored.
> CLDR-13240 fix subdivisions in production

- specs/ldml/tr35.html
> CLDR-11770 Document difference in key between RFC6067 and UTS35

- specs/ldml/tr35-collation.html
- specs/ldml/tr35-info.html
- specs/ldml/tr35-keyboards.html
- specs/ldml/tr35.html
Fixed broken links into CLDR repo, ICU User Guide, ISO 3166 codes, etc. There is at least one broken link to ICU demos that we cannot fix yet.
> CLDR-13243 BRS 36: Fix TR35 broken links (to CLDR repo, ICU User Guide, ...)

- specs/ldml/tr35-collation.html
- specs/ldml/tr35-dates.html
- specs/ldml/tr35-general.html
- specs/ldml/tr35-info.html
- specs/ldml/tr35-keyboards.html
- specs/ldml/tr35-numbers.html
- specs/ldml/tr35.html
Commit the de-yellowed TR35 files from Rick, after restoring unix line endings and fixing a few more broken links into the CLDR repository.
> CLDR-13243 BRS 36: TR35 remove yellow, fix a few more broken links to repo

- tools/build.xml
- tools/scripts/distUpdateExcludes.sh
[CLDR-13243]
Update tools that create the ZIP files to use git instead of svn, and update version used to 36.
> CLDR-13243 Update zip utilities to use git instead of SVN

- tools/cldr-apps/.classpath
- tools/cldr-apps/WebContent/WEB-INF/tmpl/row.jsp
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/test/TestCache.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/XMLSource.java
-Avoid re-creating ExampleGenerator with each http request
-Get DataSection.nativeExampleGenerator from a cache, on a per-locale basis
-Add failureaccess.jar to cldr-apps/.classpath for guava Cache
-DataSection.make consistently use session.user not ctx.session.user
-New TestCache.getExampleGenerator and exampleGeneratorCache (CacheBuilder)
-New ExampleGenerator.updateCache
-Implement disableCache methods for several objects for testing/debugging
-Test where changing the value of one path changes example-generation for another path
-New experimental TestExampleGeneratorDependencies in TestExampleGenerator.java
-Remove unused hasExamples, always true
-Move some code into subroutines, e.g., updateTestResultCache
-Rename cache to testResultCache for clarity
-Rename more items for clarity and …
> CLDR-13347 DataSection performance

- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestSTFactory.java
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/data/TestSTFactory.xml
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
-In getResolverInternal call CLDRFile.getConstructedBaileyValue as DataSection does
-New regression test in TestSTFactory.xml
-Use getSourceLocaleIdExtended with skip=false to avoid spurious warning in TestSTFactory.xml
-Comments
> CLDR-13390 Votes for identical inheritance and hard values

- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocale.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
- tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/util/TestUtilities.java
-Remove third parameter of getExampleHtml
-Replace public ExampleType with private boolean typeIsEnglish
-Simplify and shorten ExampleGenerator cache key
-No loop on ExampleType in checkPathValue
-Euro sign instead of USD for Italian currency example in unit test
> CLDR-13330 Make ExampleGenerator simpler, faster by removing ExampleType

- docs/ldml/tr35-collation.html
- docs/ldml/tr35-dates.html
- docs/ldml/tr35-general.html
- docs/ldml/tr35-info.html
- docs/ldml/tr35-keyboards.html
- docs/ldml/tr35-numbers.html
- docs/ldml/tr35.html
Updated to "proposed update" wording in headers, added yellow for that. Bumped revision to 58 and version to 37, dates to 2019-10-30.
Did a few minor HTML edits after link-checking, especially adding review notes for link errors that should be fixed by "owners" of the various parts before the release of CLDR 37.
> CLDR-13400 Update boilerplate for proposed update UTS #35 for CLDR 37 release

- seed/main/ba.xml
- seed/main/co.xml
- seed/main/gaa.xml
- seed/main/gn.xml
- seed/main/io.xml
- seed/main/jbo.xml
- seed/main/kaj.xml
- seed/main/kcg.xml
- seed/main/kpe.xml
- seed/main/nqo.xml
- seed/main/ny.xml
- seed/main/scn.xml
- seed/main/trv.xml
- seed/main/wa.xml
Add language autonyms for 14 seed locales that lack them. The names are from sources such as Wikipedia. For locales that already had other language names in a particular form (such as trv Taroko), match that form.
> CLDR-13422 Add autonyms for 14 seed locales that lack them

- common/subdivisions/af.xml
- common/subdivisions/az.xml
- common/subdivisions/ca.xml
- common/subdivisions/cy.xml
- common/subdivisions/da.xml
- common/subdivisions/es.xml
- common/subdivisions/et.xml
- common/subdivisions/eu.xml
- common/subdivisions/fi.xml
- common/subdivisions/gl.xml
- common/subdivisions/hr.xml
- common/subdivisions/id.xml
- common/subdivisions/it.xml
- common/subdivisions/ms.xml
- common/subdivisions/nb.xml
- common/subdivisions/pt.xml
- common/subdivisions/ro.xml
- common/subdivisions/sq.xml
- common/subdivisions/sv.xml
- common/subdivisions/sw.xml
- common/subdivisions/tr.xml
- common/subdivisions/uz.xml
- common/subdivisions/vi.xml
- common/subdivisions/yo.xml
- tools/java/org/unicode/cldr/util/data/external/subdivisionData.txt
https://en.wikipedia.org/wiki/Odisha
State officially changed name from Orissa to Odisha: http://indiatoday.intoday.in/story/orissa-to-odisha-negotiable-instruments-act/1/158874.html
> CLDR-13426 Update Orissa state name to Odisha

- common/main/ks_Arab.xml
- common/main/ks_Arab_IN.xml
- common/main/sd_Arab.xml
- common/main/sd_Arab_PK.xml
- common/supplemental/likelySubtags.xml
- common/supplemental/plurals.xml
- common/supplemental/supplementalData.xml
- common/supplemental/supplementalMetadata.xml
- seed/main/hi_Latn.xml
- seed/main/hi_Latn_IN.xml
- seed/main/ks_Deva.xml
- seed/main/ks_Deva_IN.xml
- seed/main/mni.xml
- seed/main/mni_Beng.xml
- seed/main/mni_Beng_IN.xml
- seed/main/mni_Mtei.xml
- seed/main/mni_Mtei_IN.xml
- seed/main/sat.xml
- seed/main/sat_Deva.xml
- seed/main/sat_Deva_IN.xml
- seed/main/sat_Olck.xml
- seed/main/sat_Olck_IN.xml
- seed/main/sd_Deva.xml
- seed/main/sd_Deva_IN.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestInheritance.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocale.java
- tools/java/org/unicode/cldr/test/CheckForCopy.java
- tools/java/org/unicode/cldr/util/data/language_script_raw.txt
- Add seed locales for hi_Latn, ks_Deva, mni_Mtei, sat, sat_Deva, sd_Deva (and default content sublocales). hi_Latn is reasonably fleshed out, the others typically have just exemplars, autonyms, and maybe standard date/time formats.
- Replace default content common ks_IN and sd_PK with ks_Arab, ks_Arab_IN, sd_Arab, sd_Arab_PK; replace default content seed mni_IN with mni_Beng and mni_Beng_IN.
- Change language_script_raw to make Olck the default script for sat (instead of Latn), and to add Latn as a script for hi; update likelySubtags accordingly.
Note that the aux exemplars for hi_Latn are the result of running the hi (Deva) exemplars through the Devanagari-Latin transform, and stripping a-z.
> CLDR-13378 seed locales for hi_Latn, ks_Deva, mni_Mtei, sat, sat_Deva, sd_Deva

- common/dtd/ldml.dtd
- common/dtd/ldmlBCP47.dtd
- common/dtd/ldmlSupplemental.dtd
- keyboards/dtd/ldmlKeyboard.dtd
- readme.html
- tools/java/org/unicode/cldr/util/CLDRFile.java
Update CLDR version to 36.1 (dtds and CLDRVersion), update Unicode version to 13.0 (supplemental dtd), update readme.
Note that this PR targets the maint/maint-36 branch, not master.
> CLDR-13431 Update CLDR version (to 36.1), Unicode version (to 13.0), readme

- tools/cldr-unittest/build.xml
[CLDR-13415]
Use -z build for testing during ST submission.
[CLDR-13415]: https://unicode-org.atlassian.net/browse/CLDR-13415
> CLDR-13415 SBRS Task S16 - Use -z build during ST phase

- common/main/ar.xml
- common/main/ca.xml
- common/main/da.xml
- common/main/de.xml
- common/main/de_CH.xml
- common/main/en.xml
- common/main/fi.xml
- common/main/fr.xml
- common/main/hi.xml
- common/main/hr.xml
- common/main/hu.xml
- common/main/ja.xml
- common/main/ko.xml
- common/main/nb.xml
- common/main/nl.xml
- common/main/pl.xml
- common/main/pt.xml
- common/main/pt_PT.xml
- common/main/ro.xml
- common/main/ru.xml
- common/main/sv.xml
- common/main/th.xml
- common/main/tr.xml
- common/main/uk.xml
- common/main/vi.xml
- common/main/zh.xml
- common/main/zh_Hant.xml
The idea is to make available forms of the names for "ars" (Najdi Arabic) and "ckb" (Central/Sorani Kurdish) that make them sort with other related languages (e.g. Arabic, Kurdish); this is similar to what was done in [CLDR-11834](https://unicode-org.atlassian.net/browse/CLDR-11834) to have name variants that would sort Chinese languages together, e.g. `<language type="yue" alt="menu">Chinese, Cantonese</language>`
For "ars", if the current standard name is not already in a form like "Arabic, Najdi", then add an alt="menu" item that is in that form.
For "ckb" the choices are more complicated:
- If the current standard name is already in a form like "Kurdish, Sorani" then do nothing.
- If the current standard name is already in a form like "Sorani" or "Sorani Kurdish" then add an …
> CLDR-13421 Add some alt=menu/variant names for ars, ckb

- tools/cldr-apps/WebContent/WEB-INF/tmpl/ajax_status.jsp
-Fix userIsLocked in ajax_status.jsp in straightforward way
> CLDR-9560 spurious account-is-locked for guest users

- tools/cldr-unittest/src/org/unicode/cldr/api/AllTests.java
- tools/cldr-unittest/src/org/unicode/cldr/api/CldrFileDataSourceTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/CldrPathTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/FilteredDataTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/PathMatcherTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/PrefixVisitorTest.java
- tools/cldr-unittest/src/org/unicode/cldr/api/XmlDataSourceTest.java
- tools/java/org/unicode/cldr/api/CldrData.java
- tools/java/org/unicode/cldr/api/FilteredData.java
- tools/java/org/unicode/cldr/api/PathMatcher.java
- tools/java/org/unicode/cldr/api/PrefixVisitorHost.java
These utilities are needed for the upcoming pseudo-locale support (moving from ICU project).
The PathMatcher API is intended to be fairly "final" at this stage. There's still a somewhat different/worse PathMatcher API in the ICU project, but I'll be migrating the ICU tools across to use this version later.
As such there's still the potential for an additional method or two being added to that class, but the methods that are already there should be stable, so please give it a look as regards docs and behaviour.
The FilteredData class is much simpler, but definitely not stable yet (as explained in the docs). However it's needed for the pseudo-locale support (coming soon) _and_ the alternate path support (which is for now staying in ICU project). This is why this is a public class, which I …
> CLDR-13388 Importing copies of various utilities into CLDR API

- tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
[CLDR-13468]
- Contention between makeVettedFile() and voteForValue()
makeVettedFile grabs lock on STFactory via get() and then PerLocaleData (for parent locale).getFile()
voteForValue is synchronized on PLD and later grabs lock on STFactory via get()
Solution is to, soon after PLD c'tor, initialize the resolved and unresolved CLDRFiles.
[CLDR-13468]: https://unicode-org.atlassian.net/browse/CLDR-13468
> CLDR-13468 fix deadlock between STFactory and PerLocaleData

- tools/java/org/unicode/cldr/test/SubmissionLocales.java
- tools/java/org/unicode/cldr/util/VettingViewer.java
-Use baselineFile.getUnresolved().getWinningValue() for oldValue
-Bug fix: status was uninitialized in getMissingStatus; call getSourceLocaleID, use local variable not parameter
-Comments
> CLDR-13457 Dashboard does not show all Error/Missing/New... values

- common/supplemental/pluralRanges.xml
- common/supplemental/plurals.xml
Add "pcm" Nigerian Pidgin to plurals/pluralRanges in same category as "en"
> CLDR-13455 Add "pcm" Nigerian Pidgin to plurals/pluralRanges

- common/supplemental/supplementalMetadata.xml
- seed/main/pcm.xml
- seed/main/pcm_NG.xml
The pcm xml data is the same as provided by Craig via e-mail 2019-Dec-11, except that:
- I made the locale display names draft="unconfirmed"
- The day names supplied as "narrow" were really "abbreviated", so I made them that
- The supplied unit patterns were only for width "full"; but for units the only required width is "short" so I made them that.
"pcm" entries already exist in likelySubtags, territoryInfo, etc. Just needed a defaultContent for pcm_NG.
I removed a now-obsolete file exemplars/main/pcm.xml (the PR incorrectly shows this as a rename to the newly added default content file seed/main/pcm_NG.xml)
> CLDR-13299 Add new seed locale "pcm" Nigerian Pidgin, delete old exemplars

- seed/main/gez.xml
Added U+129B to ges (Geez) aux exemplars per discussion in the JIRA ticket.
> CLDR-13492 gez, add U+129B to aux exemplard

- tools/java/org/unicode/cldr/test/SubmissionLocales.java
- tools/java/org/unicode/cldr/util/data/Locales.txt
I am not sure both sets of changes here are absolutely required, but having both should ensure that these locales are enabled for submission. We can clean up later.
> CLDR-13503 Add cad,pcm to NEW_CLDR_LOCALES and CLDR locales

- tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/surveytool.css
-Skip updateRow in insertRowsIntoTbody for rows whose single-row responses are pending
-Identify such rows by HTML classes tr_checking1 and tr_checking2
-When user clicks to vote, change class immediately to tr_checking1
-Style for tr_checking1 (orange) similar to tr_checking2 (green)
-Delete style for unused HTML class tr_checking
-Rename refreshRow2 to refreshSingleRow for clarity, and remove unused param vHash
-In refreshSingleRow use surveySessionId not (equivalent) tr.theTable.session, for consistency
-Comments
> CLDR-13522 Latency in recognizing clicks and turning into votes

- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/surveytool.css
-Ensure row drops orange tr_checking1 class for all server responses
-Reduce problem with rows changing position due to css cell padding
-Remove unused function handleCancelWiredClick
-Comments
> CLDR-13522 Latency in recognizing clicks

- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
-If item matching inheritedValue already added, still must do setTests
-Comments
> CLDR-13551 Error in Other column, same value in Winning column

- tools/cldr-apps/src/org/unicode/cldr/web/VettingViewerQueue.java
- tools/java/org/unicode/cldr/util/VettingViewer.java
-For changedOldValue, rename New (N) to Changed (C), and rename last-release to baseline
-Fix some warnings by deleting unused parameter nonVettingPhase
-Remove unused old temporary debugTimeStamp from json
-Delete some old commented-out dead code
-Comments
> CLDR-13457 Dashboard rename New to Changed

- seed/main/pcm.xml
In pcm week-of patterns: Fix curly quotes to be straight quotes, and in the pattern for "yw" change 'W' to 'w'
This fixes 3 of the ~60 errors in master, Mark is fixing the rest (which are all same-as-code errors)
> CLDR-13572 pcm, fix quotes and use of w/W in week-of patterns

- common/supplemental/languageInfo.xml
https://unicode-org.atlassian.net/browse/CLDR-13577
FYI On the ticket, Doug Ewell added a comment about mn-Latn. I don't see a mandate from CLDR-TC one way or another on that one, so I omitted that.
> CLDR-13577 languageMatch data: more script variant fallbacks

- common/rbnf/nn.xml
cf. https://ordbok.uib.no/perl/ordbok.cgi?OPP=millionar&nynorsk=+
> CLDR-13554 correct nn spelling of millions and up for rbnf 

- seed/main/kpe.xml
- seed/main/kpe_GN.xml
- seed/main/moh.xml
- seed/main/ny.xml
- seed/main/ss_SZ.xml
- seed/main/st_LS.xml
Filed a separate JIRA issue CLDR-13589 to catch other cases like this in the future.
> CLDR-13494 Add missing std time formats to match region time prefs

- common/main/da.xml
- common/main/fi.xml
- common/main/th.xml
Fix problems with intervalFormats for GyM* skeletons introduced in CLDR 36 for 3 locales:
- da, restore consistent use of separator '.' for gregorian formats, matching similar formats
- fi, add entries for MMMM mapping to MMMM, since MMM is now mapping to M. Model on patterns for yMMMM*
- th, restore use of G in gregorian patterns for GyM* skeletons, modeled on the generic patterns.
> CLDR-13592 BRS37 da,fi,th: fix problems with intervalFormats for GyM* skeletons

- common/main/ne.xml
[CLDR-11998]
Use 3,2 number formatting (lakhs), for Nepalese.  
[CLDR-11998]: https://unicode-org.atlassian.net/browse/CLDR-11998
> CLDR-11998 Modify Nepalese to use 3,2 number formatting same as India

- tools/cldr-apps/WebContent/js/survey.js
-Change err to error twice in processXhrQueue
-Do not use .call() in myErr0
> CLDR-13588 Fix bug in js ajax error handler, err should be error

- common/main/yo.xml
Yoruba (yo) had a bad metazone value "↑↑↑" for Mexico_Northwest which caused a failure in GenerateProductionData. Fixed by using pattern of other daylight/standard names.
> CLDR-13591 BRS37 yo, fix bad metazone

- common/main/ff_Adlm_GH.xml
- common/main/ff_Adlm_GM.xml
- common/main/ff_Adlm_LR.xml
- common/main/ff_Adlm_MR.xml
- common/main/ff_Adlm_SL.xml
Five of the regional locales for ff_Adlm (for GH, GM, LR, MR, SL) did not have time formats matching the preferred cycle for their region: they inherited from ff_Adlm (for GN) which had format using 'H', while their reion preferred format using 'h'. Fortunately the parallel ff_Latn regional locales did already have the necessary time formats, so just copy from those.
> CLDR-13591 BRS37 For 5 regions *, copy time fmts from ff_Latn_* to ff_Adlm_*

- common/main/mai.xml
Maithili (mai) uses certain vowel matras, 093E-0942, 0947-0948, 094B-094C (a subset of those used by Hindi); see for example https://www.omniglot.com/writing/maithili.htm. However, these are currently missing in the Maithili exemplars. And some of these are used in the Maithili locale data (e.g. 093F,0940,0948 used in calendar symbol and language names), so that the ICU tests produce "characters not in the exemplars" errors.
Just add the missing exemplars (copied the necessary subset from the Hindi exemplars).
> CLDR-13591 BRS37 add missing vowel matras to mai exemplars

- common/supplemental/units.xml
- common/testData/units/unitsTest.txt
We had agreed to map "part-per-million" to "permillion", but this was not reflected in units.xml.
Reasons to replace this one:
1. "-per-" is a reserved syntax.
2. More consistent with "percent", "permille", and "permyriad".
> CLDR-13620 Add permillion alias to units.xml

- common/main/mai.xml
- common/main/sd_Deva.xml
Fix exemplar set issues caught by ICU exhaustive tests.
1. For mai: Per Omniglot (and CLDR data for 093C), mai exemplars need to add 093C, 0902, 0903.
2. For sd_Deva: Per CLDR data, sd_Deva exemplars need to add 0902.
> CLDR-13591 BRS37 add exemplars 093C,0902,0903 for mai, 0902 for sd_Deva

- common/segments/root.xml
Update the CLDR segment rules for ICU 67 (and 66) => Unicode 13 updates, whch essentially means rolling in the relevant changes in:
- https://www.unicode.org/reports/tr14/tr14-44.html#TailorableBreakingRules
- https://www.unicode.org/reports/tr29/tr29-36.html#Word_Boundaries [no effect on CLDR]
I also checked the relevant diffs in the ICU repository using
`git diff release-65-1 icu4c/source/data/brkitr/rules/
`
(but note that changes related to ICU dictionary break do not apply to CLDR)
> CLDR-13591 BRS37 update CLDR segment rules for Unicode 13

- common/supplemental/languageInfo.xml
https://unicode-org.atlassian.net/browse/CLDR-13625
> CLDR-13625 Macedonian should not fall back to Bulgarian

- common/main/ms_ID.xml
- common/supplemental/likelySubtags.xml
- common/supplemental/supplementalData.xml
- tools/java/org/unicode/cldr/util/data/country_language_population_raw.txt
Changed ms usage in ID from ms_arab 4.6% of population to
ms[_Latn] 3.4%, ms_Arab 1.2% based on the data and calculations  in the JIRA ticket. This may still slightly overstate the ms_Arab usage (local sources say most ms_ID writing is in Latn) but at least it gets the likelySubtags right (still asking for more usage data from local sources).
Also added ms_ID locale. This needed to be more than a pure stub (inheriting from ms which defaults to region MY) since:
- The two regions have different preferred time cycles, h for MY vs H for ID
- The two regions have different time separators, : for MY vs . for ID
- And since I was making those changes, also supported the differences in standard date formats
Just copied the necessary items from the "id" locale (defaults to region ID).
> CLDR-13639 update territoryInfo for ms in ID; add ms_ID

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleDependencies.java
-Revise TestExampleGeneratorDependencies and related code
-Look through all locales, skip if json file already exists
> CLDR-13636 Make ExampleGenerator faster, clear cache less

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
- tools/java/org/unicode/cldr/test/CheckDates.java
- tools/java/org/unicode/cldr/test/CheckLogicalGroupings.java
- tools/java/org/unicode/cldr/tool/CLDRModify.java
- tools/java/org/unicode/cldr/tool/GenerateProductionData.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/LogicalGrouping.java
-Change all callers to allow for null return
-Return null instead of empty new TreeSet if path is null
-Comment TODO: should we ever return null instead of singleton here?
> CLDR-12023 Speed up LogicalGrouping.getPaths return null not empty

- tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAnnotations.java
-Make TestAnnotations/TestUniqueness twice as fast using parallelStream
-Make STFactory.get faster using guava Cache instead of deprecated LruMap
> CLDR-11786 Speed up tests with parallel streams

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
-Make TestCheckCLDR/TestAllLocales a few seconds faster using parallelStream
> CLDR-11786 Accelerate TestAllLocales with parallel streams

- docs/ldml/tr35-numbers.html
- docs/ldml/tr35.html
Updated spec example of currencySpacing data to match the current root data, to avoid confusion. Also fixed HTML validation errors from earlier spec changes.
> CLDR-13571 fix currencySpacing example in spec to match current root data

- docs/ldml/tr35-general.html
- docs/ldml/tr35.html
Added some info on unitPatterns in tr35-general that I hope is helpful, partly in addressing some of the issues raised in the JIRA ticket:
1. Near the beginning of section 6 Unit Patterns, added:
> The <unitPattern> elements may be used to format quantities with decimal values; in such cases the choice of plural form will depend not only on the numeric value, but also on its formatting (see Language Plural Rules). In addition to formatting units for stand-alone use, <unitPattern> elements are increasingly being used to format units for use in running text; for such usages, the new Grammatical Features information will be very useful.
> 
> Note that for certain plural cases, the unit pattern may not provide for inclusion of a numeric value—that is, it may not include “{0}”. This is …
> CLDR-11350 Added some clarifications on use of unitPatterns

- docs/ldml/tr35-dates.html
> CLDR-13501 Fix typo in TR 35, part 4, section 2.1

- common/main/su.xml
In locale "su", delete bogus data (display name and plural name) for currency "XXX". We cannot just set those values to XXX since that causes CLDR errors ("name same as code"). But deleting the data will have the same result.
> CLDR-13668 su, delete bogus data for currency XXX

- tools/cldr-apps/WebContent/WEB-INF/tmpl/ajax_status.jsp
-Add async: true in dojoConfig, fix warning XMLHttpRequest with the synchronous flag set to true is deprecated
> CLDR-11687 Update Dojo, async true

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCompactNumbers.java
- tools/java/org/unicode/cldr/test/BuildIcuCompactDecimalFormat.java
- tools/java/org/unicode/cldr/util/VerifyCompactNumbers.java
> CLDR-13630 Fix verification chart for numbers

- tools/cldr-apps/WebContent/js/survey.js
-Fix the syntax so that stui.sub returns a value
-Combine dojo/string and dojo/i18n...stui.js in the same require array
-Ensure null or empty template is not passed to string.substitute
-Comments
> CLDR-11687 Update Dojo, fix syntax for require dojo/string for stui.sub

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
-Use the query string method like survey.js?v=5f1f23b
-Change INCLUDE_SCRIPT_VERSION to true in SurveyAjax.java
-Comments
> CLDR-13582 Make browser use most recent JavaScript files

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
-Set CLDR_APPS_HASH variable in getCurrevCldrApps to avoid repeating getGitHashForSlug
-Insert space in log message, was like Updated CLDR_APPS_HASH toc18023938
-Delete some commented-out code
> CLDR-13669 CLDR_APPS_HASH null, time wasted repeating getGitHashForSlug

- tools/cldr-apps/WebContent/js/redesign.js
- tools/cldr-apps/WebContent/surveyTool/nls/stui.js
[CLDR-9326]
The prior patch didn't take coverage into account.
This puts a static message in the sidebar when there's no coverage.
[CLDR-9326]: https://unicode-org.atlassian.net/browse/CLDR-9326
> CLDR-9326 show 'no items at this coverage level' in the sidebar

- docs/ldml/tr35-general.html
- docs/ldml/tr35-info.html
- docs/ldml/tr35.html
Updated spec for deprecated dtd items. There was really only one that affected the spec: The scope attribute for &lt;unitPreferences&gt;, which was deprecated in favor of the geq attribute for &lt;unitPreference&gt;.
Also fixed unrelated validation errors.
> CLDR-13591 Update spec for deprecated unitPreferences item, fix validation errs

- tools/java/org/unicode/cldr/json/JSON_config_supplemental.txt
- tools/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
[CLDR-13725]
Update for JSON conversion utilities for 37
1. Skip units and grammaticalFeatures stuff for now.  There is just too much there. If someone needs this in JSON format then the tools will need to be modified to accommodate that, but it will take more than the one day that I have now.  Side effect is that the unitPreferenceData goes away, but the structure is so different now that this will have to be addressed later.
2). Add subdivisionAlias from supplementalMetadata.
[CLDR-13725]: https://unicode-org.atlassian.net/browse/CLDR-13725
> CLDR-13725 Skip units/grammaticalFeatures and add subdivisionAliases

- tools/java/org/unicode/cldr/util/data/africa
- tools/java/org/unicode/cldr/util/data/asia
- tools/java/org/unicode/cldr/util/data/europe
Previous PR #440 added tzdata 2020a files, but they include negative offsets from standard time. There is an existing CLDR tool code asserting such data. So when you run CLDR tools with `-ea` (enable assertions), it will stop because of the assertion code.
TZ database provide an option for modifying data not including such negative offsets (`rearguard` version). This PR includes a few modified zone data files produced by the build target, instead of original ones.
> CLDR-13739 Changed some tzdata files to rear-guard version.

- tools/cldr-apps/WebContent/WEB-INF/tmpl/ajax_status.jsp
- tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/surveyTool/nls/stui.js
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestAll.java
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestSTFactory.java
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/org/unicode/cldr/web/Race.java
- tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/java/org/unicode/cldr/test/CheckCLDR.java
- tools/java/org/unicode/cldr/test/CheckForCopy.java
- tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/java/org/unicode/cldr/test/EmojiSubdivisionNames.java
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/util/VoteResolver.java
-Split CheckForCopy.handleCheck into subroutines sameAsCodeOrEnglish, addFailure
-New function CheckForCopy.sameAsCode, called by submitVoteOrAbstention, valueCanBeAutoImported, viewOldVotes, handleBulkSubmit
-New CheckCLDR.StatusAction.FORBID_CODE
-Rename ERROR_NO_WINNING_VALUE (error-no-winning-value) to NO_WINNING_VALUE (no-winning-value)
-On client, silently accept NO_WINNING_VALUE as placeholder, but do not display it
-Also do not display [no value] as was displayed for undefined value or inheritedValue
-Move createVoter outside its calling function; misc. js clean-up
-Call setDisplayInformation in cldr-apps TestAll.main to fix null in CheckForCopy.handleCheck
-In CheckForCopy.handleCheck, throw InternalCldrException if getDisplayInformation null
-Fix bug and warning: …
> CLDR-13238 Disallow winning vote for inheritance from root

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
- tools/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
-New function DisplayAndInputProcessor.stripProblematicControlCharacters
-Strip out all code points less than U+0020 except for tab, line feed, and carriage return
-New test function TestDisplayAndInputProcessor.TestBackspaceFilter
> CLDR-13417 Fix invalid XML characters in annotations

- tools/java/org/unicode/cldr/test/CheckExemplars.java
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/util/RegexLogger.java
- tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
-Revise handleIntervalFormats to choose interval for B or b like a
-Revise SECOND_INTERVAL to include a date for G
-IntervalFormat.format swap as needed so earlier is earlier than later
-Return null in getExampleHtml if path ends with alias
-Stop catching NullPointerException in getExampleHtml
-Catch ICU NullPointerException in IntervalFormat.setPattern
-Fix several other places in the code to return no example rather than throw NullPointerException
-Fix getDefaultCurrency to return XXX rather than throw NullPointerException
-CheckExemplars.checkParse catch IllegalArgumentException but not every Exception
-Fix RegexLogger.StringIterableTransformer.transform to avoid NullPointerException
-Fix vararg warning for listFormatter.format
-Make class IntervalFormat private
-Suppress some ICU …
> CLDR-13667 NullPointerException in ExampleGenerator and others

- tools/cldr-unittest/build.xml
-Add -enableassertions (same as -ea) to JVM_EXTRA_OPTIONS in cldr-unittest/build.xml
> CLDR-11979 Enable assertion in cldr-unittest

- tools/cldr-apps/WebContent/js/CldrStForum.js
- tools/cldr-apps/WebContent/js/CldrStForumFilter.js
- tools/cldr-apps/WebContent/js/redesign.js
- tools/cldr-apps/WebContent/js/review.js
- tools/cldr-apps/WebContent/js/special/forum.js
- tools/cldr-apps/js-unittest/TestCldrStForum.js
- tools/cldr-apps/js-unittest/TestCldrStForumFilter.js
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
-Show Forum statistics summary in Dashboard and top of main Forum window
-New filters: Your open threads; Open threads you have not posted to; cf. CLDR-13610
-Change default filter from All threads to Open threads
-New functions cldrStForum.getForumSummaryHtml, loadForum, reload
-New functions cldrStForumFilter.getFilteredThreadCounts, updateCounts, clearCounts
-New reply status option: Information; cf. CLDR-13695
-Limit status options for responses; Agree/Disagree are only for Request
-Enforce reply has same locale and path as original post in thread; cf. CLDR-13695
-Use cldrStAjax for Forum instead of directly using dojo and jquery for ajax
-Move more code from forum.js to CldrStForum.js
-Change var to const or let where possible in strict code
-Enhance JS unit tests …
> CLDR-13615 Integrate work needed in the Forum into Dashboard

- common/dtd/ldml.dtd
- common/dtd/ldmlBCP47.dtd
- common/dtd/ldmlSupplemental.dtd
- keyboards/dtd/ldmlKeyboard.dtd
- readme.html
- tools/java/libs/icu4j-src.jar
- tools/java/libs/icu4j-version.txt
- tools/java/libs/icu4j.jar
- tools/java/libs/utilities-src.jar
- tools/java/libs/utilities.jar
- tools/java/org/unicode/cldr/util/CLDRFile.java
* Update dtd cldrVersion to 38
* Update CLDRFile.java GEN_VERSION to 38
* Update readme for v38 development version
* Update ICU4J libs to version release-67-1
> CLDR-13781 update CLDR version, readme; update ICU4J libs to release-67-1

- tools/cldr-apps/WebContent/css/CldrStForum.css
- tools/cldr-apps/WebContent/js/CldrStForum.js
- tools/cldr-apps/WebContent/js/CldrStForumFilter.js
- tools/cldr-apps/WebContent/js/review.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/surveytool.css
- tools/cldr-apps/WebContent/v.jsp
- tools/cldr-apps/js-unittest/TestCldrStForum.js
- tools/cldr-apps/src/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
-Votes cause auto-generated Agree post(s)
-Revise prefill texts for post types
-Disable editing of subject (path-header)
-Display status Open or Closed at top of thread
-Separate posts in thread with horizontal rules; no lines along left
-New replies always have parent == root (original) post
-New filters: Needing action; Open requests by you; remove most other filters
-Show Summary at top of Section window (progress area)
-Space between buttons with margin in css; other css improvements
-Add four columns to the FORUM_POSTS table: root, type, open, value
-Remove the FORUM_TYPES table, revise related code to use FORUM_POSTS
-New object SurveyForum.PostInfo for encapsulation, fewer function params
-Set open=false for all posts in thread when get PostType.CLOSE
-Move doPostInternal and …
> CLDR-13695 Define stages of a forum thread

- common/dtd/ldml.dtd
- common/main/be.xml
- common/main/de.xml
- common/main/fr.xml
- common/main/ja.xml
- common/main/ka.xml
- common/main/root.xml
- common/main/ru.xml
- common/main/sq.xml
- common/supplemental/coverageLevels.xml
- docs/ldml/tr35-numbers.html
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/util/PathHeader.java
To prepare this PR, I searched for all occurrences of "superscriptingExponent", and added similar entries for the new element, "approximatelySign".
I populated root.xml, plus all locales whose symbol differs in the existing approximately pattern.  I didn't touch the other 1000+ XML files where the fallbacks are redundant.  Do I need to touch up all of those files, and if so, what's the most efficient way to do it?
> CLDR-11431 Add approximatelySign to LDML number symbols

- common/annotations/en.xml
- common/annotations/root.xml
- common/main/root.xml
> CLDR-13705 remove redundant currency symbols (will be derived)

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCldrFactory.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleDependencies.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPerf.java
- tools/java/org/unicode/cldr/icu/CheckIBMCoverage.java
- tools/java/org/unicode/cldr/tool/CLDRCompare.java
- tools/java/org/unicode/cldr/tool/CLDRFormat.java
- tools/java/org/unicode/cldr/tool/CLDRModify.java
- tools/java/org/unicode/cldr/tool/CompareEn.java
- tools/java/org/unicode/cldr/tool/CountItems.java
- tools/java/org/unicode/cldr/tool/GenerateCasingChart.java
- tools/java/org/unicode/cldr/tool/GenerateComparison.java
- tools/java/org/unicode/cldr/tool/GenerateEnums.java
- tools/java/org/unicode/cldr/tool/ShowData.java
- tools/java/org/unicode/cldr/tool/ShowLanguages.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/DtdDataCheck.java
- tools/java/org/unicode/cldr/util/MatchValue.java
- tools/java/org/unicode/cldr/util/PathHeader.java
Mostly automatic via IntelliJ and inlining of methods for addAll(), but some changes needed since it’s better to say:
iterable.forEach(thing::add)
than:
iterator.forEachRemaining(thing::add)
where possible (and the original utilities class took iterators rather than iterables).
The asMap() changes were manual since there were so few.
> CLDR-13750 Refactoring collection utilities (part 2, addAll and asMap)

- tools/cldr-unittest/src/org/unicode/cldr/unittest/ObjectMatcherFactory.java
- tools/java/org/unicode/cldr/test/CheckAttributeValues.java
- tools/java/org/unicode/cldr/util/props/UnicodeProperty.java
- tools/java/org/unicode/cldr/util/props/UnicodePropertySymbolTable.java
Replace CollectionUtilities.ObjectMatcher with JDK Predicate and handle subclasses (e.g. RegexMatcher). Note that some of the other matchers in CheckAttributeValues can now probably be simplified to inlinable lambdas (which I'd happily do in a future PR).
This PR is a single commit, current stacked on other parts, so please only look at the most recent commit.
> CLDR-13750 Refactoring collection utilities (part 3, matchers)

- tools/java/org/unicode/cldr/test/CoverageLevel2.java
- tools/java/org/unicode/cldr/tool/GenerateCldrTests.java
- tools/java/org/unicode/cldr/util/LenientDateParser.java
- tools/java/org/unicode/cldr/util/XMLSource.java
Replace "containsSome()" and the FilteredIterator class with JDK utilities.
* containsSome() is just equivalent to a "disjoint" check.
* FilteredIterator is now trivially doable inline with streams and lambdas.
The “containsSome()” method is interesting because the old implementation went to great lengths to handle ordered sets efficiently, but in reality none of the sets given to it now were ordered, so that code was unused. Simply replaced with a check for “disjoint” from the JDK Sets class.
PrefixIterator was easy to change manually. The change does not appear to have made anything slower (e.g. running all unit tests).
> CLDR-13750 Refactoring collection utilities (part 4, contains/iterators)

- tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/java/org/unicode/cldr/test/TestMetadata.java
- tools/java/org/unicode/cldr/tool/CountItems.java
- tools/java/org/unicode/cldr/tool/GenerateAliases.java
- tools/java/org/unicode/cldr/tool/GenerateLanguageContainment.java
- tools/java/org/unicode/cldr/tool/GenerateSidewaysView.java
- tools/java/org/unicode/cldr/tool/LikelySubtags.java
- tools/java/org/unicode/cldr/tool/ListCoverageLevels.java
- tools/java/org/unicode/cldr/tool/SearchCLDR.java
- tools/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- tools/java/org/unicode/cldr/tool/SubdivisionNode.java
- tools/java/org/unicode/cldr/util/ICUServiceBuilder.java
This is an optional change to remove references to the now unused CollectionUtilities class from legacy comments. I'd be happy to go further and remove more legacy comments in these, or other, files if wanted.
> CLDR-13750 Removing obsolete comments relating to now unused CollectionUtilities class

- tools/cldr-apps/WebContent/surveyTool/nls/stui.js
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/java/org/unicode/cldr/util/VoteResolver.java
-Revise the URLs
-Encapsulate shared links for 3 reports in new writeReportInstructionsLink
-Keep http for now, pending support for https on cldr.unicode.org
> CLDR-13692 Broken links in reports

- tools/java/org/unicode/cldr/tool/GeneratePluralRanges.java
- tools/java/org/unicode/cldr/tool/WritePluralRules.java
- tools/java/org/unicode/cldr/util/PreferredAndAllowedHour.java
This replaces the custom logic for the CollectionUtilities methods with the recently added JDK Comparator(s) functionality. This method probably needs to be double checked against the com.ibm classes to ensure it's equivalent.
See: https://github.com/unicode-org/cldr/blob/master/tools/java/libs/utilities-src.jar
IMPORTANT: This is a clone of https://github.com/unicode-org/cldr/pull/462 which I had to abandon because of conflicting changes caused in the time that this PR has been awaiting review (a combination of the requirement to force squash branches and inability to cleanly merge recent changes).
This is one of the more subtle refactorings since it relies on human understanding of the existing (undocumented, non-trivial) comparison code. Luckily it has only a few uses, and the JDK …
> CLDR-13750 Replace custom comparison logic with JDK comparators

- tools/java/org/unicode/cldr/util/LanguageGroup.java
* Added Cebuano to "Austronesian"
* Created "Iranian" group, with languages in the Iranian family (Persian, Pashto, Kurdish, Ossetian)
* Created "Caucasian" group, for languages in the Northeast, Southeast, and South (Kartvelian) Caucasian families (note: currently only contains Georgian and Chechen)
* Reorganized code to be more readable
* Added all missing language tags from `common` and `seed`, for future-proofing
Note: This has been tested with `org.unicode.cldr.tool.ChartAnnotations`, everything looks good
> CLDR-13865 Fix language families for Annotation Charts

- tools/cldr-apps/WebContent/js/survey.js
-Return early from addVitem if displayValue is empty, to prevent exception in setLang
-That happened when appendItem returned undefined given empty displayValue
> CLDR-13872 Survey Tool en_GB, en_IN cannot load Symbols2

- docs/ldml/tr35.html
Clarify the language, region and script in the RemoveLikelySubtags are referring to the one inside the max by using 
subscript max. 
close https://unicode-org.atlassian.net/browse/CLDR-13749
> CLDR-13749 Clarify language/region/script

- docs/ldml/tr35.html
By the context, the one to be replaced should be region subtag, not language subtag.
> CLDR-13761 fix typo of language to region

- tools/cldr-apps/WebContent/tc-mzfix.jsp
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/org/unicode/cldr/web/XPathTable.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestBCP47.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPerf.java
- tools/java/org/unicode/cldr/draft/ExtractCountItems.java
- tools/java/org/unicode/cldr/draft/JsonConverter.java
- tools/java/org/unicode/cldr/json/CldrItem.java
- tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java
- tools/java/org/unicode/cldr/test/CheckNumbers.java
- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/test/TestMisc.java
- tools/java/org/unicode/cldr/tool/CLDRModify.java
- tools/java/org/unicode/cldr/tool/ChartDelta.java
- tools/java/org/unicode/cldr/tool/FilterFactory.java
- tools/java/org/unicode/cldr/tool/GenerateCoverageLevels.java
- tools/java/org/unicode/cldr/tool/GenerateItemCounts.java
- tools/java/org/unicode/cldr/tool/GenerateSidewaysView.java
- tools/java/org/unicode/cldr/tool/XMLModify.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/LogicalGrouping.java
- tools/java/org/unicode/cldr/util/PathStarrer.java
- tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/java/org/unicode/cldr/util/WikiSubdivisionLanguages.java
- tools/java/org/unicode/cldr/util/XMLSource.java
- tools/java/org/unicode/cldr/util/XPathParts.java
- Inline method XPathParts.getInstance() 
- XPathParts.getInstance() is expensive as it calls getFrozenInstance().cloneAsThawed(); Postpone calling cloneAsThawed() until needed to save time.
> CLDR-13857 Fix XPathParts.getInstance

- tools/java/org/unicode/cldr/test/CheckForCopy.java
-Treat year, month, day, and hour as exceptions to the rule
-Only if getSourceLocaleID is en or starts with en_
> CLDR-13873 in En_GB, vote to inherit month gets Same as Code error

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
-Suppress email for autoPostReplyAgree and autoPostReplyClose
-New boolean PostInfo.sendEmail with getter and setter, default true
-Comments
> CLDR-13896 Reconsider automatic forum entries

- tools/cldr-apps/WebContent/js/CldrSurveyVettingLoader.js
CLDR-13906
Not a fix, but adds a stack trace.
- show a stack trace for errors in the dreaded 'Exception while loading: section' message
- use error.stack where available to include a stack trace
> CLDR-13906 show a stack trace for loading: section

- tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
- tools/cldr-apps/src/org/unicode/cldr/web/DataSection.java
-Guard against accessing theRow.winningVhash if theRow is null or undefined
-Comments
> CLDR-13919 Error E_UNKNOWN interrupts data entry

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
- tools/java/org/unicode/cldr/test/CheckDisplayCollisions.java
-Do not delete required count attribute from unitPattern paths
-New TestCheckDisplayCollisions.testUnitPatternCollisions, mustCollide, checkUnknown
-Comments
> CLDR-13905 bogus link in error for dot unit

- tools/cldr-apps/WebContent/js/review.js
-Fix front end only to prevent crash; back end will be fixed separately
-If json has empty array, log message to console and return from insertFixInfo early
> CLDR-13937 es-419: Attempting to open provisional item via dashboard causes E_UNKNOWN

- common/main/root.xml
Adjust root currencySpacing to avoid inserting additional space if the currency symbol text already includes space  (e.g. "EUR ", which some clients have done).
> CLDR-13838 adjust root currencySpacing to avoid double space

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAttributeValues.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
- tools/java/org/unicode/cldr/util/StripUTF8BOMInputStream.java
- tools/java/org/unicode/cldr/util/XMLFileReader.java
- Remove FilterBomInputStream and use existing StripUTF8BOMInputStream as they do the same thing
- Faster XML reading by using BufferedInputStream in StripUTF8BOMInputStream
- Remove XML read code in CLDRFile.loadFromInputStream and use existing XMLFileReader.read
> CLDR-13857 Fix BufferedInputStream

- .github/workflows/ant.yml
- README.md
CLDR-13948
- uploads cldr.jar and cldr-apps.war as artifacts
ant.yml
- does not replace .travis.yml nor jenkins (yet)
README.md
- add status badge
> CLDR-13948 Github Action to build with Ant

- .github/workflows/ant.yml
This PR caches the Tomcat binary tarball so that the build process is more resilient to network/server issues.  Also, the workflow trigger condition is fixed to run on PRs from any branch.
> CLDR-13948 add caching for downloading Tomcat

- tools/cldr-apps/WebContent/js/review.js
CLDR-13994
- To fix a performance issue
- Semantic change: you can now hide unrelated review items without dismissing the popover.
> CLDR-13994 stop propagation of events from the .hide-review button to body

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCheckCLDR.java
- tools/java/org/unicode/cldr/test/CheckForExemplars.java
- tools/java/org/unicode/cldr/util/data/Placeholders.txt
Problem was that "multiple" also needs to count as "locale dependent". Only used in count/orginal minimal pairs.
> CLDR-14004 fix error for unique plural forms

- common/main/zh_Hant_HK.xml
zh_Hant_HK was just inheriting the aux exemplars from zh_Hant (it also inherits main exemplars from zh_Hant). Add its own aux exemplars which consist of all of the characters in zh_Hant aux exemplars plus 106 more from Big5 (90) and HKSCS (16) which are used in CLDR data. See discussion in JIRA ticket.
> CLDR-13939 zh_Hant_HK, add aux exemplars with chars in zh_Hant aux + 106 more from Big5/HKSCS

- tools/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/java/org/unicode/cldr/tool/Chart.java
- tools/java/org/unicode/cldr/tool/ChartDelta.java
-This PR has only preliminary minor improvements and clean-up
-ChartDelta: report when finished and report file-creation directories
-Remove duplicate new PathDescription from ExampleGenerator.java
-Avoid deprecation warning for DtdData.getInstance; cache getCldrBaseDirectory as CLDR_BASE_DIR
-Refactor to obviate single-line getValueSplitter; call DtdData.getValueSplitter directly instead
-Remove dead/unused code from ChartDelta.java and Chart.java, make private where possible
> CLDR-13306 cleanup ChartDelta and ExampleGenerator

- tools/java/org/unicode/cldr/tool/ChartDelta.java
CLDR-13306
-CLDR_BASE_DIR must be File not String to prevent mixup between two versions of DtdData.getInstance
> CLDR-13306 Data churn: Fix ChartDelta CLDR_BASE_DIR bug

- common/annotations/en.xml
This duplicate annotation was removed:
<annotation cp="⁄">stroke | virgule</annotation>
On at least one system, it creates an error.
> CLDR-13977 remove duplicate annotation in en.xml

- tools/cldr-unittest/src/org/unicode/cldr/unittest/CheckLanguageCodeConverter.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/LikelySubtagsTest.java
- tools/java/org/unicode/cldr/tool/ChartDelta.java
- tools/java/org/unicode/cldr/tool/FindPreferredHours.java
- tools/java/org/unicode/cldr/tool/LikelySubtags.java
- tools/java/org/unicode/cldr/util/CoreCoverageInfo.java
Speed up LikelySubtags initialization by making supplementalDataInfo, currencyToLikelyTerritory static, only need to initialize once
> CLDR-13857 Optimize LikelySubtags initilization

- tools/java/org/unicode/cldr/test/SubmissionLocales.java
- tools/java/org/unicode/cldr/tool/ChartDelta.java
-Replace DO_CHURN with highLevelOnly in MyOptions
-Encapsulate Delta vs Churn per highLevelOnly: dirName, chartNameCap
-New inner class HighLevelPaths determines which paths are high-level
-Match some paths exactly
-Match other paths with special functions like isHighLevelTerritoryName
-Check only locales in SubmissionLocales.CLDR_LOCALES; make that public
-Report on usage of highLevelPaths, with highLevelPathMatched
-Comments
> CLDR-13306 Generate disruptive data churn report

- tools/cldr-apps/WebContent/js/CldrStForum.js
- tools/cldr-apps/WebContent/js/CldrSurveyVettingTable.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
-Show forum posts in info panel if user is logged in (userExist)
-Hide info panel forum buttons if userCanPost (json.canModify) is false
-Do not hide buttons in main forum window (no change; possible TO-DO)
-On server, prevent post if SurveyMain.isPhaseReadonly
> CLDR-14067 Make forum visible even when ST is read-only

- common/main/sv.xml
sv: simplified and traditional translated out of context - is plural, should be singular
> CLDR-14085 sv script translation

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
- tools/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/java/org/unicode/cldr/test/XPathToMenu.java
This is some pre-work, since the name "PathUtilities" is perfect for a class to fix the normalized path problem, but already exists as a deprecated class for a possibly unused tool.
Moving for now is safe, unless someone wants me to nuke the tool as well (I'm always happy to delete code).
> CLDR-13918 Moving old (used once) PathUtilities file to make way for new version.

- common/dtd/ldml.dtd
- seed/collation/sa.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPaths.java
- tools/java/org/unicode/cldr/util/DtdData.java
CLDR-6746
- TestPaths needed to include seed and exemplars
- two files had deprecate formats, fixed.
I moved the normalization mode out of the deprecated options, and removed the deprecated draftiness on RBNF.
> CLDR-6746 TestPaths to include seed and exemplars

- seed/main/doi.xml
- seed/main/nv.xml
- seed/main/trw.xml
-With arg -fp, doi.xml, nv.xml, trw.xml have differences in exemplarCharacters
> CLDR-14093 BRS Task A05.5 : CLDRModify pass 3 seed/main

- tools/cldr-apps/src/org/unicode/cldr/web/OutputFileManager.java
CLDR-14044
a log statement wasn't behind the right check, nor did it call debug() as the other  instances did. Check context for related similar  calls.
> CLDR-14044 fix debug output in OutputFileManager

- common/supplemental/windowsZones.xml
I used data generation tool and the US Mountain Standard Time mapping data line for Canada was update becuase it contained extra spaces. There are no real changes except IANA tz database and Windows TimeZone versions.
> CLDR-14126 Updated tz version numbers in windowsZones.xml

- common/main/zh.xml
In zh:
- revert standard full time format from "zzzza h:mm:ss" to "zzzz ah:mm:ss" as in v37
- standard long already had "z ah:mm:ss", matching the reverted format (no change needed)
- availableFormats already matched this style (no change needed):
- &lt;dateFormatItem id="hmsv"&gt;v ah:mm:ss&lt;/dateFormatItem&gt;
- &lt;dateFormatItem id="Hmsv"&gt;v HH:mm:ss&lt;/dateFormatItem&gt;
- &lt;dateFormatItem id="hmv"&gt;v ah:mm&lt;/dateFormatItem&gt;
- &lt;dateFormatItem id="Hmv"&gt;v HH:mm&lt;/dateFormatItem&gt;
- some intervalFormats needed updating to be consistent with this style
> CLDR-14084 zh time fmt, revert full to match v37, make others consistent

- .github/workflows/ant.yml
- tools/cldr-apps/build.xml
- tools/cldr-unittest/build.xml
CLDR-13948
- restructure the 'ant' workflow, for parallel building
- on push to master, deploy to cldr-ref.
(This is on the main fork because of secrets, so i could try out deployment. )
> CLDR-13948 deploy to cldr-smoke2 on merge

- tools/cldr-apps/build.xml
- tools/cldr-apps/src/org/unicode/cldr/util/CLDRConfigImpl.java
- tools/java/build.xml
- tools/java/org/unicode/cldr/util/CLDRURLS.java
CLDR-11131
- store full git hash in war/jar and live fetch from CLDR_DIR
- show as 8 chars in UI
- this prevents false mismatches from 7, 8-char and 10-char hashes mismatching
so before this fix, cldr-smoke2  shows at the bottom:
> Version: utilities=8fb7d4c data=8fb7d4ca29 surveytool=8fb7d4c
There are three because they are ≠, otherwise it would show "the version". However, you can tell they are 7 and 10 character substrings of the _same hash_. This PR fixes this problem by keeping the whole hash around, and truncating at the UI side.
> CLDR-11131 record full git hash, shorten to 8 in UI

- tools/cldr-apps/WebContent/WEB-INF/tmpl/menu_top.jsp
I removed the <%! section containing the static fields (which are not referenced anywhere else in WEB-INF/ directory).
I really don't know how to test this though.
> CLDR-13918 Removing unused JSP references to deleted fields

- tools/scripts/ansible/README.md
- tools/scripts/ansible/hosts
- tools/scripts/ansible/roles.yml
- tools/scripts/ansible/setup-playbook.yml
- tools/scripts/ansible/templates/deploy-sh.j2
- tools/scripts/ansible/templates/index.html
- tools/scripts/ansible/templates/server.xml
- tools/scripts/ansible/test-local-vars/local.yml
- tools/scripts/ansible/vars/main.yml
CLDR-13771
this does the letsencrypt/nginx/proxy setup via ansible
- use cldr-smoke2 but leave cldr-ref out
- the autodeployment on merge is in PR#601 [CLDR-13948]
[CLDR-13948]: https://unicode-org.atlassian.net/browse/CLDR-13948
> CLDR-13771 playbook to include letsencrypt and deploy script

- common/main/de.xml
- common/main/doi.xml
- common/main/en_001.xml
CLDR data fixes from first ICU integration:
- de: compact decimals, revert formats for 1000,10000,100000 to use just 0 (as in PR-151), not formats with Tsd.
- doi: remove colon from main exemplars (it is already in puntuation exemplars)
- en_001: remove time formats using H copied from en_GB (so we inherit formats with h from en), to preserve time formats for chile locales and to match supplemental data which has h for 001
> CLDR-14128 data fixes for de, doi, en_001 from first ICU integration

- common/main/en_001.xml
As discussed in CLDR TC, revert some of the en_001 changes from [PR-620](https://github.com/unicode-org/cldr/pull/620), just as we did with [PR-168](https://github.com/unicode-org/cldr/pull/168) in CLDR 36:
- standard time formats: we already deleted the standard time formats with H in [PR-682](https://github.com/unicode-org/cldr/pull/682)
- availableFormats, intervalFormats: For some cases of formats that were already in en_001 but replaced by formats from en_GB, restore the formats that were in en_001 to preserve (for other en_001 child locales) use of commas after weekdays, and more compact formats for day ranges within months.
- units:: fl oz, US vs Imp; en assumed US, GB assumed Imp. 001 should assume neither and make both explicit. (we did not discuss doing this in TC, but doing it …
> CLDR-14128 revert en_001 changes for date formats and fluid-ounce-imperial as in PR-168

- common/main/en_001.xml
- common/main/en_AE.xml
- common/main/et.xml
There were a few generic-calendar availableFormats items that used '.' instead of ':' between mm and ss in some cases when all of the other time formats in the locale (including all gregorian items) used ':'; fixed:
- en_001, one item for Bhms
- en_AE, one item for Bhms (probably copied from en_001)
- et, items for hms, Hms, ms
> CLDR-14129 fix mm.ss -> mm:ss in en_001, en_AE, et

- tools/java/org/unicode/cldr/tool/CompareFilesBetweenReleases2.java
CLDR-14148
- only show 'files', not directories
- report items migrating between seed/common
- show the version that was compared
- show the real paths being compared
Example run: https://gist.github.com/srl295/9ccf97f6ca2a8c0a01b12588c8e4bde5
> CLDR-14148 improve CompareFilesBetweenReleases

- common/main/zh.xml
in zh, short dates in japanese/roc calendars should use single y instead of yy. All other short dates in zh, zh_Hant (ncluding roc), ja (including japanese) and yue already use single y.
> CLDR-14130 zh, short dates in japanese/roc calendars should use single y

- common/main/ar.xml
- seed/main/la.xml
Remove leading NBSP ins eom Arabic compact currency formats.
Also, for standard date/time formats in seed/main/la.xml, move draft attribute to correct element. This fixes a bug introduced in https://github.com/unicode-org/cldr/pull/578 that was preventing my pre-submit tests from passing.
> CLDR-14149 ar, remove leading NBSP in some compact currency formats

- common/main/es_419.xml
- common/main/es_MX.xml
- common/main/es_US.xml
In es_419, fixed the patterns for gregorian availableFormats skeletons yMMM, yMMMd to use MMM instead of MMMM. All other availableFormats and intervalFormats patterns in all calendars in es_419 already had MMM or MMMM matching the skeleton.
In es_MX,es_US made a similar fix for gregorian availableFormats yMMMEd.
A separate ticket will be filed (for a future release) to adjust use of 'de in these patterns (generally patterns with MMM should not have 'de', patterns with MMMM should).
> CLDR-14157 es_419, fix patterns for yMMM, yMMMd (MMMM -> MMM)

- common/main/root.xml
- common/main/sat.xml
This should fix the failing ICU exhaustive test.
I only updated these sets in the root.  I did not touch any that might exist in child locales.
> CLDR-14163 Add missing character to parseLenients

- common/supplemental/supplementalMetadata.xml
Fix casing in replacement of drw and tnf
type="drw" replacement="fa_af" =>  replacement="fa_AF"
type="tnf" replacement="fa_af" =>  replacement="fa_AF"
> CLDR-13899 Fix casing of drw and tnf to fa_AF

- common/bcp47/segmentation.xml
- common/main/en.xml
- docs/ldml/tr35-general.html
- docs/ldml/tr35.html
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestBCP47.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocale.java
Add u locale extension key -dx to disable dictionary breaks for one or more script codes listed as arguments.
- Add BCP47 info
- Add key name in English
- Update LDML spec
- Update tests; this is a bit incomplete for now.
> CLDR-10338 add u locale extension -dx, disable dictionary break for listed scripts

- common/supplemental/plurals.xml
Adjustment to new French plural rules from ICU integration testing:
- Rules for "many" should exclude value 0
- Samples for "other" should not include 1000000 (that is for "many")
> CLDR-12010 fr plural rules: many should not include 0, fix samples for other

- .github/workflows/ant.yml
- .github/workflows/production.yml
- tools/scripts/ansible/templates/deploy-sh.j2
CLDR-13948
Note: I put the branch on the 'head fork', so that it can be tried out (see below)
- “we only go forward”:  for all deployments (smoketest and production), display a list of what changes are about to be incorporated.  Allow a `--override` option if we really want to roll backward. If we roll backward, show what we are reverting!
- updates the deploy script deployed by ansible.  This is where the core implementation is done.
- Add a UI for the above.
-----
1. go to [⏯️ Actions](https://github.com/unicode-org/cldr/actions?query=workflow%3Aproduction), to the "production" workflow
2.  find the Run Workflow button
3. change the branch to **srl-deploy-13948** (Note: once this is merged, use `master` !) 
4. Should appear as below. Enter in a SHA (hash), or a tag, or `master`.  
5. If …
> CLDR-13948 Push to Production Improvements

- tools/st-prom-exporter/.gitignore
- tools/st-prom-exporter/README.md
- tools/st-prom-exporter/index.js
- tools/st-prom-exporter/package-lock.json
- tools/st-prom-exporter/package.json
CLDR-7798 
- reads ST JSON, re-exports as Prometheus
Seems to be ready to go. This is what brings in the surveytool_* data into prometheus.
> CLDR-7798 Prometheus exporter for the Survey Tool

- tools/cldr-apps/WebContent/AdminPanel.jsp
- tools/cldr-apps/WebContent/js/redesign.js
- tools/cldr-apps/WebContent/js/survey.js
- tools/cldr-apps/WebContent/v.jsp
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/org/unicode/cldr/web/WebContext.java
-Simplify link in v.jsp; Instructions is no longer a menu
-Remove setHelpContent
-Change GENERAL_HELP_URL to https://sites.google.com/site/cldr/translation
-Fix already-broken AdminSql link; use new SurveyMain.ADMIN_HELP_URL; also in AdminPanel.jsp
-Make 4-arg deprecated WebContext.printHelpLink private
> CLDR-13870 Instruction content update

- common/main/en_AU.xml
- common/main/fr_CA.xml
- common/main/pt_CV.xml
Fix name/symbol collisions only reported in running ConsoleCheckCLDR on cldr-staging/production data (not on regular cldr data). Nte that I have filed https://unicode-org.atlassian.net/browse/CLDR-14172 to improve the tests to detect these in regular CLDR data.
1. en_AU, use inherited names for "volume-quart" and "volume-dessert-spoon" instead of specifying names that conflict with the inherited names (from en_001) for the imperial versions of those units.
1. fr_CA, delete the entry for gbz with name "dari" that collides with the name "dari" inherited from fr for fa_AF
3. pt_CV, for currency PTE stop inheriting the symbol also specified by pt_CV for CVE. Instead, for PTE, use symbol "PTE" and the normal decimal and group separators for pt_CV.
> CLDR-14128 fix name/symbol collisions only reported in cldr-staging tests

- tools/scripts/ansible/setup-playbook.yml
CLDR-13771 ansible: fix proxy so users don't all appear as 127.0.0.1
A proxy header was set incorrectly, but it's been resolved now.  Yoshito might recognize this issue
thanks for reporting this @btangmu
> CLDR-13771 ansible: fix proxy so users don't all appear as 127.0.0.1

- tools/scripts/ansible/README.md
- tools/scripts/ansible/requirements.yml
- tools/scripts/ansible/roles.yml
- tools/scripts/ansible/setup-playbook.yml
- tools/scripts/ansible/templates/55-cldradmin.conf
- tools/scripts/ansible/templates/mycnf.j2
- tools/scripts/ansible/test-local-vars/local.yml
CLDR-13771
- regularize users/mysql users
- update the docs: "test-local-vars/local.yml" is now the documentation
for the variables.
- add enable-redirect capability into the certbot command line
> CLDR-13771 update ansible scripts in production

- tools/cldr-apps/src/org/unicode/cldr/web/MailSender.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyLog.java
CLDR-8383
- cannot use first() on a forward only updateable resultset, changed to next()
- cleaned up SurveyLog so that error messages aren't repeated.
(Exception.toString() includes Exception.getMessage(), so do not need a separate getMessage())
fyi @btangmu
SQL err was `java.sql.SQLException: Result set type is TYPE_FORWARD_ONLY`
> CLDR-8383 fix some SQL issues with mail

- common/supplemental/ordinals.xml
- common/supplemental/plurals.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPluralRuleGeneration.java
- tools/java/org/unicode/cldr/tool/EFixedDecimal.java
- tools/java/org/unicode/cldr/tool/GeneratedPluralSamples.java
- tools/java/org/unicode/cldr/util/TempPrintWriter.java
A test failure in ICU exposed that the samples were being generated incorrectly for the new French 'many' plural rule. This should fix that problem, although ICU may now need some changes to recognize syntax like "1.2e6", and as being different than 1200000.
> CLDR-14176 change plural rule regeneration to have exponent samples

- .github/workflows/maven.yml
- .github/workflows/mvn-settings.xml
- .gitignore
- README.md
- tools/cldr-apps/pom.xml
- tools/java/pom.xml
- tools/pom.xml
CLDR-11585
So, it turns out this can be done a little bit in parallel after all.
- add pom.xml and use the _current_ directory structure. Once this is working, then switch over.
- no tests yet (this needs code refactoring)
- cldr-apps builds and runs OK
- it's possible some of the libs are slightly out of date, but that's easily fixable.
- using a temporary repo for ICU4J/utilities until https://github.com/unicode-org/icu/pull/1270 gets merged.
> CLDR-11585 mavenize (2020 parallel version)

- .github/workflows/ant.yml
- .github/workflows/maven.yml
CLDR-13948
- otherwise, any fork with a master branch will attempt (and fail) to deploy.
-----
Specifically locks the smoketest deployment to https://github.com/unicode-org/cldr.git
I don't think there's a reason to lock down "push to production" because it's manually triggered. 
- example where the repo doesn't match (i.e. fork): https://github.com/srl295/cldr/actions/runs/262743821
- example where the repo matches (simulating 'head fork'): https://github.com/srl295/cldr/actions/runs/262751278 (i've changed the workflow to check for `srl295/cldr`)
This brings up a question, though. The maven (and ant) builds currently run on:
- branch 'master' (any fork)
- pull request from any branch (any fork)
We may want to change this to actually `push: branches: '*'` so that builds happen on any …
> CLDR-13948 only deploy to smoketest in head fork

- tools/cldr-apps/WebContent/js/special/statistics.js
CLDR-14184 missed some things from #719 
- sort by-locale from a to z
- by-locale was off by one
- add locale names to by-locale hover text
> CLDR-14184 Statistics page fix for by-locale

- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForum.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyForumParticipation.java
-Change table column open to is_open for all platforms (mysql/derby/etc)
-Change in SurveyForumParticipation.java as well as SurveyForum.java
-A one-time manual db modification will be required on production and smoketest
> CLDR-13945 OPEN is a reserved SQL keyword, breaks on Derby

- tools/scripts/ansible/README.md
- tools/scripts/ansible/backup-db-playbook.yml
- tools/scripts/ansible/hosts
- tools/scripts/ansible/setup-playbook.yml
- tools/scripts/ansible/templates/cldrbackup/backup_sh.j2
- tools/scripts/ansible/templates/cldrbackup/config.j2
- tools/scripts/ansible/templates/mycnf.j2
- tools/scripts/ansible/vars/main.yml
-Use Ansible to automate not only the backups but the setup of the backups
-Variables cldr_database_name, cldr_db_backup_host, cldr_db_backup_user, cldr_db_backup_destination
-Name backups like cldrdb-DUMP... instead of cldr-DUMP..., distinguish st2 from st during overlap
> CLDR-11283 Make regular automated backups of Survey Tool database

- .github/workflows/mvn-settings.xml
- tools/cldr-apps/pom.xml
- tools/java/pom.xml
- tools/pom.xml
CLDR-11585
updates to the tag `cldr/2020-09-22` from ICU
- switch settings from srl295 to unicode-org
- parallel to b3254d3f3ca4fbc32e8c6e1fe14406edf793b5e3 / #731
- will update developer docs to explain how to configure maven
> CLDR-11585 update icu4j to 68.1-SNAPSHOT-cldr-2020-09-22

- .github/workflows/ansible-lint.yml
CLDR-13771
- see https://github.com/ansible-collections/community.kubernetes/issues/135#issuecomment-661189940
- workaround by not setting a version
> CLDR-13771 workaround ansible-lint failing

- docs/ldml/tr35-numbers.html
- docs/ldml/tr35.html
Note: deviates slightly from design doc.
- 2.6e6 has the same features (v, f, ...) as 2.6, except for the exponent
- There is no @context: exponent forms are mixed into @integer and @decimal as appropriate
> CLDR-12010 Update spec for plurals to add French 'e'

- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestMisc.java
- tools/cldr-apps/src/org/unicode/cldr/web/SurveyAjax.java
- tools/scripts/ansible/setup-playbook.yml
-Change filename like `CldrStAjax._b7a33e9fe_.js` instead of query string
-Change filename only if using reverse proxy, detected by X-Real-IP in request.getHeader
-Use Ansible to set up nginx.conf rewrite rule
-Comments in unit test TestGitHash about what it currently fails to test
> CLDR-13582 Make sure browser uses most recent JavaScript files for ST

- .github/workflows/maven.yml
- .github/workflows/mvn-settings.xml
- tools/cldr-apps/pom.xml
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestAll.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestShim.java
- tools/cldr-unittest/build.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAll.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestShim.java
- tools/java/pom.xml
- tools/pom.xml
CLDR-11585
after this, then https://sites.google.com/site/cldr/development/maven instructions should work to use maven (from the command line, at least).
-----
Rescoping this one to also include adding (via a shim) all tests (but not consolecheck).
> CLDR-11585 Maven: Add tests, simplify pom setup

- common/main/he.xml
To avoid regressions, revert Hebrew currency formats to CLDR 37 versions. Will use https://unicode-org.atlassian.net/browse/CLDR-14077 to investigate the proposed changes for a future version.
> CLDR-14128 he, revert currency format changes, back to CLDR 37 version

- tools/java/org/unicode/cldr/json/Ldml2JsonConverter.java
CLDR-14143
Ldml2JsonConverter was writing an obsolete 'licenses' field
in the package.json for npm.
Fix it, and also use the correct SPDX (Unicode-DFS-2016)
> CLDR-14143 update npm packaging

- tools/java/org/unicode/cldr/json/LdmlConvertRules.java
CLDR-14175
this was broken for, say, Amharic also.  My first fix is this.
From:
```json
"power2": {
"compoundUnitPattern1": "{0}²",
"compoundUnitPattern1": "{0}²",
"compoundUnitPattern1": "{0}²"
},
```
```json
"power2": {
"compoundUnitPattern1": "{0}²",
"compoundUnitPattern1-count-one": "{0}²",
"compoundUnitPattern1-count-other": "{0}²"
},
```
Now, for German a similar issue ensued. My fix outputs this:
```json
"power2": {
"compoundUnitPattern1": "Quadrat{0}",
"compoundUnitPattern1-count-one": "Quadrat{0}",
"compoundUnitPattern1-count-one-case-accusative": "Quadrat{0}",
"compoundUnitPattern1-count-one-case-dative": "Quadrat{0}",
"compoundUnitPattern1-count-one-case-genitive": "Quadrat{0}",
"compoundUnitPattern1-gender-feminine-count-one": "Quadrat{0}", …
```
> CLDR-14175 update JSON converter to handle compoundUnitPattern1

- tools/cldr-apps/pom.xml
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestShim.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestShim.java
- tools/java/org/unicode/cldr/util/TestShimUtils.java
- tools/java/pom.xml
- tools/pom.xml
you can now run specific subtests with:
```
mvn test '-Dorg.unicode.cldr.unittest.web.testArgs=-f:TestMisc -n -q' '-Dorg.unicode.cldr.unittest.testArgs=-f:TestUntimedCounter -n -q' 
```
I was unable to get code coverage to work here, but it's just a config file change away.
> CLDR-11585 improve maven tests 

- tools/cldr-apps/src/org/unicode/cldr/unittest/web/TestSTFactory.java
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/data/TestSTFactory.dtd
- tools/cldr-apps/src/org/unicode/cldr/unittest/web/data/TestSTFactory.xml
- tools/java/org/unicode/cldr/util/VoteResolver.java
-Revise equalsOrgVote to prevent Dashboard Losing
-New itemsWithVotes = countDistinctValuesWithVotes to prevent Dashboard Disputed
-New bothInheritanceAndBaileyHadVotes, refactor combineInheritanceWithBaileyForVoting
-Remove condition voteCount != null in reallyCombineInheritanceWithBailey (never null)
-New unit test in TestSTFactory.xml, using new method TestSTFactory.verifyOrgStatus
-Add attributes statusOrg, orgStatus in TestSTFactory.dtd for verifyOrgStatus
-Make getStatusForOrganization slightly more efficient; methods were called even when not needed
-Change some methods from public to private
-Delete some dead/deprecated code
-Comments
> CLDR-10365 Logic for Losing in sublocales is faulty, Part One

- .github/workflows/maven.yml
- tools/cldr-apps/pom.xml
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestShim.java
- tools/java/pom.xml
- tools/pom.xml
CLDR-11585
- create an uber-jar for cldr.jar with:
mvn -pl java package assembly:single -DskipTests=true
- fix a comment in TestShim.java (missed in #741)
- run Maven test against MySQL
(this is an update to CLDR-8383 CI against mysql (#705) and
corrects 6adc82b6b6116bb67e046ec129adb66f4aa6aac4 which introduced
Maven CI against Derby)
- Move more pluginDependencies up from cldr-apps/pom.xml to tools/pom.xml
No plugin versions are specified in sub-poms now.
-----
Note: This unblocks CLDR-8383 from a code perspective.  The only thing holding us to Derby is
user docs / dev environment setup!
> CLDR-11585 maven: single jar assembly, mysql, cleanup

- .github/workflows/maven.yml
- tools/cldr-apps/pom.xml
CLDR-11585
- ICU/CLDR need to be default scope in pom
- "mvn install" needed for successful packaging (update to workflow)
I might not have been testing cldr-apps.war properly before.
> CLDR-11585 maven package/install

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
-Also remove unused vetweb
-This is to stop spurious warnings after Maven switch
> CLDR-11585 Remove unused CLDR_VET_WEB

- docs/ldml/tr35-numbers.html
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPluralRuleGeneration.java
- tools/java/com/ibm/icu/text/FixedDecimal.java
Allow for both c and e in the spec; update code for DecimalQuantity in the test
> CLDR-12010 Allow for both c and e in the spec

- tools/cldr-apps/js-unittest/TestCldrStForum.js
- tools/cldr-apps/src/main/webapp/js/CldrStForum.js
-New function cldrStForum.setDisplayUtc to use UTC for unit test only
-Update unit test to request and expect UTC
-No change to Survey Tool interface, which still displays local time zone
> CLDR-14215 Make js unit test work in all time zones

- tools/java/org/unicode/cldr/tool/ChartDtdDelta.java
- tools/java/org/unicode/cldr/util/DtdData.java
Remove + on attribute if only constraints changed. Suppress identical constraint words for a more concise format. 
Results are in https://unicode-org.github.io/cldr-staging/charts/38/supplemental/dtd_deltas.html
> CLDR-14066 Fix display of constraints in Delta DTD charts

- docs/ldml/tr35-general.html
- docs/ldml/tr35.html
In spec, use "legacy" rather than "grandfathered" where possible. Similar to ICU changes in https://github.com/unicode-org/icu/pull/1243/files
Also fix html validation errors with ampersand in a link
> CLDR-13922 in spec, use "legacy" rather than "grandfathered" where possible

- tools/cldr-unittest/src/org/unicode/cldr/unittest/LocaleMatcherTest.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestAttributeValues.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLsrvCanonicalizer.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestValidity.java
- tools/java/org/unicode/cldr/test/CheckAttributeValues.java
- tools/java/org/unicode/cldr/tool/CheckLangTagBNF.java
- tools/java/org/unicode/cldr/tool/CountItems.java
- tools/java/org/unicode/cldr/tool/FallbackIterator.java
- tools/java/org/unicode/cldr/tool/FallbackIteratorDataGenerator.java
- tools/java/org/unicode/cldr/tool/GenerateG2xG2.java
- tools/java/org/unicode/cldr/tool/LocaleReplacements.java
- tools/java/org/unicode/cldr/tool/SimpleLocaleParser.java
- tools/java/org/unicode/cldr/util/AttributeValueValidity.java
- tools/java/org/unicode/cldr/util/LanguageTagParser.java
- tools/java/org/unicode/cldr/util/MatchValue.java
- tools/java/org/unicode/cldr/util/StandardCodes.java
- tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/java/org/unicode/cldr/util/TestUtilities.java
- tools/java/org/unicode/cldr/util/Validity.java
https://unicode-org.atlassian.net/browse/CLDR-14226
For affected enums, I replaced several calls to Enum.valueOf(String) with .from(String) or .fromString(String) and temporarily still handled the old name. Set a breakpoint, ran the unit tests, updated call sites, removed the alias.
For other string comparisons I also set temporary breakpoints to make sure the unit tests don't show use of the old name.
I did not change what looked like data file syntax.
> CLDR-14226 reduce use of term grandfathered in code

- tools/scripts/ansible/setup-playbook.yml
-Add Ansible setup for /etc/logrotate.d/surveytool-logs
-Rotate /var/lib/tomcat8/cldr/exception.log same as on old server
-Also similarly rotate /var/lib/tomcat8/cldr/cldrmail.log
-Note: catalina.out already uses system default /etc/logrotate.d/tomcat8
> CLDR-14220 Azure migration: log rotation

- .github/workflows/commit-checker.yml
CLDR-14205
- improve markdown processing
This is an update to the calling button only. It will solve the "links from the TOC do not work".
The markdown processing wasn't specified properly previously.
> CLDR-14205 commit checker: update

- common/supplemental/supplementalMetadata.xml
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/data/localeMatcherTest.txt
- tools/java/org/unicode/cldr/util/Rational.java
- tools/java/org/unicode/cldr/util/data/langtagRegex.txt
- tools/java/org/unicode/cldr/util/data/langtagTest.txt
This changes more "uses" of "grandfathered" to "legacy", and also replaces uses of "blacklist" and "crazy".
There are remaining uses of "grandfathered" specifically in reference to BCP47, and remaining uses of "master" specifically referring to a github branch (and URLs for it), but there is not much we can do about those for the time being. I think this PR represents the final chnages in this area for CLDR v38. We can investigate more for v39 (with a new ticket).
Note that some sensitive terms are present just as (1) terms for which we have IPA transcription data, and (2) localized name of language "den".
> CLDR-14226 change more uses of "grandfathered", and of "blacklist", "crazy"

- docs/ldml/tr35-general.html
- docs/ldml/tr35-numbers.html
- docs/ldml/tr35.html
1. Document:
- new number symbol approximatelySign (was already there, but not marked as a change)
- characterLabelPattern type atttribute values subscript and superscript
2. Repair the Modifications section, was somewhat mangled
3. Fix various pre-existing validation errors
> CLDR-14128 document approximatelySign,sub/superscript, fix modifications and validation errs

- tools/cldr-apps/.classpath
- tools/cldr-unittest/.classpath
CLDR-14212
- a temporary fix until the final Maven switchover, where we will delete the .classpath and other setting files
> CLDR-14212 update .classpath to include JUnit

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/webapp/about.jsp
- tools/cldr-unittest/src/org/unicode/cldr/unittest/LanguageTest.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestBasic.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestCoverageLevel.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestInheritance.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestLocale.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestPathHeader.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestScriptMetadata.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestSupplementalInfo.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUnits.java
- tools/java/org/unicode/cldr/tool/CompareSuppress.java
- tools/java/org/unicode/cldr/tool/CountItems.java
- tools/java/org/unicode/cldr/tool/FallbackIteratorDataGenerator.java
- tools/java/org/unicode/cldr/tool/FindWidths.java
- tools/java/org/unicode/cldr/tool/FixTransformNames.java
- tools/java/org/unicode/cldr/tool/GenerateCasingChart.java
- tools/java/org/unicode/cldr/tool/GenerateChangeChart.java
- tools/java/org/unicode/cldr/tool/GenerateDayPeriodChart.java
- tools/java/org/unicode/cldr/tool/GenerateDerivedAnnotations.java
- tools/java/org/unicode/cldr/tool/GeneratePluralConfirmation.java
- tools/java/org/unicode/cldr/tool/GetChanges.java
- tools/java/org/unicode/cldr/tool/ListCoverageLevels.java
- tools/java/org/unicode/cldr/tool/ListRedundantUnicodeSets.java
- tools/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- tools/java/org/unicode/cldr/tool/ShowRegionalVariants.java
- tools/java/org/unicode/cldr/util/CLDRConfig.java
- tools/java/org/unicode/cldr/util/DayPeriodsCheck.java
- tools/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/java/org/unicode/cldr/util/WikipediaOfficialLanguages.java
CLDR-14180
- change SupplementalDataInfo to a mutable Bill Pugh singleton
SupplementalDataInfo needs to be able to change its default instance
- remove CLDRConfig.getStandardCodes() - use StandardCodes.make() instead.
> CLDR-14180 cleanup SupplementalDataInfo  / CLDRConfig.getStandardCodes

- common/main/uk.xml
In uk Ukrainian, per TC discussion, copy the data for "energy-kilocalorie" to "energy-foodcalorie" (replacing the bogus data currently in "energy-foodcalorie"). Only have this for long and short forms, no data for narrow. Then for both "energy-kilocalorie" and "energy-foodcalorie", "Ккал" should be lowercased.
> CLDR-14222 uk, data for "energy-foodcalorie" should be the same as for "energy-kilocalorie"

- tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUtilities.java
- tools/java/org/unicode/cldr/util/VoteResolver.java
-In VoteResolver.setLocale, use locale (like fr_CA) instead of locale.getLanguageLocale (like fr)
-Fix deprecation warnings for single-arg setLocale
-Remove unused return value of VoteResolver.setLocale (make void)
-Some changes made automatically by Eclipse (whitespace; ...new... with angle brackets)
-Comments
> CLDR-13777 Logic for Losing in sublocales is faulty, Part Two

- common/dtd/ldmlSupplemental.dtd
Simple reformat, just expected whitespace changes. Should be cherry-picked into v38
> CLDR-14167 BRS A34.5, Run GenerateDTD

- tools/cldr-unittest/src/org/unicode/cldr/api/PrefixVisitorTest.java
- tools/java/org/unicode/cldr/api/CldrDataSupplier.java
- tools/java/org/unicode/cldr/api/PrefixVisitorHost.java
CLDR-13458 Better test to show how nested prefix visitors work.
Hopefully it makes clear where the visitors swap out and get restored (I caught myself out while writing the new ICU data processor code, so this helps cement behaviour).
> CLDR-13458 Better test to show how nested prefix visitors work

- tools/scripts/ansible/hostname-playbook.yml
-Use inventory_hostname instead of hard-coded st.unicode.org
> CLDR-14220 Azure migration: set st.unicode.org hostname

- tools/scripts/ansible/server-playbook.yml
- tools/scripts/ansible/templates/mycnf.j2
-Move database in .my.cnf (mycnf.j2) under [mysql] to prevent mysqldump failure
-Fix logrotate: on new servers, log files are owned by tomcat8 tomcat8
> CLDR-14220 Azure migration: fix db backup and log rotation

- .github/workflows/ant.yml
CLDR-14212
- 8.5.57 was off the mirrors, and was causing build errors
@hagbard you are also welcome to incorporate this patch into your own PR, or at least push it to a branch which will populate your cache.
> CLDR-14212 update ant build to use tomcat 8.5.59

- tools/scripts/ansible/backup-db-playbook.yml
-Fix the location for backup.sh, not inside .ssh (copy-paste error)
> CLDR-14220 Azure migration: fix db backup

- common/main/zh.xml
Per TC discussion: In zh, revert to CLDR 37 value for &lt;metazone type="Indochina"&gt;, i.e. with the region portion of the name being "印度支那" (Indochina) instead of "印度中国" (India-China)
> CLDR-14236 zh, revert to CLDR 37 value for <metazone type="Indochina">

- tools/scripts/ansible/backup-db-playbook.yml
-Fix the name of .ssh/config, should not have .j2 extension
> CLDR-14220 Azure migration: fix db backup rsync to corp

- tools/java/org/unicode/cldr/json/JSON_config_supplemental.txt
- tools/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/java/org/unicode/cldr/util/CLDRFile.java
[CLDR-14238](https://unicode-org.atlassian.net/browse/CLDR-14238)
This adds pluralRanges to the data handled by ldml2json, which will allow it to be included in the `cldr-core` npm package.
As a sidenote, I needed to locally replace the master branch contents of `tools/java/lib/` with those of the release 37 tools.zip in order to get `ant jar` to succeed, but did not investigate the cause for this.
> CLDR-14238 Include pluralRanges in ldml2json output

- common/main/zh_Hant.xml
Per TC discussion: Just as https://github.com/unicode-org/cldr/pull/800 did for zh, this PR reverts zh_Hant to the CLDR 37 value for `<metazone type="Indochina">`, i.e. with the region portion of the name being "印度支那" (Indochina) instead of "印度中國" (India-China)
> CLDR-14236 zh_Hant, revert to CLDR 37 value for <metazone type="Indochina">

- tools/scripts/ansible/server-playbook.yml
-Configure nginx with same generous timeouts as it had on the old server
> CLDR-14241 Forum Participation is breaking

- tools/pom.xml
(ICU tag `cldr/2020-10-21`)
followon to #806
- also, update documentation in tools/pom.xml
> CLDR-14128 Update pom.xml for maven for ICU4J libs to Oct 21

- docs/ldml/tr35-collation.html
- docs/ldml/tr35-dates.html
- docs/ldml/tr35-general.html
- docs/ldml/tr35-info.html
- docs/ldml/tr35-numbers.html
- docs/ldml/tr35.html
Made a first pass at fixing broken links in the spec, following the general approach of Mark's e-mail "Re: TR35 - critical header link issues / tr35.html" of 2020-Oct-21 6:06 PM PDT, with changes and additions as follows:
1. So at a minimum we have to change https://unicode.org/cldr/X back to http://unicode.org/cldr/X
- except for https://unicode.org/cldr/dtd/ which needs to stay that way
- also have to change http[s]://unicode.org/cldr/index/ -> http://cldr.unicode.org/index/
2. The second issue is that if we have links to XML files, those need to go to github. Handle that as follows:
- http://unicode.org/cldr/data/ -> https://github.com/unicode-org/cldr/blob/master/
- http://unicode.org/cldr/latest/ -> https://github.com/unicode-org/cldr/blob/maint/maint-38/ (which is permanently valid …
> CLDR-14128 fix broken links in spec, pass 1

- .github/workflows/commit-checker.yml
- .github/workflows/maven.yml
CLDR-14212
- Background: https://github.community/t/version-numbering-for-actions/16307/4
- Specific issue: https://github.com/actions/setup-java/pull/104#issuecomment-715489633
actions/setup-java@v1.4.2 was creating warning messages about set-env,
needed to switch to v1.4.3.  Instead, all actions now use @v1 or @v2, which points to a
branch.
> CLDR-14212 Update GitHub actions to @vx vs @vx.y.z

- tools/java/org/unicode/cldr/json/CldrItem.java
- tools/java/org/unicode/cldr/json/CldrNode.java
- tools/java/org/unicode/cldr/json/JSON_config_supplemental.txt
- tools/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/java/org/unicode/cldr/json/pathTransforms.txt
- tools/java/org/unicode/cldr/util/FileProcessor.java
CLDR-13730
- Also, move path transforms out to a separate file
- Other JSON code improvements
Example files:
```json
{
"supplemental": {
"version": {
"_unicodeVersion": "13.0.0",
"_cldrVersion": "38"
},
"unitPreferenceData": {
"area": {
"default": {
"001": [
{
"unit": "square-kilometer"
},
{
"unit": "hectare"
},
{
"unit": "square-meter"
},
{
"unit": "square-centimeter"
}
],
…
"person-height": {
"001": [
{
"unit": "centimeter"
}
],
…
"CA": [
{
"unit": "foot-and-inch",
"geq": 3.0
},
{
"unit": "inch"
}
],
}
```
> CLDR-13730 json: support unit preferences

- tools/cldr-unittest/src/org/unicode/cldr/unittest/TestUtilities.java
-Add TestUtilities.TestSublocaleRequiredVotes, expect required 8 for pt_PT, zh_Hant, else 4
> CLDR-13777 Logic for Losing in sublocales is faulty, Part Two, add test

- tools/cldr-apps/.gitignore
CLDR-14212
hopefully we won't have too many of these.
> CLDR-14212 add generated .gitignore from eclipse

- tools/java/src/main/java/com/ibm/icu/dev/test/TestFmwk.java
- tools/java/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java
CLDR-14285
The search code for the relevant test source file was wrong.
This fixes it to skip 'lambda$' if present, otherwise the
error source is obscured.
> CLDR-14285 cause TestFmwk.sourceLocation() to handle lambdas

- common/supplemental/grammaticalFeatures.xml
- tools/java/src/main/java/org/unicode/cldr/json/CldrItem.java
- tools/java/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/java/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/java/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
- tools/java/src/main/resources/org/unicode/cldr/json/pathTransforms.txt
CLDR-13730
- also general cleanup
- moved grammaticalGender to separate file
- corrected duplicate locale fil in common/supplemental/grammaticalFeatures.xml
> CLDR-13730 add grammaticalFeatures

- tools/scripts/ansible/Vagrantfile
CLDR-14214
- to prevent intermittent failures with ansible-lint jobs
see: https://www.vagrantup.com/docs/vagrantfile/machine_settings#config-vm-boot_timeout
> CLDR-14214 increase Vagrant boot timeout

- tools/java/src/main/java/org/unicode/cldr/json/CldrItem.java
- tools/java/src/main/java/org/unicode/cldr/json/CldrNode.java
- tools/java/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- simplify so there are fewer rbnf special cases
- change to simpler tuple form:
"%spellout-cardinal": [ ["-x","მინუს →→;"],["x.x","←← მძიმე →→;"],
to preserve ordering
Might need resolution with #830
> CLDR-10883 improving JSON RBNF

- tools/cldr-apps/pom.xml
- tools/pom.xml
CLDR-14212
- cldr-apps was still depending on the old artifact!
- fixup to d6ead5d07db76e934d4cfe3220f28ac1114f3032
I was seeing strange errors, and realized that cldr-apps did not get updated to use `cldr-code` and not `cldr` as the artifact.
> CLDR-14212 rename java to cldr-code: fix cldr-apps

- common/supplemental/windowsZones.xml
This PR adds the new `Yukon Standard Time` time zone added here:
https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/2020-time-zone-updates-for-yukon-now-available/ba-p/1598976
It also updates the version numbers to their current values.
> CLDR-14301 Add Windows mapping for Yukon Standard Time zone

- tools/cldr-apps/pom.xml
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/webapp/cldr-setup.jsp
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
- tools/pom.xml
CLDR-13328
- common constant for repo root
- remove unneeded libs for Subversion
- also remove 'rome' which is an RSS library, not used.
> CLDR-13328 remove last bits of svn mention, cleanup urls

- tools/cldr-apps/src/main/webapp/DataExport.jsp
CLDR-14268
- was broken in #838 / eabb612cf0bde0a198a59cb27e7c49c9996419b4
- I missed this use case in the JSP
- the button is the 'Download .csv' at the bottom of the user list
> CLDR-14268 fix DataExport of users

- .github/workflows/ansible-lint.yml
- tools/scripts/ansible/README.md
- tools/scripts/ansible/Vagrantfile
- tools/scripts/ansible/cldr-apps-playbook.yml
- tools/scripts/ansible/mysql-playbook.yml
- tools/scripts/ansible/requirements.yml
- tools/scripts/ansible/roles.yml
- tools/scripts/ansible/templates/context.j2
- tools/scripts/ansible/templates/deploy-sh.j2
- tools/scripts/ansible/templates/server.xml
- tools/scripts/ansible/tomcat-playbook.yml
- tools/scripts/ansible/vagrant-playbook.yml
- tools/scripts/ansible/vars/main.yml
- tools/scripts/ansible/vars/mysql.yml
- tools/scripts/ansible/vars/tomcat.yml
-Revise tomcat-playbook.yml to use robertdebock.tomcat
-Move parts of vars/main.yml to new mysql.yml, tomcat.yml
-Make cldr_tomcat_conf_path end in /conf
-Use only /etc/tomcat, never /var/lib/tomcat (which no longer exists)
-Remove roles.yml; use requirements.yml instead in ansible-lint.yml
-Update README.md: requirements.yml not roles.yml; mvn not ant
-Revise context.j2: com.mysql.cj.jdbc.Driver not com.mysql.jdbc.Driver; cachingAllowed; cacheMaxSize
-For vagrant only, new vagrant-playbook.yml; just calls setup-playbook.yml but adds flexibility
-Remove problematic AJP section from server.xml
-In deploy-sh.j2 use only spaces for indentation, rather than mix tabs and spaces
> CLDR-13139 Upgrade Tomcat using Ansible

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
- tools/cldr-apps/src/main/webapp/js/review.js
-Remove the constraint in ReviewHide.java, not needed
-Also fix a bug in review.js: do not crash in fixPopoverVotePos if no button.position(), as while loading
> CLDR-14283 Fix MySQLIntegrityConstraintViolationException for cldr_review_hide

- tools/cldr-apps/pom.xml
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/HttpStatusCache.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/webapp/js/CldrSurveyVettingLoader.js
- tools/cldr-apps/src/main/webapp/js/survey.js
- tools/cldr-apps/src/main/webapp/tc-all-errors.jsp
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSubtypeToURLMap.java
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes.html
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_badtype.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_badurl.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_dangling.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_dangling2.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_noend.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_nostart.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_bad_nourl.txt
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/subtypes_empty.txt
- tools/cldr-code/.settings/org.eclipse.wst.validation.prefs
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
- tools/pom.xml
CLDR-13197
Ready to go.
Note that the URL map only has a couple of entries.
Would like to get this in and make sure it is working, and use CLDR-14277 as a test case, before a subsequent effort to actually populate the subtype map.
- updated utility functions in CLDRURLs et
- added new page "tc-all-errors.jsp" showing all errors
- new data file subtypeMapping.txt mapping subtype to URL
> CLDR-13197 make it easier to find more details about an error subtype

- .github/workflows/maven-release.yml
- .github/workflows/mvn-settings.xml
- tools/pom.xml
CLDR-14212
publish ( using version `0.0.0-SNAPSHOT-`_hash_ where _hash_ is the git hash ) all released versions to maven
> CLDR-14212 publish to maven on release

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/webapp/WEB-INF/tmpl/manage.jsp
- tools/scripts/ansible/templates/cldr-properties.j2
-New function SurveyMain.isPhaseFinalTesting called by userCanModifyLocaleWhy and manage.jsp
-New message ModifyDenial.DENY_PHASE_FINAL_TESTING
-Clean up formatting of enum ModifyDenial
-Fix compiler warnings about static SurveyMain.QUERY_DO and SurveyMain.getNewVersion
-Fix compiler warning about UserRegistry.writeUserFile, call out.close before return
-Remove superfluously duplicated CLDR_PHASE setting in cldr-properties.j2
-Delete some dead code
> CLDR-14057 Survey Tool CLDR_PHASE=FINAL_TESTING should not allow vetters to vote

- common/main/es_419.xml
Removing the ungrammatical time formatting so it can fall back on parent locale es.
> CLDR-14279 es_419 plural time formatting

- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLNormalizingLoader.java
> CLDR-14363 Use PathUtilities for normalized file names (as opposed to getCanonicalPath()).

- tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/Main.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/SearchXml.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRTool.java
CLDR-13987
- use a default CLDR_DIR if the jar is launched from a CLDR dir
- add docs for SearchXML
- correct cldr.jar to cldr-code.jar
Also see rewrites to http://cldr.unicode.org/tools
> CLDR-13987 improve @CLDRTool annotation, default CLDR_DIR in tools

- tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrItem.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrNode.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
CLDR-14258 JSON build improvements: add cldr-segments-full
- add a -V option to specify the version, overriding the CLDR version
- restructuring for more clarity on the package calculation process
- reduce the default text output verbosity
- cause the "other" package to not overwrite if multiple "other" sections.
- make sure all tiered (full/modern) modules have files present in full if they are in modern
(only affected module: segments)
- change output format to spend less time in synchronized block:
One output per input file with a summary.
Percentage progress inspired by ninja-build.
Also changes from:
CLDR-14313 compare JSON config to DTD Data
- JSON config was not easily derivable from DTD, however, this commit now
runs a test comparing especially "@MATCH:set" annotations against …
> CLDR-14258 JSON build improvements: add cldr-segments-full

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- tools/cldr-apps/src/main/webapp/AdminPanel.jsp
- tools/cldr-apps/src/main/webapp/js/new/cldrAjax.js
- tools/cldr-apps/src/main/webapp/js/new/cldrBulkClosePosts.js
- tools/cldr-apps/src/main/webapp/js/new/cldrEvent.js
- tools/cldr-apps/src/main/webapp/js/new/cldrFlip.js
- tools/cldr-apps/src/main/webapp/js/new/cldrForum.js
- tools/cldr-apps/src/main/webapp/js/new/cldrForumParticipation.js
- tools/cldr-apps/src/main/webapp/js/new/cldrGui.js
- tools/cldr-apps/src/main/webapp/js/new/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/new/cldrLocaleMap.js
- tools/cldr-apps/src/main/webapp/js/new/cldrOtherSpecial.js
- tools/cldr-apps/src/main/webapp/js/new/cldrStatus.js
- tools/cldr-apps/src/main/webapp/js/new/cldrSurvey.js
- tools/cldr-apps/src/main/webapp/js/new/cldrTable.js
- tools/cldr-apps/src/main/webapp/js/new/cldrXpathMap.js
- tools/cldr-apps/src/main/webapp/js/redesign.js
- tools/cldr-apps/src/main/webapp/myvotes.jsp
-Fix bug in PR #893: in cldrAjax.js, only use responseText if responseType is text
-Section view is now mostly working without dojo
-Add lots of placeholders for old dojo-dependent features
-New cldrEvent.js has most of the code from old redesign.js
-Move OtherSpecial to new cldrOtherSpecial.js
-Remove dead code; clean up
-Comments
> CLDR-14251 Modernize: continue implementing front end without dojo

- docs/ldml/tr35.html
https://github.com/unicode-org/cldr/blob/f443882bd0fc9267ad7b2b534da6428929bd7b0f/common/main/ru.xml#L818
> CLDR-13895 Correct Russian spelling of "China" in documentation

- tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRCacheDir.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/util/CLDRConfigImpl.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/AbstractCacheManager.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
CLDR-14323
- make XML cache, Abstract cache, Subtype URL, and Sandbox locales all use the new
cache facility
- the cache dir is under 'cldr/.cache' where .cache is a sibling of cldr.properties, etc.
- implements https://bford.info/cachedir/ recommendation for cache dir tagging (that is the `CACHEDIR.TAG` file)
Example of cache in use: (all of these files were in random places previously)
```shell
$ (cd eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0  ; find ./cldr/.cache -print)
./cldr/.cache
./cldr/.cache/CACHEDIR.TAG
./cldr/.cache/urlmap
./cldr/.cache/urlmap/urlmap-cache.txt
./cldr/.cache/abstracts
./cldr/.cache/abstracts/xpath-to-resource.properties
./cldr/.cache/sandbox
./cldr/.cache/sandbox/annotations
./cldr/.cache/sandbox/annotations/mul.xml …
```
> CLDR-14323 add new CLDRCacheDir service

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- tools/cldr-apps/src/main/webapp/js/new/cldrAbout.js
- tools/cldr-apps/src/main/webapp/js/new/cldrSurvey.js
- tools/cldr-apps/src/main/webapp/js/survey.js
-Fix localizeAnon TRANS_HINT_LANGUAGE_NAME bug affecting both dojo and non-dojo versions
-For non-dojo, add vue.js and upgrade to latest version of jquery and jquery-ui
-Add tiny test for vue.js in cldrAbout.js
-Comments
> CLDR-14251 Modernize: fix localizeAnon bug; for non-dojo, add vue, upgrade jquery

- common/supplemental/languageInfo.xml
https://unicode-org.atlassian.net/browse/CLDR-14355
> CLDR-14355 remove special zh-Hans↔zh-Hant language distances

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- tools/cldr-apps/src/main/webapp/AdminPanel.jsp
- tools/cldr-apps/src/main/webapp/js/new/cldrAjax.js
- tools/cldr-apps/src/main/webapp/js/new/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/special/admin.js
CLDR-14251
`USE_DOJO` (default true) can now be set in cldr.properties
also, any request can have `?USE_DOJO=false` or `?USE_DOJO=true` to override
It turned out to be very simple to make this switchable. Could be helpful in testing old vs. new behavior.
> CLDR-14251 make USE_DOJO a server side and a request-time param

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
- tools/cldr-apps/src/main/webapp/js/new/cldrAjax.js
- tools/cldr-apps/src/main/webapp/js/new/cldrBulkClosePosts.js
- tools/cldr-apps/src/main/webapp/js/new/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/new/cldrSurvey.js
- tools/cldr-apps/src/main/webapp/js/survey.js
-For new (non-dojo) front end: include bulk_close_posts in getSpecial; no load params
-Write progress to java log so Admin user can see it
-Fix cldrAjax timeout handling (dojo and non-dojo): err if timeout; default no timeout
-Add new cldrAjax.mediumTimeout to restore old 2-sec timeout for certain requests
-Alphabetize specials array including admin
> CLDR-14392 Modernize Bulk Close Posts in gear menu

- common/rbnf/pt.xml
- common/rbnf/pt_PT.xml
In addition to the short scale versus long scale difference, I simplified the rule logic and mirrored the style between the two Portuguese variants to make it easier to compare for differences in the future.
I used https://www.flip.pt/Duvidas-Linguisticas/Duvida-Linguistica/DID/4389 for reference to determine the scale used.
> CLDR-11268 Portugal Portuguese should use the long scale and Brazil should use the short scale

- common/rbnf/root.xml
I confirmed the numbers here:
5780 https://he.wikipedia.org/wiki/ה'תש"ף
5781 https://he.wikipedia.org/wiki/ה'תשפ"א
> CLDR-13419 The final form of the Hebrew Pe should be used at the end of Hebrew numbers

- common/rbnf/it.xml
This looks like a copy and paste typo.
> CLDR-14182 23000 is misspelled in Italian

- common/rbnf/de.xml
- common/rbnf/de_CH.xml
This will have to be merged after https://github.com/unicode-org/cldr/pull/921 because there are file conflicts, but I wanted to get this started for a review.
After consulting with @markusicu and our fellow German experts, we determined the following.
- The range of 2000-2099 should be using the thousands (e.g. zweitausendeins for 2001). While the English style "twenty twenty" could be used for 2020-2099, it's perhaps a little too casual. The original ticket didn't mention the range, and we're explicitly stating for future posterity why we didn't go this route. @markusicu did state "1100..1999 are of the form 'eleven hundred' .. 'nineteen hundred ninety nine' in German." Our German experts agree on this point.
- The ein should still precede the tausend and hundert. As one our German …
> CLDR-10823 Fix in German RBNF numbering-year

- common/rbnf/de.xml
- common/rbnf/de_CH.xml
For completeness, I added one for the ordinal too. For consistency, I used the same naming scheme of cardinal-m as the other rules. This rule seems to apply to the masculine dative and neuter dative case only in German.
I got a German expert to review the changes. The changes seem fine within the scope of the changes. There were some additional comments about other existing rules, but that should be handled with separate tickets.
> CLDR-13418 German cardinal doesn't have spellout-cardinal-m rule

- common/rbnf/fr.xml
- common/rbnf/fr_BE.xml
- common/rbnf/fr_CH.xml
> CLDR-11407 Spelt out date past 1999 should use multiples of a thousand

- common/supplemental/units.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/nistConversions.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/nistDerivedUnits.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/ExternalUnitConversionData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/NistUnits.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TotalOrderBuilder.java
This looked like a spec bug, but turned out to be an error in the data.
https://unicode.org/reports/tr35/tr35-info.html#Unit_Identifier_Normalization
Problems. 
- #4,  the ordering algorithm for units within the numerator or denominator, doesn’t handle derived units like newton in the way the user would expect.
- We need to also mention the powers, in a step either before or after #5.
- 
I looked into this, and wrote a module to walk though our data plus the NIST data to pick up the ordering of units within the denominators and numerators. This results in a partial order which I then used a simple algorithm to produce a total order among base and derived units. (NOTE there are multiple orders that would satisfy the partial order; I used an algorithm that favors lexicographic order, just …
> CLDR-14410 clean up ordering and add test

- common/rbnf/pt.xml
- common/rbnf/pt_PT.xml
I verified the following values.
- 12147889885678 → doze trilhões cento e quarenta e sete bilhões oitocentos e oitenta e nove milhões oitocentos e oitenta e cinco mil seiscentos e setenta e oito
- 100030 → cem mil e trinta
- 1000500 → um milhão e quinhentos
- 1100030 → um milhão cem mil e trinta
- 1100000 → um milhão e cem mil
The largest number was the reported value. The rest were added as test examples from Portuguese experts.
> CLDR-9291 Spell out large Portuguese number with fewer conjunctions

- common/main/de_CH.xml
> CLDR-14322 A de_CH unit binary prefixes have incorrect capitalization

- common/main/yo.xml
CLDR-14269 Add missing additional nasal Yoruba exemplar characters: “ǹ, ḿ, m̀”
Syllabic nasals can have either a high tone, a mid tone or a low tone. They are written as a 'n' except before 'b' where they are written as a 'm'.
- High tone is marked with an acute accent 
- Mid is unmarked
- Low is marked with a grave accent
> CLDR-14269 add nasal Yoruba exemplar characters

- common/main/en_IN.xml
For en_IN, make the compact **decimal** formats match the compact **currency** formats (but without the ¤), this achieves the desired result.
Note that in Apple ICU, en_IN has compact currency and decimal formats equal to the result of this, except that Apple ICU en_IN uses 'K' instead of 'T' to indicate thousands (the result of some internal discussion). But the CLDR vetters chose T for the compact currency formats so in CLDR we use that for the compact decimal formats too.
> CLDR-13759 copy compact currency formats to compact decimal (without ¤)

- common/supplemental/dayPeriods.xml
Transition from evening1 to night1 should be at 22:00, not 24:00/0:00
> CLDR-14422 ru dayPeriods, transition to night should be at 22:00

- tools/cldr-code/src/main/java/org/unicode/cldr/util/ZoneParser.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
-Hard-code data for Australia/Currie in ZoneParser.java
-Also work around a possible compiler bug affecting TestSupplementalInfo.LOCALES_FIXED
> CLDR-14428 ZoneParser fails for Australia/Currie

- common/main/be.xml
- common/main/dz.xml
- common/main/es_GT.xml
- common/main/gd.xml
- common/main/ja.xml
- common/main/mk.xml
- common/main/my.xml
- common/main/sk.xml
- common/main/ug.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
-Revise normalizeWhitespace to call subroutines, including new trimNBSP
-Add new enum PathSpaceType
-Add new unit test TestDisplayAndInputProcessor.TestWhitespaceNormalization
-Update xml with changes from running CLDRModify -fp
> CLDR-14159 DAIP should trim all whitespace

- common/main/root.xml
change root symbol for PHP to match narrow = ₱
> CLDR-13952 change root symbol for PHP to match narrow = ₱

- common/main/fa.xml
Updated lines 8903 and 8913 to the non-localized versions of GB and MB for fa
> CLDR-10831 Non-localize MB GB fa

- common/main/ka.xml
Updated lines 7887-7890 and 7898-7900. Updated this lines to "MB" and "GB"
> CLDR-10831 Non-localized version of MB GB ka

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
CLDR-11059
- fix to cldr-json licensing (add license key to bower.json)
- Add compatible MapComparator data for CLDR 38.1 and prior blood glucose units ( CLDR-14232 )
Without the DtdData change, CLDR 39 is unable to read CLDR 38.1 staging data, crashes with "Missing Map Comparator Values … `concentr-milligram-per-deciliter`…"
> CLDR-11059 fix cldr-json licensing

- tools/cldr-code/src/main/java/org/unicode/cldr/util/ZoneParser.java
-Use the existing linkold_new in getData in ZoneParser.java
> CLDR-14428 ZoneParser failures

- common/supplemental/units.xml
We would also need to change the spec so that the category means 'units that are convertible to this quantity', thus "consumption' can include liters per kilometer and kilometers per meter (and anything convertible to those).
> CLDR-13787 Try merging consumption preferences together. 

- tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXMLSource.java
The goal is to allow 202F to distinguish collisions. 
- fix the set of characters that are distinguished to add 202F (also removed some CO controls and reformatted for clarity
- add hack to get around the NFKC normalization for this character. 
CLDR-11581
> CLDR-11581 Allow U+202F to distinguish collisions

- common/main/sd_Deva.xml
Quarter 4 was "1" in the format version, but "4" in the stand-alone version.
> CLDR-14361 Fix quarter format narrow typo

- tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java
CLDR-14460
On a quick test, seems to give about a 50% speedup in JSON generation.
> CLDR-14460 XPathParts remove synchronized block

- common/main/zh.xml
Fix zh date time format by returning the spaces in the full and medium forms that were removed in v38.
> CLDR-14457 Revert space removal in zh date format

- common/testData/localeIdentifiers/localeCanonicalization.txt
Issue found during integration of CLDR alpha0 with ICU: Needed to update the CLDR file localeCanonicalization.txt (which is used in ICU testing) to account for the change to use no instead of nb, per [CLDR-2698](https://unicode-org.atlassian.net/browse/CLDR-2698; this PR is really a follow-on to [PR-964](https://github.com/unicode-org/cldr/pull/964) for that ticket.
> CLDR-14461 update localeCanonicalization.txt for using no instead of nb

- common/main/es_419.xml
- common/main/es_MX.xml
- common/main/es_US.xml
Update minimumdigitgrouping for es-419, es-US & es-MX per language specialist feedback that Spanish in Latin America uses minimum digit grouping of 1.
This is a replacement for [PR-1008](https://github.com/unicode-org/cldr/pull/1008) since that one needed to be rebased on master and squashed to fix reported errors, faster this way.
> CLDR-14054 change minimumGroupingDigits from 2 to 1 for es_419,es_MX,es_US

- .github/workflows/maven.yml
- this only affects the GitHub automated build
I will revisit additional build issues separately, this is just a point fix to get the right testing to happen.
> CLDR-14456 use -z BUILD in CI build

- common/testData/units/unitPreferencesTest.txt
[PR-991](https://github.com/unicode-org/cldr/pull/991) eliminated the category consumption-inverse category in the units usage data. However, it did not update the unitPreferencesTest.txt test file, which is part of CLDR but is copied to ICU as part of the CLDR-ICU integration, and used for ICU tests. Errors in those tests during CLDR-ICU integration deomnstrated a need to adjust this text file to match the changes in units.xml, this PR makes those adjustments.
> CLDR-13787 fix unitPreferencesTest.txt to match changes in PR-991

- .gitignore
- pom.xml
- tools/cldr-rdf/.settings/org.eclipse.core.resources.prefs
- tools/pom.xml
CLDR-14485
It is optional to use, and for the convenience of Eclipse use
-----
- so with this change, i just run the same maven import at the /cldr level. 
- Seems to work for editing in Eclipse…
Command line building from the tools directory down is unaffected, no files changed there. (I’m not going to rev all of the docs, but `—file=tools/pom.xml` is now optional.)
I don’t want to *require* building from / using the new top level directory, that would break workspaces, build scripts, processes, etc.  for no real benefit at this point. 
You can build from the top level:
```shell
~/src/cldr:$ mvn package -DskipTests=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] CLDR All Tools …
```
> CLDR-14485 add top level maven project

- common/main/nn.xml
In _nn_, delete <miscPatterns numberSystem="latn"> (inconsistent with _no_) to inherit from _no_
> CLDR-14477 nn, delete <miscPatterns numberSystem="latn"> to inherit from no

- common/main/fa.xml
- common/main/ko.xml
In fa, which has a bunch of ASCII &lt;LRM&gt; which were probably intended to be actual \u200E characters:
- If the  &lt;LRM&gt; immediately precedes a strong L character (ASCII letter or µ), then just remove it, it would have zero effect if converted to \u200E
- In the other cases, convert the &lt;LRM&gt; to an actual  \u200E character. Most of these are before a / in a per pattern, which makes sense. Two of them precede a space which is followed by a strong L character; these are probably mistakes but they would have an effect in a R-L context so I did convert them.
In ko, there was one bogus &lt; in Japanese era name, removed it.
I will split off a separate ticket to add tests for a future Survey Tool phase.
> CLDR-14476 fa, remove explicit <LRM> or replace with \u200E; ko, remove a bogus <

- seed/main/en_Dsrt.xml
- seed/main/gaa.xml
- seed/main/sc.xml
- seed/main/szl.xml
- seed/main/trv.xml
- seed/main/trw.xml
-Changed ordering of timezones Currie, Honolulu
-Changed copyright year 2020 to 2021
> CLDR-14491 BRS Task A05.5 : CLDRModify pass 1 seed/main

- docs/ldml/tr35-collation.md
In section 2.5, there's a nested bulleted list. The sentence "An implementation..." should not be part of the inner bulleted list level.
Other cleanup changes:
- In section 1.1.5, two spurious empty cells removed from the first line of the table showing Danish and emoji ordering.
- In sections 3 and 3.1, the `<span class="element">...</span>` formatting was changed to use backquotes in three locations (`collation` twice, and `defaultCollation` once).
- Various "note" type items (from elements using class="note") standardized to begin with: `> :point_right: **Note**:`
> CLDR-14444 tr35-collation markdown changes

- tools/cldr-apps/js/src/index.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
- tools/cldr-apps/src/main/webapp/js/new/cldrAccount.js
-Fix SurveyAjax.doPost bug by skipping antiquated request.getReader code
-The doPost bug involved non-empty qs in POST due to USE_DOJO=...
-Remove recently introduced problematic @WebServlet annotation
-Add test in SurveyAjax for non-UTF-8 request encoding
-Add UserList constructor; misc. improvements to UserList.java (non-dojo)
-Misc. improvements to cldrAccount.js (non-dojo) for mass email, etc.
-Comments
> CLDR-14386 Modernize List Users email/etc; fix SurveyAjax.doPost bug

- common/rbnf/nb.xml
- common/testData/localeIdentifiers/localeCanonicalization.txt
Fixes from integrating CLDR alpha1 (with changes so nb is a child of no, not an alias to it) into ICU.
- Mainly this is just an update to the localeCanonicalization.txt test file, which comes from CLDR but is only used in ICU tests.
- I also cleaned up some spacing in rbnf/nb.xml to be consistent with ofher rbnf files.
> CLDR-14461 update localeCanonicalization.txt for nb as child of no

- tools/cldr-apps/src/main/liberty/config/server.xml
CLDR-14484
should be capital C per https://openliberty.io/docs/20.0.0.12/reference/feature/localConnector-1.0.html
> CLDR-14484 fix typo in server config

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- tools/cldr-apps/src/main/webapp/js/new/cldrForum.js
-Upgrade autosize from 1.18.6 to 4.0.2 (if not using Dojo)
-Revise calling convention in cldrForum.js
> CLDR-14403 Modernize by upgrading autosize

- tools/cldr-apps/js/src/index.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
-New function runGui in index.js calls cldrGui.run
-Move subroutine show() below its caller
-New boolean SurveyTool.RUN_ALL_JS_FROM_BUNDLE
> CLDR-14401 Modernize with ESM; include esm in webpack bundle

- common/testData/units/unitPreferencesTest.txt
The unitPreferencesTest.txt file, which comes from CLDR but is used for ICU tests, needed to be updated due to the changes for mixed metric units in [CLDR-14515](https://unicode-org.atlassian.net/browse/CLDR-14515).
> CLDR-14461 update unitPreferencesTest.txt for changes in CLDR-14515

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
CLDR-14395
in e35a0992b2ffb032c90eb53e9d8b1cceb28cf710 I moved SurveyTool.service() to doGet()
service() was not the right override, but this disabled POST which seems to be used by
the login form.
> CLDR-14395 fix /v to accept POST

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/IntLocsRequest.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/InterestLocales.java
- tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrAjax.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrGenericVue.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrOldVotes.js
-Extensive changes in UserList.java and cldrAccount.js
-Shorten long functions by adding subroutines
-Avoid onsubmit in html: same problem as onclick for ESM
-Change bulk-action button name from Change to Do Action, for consistency
-New getInterestLocales, etc., in cldrAccount.js for setting interest locales
-New api/intlocs endpoint on back end using Liberty Server features
-New api/InterestLocales.java and IntLocsRequest.java
-New UserRegistry.userCanSetInterestLocales
-New version of UserRegistry.setLocales uses CookieSession instead of WebContext
-In cldrAjax.js, for api only, use application/json not application/x-www-form-urlencoded
-Delete unused errorHandler in cldrGenericVue.js
-Comments; clean-up
> CLDR-14554 Modernize My Account; maybe feature-complete

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/webapp/js/esm/cldrAccount.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrListEmails.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrText.js
-New cldrListEmails.js, based partly on old special/tc-emaillist.js
-New UserRegistry.userCanGetEmailList for encapsulation
-In cldrText.js, add `special_list_emails`, combine and sort `special_`
-Comments
> CLDR-14432 Modernize Email Address of Users Who Participated

- tools/cldr-apps/js/src/specialToComponentMap.js
- tools/cldr-apps/js/src/views/LookUp.vue
- tools/cldr-apps/js/src/views/WaitingPanel.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathRequest.java
- tools/cldr-apps/src/main/webapp/js/esm/cldrAjax.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrGear.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrText.js
-New LookUp.vue partly working; revise layout; base locale only affects whatis
-Extend XPathAPI.java with api/xpath/str getByString to convert string to hex and dec id
-Move subroutine getXPathTable to bottom of XPathAPI.java
-Format XPathAPI.java with Eclipse
-New XPathRequest.java to enable POST request for api/xpath/str
-Change tt (obsolete html, triggered vue warning) to kbd
-Prevent addition of USE_DOJO to api/ requests
-Comments
> CLDR-14557 Modernize look up code or xpath (browse)

- common/main/fr.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRUtils.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
Two fixes to make test pass on both the main cldr repo and  on the production data in cldr-staging. The first actualy fixes a problem in the French data.
1. The first issue has to do with how to handle requests for display names that are both short and dialect-style (non-compound); the CLDR spec does not say which to give priority. The fr data in the main CLDR repo was as below, with the items removed as redundant for production data marked with '-':
```
<languages>
<language type="en">anglais</language>
<language type="en_GB">anglais britannique</language>
-    <language type="en_GB" alt="short">anglais (R.-U.)</language>
<language type="en_US">anglais américain</language>
-    <language type="en_US" alt="short">anglais (É.-U.)</language>
<territories>
<territory …
```
> CLDR-14572 remove fr names for short en_GB/US; fix TestMissingStatus to use non-↑↑↑ value

- readme.html
- tools/cldr-code/src/license/THIRD-PARTY.properties
- tools/pom.xml
Update the ICU4J libs in CLDR to the version from ICU main branch as of 2021-03-09, including Elango's fix [ICU-PR-1624](https://github.com/unicode-org/icu/pull/1624) to make compact notation 'c' behave like 'e' in FixedDecimal.
Also update the readme for beta.
> CLDR-14461 update ICU4J libs to version of 2021-03-09 with fix for compact dec e,c; update readme

- common/supplemental/plurals.xml
> CLDR-14581 Change plural rule format from 2e6 to 2c6

- tools/cldr-apps/src/main/webapp/js/esm/cldrSurvey.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrTable.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrVote.js
-Move voting-related code from cldrSurvey.js to new cldrVote.js
-Add stub for cldrVote.pending, call it from handleChangedLocaleStamp
-This will compensate for queueCount call removed from handleChangedLocaleStamp in last PR
> CLDR-14590 Modernize Ajax; prepare revision for pending votes

- tools/cldr-apps/src/main/webapp/js/esm/cldrLoad.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrOldVotes.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrSurvey.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrTable.js
- tools/cldr-apps/src/main/webapp/js/esm/cldrVote.js
-New function cldrVote.isBusy replaces stub cldrVote.pending
-Use both timer and pending count for cldrVote.isBusy
-Move more code from cldrSurvey.js to cldrVote.js, or to cldrTable.js
-Fix scrollToItem to use nearest not middle; avoid scrolling if already visible
-Revise log message in doHashChange, make contingent on CLDR_LOAD_DEBUG
-Comments
> CLDR-14590 Modernize Ajax; implement cldrVote.isBusy

- tools/cldr-apps/src/main/liberty/config/server.xml
This used to be a problem under Tomcat, and somehow randomly bit me on a restart.
Cause the JDBC connection to only use GMT, otherwise I got "unknown time zone CDT"…
> CLDR-14555 Fix Server DB TZ

- tools/pom.xml
Note: this is on the maint branch only.
CLDR 40 can update to release 69 when available.
> CLDR-14461 bump ICU4J level to the ICU 69RC

- docs/ldml/tr35.md
There should not be any uppercase characters in the canonical form of a unicode locale id except inside unicode_language_id
> CLDR-14330 only uppercase characters inside unicode_language_id

- docs/ldml/tr35.md
Make it clear that canonicalization does not 'fix' invalid key values.
> CLDR-14377 Clarify use of the implicit "true"

- docs/ldml/tr35.md
Having
> Step 3 of [https://tools.ietf.org/html/bcp47#section-4.5](https://www.google.com/url?q=https://tools.ietf.org/html/bcp47%23section-4.5&sa=D&ust=1600829915065000&usg=AOvVaw12vD5EzoVl3VFzEyrECMj-)
in the spec -- note the link goes through some Google interstitial -- doesn't make any sense.  Much better for it to be
> Step 3 of BCP 47 [Section 4.5](https://tools.ietf.org/html/bcp47#section-4.5)
which is consistent with the style elsewhere in the document.
> CLDR-14508 Fix a link to BCP 47 Section 4.5 to link directly, not through an interstitial page

- docs/ldml/tr35-info.md
1. In Contents of Part 6, Supplemental section, update the 2.4.1 table title from “Unit Preference Categories” to “Unit Preference” as that is the name of the section 
2. In Section 9.1, in the Alias Attribute Values table, “languagethat” needs a space between the two words (see macrolanguage)
> CLDR-14447 Fixing typos in MD

- docs/ldml/tr35.md
Also fixes typo in the BNF for 'keyword'
> CLDR-14320 clarify ordering of keys in extensions

- docs/ldml/tr35-numbers.md
> CLDR-13221 format for currency symbol at decimal point

- docs/ldml/tr35-general.md
Fixed a few minor formatting issues. The main one that I wasn't 100% sure how to fix is the ↔ symbol which was showing up as an emoji in the markdown, so I made it a code snippet. See the edits in the reference doc linked in the ticket.
> CLDR-14446 Formatting updates for Markdown migration: General

- docs/ldml/tr35-keyboards.md
> CLDR-14528 clarify hex notation in keyboards

- docs/ldml/tr35-info.md
CLDR-14447
cherry-pick of #1138 to maint-39
1. In Contents of Part 6, Supplemental section, update the 2.4.1 table title from “Unit Preference Categories” to “Unit Preference” as that is the name of the section
2. In Section 9.1, in the Alias Attribute Values table, “languagethat” needs a space between the two words (see macrolanguage)
(cherry picked from commit 3a7f05d9ba24ceb97bc4b630ceba197f6f049c08)
> CLDR-14447 Fixing typos in MD (#1138)

- .github/workflows/maven.yml
CLDR-14612
This allows the usual 'maven' build step to be invoked on an arbitrary branch/commit. For example, we could use this to manually build the maint/maint-39 branch.
> CLDR-14612 Add a manual build step for maven

- tools/cldr-apps/src/main/webapp/createAndLogin.jsp
-Delete obsolete reg.setOrgList call from createAndLogin.jsp
-Should have been deleted in earlier PR but jsp callers are not shown by Eclipse
> CLDR-14433 Modernize Add User; fix createAndLogin.jsp

- tools/cldr-apps/js/src/esm/cldrGui.js
-When un-hiding the info panel, make style.display flex, not block
> CLDR-14615 Modernize by fixing UI glitches: info panel scrollbars

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
-Remove old code that was for Dashboard Fix window
-Dashboard could now call cldrInfo.show for Info Panel
-Fix cldrGui.hideRightPanel to set rightPanelVisible = false
-Export cldrGui.showRightPanel so Dashboard can open it
> CLDR-14615 Modernize fix glitches: hideRightPanel; Dashboard

- tools/cldr-apps/js/src/esm/cldrAjax.js
- tools/cldr-apps/js/src/views/AddUser.vue
- tools/cldr-apps/js/src/views/GearMenu.vue
- tools/cldr-apps/js/src/views/LookUp.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/XPathAPI.java
-Back end WhatisResponse.java not serializing to json yet with Open Liberty
-Slow response was already a problem; long-running What Is task should have progress bar
-Show Look up... in the menu for any logged-in user
-Catch exceptions thrown for path not found, avoid useless log messages
-Make more user-friendly message Not Found instead of Status 404...
-Use cldrAjax.makeApiUrl for encapsulation
-Delete dead code from cldrAjax
-Fix Vue browser warning Extraneous non-props: add top-level article tags in 2 templates
> CLDR-14557 Modernize Look Up: disable What Is; various improvements

- tools/cldr-apps/src/main/resources/org/unicode/cldr/web/sql/cldr-forum-participation.sql
CLDR-14539
- SQL error, cldr_users needed to be in lowercase
> CLDR-14539 fix Forum Participation

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartAnnotations.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDayPeriods.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateTransformCharts.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/GenerateScriptMetadata.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java
NOTE: code changes are in v40, but the data is for v39 and the charts for v39 also.
The biggest number of changes was in ToolConstants, where I put in some extra code to distinguish the two ways that we use the version numbers in folder/file names. eg cldr-39.0 vs cldr-39 
Second biggest was in ChartGrammatical forms. I'd done this earlier, but never committed the changes.
(longer term fix would be to only use one style)
> CLDR-14651 fix charts for /trunk/ in link problem, grammatical forms

- tools/cldr-apps/js/src/esm/cldrCoverage.js
- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/views/DashboardWidget.vue
- tools/cldr-apps/js/src/views/MainHeader.vue
-Main header coverage menu display Auto when appropriate
-New function cldrCoverage.effectiveName, use for Dashboard
-New function cldrGui.updateDashboardCoverage called by cldrLoad.handleCoverageChanged
> CLDR-14668 Fix Coverage bugs in modern front end

- tools/cldr-code/pom.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/cldr-json-readme.md
- tools/pom.xml
- automatically copy unicode-license.txt into the CLDR dataset
- also, improve Ldml2JsonConverter response to incorrect -t options
This concludes CLDR-14451
> CLDR-14451 add README.md and LICENSE to cldr-json packages

- tools/cldr-apps/js/src/views/MainHeader.vue
CLDR-14668 MainHeader.vue: make coverage menu reactive
- Vue makes items reactive that are in `data()`, see <https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes>
> CLDR-14668 MainHeader.vue: make coverage menu reactive

- tools/cldr-apps/js/src/esm/cldrCoverage.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrMenu.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/js/src/views/MainHeader.vue
CLDR-14662
- rename Auto to Default
- org coverage is really per locale, store it this way in the APIs
- move the default labelling into the vue code
- add a $forceReload() in MainHeader if the menus change
workaround for a lack of reactivity
> CLDR-14662 fixes to Coverage menu

- CONTRIBUTING.md
- README.md
- common/main/fr.xml
- common/main/hi.xml
- common/supplemental/plurals.xml
- common/supplemental/windowsZones.xml
- docs/ldml/tr35-collation.md
- docs/ldml/tr35-dates.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35-numbers.md
- docs/ldml/tr35.md
- readme.html
- tools/cldr-code/src/license/THIRD-PARTY.properties
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRUtils.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
- tools/pom.xml
- tools/scripts/tr-archive/.gitignore
- tools/scripts/tr-archive/README.md
- tools/scripts/tr-archive/archive.js
- tools/scripts/tr-archive/make-tr-archive.sh
- tools/scripts/tr-archive/package-lock.json
- tools/scripts/tr-archive/package.json
Hello,
Since Kurdish is a macro language, the dialect must be specified fully.
Currently, Kurdish (ku) is set to Northern Kurdish or Kurdish (Kurmanji), so the language name must also be changed. Fixing this error is very important because tech companies often use incorrect language codes.
*Kurdish (Kurmanji) and Northern Kurdish express the same language.
For more information see;
1- https://translatorswithoutborders.org/wp-content/uploads/2017/07/Kurdish-Factsheet-English.pdf
2- https://iso639-3.sil.org/code/kur
* Example for the problem I mentioned above;
Microsoft Translator uses different language codes than the codes in Unicode. Please check. Incorrect codes are used for Kurdish dialects.  https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support
Problems …
> Changing Kurdish to Northern Kurdish or Kurdish (Kurmanji) in CLDR

- tools/cldr-apps/js/src/esm/cldrCoverage.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/views/MainHeader.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- fix orgCoverage missing from data() in MainHeaderVue.js
- update cldrLoad.js / SurveyAjax.java to not pass the org coverage back from
client to server, but send "auto" and let the server figure it out. Otherwise we'd
need to delay load.
CLDR-14668
Note:
- Split off CLDR-14703 to modernize cldrLoad and the General Info page
> CLDR-14668 fix additional coverage/General Info issues

- tools/cldr-apps/js/src/esm/cldrCoverage.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/test/pretty.sh
- prettier on cldrLoad.js
- change effectiveCoverage(locale) to not throw
- speed up pretty.sh (call npx once)
Addresses review comments from #1221
> CLDR-14668 coverage menu/etc

- tools/cldr-apps/js/src/esm/cldrStatus.js
- sessionIdChangeCallback was not being called if the session ID was already set
CLDR-14395
> CLDR-14395 fix sessionIdChangeCallback

- tools/cldr-apps/js/src/cldrVueRouter.js
- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrStatus.js
- tools/cldr-apps/js/src/runGui.js
- tools/cldr-apps/js/src/views/LoginButton.vue
- tools/cldr-apps/js/src/views/MainHeader.vue
- tools/cldr-apps/pom.xml
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/WebContext.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
- tools/pom.xml
- bump commons-codec version to recommended level
- add more <a- components to vue router
- cause cldrGui.run() to erase all <body> elements before starting up
- add basic login form
- update mainheader to hide 'user' icon if no user
- refactor cookie code
- auth/login: fetch from cookie if needed (still need to support anonymous)
- login/out seems to work
- improve error handling in startup
- anonymous sessions (from API)!
- bump woodstox version to most recent (2014) and document why it is there
- prefer 'pw=' for the password query in URL (but still support uid=)
- allow cldrGui.run() to consume a "s=" session param
(which gets removed from the query)
- make cldrGui.run() return a promise
- cleanup how the "/v#" URL is generated from SurveyMain
> CLDR-14395 Improve ST Login

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrStatus.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Auth.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LoginResponse.java
-In setSessionId, call dispatchEvent if and only if id changes
-Call cldrStatus.on earlier so it gets called the first time id changes
-Remove unused LoginResponse.user and LoginResponse.newlyLoggedIn, avoid User serialization errors
-Add console logging for debugging
-Comments
CLDR-14705
> CLDR-14705 Fix log-in bugs

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/FeedBack.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/PermanentVote.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyBulkClosePosts.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserSettingsData.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/StackTracker.java
- replace getDBConnection() with getAConnection() for locations
where commit() is not called (such as read-only usage)
- property org.unicode.cldr.web.DBUtils.DEBUG_DB_OPEN for tracing
where connections are being opened
- update StackTracker to be able to skip with a Predicate<> (debug)
CLDR-14555
> CLDR-14555 reduce JDBC warnings

- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
CLDR-14754 add an assert that the SurveyTool is not busted during tests
Example if #1245 isn't merged:
```
Error: (TestSTFactory.java:55) : SurveyTool shouldn?t be busted!: expected false
```
> CLDR-14754 fail ST tests if SurveyTool becomes busted

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/views/DashboardWidget.vue
-Re-use data if Dashboard was created then made invisible
-But do not re-use data if locale or coverage level has changed
-Enable the user to see newest data from server with new Reload button
CLDR-14746
> CLDR-14746 Retain Dashboard Data on Front End

- common/main/en_IN.xml
CLDR-14674
en_IN compact decimal short forms, add the missing "other" case for 10^14 (100 trillion)
(was missed in https://github.com/unicode-org/cldr/pull/963)
> CLDR-14674 en_IN compact decimals, add missing other case for 10^14

- common/main/vi.xml
CLDR-13541
vi, move from main to aux examplars: f j w z
Note that index exemplars still have F J W Z; I think that is fine, because the index entries may be used for foreign words and names, etc.
> CLDR-13541 vi, move f/j/w/z from main exemplars to aux

- common/main/en.xml
- common/supplemental/coverageLevels.xml
- common/supplemental/metaZones.xml
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/MetazoneSortMode.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-14709
- metaZones.xml
- remove old mappings to Yukon metazone
- change current mappings for America/Dawson and America/Whitehorse from America_Mountain to Yukon
- change golden zone for Yukon from America/Yakutat to America/Whitehorse
- en.xml, add English name for Yukon metazone (only for &lt;standard&gt;)
- coverageLevels.xml, add coverage for Yukon metazone (level 30 for CA, level 80 otherwise)
- MetazoneSortMode.java, update description for Yukon metazone
- PathHeader.txt & TestCoverageLevel.java, remove Yukon from list of deprecated metazones
There did not seem to be anything relevant in XMLSource.java
> CLDR-14709 Remove old Yukon mapping, now use for Whitehorse,Dawson; undeprecate, add coverage

- .github/workflows/ansible-lint.yml
-  due to GPG issue with openliberty
CLDR-14757
> CLDR-14757 ci: temporarily ignore 'vagrant up' failures

- common/main/en.xml
- common/supplemental/attributeValueValidity.xml
- common/supplemental/coverageLevels.xml
- common/supplemental/likelySubtags.xml
- common/supplemental/supplementalData.xml
- common/supplemental/supplementalMetadata.xml
- exemplars/main/rhg_Arab.xml
- seed/main/rhg.xml
- seed/main/rhg_Rohg.xml
- seed/main/rhg_Rohg_BD.xml
- seed/main/rhg_Rohg_MM.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_script_raw.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
CLDR-14633
Add basic support for Rohingya (rhg), per discussion in ticket:
- Add to the set of language names we translate (attributeValueValidity)
- Add display name in English, and include display name in modern coverage
- For script Rohg, make "Hanifi Rohingya" the stand-alone English name, with the combining name being just "Hanifi"
- Add territoryInfo, language info, likelySubtags; change default script from Arab to Rohg
- Add seed locales for rhg, rhg_Rohg, rhg_Rohg_MM, rhg_Rohg_BD with exemplars, layout direction, endonym, and standard time formats that match region timecycle prefs.
> CLDR-14633 Rohingya: name, territoryInfo, likelySubtags, seed locales; change default script

- tools/cldr-rdf/pom.xml
- an incorrect mainClass was there, preventing use of the RDF classes
- in fact, it is better to have no mainClass so that it is given from the command line
CLDR-14769
Discovered this with #1230
> CLDR-14769 fix pom.xml for language group tool (RDF)

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- add a get/set baselineFactory() function to VettingViewer
- use SurveyTool's getDiskFactory() as the baseline factory
CLDR-14758
Ideally, the `get…Factory()` functions would only be used in tests and tools, and not in main library functions.
> CLDR-14758 fix Dashboard for sandbox locales

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- rare occurance
- connection is auto commit (explicit `commit()` may not be called)
CLDR-14555
this code was hit because xpaths became invalid for voting.
> CLDR-14555 remove stray commit() when deleting invalid votes

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/MailSender.java
CLDR-14675
integer comparison was backwards. should have been "logger.getValue() < … FINE" not >=. 
Anyway, there's a function that can be used instead.
> CLDR-14675 reduce MailSender debug output

- common/main/root.xml
- common/main/ru.xml
- common/main/uk.xml
CLDR-13981
The goal was for the root narrow currency symbol for BYN (Belarusian Ruble) and RUR (old Russian Ruble to 1998) to change from Cyrillic "р." to just the ISO 4217 3-letter code, with the "р." added as narrow symbol in Cyrillic locales as necessary.
1. In root that just means removing the currency entries for BYN and RUR, which only had the narrow symbol.
2. be Belarusian already has an antry using a different symbol:
```
<currency type="BYN">
<symbol>Br</symbol>
<symbol alt="narrow" draft="contributed">Br</symbol>
```
3. ru Russian already had the following; we add the narrow symbol for RUR (not strictly necessary):
```
<currency type="BYN">
<symbol alt="narrow" draft="contributed">р.</symbol>
</currency>
<currency type="RUR">
<symbol>р.</symbol>
</currency>
```
4. uk Ukrainian …
> CLDR-13981 Remove narrow symbols for BYN/RUR in root, add elsewhere as needed

- common/supplemental/coverageLevels.xml
CLDR-13605
Expand intervalFormatDateItems coverage to add the following skeletons, all of which exist in data (e.g. in en, fi, ja):
```
<intervalFormatItem id="GGGGGyM">
<intervalFormatItem id="GGGGGyMd">
<intervalFormatItem id="GGGGGyMEd">
<intervalFormatItem id="GyMMMMd">
<intervalFormatItem id="GyMMMMEd">
<intervalFormatItem id="MMMMd">
<intervalFormatItem id="MMMMEd">
<intervalFormatItem id="yMMMMd">
<intervalFormatItem id="yMMMMEd">
```
> CLDR-13605 expand intervalFormatDateItems coverage to include more with MMMMd, GGGGGyM

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
-Make client send change_INFO_EMAIL not CHANGE_INFO_EMAIL
-New getSelectedAction retains menu selection so POST includes change_INFO_EMAIL
-On server, after change, call reg.getInfo to update u.user for correct response to client
-On client, after changing email address, update justUser to the new address
-Remove message: click Change again to see changes; not needed and no Change to click
-Wait until finished forming response string before calling u.ua.put
-Comments
CLDR-14791
> CLDR-14791 enable changing vetter email, name, password, and org

- common/main/en_IN.xml
CLDR-13660
For en_IN, we had changed the compact decimal short forms per https://github.com/unicode-org/cldr/pull/963 to use L for lakh and Cr for crore (as well as T for thousands). However, the long forms were not chnaged; this PR handles the long forms. Basically we copy the short forms, but change L to "lakh" and Cr to "crore", set off with \u202F narrow no-break space.
> CLDR-13660 en_IN, compact decimals long should also use lakh, crore

- common/supplemental/grammaticalFeatures.xml
- common/transforms/Turkmen-Latin-BGN.xml
CLDR-14498
Note: this incorporates the preliminary data from the survey. There are still questions out for about a dozen locales that may result in further changes.
Most of the changes are adding new lines with a restriction to scope="units", to reflect that a subset of the grammatical forms are needed for normal messages with placeholders of formatted units (eg "3.5 kilometers")
There was also a change to sw and zu, which should be changed to 'no information included yet' (that is, removed from the data until we get more information). Also left a note that the data is not completely clear regarding when gender is really only scoped to 'semantic gender' (aka gender of people).
> CLDR-14498 Incorporate information from survey: phase 1

- tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
CLDR-14801
I want to use this from Unicode Tools class Settings, removing the null parameter.
> CLDR-14801 make the single-arg getPath() public

- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-14801
Automatically skip not-recommended scripts.
Saves us from adding every new script to the `script100` pattern in the test code.
*Let me know if you want scripts other than Identifier_Type=Recommended to continue to be listed explicitly.*
> CLDR-14801 TestCoverageLevel auto-skip scripts

- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/paths/missingOk.txt
CLDR-14797
The narrow units are typically a nice-to-have, and this makes them not counted among the Missing. That almost halves the number of Missing items for a language like Croatian.
> CLDR-14797 Dont count narrow units as missing

- common/main/bo.xml
- common/main/bo_IN.xml
- common/main/ii.xml
- common/main/ug.xml
- common/main/yue_Hans.xml
- common/main/zh.xml
- common/main/zh_Hans_HK.xml
- common/main/zh_Hans_MO.xml
- common/main/zh_Hans_SG.xml
- common/main/zh_Hant.xml
- common/main/zh_Hant_HK.xml
- common/supplemental/supplementalData.xml
CLDR-10560
Change time cycle prefs for Chinese regions as described in the bug.
1. CN (zh, yue_Hans; also bo, ii, ug) changes from ah to HH (and make that first preference for pattern char C)
2. TW (zh_Hant) changes from ah to Bh. Affects standard formats, availableFormats, intervalFormats; the latter now have entries for greatestDifference="B".
3. HK,MO continue to use ah (and make that first preference for pattern char C). Per further feedback (as noted in the ticket) there was no need to split HK,MO time cycle behavior by script.
4. SG time cyle prefs are unchanged.
5. zh_Hans_HK, zh_Hans_MO, zh_Hans_SG must now override the standard time formats inherited from zh (which have HH)
6. zh_Hant_HK must now override standard time formats and 'h' formats inherited from zh_Hant (which have …
> CLDR-10560 change time cycle pref/use: CN: HH, TW: Bh, HK/MO: ah

- pom.xml
- tools/cldr-apps/pom.xml
- tools/cldr-code/pom.xml
- tools/cldr-rdf/pom.xml
- tools/pom.xml
CLDR-14711
Finish the SBRS task of updating CLDR version by updating the <version>40.0-SNAPSHOT</version> in all relevant pom.xml files.
> CLDR-14711 SBRS 40: Update CLDR snapshot version in pom files

- common/supplemental/supplementalData.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-13595
Make ckb regions non-secondary in <languageData> so Persian calendar months show up in ST for ckb_IR (and ckb).
Need a way either to
- make that permanent so the next run of ConvertLanguageData does not revert
- provide a different solution that assoicates IR with ckb for coverage purposes; that can be associating all regions (and scripts) for which we actually have a locale with the corresponding language for coverage purposes.
Either way that can be another PR.
> CLDR-13595 Make ckb regions non-secondary so Persian cal months show up in ST for ckb

- tools/cldr-apps/js/src/views/DashboardWidget.vue
-In DashboardWidget.vue, use key g.section + g.page + g.header, instead of just g.header
-Delete unused deprecated getJSONReview in VettingViewerQueue.java
CLDR-14765
> CLDR-14765 stui: Dashboard vue warning

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/views/WaitingPanel.vue
- tools/cldr-apps/js/test/pretty.sh
- just go back to the default (locales) page if ST is up
- show a brief popup on reconnect
- also document cldrGui.run()'s callers
- fix a minor pretty.sh script error
CLDR-14790
brief popup below:
It's not visible in the screen shot, but the URL goes back to `/cldr-apps/v#locales///` with the usual locale list on the left
> CLDR-14790 break the error loop on #retry

- common/main/en.xml
- common/main/root.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartGrammaticalForms.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateAllCharts.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListGrammarInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/UnitConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/ValuePathStatus.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
CLDR-14824
This is the first of many chart generations for v40. In this PR:
1. Fixes the omission of 'item' from root.
2. Adjusts the ChartGrammatical forms because some of the units may not have gender values yet.
3. Adds a tool ListGrammarInfo.java for generating the table at the top of http://cldr.unicode.org/translation/grammatical-inflection
4. Fixes GrammarInfo.java to have a superset of the case values, and to validate the enum values when supplemental data is read.
5. AdjustsValuePathStatus.java because count values may be integers. (and are)
> CLDR-14824 Generate new charts, and make any necessary fixes.

- common/main/zh_Hant.xml
CLDR-14711
While doing a first integration of CLDR 40 into ICU (i.e. an "m1" integration reflecting the state of CLDR soon after the beginning of data submission), ICU tests demonstrated the need to copy some zh_Hant availableFormats for times from the generic to the roc calendar. (This is related to the change in zh_Hant time formats to use Bh)
> CLDR-14711 SBRS 40, adjust zh_Hant based on first ICU integration

- tools/cldr-apps/js/src/cldrVueRouter.js
- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/views/DashboardWidget.vue
- tools/cldr-apps/js/src/views/WaitingPanel.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyTool.java
Bugs Everywhere! Well, hopefully not. This PR catches the rest of the err cases (the known knowns!) that
ought to make "ST seems stuck/dead/hung" move even more towards 0%.
- the 'waiting' page is not able to run cldrGui.run(), we just need to reload first.
- make cldrGui.run() throw an exception instead of 'doing nothing'.
- also, annotate which function generated the /v page
- show err if there's a problem mounting the main header
- fix a css err in dashboardwidget
- add an error handler when mounting vue components
CLDR-14790
Note: The following are all _simulated_ errors! (hence 'foo')
> CLDR-14790 handle another case where ST could not coldstart

- tools/pom.xml
CLDR-14711
Update the ICU4J libs in CLDR to an ICU snapshot of 2021-06-15 - after integrating CLDR release-40-m1 to ICU per ICU [PR-1742](https://github.com/unicode-org/icu/pull/1742) - which among other things adds ICU support for the new measure units "concentr: item" and "force: kilowatt-hour-per-100-kilometer".
> CLDR-14711 update ICU4J libs to version of 2021-06-15 after integrating CLDR 40 m1

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
CLDR-14801
It relied on old redirects.
> CLDR-14801 fix a unicode.org/unicode/ URL

- tools/cldr-code/src/main/java/com/ibm/icu/dev/test/TestFmwk.java
- tools/cldr-code/src/main/java/com/ibm/icu/dev/test/UnicodeKnownIssues.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestLocale.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
- tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/AbstractCache.java
CLDR-14588 fix known issues output, reduce test noise
- known issues (ICU and CLDR) are now valid urls once more
- quiet abstractcache errors (don't need full stacktrace for missing file)
- quiet a number of other tests, logger available from getLogger()
- only show n (default: 2) lines of 'known issue' output, to keep the output manageable
All output is still available using for example:
`mvn --file=tools/pom.xml test -pl cldr-code '-Dorg.unicode.cldr.unittest.testArgs=-allKnownIssues -n -q'`
With this fix, output is as below. Note that excessive known issues are rolled up, but `-allKnownIssues` will show all lines.
```
13 Known Issues:
CLDR-11583 <https://unicode-org.atlassian.net/browse/CLDR-11583>
- CLDR/TestBasic/TestBasicDTDCompatibility (Comment out test until last release data is …
```
> CLDR-14588 fix known issues output, reduce test noise

- common/annotations/en.xml
- common/main/en.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckWidths.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckWidths.java
CLDR-14808
Restructures the unit width checks for excessive length (short and narrow) to be much more granular. That is, it takes into account the subunits (eg in kilowatt-hour) and allows non-metric units to be longer (since there are often no good abbreviations for them in languages with metric units).
Information is cached for the extra unit data, so we shouldn't see significant performance cost. Would appreciate Steven's taking a look at the caching.
Note: makes some small changes in en.xml to fix excessive widths (don't want warnings from en).
> CLDR-14808 Revamp unit width tests to be more granular

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java
CLDR-14810
So many of the units are SI (and thus common across languages) or are English units (and thus ok to be copies) that all checks for same as units are disabled.
> CLDR-14810 Suppress some same as English warnings

- common/supplemental/likelySubtags.xml
- exemplars/main/kdh.xml
- exemplars/main/kdh_Arab.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/external/langtags.json
CLDR-14846
Note that git may tell you that 
- kdh.xml is modified
- kdh_Latn.xml renamed kdh_Arab.xml
In reality, two files were renamed without modification:
- kdh.xml renamed to kdh_Arab.xml
- kdh_Latn.xml renamed to kdh.xml
> CLDR-14846 change kdh default script

- .github/workflows/production.yml
- Create a tag of the form `production/2021-06-22-2206z` during
the manual push to production process.
- The date and time are UTC (June 22nd, 22:06 UTC)
CLDR-14841
Example tag: https://github.com/srl295/cldr/releases/tag/production%2F2021-06-22-2206z
I have tested the exact code stanza involved, but have not tested an actual push to production (I had my test case stop before continuing that far).
Probably once this is merged, we will want to test it with an actual push. It could wait to merge until the next time we're doing such a push.
> CLDR-14841 create production tag on push to production

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestSTFactory.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-Add tests for two rules:
--- (1) For a 20 vote item, 8 votes are needed to change from non-approved to approved
--- (2) Once Approved, it requires 20 votes to change
-Revise VoteResolver to pass both tests; adjust from HIGH_BAR (20) to LOWER_BAR (8) if not approved
-Revise SurveyJSONWrapper.wrap(VoteResolver) to send client the adjusted required votes
-Remove unneeded 3rd arg of computeStatus (always trunkStatus)
CLDR-13928
> CLDR-13928 Value for 20-vote item moved to Winning column with 8 votes

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Race.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
-In VoteResolver.canFlagOnLosing the threshold is 20 (HIGH_BAR), never 8
-Revise tests to take baselineStatus into account
-Rename ...trunk... to ...baseline...
-Avoid awkward names/implementations like getAdjustedRequiredVotes
-Refactor VoteResolver to postpone all calculation of required votes until locale, path, and baseline status are set
-Reduce hard-coding of numbers 4, 8, ..., in tests
-Comments
CLDR-13928
> CLDR-13928 Revise canFlagOnLosing, false if need 8 votes; refactoring, renaming

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNew.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateBirth.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
CLDR-13853
After a few wild goose chases, tracked down the problem. The code used in VettingViewer for english changed was no longer in sync with CheckNew, so fixed that. Will have to check it out on Smoketest.
> CLDR-13853 reduce the number of english changed

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckDisplayCollisions.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ListSurveyToolStatus.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
CLDR-14807 
The ticket will have 3 parts:
1. Make sure the special durations for persons don't collide.
2. Make the alias mechanism more robust where it could need recursion.
3. Make the iteration over aliases also more robust.
This PR should address the first item, but more work needs to be done on #2 and #3, which were encountered while doing #1. It is worth starting with #1, since it will unblock the vetters on fixing current errors.
The PR also adds a tool used in testing.
> CLDR-14807 fix day-person collisions

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- interest loc calculation was incorrect for users below the manager level
- fix SQL issue that prevented updating interest locales for all users
CLDR-14597 but related to CLDR-14850
> CLDR-14597 fix interest locales

- .vscode/settings.json
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java
- use JUnit5 for a modern test experience
- add a VSCode settings file for test execution
CLDR-13853
depends on #1343
> CLDR-13853 unit test for VettingViewer English Changed

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/GrammarInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-14101
ExampleGenerator.java
I also did a bit of cleanup, moving the fields up to the top with statics before non-statics. supplementalDataInfo could be initialized statically also.
Main changes are
- private String handleMinimalPairs(XPathParts parts, String minimalPattern) - all new
- private String getBestUnitWithGender(String gender) - all new. Not quite sure about threading with the caching pattern used
- private String handleFormatUnit(XPathParts parts, String value) - adds use of minimal pairs for context
GrammarInfo.java - just some minor reformatting
TestExampleGenerator.java
- Added tests for the two additions (minimal pairs, units with minimal pairs)
> CLDR-14101 add examples for minimal pairs, units with grammar

- tools/cldr-apps/pom.xml
- tools/cldr-code/pom.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckMetazones.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-code/src/test/java/org/unicode/cldr/test/TestCheckMetazones.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
- tools/cldr-rdf/pom.xml
- tools/pom.xml
- add a check that CLDRFile.getRawExtraPaths() does
not show DST strings for non-DST metazones
- update getRawExtraPaths() to not include such paths
- include junit params for parameterized tests
- simplify junit pom dependencymanagement, remove an unneeded entry (bare "junit" not used anywhere)
CLDR-14858
> CLDR-14858 Yukon should not show DST strings

- common/collation/bo.xml
CLDR-9895
Per CLDR TC discussion, this PR changes the draft status of the Tibetan ("bo") collation from unconfirmed to contributed.
> CLDR-9895 change bo collation draft status from unconfirmed to contributed

- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
-New unit test TestSplitBar for danda and lowercase l
-New BAR_REGEX used only by SPLIT_BAR, handles danda like pipe
-Construct regex from pieces for clarity and maintainability
-Comments
CLDR-14898
> CLDR-14898 Devanagari danda instead of pipe in emoji keywords

- common/annotations/en.xml
Removing "busstop" due to spelling error.
CLDR-14895
> CLDR-14895 remove busstop

- .github/workflows/ansible-lint.yml
- this test has been hanging, as a stopgap fail fast after 10m
- test should take a few seconds to run
CLDR-14408
> CLDR-14408 build: timeout for JS tests

- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAnnotations.java
CLDR-14803
The source for the test says:
```java
/** The English name should line up with the emoji-test.txt file */
```
…this change makes the test print out something to that effect.
> CLDR-14803 improve error message for TestNamesVsEmojiData

- common/main/ar_AE.xml
> CLDR-14892 ar_AE should default to "latn" digits

- common/main/en.xml
CLDR-14781
In English, add alt=menu variants for Sami language names.
Too late in CLDR 40 to collect these for other display languages.
> CLDR-14781 en: add menu variants for Sami language names

- common/collation/br.xml
CLDR-14863
I searched through all locales in common/main to see if any other exemplar sets included instances of u2019, u02BC or u0027 between a pair of letters, and did not find any other instance.
> CLDR-14863 br: add \u02BC to collation-equivalent apostrophes between c,h e.g. cʼh

- tools/cldr-apps/js/package.json
CLDR-14408
per https://github.com/shellscape/mocha-chrome/issues/32#issuecomment-539599328
Update timeouts to give the FE tests a better chance of running
> CLDR-14408 improve FE test timeouts

- tools/scripts/ansible/backup-db-playbook.yml
- tools/scripts/ansible/templates/cldrbackup/backup_sh.j2
-Change backup starting time to 14:53 UTC = 7:53 PDT or 6:53 PST
-Comments in backup-db-playbook.yml and backup_sh.j2
CLDR-14931
> CLDR-14931 Change timing of automatic Survey Tool database backups

- common/annotations/kab.xml
- common/main/kab.xml
- common/annotations/kab: remove colliding strings
- common/main/kab: remove 'SX' translation as colliding with 'MF'
CLDR-14952
> CLDR-14952 v40 fixes

- common/supplemental/dayPeriods.xml
CLDR-14957
The CLDR 40 Survey Tool phase added dayPeriods (besides just am/pm) for nn Nynorsk, but dayPeriods.xml did not actually specify the day period rules for nn, so just added nn to the list of locales for the Norwegian day period rules.
> CLDR-14957 include nn in dayPeriod rules for Norwegian

- common/annotations/kab.xml
- common/annotations/zu.xml
annotations: votes for triple-up-arrow are causing "must be a real value" errors. Removed from:
- kab.xml
- zu.xml
CLDR-14952
> CLDR-14952 remove triple up arrow in annotations

- common/annotations/hy.xml
CLDR-14957
In hy Armenian, rename emoji annotation for red hair component to avoid conflict. Fixes all of the related conflicts.
> CLDR-14957 hy, rename emoji annotation for red hair to avoid conflict

- common/dtd/ldml.dtd
CLDR-14957
ldml.dtd needs to list 5 more grammatical forms for the case attribute of the &lt;unitPattern&gt; and &lt;caseMinimalPairs&gt; elements: elative, illative, partitive, terminative, translative.
> CLDR-14957 dtd needs to list 5 more grammatical forms for case attribute of <unitPattern> & <caseMinimalPairs>

- common/annotations/ru.xml
> CLDR-14780 Typo in ru-RU annotation for 👾 emoji

- common/main/km.xml
Time durations were incorrectly replaced with localized duration units in the patterns.
CLDR-14722
> CLDR-14722 Fix Khmer duration patterns

- seed/main/bal_Latn.xml
CLDR-14966
This should correct 188 bal_Latn final testing errors (by removing incomplete decimalFormatLength elements, Chinese yuan currency element).
> CLDR-14966 clean up bal_Latn errors

- seed/main/bal.xml
CLDR-14966
Should resolve 8 bal final testing errors (by removing incomplete decimalFormatLength elements, Chinese yuan currency element, and correcting name of Western Argentina time zone).
> CLDR-14966 clean up bal errors

- common/main/doi.xml
Delete relative Sunday value to fix doi error.
doi [Dogri]	error	▸Date_&_Time|Fields|Relative_Sunday|0◂	〈this Sunday〉	【】	〈this Sunday〉	«=»	【】	⁅incomplete logical group⁆	❮Error: Incomplete logical group - missing values for: [0]; level=modern❯	https://st.unicode.org/cldr-apps/v#/doi//34da11643c7613cf	root
https://gist.github.com/srl295/1b17f5b76b613ed75a82b16c31cc726a
CLDR-14966
> CLDR-14966 Fix doi errors

- common/main/be_tarask.xml
- common/main/ee.xml
- common/main/gu.xml
- common/main/sv.xml
- common/main/yo_BJ.xml
CLDR-14966
* be_tarask 
* name for width/100 normal conflicts with weight/100 regular (which is same as in "be"); both important, so convert the "be" name for width/100 using tarask transliterator
* ee 
* duration/minute/short too wide, copy value from narrow
* gu 
* angle/radian/short too wide, copy value from narrow
* sv 
* remove provisional status for narrow kilowatt-hour-per-100-kilometer/other, matches confirmed short & long
* yo_BJ 
* light/lumen/short too wide, copy value from long (which is shorter!)
> CLDR-14966 fixed various final_testing errs in be_tarask,ee,gu,sv,yo_BJ

- common/annotations/kab.xml
- common/main/kab.xml
CLDR-14966
Fixes kab errors. Kept consistent with 39 for where there were errors.
Note: Garlic appeared to have another term as well: https://polyglotclub.com/wiki/Language/Kabyle/Grammar/Noun-Gender
> CLDR-14966 Fix kab errors

- docs/ldml/tr35.md
- en_US_POSIX is not a bcp47 id, and so is not subject
to bcp47 locale canonicalization. Clarify that conversion from
a legacy format to bcp47 is a prerequisite to canonicalization.
CLDR-14487
> CLDR-14487 doc: clarify legacy variant (en_US_POSIX)

- common/supplemental/likelySubtags.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
- tools/pom.xml
CLDR-14783
Update to use libs from latest ICU4J, tagged "cldr/2021-08-11", which adds Unicode 14 support. That requires likelySubtags & test/tool support for an additional ancient script Cpmn "Cypro-Minoan" (already have en name for it).
> CLDR-14783 update ICU4J libs to version of 2021-08-11 with Unicode 14 beta

- common/main/ckb_IR.xml
CLDR-13595
Compared the names requested in the bug to the Kurdish names in
https://en.wikipedia.org/wiki/Solar_Hijri_calendar#Months
and also to the unconfirmed names in ckb.
The bug had the names for months 5 and 6 swapped; compared to wikipedia it also added a space in month 3 and used a different final character for month 4. I went with the wikipedia data instead.
This completes the data changes for the bug, but in the ticket I also proposed a change to SupplementalDataInfo. getTargetTerritories which I will do in another PR.
> CLDR-13595 ckb_IR, add Persian calendar month names

- common/supplemental/plurals.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNumbers.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleIDParser.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PluralRulesUtil.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-14187
This is copying the 'many' category to es, it, pt, and pt_PT, plus a test fix.
> CLDR-14187 Update plural many category for some romance languages

- docs/ldml/tr35-dates.md
Interval formats are split on a repeating field however
in at least one case (in locale "fa") there is no repeating
field since the "left" side of the pattern uses "L" and
the right side uses "M".
This commit notes that when determining a repeating field
at which to break the pattern into "left" and "right",
standalone fields (like "L") are considered equivalent to
format fields (like "M").
CLDR-14971
> CLDR-14971 Update TR35 Dates interval pattern

- common/main/mt.xml
- many per EU Annex A5 for Maltese
CLDR-13391
Note: confirmed with Kunsil tal-Malti
> CLDR-13391 mt: Language and Region fixes

- common/main/uk.xml
CLDR-14423 - Use the year marker 'р'." consistently in Ukrainian
Please check spreadsheet attached to issue for additional feedback from the linguist
> CLDR-14423 Use year marker " 'р'." consistently in uk

- common/dtd/ldmlICU.dtd
- common/testData/units/unitPreferencesTest.txt
- common/transforms/Any-Accents.xml
- common/transforms/Bulgarian-Latin-BGN.xml
- common/transforms/Greek_Latin_UNGEGN.xml
- common/transforms/InterIndic-Gurmukhi.xml
- common/transforms/InterIndic-Latin.xml
- common/transforms/Latin-ConjoiningJamo.xml
- common/transforms/Latin-InterIndic.xml
- common/transforms/am-am_FONIPA.xml
- common/transforms/cs-cs_FONIPA.xml
- common/transforms/es-es_FONIPA.xml
- common/transforms/es_FONIPA-zh.xml
- common/transforms/it-ja.xml
- common/transforms/sat_Olck-sat_FONIPA.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/api/LocaleIds.java
- tools/cldr-code/src/main/java/org/unicode/cldr/icu/ICUID.java
CLDR-14976
Misc fixes from integrating CLDR release-40-alpha0 to ICU:
- Support the lstm data for break iterators (special ICU type like dictionaries etc.)
- Handle the "tarask" variant in lower case (as in the filename, and in the validity data for example)
- Miscellaneous spelling fixes already made in the ICU copies of some CLDR-derived data
> CLDR-14976 40a0 integration: handle brkitr lstm data, allow tarask variant, spelling fixes from ICU

- common/supplemental/attributeValueValidity.xml
- common/supplemental/supplementalMetadata.xml
- seed/main/ab.xml
- seed/main/ab_GE.xml
> CLDR-14954 Add Abkhazian locale to CLDR

- common/main/be_TARASK.xml
- common/main/en_CA.xml
CLDR-14976
Two more fixes for CLDR alpha0 integration to ICU:
1. en_CA needs to specify USD symbol as "US$" which it used to inherit from en_001
2. For be_tarask, the variant needs to be uppercase
> CLDR-14976 CLDR 40 a0, fix en_CA symbol for USD, make tarask uppercase

- common/main/az_Cyrl.xml
CLDR-14646
<territory type="CI">Kотд’ивуар</territory> was using a Latin K when all other cases used a Cyrillic K
Replaces https://github.com/unicode-org/cldr/pull/1183 which had a bad commit message
> CLDR-14646 az_Cyrl Latin K to Cyrillic K

- common/main/es.xml
- common/main/it.xml
- common/main/pt.xml
- common/supplemental/plurals.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratedPluralSamples.java
CLDR-14982
Fixes the plural samples for pt, es, it.
> CLDR-14982 fix plural samples

- common/annotations/en_CA.xml
- common/main/en_CA.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt
That is, with the new inheritance, the resolved file is the same as the resolved file with the old inheritance.
That is, the revised file has items that were in the old en_001 + en_CA but not in en.
That means people won't see a difference in the results that they saw in the ST. Note that in the process, the up arrows are removed. That won't make any effective difference: for the release they are removed anyway, and during the next cycle people's votes for inheritance should be restored (since those will be the winning values).
CLDR-14635
> CLDR-14635 change the en_CA data for the new inheritance

- common/main/de.xml
CLDR-14976
Once again, for German compact decimals, revert formats for 1000..100000 to use just 0 (as in https://github.com/unicode-org/cldr/pull/151 and 2 or 3 others), not formats with Tsd.
> CLDR-14976 de: compact decimals, revert formats for 1000..100000 to use 0, not Tsd.

- common/main/en_001.xml
CLDR-14976
In https://github.com/unicode-org/cldr/pull/1445, as part of CLDR-14984 update en_001 from en_GB, the time formats with HH were added to en_001, overriding the time formats with h inherited from en. This breaks nearly all child locales and should *not* be done as part of the en_001 updates, as discussed in previous CLDR releases. This PR reverts that part of the en_001 updates.
> CLDR-14976 en_001, revert add of HH time formats

- common/bcp47/timezone.xml
CLDR-14607
We had
```
<type name="gaza" description="Gaza Strip, Palestinian Territories" deprecated="true" alias="Asia/Gaza gazastrp"/>
<type name="gazastrp" description="Gaza Strip, Palestinian Territories" alias="Asia/Gaza"/>
```
but the first entry had two problems: the deprecated "gaza" short ID should not have the alias mapping to Asia/Gaza (that conflicts with the correct mapping from Asia/Gaza to gazastrp), and its reference to "gazastrp" should be via a preferred attribute, not an alias.
> CLDR-14607 deprecated gaza should NOT alias to Asia/Gaza but SHOULD have a preferred mapping to gazastrp

- .github/workflows/build-icu.yml
CLDR-14989
This is a first step, just producing production data on request.  Manually launched. Your choice of CLDR ref to build. outputs a .zip file with production data.
See an example run with .zip attached at:
https://github.com/srl295/cldr/actions/runs/1206942094
I will be adding the ability to build with ICU, but that may take some more debugging. This workflow will be useful as is for producing production data.  Additionally, the cldr-code .jar file is attached to the run.
> CLDR-14989 GitHub Action to produce CLDR Production Data

- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
CLDR-15024
Note that the old comment says specifically "does not skip inheritance marker", but made a function call that **did** skip the inheritance marker.
Note that we would still have to change our process for generating charts, as in the ticket.
> CLDR-15024 get correct coverage information

- common/dtd/ldmlSupplemental.dtd
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
CLDR-14571
- omit _deprecated:false (the default)
- use _deprecated: true (a boolean instead of string)
- remove debugging string
Also:
- CLDR-14607: whitespace fix in DTD
fyi @nordzilla 
Examples:
This under JSON package **cldr-core** supplemental/metaZones.json
```json
"supplemental": {
"metaZones": {
"metazoneIds": {
"acre": {
"_longId": "Acre",
"_since": "40"
},
"afce": {
"_longId": "Africa_Central",
"_since": "40"
},
"afea": {
"_longId": "Africa_Eastern",
"_since": "40"
}
}
}
```
And a contrived example on incorrect data, just to show that other fields work:
```json
"chil": {
"_deprecated": true,
"_longId": "Chile",
"_preferred": "EST3CDT",
"_since": "22"
},
```
Note that `_deprecated`  is omitted unless `true` in which case it is a boolean.
> CLDR-14571 json: improve format of metazone short alias

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateSidewaysView.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
-Remove superfluous path exclusion checks for altProposed, /references
-Refactor and format DataSection.ensureComplete to clarify it only applies to timeZoneNames paths
-Use ph.shouldHide instead of SurveyToolStatus.DEPRECATED/HIDE where the distinction is unneeded
-Simplify code that had impossible conditions in TestPathHeader
-Fix deprecation warnings for SurveyLog, setCldrFileToCheck
-Comments, clean-up
CLDR-14877
> CLDR-14877 Coverage Progress Bars

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Timer.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_bcp47.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt
- add a "-t all" that converts all types in one operation
- use a modern Timer for progress
- update progress messages
- modify some paths to use valid bcp47 values
- produce bcp47 locale ids for files, such as und, ca-ES-valencia, en-US-u-va-posix
- add a new tool option --bcp47=false which produces the old behavior (for compatibility)
- correct JSON_config_bcp47.txt (update to CLDR-14571)
CLDR-14642
> CLDR-14642 json: bcp47 filenames and values

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Timer.java
- skip locales with subtags (currently: en-US-u-va-posix)
This behavior is controlled by the -T option
- add a hasLocales() property to RunType, which could simplify
many if clauses
- fix Timer use to show min/sec instead of nanoseconds
CLDR-14642
> CLDR-14642 cldr-json: skip en-US-u-va-posix

- tools/pom.xml
CLDR-14783
One more update of ICU4J libs in CLDR to pick up latest Unicode 14 support changes. No issues found in unit tests or ConsoleCheck.
> CLDR-14783 update ICU4J libs to version of 2021-09-15 with latest Unicode 14 support

- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
-Add two patterns to coverageLevels.xml, for de only
-Add a test in TestCoverageLevel.java for paths that should and should not match the new patterns
-Refactor TestCoverageLevel.java by moving some duplicated code to a new subroutine
CLDR-14988
> CLDR-14988 Mark specific paths as requiring a 20-vote override

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestSTFactory.java
-In voteForValue, call setValueFromResolver with resolveMorePaths true so vote resolution is not bypassed
-In setValueFromResolver, fix handling of Status.missing: no premature return, must update delegate
-Change setValueFromResolver from public to private since only called locally
-Change TestSTFactory.TestSparseVote to expect inheritance, not null
-Rename some variables in TestSTFactory.TestSparseVote
-Comments
CLDR-14945
> CLDR-14945 Abstain should not cause disappearance of inherited item

- tools/pom.xml
CLDR-14976
Update IC4J libs in CLDR to ICU release-70-rc. Since for some reason that release-70-rc tag was not available in https://github.com/unicode-org/icu/packages/411079/versions (github action failure?), created a separate but equivalent ICU tag "cldr/2021-09-29" and used that instead.
> CLDR-14976 update ICU4J libs to release-70-rc (use different but equivalent tag)

- common/main/sr.xml
- common/main/sr_Latn.xml
CLDR-15081
For sr and sr_Latn, revert the Gregorian-calendar format-style wide month names to nominative form, as in CLDR v39.
> CLDR-15081 sr[_Latn], revert grego format month names to nominative as in v39

- docs/ldml/tr35-general.md
- docs/ldml/tr35.md
CLDR-14751
* Note that this doesn't remove the old Modifications; that is in a separate ticket
* Also, the syntax is different than originally proposed: see ticket
> CLDR-14751 unit number prefixes

- common/supplemental/languageInfo.xml
CLDR-14635 Philippines English ...
(and CLDR-14544 Canadian English should fallback to en instead of en-GB)
The two tickets above are about making en_CA and en_PH closer to en[_US] than to en_001/en_GB (both for formats and for vocabulary/orthography). The original PRs for those tickets changed the supplemental parentLocales for en_CA/en_PH but dit not change the Language Matcher data; this PR fixes that to also update the Language Matcher data.
Amazingly, this did not require any CLDR unit test updates (though we have a ticket to add tests specifically for this: https://unicode-org.atlassian.net/browse/CLDR-15082)
> CLDR-14635 Update languageInfo to make en_CA and en_PH closer to en_US

- docs/ldml/tr35-general.md
- docs/ldml/tr35.md
CLDR-15035
While cleaning up the EBNF and other items listed in the ticket, I also reordered the text in that section to make it flow better. That included recasting some of the tables.
The EBNF is also reordered to have the core unit identifier first, then the mixed unit identifier, and finally the long unit identifier.
> CLDR-15035 clean up unit identifier BNF and text

- docs/ldml/tr35.md
CLDR-14971
This just updates the spec mods section to reflect the body changes made in https://github.com/unicode-org/cldr/pull/1428 (clarifying that when determining the repeating field of an interval pattern, standalone and format fields are considered equivalent).
> CLDR-14971 update spec mods for intervalFmts repeat fields clarification

- tools/cldr-apps/js/src/esm/cldrSurvey.js
-In cldrSurvey.chgPage set id to null to prevent warning when that id is not found on new page
CLDR-15126
> CLDR-15126 Bogus xpath warning when press Previous or Next button

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/js/src/esm/cldrStatus.js
- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/js/src/views/MainHeader.vue
- tools/cldr-apps/js/src/views/ProgressMeters.vue
- tools/cldr-apps/js/test/TestCldrStatus.js
- tools/cldr-apps/src/main/webapp/css/redesign.css
-Bug fix: filter for coverage when count rows in section
-Bug fix: avoid division by zero
-Make user-friendly percentage, never round down to zero or up to 100
-Implement a front end for locale completion
-Update voter completion after vote/abstain, updateStatsOneVote just as for section completion
-Call cldrLoad.handleCoverageChanged from cldrLoad.coverageUpdate, do not wait for menu choice
-Improve layout and style consistency of nav-page
-Refactor with new class MeterData; the vue component only has display logic
-Improve cldrStatus.setCurrentId and its unit test: normalize to string
-Remove unneeded timeout for cldrProgress.insertWidget
-Remove some unused imports and exports
-Comments
CLDR-15056
> CLDR-15056 Coverage Progress Bars front end

- common/main/bo.xml
- common/main/ig.xml
- common/main/ku.xml
- common/main/pa.xml
- common/main/smn.xml
- common/main/tg.xml
- common/main/to.xml
- common/main/tt.xml
- common/main/vai.xml
- common/main/wo.xml
- common/main/yi.xml
- seed/main/co.xml
- seed/main/trw.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAlt.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckAltOnly.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckAltOnly.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckDisplayCollisions.java
-New CheckAltOnly.java to check if only the alt path is present but the non-alt path is absent
-New CheckCLDR.CheckStatus.Subtype.missingNonAltPath
-New TestCheckAltOnly.java (unit test for CheckAltOnly.java)
-CheckAltOnly: no error for the root locale
-CheckAltOnly: no error if the non-alt path has a constructed value
-CheckAltOnly: no error if getSourceLocaleIdExtended does not return XMLSource.CODE_FALLBACK_ID
-CheckAltOnly: no error if currency symbol with alt is same as root alt value
-XML data changes: remove alt from error-triggering paths (move to non-alt) for locale display names
-XML data changes: delete currency types RUR in pa.xml and GEL in to.xml
-Fix TestCheckDisplayCollisions: frCaResolved was clearly intended to be resolved
-Fix some warnings
-Remove some …
> CLDR-13731 Report in ConsoleCheck if alt without non-alt

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
-Change newline to br tag where a newline might disappear with FormData
-Fix substitution for apostrophe: ASCII 39 (U+0027) not quot (U+0029)
-No longer use unneeded sendWhatTranslit
-Work around a js error when missing json.stats_bydayuserloc
CLDR-14818
> CLDR-14818 Survey Tool admin message formatting problems

- .github/workflows/production.yml
-Change the prompt from ...(main, hash, tag) to ...(hash: 40 hex digits)
CLDR-15151
> CLDR-15151 Tag does not work for Push to Production

- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/js/src/views/ProgressMeters.vue
CLDR-15161
Hide meters that aren't present, particularly the Locale Progress
> CLDR-15161 Hide progress meters that aren’t present

- tools/cldr-code/src/main/java/org/unicode/cldr/test/SubmissionLocales.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDelta.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
As a result, paths should be votable if:
1. they are in any of these 3 locales, OR
2. they are long units in grammar locales
SubmissionLocales.java
- Restructured to make this easier in the future. Mostly renaming of constants for clarity, which percolated into 3 other files.
TestCheckCLDR.java
- Dropped some old code that checked for scripts (without being needed).
- Added the ability to print out the results of the allowed paths for sanity checking.
ChartDelta.java, TestUtilities.java
- Just the results from renaming constants in SubmissionLocales.java
CLDR-15183
> CLDR-15183 enable Rohingya, Bodo, Kashmiri

- tools/cldr-apps/js/src/esm/cldrMenu.js
- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/js/src/views/DashboardWidget.vue
-Hide the 2nd meter (Voter Completion) until the back end works
-Do not try to fetch data for 2nd or 3rd meter until the back end works
-New booleans in cldrProgress.js: CAN_GET_VOTER_PROGRESS, CAN_GET_LOCALE_PROGRESS
-Fix bug: Dashboard would reload after all-row getrow request though coverage unchanged
-In cldrMenu.js, do not call cldrLoad.coverageUpdate unless effectiveName changes
-In DashboardWidget.vue, do not call this.reloadDashboard unless this.level changes
CLDR-15056
> CLDR-15056 Coverage Progress Bars, hide 2nd meter, fix dashboard reload

- tools/cldr-apps/js/src/esm/cldrProgress.js
-If CAN_GET_VOTER_PROGRESS is false then the view needs un-hiding for Section Meter
-No Section Meter if not logged in
-Comments
CLDR-15056
> CLDR-15056 Coverage Progress Bars, fix to show at least Section Meter

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Level.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLevel.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestStandardCodes.java
CLDR-15161
- API scaffolding for back end for locale (third) meeting
Front End fixes:
- reload locale progress if locale changes or if there is a vote
Also:
- implementation and tests for StandardCodes.getTargetCoverageLevel()
- implementation and tests for Level.min() and Level.max()
> CLDR-15161 locale completion API

- .github/workflows/gh-pages.yml
- .gitignore
- docs/.gitignore
- docs/_config.yml
- docs/index.md
- tools/scripts/tr-archive/make-tr-archive.sh
- build into the 'gh-pages' branch instead of using Github Pages default build
- use the tr-archiver for the spec
CLDR-15104
Sample site: https://srl295.github.io/cldr/ (Just URLs under this location!)
Compare https://unicode-org.github.io/cldr/
> CLDR-15104 docs: use gh-pages branch and tr-archiver

- .github/workflows/maven-release.yml
CLDR-15195
This builds jar sources before attaching. 
I'm going to see if I can include javadoc also… if possible. If not I'll merge this as is.
> CLDR-15195 build jar sources when deploying to maven

- .github/workflows/maven-release.yml
- needed to build sources after the version number change
CLDR-15195
Markus, 
I've tried this myself with my own repo and it is actually attaching the sources properly. (partial extract below).
So if this looks good let's try once again.
```
8868  12-03-2021 17:20   org/unicode/cldr/util/ExtractCollationRules.java
2478  12-03-2021 17:20   org/unicode/cldr/util/RangeAbbreviator.java
4077  12-03-2021 17:20   org/unicode/cldr/util/Visitor.java
10829  12-03-2021 17:20   org/unicode/cldr/util/With.java
9247  12-03-2021 17:20   org/unicode/cldr/util/SpecialLocales.java
25293  12-03-2021 17:20   org/unicode/cldr/util/MatchValue.java
5134  12-03-2021 17:20   org/unicode/cldr/util/Differ.java
49492  12-03-2021 17:20   org/unicode/cldr/util/DateTimeFormats.java
23188  12-03-2021 17:20 …
```
> CLDR-15195 build jar sources on maven release

- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrMenu.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/src/main/webapp/surveytool.css
- on production, hide the sandbox locales
- on smoketest/dev, show sandbox locales in a separate section
CLDR-15222
-----
On smoketest it will look like the following, on production will be hidden:
> CLDR-15222 hide sandbox in production, identify

- tools/cldr-apps/js/src/esm/cldrEvent.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/webapp/surveytool.css
- refactor hover / locale message code for locale sidebar
- indicate locales that are not open due to limited submission
- for locales that the user *would* be able to edit if not due to limited submission,
maintain those locales as visible even if other locked locales would be hidden
- gray out top level (not just sublocale) that are 'locked'
(old bug)
CLDR-15224
> CLDR-15224 make it clearer that you are in a limited submission locale

- tools/cldr-apps/js/src/esm/cldrAjax.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrStatus.js
- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCLDR.java
-New boolean cldrTable.TABLE_USES_NEW_API to test calling api/voting instead of SurveyAjax.getRow
-Keep cldrTable.TABLE_USES_NEW_API false until new api works correctly
-Enable old-fashioned sendXhr request to use modern session header for api
-Encapsulate X-SurveyTool-Session, and adding session header, in cldrAjax.js
-Minor refactoring of cldrAjax.js, more subroutines
-Make ST_AJAX_DEBUG false; debugging should be off unless specifically needed
-Fix VoteAPIHelper to call getErrorOnPath as when required by front end
-Add convenience functions VoteAPIHelper.handleGetOneRow/handleGetOnePage
-Add convenience class VoteAPIHelper.ArgsForGet, shorten parameter lists
-Remove dead deprecated CheckCLDR.get/setHTMLMessage
-Fix deprecation warnings for SurveyLog.logException
-Formatting
-Comments …
> CLDR-14745 First steps for WHAT_GETROW to modern api

- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/js/src/views/ProgressMeters.vue
- tools/cldr-apps/js/test/TestCldrChecksum.js
-CAN_GET_LOCALE_PROGRESS = true in cldrProgress.js
-Ensure that Page, Voter, Locale meters are displayed as 1st, 2nd, 3rd respectively
-If Page meter is visible, make Voter meter visible even if no Dashboard data yet
-If Voter meter is visible but no data yet, display with special message and appearance
-TestCldrChecksum.js: warn without failure if time is excessive
-Format unrelated cldrLoad.js by running sh tools/cldr-apps/js/test/pretty.sh
CLDR-15056
> CLDR-15056 Coverage Progress Bars, enable Locale Progress meter

- common/main/nn.xml
- common/main/no.xml
- common/supplemental/grammaticalFeatures.xml
Note: this is done by removing the gender unit override. It also needs the minimalPair patterns for feminine. All 3 were changed to make more general and parallel.
CLDR-15235
> CLDR-15235 add feminine to nn

- tools/cldr-apps/js/src/esm/cldrMenu.js
CLDR-15222
On smoketest, [there "used" to be a 'Test Locales' subsection on the left sidebar](https://github.com/unicode-org/cldr/pull/1657#issuecomment-989345149). It had a bug where that subsection heading was always present, even if a specific locale was selected.
Now that each test locale says 'Test Locale', I don't think that subheading is needed. 
This one line fix changes the left sidebar (on smoketest!) to the following:
> CLDR-15222 mul: remove 'Test Locales' divider

- tools/cldr-apps/js/src/esm/cldrEvent.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/specialToComponentMap.js
- tools/cldr-apps/js/src/views/GeneralInfo.vue
CLDR-14703 fix 'empty space' above dashboard, modernize General Info
- modernize the 'General Info' area into Vue, remove hard coded javascript
- don't hide the OtherSection when the dashboard is shown and we were in
the General Info panel
- delete some dead code around the unused Possible Errors display - also see CLDR-15254
> CLDR-14703 modernize General Info

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java
- send in dpath (not fullpath) to check(), avoid spurious collision errors
- also add some more debugging values to the response payload
CLDR-15161
> CLDR-15161 3rd meter: correct error count

- .github/workflows/ansible-lint.yml
Fix the ansible-lint job which was failing due to two (2) issues:
ansible-lint issue:  https://github.com/ansible-community/ansible-lint/issues/1795
vagrant issue: pin macos per https://github.com/actions/virtual-environments/issues/4060
CLDR-15176
> CLDR-15176 ansible-lint: workaround for version problem

- tools/cldr-apps/js/src/esm/localesTxtGenerator.mjs
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VotingParticipation.java
Note this is on the generated Locales.txt viewable through the admin panel
- add 'coverageLocales' to each org with a list of orgs with cov
- add an `ERROR` note to the generated Locales.txt when vetters are assigned out of bounds
- add a note for orgs with a `*` coverage with out of bound vetters
CLDR-15277
> CLDR-15277 VettingParticipation2: err on out of bound locales

- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/StandardCodesTest.java
- allow 'mul' (sandbox) for orgs that have not set any other coverage yet.
- Such orgs will be prohibited from adding users to locales, at runtime.
- Cleanup nits in Locales.txt
CLDR-15182
> CLDR-15182 Remove warnings from Locales.txt

- common/main/am.xml
- common/main/be.xml
- common/main/be_TARASK.xml
- common/main/ky.xml
CLDR-15291
* am: "decade" was being translated as "10 years" which does not work well with a numeric unit; from Fesseha Atlaw get a translation that actually means "decade" (singular and plural forms), and also a suitable abbreviation to use for short (and narrow by inheritance).
* be,be_TARASK: abbreviate the short form of decade
* ky: "decade" was being translated as "10 years" in the long and short forms but as "decade" (unabbreviated) in the narrow form. Use that unabbreviated version from narrow for the long and short forms, and abbreviate it for narrow.
> CLDR-15291 am,ky: translate "decade" as such, not "10 years"; am,ky,be*: abbrev short or narrow decade

- common/main/eu.xml
- common/main/fo.xml
CLDR-15291
* eu, short form for decade was too long; fixed by copying narrow forms to short
* fo, short for permission was too long; fixed by further abbreviating "partur/mill." and "partar/mill." as "pt./mill.", since "pt." is an abbreviation I see in Faroese Wikipedia to mean "part" (in English context, but understood in Faroese).
> CLDR-15291 shorter short forms for decade (in eu), permillion (in fo)

- common/main/brx.xml
- common/main/jv.xml
- common/main/kab.xml
CLDR-15291
* brx: Add missing standard form for 3 zones by being the standard time suffix used in other complete zone sets with the same style for generic/daylight (e.g. America_Eastern)
* kab: short digital-byte was too wide, copy the forms from narrow
* jv: short permillion was too wide, copy the form from narrow
> CLDR-15291 jv,kab: copy a narrow unit to short; brx: add standard form for 3 zones

- common/main/cs.xml
- common/main/da.xml
- common/main/en.xml
- common/main/fr.xml
- common/main/pt.xml
- common/main/tr.xml
CLDR-10991
- [x ] This PR completes the ticket.
Fix display name for "crh" to be "Crimean Tatar" (not "Crimean Turkish") in English, and the equivalent in a few other languages (many CLDR languages already had "crh" as the equivalent of "Crimean Tatar"). Note that this display name is in comprehensive coverage so vetters do not normally see it.
> CLDR-10991 Fix name for "crh" (Crimean Tatar) in en and a few other languages

- common/main/en.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
…
CLDR-15307
Add English display names for languages:
* which have locales in seed but currently no display names in English
* whose names will be added for moden coverage in CLDR 42 (but useful to have the English names now)
> CLDR-15307 en: add names for seed languages and others whose names will have modern coverage

- common/main/kkj.xml
CLDR-11924
In the Kako (kj) main and index exemplars (respectively), replace the single composed chars 01CC, 01CB with the corresponding ASCII sequences {nj}, {Nj}
> CLDR-11924 kkj exemplars: replace 01CC,01CB with ASCII sequences

- tools/cldr-code/src/main/java/com/ibm/icu/dev/test/TestFmwk.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestSourceLocation.java
CLDR-15304
- supports rich GitHub annotations for console check errs
- improvements to XMLSource.SourceLocation to support GitHub
- added cross annotations with TestFmwk.SourceLocation (a similar but unrelated class)
> CLDR-15304 ConsoleCheck to use file:line:col

- common/supplemental-temp/coverageLevels2.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/draft/Keyboard.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CoverageLevel2.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLFileReader.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
CLDR-14289
common/supplemental-temp/coverageLevels2.xml
Best reviewed against the spreadsheet https://docs.google.com/spreadsheets/d/1Q1jVVY5RH2la7y26SW5SqptphJU-8AbZf7iIyJCItnM/edit#gid=0
tools/cldr-code/src/main/java/org/unicode/cldr/draft/Keyboard.java
Small change to get charts to work (for generating coverage charts).
tools/cldr-code/src/main/java/org/unicode/cldr/test/CoverageLevel2.java
Tooling changes to allow comparison of before and after coverage rule changes. Note: there is a TODO to move the main into a tool. That's for later.
tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java
Just allows for the extra directory for testing the before/after versions
tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
Some access changes so that …
> CLDR-14289 add tooling for comparing coverage, and change coverage

- common/main/sq.xml
CLDR-14488
Delete bogus narrow currency symbol in Albanian to fall back to standard € symbol (which is the narrow symbol in root).
> CLDR-14488 sq, remove bogus narrow symbol for EUR using the ISO code

- common/rbnf/ru.xml
CLDR-15266
These changes just mirror the set of rules for ordinals for spellout. The animate rules will be considered with CLDR 15267. Also the values are already available with other names.
> CLDR-15266 Add static rules to digits-ordinal for Russian

- common/supplemental/coverageLevels.xml
- common/supplemental/supplementalData.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-14289
common/supplemental/coverageLevels.xml
shift to new rules, already reviewed
common/supplemental/supplementalData.xml
fixed core checking errors: 
* no didn't show up as having country data
* The time cycle wasn't explicit for some locales. Added them explicitly.
tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
The bulk of the changes.  Add more information to the chart, helping to debug the data: notably the default locale, and an 'imputed' coverage level. Also remove some fields that are of lesser use.
tools/cldr-code/src/main/java/org/unicode/cldr/util/CoreCoverageInfo.java
This is where the non //ldml/ checks go. Expanded what we had, and assigned the different features to different levels. I left some of the names the same  (like the name of the …
> CLDR-14289 switch to new coverage rules

- common/supplemental/grammaticalFeatures.xml
Rationale for the first change: "use a number for which nominative and genitive forms are distinct":
to make the example clear, we need a plural falling in the "few" or "one" categories, since these have distinctions between "nominative" and "genitive". The plural rule for "few" looks as follows:
```
   few{
        "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 3"
        "2~34, 42~44, 52~54, 62, 102, 1002, …"
    }
```
33% seems like a more reasonable number than 2%, based on my lights for example - but 1% could also work.
The data for "percent" for "ru" shows no distinction between nominative and genitive for the "many" and "other" plural categories:
```
    genitive{
        few{"{0} процентов"}
        many{"{0} процентов"}
        one{"{0} процента"}
        …
```
> CLDR-14578 Fix and improve comments in grammaticalFeatures.xml

- common/supplemental/supplementalData.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt
CLDR-14552
Update territoryInfo for GB based on https://en.wikipedia.org/wiki/Languages_of_the_United_Kingdom, which is in turn based primarily on an analysis of latest data from the 2011 census (plus a few other sources).
This also fixes a leftover item from https://github.com/unicode-org/cldr/pull/1730, updating country_language_population_raw.txt for "no" in "NO".
> CLDR-14552 update territoryInfo for GB based on Wikipedia analysis of latest UK census data

- common/annotations/dsb.xml
- seed/main/hi_Latn.xml
CLDR-15276
These errs don't show up locally but do show up on the build system.
Perhaps a JDK or XML parser version difference.
```
Error:  (TestPaths.java:437)  Error: Inconsistency:	file=annotations/dsb.xml	elementType=PCDATA	value=«»	path=//ldml/annotations/annotation[@cp="👨‍⚕"][@type="tts"]
Error:  (TestPaths.java:468)  Error: Duplicate: hi_Latn.xml, //ldml/localeDisplayNames/scripts/script[@type="Moon"
```
> CLDR-15276 XML fixes to main/hi_Latn and annotations/dsb

- common/transforms/Ethiopic-Latin-BetaMetsehaf.xml
- common/transforms/Ethiopic-Latin-IES_JES_1964.xml
CLDR-15328
Two more fixes for Ethiopic transform names (not the BCP47 versions): The complete variant part needs to be a valid UnicodeIdentifier (no hyphens), and should be used consistently.
> CLDR-15328 two more fixes for Ethiopic transform names

- common/main/ks.xml
CLDR-15328
ks (Kashmiri) uses 'arabext' digits by default, but for arabext had the same value for &lt;decimal&gt; and &lt;group&gt;: "،" U+060C ARABIC COMMA. This caused parse failures in ICU4J number tests.
The other relevant locales such as pa_Arab, ur, fa (and root) have the following for 'arabext':
&lt;decimal&gt;: "٫" U+066B ARABIC DECIMAL SEPARATOR
&lt;group&gt;: "٬" U+066C ARABIC THOUSANDS SEPARATOR (which looks almost identical to U+060C ARABIC COMMA)
So switched ks/arabext to have the same &lt;decimal&gt; and &lt;group&gt; as those, and also added U+066B and U+066C to the ks number exemplars.
Note that ks has the following for 'latn' digits
&lt;decimal&gt;: "." U+002E FULL STOP
&lt;group&gt;:  "،" U+060C ARABIC COMMA
The &lt;group&gt; here may also be an error but is not causing …
> CLDR-15328 ks, fix number symbols for arabext (decimal & group were the same)

- tools/cldr-code/src/main/java/org/unicode/cldr/draft/FileUtilities.java
- fix for 0789429c9673740d784eab73cedd087acf21fbfa #1729 
- File() arguments were swapped
- this is breaking UnicodeTools
CLDR-15323
> CLDR-15323 Fix fileutilities for non-Windows

- common/supplemental/likelySubtags.xml
- common/supplemental/supplementalData.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/country_language_population_raw.txt
CLDR-15347
Add likelySubtags from sd_IN to sd_Deva_IN; Deva is the official script for Sindhi in India (Arab, Guru, Koj also used); in Pakistan it is Arab.
Update the territoryInfo for sd_Deva in IN.
> CLDR-15347 add likelySubtag sd_IN → sd_Deva_IN and supporting demographics

- common/main/ks.xml
CLDR-15341
Add to ks aux exemplars U+0626, which is used in the name for gregorian "May" (correctly spelled according to vetter) and in display the names of a language and region, though it is apparently not part of the normal ks orthography (may be used for words imported from other languages).
> CLDR-15341 ks, add \u0626 to aux exemplars (used in name of month "May" and elsewhere)

- common/main/ks_Deva.xml
CLDR-15355
In ks_Deva, add \u0902 to main exemplars (appears to be part of standard orthography per references - see ticket; used in names of some months & days and many other things).
> CLDR-15355 ks_Deva, add \u0902 to main exemplars (used in month & day names & elsewhere)

- common/dtd/ldmlICU.dtd
- tools/cldr-code/src/main/java/org/unicode/cldr/api/CldrPaths.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
CLDR-15328
Add the @ORDERED metadata item for the icu:extension element to generate a distinguished path, and remove obsolete restrictions on using @ORDERED with icu:-namespace elements.
> CLDR-15328 add @ORDERED for icu:extension, remove restrictions on using @ORDERED for icu: elements

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDerivedAnnotations.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Annotations.java
- improve error output of GenerateDerivedAnnotations
- allow pattern category-list to inherit from root
- minor improvement to tool
- Regenerate Derived Annotations
(cherry picked from commit b3999016827d728daf41c6eb74382b50f94ad9e1)
CLDR-15285
> CLDR-15285 Derived annotations [maint-40] (#1708)

- tools/cldr-code/src/main/java/org/unicode/cldr/draft/FileUtilities.java
dir is an object and not a string
CLDR-15323
> CLDR-15323 fix FileUtilities.openWriter NPE

- common/main/hy.xml
- common/main/mai.xml
- common/main/pa.xml
- common/main/th.xml
- common/main/tr.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/FlexibleDateFromCLDR.java
CLDR-13606
If a skeleton for availableFormats or intervalFormats includes G, then the corresponding pattern (for calendars other than chinese/dangi) must include G (for chinese/dangi, it should preferably include r, or at least U). Add the test for this, then fix a few patterns that then failed the test - look at similar patterns or generic patterns for guidance.
Note that the ordering of patterns in some locales (like hy Armenian) is pretty inconsistent. That is another problem, probably to fix using Survey Tool.
> CLDR-13606 G in skeleton => pattern should have G (or r,U); test, fix patterns

- common/main/en_AU.xml
- common/main/fi.xml
- common/main/it.xml
- common/main/ps.xml
- common/main/sv.xml
- common/main/to.xml
CLDR-15383
This fixes a problem where tests on the production data (in which ↑↑↑ is removed) produced errors like:
```
/Volumes/pmData/Sources/cldr-staging/production/common/main/it.xml:6110:38: error
it [Italian]	error	▸Currencies|Northern/Western_Europe|Northern_Europe:_Norway|NOK-symbol-narrow◂	〈kr〉	【】	〈NKr〉	«=»	【】	⁅missing non alt path⁆	❮Error: A path with alt is present but the corresponding path without alt is missing; a solution might be to confirm the non-alt path❯	https://st.unicode.org/cldr-apps/v#/it//7b917bf155f6cc00
/Volumes/pmData/Sources/cldr-staging/production/common/main/it.xml:5510:37: error
it [Italian]	error	▸Currencies|Southern/Eastern_Europe|Eastern_Europe:_Belarus|BYN-symbol-narrow◂	〈BYN〉	【】	〈Br〉	«=»	【】	⁅missing non alt path⁆	❮Error: A path with alt is present but …
```
> CLDR-15383 if have narrow currency symbol but non-narrow ↑↑↑ inherit no value, provide value

- common/supplemental/likelySubtags.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LikelySubtagsTest.java
- update test to be clearer (related to CLDR-15391)
- add 'less disruptive' likely subtag changes
CLDR-15366
> CLDR-15366 BRS v41: likelySubtags update #0

- common/rbnf/ar.xml
CLDR-15261
This ticket provided additional feedback that the changes were incomplete. I have confirmed that 138000 comes out as the following as per the feedback:
مائة وثمانية وثلاثون ألف وأربعة مائة
Also 1111111111111 comes out as the following:
ترليون ومائة وإحدى عشر مليار ومائة وإحدى عشر مليون ومائة وإحدى عشر ألف ومائة وإحدى عشر
The fix was performed by searching and replacing all instances of the "and" (و) surrounded by spaces. FYI و means "and" in Arabic. Since testing the result requires ICU and there isn't an easy way to convert this XML to ICU syntax, there isn't an easy way to add a test for this value. This is a resubmission of https://github.com/unicode-org/cldr/pull/1782 to the maint-41 branch.
> CLDR-15261 Arabic spellout rules render a stray space after the conjunction

- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
CLDR-15394
This is a follow-on to [PR-552](https://github.com/unicode-org/cldr/pull/552), which updated the test CheckNew.handleCheck to make sure that root-style emoji annotations like "E10-836" were not finding their way into non-root data (either explicitly or by inheritance), and added a new test TestCheckCLDR.TestCheckNewRootFailure to verify that the updated CheckNew.handleCheck was working correctly. However, the latter test tried to verify that an error was generated for both "E10-836" and "↑↑↑"; the latter test is not valid, and caused problems in production code, so it is removed here.
For entries like "↑↑↑", the value is obtained by following the parent chain until an explicit value if found (which may be in root, in which case for regular CLDR data it will be an entry like …
> CLDR-15394 remove invalid test in TestCheckNewRootFailure

- common/dtd/ldml.dtd
- common/main/en.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRFile.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCldrFactory.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-15405
DTD enhancements corresponding to the structure proposed in [CLDRPerson Name Formatting](https://docs.google.com/document/d/1uvv6gdkuFwtbNV26Pk7ddfZult4unYwR6DnnKYbujUo/edit#heading=h.spx0ljsttgli). In order to test the DTD I also had to roll in the English structure proposed there as well.
DTD notes:
- For namePattern element:
- Since there can be more than one without distinguishing attributes, I added @ORDERED.
- TestBasic.TestDtdCompatibility specifies that "ldml DTD elements with PCDATA must have 'alt' attributes", so I added the possibility for an alt=variant attribute. We need to consider this more.
- For all leaf elements, added draft & references attributes (usual practice), which are @METADATA
- All attributes are distinguishing except for the @METADATA ones and for …
> CLDR-15405 first cut personNames dtd & en data, plus tooling updates/skips

- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRURLS.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-15405
Fill out coverage, PathHeader, and PathDescription for Person Name Formats data (but not yet AttributeValueValidity). I did not find any place in PathHeader where I needed to do something special for the nameFormat placeholders.
Note that as part of this I created a stub translation guidelines page for Person Name Formats, since PathDescription needed to refer to it: https://cldr.unicode.org/translation/miscellaneous-person-name-formats
> CLDR-15405 PersonNames coverage, PathHeader, PathDescription

- .github/COMMIT_METADATA.md
- .github/workflows/commit-checker.yml
CLDR-15021
- add a .github/COMMIT_METADATA.md
- Update commit checker workflow
- ~Also temporarily use the srl295 branch of the commit checker~ no, you will have to manually put this in.
- Fixes the hardcoded and increasingly-inaccurate `v38` in the report URL!
> CLDR-15021 v41 Add COMMIT_METADATA.md with commits to skip

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-15405
Changes from what we discussed in meeting:
- We had said the monogram lengths should ignore attributes except for order. But we need style too, as shown in the English examples in our own spec.
- We had said the data paths would include all attribute combinations, and where we were ignoring one (like usage for monogram lengths, or order for sorting), we would alias one to the other and use coverage to exclude the non-used one. But that does not make much sense; better to just have the fleshed-out paths in xml data not include the ignored attribute value, then no aliasing necessary.
- I had to add the English data for order=surnameFirst, that was not in the spec.
- I have not yet added the patterns for initial and initial sequence.
dtd changes (affects other items like data, …
> CLDR-15405 Fully enumerated paths in root (with aliases) and en; namePattern no longer @ORDERED

- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35.md
CLDR-15131
Fix some spec links into the CLDR Sites pages. In one case - for https://cldr.unicode.org/index/cldr-spec/transliteration-guidelines - I instead had to restore the old URL of the Sires pages, from "unicode-transliteration-guidelines" back to just "transliteration-guidelines".
Also update some links that went to the maint-40 branch or downloads/cldr-40 page to go to the 41 version.
> CLDR-15131 spec fix links into cldr.unicode.org and repo maint branch

- common/bcp47/currency.xml
- common/main/en.xml
- common/supplemental/supplementalData.xml
- common/validity/currency.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/ICUServiceBuilder.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/ISO4217.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-15456
- There’s an undetermined transition period. SLE is an internal code until that transition period is announced.
- For now SLE is 'new leone' but it will eventually just be 'leone' when SLE is in circulation.
- Updated ISO4217 and currency validity. SLE is not available in the 4217 lists yet.
- Also update tests that would otherwise fail on NPEs found during development
https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl_currency_iso_amendment_171.pdf
> CLDR-15456 Currency: SLL»SLE

- common/supplemental/supplementalData.xml
- SLL on the ground does not use subunits per @roozbehp 
- partial revert of c2c9723e653b703e92fc008eb6467f2be00d6643 (#1825)
CLDR-15456
see https://github.com/unicode-org/cldr/pull/1825#issuecomment-1075834540
> CLDR-15456 Currency: SLL should have 0 digits

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/SimpleNameObject.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
- It adds fallback behavior for modifiers, including the first grapheme for -initial, and uppercasing for -allCaps. That also involved newly passing around the locale and a BreakIterator
- There is a default order if none specified by the name object, to prevent inadvertent matches.
- There is a working bestValue for field values implementation in the SimpleNameObject to figure out the best match for field+modifier combinations.
- It uses longest match first
- Among the longest matches (if more than one), favors modifiers according to the following order (see the Modifier enum)
- informal, allCaps, initial, prefix, core
- We need to decide on the right order and add to the spec.
- This meant changing the internal data structure so that we could go right from the field to the …
> CLDR-15404 add fallbacks

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- reinstate 'memfree' and 'memtotal'
These were removed in #893 but are read by Prometheus.
CLDR-15369
> CLDR-15369 re-instate memfree/memtotal

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Placeholders.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-15405
Finish up the remaining changes to dtd, coverage, PathHeader etc. modulo discussion about changing some of the added items, and add new data items for root/English:
- Add initialPattern element with type=initial|initialSequence, and data for root/English. Since this is PCDATA, it is also required to have an alt attribute, so it allows alt=variant.
- Add sampleName element with item=minimal|simple|full|multiword, and child element nameField with type=prefix|given|given2|surname|surname2|suffix, and initial data for English. Since nameField is PCDATA, it also allows alt=variant. **Note: we need to discuss (in meeting): (1) whether "item" is the best name for the sampleName attribute; (2) what additional values might be needed besides minimal|simple|full|multiword; and (3) whether …
> CLDR-15405 Add initialPatterns, sampleNames & data; PathHeader functions for ordering

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserSettingsData.java
- a 'commit' was missing before an operation which depended on a settled state of the DB
- minor, only occurs during derby db setup (i.e. unit tests)
- could be the cause of intermittent test hang or failure
(cherry picked from commit 709d0bbe5e855f7e942009f3581a867601a0cfc7)
CLDR-15488
> CLDR-15488 db: improve issue with hang on derby table create

- tools/cldr-code/pom.xml
- tools/cldr-rdf/pom.xml
- tools/pom.xml
CLDR-14311
xerces provides org.xml.sax, which causes eclipse to complain that it is already available (as part of JDK11+).
> CLDR-14311 remove xerces to avoid conflict in eclipse

- tools/cldr-code/src/main/java/org/unicode/cldr/util/SimpleXMLSource.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
- intern the xpath string (cost only on read)
- instead of substringing the system name (which starts with file://…) at construction
time, substring it later only when (if) the user uses it
CLDR-14543
> CLDR-14543 reduce memory use of the getSourceLocation() calls

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
- Handle multiword initials (John Bob ==> J. B.)
- For monograms, only get first grapheme, and *don't* use the initial format (no dot)
> CLDR-15404 fix monogram, multiword initials

- readme.html
- tools/pom.xml
CLDR-15461
The last update ot ICU4J libs in CLDR 41, picking up ICU maint/maint-71 branch as of 2022-03-31 including CLDR beta2 integration and Yoshito's addition for SLE.
Also updated readme to say final release.
> CLDR-15461 for final: update ICU4J libs to maint-71 as of 2022-03-31, update readme

- docs/ldml/tr35-collation.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35.md
Not all sections of the spec link to data files,
only those specs which do were updated.
CLDR-14332
> CLDR-14332 spec: add a warning about out-of-date doc links

- docs/ldml/tr35-collation.md
- docs/ldml/tr35-dates.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35-numbers.md
- docs/ldml/tr35.md
- tools/scripts/tr-archive/archive.js
- Update all anchors starting with section numbers (1.2.3.4) so the number
is outside of the anchor.
- CLDR-14611: Update all h6 (######) to have the text 'Table: '
outside of the anchor.
- Update archiver to move h6-followed-by-table into a <caption>
inside the table, iff the h6 starts with 'Table:'
- demoted a few non-caption h6
- Regenerate ToC
CLDR-15206
> CLDR-15206 spec: section numbers outside of anchors, table caption

- .github/workflows/ansible-lint.yml
- .github/workflows/gh-pages.yml
- .github/workflows/js.yml
- .github/workflows/maven.yml
- run ansible/vagrant only if ansible changes
- run js test only if js changes
- move yaml lint of the workflows into maven
CLDR-15460
Includes fix from: CLDR-15467 update maven.yml to improve builds (#1824) 2ea074bfc0716359c24e47b757b6027bc78eb69f
> CLDR-15460 build: restructure workflows

- tools/cldr-apps/js/src/views/AboutPanel.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/QueueMemberId.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/About.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/MemoryHelper.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-Schedule auto snapshots if cldr.properties has CLDR_AUTO_SNAP=true
-Summary.java has new methods scheduleAutomaticSnapshots, etc.
-For testing only, first snapshot is scheduled two minutes after startup
-Cancel scheduled snapshot when Survey Tool shuts down
-New class QueueMemberId to solve the problem of snapshot without CookieSession
-Refactor getPriorityItemsSummaryOutput to avoid long parameter list, new classes Args/Results
-Revise About panel memory reporting, separate lines for total/max/free
-New module MemoryHelper with method availableMemory called by VettingViewer only if DEBUG
CLDR-15369
> CLDR-15369 Priority Items Summary, schedule automatic snapshots

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
Various items to unblock other work:
1. Change nameOrder to nameOrderLocales, make order attribute distinguishing, move locale list from attribute to value. Use root/en data suggested by Mark.
2. Move sorting from usage to order. Rearrange root/en data to match.
3. For sampleName, expanded & renamed items types, included givenInformal. Added root data with all nameFields for each item; adjusted the en data with ∅∅∅ for unused fields (add PathDescriotion note for that). The en sampleName data needs better values, current ones are just to have something for testing 
4. Misc en updates. remove . in mononym patterns since it is in initialPattern; use -initial-allCaps for all mononym patterns. 
5. Use PathHeader ordering functions for personName/sampleName section heads too.
Still …
> CLDR-15405 nameOrder→nameOrderLocales, mv sorting from usage→order, sampleNames in root / ∅∅∅ in en

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
-Ensure dbUtils is initialized before calling doStartupDB
-Exit doStartup early if dbUtils is null (this can happen with liberty:dev)
-Wait until the end of doStartupDB to call Summary.scheduleAutomaticSnapshots
-Rename startUpDatabase to getDbInstance, reducing confusion with doStartupDB
-Throw exception from getDbInstance instead of boolean return, for consistency/brevity
-Revise logger.info in validateDatasourceExists to use actual method name
-Comments
CLDR-15472
> CLDR-15472 dbUtils is null in SurveyMain.doStartupDB

- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35.md
CLDR-15290
I checked and fixed all of the external (http / https) links in markdown, using `npx markdown-link-check *.md` 
-----
I couldn't figure out what to do with the following in `tr35-general.md`:
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#AbessiveCase → Status: 404
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#AdessiveCase → Status: 404
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#AllativeCase → Status: 404
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#DelativeCase → Status: 404
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#ElativeCase → Status: 404
-   [✖] http://acoli.cs.uni-frankfurt.de/resources/olia/olia.owl#EssiveCase → Status: 404
-   [✖] …
> CLDR-15290 BRS v41: fix broken links in spec

- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCldrFactory.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
- Remove the fallback "any" personName entry in root & en. Instead, in root provide explicit patterns for the 3 different orders (with length="long" usage="referring" style="formal" ) and have other personName entries fall back to the appropriate one of those.
- As a result, remove ParameterMatcher.MATCH_ALL and adjust code accordingly. Update tests that passed an empty string of attribute values to now pass one or more fallback strings with order attribute set.
- Add PathHeader function personNameSection and use it in PathHeader.txt
- Remove the logKnownIssue skip around a test in TestCldrFactory.testWrite, the original test now works fine.
-  Other minor fixes
> CLDR-15405 replace "any" entry with 3 root fallbacks by order; add/use &personNameSection

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/MatchValue.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
- Add checks for nameOrderLocales and sampleName
- Make LocaleMatchValue public, for ease of checking validity of locales
- Add information to exceptions thrown by NamePattern.parse
- Fix the TestPersonNameFormatter to account for the more detailed messages
> CLDR-15404 Enhance error checking

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
1. Add mononym example to sampleNames (for English I used Sinbad, Popeye has IP encumbrance in the US)
2. For the sampleName dummy name fields in root, used more code-like values
3. For the ST PathHeader section ordering and item ordering:
- Moved the SampleName sections before the PersonName sections
- Fixed the item ordering within those sections
- For the SampleName sections, drop the item type as part of the key in the left column
> CLDR-15405 add mononym sample, more code-like root dummy names, fix ST section & path ordering

- docs/ldml/tr35-collation.md
- docs/ldml/tr35.md
- change `:point_right:` to 👉
thanks @ivan-pan for catching this. 
I thought that GFM character references were expanded but …  guess not. 
I did a simple search and didn't find anything that looked similarly suspicious.
CLDR-15484
> CLDR-15484 spec: change :point_right: to character

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
This adds some code for debugging on smoketest, since I'm unable to reproduce the problems I see there. That code will be retracted once the problem is solved.
It also adds a fix to the example generator for displaying the name order locales, and a null-check for string values (that should never occur).
> CLDR-15404 instrument for debugging

- .github/workflows/gh-pages.yml
With a recent change (below), we need to do an extra step in the gh-pages build.
make-tr-archive.sh does not fetch remote resources (css/gif) by default.
Run 'npm build' to fix.
Regression was in CLDR-15088 / #1881 / db15bae6b0ba6be54b50072c220e77a2dc14047f
CLDR-15464
-----
Review note: https://srl295.github.io/cldr/ldml/tr35.html was built using this commit.
> CLDR-15464 spec: fix gh-pages

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleCache.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
There were problems where a change in a sample name wasn't reflected in the examples for patterns. That doesn't work for two reasons:
1. The examples are cached per path, so wouldn't get automatically refreshed. 
2. For *generating* those examples, two objects are used that relatively expensive to create, and were being cached across invocations.  
For the first problem, I added paths to ExampleDependencies. There is a call that uses that in ExampleGenerator to clear examples that are dependent on given paths.
For the second problem, there was no built-in mechanism for that. You could clear examples, but not arbitrary other constructs. So I extended the cache mechanism a bit so that I could clear out other items when a path changed.
The synchronization is a bit heavy handed, …
> CLDR-15404 fix the internal caching in example generator, part 1

- tools/cldr-apps/js/src/esm/cldrDash.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
- tools/cldr-apps/js/src/views/DashboardWidget.vue
- tools/cldr-apps/js/test/Test.html
- tools/cldr-apps/js/test/TestCldrDash.js
- tools/cldr-apps/js/test/data/dash_data.js
- tools/cldr-apps/js/test/index.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DBUtils.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/HiddenNotifications.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/PathValuePair.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReviewHide.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SubtypeToURLMap.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyJSONWrapper.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- tools/cldr-apps/src/main/webapp/tc-all-errors.jsp
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java
-Revise DASH_HIDE db table: unversioned; new column val (blob)
-DASH_HIDE subtype column, CheckCLDR.CheckStatus.Subtype instead of VettingViewer.Choice
-Include value and subtype in http requests and responses
-Consistently spell subtype with lowercase t in all files
-New small class PathValuePair.java
-New HiddenNotifications.java to encapsulate complex HashMap
-New subclasses of VettingViewer etc to encapsulate arguments and results
-Refactor single-path dashboard to use the same code as multi-path dashboard
-Refactor ReviewHide using HiddenNotifications and move inline SQL to constants
-Rename some items for consistency to reduce confusion
-Distinguish ReviewNotificationGroup groups from ReviewEntry entries
-Shorten methods by moving code into new subroutines
-New unit tests for …
> CLDR-14906 Retain Dashboard hidden status across releases

- tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
- World Organization for the Development of N’ko (WODN)
CLDR-15449
> CLDR-15449 add wod_nko for the nqo langauge

- tools/cldr-rdf/src/main/java/org/unicode/cldr/rdf/LanguageMapper.java
- tools/cldr-rdf/src/test/java/org/unicode/cldr/rdf/TestMapAll.java
- was not catching an error on https://dbpedia.org/page/Grebo_language so some entries were missing
- Filter was incorrect, so skipped some entries
- Added unit tests for 'ace' (Acehnese)
- Cleaned up test code, fixed use of deprecated API
CLDR-15292
> CLDR-15292 rdf: fix LanguageMapper

- tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
- if possible, read directly from .git/HEAD and related files
- due to a recent git update, 'git rev-parse HEAD' may refuse to operate,
details at https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory
- if we do use git rev-parse HEAD, be clearer when there is an error
CLDR-15561
> CLDR-15561 read git hash directly for data

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ToolConstants.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
CLDR-15567 fixes for DTD and chart generation
- ToolConstants: add 1.1, 1.4, 1.5.0.1, 41 versions
( [1.1](https://github.com/unicode-org/cldr/releases/tag/release-1-1) is newly remanufactured)
- DtdData: map 1.1.1, 1.4.1, 1.5.1 to prior DTDs (those versions did
not have a shipped DTD.)
> CLDR-15567 fixes for old DTDs

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/test/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
- move monograms from length to usage attribute
- reorder the values for the order attribute to be givenFirst, surnameFirst, sorting
- sampleNames:
- change items to be just givenOnly, givenSurnameOnly, given12Surname, full
- update the English values to be all fictional characters (e.g. from Sherlock Holmes, no IP issues) or made-up names
- remove the fields from root that are not supposed to be supplied for a given sampleName
- add a little more path description
- for SurveyTool, group personName entries by both length and usage
Note: There may be a problem with initials, a couple of the results in TestPersonNameFormatter looked odd (flagged with TODO and noted below). Rather than fully investigating and debugging these (if they are indeed errors), I thought it best to get …
> CLDR-15405 move monogram from length→usage, reduce/rename sampleName items, rearrange order

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
CLDR-15571
- Return a FE err instead of a 500 which caused a loop, in SurveyAjax
- no reason all exceptions weren't caught here
> CLDR-15571 SurveyAjax: return error instead of 500

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyLog.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMain.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyMetrics.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
- tools/cldr-apps/src/main/liberty/config/server.xml
CLDR-15572
add the `/metrics` endpoint to the server for prometheus monitoring
> CLDR-15572 liberty: enable monitoring and metrics

- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
1. Restore the special handling for monograms (now simpler to test for).
2. Fix the tests, but also replace the numbers as suggested in a review of the translators guide.
> CLDR-15404 fix for monogram after swapping to usage

- common/supplemental/supplementalData.xml
CLDR-14956
Haitian Creole language `ht` should fallback to French `fr-HT`
> CLDR-14956 ht should fallback to French fr_HT

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
- tools/cldr-apps/js/src/esm/cldrVote.js
-After user votes, when no more votes are pending responses, schedule update in 3 seconds
-New function cldrSurvey.expediteStatusUpdate
-New fastTimerSpeed = 3000 ms = 3 seconds
-Fix bug in updateDashboardRow, updateRow was renamed to updatePath
CLDR-15538
> CLDR-15538 Expedite page refresh after user votes

- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15404
3 fixes:
- change to print out order for spreadsheet
- fix comments for Rich
- add -monogram support
- Note that one of the tests has a commented out section, until monograms are fixed in the data.
> CLDR-15404 fix monograms3

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- common/supplemental/supplementalData.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleDependencies.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/json/LdmlConvertRulesTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/test/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
1. Rename personName attribute "style" to "formality"; rename PersonNameFormatter.Style to PersonNameFormatter.Formality
2. Rearrange personName attributes so "order" moves from last (and least significant) to first (and most significant), yielding: order, length, usage, formality
3. Reorder data, SurveyTool display, function parameters, and code chunks to match new personName attribute ordering and naming, for consistency.
4. Add "vi" and "yue" to surnameFirst locales in root and supplementalData.
5. Since #1950 has been merged into main and that updated main merged into this, this also now changes root & English monogram patterns to use -monogram instead of -initial.
There were 3  test failures with  the original version of this that were worked around; those were fixed by …
> CLDR-15405 style→formality, make personName order attribute first & most significant

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java
-Add Modhi to the exception list
-Move that code into a subroutine and cache the constant result
CLDR-13335
> CLDR-13335 Errors in Survey Tool, names same as codes, Modhi

- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestStandardCodes.java
CLDR-15411
Add high coverage locales to Locales.txt so that they show up in the priority view.
I will file a separate ticket about updating the docs.
> CLDR-15411 Add high coverage locales to Locales.txt

- common/main/en.xml
CLDR-15564
In English, add narrow versions of certain fields (year, quarter, month, week, day, hour, minute, second) with displayName and relativeTime, mostly based on narrow duration units (except e.g. for quarter, which is not yet in duration units).
> CLDR-15564 en, add narrow fields: displayName & relativeTime based on narrow duration units

- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
CLDR-15598 Update Google coverage in Locales.txt
Updated from moderate to modern: ha, ig, nn, yo in Google and Cldr items
Commented OC out for Google
Removed basic level versions of ha, ig, yo
> CLDR-15598 Update Google coverage in Locales.txt

- common/supplemental/ordinals.xml
CLDR-13972
Plural rules ordinal for Asturian. Added `ast` to same category as es & pt per ticket
> CLDR-13972 Plural rules ordinal for Asturian

- common/main/en.xml
- common/supplemental/attributeValueValidity.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-apps/src/test/java/org/unicode/cldr/web/api/TestLocaleCompletion.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
CLDR-15585
Expand modern coverage for names of languages, scripts, key types per
https://docs.google.com/document/d/1XRDw07aD62FTMM0s1cfOYpNmKoCBIGabuEpT1S4AjrE/edit#heading=h.awus4p4ii9g8
Cleaned up the codes in attibuteValueValidity.xml $language, $languageExceptions, and $oldLanguages:
- $language has everything that is in common/main and in modern coverage, plus 4 grandfathered values that are in neither.
- $languageExceptions has everything else for which we request name translations in modern coverage (there are locales in seed/main for some of these); most of these were moved from $oldLanguages
- $oldLanguages is left with a few entries that were previously there; none of these are in modern coverage.
Notes:
- This still uses the compact-form approach for language codes in coverage …
> CLDR-15585 Expand modern coverage for names of languages, scripts, key types

- common/supplemental/plurals.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PluralRulesUtil.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
CLDR-15599
Update plural many category for Catalan. Catalan should have the same behavior as the other romance languages.
> CLDR-15599 Update plural many category for Catalan

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java
- tools/cldr-apps/src/test/resources/org/unicode/cldr/web/TestUserLevel.csv
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
CLDR-14766
👉  **Note** because of the way phases work, canSubmit returns false not only in the SurveyTool `READONLY` phase, but also `VETTING_CLOSED`.  This is because CheckCLDR.Phase only has `FINAL_TESTING` and does not have a readonly option. But voting during `VETTING_CLOSED` should not have been allowed before, either, and probably stopped by other code.
> CLDR-14766 move permissions policy from UserRegistry to VoteResolver.Level

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/ja.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathDescription.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15405
Per e-mail discussion, add foreignSpaceReplacement element with regular space for root value, and ・ \u30BF for Japanese, along with coverage and PathHeader stuff, etc. Having a value of space required some exceptions in tests for DAIP and exemplars.
> CLDR-15405 Add foreignSpaceReplacement with \u0020 for root and ・ for ja

- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCoverageLevel.java
CLDR-14992
Per the ticket and TC discussion, the locales returned by SupplementalDataInfo getTargetScripts and getTargetTerritories for a given target language should include not just the primary script and region from languageData, but also the explicit scripts and regions from the locale IDs for all (common/main) CLDR locales for that language (except for regions that are 3-digit UN M.49 codes, which we decided in TC to exclude). See the scripts/regions that will be added in [Additions to Target-Scripts, Target-Regions](https://docs.google.com/document/d/1TqsXBswiOSCgHckeAJ--day9WR08EXSNBuJUeJz48Dk/)
This will help do things like ensure that there is Persian calendar coverage in ckb_IR, for example.
> CLDR-14992 SDI.getTargetTerritories/Scripts should include the ones for actual CLDR locales

- common/dtd/ldmlSupplemental.dtd
- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LocalesTxtReader.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestLocalesTxtReader.java
- tools/cldr-code/src/test/resources/org/unicode/cldr/util/TestLocales.txt
CLDR-15468 Locales.txt: steps to support for focussed orgs
- new pathMatch element in coverageLevels.xml
- document Locales.txt format
- Split Locales.txt to a separate reader class
- parse @-commands
- tests for Locales.txt reader
Co-authored-by: Peter Edberg <42151464+pedberg-icu@users.noreply.github.com>
Note that this does NOT add IAAP, nor make any changes to Locales.txt content.
It also does not parse pathMatch.
> CLDR-15468 Locales.txt - steps towards support for focussed orgs

- common/dtd/ldml.dtd
- common/main/en.xml
- common/main/root.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
CLDR-15632
Add surname-prefix and surname-core options for personNames/sampleName
* Updates allowed nameField values
* Adds surname-prefix and surname-core test values to root.xml and en.xml
This PR blocks PR #1970 , add nl and nl_BE personNames
> CLDR-15632 prefix & core modifiers for sampleName

- common/main/nl.xml
- common/main/nl_BE.xml
CLDR-15588
Add nl and nl_BE personName patterns and sample names.
Note that nl uses surname-prefix and surname-core to handle tussenvoegsels, but -prefix and -core are not used in Belgium
Double-Barreled names are not handled.  See: https://onzetaal.nl/taaladvies/geachte-mevrouw-jansen-de-jong-jansen
In double-barreled surnames, e.g. maiden plus married, defacto usage it to only use the first surname in `usage="addressing"`
"mevrouw Jansen-de Jong" -> "Dear mevrouw Jansen" (mevrouw = "Ms.")
Test data are in the "nl" and "nl-BE" tabs of the [PersonName Test Data Google Sheet ](https://docs.google.com/spreadsheets/d/1YwWVSgaMNx13O0yf3f86MQjpMqy8VS1gfqGrT38fQ8g/edit?usp=sharing)
> CLDR-15588 add nl and nl_BE PersonNames

- common/main/en.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPathHeader.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPseudolocalization.java
CLDR-14032
Enhanced DAIP to make the space adjustments per the ticket and associated [proposal](https://docs.google.com/document/d/1MuHnd5hvrwI1TqgxW_js4lgzh7nQRySjNHOsFJCF2qY/edit#heading=h.xcfpr8iehq4e) as discussed in TC:
- In Latin-script locales intervalFormats, spaces around \u2013 become thin space \u2009
- In time formats, space between time and AM/PM marker becomes NNBSP \u202F
- In Cyrillic-script locales date formats with year, space between y and year marker becomes NNBSP \u202F
- In narrow units, space(s) on either side of {0} become NNBSP \u202F
- In short units,  space(s) on either side of {0} become NBSP \u00A0
Added a unit test for these changes.
Then ran CLDRModify -fp on en.xml to show the result of these changes (that also reordered some data items not related to the …
> CLDR-14032 More space adjustments in DAIP; add test. Run it on en.xml, adjust tests

- tools/cldr-apps/js/src/esm/cldrForum.js
-Hide (effectively disable) Agree and Decline buttons, pending better implementation
-New SHOW_AGREE_AND_DECLINE, false to hide
CLDR-14922
> CLDR-14922 Hide Agree/Decline buttons in forum

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/FindFlipFlops.java
-New FindFlipFlops.java, partly based on GenerateBirth.java
-Find all paths in all locales where value changed from A to B then back to A
-Output tab-separated data including a row for each significant change
-Treat differences in whitespace as insignificant
-Replace INHERITANCE_MARKER with inherited value
-Default starting release is 21.0
CLDR-15017
> CLDR-15017 Check for back-and-forth flip-flop values

- common/supplemental/coverageLevels.xml
- common/supplemental/supplementalData.xml
CLDR-7813
Add Islamic calendar to supplemental calendarPreferenceData and to coverage (if not already there) for more regions, but after Gregorian in preference.
In calendarPreferenceData the following prefer
- astronomical islamic: BD ID MY NE PK
- civil islamic: AL AZ MV TJ TM TR UZ XK
> CLDR-7813 Add islamic to calendarPreferenceData & coverage for more regions

- common/main/en.xml
- tools/cldr-apps/src/test/java/org/unicode/cldr/util/SandboxLocalesTest.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
CLDR-15630
Fix DtdAttribute attribute ordering for personName attributes. Also some other cleanup:
- Fix DtdAttribute attribute ordering for dateTimeFormat type attribute
- In SandboxLocalesTest.java call to Factory.make, delete third parameter to use default minimalDraftStatus (unconfirmed).
Regenerate en.xml with updated attribute ordering.
> CLDR-15630 Fix DTD attribute ordering for personName, other cleanups

- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-Missing (VettingViewer.Choice.missingCoverage) should not have been omitted from org-neutral summaries
CLDR-15646
> CLDR-15646 Priority Items: include Missing in org-neutral summaries

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GeneratePluralList.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPluralRuleGeneration.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestSupplementalDataInfo.java
- add a convenience function SupplementalDataInfo.getPluralRules()
- fix call sites to use this function instead of ICU4J's PluralRules.forLocale()
CLDR-15651
blocks #1709
Note, I did not change PluralRulesFactory call sites. It seems to explicitly use ICU4J plurals, need more feedback.
> CLDR-15651 fixup incorrect calls into ICU4J PluralRules

- common/main/en.xml
- common/main/root.xml
- common/supplemental/coverageLevels.xml
- common/supplemental/supplementalData.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
CLDR-15652
Some fixes and cleanups from the process of integrating CLDR 42 m1 to ICU:
- In DtdData, tha attribute comparator for "usage" is only intended for element personName (to avoid conflict with usage attribute in units.xml)
- Remove draft="provisional" in root and en. For en this was to avoid conflict between patterns for degrees of angle and degrees of generic temperature; solved the problem by adding "temperature" to the patterns for long generic temperature (and added a display name too).
- In GenerateProductionData added a more complete warning about subdivision files not written.
- Fixed some spacing (spaces->tabs) in coverageLevels.xml and supplementalData.xml for consistency.
> CLDR-15652 integration fixes: fix DtdData, no provisional in root/en

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/Summary.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/web/api/TestLocaleCompletion.java
- update Summary (dashboard) for metric names
- add metrics to LocaleCompletion
- add a Cache to LocaleCompletion, that gets invalidated if any votes change
CLDR-15653
> CLDR-15653 LocaleCompletion: cache, concurrency, metrics

- common/main/de.xml
- common/main/en.xml
- common/main/en_001.xml
CLDR-15652
Integration fix for problems with Japanese calendar formatting found during CLDR-ICU integration. This undoes part of the changes in #1975 (CLDR-15510 `en`,`de`: change era in numeric dates from GGGGG to G) which went too far.
The changes there were correct for Gregorian, for which `en` has a little-used narrow form, and for which `de` has the same form in all widths. They were wrong for Japanese calendar; the eras for that are inherited from root for both `en` and `de`, and the narrow form there is distinct and commonly used in numeric-only date formats. In both `en` and `de`, The Japanese calendar inherits some formats from generic (as do other non-gregorian calendars). But for the other non-Gregorian calendars, there are not really any narrow eras provided. So we can change …
> CLDR-15652 integration fix for en,de: restore GGGGG forms for japanese/generic calendar

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/web/TestUserLevel.java
- add a test for a null user on operations
- e.g. assert UserRegistry.userCanGetEmailList(null) == false
- refactor test code to make this test clearer and less error prone
CLDR-14766
Note this does NOT address the currently-failing `main` build.
> CLDR-14766 perms: UserRegistry: Check for User==null

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataSection.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNew.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/AnnotationUtil.java
-Revise CheckForCopy to recognize annotation codes like E10-836
-Move some code into new methods
-New class AnnotationUtil.java encapsulates info about annotation paths/values
-Revise import statements, done automatically by IntelliJ
CLDR-14064
> CLDR-14064 Prevent submission of root annotation values/codes

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/personname/PersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
Add checks on consistency of modifiers
Add checks on consistency of values for -core, -prefix, and plain
CLDR-15637
> CLDR-15637 add checks on consistency of modifiers

- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/js/src/views/AddUser.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleList.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/STError.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleNormalizer.java
- add API endpoint for locale normalizer
- add LocaleNormalizer.getMessageArray()
- live feedback on add user panel
CLDR-15223
image below from adding `und doi ff es FF` as locales  for an Adlam user
the field gets updated to just 'ff'
> CLDR-15223 feedback for adding users

- tools/pom.xml
CLDR-15532
Update ICU4J libs in CLDR to the ICU version after integrating CLDR 42-m1 (including rewrites of code to load DateTimeFormats, adding support for quarter duration, etc.).
> CLDR-15532 SBRS v42: Update ICU4J libs again after integrating CLDR 42-m1

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForExemplars.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PatternPlaceholders.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Placeholders.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
CLDR-15628
Handle non-numeric placeholders for personName nameField, add descriptions:
- Change regex for matching placeholders to accommodate the personName nameField style of placeholder
- Add new PlaceholderStatus OPTIONAL("Any specific placeholder is optional (and non-numeric); there must be at least one.")
- For a first pass, when generating placeholder id ignore some of the modifiers to allow one description to handle various modifier combinations.
- Add the placeholder descriptions for {prefix} {given} {given-informal} {given2} {surname} {surname-prefix} {surname-core} {surname2} {suffix} (in any combination with ignored modifiers -allCaps -initialCap -initial -monogram)
> CLDR-15628 Handle non-numeric placeholders for personName nameField, add descriptions

- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Placeholders.txt
CLDR-15628
Remove an extra character that found its way into on nameField placeholder example.
Also finish an incomplete comment that was part of a different PR (#2025)
> CLDR-15628 Extra char in one nameField placeholder example; incomplete comment elsewhere

- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/js/src/esm/cldrVote.js
- tools/cldr-apps/js/src/getCldrOpts.js
- tools/cldr-apps/js/src/views/CldrRow.vue
- tools/cldr-apps/js/src/views/CldrValue.vue
- tools/cldr-apps/js/src/views/DashboardWidget.vue
- tools/cldr-apps/src/main/webapp/surveytool.css
- setLang() (raw js) and CldrValue (Vue) encapsulate what is needed for display
of a CLDR value
- use <cldr-value> in DashboardWidget
- add cldrLoad.getLocaleDir() (refactoring code out of getCldrOpts)
- add a "cldrValue" class in surveytool.css, used everywhere and with
white-space: pre-wrap
CLDR-15686
> CLDR-15686 preserve spaces

- common/main/en.xml
- common/main/nl.xml
- common/main/root.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
CLDR-15691
- In ST display of sampleName fields for full sample, fix ordering of surname-prefix vs surname-core
- In full sample data, remove surname field if we have both surname-prefix and surname-core (note that nl_BE does not have surname-prefix and surname-core, just surname)
> CLDR-15691 fix sampleName field order in ST; remove surname from full if we have surname-prefix/-suffix

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/GlossonymConstructor.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/RegexUtilities.java
-Move digit pattern to util/RegexUtilities, rename it PATTERN_3_OR_4_DIGITS
-Remove GlossonymConstructor.track, inline the code instead
CLDR-13263
> CLDR-13263 Constructed-value-related clean-up

- tools/cldr-apps/js/src/esm/cldrReport.js
- tools/cldr-apps/js/src/views/ReportResponse.vue
- tools/cldr-apps/js/src/views/VettingSummary.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
- fixed CSS for report header
- add Download link to Report Status
CLDR-8666
UI improvement:
in Vetting Summary, download provides XLS (attached)
[survey_reports_-(6).xlsx](https://github.com/unicode-org/cldr/files/8855939/survey_reports_-.6.xlsx)
> CLDR-8666 Reports updates

- tools/cldr-apps/src/test/java/org/unicode/cldr/util/TestCLDRLinks.java
CLDR-10720
( Note: https://unicode-org.atlassian.net/browse/CLDR-15678 has been updated with  the results of this test.)
> CLDR-10720 TestCLDRLinks: fix URL parsing, was too restrictive

- common/dtd/ldml.dtd
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdData.java
CLDR-15671
In DtdData, treat all xml: attributes as metadata. Hopefully this is enough to make the xml:space attribute not show in ST,
- I don't want to just ignore/discard them entirely, since we want to be able to use the xml:space attribute as an indicator for space trimming in places like DAIP
- This should produce the desired result in XPathParts.getSpecialNondistinguishingAttributes()
- This allows us to remove `@VALUE` from the xml:space attribute in the dtd (and we don't need to replace it with `@METADATA`)
> CLDR-15671 treat xml: attributes as metadata, should not show in ST

- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
CLDR-15716
To clarify usage, change PathHeader (personNameSection) to rename the "Sorting" attribute value in a Survey Tool subsection head to "Sorting/Index" (affects Survey Tool only)
> CLDR-15716 in PathHeader personNameSection, rename "sorting" to "sorting/index"

- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLSource.java
CLDR-15318
To make the alt=variant (Türkiye) appears in all files, we need to add this one extra step (addFallbackCode, in XMLSource.java).
(The @Override is just from reformatting.)
> CLDR-15318 Make sure it appears (as missing) in all locales

- common/supplemental/coverageLevels.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/Locales.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
CLDR-15687
This adds a test for the 8 vote locales, according to the following policy.
* If a locale is in Locales.txt under Organization=Cldr, and has > 2 TC org locales at Modern, then it needs 8 votes.
* Otherwise it needs 4.
This involved making some small changes to coverageLevels.txt
* setting 3 locales to 4 votes that didn't make the bar: am, ga, ky
* setting some locales that did make the bar to 8 votes: bg, 'is' and the sublocales en_AU, en_GB, es_MX, fr_CA,
And some unrelated cleanup
* dropping 1 warning that isn't relevant anymore
* reformatting the output of another to be more readable.
Review the ticket with hiding whitespace to avoid some noise introduced by re-indenting.
> CLDR-15687 Add test for 8 votes, make changes in coverageLevels.xml

- common/dtd/ldml.dtd
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestXPathTable.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XPathParts.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/prettyPath.txt
CLDR-15671
This is a follow-on to #2087 that attempts to do a few more things that should fix the problem with the xml:space=preserve attribute showing in Survey Tool for the foreignSpaceReplacement element.
1. First I re-ran GenerateDtd; this added an explicit `@METADATA` annotation in the dtd for xml:space (even though we set this status in code anyway). This also responds to an issue Steven raised in a comment on #2087.
2. Finally understand what XPathParts.getSpecialNondistinguishingAttributes() is supposed to do (return  the collection of non-distinguishing attribute values that *should* appear with blue background in the Survey Tool left column) so fixed it to exclude xml: attributes from this collection, and added a function description to alleviate future confusion. Also added a …
> CLDR-15671 xml: attribute tests, explicitly list as @METADATA, prettyPaths for personNames

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterProgress.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestVettingViewer.java
-Make only one pass through paths for Summary, calculate locale completion in the same pass
-New VettingViewer.getLocaleCompletionCategories and getPriorityItemsSummaryCategories
-Rename getChoiceSetForOrg to getDashboardNotificationCategories for clarity
-New FileInfo.hasLocaleProblems to ignore warnings for locale completion
-New TestVettingViewer.java, make sure Summary notifications are superset of locale completion notifications
-New VoterProgress.friendlyPercent to round Progress column like progress meters
-Remove setLocaleToProgress and related code that was for double pass
-Remove unused parameter of updateVotedOrAbstained
-Comments
CLDR-15646
> CLDR-15646 Priority Items Summary: Progress column improvements

- tools/cldr-apps/js/src/views/VettingSummary.vue
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-Display snapshot id like 2022-05-16 08:15 GMT instead of 2022-05-16T08:15:25.083077935Z
-Fix the subheader lines, they are supposed to be between different first letters of locales
CLDR-15646
> CLDR-15646 Priority Items Summary: improve snapshot id, subheaders

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
CLDR-15357 
It's an incremental step.
`GET /api/completion/locale/es` for example now returns:
```json
{
"baselineCount": 6,
"error": 0,
"level": "MODERN",
"missing": 7,
"provisional": 0,
"total": 8653,
"votes": 8632
}
```
That `6` is missing+error+provisional from HEAD (current .xml).
> CLDR-15357 LocaleCompletion: add baseline count to back end

- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/js/src/views/VettingSummary.vue
-Even when a non-snapshot summary is displayed, the snapshot buttons should still be there
-Delete dead code from cldrProgress.js (unrelated)
CLDR-15646
> CLDR-15646 Priority Items Summary: fix bug, disappearing snapshot buttons

- common/annotations/en.xml
CLDR-15282
Remove keywords for 'red' from upwards and downwards button since the representation is up to the vendor and may not be red.
> CLDR-15282 Remove keywords for red

- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/js/src/views/VettingSummary.vue
-Change human-friendly snapshot id to have UTC not GMT
-Show the raw id in the snapshot button hover text
CLDR-15646
> CLDR-15646 Priority Items Summary: UTC; snapshot button hover

- tools/cldr-apps/js/src/esm/cldrProgress.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/VettingViewerQueue.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletion.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CompletionPercent.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleCompletionData.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterProgress.java
-Fix baselineCount by using a resolved CLDRFile for sourceFile
-Throw exception in generateLocaleCompletion unless sourceFile.isResolved
-Change calculation of locale completion percentage to use baselineCount
-Percentage cannot be less than 0 or greater than 100
-New interface LocaleBaselineCount, implemented by VVQueueLocaleBaselineCount
-New VettingViewer.localeBaselineCount, with setter
-New static LocaleCompletion.getBaselineCount
-Refactor LocaleCompletionCounter constructors to avoid duplication
-New CompletionPercent.java in util
-Move LocaleCompletionData to its own file LocaleCompletionData.java in util
-Encapsulate formula errors+missing+provisional with method LocaleCompletionData.problemCount
-Minor refactoring; final where possible; reduce public members, use getters/setters …
> CLDR-15646 Use baselineCount for 3rd meter and summary Progress column

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
-Eliminate unneeded setUsingKeywordAnnotationVoting
-VoteResolver.isUsingKeywordAnnotationVoting gets path from pathHeader
-This change will facilitate implementing a UsersChoice with VoteResolver without votes
CLDR-15646
> CLDR-15646 Encapsulate VoteResolver.isUsingKeywordAnnotationVoting

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STUsersChoice.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VotelessUsersChoice.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java
-New VotelessUsersChoice implements UsersChoice
-Add cldrFile parameter to UsersChoice.getVoteResolver
-Remove unused ValueChecker and ERRORS_ALLOWED_IN_VETTING (making ERRORS_ALLOWED_IN_VETTING permanently true); otherwise VotelessUsersChoice would need to reference them, and they would need to move from web to util
-Move calculateStatus from web/STFactory.java to util/VoteResolver
-Combine 1st/2nd parameters of calculateStatus which were always the same
CLDR-15646
> CLDR-15646 Prevent baselineCount from depending on votes

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
CLDR-15646
Adds the ability to see the raw Missing and Provisional items. While these are not exactly the same as the counts of items in the Survey tool, they are useful for sanity checks.
Also, skip items with SectionId=Special; no need to process those.
> CLDR-15646 Modify ConsoleCheckCLDR to show missing/provisional items

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-15732
Small fix, plus test.
Note: most of the changes in ExampleGenerator are just formatting to fix the import of *.
> CLDR-15732 fix bad ordinal minimal pair examples

- common/main/ca.xml
- common/main/es.xml
- common/main/gl.xml
CLDR-15749
As per discussions in person-names WG.
* These are added as alt='1' and provisional, so vetters will need to confirm the value and change as needed.
> CLDR-15749 Add extra paths for ca, es, gl names

- tools/cldr-code/src/main/java/org/unicode/cldr/util/VotelessUsersChoice.java
-In VotelessUsersChoice set baseline value using xmlSource.isHere, getValueAtDPath
CLDR-15646
> CLDR-15646 Make baselineCount more consistent with non-baseline

- tools/cldr-apps/src/main/webapp/surveytool.css
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-10674
This PR adds the infrastructure to display bidi examples in both default and RTL context, and implements it for just currencyFormats. Once we see how that looks, I will create a separate PR to implement it for more cases (units, short date formats?) and also to refine the behavior based on this first pass.
> CLDR-10674 Survey Tool to display bidi examples in default and RL context; pass 1 currencyFmts

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/ReportStatusUpdater.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/MemVoterReportStatus.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestReportStatus.java
CLDR-8666 Vote Report Resolver and tests
- also make VoterReportStatus abstract instead of interface
- move ReportStatusUpdater into org.unicode.cldr.util (not web specific)
- tests added, but they depend on CLDR-15765 to be safe (so disabled for now)
> CLDR-8666 Implementation for Vote Report Resolver

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/MemVoterReportStatus.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterReportStatus.java
- move MemVoterReportStatus out of tests and back into cldr-code
- add a 'date' field to ReportStatus and MemVoterReportStatus, for date dependent
vote resolution
- add a ReportsDB.clone() function which make a subset copy of the database
This makes it much more performant to update VoteResolvers- one query instead of
thousands
CLDR-8666
> CLDR-8666 Reports: Updated API for using VoteResolver 

- tools/cldr-apps/src/main/webapp/surveytool.css
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
CLDR-10674
Improve the bidi examples using multiple contexts:
- Better cell background for neutral examples
- Better phrasing for header
- Simpler set for BIDI_MARKS
- Better determination of when to use neutral or strong symbol for currency examples
- Extend the multi-context examples to other number patterns
- Avoid invisible characters in code
> CLDR-10674 Bidi examples: better header & cell background, fix symbolIsLetters, extend to other numberPatterns

- common/main/oc_ES.xml
CLDR-15746
For `oc_ES`, the vetter requested adding some missing `MMMM` date formats (cannot be added in Survey Tool), copying the missing forms from `es` which has them.
> CLDR-15746 os_ES, copy missing MMMM ("de MMMM") date formats from es

- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAll.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCompactNumbers.java
The test for compact numbers was not actually being run, so enabling that, and cleaning up the test a bit.
CLDR-15737
> CLDR-15737 The test for compact numbers was not actually being run

- tools/cldr-code/src/main/java/org/unicode/cldr/test/ExampleGenerator.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestExampleGenerator.java
CLDR-10674
Add multi-bidi-context examples for time formats and short date formats.
I think that is the last of the important cases I wanted to add for CLDR 42.
> CLDR-10674 Add multi-bidi-context examples for time & short date formats

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/Dashboard.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/LocaleCompletionCounter.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/MissingPathXml.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/MissingXmlGetter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingParameters.java
-Accessible through openapi/ui/ under api/missingxml for users with write permission for locale
-Implement by getting Dashboard data and adding paths that have notifications
-Show notification types/descriptions and English values in xml comments
-Move Dashboard.setFiles and setFilesForBaseline to VettingParameters in util, not limited to Dashboard
CLDR-15707
> CLDR-15707 Enable downloading error/missing/provisional as xml

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/ReportsDB.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/ReportAPI.java
- tools/cldr-apps/src/main/resources/org/unicode/cldr/web/sql/cldr-reports-db.sql
- CLDR_VOTE_REPORTS* index needed to be unique.
This is now fixed, meaning that future versions will create this table with a unique index.
- For the current release, ensure that votes are  queried in
last_mod ascending order, meaning that the latest vote wins
- Fix a logic bug in the report API
CLDR-8666
> CLDR-8666 Reports: correction to table uniqueness

- common/supplemental/supplementalData.xml
CLDR-15788
Per the actual time formats for ja, 12-hour formats prefer K over h
> CLDR-15788 supplemental timeData for JP should move K before h

- common/main/et.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckForCopy.java
CLDR-15795
Allow the name for language code `gaa` ("Ga" in English) to be the same as code, needed for `et` where the name should  be exactly "gaa". Add language name as provisional in `et` for testing. This is needed by Pikne, Wikimedia vetter for `et`.
> CLDR-15795 Allow name for lang code gaa to be same as code, test for et (where needed)

- common/annotations/tk.xml
- common/main/tk.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt
CLDR-15801
1. The data is marked as draft=contributed.
2. Some of the XML data was commented out, because they caused errors. 
1. The date formats were malformed. Using AAAA instead of MMMM for long month, and ý for year.
2. The abbreviated islamic months require language knowledge to fix. 
3. In both cases, the Survey tool alerts people to the problems as they enter them, allowing them to fix the syntax.
> CLDR-15801 workaround for data from Turkmenistan

- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckLogicalGroupings.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/LogicalGroupChecker.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LogicalGrouping.java
- tools/cldr-code/src/test/java/org/unicode/cldr/test/TestCheckLogicalGroupings.java
-New unit test TestCheckLogicalGroupings.testSameCoverageLevel
-Take isOptional into account for the unit test
-Refactor CheckLogicalGroupings.java, especially extremely long method handleCheck
-New LogicalGroupingChecker.java encapsulates the refactored code with shorter methods
CLDR-10564
> CLDR-10564 Logical groups; unit test and refactoring

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
CLDR-15799
Per [CLDR-13263](https://unicode-org.atlassian.net/browse/CLDR-13263) which added GlossonymConstructor, the path PSEUDO_PATH ("constructed") is now used to indicate the path for constructed fallback values for locale display names. However, GenerateProductionData had not been updated to handle this, leading to exceptions when "constructed" was passed down to XPathParts Apis that expected a real path beginning with '/'. This PR updates GenerateProductionData to handle PSEUDO_PATH. This also means that production data will remove a lot of display names that duplicate the inherited or constructed value.
> CLDR-15799 Adapt GenerateProductionData to the CLDR-13263 change to use PSEUDO_PATH

- common/main/hi.xml
- common/supplemental/dayPeriods.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-15833
On the brs/v42vxml branch, fix the following unittest failures from the imported CDR 42 vxml:
```
TestDayPeriods {
TestAttributes {
Error: (TestFmwkPlus.java:49) File TestDayPeriods.java, Line 86 hi_Latn : ‹[midnight, night1, morning1, afternoon1, evening1, night1]› NOT contains ‹noon›; expected true
Error: (TestFmwkPlus.java:49) File TestDayPeriods.java, Line 86 hi_Latn : ‹[midnight, night1, morning1, afternoon1, evening1, night1]› NOT contains ‹noon›; expected true
Error: (TestFmwkPlus.java:49) File TestDayPeriods.java, Line 86 hi_Latn : ‹[midnight, night1, morning1, afternoon1, evening1, night1]› NOT contains ‹noon›; expected true
Error: (TestFmwkPlus.java:49) File TestDayPeriods.java, Line 86 hi_Latn : ‹[midnight, night1, morning1, afternoon1, evening1, night1]› NOT …
```
> CLDR-15833 vxml errs: hi empty zone name, hi_Latn needs noon, update ja personName example

- common/annotations/ff.xml
- common/annotations/kk.xml
- common/annotations/nb.xml
CLDR-15838
Fix remaining unittest failures in bis/v42vxml branch as follows:
1. Add missing stub files in common/annotations: ff.xml, nb.xml
2. Fix duplicate emoji tts names for kk as follows (we can update these later if we get better info from vetters, but this fixes the errors for now):
* For 🏵 rosette, changed from  "раушан" (rose, duplicates another) to "розетта" (rosette, which was already one of the annotations)
* For ❤️‍🩹 mending heart, changed from "жаралы жүрек" (broken heart, duplicates another name) to "емдік жүрек" (healing heart)
Once this is merged we can go on to fix the ConsoleCheckCLDR errors in the vxml branch.
> CLDR-15838 vxml annotations errs: missing ff, nb; dup kk names

- tools/cldr-apps/js/src/esm/cldrForum.js
- tools/cldr-apps/js/src/esm/cldrForumPanel.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrMenu.js
- tools/cldr-apps/js/src/esm/cldrOldVotes.js
- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/js/test/TestCldrTable.js
- tools/cldr-apps/js/test/index.js
-Move code to new method cldrLoad.addSectionHeader; add onclick
-New methods cldrTable.isHeaderId, makeHeaderId, and goToHeaderId
-Encapsulate row_ (formerly r@) prefix with new cldrTable.makeRowId
-Remove unused parameters doPush/replace for cldrLoad.replaceHash, setHash, updateHashAndMenus
-Remove deprecated and pointless substr(0) in cldrLoad.js
-Use CLDR_LOAD_DEBUG instead of local variable reportProblems
-New unit test for cldrTable
-Comments
CLDR-13082
> CLDR-13082 Add link for headers on ST pages

- common/main/ne.xml
- common/main/tok.xml
- seed/main/ab.xml
- seed/main/cv.xml
- seed/main/hnj.xml
- seed/main/myv.xml
CLDR-15842
Fix the following ConsoleCheck errors in the vxml:
```
ne [Nepali]	error,ne.xml:2068	▸Date_&_Time|Indian|Months_-_wide_-_Formatting|Oct◂	〈Pausa〉	【】	〈माघ〉	«=»	【】	⁅date symbol collision⁆	❮Error: The date value “माघ” is the same as what is used for a different item: [Months - wide - Standalone: Nov]❯
ne [Nepali]	error,ne.xml:2113	▸Date_&_Time|Indian|Months_-_wide_-_Standalone|Nov◂	〈Magha〉	【】	〈माघ〉	«=»	【】	⁅date symbol collision⁆	❮Error: The date value “माघ” is the same as what is used for a different item: [Months - wide - Formatting: Oct]❯
tok [Toki Pona]	error	▸Locale_Display_Names|Territories_(Africa)|Eastern_Africa|IO◂	〈British Indian Ocean Territory〉	【】	〈IO〉	«=»	【】⁅same as code⁆	❮Error: The value is the same as the 'code'❯	code-fallback
tok [Toki Pona]	error …
```
> CLDR-15842 vxml ConsoleCheck errs for ne, tok, ab, cv, hnj, myv

- common/main/chr.xml
- common/main/mai.xml
- common/main/mt.xml
- seed/main/syr.xml
CLDR-15844
Fix the following ConsoleCheck errors in the vxml:
```
chr [Cherokee]	error,chr.xml:9260	▸Miscellaneous|Person_Name_Formats|NameOrder_for_Locales|givenFirst◂	〈und en〉	【】	〈und en〉	«=»	【】	⁅missing language⁆	❮Error: Your locale code (chr) must be explicitly listed in one of the nameOrderLocales: either in givenFirst or in surnameFirst.❯
chr [Cherokee]	error,root.xml:5416	▸Miscellaneous|Person_Name_Formats|NameOrder_for_Locales|surnameFirst◂	〈ja ko zh〉	【】	〈hu ja ko vi yue zh〉	«=»	【】⁅missing language⁆	❮Error: Your locale code (chr) must be explicitly listed in one of the nameOrderLocales: either in givenFirst or in surnameFirst.❯	root
mai [Maithili]	error	▸Timezones|Oceania|New_Caledonia|daylight-long◂	〈New Caledonia Summer Time〉	【】	〈null〉	«»	【】	⁅incomplete logical group⁆	❮Error: …
```
> CLDR-15844 vxml ConsoleCheck errs for chr, mai, mt, and partially for syr

- common/annotations/kab.xml
- common/main/bn_IN.xml
- common/main/fil.xml
CLDR-15845
common/annotations/kab.xml
Deleted the 2 zodiac symbols that were colliding
common/main/bn_IN.xml
The bn.xml patterns didn't have the problem, so reverted to them (by deletion). The new values were broken anyway because they were only partial : all of the patterns have to be in parallel, and have the same meaning.
We need to alert the vetters for next time to review these (and work in coordination with bn.xml)
common/main/fil.xml
One was an obvious error, and I picked formatting versions for some of the collisions.
There are still oddities, like the following:
```
2,325: <dayPeriod type="evening1">ng gabi</dayPeriod> 
2,336: <dayPeriod type="evening1">sa gabi</dayPeriod> 
2,347: <dayPeriod type="evening1">ng gabi</dayPeriod> 
```
The abbreviated and wide are 'na', while the …
> CLDR-15845 more xml errors

- .github/COMMIT_METADATA.md
02198373a591a15b804127acddd32582ec985b7e (#2190) was a merge, but the message was not edited
CLDR-15852
> CLDR-15852 v42: update COMMIT_METADATA for bad commit message

- tools/cldr-apps/js/src/esm/cldrVettingParticipation.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/OrgCoverageLevelCounter.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyVettingParticipation.java
- new class, OrgCoverageLevelCounter - takes about 2 minutes the first
time each startup to count items in coverage.
CLDR-15689
Example of spreadsheet image:
> CLDR-15689 add votes and cldrcovcount column to spreadsheet

- common/dtd/ldml.dtd
- common/main/cs.xml
CLDR-15804
In CLDR 42 Survey Tool submission, Czech vetters added a comma to the standard full time format (with zzzz) `H:mm:ss, zzzz` (and this won), leaving the standard long time format (with just z) without a comma: `H:mm:ss z`. To match this and prevent associated warnings, we need to update the availableFormats and intervalFormats to add patterns that distinguish skeletons with `vvvv` (which should have comma) from skeletons with just `v` (which should not). Adding these was something the vetters could not do in the Survey Tool.
> CLDR-15804 cs: add availableFmts/intervalFmts for vvvv, with comma

- common/collation/sv.xml
CLDR-15603
For Swedish, https://github.com/unicode-org/cldr/pull/2171 renamed the "reformed" collation to "standard" (after renaming the previous "standard" to "traditional". However it not update the defaultCollation element, which still pointed to the now non-existent "reformed". This fixes that. (Note there is a separate CLDR ticket to add a test that should detect this kind of problem).
> CLDR-15603 sv: also update defaultCollation from "reformed" to "standard"

- common/main/de.xml
CLDR-15864
Fix the problem of space (\u2009) swapped with y in de gregorian intervalFormat for yM/y
> CLDR-15864 de: fix intervalFormat for yM/y (space swapped)

- common/rbnf/root.xml
CLDR-15863
Add a fallback xDefault ruleset to rbnf root NumberingSystemRules; for motivation see https://unicode-org.atlassian.net/browse/ICU-22088
> CLDR-15863 add fallback zDefault ruleset to NumberingSystemRules

- tools/cldr-apps/src/main/webapp/META-INF/microprofile-config.properties
- tools/scripts/ansible/nginx-playbook.yml
- add X-Forwarded-Proto: header as it should have been
- remove microprofile-config.properties as not needed
CLDR-8666
this fixes CLDR-15702
> CLDR-8666 fix nginx, not microprofile

- common/collation/hy.xml
CLDR-15840
For hy: sort ech-yiwn ligature between lowercase and titlecase ech+vew, per [L2/22-124](https://www.unicode.org/L2/L2022/22124-utc172-properties-recs.pdf) item Coll2.
> CLDR-15840 hy collation: sort ech-yiwn ligature between lowercase and titlecase ech+vew

- common/main/wae.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDisplayAndInputProcessor.java
CLDR-15635
Remove the logKnownIssue test skip added per CLDR-14032, which skipped testing DAIP roundtrip on certain paths until CLDRModify with he updated DAIP had been run over the data. It now has, per [CLDR-15862](https://unicode-org.atlassian.net/browse/CLDR-15862), so remove the test skip.
However: One of the files tested is `wae`, which still inherits many paths from root (which intentionally does _not_ have the DAIP modifications). So add the necessary items to `wae`, easy to infer from what it was inheriting plus comparison to the patterns it does have. Another alternative might have been to skip `wae`, but then we might not have caught other possible issues for which testing it was added in the first place.
> CLDR-15635 Remove logKnownIssue test skip in TestDisplayAndInputProcessor; add items to wae

- common/main/he.xml
CLDR-14660
In the Hebrew standard currency format, add RLM before the currency symbol in both the positive and negative formats. As demonstrated in smoketest using the new bidi examples, this makes currency lay out the same regardless of positive of negative form, ISO 4217 symbol (strong LR) or shekel symbol, and R-L or neutral context.
And then since the accounting format did not seem to be trying to do anything special, copy the standard currency format to the accounting format.
I plan to discuss this during the CLDR TC meeting 2022-08-01.
> CLDR-14660 he currency formats, add RLM before currency sign

- common/main/ig.xml
Fix "this is not a translation" names and symbol for Igbo translation of Lesotho Loti (LSL)
CLDR-15866
> CLDR-15866 Fix translation for LSL in ig

- keyboards/und/pcm-t-k0-windows.xml
- use \u{22} instead of &quot; as with other files
CLDR-15557
> CLDR-15557 keyboard: work around XPath issue for doublequote

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/WritePluralRulesSpreadsheets.java
'*' isn't a locale, it's a Locales.txt marker.
CLDR-15647
As the comment in https://cldr.unicode.org/development/updating-codes/update-plurals - it's not clear what the purpose of this tool is.  Dumps a bunch of stuff to the console.
Note that this tool is still broken due to CLDR-15599 ( @AEApple  ) but i put in a temporary catalan 'many' rule to ensure there was no other breaker.
> CLDR-15647 WritePluralRulesSpreadsheets: skip '*'

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserRegistry.java
- tools/cldr-apps/src/test/java/org/unicode/cldr/unittest/web/TestAnnotationVotes.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/ConsoleCheckCLDR.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VotelessUsersChoice.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoterInfoList.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestVettingViewer.java
- new class VoterInfoList, replaces hidden statics in VoteResolver
- VoterInfoList must be passed as the first arg of new VoteResolver()
- VoterInfoList is mutable (synchronized)
- Fixup tests to use VoterInfoList
- For SurveyTool, the UserRegistry manages the VoterInfoList along with the underlying
map
CLDR-15765
> CLDR-15765 refactor VoteResolver to fix static init

- common/main/en_001.xml
- common/main/en_GB.xml
CLDR-14075
Per discussion in CLDR infra meeting 2022-08-02: en_001 format that combine E + time should not have comma (push up formats from en_GB); en_GB date formats with E should have comma, so changes the two generic ones that do not to inherit ones that do instead.
> CLDR-14075 en_001 E+time formats should not have comma, en_GB E+date formats should (inherit)

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/CLDRModify.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Annotations.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRConfig.java
- CLDRConfig.getAnnotationsFactory now includes seed
- but, Annotations.getAvailable() only includes locales in common
- Annotations.getAllAvailable() includes seed+common
- CLDRModify has a special path which includes common/annotations when resolving
seed/annotations files, otherwise root.xml is not found.
CLDR-14981
> CLDR-14981 make CLDRModify -fQ work for seed/annotations

- common/main/en.xml
- common/main/en_AU.xml
- common/main/en_SL.xml
- common/main/ff_Adlm_SL.xml
- common/main/ff_Latn_SL.xml
- common/supplemental/supplementalData.xml
- SLE became legal tender 2022-07-01
- SLL will cease to be tender 2022-10-01
This PR:
- updates metadata
- moves SLL to SLE in symbol
- add (1964-2022) to SLL in en name
References:
- https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/news/sierra-leone.pdf
- https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl_currency_iso_amendment_172.pdf
CLDR-15900 followon to #1825 
> CLDR-15900 BRS v42: update SLE/SLL legal tender

- common/main/ar.xml
CLDR-13449
Improve the consistency of short date formats in Arabic.
- One part of this was just making sure that in the combination of RLM and '/', the RLM consistently comes first (easier to compare formats). That fix was also related to https://unicode-org.atlassian.net/browse/CLDR-14076. Also removed unnecessary RLMs on the en-dash in a couple of intervalFormats.
- For Md intervalFormats, most greatestDifference values used d/M (with RLM), but:
- 3 used d-M (one of these was mixed with d/M for the same skeleton).
- 1 used M/d without RLM to try and get right layout (but with wrong field order).
- Made them all consistently use d/M (with RLM before /).
> CLDR-13449 ar short date formats, improve consistency

- common/segments/fi.xml
- common/segments/root.xml
- common/segments/sv.xml
CLDR-15910
For word break in CLDR, remove colons from MidLetter class for root version, but add tailorings for fi,sv that include colons for MidLetter. Colons include:
```
003A # Po COLON
FE55 # Po SMALL COLON
FF1A # Po FULLWIDTH COLON
```
> CLDR-15910 For word break MidLetter class, only include COLON for fi,sv

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
CLDR-15912
When running the CLDR-ICU integration, I periodically encounter hard-to-diagnose crashes in GenerateProductionData (usually NPE) that sometimes go away if I re-run it or if there is a slight data change, and go away if I temporarily de-parallelize GenerateProductionData. So I am just going to commit the de-parallelized version, the 2 or so minutes of speedup from the parallel version are not worth the occasional crashes. At some point we can investigate these crashes.
> CLDR-15912 un-parallelize GenerateProductionData to avoid crashes

- common/properties/coverageLevels.txt
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
Further coverage chart refinements to extract exact counts of items for each locale. Also adds a bit of documentation to the .html chart.
CLDR-15903
> CLDR-15903 further coverage chart refinements

- common/main/el.xml
- common/main/eu.xml
- common/main/fr.xml
- common/main/he.xml
- common/main/hy.xml
- common/main/ig.xml
- common/main/ky.xml
- common/main/mk.xml
- common/main/mn.xml
- common/main/nl.xml
- common/main/pa.xml
- common/main/qu.xml
- common/main/so.xml
- common/main/ta.xml
- common/main/tk.xml
- common/main/to.xml
- common/main/tr.xml
- common/main/yo.xml
- common/main/yo_BJ.xml
- common/main/zu.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPaths.java
CLDR-15739
Modifies DAIP so that it normalizes the locale lists, then runs it.
1. Any zxx is removed
2. Any 'und' is sorted at the front.
Note that Dutch is pulled in because the file was not yet normalized with DAIP
> CLDR-15739 allow vote for empty list of locales

- common/main/cs.xml
CLDR-13717
In cs list patterns, use NBSP for second space in {0} a {1} to prevent lines that end with a 1-letter word (not permitted in cs).
> CLDR-13717 cs list patterns, use NBSP for second space in {0} a {1}

- common/main/bg.xml
CLDR-13043
bg currency patterns should use grouping separator
> CLDR-13043 bg currency patterns should use grouping separator

- common/main/ar.xml
CLDR-15902
For currency patterns in ar:
- For standard currency patterns for 'arab' and 'latn' digits, add RLMs as shown in [Arabic currency formats](https://docs.google.com/document/d/1D3q1BlICcpQi_GWZXyudP-KlVMNMb3l2ZJAGELF1VI4/edit#)
- For accounting currency patterns for 'latn' digits, add ALM at the beginning of the positive pattern, and also lust after the initial paren of the negative currency pattern.
> CLDR-15902 ar currency patterns add RLM/ALMs for improved layout

- common/dtd/ldmlSupplemental.dtd
- common/supplemental/units.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/PathHeader.txt
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUnits.java
The problem was a hidden NBSP.
Also, hide the display of information in TestUnits under the flags. This drastically reduces the number of warnings for the normal case.
CLDR-14421
> CLDR-14421 fix XML problem in unitIdComponents

- common/supplemental/likelySubtags.xml
- common/supplemental/supplementalMetadata.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestAttributeValues.java
CLDR-15921 likely subtags
Still some manual reverts here, all of the following are missing:
Missing from defaultcontent when generating
~- `shn_MM`~ **Edit** This wasn't missing, just in the wrong place.
- `tok_001`
- `os_GE` (vs `os_RU`)
Missing from likelysubtags when generating
- `oc_ES`
- `sd_IN`
- `tok`
- `rhg_Arab_MM`
- `und_Cpmn_CY`
> CLDR-15921 v42 BRS LikelySubtags

- common/supplemental/plurals.xml
CLDR-15255
The discussion is complicated: see the comments in https://unicode-org.atlassian.net/browse/CLDR-15255. 
Reverting to before 11578: 
[CLDR-11578: rules for Romanian plural numbersDONE](https://unicode-org.atlassian.net/browse/CLDR-11578) 
That is, [CLDR-11577 fix for Romanian 101, etc. · unicode-org/cldr@aedd789](https://github.com/unicode-org/cldr/commit/aedd789db89d567a2d8555f510aef3577747ae75)
> CLDR-15255 revert Romanian plurals

- common/main/en_AU.xml
- common/main/oc_ES.xml
- common/main/sw_KE.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateProductionData.java
CLDR-15932
Fix issues from running tests on the production version of the data (BRS task):
1. `en_AU` fluid ounces: There was a display name collision because `en_AU` was inheriting from `en_001` the plain name "fluid ounce" for `volume-fluid-ounce-imperial`, but also defined the plain name "fluid ounce" for `volume-fluid-ounce` (i.e. the US fluid ounce). Although `en_AU` is mostly metric (more so than `en_GB`), per https://www.legislation.gov.au/Details/F2012C00400 the fluid ounce they do use is the US one, i.e. 0.0000295735296 cubic meters. So changed the display names for `volume-fluid-ounce-imperial` to explicitly use "Imperial".
2. `oc_ES` missing currency symbols: There were two cases in which `oc_ES` was overriding a narrow currency symbol inherited from `os`, while inheriting …
> CLDR-15932 issues from prod test: copy empty annotation parents, fix en_AU/oc_ES/sw_KE

- common/main/zh.xml
CLDR-15937
Note: the change now makes the translation *almost* identical to currency BGO, which uses "保加利亚列弗 (1879–1952)", i.e. the same currency name but with the year interval added.
> CLDR-15937 zh word new erroneously added

- common/main/en_CH.xml
- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/modify_config.txt
CLDR-14951
Change the en_CH date format separator. 
- This probably changes more calendar than necessary. However, the extra data is harmless.
- I had to change the format of the modify_config.txt lines (just a note for the future)
> CLDR-14951 english date format separators for CH

- common/testData/units/unitPreferencesTest.txt
CLDR-15949
CLDR-14421 renamed the unit "metric-ton" to "tonne" but did not update the unitPreferencesTest.txt file used for ICU tests; this PR updates "metric-ton" in that file to "tonne"
> CLDR-15949 In unitPreferencesTest.txt, change metric-ton to tonne for ICU tests

- tools/cldr-code/src/main/java/org/unicode/cldr/util/Containment.java
- tools/cldr-rdf/pom.xml
- tools/cldr-rdf/src/main/resources/org/unicode/cldr/rdf/sparql/wikidata-childToParent.sparql
- speedup childToParent query a few orders of magnitude
- also enable JDK 1.4 logging from Jena
(this matches what we do with OpenLiberty)
The actual data update will be a separate PR.
CLDR-15957
> CLDR-15957 rdf: fix logging, speedup query

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
JSON output already escapes " to \", double escaping produced \\\"
CLDR-15575
> CLDR-15575 json: don\"t double escape double quotes

- common/dtd/ldml.dtd
- common/main/ja.xml
Previously, the maximum supported number was:
999999999999999
Adds support for numbers up to:
99999999999999999999
CLDR-15966
> CLDR-15966 ja-JP numbers ≤ 99999999999999999999

- common/annotations/fr.xml
- common/main/da.xml
- common/main/fr.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
-Add feature to DAIP to remove ZWS from only two locales for now: da and fr
-Apply the resulting changes to 3 xml files
-Comments
CLDR-15976
> CLDR-15976 Remove some occurrences of ZERO WIDTH SPACE

- tools/pom.xml
CLDR-15994
Update ICU4J libs in CLDR to ICU4J as of 2022-09-07, through the following ICU fixes:
- 00003dcbf2... ICU-21957 Update TODO ticket reference: CLDR-13044 (done) ---> ICU-21420 (open).
- 6e3a923056... ICU-22116 Update CI job for ICU4J to use Java 8 instead of Java 7
- baa104b50b... ICU-21957 Clean-up of TODO and logKnownIssue entries (BRS task):
> CLDR-15994 BRS v42: Update ICU4J libs before alpha3

- common/main/ar.xml
CLDR-15992
For ar with 'latn' digits, change currency formats to have symbol trailing (displaying on the L):
- For standard formats, change to `<RLM>#,##0.00<NBSP>¤;<RLM>-#,##0.00<NBSP>¤`
- For accounting format, change to `<ALM>#,##0.00¤;(<ALM>#,##0.00¤)`
- Interestingly, the accounting format alt="alphaNextToNumber" was already the same as the above plus NBSP before the currency symbol
> CLDR-15992 ar with latn digits: change currency formats to have symbol trailing

- tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config_supplemental.txt
- fix for units in CLDR-14421
- fix for supplemental person names data in CLDR-15414
- rename package to cldr-person-names* instead of cldr-personNames*
CLDR-15414
> CLDR-15414 json: personnames, unit fixes

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
- update logic for 'modern' vs 'full'
- new StandardCodes.getHighestLocaleCoverageLevel() which checks parent locales (but not root)
CLDR-16002
Yes, this is on maint-42
> CLDR-16002 json: update 'modern' logic

- common/main/lo.xml
- common/main/th.xml
CLDR-15977
Fix spaces in th and lo on maint-42
> CLDR-15977 fix spaces in th and lao in person names

- readme.html
- tools/pom.xml
CLDR-16005
Update ICU4J libs in CLDR to the version of 2022-Sep-12. In particular, this picks up the fix for https://unicode-org.atlassian.net/browse/ICU-22143 to increase COMPACT_MAX_DIGITS to handle the new Japanese data.
Also update the readme date for beta.
> CLDR-16005 BRS v42: Update ICU4J libs before beta1

- tools/cldr-code/src/main/java/org/unicode/cldr/draft/JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt
- due to CLDR-14336
CLDR-15958
With this fix, English JSON data is, for example,
```json
{
"standard": "¤#,##0.00",
"standard-alphaNextToNumber": "¤ #,##0.00",
"standard-noCurrency": "#,##0.00",
"accounting": "¤#,##0.00;(¤#,##0.00)",
"accounting-alphaNextToNumber": "¤ #,##0.00;(¤ #,##0.00)",
"accounting-noCurrency": "#,##0.00;(#,##0.00)"
}
```
> CLDR-15958 json: fix currency generation

- common/dtd/ldml.xsd
- common/dtd/ldmlBCP47.xsd
- common/dtd/ldmlSupplemental.xsd
- common/dtd/xml.xsd
- keyboards/dtd/ldmlKeyboard.xsd
- tools/cldr-code/pom.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDtd.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DtdType.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/XMLValidator.java
- tools/pom.xml
CLDR-15990
⚠️ **Not v42 See important note at end**
Generates and adds XML Schema as part of GenerateDtd
Does not currently alter the XSD from the autoconverted form, but in the future *could* use the DtdData annotations to create a better .xsd file
- use the jing-trang library
- add an option --schema= to XMLValidator to use the schema
-----
Note: this is not for v42.  It is on the keyboard branch in response to an idea that had been brought up in Keyboard-SC. If this is included in keyboard branch (and as part of the Keyboard work) that doesn't mean that it must go into CLDR. But brought here for review in case it's a good idea.
Also note that Keyman in https://github.com/keymanapp/keyman/pull/7184 is using an auto generated XSD because it is difficult to find DTD validators in …
> CLDR-15990 generate .xsd from .dtd

- tools/cldr-code/src/main/java/org/unicode/cldr/json/CldrNode.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/LdmlConvertRules.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CldrUtility.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/JSON_config.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/json/pathTransforms.txt
- tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/cldr-json-readme.md
CLDR-15414
- updated structure for personnames
also:
- drop xml:space from json, everywhere
- reorg how the copyright date is done in json (to avoid a yearly bump)
- improve how packageDesc is handled, so more packages have descriptions
> CLDR-15414 json: personNames structure, other improvements

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrAdmin.js
- tools/cldr-apps/js/src/esm/cldrCreateLogin.js
- tools/cldr-apps/js/src/esm/cldrErrorSubtypes.js
- tools/cldr-apps/js/src/esm/cldrEvent.js
- tools/cldr-apps/js/src/esm/cldrGenericVue.js
- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrLocales.js
- tools/cldr-apps/js/src/esm/cldrMenu.js
- tools/cldr-apps/js/src/esm/cldrRecentActivity.js
- tools/cldr-apps/js/src/esm/cldrReport.js
- tools/cldr-apps/js/src/esm/cldrReportDates.js
- tools/cldr-apps/js/src/esm/cldrReportNumbers.js
- tools/cldr-apps/js/src/esm/cldrReportZones.js
- tools/cldr-apps/js/src/esm/cldrRetry.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/js/src/views/GeneralInfo.vue
- tools/cldr-apps/js/src/views/InfoPanel.vue
- tools/cldr-apps/js/test/TestCldrProgress.js
- tools/cldr-apps/src/main/webapp/css/redesign.css
-Give the Info Panel a title bar with a close box
-Rename button from Toggle Info Panel to Open Info Panel
-Hide button when panel is visible
-Remember whether the panel should be visible for the Page table view
-Use new InfoPanel.vue for the title bar, non-Vue (for now) for content
-Automatically close panel by default for specials
-Automatically open panel for specials that call showMessage
-Move some Info Panel code from cldrGui.js to cldrInfo.js
-Refactor for encapsulation, simplicity, shorter functions, use subroutines
-Fix inconsistent naming: change section_general to generalSpecialGuidance; change special_general to section_general
-Fix unit test TestCldrProgress, was missing export ok
-Comments
CLDR-14734
> CLDR-14734 Info Panel Visibility

- common/bcp47/measure.xml
CLDR-15933
The bcp47 alias added in #2303 for new key "mu" is unnecessary (don't need aliases for new keys), and is malformed.
> CLDR-15933 Remove unnecessary & incorrect legacy alias added for key "mu"

- common/annotations/ar.xml
CLDR-15246
Remove dangerous and unneeded unpaired RLEs from annotations/ar.xml
Hard to see a removal of invisible characters in the git diffs, although it does affect the layout (possibly depending on the browser you are using)
> CLDR-15246 Remove dangerous and unneeded unpaired RLEs from annotations/ar.xml

- docs/ldml/tr35-dates.md
CLDR-15286
Document new dateTimeFormat "atTime" variant and when to use it.
Note in this PR I am not adding the corresponding entry in the Mods section of tr35 because it would conflict with a prior PR. I will updated the Mods section for this addition as part of another spec PR.
> CLDR-15286 Document new dateTimeFormat "atTime" variant and when to use it

- docs/ldml/tr35.md
- Latest proposed update link should always be: https://www.unicode.org/reports/tr35/proposed.html
- This URL will redirect to the appropriate spot depending on project phase
CLDR-16028
> CLDR-16028 doc: update Latest Proposed Update link

- docs/ldml/tr35.md
CLDR-16018
Used https://www.tablesgenerator.com/markdown_tables to regenerate and fix the table
1. first paste from HTML spec page into spreadsheet (https://unicode.org/reports/tr35/tr35.html#1-multimap-interpretation)
2. then adjust spreadsheet to have no merged cells (and in this case, fix the misalignment)
3. copy into  https://www.tablesgenerator.com/markdown_tables
4. hit Generate, and copy result into LDML page
> CLDR-16018 fix table

- readme.html
- tools/pom.xml
CLDR-16036
Now that ICU release-72-rc is tagged, update ICU4J libs in CLDR to that version before CLDR 42 beta2
> CLDR-16036 BRS v42: Update ICU4J libs to release-72-rc before CLDR 42 beta2

- common/supplemental/supplementalData.xml
- per ISO 4217 amendment 173 quoting directive from the Bank of Sierra Leone dated 2022-09-15
- https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl-currency-iso-amendment-173.pdf
CLDR-15900
> CLDR-15900 v42: SLL extended transition period

- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35.md
CLDR-15955
Note that this deviates somewhat from the ticket: simple_unit is now above prefixed_unit, since the names and structure make more sense that way.
(Also, the table in the ticket got gummed up because of the presence of | characters in the text. The sheet https://docs.google.com/spreadsheets/d/1QpVPnIgJdYWZil2sr_L4P3z6O_AsT3sKZhP_SOyTVqQ/edit#gid=1228405746 has a cleaned up version.)
I considered changing the table structure to markdown, but refrained because that would make it harder to review.
> CLDR-15955 Add constraints for unit IDs

- docs/ldml/tr35.md
Reverts unicode-org/cldr#2365
I didn't notice that it was targeted at main, sigh.
> CLDR-15956 REVERT BCP47 u-extension specification for measurement unit

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-Do not allocate localeNameToFileInfo when unused (!SHOW_SUBTYPES)
-Remove unused peekLocaleStamp (not related to memory problem)
CLDR-15859
> CLDR-15859 Priority Items Summary failure for all locales

- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
PACKAGES.md's readme section was inadvertently written to cldr-packages.json, after that file was closed.
Missed commiting this in a hardware restore, this was already used to create cldr-json
CLDR-15974
> CLDR-15974 json: fix to PACKAGES.md

- common/annotations/bn.xml
- common/annotations/de.xml
- common/annotations/en.xml
- common/annotations/es.xml
- common/annotations/es_419.xml
- common/annotations/es_MX.xml
- common/annotations/es_US.xml
- common/annotations/fr.xml
- common/annotations/fr_CA.xml
- common/annotations/hi.xml
- common/annotations/hi_Latn.xml
- common/annotations/ur.xml
- common/annotations/zh.xml
CLDR-16045
Remove (the equivalents of) Australia, India, Vietnam from annotations for non-globe emoji in selected languages (based on the region names we have in the language). This is just the preliminary manual change for CLDR 42 beta2, a more comprehensive removal using a tool will follow under a different ticket.
Note: besides the emoji we discussed (lotus blossom, kangaroo, boomerang) this was also relevant for some other emoji in some languages:
- sari had a keyword of India in some
- koala bear had a keyword of Australia in some
- om sign had a keyword of India in zh
> CLDR-16045 Remove Australia/India/Vietnam as keywords for non-globe emoji in some langs

- docs/ldml/tr35-info.md
- docs/ldml/tr35.md
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestDtdData.java
- document the invariant against nondistinguishing elements and children
- update the test to link to the docs
- test: add an unreached enum value to the switch statement
CLDR-15618
> CLDR-15618 spec: improve docs about value+children

- docs/ldml/tr35-keyboards.md
Constant sourced from Windows DDK kbd.h (VK_ABNT_C1).
CLDR-15034
> CLDR-15034 tr35-keyboards: add hex constant for ABNT2 key

- docs/ldml/tr35-keyboards.md
- more instances of the <backspace> element and `after=` in the docs to remove
CLDR-15034
> CLDR-15034 kbd: remove backspace element and after

- docs/ldml/tr35.md
- Latest proposed update link should always be: https://www.unicode.org/reports/tr35/proposed.html
- This URL will redirect to the appropriate spot depending on project phase
(cherry picked from commit d33f209bfeaae80bee6c1e8a224bd4b5de2421e6) #2370 
CLDR-16029
> CLDR-16029 doc: update Latest Proposed Update link (maint-41)

- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrSurvey.js
- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyAjax.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/XPathTable.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/PathHeader.java
-Enable Survey Tool to work correctly with TABLE_USES_NEW_API = true
-Keep TABLE_USES_NEW_API = false for now pending further testing
-Make VoteAPI produce json more like DataSection.getRow
-Supply numerous data items that were missing from VoteAPI json
-Remove duplicate VoteResolver in VoteAPI
-Distinguish front-end votingResults from back-end voteResolver
-Lazy initialization of PathHeader alphabetic collator to avoid CLDRConfig conflict
-A few front end changes, no need for displaySets.default; fix getSingleRowUrl; simplify testItem.cause
-Comments
CLDR-15368
> CLDR-15368 Enable API to replace WHAT_GETROW

- docs/ldml/tr35-collation.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35-personNames.md
- docs/ldml/tr35.md
CLDR-16066
FIx LDML 42 spec links (broken or inefficient) per report from W3C checkLink tool (https://validator.w3.org/checklink).
Some of these are just replacing a URL with what it already redirects to, if it is the same or nearest possible result. Many of these are links into our github repo, changing https://github.com/unicode-org/cldr/tree/.... to https://github.com/unicode-org/cldr/blob/...
> CLDR-16066 fix LDML 42 bad links found by W3C checkLink

- tools/cldr-apps/pom.xml
CLDR-15970
Node v16 is the current LTS version.
> CLDR-15970 deps: update Node.js to LTS v16

- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
-Turn on the api, and fix a bug that occured with Jump to Original links
-Front end: set TABLE_USES_NEW_API = true; enhance getPageUrl
-Back end: new getPageFromXpathStringId reproduces old behavior when page name is absent
CLDR-15368
> CLDR-15368 TABLE_USES_NEW_API=true and page/auto

- common/validity/currency.xml
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
re-ran GenerateValidityXml
CLDR-16078
> CLDR-16078 v42: SLE should not be deprecated

- docs/ldml/tr35.md
- readme.html
- tools/pom.xml
CLDR-16080
Before CLDR release-42-beta4:
- Update ICU4J libs to latest from ICU maint/maint-72 branch (with post rc fixes)
- Update some doc dates (readme, spec)
> CLDR-16080 BRS v42: Update ICU4J libs (and some doc dates) before 42-beta4

- tools/cldr-code/src/main/java/org/unicode/cldr/util/VettingViewer.java
-Skip NotificationCategory.changedOldValue due to obsolete hard/soft distinction
CLDR-15054
> CLDR-15054 No Changed notification if oldValue=INHERITANCE_MARKER and value=bailey

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartDtdDelta.java
CLDR-16023
Allows the significant alt values (but kept the suppression of others, to cut down on the noise).
Also added a TSV chart for the data, since that was simple to do and I was right in the code.
The changes in the charts are visible at https://github.com/unicode-org/cldr-staging/pull/63
> CLDR-16023 In DTD delta charts, allow significant alt values

- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/bytype-index.css
(cherry picked from commit b3948345c4f0b0fbd46733906506a830ba58fd81)
CLDR-16086
-Fix in bytype-index.css
Just cherry-picks the CSS change in #2455 (which accidentally went into main branch) to maint/maint-42 branch.
> CLDR-16086 Headers are hidden in new web site color scheme (#2455)

- tools/cldr-code/src/main/java/org/unicode/cldr/util/Annotations.java
CLDR-16091
In Annotations.java it currently does:
```
throw new IllegalArgumentException(
"Did not find exactly one source directory for locale " + locale + " - " +
String.join(" ", dirs.toArray(new String[0])));
}
```
Except dirs is a List<File>.
This code should just add dirs to the string and let toString() do the rest.
> CLDR-16091 Type error in Annotations.java which is harmless but prevents code compiling.

- keyboards/dtd/ldmlKeyboard.dtd
CLDR-15034
The DTD should specify the flick direction regex
> CLDR-15034 kbd: dtd: tighten up the DTD for directions

- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VerifyZones.java
-Move method VerifyZones.metazoneIsOutdated to SupplementalDataInfo
-Use Calendar class (instead of deprecated Date) to get timeInMillis
-Comments
CLDR-16014
> CLDR-16014 Bad link in Zones report, refactoring

- docs/ldml/tr35-collation.md
- docs/ldml/tr35-dates.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35-numbers.md
- docs/ldml/tr35-personNames.md
- docs/ldml/tr35.md
CLDR-16094
* Remove draft next to version number
* Make sure all sections have the approve status line
* Update version that the keyboard spec update is expected to v43
* Update all tables to be markdown tables
> CLDR-16094 Change v42 spec to approved status

- docs/ldml/tr35-numbers.md
CLDR-16094
The markdown header for art 3 numbers was missing the header/body separation row
> CLDR-16094 spec: fix header for numbers part

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrUserLevels.js
- tools/cldr-apps/js/src/views/AddUser.vue
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/UserLevels.java
-Move userlevels request from AddUser.vue to cldrUserLevels.js
-Use session header, not query param s, for api/userlevels
-Do not forbid api/userlevels access since that info is public
-Comments
CLDR-15349
> CLDR-15349 Refactoring related to user levels

- tools/cldr-apps/js/src/esm/cldrTable.js
- tools/cldr-apps/js/src/esm/cldrVote.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
-Remove TABLE_USES_NEW_API and VOTE_USES_NEW_API, now effectively permanently true
-Recognize DAIP reduction to empty string, as it was recognized for WHAT_SUBMIT
-New method VoteAPIHelper.normalizedToZeroLengthError
-Use the string value of json.didNotSubmit when present
-Use boolean json.didVote instead of json.submitResult, which was treated as boolean anyway
-Imitate old json more closely, including testErrors, testWarnings, testResults
-Remove unused json.dataEmpty, json.testsRun
-Fix duplicate cldrRetry.handleDisconnect in cldrVote.js
-Do not assign to unused variable span in cldrVote.js
-Comments
CLDR-15368
> CLDR-15368 Switch WHAT_GETROW/WHAT_SUBMIT to api, corrections, clean up

- tools/cldr-apps/js/src/esm/cldrGui.js
- tools/cldr-apps/js/src/esm/cldrMenu.js
-Revise menubuttons.set in cldrMenu.js
-Set textContent instead of innerHTML to avoid vulnerability warnings
-Sanitize locale code to avoid vulnerability warnings
-Remove unused parameters for two cldrMenu functions
CLDR-10256
> CLDR-10256 ST: clicking on language should go back to the language

- common/dtd/ldml.dtd
- common/dtd/ldmlBCP47.dtd
- common/dtd/ldmlSupplemental.dtd
- docs/ldml/tr35-collation.md
- docs/ldml/tr35-dates.md
- docs/ldml/tr35-general.md
- docs/ldml/tr35-info.md
- docs/ldml/tr35-keyboards.md
- docs/ldml/tr35-numbers.md
- docs/ldml/tr35-personNames.md
- docs/ldml/tr35.md
- keyboards/dtd/ldmlKeyboard.dtd
- pom.xml
- readme.html
- tools/cldr-apps/pom.xml
- tools/cldr-code/pom.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRFile.java
- tools/cldr-rdf/pom.xml
- tools/pom.xml
CLDR-16100
Various things to get set for CLDR 43:
- Update cldrVersion in dtds and GEN_VERSION in CLDRFile.java to 43
- Update CLDR version in pom files to 43.0-SNAPSHOT (and update ICU4J libs to 72.1 release)
- Update CLDR version and status in readme
- Update TR35 for 43: version, draft status, and clear Modification section
> CLDR-16100 SBRS 43: update CLDR version, ICU4J libs, TR35 version and status

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrOrganizations.js
- tools/cldr-apps/js/src/esm/cldrUserLevels.js
- tools/cldr-apps/js/src/views/AddUser.vue
- tools/cldr-apps/js/test/TestCldrAccount.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/UserList.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUser.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/OrgList.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/Organization.java
-New cldrOrganizations.js encapsulates org names on front end
-Sort org display names alphabetically on front end with localeCompare
-List Users and Add User menus are alphabetically sorted by org display name
-List Users sections are alphabetically sorted by org display name
-Fix form-validation problems in AddUser.vue, wait until levels and orgs are loaded
-Fix AddUser.vue, clear errors and warnings when Add Another User
-In cldrAccount.js always get orgs; even for a single org, need short/display mapping
-In cldrAccount.js new setMockLevels, setMockOrgs for unit testing without json from server
-In AddUser.java, use Auth.SESSION_HEADER not query param s
-In OrgList.java, respond with both short and display org names
-In OrgList.java, do not share Organization.special (High Coverage and …
> CLDR-10384 Use display names for Organization menus

- common/dtd/ldmlSupplemental.dtd
CLDR-16102
Fix supplemental version unicodeVersion attribute (FIXED in dtd) to be 15.0.0 to correctly reflect CLDR 42 Unicode version (on maint/maint-42 branch, already fixed on main branch)
> CLDR-16102 Fix supplemental version unicodeVersion attribute to be 15.0.0

- .github/workflows/staging.yml
had `repo` instead of `repository` for the checkout action
CLDR-14878
> CLDR-14878 fix(build): fix action

- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrText.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/DataPage.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPI.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/VoteAPIHelper.java
- tools/cldr-apps/src/main/webapp/surveytool.css
- tools/cldr-code/src/main/java/org/unicode/cldr/util/VoteResolver.java
- for now, include transcript with each row
CLDR-14943
> CLDR-14943 cldrsplain: refactor VoteResolver code, add API

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/STFactory.java
- tools/cldr-apps/src/test/resources/org/unicode/cldr/unittest/web/data/TestSTFactory.xml
-Normalize Bailey value to INHERITANCE_MARKER in STFactory
-New method STFactory.PerLocaleData.processValue, called by voteForValue and loadVoteValues
-For consistency/encapsulation, use DAIP for the normalization
-Fix one test in TestSTFactory.xml that assumed hard vote would persist when bailey changed
CLDR-16105
> CLDR-16105 Inheritance not recognized by PerXPathData

- common/rbnf/pt.xml
CLDR-16077
Apparently due to a copy and paste typo, trillions was misspelled in Brazilian Portuguese. The pt_PT locale is not affected by this issue.
> CLDR-16077 Portuguese spellout-ordinal-masculine for trillion is feminine instead of masculine

- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
- tools/cldr-code/src/test/java/org/unicode/cldr/util/TestCLDRFile.java
-Fix TestCLDRLocaleCoverage/TestLanguageNameCoverage, skip non-basic locales
-Fix TestReadAllDTDs, do not test seed/main
CLDR-6396
> CLDR-6396 Seed and common; fix TestCLDRLocaleCoverage, TestReadAllDTDs

- tools/cldr-apps/js/src/esm/cldrAccount.js
- tools/cldr-apps/js/src/esm/cldrForumPanel.js
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/SurveyForum.java
-New method SurveyForum.gatherUsersInterestedInThread
-Rename gatherInterestedUsers to gatherUsersInterestedInLocale
-Parameter PostInfo in emailNotify, used for gatherUsersInterestedInThread, also reduces parameters
-Simplify and speed up by replacing getFirstPosterInThread with getUserId(postInfo.getRoot())
-Use logger.severe instead of deprecated SurveyLog.errln
-Fix bug in cldrAccount.js, needed return in getInterestLocalesUrl
-Fix bug in cldrForumPanel.js, in exceptional case content is not const
-Comments
CLDR-11228
> CLDR-11228 ST: notify TC of forum responses; notify

- tools/cldr-apps/js/src/esm/cldrForum.js
-Simplify cldrForum.appendPostDivsToTopicDivs to facilitate modernization
-Boolean constants SIMPLE_REPLY_STYLE and USE_HORIZONTAL_RULE were left over from very old changes, enabling reversion to obsolete behavior
CLDR-11228
> CLDR-11228 forum; follow-up simplification

- tools/cldr-apps/js/src/esm/cldrForumPanel.js
- tools/cldr-apps/js/src/esm/cldrInfo.js
- tools/cldr-apps/js/src/esm/cldrLoad.js
- tools/cldr-apps/js/src/esm/cldrSideways.js
- tools/cldr-apps/js/src/esm/cldrTable.js
-Shorten and modularize cldrForumPanel.loadInfo by moving code into new methods
-Change some nested methods to top-level methods
-New cldrSideways.js contains menu code unrelated to forum
-In loadAllRows, only show guidance message if there is no current id (otherwise it was immediately replaced)
-Comments
CLDR-14045
> CLDR-14045 Forum in Info Panel, preliminary refactoring

- common/main/be.xml
- common/main/el.xml
- common/main/en.xml
- common/main/he.xml
- common/main/mn.xml
- common/main/ne.xml
- common/main/ps.xml
- common/main/yue_Hans.xml
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPersonNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
CLDR-16135
This cleans up the last part of the previous PR, and also enables the script check.
There was a small change in CheckPlaceHolders to allow surname2 if either the surname or surname-core is present (since we treat those as equivalent if there is no surname-prefix).
> CLDR-16135 Cleanup for sample names

- tools/cldr-code/src/main/java/org/unicode/cldr/tool/Chart.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonName.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartPersonNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/FormattedFileWriter.java
- tools/cldr-code/src/main/resources/org/unicode/cldr/tool/index.css
CLDR-16159
Note: This won't be complete until it is wired up to the Survey Tool. It uses the current Chart infrastructure, so it also adds charts for all the languages with person names. See https://github.com/unicode-org/cldr-staging/tree/main/docs/charts/43/personNames for those results.
It is separated into two main files to make the logic easier to see, and to allow calling ChartPersonName.java independently, eg from the ST back end. There is a little stub to show how this can be done in the main(), but there will probably be some other changes necessary.
There are some small changes to Chart.java and FormattedFileWriter.java, and to the index.css (to fix padding).
> CLDR-16159 Report for person names

- tools/cldr-code/src/main/java/org/unicode/cldr/test/SubmissionLocales.java
- tools/cldr-code/src/test/java/org/unicode/cldr/test/TestSubmissionLocales.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckCLDR.java
- tools/cldr-code/src/test/resources/org/unicode/cldr/test/TestSubmissionLocales.csv
CLDR-16140
- re-enable non-grammar locales (`zh`, `ja`)
- add .csv-driven test for submission locales
> CLDR-16140 re-enable non-grammar locales, limited data driven-test

- tools/cldr-apps/js/src/views/DashboardWidget.vue
- tools/cldr-apps/js/src/views/InfoPanel.vue
CLDR-16141
- two spots, use ✕ instead of X
Followup to CLDR-13837
> CLDR-16141 use multiplication sign instead of X

- tools/cldr-apps/src/main/java/org/unicode/cldr/web/OutputFileManager.java
- tools/cldr-apps/src/main/java/org/unicode/cldr/web/api/AddUser.java
- tools/cldr-code/src/main/java/org/unicode/cldr/json/Ldml2JsonConverter.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CLDRTest.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckCoverage.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/CheckPlaceHolders.java
- tools/cldr-code/src/main/java/org/unicode/cldr/test/DisplayAndInputProcessor.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ChartLanguageGroups.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateDerivedAnnotations.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/GenerateMaximalLocales.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowLocaleCoverage.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/ShowStarredCoverage.java
- tools/cldr-code/src/main/java/org/unicode/cldr/tool/SimpleLocaleParser.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRConfig.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/CLDRLocale.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/DayPeriodsCheck.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LanguageInfo.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/LocaleNames.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/StandardCodes.java
- tools/cldr-code/src/main/java/org/unicode/cldr/util/SupplementalDataInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/LanguageInfoTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/StandardCodesTest.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCLDRLocaleCoverage.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestCheckWidths.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestPersonNameFormatter.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestSupplementalInfo.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestUtilities.java
- tools/cldr-code/src/test/java/org/unicode/cldr/unittest/TestValidity.java
- tools/cldr-rdf/src/main/java/org/unicode/cldr/tool/GenerateLanguageContainment.java
-New class LocaleNames has constants MIS, MUL, ROOT, UND, ZXX
CLDR-15187
> CLDR-15187 Encapsulate locale name constants for mis, mul, root, und, zxx
